### ISSUE TITLE
Excitement!

### ISSUE THREAD

**Issue by faceleg** [Shougo/deoplete.nvim#1]

**Comment by ZyX-I** [comment]
Why?

**Comment by faceleg** [comment]
Is this not the repo placeholder for Shougo's completion plugin for neovim?

**Comment by Shougo** [comment]
Thanks.  But to develop it, neovim must implement lua plugin feature.

https://github.com/neovim/neovim/issues/1512

**Comment by Shougo** [comment]
I will develop it.  Because, I use if_python3 for development...

**Comment by marlun** [comment]
@Shougo How is the performance of python3 compared to lua? Just curious since you said using lua in neocomplete was such an increase in peformance compared to neocomplcache.

**Comment by Shougo** [comment]
> How is the performance of python3 compared to lua?

Python3 is 2~3 times slower than Lua.
But it is faster than VimL.

I think the performance is not problem.
Because, I will create asynchronous completion plugin.
