### ISSUE TITLE
Use 'kind' instead of 'menu' for the completion data

### ISSUE THREAD

**Issue by fmoralesc** [Shougo/deoplete.nvim#10]
In https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L117-L118, I think it should be
~~~ python
                if not 'kind' in candidate:
                    candidate['kind'] = source.mark
~~~
And then `self.mark` should be adjusted in the sources.

**Comment by Shougo** [comment]
Why?  Please describe it.

**Comment by fmoralesc** [comment]
It is designed for this purpose of showing which kind of completion is being used to provide the completion suggestion, and you might want to use the 'menu' keyword for something else later. See `:help complete-items|`:

~~~
	word		the text that will be inserted, mandatory
	abbr		abbreviation of "word"; when not empty it is used in
			the menu instead of "word"
	menu		extra text for the popup menu, displayed after "word"
			or "abbr"
	info		more information about the item, can be displayed in a
			preview window
	kind		single letter indicating the type of completion
~~~
'kind' is displayed similarly to 'menu' after the 'word' text.

**Comment by Shougo** [comment]
OK.  But the "kind" is used for tags or vim completion menu in neocomplete.
I don't think it should be sources type.
