### ISSUE TITLE
Tabbing Moves From Bottom Up

### ISSUE THREAD

**Issue by westlywright** [Shougo/deoplete.nvim#100]
Tabbing through the auto complete options happens from the bottom up. Screen shots show the movement happen from top down. I do not see a way to change this. Possibly add an option? 

OS: OSX 10.11.2
NVIM: v0.1.1-15-g81960df

**Comment by hassan-k** [comment]
tabbing needs to be mapped. The default behaviour is `CTRL-N` to cycle forward (from top) and `CTRL-P` to cycle backwards (from bottom).

here is the mapping I use (I think I got it from Shougo's neocomplete README)

```
" use tab to forward cycle
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
" use tab to backword cycle
inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"
```

**Comment by westlywright** [comment]
@hassan-k thanks i'll give this a shot

**Comment by eldamir** [comment]
thanks @hassan-k :+1:

**Comment by wsdjeg** [comment]
@westlywright @Shougo move selection  from the bottom up or from top down,I think it is feature of vim ,you can use ctrl+p or Ctrl + n ,also imap anything you like,it is not the business of deoplete,It is just my own opinion

**Comment by JulioJu** [comment]
@Shougo maybe it's intersting to give this information in doc/deoplete.txt ? And inform do not use plugins as SuperTab ?

**Comment by Shougo** [comment]
> maybe it's intersting to give this information in doc/deoplete.txt ?

It is already added.

```
		inoremap <silent><expr> <TAB>
		\ pumvisible() ? "\<C-n>" :
		\ <SID>check_back_space() ? "\<TAB>" :
		\ deoplete#mappings#manual_complete()
		function! s:check_back_space() abort "{{{
		let col = col('.') - 1
		return !col || getline('.')[col - 1]  =~ '\s'
		endfunction"}}}
```

>  And inform do not use plugins as SuperTab ?

I don't want to inform it.
