### ISSUE TITLE
v:completed_item fields are limited to 2/3 the width of the current window

### ISSUE THREAD

**Issue by Chase-C** [Shougo/deoplete.nvim#1002]
# Problems summary
The `v:completed_item` variable contains important information about the selected completion item, but all of its fields are truncated by deoplete so that they are at most the 2/3 the width of the current window.

These limits are set in this function: https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/context.py#L27

Most important and likely to be truncated are the  `info` and `menu` fields of `v:completed_item`.

The `info` field usually contains a description of the completed item that may be longer that the allowed width despite typically being shown in the preview window (which can wrap the text).

The `menu` field is trickier because it contains text that is displayed by deoplete in the pop-up menu, but it may also be used by plugins like `EchoDoc` that rely on it not being truncated.

## Expected
The fields in the `v:completed_item` variable (at least `info` and `menu`) are untruncated and contain all the information provided by the completion source.

## Environment Information

 * deoplete version (SHA1): `bb2b163`

 * OS: Arch Linux

 * neovim/Vim `:version` output: `NVIM v0.3.8`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
## deoplete.nvim
 - OK: exists("v:t_list") was successful
 - OK: has("timers") was successful
 - OK: has("python3") was successful
 - OK: Require Python3.6.1+ was successful
 - INFO: If you're still having problems, try the following commands:
   $ export NVIM_PYTHON_LOG_FILE=/tmp/log
   $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
   $ nvim
   $ cat /tmp/log_{PID}
   and then create an issue on github
```

## How to reproduce the problem from neovim/Vim startup

 1. Setup deoplete with `tsserver` as a completion source (I'm using ALE)
 2. Open a typescript file (may be empty)
 3. Resize window so its width is less than about 80 characters
 4. Activate completion for `Function.bind`
 5. `:echo v:completed_item`
 6. The `menu` and `info` fields will be truncated to around 50 characters.

## Screenshot
https://imgur.com/UEWctV4

**Comment by Shougo** [comment]
Please read the documentation.
The feature is already documented.

```vim
call deoplete#custom#source('_', 'max_menu_width', 0)
call deoplete#custom#source('_', 'max_info_width', 0)
```
