### ISSUE TITLE
Async `feedkeys()` brokes IME input (on Windows)

### ISSUE THREAD

**Issue by Milly** [Shougo/deoplete.nvim#1003]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Async `feedkeys()` brokes IME input.

## Expected
Do not brokes IME input.

## Environment Information

 * deoplete version (SHA1):
bb2b16309b94695a3344c713282368b3329a2412

 * OS:
Windows 10

 * neovim/Vim `:version` output:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jun  1 2019 13:52:50)
MS-Windows 64 ビット GUI/コンソール 版
適用済パッチ: 1-1436
Modified by koron.kaoriya@gmail.com
Compiled by koron.kaoriya@gmail.com
Huge 版 with GUI.  機能の一覧 有効(+)/無効(-)
+acl                +cindent            +cursorshape        -farsi              +job                +lua/dyn            +num64              +quickfix           +tag_binary         +title              +wildignore
+arabic             +clientserver       +dialog_con_gui     +file_in_path       +jumplist           +menu               -ole                +reltime            -tag_old_static     +toolbar            +wildmenu
+autocmd            +clipboard          +diff               +find_in_path       +kaoriya            +migemo/dyn         +packages           +rightleft          -tag_any_white      +user_commands      +windows
+autochdir          +cmdline_compl      +digraphs           +float              +keymap             +mksession          +path_extra         +ruby/dyn           -tcl                +vartabs            +writebackup
+autoservername     +cmdline_hist       +directx            +folding            +lambda             +modify_fname       +perl/dyn           +scrollbind         +termguicolors      +vertsplit          -xfontset
+balloon_eval       +cmdline_info       -dnd                -footer             +langmap            +mouse              +persistent_undo    +signs              +terminal           +virtualedit        -xim
+balloon_eval_term  +comments           -ebcdic             +gettext/dyn        +libcall            +mouseshape         -postscript         +smartindent        -termresponse       +visual             +xpm_w32
+browse             +conceal            +emacs_tags         +guess_encode       +linebreak          +multi_byte_ime/dyn +printer            +startuptime        +textobjects        +visualextra        -xterm_save
++builtin_terms     +cryptv             +eval               -hangul_input       +lispindent         +multi_lang         +profile            +statusline         +textprop           +viminfo            
+byte_offset        +cscope             +ex_extra           +iconv/dyn          +listcmds           -mzscheme           +python/dyn         -sun_workshop       -tgetent            +vreplace           
+channel            +cursorbind         +extra_search       +insert_expand      +localmap           +netbeans_intg      +python3/dyn        +syntax             +timers             +vtp                
      システム vimrc: "$VIM\vimrc"
      ユーザー vimrc: "$HOME\_vimrc"
   第2ユーザー vimrc: "$HOME\vimfiles\vimrc"
   第3ユーザー vimrc: "$VIM\_vimrc"
       ユーザー exrc: "$HOME\_exrc"
    第2ユーザー exrc: "$VIM\_exrc"
     システム gvimrc: "$VIM\gvimrc"
     ユーザー gvimrc: "$HOME\_gvimrc"
  第2ユーザー gvimrc: "$HOME\vimfiles\gvimrc"
  第3ユーザー gvimrc: "$VIM\_gvimrc"
  デフォルトファイル: "$VIMRUNTIME\defaults.vim"
    システムメニュー: "$VIMRUNTIME\menu.vim"
コンパイル: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL -DFEAT_NETBEANS_INTG -DFEAT_JOB_CHANNEL   -DFEAT_XPM_W32  /DMODIFIED_BY=\"koron.kaoriya@gmail.com\" /DDYNAMIC_MSVCRT_DLL=\"msvcr100.dll\" /DGETTEXT_DLL=\"intl.dll\" /DGETTEXT_DLL_ALT=\"intl.dll\" /D_BIND_TO_CURRENT_VCLIBS_VERSION=1 -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /MD -DVIMDLL -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_GUI_MSWIN -DFEAT_DIRECTX -DDYNAMIC_DIRECTX -DFEAT_DIRECTX_COLOR_EMOJI -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DDYNAMIC_MIGEMO -DFEAT_LUA -DDYNAMIC_LUA -DDYNAMIC_LUA_DLL=\"lua51.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python37.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl528.dll\" -DFEAT_RUBY -DDYNAMIC_RUBY -DDYNAMIC_RUBY_VER=26 -DDYNAMIC_RUBY_DLL=\"x64-msvcrt-ruby260.dll\" -DFEAT_HUGE /Fd.\ObjDXULYHRVAMD64/ /Zi
リンク: link  /nologo /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib netapi32.lib uuid.lib /machine:AMD64 gdi32.lib version.lib   winspool.lib comctl32.lib advapi32.lib shell32.lib netapi32.lib  /machine:AMD64 /nodefaultlib msvcrt.lib  user32.lib  /nodefaultlib:lua51.lib   /nodefaultlib:python27.lib /nodefaultlib:python37.lib    WSock32.lib ..\..\build\msvc\target\install-x64\lib\libXpm.lib /PDB:vim64.pdb -debug

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set encoding=utf-8
set nocompatible
set runtimepath+=C:\path\to\deoplete.nvim
let g:deoplete#enable_at_startup = 1
set runtimepath+=C:\path\to\nvim-yarp
set runtimepath+=C:\path\to\vim-hug-neovim-rpc
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `gvim -u init.vim -U NONE`
 2. input these:

        foobar
        fooqux
        fooあ

 3. When "あ" is undetermind IME input, it will be determind (by `feedkeys()`.)

## Screenshot (if possible)
![deoplete-feedkeys-brokes-IME-input-01](https://user-images.githubusercontent.com/22977/63322657-e94d2500-c35e-11e9-9c39-677ec1617fb4.png)
![deoplete-feedkeys-brokes-IME-input-02](https://user-images.githubusercontent.com/22977/63322667-ece0ac00-c35e-11e9-9bdb-714610cb5e3a.png)

**Comment by Milly** [comment]
I tried the following, the IME was not broken.
(But, I do not know how to fix it correctly.)

```diff
diff --git a/autoload/deoplete/handler.vim b/autoload/deoplete/handler.vim
index e7c94b9..37d25b6 100644
--- a/autoload/deoplete/handler.vim
+++ b/autoload/deoplete/handler.vim
@@ -71,7 +71,7 @@ function! deoplete#handler#_do_complete() abort
     call deoplete#mapping#_set_completeopt()
   endif
 
-  call feedkeys("\<Plug>_", 'i')
+  call deoplete#mapping#_complete()
 endfunction
 
 function! deoplete#handler#_check_omnifunc(context) abort
@@ -162,7 +162,7 @@ function! s:check_prev_completion(event) abort
         \ 'complete_position': prev.complete_position,
         \ 'candidates': candidates,
         \ }
-  call feedkeys("\<Plug>+", 'i')
+  call deoplete#mapping#_prev_complete()
 endfunction
 
 function! deoplete#handler#_async_timer_start() abort
```

**Comment by Shougo** [comment]
Thanks.  It seems better.

**Comment by Shougo** [comment]
@Milly 

https://github.com/Shougo/deoplete.nvim/issues/1003#issuecomment-522878428

You should not remove `feedkeys()`.
It causes many many problems.

**Comment by Milly** [comment]
I can't come up with a solution.

**Comment by Shougo** [comment]
I have added iminsert check in latest HEAD.
Please test deoplete latest.

**Comment by Milly** [comment]
It has not been solved.
When `set iminsert=0` and IME turned on by manually, the problem is appears.

* `iminsert` is a mechanism for controlling IME state from Vim, not get the state of IME.
* If `imstatusfunc` is set correctly, can use it. But it is usually set to empty.

Unfortunately there is no way to get IME state from Vim (unless the external program).
So it is difficult to solve this.
If IME state changed event is implemented in Vim, it may be resolved.

**Comment by Shougo** [comment]
OK.  So I cannot fix it in deoplete side.

**Comment by Shougo** [comment]
I have added `getimstatus()` support.
