### ISSUE TITLE
Add support for calling LSP completionItem/resolve implementation when completion items are selected

### ISSUE THREAD

**Issue by wincent** [Shougo/deoplete.nvim#1004]
Looking at the LSP spec, I see [this](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion) (emphasis added):

>  If computing full completion items is expensive, servers can additionally provide a handler for the completion item resolve request (‘completionItem/resolve’). This request is sent when a completion item is selected in the user interface. **A typical use case is for example: the ‘textDocument/completion’ request doesn’t fill in the documentation property** for returned completion items since it is expensive to compute. **When the item is selected in the user interface then a ‘completionItem/resolve’ request is sent** with the selected completion item as a parameter. The returned completion item should have the documentation property filled in.

To this effect, LanguageClient-neovim [implemented](https://github.com/autozimu/LanguageClient-neovim/pull/514) a `LanguageClient#completionItem_resolve()` function that can be called to get additional information about a completion. The obvious use-case here is to show info about the selection completing in a preview window (or floating window).

As far as I can tell, LanguageClient-neovim sets its `LanguageClient#complete()` function as the `'omnifunc'`, and deoplete calls that to get completions. But when you move through completions, deoplete doesn't call `LanguageClient#completionItem_resolve()` and so doesn't get the extra info that an LSP server might provide. One such example server would be [typescript-language-server](https://github.com/theia-ide/typescript-language-server), which doesn't provide extended information for `textDocument/completion` requests, but does implement `completionItem/resolve`.

So this is really a feature request. Could we have an option to make deoplete call an LSP `completionItem/resolve` function when completion items are selected? This means that `'completopt=preview'` would be more useful, because it would have information to show about selected completions in more cases. coc.nvim [implements this](https://github.com/neoclide/coc.nvim/blob/3e0eec9c4f08003304ba4d50bb0866dbaf7cc707/src/provider/index.ts#L40-L52), in case you wanted to check out what they're doing.

**Comment by Shougo** [comment]
It is not deoplete's work.

LanguageClient-neovim should use `:help CompleteChanged`.

**Comment by wincent** [comment]
Ok @Shougo; I opened an issue over in the LanguageClient-neovim repo: https://github.com/autozimu/LanguageClient-neovim/issues/875
