### ISSUE TITLE
max number of candidates in menu

### ISSUE THREAD

**Issue by tex** [Shougo/deoplete.nvim#1005]
Hi Shougo,

how can we set maximum number of candidates shown in deoplete menu?

I am not asking about `max_candidates` which does something else than I want - it limits number of candidates returned per source. I want to get all candidates from all configured sources but set height of that deoplete menu so it does not overlaps over whole screen and other info shown by deoplete...

**Comment by tex** [comment]
Answer is `pumheight`.

**Comment by Shougo** [comment]
Yes.
