### ISSUE TITLE
How to change show order?

### ISSUE THREAD

**Issue by dcy** [Shougo/deoplete.nvim#1009]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
![DeepinScreenshot_select-area_20190826162312](https://user-images.githubusercontent.com/1137238/63676893-7e985f80-c81e-11e9-96aa-ea57760bf230.png)
Tabnine(TN) is the first position in default order.

## Expected
[Go] for golang(xx.go) in the first position.
[Go] -> [TN] -> [B]

**Comment by Shougo** [comment]
https://github.com/tbodt/deoplete-tabnine/issues/5
