### ISSUE TITLE
Insertion of completion is wrong (example: a.foo(int x) -> void)

### ISSUE THREAD

**Issue by MarkGreeny** [Shougo/deoplete.nvim#1010]
# Problems summary

See the image bellow

![image](https://user-images.githubusercontent.com/40479001/64020273-7ea3a280-cb31-11e9-903f-6ad913418ce9.png)

Another example

![image](https://user-images.githubusercontent.com/40479001/64020851-ee665d00-cb32-11e9-87cb-52e40c911801.png)

I am using deoplete in conjuction with languageClient-neovim. My language server is ccls.

## Expected

Only the name of the field, or the method to be inserted, not the types aswell.

## Environment Information

 * deoplete version (SHA1): latest (updated before creating the issue)

 * OS: Ubuntu 19.04

 * neovim/Vim `:version` output: v0.3.8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

### deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python3.6.1+ was successful

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
"deoplete
let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

"this enables large modules to load before timeout (tf,np)
let g:deoplete#sources#jedi#server_timeout=50
```

## Separate question, not worthy of its own issue

In the images above, what are the `[L]` entries in the completion list? How to disable them?

**Comment by MarkGreeny** [comment]
This seems to be a bug of leanguageClient neovim, as other users are reporting it.

**Comment by Shougo** [comment]
Yes.  It is not deoplete problem.
