### ISSUE TITLE
How do I write a unit test for deoplete source?

### ISSUE THREAD

**Issue by lighttiger2505** [Shougo/deoplete.nvim#1012]
Thank you for creating a cool plugin.

I have a question.

# Question

I am making a deoplete source and am trying to add UT to improve the quality of the source.
However, to write a unit test of source that inherits the deoplete base class, I need to add the deoplete base class to the source code.

I thought about using git submodule to import the base class into my repository,
The deoplete source cannot be imported because it must be placed under the deoplete package.

Can you tell me how to write a source unit test?

**Comment by Shougo** [comment]
If so, you should use patch feature in mock.

https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch

It can replace deoplete base class to mock.
