### ISSUE TITLE
Correct Keys for Moving in popup dialog

### ISSUE THREAD

**Issue by Kennith-eng** [Shougo/deoplete.nvim#1014]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I can't select an auto complete option

## Expected

I expect to be able to make selection

Should there be some information in the README about how to move around the popup dialog?

Once the auto complete dialog has presented itsself, how can you move down the list to select one?

**Comment by Shougo** [comment]
It is not deoplete's issue.
Because, popup window key mappings are Vim's feature.

`:help popupmenu-keys`, `:help popupmenu-completion`
