### ISSUE TITLE
Open to changing Clojure keyword_patterns?

### ISSUE THREAD

**Issue by Olical** [Shougo/deoplete.nvim#1015]
Hi there! One of the main Clojure + Vim completion tools, [async-clj-omni](https://github.com/clojure-vim/async-clj-omni), has been recommending the following configuration to improve Deoplete + Vim + Clojure for some years now.

```vim
let g:deoplete#keyword_patterns = {}
let g:deoplete#keyword_patterns.clojure = '[\w!$%&*+/:<=>?@\^_~\-\.#]*'
```

I've been using the following in my dotfiles for years using the new config framework functions.

```vim
call deoplete#custom#option('keyword_patterns', {'clojure': '[\w!$%&*+/:<=>?@\^_~\-\.#]*'}) 
```

I was just wondering if you'd be open to changing the Clojure defaults to these values? That's if there are any language defaults for Deoplete... I couldn't actually find them.

I only bring this up because, as a Clojure tool author ([Conjure](https://github.com/Olical/conjure)) I have built in integration with Deoplete. Essentially every Clojure autocomplete in Vim developer tries to get their users to set this configuration, it makes Deoplete + Clojure work so much better.

If you have no framework for this kind of default or you're not happy with the change I totally understand. I'm happy to make the change, I just wanted to ask you about this before doing anything :slightly_smiling_face:

I hope you're having a great weekend so far!

**Comment by Shougo** [comment]
> I was just wondering if you'd be open to changing the Clojure defaults to these values? 

No.  I don't add default patterns anymore.
I think users should set default values themselves.

> If you have no framework for this kind of default or you're not happy with the change I totally understand. I'm happy to make the change, I just wanted to ask you about this before doing anything

If you want to set the default value in plugin, you should add plugin's option instead.

**Comment by Olical** [comment]
Okay, noted, thanks a lot! 😊

**Comment by Shougo** [comment]
In neocomplete.vim, I have defined may keyword patterns.
But I have quit it in deoplete.
