### ISSUE TITLE
Moving cursor in preview

### ISSUE THREAD

**Issue by mohitleo9** [Shougo/deoplete.nvim#102]
Hey,
I I have completeopt set to menuone,longest,preview. 
the problem is that when I try to tab through the completion options, my cursor moves to preview window for a second sometimes and then comes back to the current position. I find it pretty annoying, I was wondering why is this happening?

**Comment by Shougo** [comment]
Unfortunately, it is Vim's feature.
I cannot fix it.
I don't recommend to use the preview feature.
