### ISSUE TITLE
deoplete not working on windows

### ISSUE THREAD

**Issue by ycxiu01** [Shougo/deoplete.nvim#1022]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When calling deoplete#toggle() to start deoplete,  won't start and shows error:
timeout estalishing channel for 'd:\Python36\python3.exe'.'-u'.'~\.vim\bundle\nvim-yarp\pythonx\yarp.py'.'127.0.0.1:51599'.2.'deoplete'

## Expected
start normally

## Environment Information

 * deoplete version (SHA1):
installed with Vundle on Sep 16,2019

 * OS:
window10 x64
with 32bit Vim 8.1, 32bit python36

 * neovim/Vim `:version` output:
VIM - Vi IMproved 8.1 (2018 May 18, compiled May 18 2018 18:26:56)
MS-Windows 32bit 
including patch: 1
+acl               +eval              -mouseshape        -tag_any_white
+arabic            +ex_extra          +multi_byte        -tcl
+autocmd           +extra_search      +multi_lang        +termguicolors
+autoservername    +farsi             -mzscheme          +terminal
-balloon_eval      +file_in_path      -netbeans_intg     -tgetent
+balloon_eval_term +find_in_path      +num64             -termresponse
-browse            +float             +packages          +textobjects
++builtin_terms    +folding           +path_extra        +timers
+byte_offset       -footer            -perl              +title
+channel           +gettext/dyn       +persistent_undo   -toolbar
+cindent           -hangul_input      -postscript        +user_commands
+clientserver      +iconv/dyn         +printer           +vertsplit
+clipboard         +insert_expand     +profile           +virtualedit
+cmdline_compl     +job               -python            +visual
+cmdline_hist      +jumplist          -python3           +visualextra
+cmdline_info      +keymap            +quickfix          +viminfo
+comments          +lambda            +reltime           +vreplace
+conceal           +langmap           +rightleft         +vtp
+cryptv            +libcall           -ruby              +wildignore
+cscope            +linebreak         +scrollbind        +wildmenu
+cursorbind        +lispindent        +signs             +windows
+cursorshape       +listcmds          +smartindent       +writebackup
+dialog_con        +localmap          +startuptime       -xfontset
+diff              -lua               +statusline        -xim
+digraphs          +menu              -sun_workshop      -xpm_w32
-dnd               +mksession         +syntax            -xterm_save
-ebcdic            +modify_fname      +tag_binary        
+emacs_tags        +mouse             +tag_old_static    

cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG /arch:IA32 /Zl /MT -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_HUGE /Fd.\ObjCi386/ /Zi
link  /nologo /subsystem:console,5.01 /opt:ref /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:i386   libcmt.lib  user32.lib          WSock32.lib  /PDB:vim.pdb -debug

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/.vim/bundle/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

" For Vim only
"set runtimepath+=~/.vim/bundle/nvim-yarp/
"set runtimepath+=~/.vim/bundle/vim-hug-neovim-rpc/
```

## How to reproduce the problem from neovim/Vim startup (Required!)
:call deoplete#toggle()

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/7941574/65407180-4c295480-de14-11e9-83d5-590e5b772677.png)

## My question:
I've debugged yarp.py in pycharm. It ends in asyncio->windows_event.py->_overlapped.GetQueueCompletionStatus. Could it be I'm using 32bit python36 on 64bit Windows so that  _overlapped.pyd missing some win dll?

**Comment by Shougo** [comment]
I think you use proxy for internet connecting.
You must disable proxy for 127.0.0.1.

**Comment by ycxiu01** [comment]
I've reinstalled all related software to 64bit and also forbid proxy 127.0.0.1. It's working now.

**Comment by Shougo** [comment]
OK.
