### ISSUE TITLE
deoplete completion is blink

### ISSUE THREAD

**Issue by JoveYu** [Shougo/deoplete.nvim#1031]
# Problems summary
completion  reset when input a new char, even if this char is correct, and the completion is blink

## Expected
deoplete can cache the previous completion. if new char is in last completion then use cached completion.
or
use cached completion before new engine completion

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set runtimepath+=~/.cache/dein/repos/github.com/deoplete-plugins/deoplete-go
let g:deoplete#enable_at_startup = 1
```

## Screenshot (if possible)
[![asciicast](https://asciinema.org/a/276668.svg)](https://asciinema.org/a/276668)

**Comment by Shougo** [comment]
You can disable `refresh_always` option.

```vim
	call deoplete#custom#option('refresh_always', v:false)
```
