### ISSUE TITLE
Add new deoplete plugin deoplete-wp-hooks

### ISSUE THREAD

**Issue by Mte90** [Shougo/deoplete.nvim#1033]
I saw the wiki and doc.txt but is not explained about how to add a new plugin to the list.

I did yesterday a new plugin (my first for Vim) about WordPress and hooks https://github.com/Mte90/deoplete-wp-hooks.

It was not very easy to understand how to do a plugin because there isn't like a tutorial or a boilerplate with all the parameters so looking at the code of other plugins and deoplete I did it.

I share also here to get feedback about how to do it better, basically check if the funciton on writing it is about a filter or action and use the relative JSON file to look on that.

**Comment by Shougo** [comment]
Thank you,

Can you edit the wiki by https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources?

You can clone the wiki instead though.

**Comment by Shougo** [comment]
Or please upload the description.
I can edit the list.

**Comment by Mte90** [comment]
I will do it but one of the most biggest issues I had is how to refresh Vim to test the changes I did to my plugin.
I had to close and restart vim because a refresh of the vim.rc wasn't enough.
So a guide about how do develop one will be not bad.

**Comment by Shougo** [comment]
> I will do it but one of the most biggest issues I had is how to refresh Vim to test the changes I did to my plugin.

I refresh Vim to test the changes.

> I had to close and restart vim because a refresh of the vim.rc wasn't enough.

Yes. You need to restart Vim repeatedly.

I restart Vim to test plugins.  It is my daily task.

**Comment by Shougo** [comment]
So, no magic for it.
