### ISSUE TITLE
deoplete.nvim & neosnippet.vim: Python: "SystemError: Parent module 'deoplete.source' not loaded, cannot perform relative import"

### ISSUE THREAD

**Issue by hyperslv** [Shougo/deoplete.nvim#1034]
Hi Shougo

Could you take a look at this issue which I guess in deoplete.nvim and neosnippet.vim interaction?
I minimized my init.vim but was not able to fit into 50 lines due to I cannt imagine how neosnippet.vim should be installed manully.
I use only your plugins and their default configuration in this setup.
Please, help!
Thanks, Slava

## Problems summary
When open a file got the following error message:
[deoplete] Traceback (most recent call last):
  File "C:\Users\slv\AppData\Local\nvim\dein_inst_dir\.cache\init.vim\.dein\rplugin\python3\deoplete\child.py", line 103, in _add_source
    Source = import_plugin(path, 'source', 'Source')
  File "C:\Users\slv\AppData\Local\nvim\dein_inst_dir\.cache\init.vim\.dein\rplugin\python3\deoplete\util.py", line 69, in import_plugin
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:/Users/slv/AppData/Local/nvim/dein_inst_dir/.cache/init.vim/.dein\rplugin\python3\deoplete\sources\neosnippet.py", line 8, in <module>
    from .base import Base
SystemError: Parent module 'deoplete.source' not loaded, cannot perform relative import
Could not load source: C:/Users/slv/AppData/Local/nvim/dein_inst_dir/.cache/init.vim/.dein\rplugin\python3\deoplete\sources\neosnippet.py.

## Expected
No errors

## Environment Information

 * Plugins version:
Shougo\deoplete.nvim> commit ff09a7ab58e5271053c59825895d607316657023
Shougo\neosnippet.vim>commit 037b7a76f28d51c126de43fb88f01b592193c835
Shougo\neosnippet-snippets> commit f38f1732e4bb0643b3019b5b733a87f5f03ea348
Shougo\dein.vim> commit 7ea274e3582710b7d6476270c8050c4db277e818

 * OS:
OS Name:                   Microsoft Windows 7 Professional
OS Version:                6.1.7601 Service Pack 1 Build 7601
System Type:              x64-based PC

 * neovim/Vim `:version` output:
(downloaded from: https://github.com/neovim/neovim/releases/download/v0.4.2/nvim-win64.zip)

NVIM v0.4.2
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/nvim-deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled appveyor@APPVYR-WIN

Features: -acl +iconv +tui
See ":help feature-compile"

            system vimrc: "$VIM\sysinit.vim"
            $VIM by default: "C:/Program Files/nvim/share/nvim"

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Program Files\Python36\python.EXE is Python 3.6 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: C:\Program Files\Python36\python3.EXE
  - INFO: Other python executable: C:/Program Files/Python36/python3
  - INFO: Other python executable: /python3
  - INFO: Python version: 3.6.2

  - INFO: pynvim version: 0.3.2

  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
"dein Scripts >>>>>>>>>>>>>>>>>>>>>>>>>>>>
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=C:/Users/slv/AppData/Local/nvim/dein_inst_dir
" Required:
if dein#load_state('C:/Users/slv/AppData/Local/nvim/dein_inst_dir')
  call dein#begin('C:/Users/slv/AppData/Local/nvim/dein_inst_dir')

  " Let dein manage dein
  " Required:
  call dein#add('C:/Users/slv/AppData/Local/nvim/dein_inst_dir/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable
"dein Scripts <<<<<<<<<<<<<<<<<<<<<<<<<<<<

"deoplete config >>>>>>>>>>>>>>>>>>>>>>>>>
let g:deoplete#enable_at_startup = 1
"deoplete config <<<<<<<<<<<<<<<<<<<<<<<<<

"neosnippet.vim config >>>>>>>>>>>>>>>>>>>
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <expr><TAB>
" \ pumvisible() ? "\<C-n>" :
" \ neosnippet#expandable_or_jumpable() ?
" \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
"neosnippet.vim config <<<<<<<<<<<<<<<<<<<

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Start nvim-qt
 2. open the init.vim file

## Generate a logfile if appropriate
 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
-- These did not generate any logs

## Screenshot (if possible)

![deoplete](https://user-images.githubusercontent.com/57301860/68084679-dfa96880-fe49-11e9-90b9-485d3330bb37.png)

**Comment by hyperslv** [comment]
Shougo
One more comment: I checked on Ubuntu - no issue.
But I really appreciate if you are able to help since my second PC is Windows.
Thanks, Slava

**Comment by Shougo** [comment]
Thanks.  Please update neosnippet to the latest version.

**Comment by hyperslv** [comment]
Thank you, Shougo! The fix works!
