### ISSUE TITLE
Explanation of [A], [B] at the second column of the completion list

### ISSUE THREAD

**Issue by alanjcfs** [Shougo/deoplete.nvim#1038]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I haven't been able to find an explanation for what [A] or [B] means as the second column. Without using deoplete, I usually see file locations. When I use TernJS, I can see [TernJS]. I looked at the documentation, and see `deoplete-options-candidate_marks` as a possible reason, but I'm not sure what they means.

## Expected
I will add to the documentation if anyone can explain what those cryptic letters mean. I gather that the letters usually show the origin of the completion functions, but I don't know how to get more information on that.

## Environment Information

 * deoplete version (SHA1): 22db8b273

 * OS: Mac OS X

 * neovim/Vim `:version` output: VIM - Vi IMproved 8.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

" For Vim only
"set runtimepath+=~/path/to/nvim-yarp/
"set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

## How to reproduce the problem from neovim/Vim startup (Required!)

The screenshots in the README shows various autocompletion with letters like `[O]`

![Image from README](https://user-images.githubusercontent.com/29815830/36537545-1184f10a-1803-11e8-81a1-097222a58752.png)

**Comment by Shougo** [comment]
It is already documented.

```
Q: What does each part of a line on the pop up mean?  For example I see:
   Bree pops up Breed [A]. What do [A] stands for?

A: It is the source mark. [A] is from around source.  A is from
   |deoplete-source-around|.
```
