### ISSUE TITLE
Crazily slow on windows gvim8

### ISSUE THREAD

**Issue by byzf** [Shougo/deoplete.nvim#1048]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Completion menu need about 1-2 second to show up, typing './' or './test' with only 'file' source enabled in a small test directory.
Changed to 'buffer' and 'around' source and type some words to test has same results.
**I tested the behaviour in release 4.0 code, it works as expected, though not fast enough.**
Seems code broken.

## Expected
Maybe 0.2~0.3s.

## Environment Information
Windows gvim 8.1
Latest gvim release downloaded. Nothing special.
python 3.8
deoplete and its depencies in head version. I manully change one line in init.vim to enable python3.8.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
if &compatible
	set nocompatible
endif

set backspace=indent,eol,start
set history=200
set nobackup
set pythonthreedll=python38.dll

set encoding=utf-8

call plug#begin('~/vimfiles/.cache')

Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'Shougo/deoplete.nvim'

call plug#end()

let g:python3_host_prog="python.exe"
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option({
			\ 'auto_complete_delay': 0,
			\ 'auto_refresh_delay': 0,
			\ 'sources': {
				\ '_': ['file'],
				\ },
			\ })

**Comment by Shougo** [comment]
> I tested the behaviour in release 4.0 code, it works as expected, though not fast enough.
Seems code broken.

It is not current code is broken.
But recent changes may be affected with Windows environment.

Please test `git bisect` instead.
If you don't do `git bisect`, unfortunately I will ignore your report.

Hint: `git bisect good` is https://github.com/Shougo/deoplete.nvim/commit/3e3b762a2c9ca92f4fbdc74f5558050b1a4a5572
`git bisect bad` is HEAD.

**Comment by Shougo** [comment]
You can disable parallel feature.
I think it is slow in Windows environment.

```vim
call deoplete#custom#option('num_processes', 1)
```

**Comment by Shougo** [comment]
Hm.  I think it is affected.

```
2018.12.24
* neovim-python 0.3.0+ is needed for asyncio feature.
* Change deoplete-options-num_processes default value in Windows.
* Remove "complete_method" option.
```
