### ISSUE TITLE
Cannot use <tab> to jump parameters after autocomplete.

### ISSUE THREAD

**Issue by Ni1fheim** [Shougo/deoplete.nvim#1052]
Hi,
when deoplete and LanguageClient-neovim work together, the function can be completed automatically, but this is the case after completion:

![](https://user-images.githubusercontent.com/31804253/71839988-5fc4a680-30f7-11ea-957c-16856696922e.png)

![](https://user-images.githubusercontent.com/31804253/71840013-6eab5900-30f7-11ea-98c4-9fbfa4fa8f3e.png)

How can I achieve automatic jump parameters and edit the whole block by <tab>?
Same thing happened on snipmate.
Thank you!

My vimrc configuration is as follows：
```vim
" LanguageClient
let g:LanguageClient_serverCommands = {
  \'c': ['/usr/bin/clangd'],
  \'rust': ['~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rls'],
  \'python': ['/usr/bin/pyls'],
  \ }   " path to language server
let g:LanguageClient_selectionUI = "fzf"
let g:LanguageClient_selectionUI_autoOpen = 1
let g:LanguageClient_hasSnippetSupport = 1
nnoremap <silent> K :call LanguageClient#textDocument_hover()<CR>
nnoremap <silent> <F2> :call LanguageClient#textDocument_rename()<CR>
nnoremap <silent> <C-k> :call LanguageClient#textDocument_definition()<CR>

" deoplete
let g:deoplete#enable_at_startup = 1
set pyxversion=3
```

**Comment by Ni1fheim** [comment]
When I write, auto-completion pop up without insert, and the first item is always selected. Then I use arrow or <C-n> / <C-p> to navigate between complete items. When I hit tab, if the complete item is a snippet then expand snippet, else insert that item.

**Comment by Shougo** [comment]
> How can I achieve automatic jump parameters and edit the whole block by ?

neosnippet supports the feature.

https://github.com/Shougo/neosnippet.vim/

```vim
let g:neosnippet#enable_complete_done = 1
```

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/1052#issuecomment-571271541

This place is not QA site.  You should not ask the general question.

> When I write, auto-completion pop up without insert, and the first item is always selected. 

`:set completeopt+=noinsert`

> Then I use arrow or <tab> / <c-k> to navigate between complete items. <tab> means <down>, <c-k> means <up>

It is possible.  But please study by `:help popupmenu-keys`.
