### ISSUE TITLE
I want to suppress warning messages.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1055]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
A warning message is displayed.

## Expected
I want to suppress warning messages.

## Environment Information

 * deoplete version (SHA1): 5be25591770c5abc7214e8899c4d451c479ac2ec

 * deoplete-lsp version (SHA1): 7a8c44f423bc4339c092a759abaad40131d2c98a
 * nvim-lsp version (SHA1): 7a15a52c0a7d735625ac73dc4d8efe70c5e99707

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-316-g8fe0635e7

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
Plugins and settings
```toml
[[plugins]]	
repo = 'Shougo/deoplete.nvim'	
hook_add = ''' 	
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'rust': '(\.|::|->)\w',
    \})

call deoplete#custom#option('sources', {
    \ 'rust': ['lsp'],
    \})
   
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'matcher_length',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])

set completeopt-=preview

call deoplete#enable()	
'''

[[plugins]]
repo = 'Shougo/deoplete-lsp'	

[[plugins]]
repo = 'neovim/nvim-lsp'
hook_add = '''
    command! Scratch lua require'tools'.makeScratch()
'''
```

`.config/nvim/lua/tools.lua`
```lua
-- 
local api = vim.api
local M = {}
function M.makeScratch()
    require'nvim_lsp'.rls.setup{}
end
return M
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `$ cargo new issue-rust` 
 2. `$ cd issue-rust`
 3. `$ nvim`
 4. `:Scratch`
 5. `:e src/main.rs`
 6. Type appropriately

## Screenshot (if possible)
<img width="602" alt="スクリーンショット 2020-01-18 15 03 51" src="https://user-images.githubusercontent.com/3197942/72659744-ecc90300-3a07-11ea-92ac-1a3492001993.png">

**Comment by Shougo** [comment]
> I want to suppress warning messages.

It is not deoplete problem.
It is displayed by neovim built-in lsp side.

Please ask it to neovim developers.

**Comment by nabezokodaikon** [comment]
understood. I will ask with nvim-lsp.
