### ISSUE TITLE
Completion doesn't respect the prefix and is not deterministic

### ISSUE THREAD

**Issue by astier** [Shougo/deoplete.nvim#1056]
## Problem

1. Sometimes the top-matches do not have the same prefix as the typed word. This is suboptimal.

2. Matches are not deterministic. They are sometimes different for the same typed word in the same place in the same file without changing anything.

## Expected

1. Prefix should always be respected. This means if a match has the same prefix as the typed word it should be at the top.

2. Suggestions should be deterministic.

## Environment

 * deoplete version (SHA1): 5be2559

 * OS: `Arch Linux`

 * neovim version: `NVIM v0.4.3`

 * `:checkhealth`:

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.1
  - INFO: pynvim version: 0.4.0
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v13.6.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Minimal vimrc

```vim
cal plug#begin('~/.local/share/nvim/plugins')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
cal plug#end()

cal deoplete#custom#option({
    \ 'min_pattern_length': 1,
    \ 'max_list': 8,
    \ 'num_processes': -1,
    \ 'ignore_sources': { '_': ['around', 'member'] },
    \ })
cal deoplete#custom#source('_', 'matchers', ['matcher_fuzzy', 'matcher_length'])
let g:deoplete#enable_at_startup = 1
se completeopt=menuone,noinsert
se shortmess+=c
```

## How to reproduce the problem from neovim

This can be reproduced with the minimal vimrc. Just try to type the same thing as described below in the last line of the vimrc, right below `se shortmess+=c`

1. Deoplete doesn't always respects the typed word as the prefix of the suggestions. For example as can be seen in the screenshot I typed `me` but it suggests as the first match `matcher_fuzzy`. I would expect `member` and `menuone` as the first suggestions. If I would have typed `mf` I would expect `matcher_fuzzy`. After typing `mem` it does suggest `member` as the first result.

2. It shows different suggestions for the same prefix in the same context. For example as can be seen in the 2nd screenshot after typing `mem` it suggests `member` as mentioned before which is correct. However, after deleting the last `m` such that the prefix is `me` again it does still suggest `member` instead of `matcher_fuzzy` as previously. After deleting the `e` such that the prefix bevomes `m` and then adding the `e` back such that the prefix is again `me` deoplete suggests again `matcher_fuzzy`. This can be repeated over and over.

## Screenshot
'![2020-01-23-033055_203x145_scrot](https://user-images.githubusercontent.com/36510152/72952261-96eeb500-3d91-11ea-8253-d90b458f1c06.png)

![2020-01-23-033718_204x127_scrot](https://user-images.githubusercontent.com/36510152/72952299-b1c12980-3d91-11ea-9b36-571ece5b6a47.png)

**Comment by astier** [comment]
Here another example. I want `sin`. I get `split`.

![2020-01-23-163303_254x152_scrot](https://user-images.githubusercontent.com/36510152/72998428-17e39600-3dfe-11ea-995d-308bcf60db09.png)

**Comment by astier** [comment]
It seems I was able to solve it by adding `matcher_head` to the matchers. Issue 2 seems also to disappear mostly. Sometimes it comes back. I can not reproduce it regularly. I will close it for.

**Comment by Shougo** [comment]
I will research the problem.
Please wait.

**Comment by astier** [comment]
I also got this issue again with other examples in my huge vimrc. I am not sure if this resolves it 100% but it seems that setting `'num_processes': 1` instead of `'num_processes': 0` helps.

**Comment by astier** [comment]
At least in some other cases it seeams to help. It doesn't help in my minimal vimrc example. Hm sorry but its quite hard to reproduce. I can't pin it down right now.

PS: I watched recently your presentation on the vim-jp youtube-channel. Great talk.

**Comment by Shougo** [comment]
I have get the reason.
It is prev completion feature.
I have disabled it in default.

**Comment by astier** [comment]
I just want to make you aware that setting `num_processes` to 1 also inroduces weird behavour. Like the completion doesn't update and inconsistent completion. Setting it to 0 or 2 however works for me without issues.

**Comment by Shougo** [comment]
I don't work without reproduce instructions.
I have not reproduced your problem.
