### ISSUE TITLE
Enter all keywords and they will be removed from completion.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1057]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Enter all keywords and they will be removed from completion.

## Expected
Even if you enter all keywords, do not disappear from the completion candidates.

## Environment Information

 * deoplete version (SHA1): 5be25591770c5abc7214e8899c4d451c479ac2ec
 * LanguageClient-neovim version (SHA1): 51fa22f21d993455a974414116f92eff45ac5f01

 * OS: Mac

 * neovim/Vim `:version` output: v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
"--------------------------------	
" deoplete.nvim	
"--------------------------------	
call deoplete#custom#option('keyword_patterns', {	
   \ 'denite-filter': '',	
   \})	
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'rust': '(\.|::|->)\w',
    \})
call deoplete#custom#option('min_pattern_length', 1)
call deoplete#custom#source('_',
    \ 'matchers', ['matcher_fuzzy', 'matcher_length'])
call deoplete#custom#option('sources', {
    \ 'rust': ['buffer', 'dictionary', 'LanguageClient', 'lsp'],
    \})
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])
set completeopt-=preview

inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"
inoremap <expr><TAB>  pumvisible() ? deoplete#close_popup() : "<TAB>"

call deoplete#enable()

"--------------------------------	
" LanguageClient-neovim	
"--------------------------------	
set hidden	
set completeopt=menu	
set signcolumn=yes	

let g:LanguageClient_useVirtualText = 'No'
let g:LanguageClient_autoStart = 1
let g:LanguageClient_loadSettings = 1

let g:LanguageClient_serverCommands = {	
    \ 'rust': ['~/.cargo/bin/rustup', 'run', 'stable', 'rls'],	
    \ }	
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `$ cargo new issue-rust` 
 2. `$ cd issue-rust`
 3. `$ nvim`
 4. `:e src/main.rs`
 5. Type appropriately

## Screenshot (if possible)
<img width="292" alt="スクリーンショット 2020-01-25 2 54 55" src="https://user-images.githubusercontent.com/3197942/73091631-29bc5a80-3f1e-11ea-9896-366a0ad4758c.png">
<img width="253" alt="スクリーンショット 2020-01-25 2 55 11" src="https://user-images.githubusercontent.com/3197942/73091636-2e810e80-3f1e-11ea-9046-bdfddc10a7df.png">

In VSCode, completion candidates remain.
<img width="573" alt="スクリーンショット 2020-01-25 1 58 18" src="https://user-images.githubusercontent.com/3197942/73091387-b581b700-3f1d-11ea-8bd5-4346ffc94279.png">

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('_',
    \ 'matchers', ['matcher_fuzzy', 'matcher_length'])
```

You have enabled `matcher_length`.
You need to know what is `matcher_length`.

```
					*deoplete-filter-matcher_length*
matcher_length
		Length matching matcher.
		It removes candidates shorter than or equal to the user input.
```

> Enter all keywords and they will be removed from completion.

`matcher_length` removes inputted candidate.

**Comment by nabezokodaikon** [comment]
I didn't know. Thank you.

**Comment by nabezokodaikon** [comment]
When I introduced nvim-lsp, I encountered the same problem.

## Environment Information

 * deoplete version (SHA1):86b18d9b7fc1dcf1270ed83b9b1c52ff41ee5a7a
 * nvim-lsp version (SHA1):b77a24f6b6bdf32d621f37c733f399f33a7eab0d
 * deoplete-lsp version (SHA1):6aa2bfd73a181fa6b55021264c4a8a83237ce558

 * OS: Mac

 * neovim/Vim `:version` output: v0.5.0-nightly

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK


## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```toml
[[plugins]]
repo = 'neovim/nvim-lsp'	
hook_add = '''
    luafile ~/.config/nvim/lua/lsp.lua
'''

[[plugins]]
repo = 'Shougo/deoplete-lsp'	
```

```lua
require'nvim_lsp'.pyls.setup{}
```

### Other setting
```bash
$ pip3 install 'python-language-server[all]'
```


## How to reproduce the problem from neovim/Vim startup (Required!)
1. `touch foo.py`
2. `nvim foo.py`
3. Enter the following
```
foo = 0
foo1 = 1
foo2 = 2
```
4. Type `fo` and `foo`


## Screenshot (if possible)
<img width="406" alt="スクリーンショット 2020-05-13 14 23 05" src="https://user-images.githubusercontent.com/3197942/81774471-9c7d3000-9525-11ea-9cfa-3c3844dbf0ac.png">
<img width="203" alt="スクリーンショット 2020-05-13 14 23 16" src="https://user-images.githubusercontent.com/3197942/81774490-a2731100-9525-11ea-8a66-6cde7f04f2a4.png">

**Comment by nabezokodaikon** [comment]
I have not set the following.
```
call deoplete#custom#source('_',
    \ 'matchers', ['matcher_fuzzy', 'matcher_length'])
```

**Comment by Shougo** [comment]
@nabezokodaikon 

```vim
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'matcher_length',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])
```

You have set `matcher_length` in converters.
It works in converters.

You should check the configuration...

**Comment by nabezokodaikon** [comment]
Excuse me. I overlooked it...
