### ISSUE TITLE
Bug: scriptencoding used outside of a sourced file

### ISSUE THREAD

**Issue by pappasam** [Shougo/deoplete.nvim#1059]
Commit: https://github.com/Shougo/deoplete.nvim/commit/175169dcb6ffc9dd4df12e5f339154fdf4efb0dc

Deoplete breaks with the following message: "E167: :scriptencoding used outside of a sourced file"

Fix: remove this line: https://github.com/Shougo/deoplete.nvim/blob/175169dcb6ffc9dd4df12e5f339154fdf4efb0dc/autoload/deoplete/mapping.vim#L30

**Comment by acesaro** [comment]
I just ran into this myself after running a `PlugUpdate`.  Thanks for reporting a workaround in the meantime.

**Comment by thecontinium** [comment]
I have the same issue after just updating

**Comment by antenore** [comment]
Thanks for the workaround @pappasam

**Comment by Shougo** [comment]
Thanks.  I have fixed.
