### ISSUE TITLE
I can't complement it.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1060]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When I enter text, an error occurs and I cannot complete it.

## Expected
I want you to be able to complete without errors.

## Environment Information

 * deoplete version (SHA1): 4121320109172e3212c6c590f5ce1dc9dd756511

 * OS: Mac

 * neovim/Vim `:version` output: neovim v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```toml
[[plugins]]	
repo = 'Shougo/deoplete.nvim'	
on_event = 'InsertEnter'
```

```vim
call deoplete#custom#option('keyword_patterns', {	
   \ 'denite-filter': '',	
   \})	
call deoplete#custom#var('omni', 'input_patterns', {
    \ 'rust': '(\.|::|->)\w',
    \})
call deoplete#custom#option('min_pattern_length', 1)
call deoplete#custom#option('sources', {
    \ 'rust': ['buffer', 'dictionary', 'LanguageClient', 'lsp'],
    \})
call deoplete#custom#source('LanguageClient', 'converters', ['converter_reorder_attr'])
set completeopt-=preview

inoremap <expr><CR>  pumvisible() ? deoplete#close_popup() : "<CR>"
inoremap <expr><TAB>  pumvisible() ? deoplete#close_popup() : "<TAB>"

call deoplete#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `$ nvim`
 2. Type appropriately

## Screenshot (if possible)
<img width="905" alt="スクリーンショット 2020-01-30 1 22 58" src="https://user-images.githubusercontent.com/3197942/73377074-d1ac9c00-4301-11ea-814e-217246d15b30.png">

**Comment by TMiller00** [comment]
I just upgraded and am having the exact same issue in Ruby

**Comment by TMiller00** [comment]
This is also referenced in #1059

**Comment by Shougo** [comment]
Fixed in master.

Note:  I don't reproduce the error in neovim....  It is reproduced in Vim8
