### ISSUE TITLE
Possible to show doxygen comments in preview window?

### ISSUE THREAD

**Issue by gridley** [Shougo/deoplete.nvim#1063]
Hi, I have searched for info on this for a bit. I was hoping to find a way to show more information in the completion window. In particular, is there any deoplete plugin which checks for doxygen documentation above C/C++ functions and can display it in the preview window?

It seems that deoplete-jedi can show docstrigs, so why isn't there similar functionality for deoplete-clangx?

**Comment by Shougo** [comment]
This is not deoplete issue.

> It seems that deoplete-jedi can show docstrigs, so why isn't there similar functionality for deoplete-clangx?

You can contribute with deoplete-clangx.  clang may support doxygen comments.
But I think using LSP is better instead.
