### ISSUE TITLE
Please provide a way to use it without popup menu

### ISSUE THREAD

**Issue by powerman** [Shougo/deoplete.nvim#1065]
I hate to hide adjacent lines of code by completion popup menu, this is just not an acceptable workflow to me. At same time I like how this plugin works at all other aspects. I've spent two days trying a lot of different configurations based on `deoplete#manual_complete()` recipe in the doc but failed, and looks like I'll have to give up and try some other plugin for completion. :disappointed: 

I suppose this plugin may be somehow improved to enable workflow I need, please consider such a feature:
* Completion still gather data async but no menu is visible on screen and no completion is applied automatically just because I've typed some prefix string.
* On pressing `<Tab>` completion menu may or may no be shown - both cases are acceptable, but if it's shown then it must disappears right after some completion will be selected or all completions will be rejected (like by typing non-keyword symbol) and must not be shown again automatically (without pressing `<Tab>`).
* On pressing `<Tab>` (same key press as mentioned in previous item, not second one) first completion item must be used, i.e. it should work just like pressing `<C-n>` when menu is shown. Pressing `<Tab>` again and again should work like `<C-n>`.

I belive troubles I had was related to #1006 - I've used suggestions from LSP (provided by vim-go), and while at a glance it works next when I've tried to `<BS>` several times after accepting initial successful completion and press `<Tab>` once again I got either no result, or sometimes valid result intermixed with invalid (wrong prefix string with head matcher). Sometimes it works okay, but most often it doesn't. Yeah, I suppose this is probably some sort of async/timing related issue, and probably we need to implement optional sync mode for deoplete to make it work reliably with mentioned above workflow.

**Comment by Shougo** [comment]
> I belive troubles I had was related to #1006 - I've used suggestions from LSP (provided by vim-go), and while at a glance it works next when I've tried to <BS> several times after accepting initial successful completion and press <Tab> once again I got either no result, or sometimes valid result intermixed with invalid (wrong prefix string with head matcher). Sometimes it works okay, but most often it doesn't. Yeah, I suppose this is probably some sort of async/timing related issue, and probably we need to implement optional sync mode for deoplete to make it work reliably with mentioned above workflow.

I recommend for you to use deoplete-vim-lsp.
https://github.com/lighttiger2505/deoplete-vim-lsp

And I don't work without minimal vimrc and reproduce instructions.
