### ISSUE TITLE
deoplete auto-replacing from its match list even when I'm not selecting anything from the menu

### ISSUE THREAD

**Issue by srinathh** [Shougo/deoplete.nvim#107]
When I'm trying to type something that is not in deoplete's match list, it auto replaces what I'm typing with closest match in the match list even when I'm not selecting anything from the menu. This is making it difficult for me to type something that's not in the match list.

**Comment by Shougo** [comment]
I want to reproduce the problem.
Please read the CONTRIBUTION.md.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by srinathh** [comment]
### Problems summary
When I'm trying to type something that is not in deoplete's match list, it auto replaces what I'm typing with closest match in the match list even when I'm not selecting anything from the menu. This is making it difficult for me to type something that's not in the match list. The issue seems to be intermittent. Was happening yesterday and day before. Not happening right now.

### Expected
Replacing what is being typed only on selection from the menu

### Environment Information
OS: Ubuntu 14.04 through Crouton on Chromebook, Kernel 3.8.11
Neovim version: NVIM 0.1.1 (compiled Dec 23 2015 21:24:39)
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector --param ssp-buffer-size=4 -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/config -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/src -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/.deps/usr/include -I/usr/include -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/src/nvim/auto -I/build/neovim-n2Y7bc/neovim-0.1.1ubuntu1+git201512232013+2087+16~ubuntu14.04.1/build/include
Compiled by buildd@lgw01-26
Optional features included (+) or not (-): +acl   +iconv    +jemalloc 

### Provide a minimal init.vim with less than 50 lines
call plug#begin('~/.vim/plugged')
Plug 'junegunn/vim-easy-align'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'fatih/vim-go'
Plug 'Shougo/deoplete.nvim'
call plug#end()
syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
colorscheme railscasts
let g:deoplete#enable_at_startup = 1

**Comment by Shougo** [comment]
@srinathh 
Please upload the reproduce ways from neovim starting.

And I think it is the minimal init.vim.

```vim
set rtp+=path_to_deoplete.nvim
syntax on
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set expandtab
let g:deoplete#enable_at_startup = 1
```

**Comment by marcosnils** [comment]
@Shougo the same is happening to me with omni completions. 

I've used your minimal config and when trying to edit an HTML attribute, omni completion popup appears and depending on which keys you press, deoplete will always select a default option even though it's not available.

Example:
https://asciinema.org/a/3tmpij6arzkht0wl2p6a1wtyb

I'm trying to add an "ng-click" property in the HTML button but deoplete always selects the 'lang' suggestion even though it's not matching my tyiping. 

Hope it helps to reproduce.

**Comment by adambiggs** [comment]
I'm having the same issue. For me this only happens when editing `filetype=html.handlebars` files, although I haven't tried editing straight HTML yet.

**Comment by Shougo** [comment]
Reproduced and fixed.  Thanks.
It is by #79 changes.

**Comment by marcosnils** [comment]
@Shougo omni completion suggestions are not appearing anymore now

**Comment by blueyed** [comment]
Here's a new attempt: https://github.com/Shougo/deoplete.nvim/pull/202.
