### ISSUE TITLE
Error: deoplete requires msgpack 1.0.0+.

### ISSUE THREAD

**Issue by Cherrry9** [Shougo/deoplete.nvim#1073]
## Problems summary
After deoplete updated to latest version it doesn't load and I see: [deoplete] deoplete requires msgpack 1.0.0+.

## Expected
Working deoplete

## Environment Information
 * deoplete version (SHA1): 1ec8428fc4a150756dc793295b44f7e62544b5ed 

 * OS: arch

 * neovim/Vim `:version` output:
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser
Features: +acl +iconv +tui

 * `:checkhealth` or `:CheckHealth` result(neovim only):
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - ERROR: Require msgpack 1.0.0+ was not successful
    - ADVICE:
      - Please install/upgrade msgpack 1.0.0+.

## Minimal init.vim/vimrc
```vim
call plug#begin('~/.config/nvim/bundle')

	Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()
~/set runtimepath+=/home/jan/.config/nvim/bundle/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup
1. Downloand/Install the latest version of deoplete.
2. Run neovim.

## Generate a logfile if appropriate
 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
Log file is empty (I did everything as described)

## Screenshot
https://0x0.st/iPpQ.png

## What did I try to do?
Updated my OS
Reinstalled python-msgpack
Reinstalled deoplete

**Comment by zo7** [comment]
I ran into this issue today too with Vim8/macOS. I fixed it by upgrading `msgpack` (naturally) but the trick was to upgrade `msgpack` for the version of Python that your Vim is built against.

I have multiple Python installs via pyenv, so my solution was:
```sh
>>> pyenv global system  # Switch pyenv to the "system" python
>>> pyenv which pip3
/usr/local/bin/pip3
>>> pip3 install --upgrade msgpack
```

**Comment by codycraven** [comment]
I'm on Ubuntu (upgraded from last LTS) and haven't been able to get rid of this error with upgrading either Python 2 or 3 (note I had to install pip3):

```
$ pip3 install --upgrade msgpack
Requirement already up-to-date: msgpack in $HOME/.local/lib/python3.7/site-packages (1.0.0)
```

```
$ pip install --upgrade msgpack
Requirement already up-to-date: msgpack in $HOME/.local/lib/python2.7/site-packages (1.0.0)
```

**Comment by Cherrry9** [comment]
Thanks you very much. @codycraven, you solved my problem.

**Comment by VictorYYW** [comment]
On my machine (arch linux), the issue can only be solved by
```
pip3 install --user pynvim --upgrade msgpack
```
Just want to make a note here in case others need it.

**Comment by djh-orphan** [comment]
> I'm on Ubuntu (upgraded from last LTS) and haven't been able to get rid of this error with upgrading either Python 2 or 3 (note I had to install pip3):
> 
> ```
> $ pip3 install --upgrade msgpack
> Requirement already up-to-date: msgpack in $HOME/.local/lib/python3.7/site-packages (1.0.0)
> ```
> 
> ```
> $ pip install --upgrade msgpack
> Requirement already up-to-date: msgpack in $HOME/.local/lib/python2.7/site-packages (1.0.0)
> ```
> 
> **Update Resolved**
> Running pip3 install for pynvim fixed:
> 
> ```
> pip3 install --user pynvim
> ```
Thanks a lot. It solved my problem！！！！

**Comment by lydialitvyak** [comment]
I can not solve same problem on rasspberrypi
Is there any advice please?

**Comment by Shougo** [comment]
You need to check your pip python is same with neovim python.
:checkhealth is recommended.
No magic.
