### ISSUE TITLE
deoplete requires msgpack 1.0.0+ but it is in my venv

### ISSUE THREAD

**Issue by statquant** [Shougo/deoplete.nvim#1075]
# Problems summary
Hello, I have what I assume to be a simple issue, I have very little python know-how so I cannot solve that by myself.
I get a :message "[deoplete] deoplete requires msgpack 1.0.0+." I am experiencing this on different machines
- at home on my personal laptop where I can install latest everything, I have msgpack 1.0.0
- at work where I use venv (activated) at version 1.0.0

```
$ pip show msgpack
Name: msgpack
Version: 1.0.0
Summary: MessagePack (de)serializer.
Home-page: https://msgpack.org/
Author: Inada Naoki
Author-email: songofacandy@gmail.com
License: Apache 2.0
Location: /home/statquant/.local/lib/python3.7/site-packages
Requires: 
Required-by: pynvim
```
As a result (I think) I cannot get completion, is there something I can do ?

**EDIT:**
I just tested and reverting to deoplete commit  e897e01 makes it work again

## Environment Information

 * deoplete version (SHA1): lattest from master

 * work OS: centos 7.4
 *  home Fedora 31

 * work vim 8.1
 * home vim 8.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
set runtimepath+=~/path/to/nvim-yarp/
set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. symply start vim and type :messages

**Comment by Shougo** [comment]
You can specify the Python path by `pythonthreedll` option.
It is not deoplete problem.

Your pip path is not same with Vim's python path.

Note: You should learn what is `pyenv` and if_python behavior in Vim8.
pyenv changes `python` path.  But it does not affect with Vim's python path.

**Comment by Shougo** [comment]
Vim's python path means your system's python path.

**Comment by statquant** [comment]
> `pythonthreedll`
on linux ?

**Comment by Shougo** [comment]
> A dll on linux ?

Yes.  You should google by `pythonthreedll` and read the documentation.

```
						*'pythonthreedll'*
'pythonthreedll'	string	(default depends on the build)
			global
			{only available when compiled with the |+python3/dyn|
			feature}
	Specifies the name of the Python 3 shared library. The default is
	DYNAMIC_PYTHON3_DLL, which was specified at compile time.
	Environment variables are expanded |:set_env|.
	This option cannot be set from a |modeline| or in the |sandbox|, for
	security reasons.
```

I think using system pip3 to upgrade `msgpack` is easier than set `pythonthreedll` though.

**Comment by statquant** [comment]
> I think using system pip3 to upgrade msgpack is easier than set pythonthreedll though.

That's what I did (as per first message), but I'll read what you suggest

**Comment by Shougo** [comment]
> That's what I did (as per first message), but I'll read what you suggest

I don't read the situation from the message.

I have read is:

```
$ pip show msgpack
Name: msgpack
Version: 1.0.0
Summary: MessagePack (de)serializer.
Home-page: https://msgpack.org/
Author: Inada Naoki
Author-email: songofacandy@gmail.com
License: Apache 2.0
Location: /home/statquant/.local/lib/python3.7/site-packages
Requires: 
Required-by: pynvim
```

The location is not same with system pip.
Because:

> work OS: centos 7.4

centos 7.4 is not Python 3.7.

I think you have used pip in venv environment.
But it is not same with system Python environment.

**Comment by statquant** [comment]
No sorry, I have actually done both
- on one machine with fedora 31 I did use pip WITHOUT a venv
- on another machine with centos 7.4 I did use pip WITH a venv
I'll clean my messages so to only show the fedora 31 non-venv case

**Comment by Shougo** [comment]
Really?
But msgpack in your Vim environment doesn't have 1.0
It is not deoplete problem.

**Comment by Shougo** [comment]
And you need to use pip3 instead of pip.
Because pip may point to Python2.

**Comment by Shougo** [comment]
Please read this.
https://github.com/Shougo/deoplete.nvim/issues/1073

**Comment by Shougo** [comment]
And this.
https://github.com/Shougo/deoplete.nvim/issues/1072
