### ISSUE TITLE
Enable zsh autocomplete for sh buffers.

### ISSUE THREAD

**Issue by Cherrry9** [Shougo/deoplete.nvim#1081]
# Problems summary
I tryied to use [zsh autocompletion](https://github.com/deoplete-plugins/deoplete-zsh) in buffers with the file type sh. I have read about the "deoplete#custom#option('sources'..." option and I tryied to use this.

## Expected
Working zsh autocomplition in sh buffers.

## Environment Information

 * deoplete version (SHA1): 494fcd8f311fb394d81921b63797e963c7d642a3

 * OS: arch

 * neovim/Vim `:version` output: 
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.4.3/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

 * `:checkhealth` or `:CheckHealth` result(neovim only):
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

## Minimal init.vim

```vim
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
if !exists('g:deoplete#omni#input_patterns')
	let g:deoplete#omni#input_patterns = {}
endif
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
call deoplete#custom#source('ultisnips', 'rank', 1000)
call deoplete#custom#option('sources', {
            \ 'sh': ['zsh'],
            \ 'zsh': ['zsh'],
\})
```

**Comment by Shougo** [comment]
You need to configure `filetypes` option instead.

```vim
call deoplete#custom#source('zsh', 'filetypes', ['sh', 'zsh'])
```
