### ISSUE TITLE
support for msgpack new major version

### ISSUE THREAD

**Issue by jcao219** [Shougo/deoplete.nvim#1082]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

* msgpack is now the pip package name, not msgpack-python

## Expected
:checkhealth and :updateremoteplugins work
## Environment Information

nearly fresh nvim install

everything set up, but instead of `pip install msgpack-python`: `pip install msgpack` for the latest version

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. `pip uninstall msgpack-python; pip install msgpack`
2. `use deoplete`

## Screenshot (if possible)

Sorry, I forgot to, can do it later.

**Comment by Shougo** [comment]
I don't understand your issue.
Closing.
