### ISSUE TITLE
Locality Bonus for increasing rank of nearby words

### ISSUE THREAD

**Issue by astier** [Shougo/deoplete.nvim#1085]
Hi. VSCode and COC have both a setting called `localityBonus`. This gives nearby words a higher rank such that they appear higher in the suggestion list. In particular the rank would be higher compared to words which otherwise would have the same rank based on the fyzzy-match but are which further away from the cursor. This tends to be generally a good heuristic and gives me constantly better results since in programing variables which you just defined are more likely to be the word which you want next if the fuzzy-search matches.

**Comment by Shougo** [comment]
The feature is really needed?
Current `sorter_rank` implements nearly feature.

Already typed word is higher rank.

**Comment by astier** [comment]
Its not just about already typed words but about word which are closer to the curser. Here is an [explanation and example](https://code.visualstudio.com/docs/editor/intellisense#_locality-bonus). For me the lack of this feature in deoplete is noticable. The problem is that currently deoplete might suggest words which are already typed in the buffer however they may be typed on the top of the buffer while I expect to complete the variable which I just defined in the local function.

An example happened to me today. I tried to complete the word `shortmess` in my vimrc which I just typed above. Coc suggests immediately `shortmess`. Deoplete suggests all kinds of words which appear in the buffer but shortmess is somewhere on the bottom. Even after typing `sh` deoplete suggested me first `search` which appears first on the top of my vimrc and only second `shortmess`. I had first to type `sho` before the suggestion was correct. I had many similar examples for python etc.

**Comment by Shougo** [comment]
OK.  I have implemented the feature.
Please test it.

**Comment by astier** [comment]
Thank you. It seems to work! Didn't think you would be so fast.

**Comment by astier** [comment]
I just want to get rid of the coc-node bloat. Deoplete is my only hope.

**Comment by Shougo** [comment]
> Didn't think you would be so fast.

My work is fast if possible.
