### ISSUE TITLE
How to realize the multiple filetypes autocomplete？

### ISSUE THREAD

**Issue by yangxyo** [Shougo/deoplete.nvim#1087]
I am a newbie for vimscript.

Yesterday， I research the source code of `deoplete.nvim` and `context_filetype.vim` for a whole day. I know `context_filetype.vim` through return such as 
```
{'range': [[9, 1], [12, 4]], 'filetype': 'css'}
```
to did the super job.

I find this in the source code of `deoplete.nvim`:
```vimscript
" For context_filetype check
  silent! call context_filetype#get()
```

But, I can't know **how and where** the `deoplete.nvim ` use 
```
{'range': [[9, 1], [12, 4]], 'filetype': 'css'}
```

Can you give me some tips?

I want to use the `context_filetype.vim` in some other projects of autocomplete.

___
And I don't know why must call 'javascript' double , too. I didn't understand the doc.  Can you help me to make it?
```
call deoplete#custom#var('omni', 'functions', {
\ 'javascript': ['javascriptcomplete#CompleteJS']
\})
call deoplete#custom#var('omni', 'input_patterns', {
\ 'javascript': '[^. *\t]\.\w*',
\ })
```

I'm sorry.
English is not my mother tongue, too.

**Comment by Shougo** [comment]
> But, I can't know how and where the deoplete.nvim use

You should read context.py implementation.
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/context.py

**Comment by Shougo** [comment]
> And I don't know why must call 'javascript' double , too. I didn't understand the doc. Can you help me to make it?

They are not same.  You should read the code carefully.
You need to set omnifunc in `functions` variable in omni source.
Because `omnifunc` option is set when `autocmd FileType`.
deoplete with context_filetype does not work. `autocmd FileType` is not fired.

**Comment by yangxyo** [comment]
Thanks.
