### ISSUE TITLE
Make matcher_length default

### ISSUE THREAD

**Issue by astier** [Shougo/deoplete.nvim#1088]
I believe the matcher `matcher_length` should be the default besides `matcher_fuzzy`. I do it manually by:

```vim
cal deoplete#custom#source('_', 'matchers', [
    \ 'matcher_fuzzy',
    \ 'matcher_length',
    \ ])
```

My reasoning is that so far all completion engines in any editor I used so far have this as default behavior. Thus I think most people expect this. I personally found it kind off difficult and time-consuming to find out how actually to change this behavior in deoplete which initially made me search for alternatives and use coc. Also I don't really see the value in suggesting a completion which I have already typed. This takes away place for suggestions which actually would make sense and results often in more keystrokes to find a meaningful suggestion.

**Comment by Shougo** [comment]
I don't change the default.
It depends on users usage and you can change the default.

**Comment by Shougo** [comment]
> My reasoning is that so far all completion engines in any editor I used so far have this as default behavior. 

Vim's default completion is not.
