### ISSUE TITLE
Treat the directory of current file as base directory for directory completion

### ISSUE THREAD

**Issue by nabn** [Shougo/deoplete.nvim#109]
When deoplete attempts to autocomplete relative paths, it seems that it's using the CWD that was set on vim open. I think a better way is to use the directory of the current file as base for autocompletion suggestions.

**Comment by wsdjeg** [comment]
i think is is not a good ideal,for most project,the file path we need complete is not in the directory of current file ,but in some specified path of current project

**Comment by ZyX-I** [comment]
@wsdjeg This depends on the file used. I think it needs a `b:var` for this.

**Comment by nabn** [comment]
@wsdjeg I'm not sure if I follow what you mean.. I primarily work with javascript files where I'm constantly using relative paths to assets, module imports, etc. I've used YouCompleteMe and a couple other completion plugins in the past, they all use the behavior as I'm trying to suggest.
I think it's more logical. for example, If i'm in a file src/components/Navigation/index.js and I want to import some utility functions from src/Utilities/network_utils.js, it'd be better if the plugin i'm using suggests `Utilities` when i type in '../../' from the navigation/index.js file.

My workflow includes a tmuxinator session with vim opened from the project directory. Do tell me if my setup is too specific to be considered, but I think that's hardly the case..

**Comment by wsdjeg** [comment]
`:echo getcwd()` is not you project's root path?
i think the plugin now complete file path bash on getcwd();
for example my project root path is ~/projectT/
contains these files
```
~/projectT/src/wsdjeg/Foo.java
~/projectT/pic/test.png
~/projectT/utils/test.sh
```
in vim `:echo getcwd()` show /home/wsdjeg/projectT/
when i am editting `~/projectT/src/wsdjeg/Foo.java`
if i want want use the png file;
i just neet to type `./` then the popup menu contais `src`,`utils`,and `pic`

**Comment by wsdjeg** [comment]
https://github.com/airblade/vim-rooter
this plugin maybe what you want.

**Comment by SageEx** [comment]
@nabn 
>I think it's more logical. for example, If i'm in a file src/components/Navigation/index.js and I want to import some utility functions from src/Utilities/network_utils.js, it'd be better if the plugin i'm using suggests Utilities when i type in '../../' from the navigation/index.js file.

How about using 
```vim
set autochdir
```

**Comment by MobiusHorizons** [comment]
It is worth noting that pluggins like clang_complete and (as far as i know) ternjs cannot find modules imported from the project root without special configuration. At least in these two contexts, the only sane behavior for file completion of relative paths is relative to the file itself. 

I agree that this should be a configurable setting, maybe even a language dependent one.

**Comment by Shougo** [comment]
@SageEx I don't recommend to use `autochdir` option.
It conflicts the plugins.

I can implement this feature.  But it is really needed?
If you want to complete the files from the relative path, you should install neoinclude.vim.
Why don't you use neoinclude.vim with deoplete?

**Comment by Shougo** [comment]
If neoinclude does not support your filetypes, neoinclude should be fixed.
I think it is not file source work.

**Comment by SageEx** [comment]
@Shougo Just installing neoinclude does not gives the same behaviour as using `./` and `autochdir`. How can I configure it ?
What I want is that `./` should complete filename with current file's working directory - that feels more natural and quite useful.

**Comment by Shougo** [comment]
> @Shougo Just installing neoinclude does not gives the same behaviour as using ./ and autochdir. How can I configure it ?

It works if the input text is matched `include` option pattern.

> What I want is that ./ should complete filename with current file's working directory - that feels more natural and quite useful.

> i think is is not a good ideal,for most project,the file path we need complete is not in the directory of current file ,but in some specified path of current project

So, I think is is natural.
If the exception is nothing, OK.  I will change the behaviour.
I don't want to add the option.

**Comment by wsdjeg** [comment]
@Shougo the g:deoplete#file#enable_buffer_path default value should be 0,let deoplete works like before

**Comment by Shougo** [comment]
OK

**Comment by wsdjeg** [comment]
thanks!

**Comment by SageEx** [comment]
@Shougo Thanks for the quick fix.

**Comment by nabn** [comment]
Thanks! It works perfectly with the flag set!
