### ISSUE TITLE
Unknown error with coc + deoplete

### ISSUE THREAD

**Issue by dylanirlbeck** [Shougo/deoplete.nvim#1092]
I'm getting the following error whenever I type in anything in insert mode:

```
[coc.nvim] error: Some plugin change completeopt on insert mode: Last set from ~/.config/nvim/bundle/de
oplete.nvim/autoload/deoplete/mapping.vim line 83!
```

I've never gotten this before, so any help debugging is much appreciated. I'm also happy to provide more information if needed.

**Comment by Shougo** [comment]
It is coc feature.
coc changes `completeopt` internally and if other plugins change it, it is detected.

deoplete changes `completeopt`, so it is conflicted with coc.
You should not mix coc and deoplete.
