### ISSUE TITLE
pasted text erased

### ISSUE THREAD

**Issue by tzachar** [Shougo/deoplete.nvim#1093]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

When pasting text while suggestions pum is opened, pasted text is erased.

## Expected

pasted text should be inputted

## Environment Information

 * deoplete version (SHA1):
b7aee6552c7d972b3ead12f13466776c67cf8300

 * OS:
linux

 * neovim/Vim `:version` output:

NVIM v0.5.0-396-gc036e24f3
 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

" deoplete:
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. paste text when pum is opened
 2. watch pasted text disappear

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

log empty

## Screenshot (if possible)

![output](https://user-images.githubusercontent.com/4946827/78535080-3994cc80-77f4-11ea-9f95-0083df7fd5f3.gif)

**Comment by Shougo** [comment]
> deoplete version (SHA1):
> b7aee65

Your deoplete is not the latest version.
You should update deoplete before create issues.
 
Please read the issue.
https://github.com/Shougo/deoplete.nvim/issues/1090

> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

And you should know what is minimal vimrc.
I have seen your screenshot, but it is not minimal vimrc's Vim.
For example, many plugins are installed(deoplete-tabnine, status line plugin, etc...).

**Comment by tzachar** [comment]
10x for your reply.

I usually keep my plugins updates, but seem to have missed your fix...
