### ISSUE TITLE
[SOLVED] Can I make Deoplete behave like YCM?

### ISSUE THREAD

**Issue by Godnyx** [Shougo/deoplete.nvim#1094]
Hello! I just want to make a question cause I can't find it in documentation or anywhere else.
If you thing this doesn't belong here then go ahead and remove it even without saying anything, it's fine by me!

Ok. I just want to ask if Deoplete can behave the way [YCM](https://github.com/ycm-core/YouCompleteMe).
Be default Deople does a behavior I strogly dislike! You have to use the arrow keys the move bettween the options and also the word isn't auto-completed so you also have to press Enter to select and complete it. Can this change? In YCM you press TAB to go the the first option and then to the next if you keep pressing it and S-TAB to go to the previous. Also as you select options the word is also auto-completed so you don't have to press Enter!

If you need more info let me know!

**SOLVED:** I've got the answer from a reddit post.
For anyone that me find this in the future and wondering. Use:
inoremap <silent><expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
inoremap <silent><expr><s-tab> pumvisible() ? "\<c-p>" : "\<s-tab>"

**Comment by Shougo** [comment]
Yes.  You can change mappings.
deoplete does not change any of mappings like YCM.
It is my policy to prevent to conflict with your other configuration or plugins.
