### ISSUE TITLE
Deoplete candidates disappear with auto_complete_delay

### ISSUE THREAD

**Issue by ZwodahS** [Shougo/deoplete.nvim#1095]
# Problems summary
When used with ultisnips, on alternate character, it doesn't autocomplete and display "Pattern Not found"

## Environment Information
* Last working version: `36f83eb5cea68b7abfa31aa5f2cdfb1720502d91`
* Bisected and suspect that this commit caused it: `8b917be8cc7d9cc75066228ec1cb92c643b2bbce`
* This version also works: `9b048ab08b1ea6be1a79426e5082e82f2e37fecc`
* OS: OSX

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin(".")
" source all the plugins
Plug 'SirVer/ultisnips'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 50
let g:python3_host_prog='.....'
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Open a python file, i.e. `test.py`

Paste in the following

```
class Hello(object):
    def __init__(self):
        pass
```

At the new line, start typing "Hello". Alternate character will show autocomplete menu, but the other character will not. For example, when you press "He", the autocomplete menu will appear, then when you type 'l', it will disappear, then appear on the next 'l', then disappear on 'o'

![Screenshot 2020-04-25 at 6 15 36 PM](https://user-images.githubusercontent.com/197371/80277329-cd392900-8720-11ea-936e-9d516f4ab8c0.png)

![Screenshot 2020-04-25 at 6 15 46 PM](https://user-images.githubusercontent.com/197371/80277333-d0341980-8720-11ea-82ac-46f2e849aee4.png)

**Comment by Shougo** [comment]
```vim
let g:deoplete#auto_complete_delay = 50
```

It does not work.

**Comment by Shougo** [comment]
I have tested it and Ultisnips is not related.

**Comment by ZwodahS** [comment]
Cool thank you for the quick for fix ! :D
