### ISSUE TITLE
After upgrade from Buster to Bulleye deoplate ask for pyvim

### ISSUE THREAD

**Issue by nguxx** [Shougo/deoplete.nvim#1098]
Hi,
WHole message is 
`[vim-hug-neovim-rpc] Vim(pyth...r: No module named 'greenlet'
Erreur détectée en traitant function deoplete#enable[9]..deoplete#initialize[1].
.deoplete#init#_initialize[10]..<SNR>84_init_internal_variables[28]..neovim_rpc#
serveraddr :
ligne   18 :
E605: Exception non interceptée : [vim-hug-neovim-rpc] requires one of `:pythonx
 import [pynvim|neovim]` command to work
`
I have pynvim installed, What could I do ?
Thanx

**Comment by Shougo** [comment]
Please install greenlet module for pynvim by pip3.
I think it must be installed though.

**Comment by nguxx** [comment]
Yes "requirement already satisfied", I have it too.

**Comment by Shougo** [comment]
You should check your Vim's Python.
I think your pip3 path is different from Vim.

You can check the installation by `:python3 import greenlet` in Vim.

**Comment by Shougo** [comment]
> After upgrade from Buster to Bulleye deoplate ask for pyvim

Hm.  After upgrade, Python version is changed.  You need to re-install modules.
I think you should use `pip3.8` command instead of `pip3`.

And your Vim's python is built for Python3.8?
If you build Vim manually, you need to re-build Vim.
You can check it by `:version` output.

**Comment by nguxx** [comment]
Try to re install vim from source, because Bullyeye is python3.8 I have an issue with libpython3.7m.so.1.0 to run vim.
No time for this.
Migrate to Neovim witch works like a charm.
Thanks

**Comment by Shougo** [comment]
OK.
For python, neovim is easy to use.
