### ISSUE TITLE
Broken `cpoptions+=$` functionality

### ISSUE THREAD

**Issue by toddabrahm** [Shougo/deoplete.nvim#1099]
# Problems summary

Deoplete seems to break `cpoptions+=$` functionality

## Expected

Normally, `cpoptions+=$` would keep the text being changed (ex. with `cw`) and include a `$` as the ending boundary of what will be changed. The new text replaces the original text as you type but you can continue to see what's left of the original. When you leave insert mode the rest of the original text and boundary mark disappear and are completely replaced by the new text.

Instead deoplete causes one of two things to happen depending on the timing of the popup (ex. due to the `auto_complete_delay` setting):

1. The original text and boundary marker (`$`) are left on the screen even after leaving insert mode. Redrawing with `<c-l>` fixes it and shows that text has been changed it just didn't redraw to reflect that.
2. The new text immediately replaces the original entirely. Essentially it behaves as if you hadn't set the `$` option.

## Environment Information

 * deoplete version (SHA1): 86b18d9
 * OS: macOS Sierra
 * neovim/Vim `:version` output:

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG
-DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -W
missing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_D
ECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20191110-77481-1qbzxbb/neo
vim-0.4.3/build/config -I/tmp/neovim-20191110-77481-1qbzxbb/neovim-0.4.3/src -I/usr/local/include -I/tmp/neovim-2019111
0-77481-1qbzxbb/neovim-0.4.3/deps-build/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20191110-
77481-1qbzxbb/neovim-0.4.3/build/src/nvim/auto -I/tmp/neovim-20191110-77481-1qbzxbb/neovim-0.4.3/build/include
Compiled by t@imac.local

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.4.3/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#denite#check
========================================================================
## denite.nvim
  - OK: has("python3") was successful
  - OK: Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: xterm-256color
  - INFO: default-terminal: tmux-256color
  - ERROR: $TERM differs from the tmux `default-terminal` setting. Colors might look wrong.
    - ADVICE:
      - $TERM may have been set by some rc (.bashrc, .zshrc, ...).

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python version: 2.7.17
  - INFO: pynvim version: 0.2.6 (outdated; from ~/Library/Python/2.7/lib/python/site-packages/neovim)
  - WARNING: Latest pynvim is NOT installed: 0.4.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python version: 3.7.7
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-darwin16]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v14.2.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

And just FYI:

```
:verbose set cpoptions
```

results in:

```
cpoptions=aABceFs_$
      Last set from /usr/local/Cellar/neovim/0.4.3/share/nvim/runtime/scripts.vim line 409
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/

set cpoptions+=$

let g:deoplete#enable_at_startup = 1
" Optional delay to help trigger redraw bug
call deoplete#custom#option({'auto_complete_delay': 1000 })
```

## How to reproduce the problem from neovim/Vim startup (Required!)

To trigger the redraw bug:

1. Make sure a long enough `auto_complete_delay` is set so that the popup happens after you've typed and the `$` is drawn.
2. `echo "originaltext" > test.txt`
3. `nvim -u init.vim test.txt`
4. Type `cw` to change the word and then type `foo` or any replacement text
5. Wait for completion popup
6. Leave insert mode
7. Note that instead of seeing just the changed text, "foo", you should see "fooginaltex$"
8. Use `<c-l>` or `:redraw` to see that the change was made but the screen wasn't redrawn to reflect that.

To trigger the other bug where the original text disappears immediately:

1. Make sure no `auto_complete_delay` is set so that popup happens first.
2. `echo "originaltext" > test.txt`
3. `nvim -u init.vim test.txt`
4. Type `cw` to change the word and then type `foo` or any replacement text
7. Note that instead of seeing "orignaltex$" getting replaced as you type it's been completely cleared as if you hadn't set the `$` option.

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
> To trigger the other bug where the original text disappears immediately:

Sorry.  I cannot fix the problem.
I don't recommend for you to use `cpoptions+=$`.
It is only used for vi compatibility.

**Comment by Shougo** [comment]
`cpoptions+=$` conflicts with auto completion popup.
Because if you close the popup, "orignaltex$" will be disappear.
To redraw the popup, deoplete needs to close the popup.

So it is not bug.
