### ISSUE TITLE
Showing longer string from .bib file in popup?

### ISSUE THREAD

**Issue by flimofly** [Shougo/deoplete.nvim#1108]
In a .tex file, when deoplete shows .bib entries in the popup window (after `\cite{`) the data of this entry (notably title) are shortened to the point of being impractical. Is it possible to change this?

I have tried altering `pumwidth` but that doesn't help.

I found the following in an other issue but being a novice at vim I'm not sure whether it's relevant. It doesn't fix the problem when I add it to my .vimrc. 
 `call deoplete#custom#source('jedi', 'max_info_width', 0)`

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('_', 'max_info_width', 0)
```
