### ISSUE TITLE
Lisp patterns

### ISSUE THREAD

**Issue by SevereOverfl0w** [Shougo/deoplete.nvim#111]
There are no patterns for lisp in deoplete#omni#_input_patterns which means that this plugin does not currently work for lisp + dialects (clojure, etc.)

**Comment by Shougo** [comment]
Yes, it is no support.
But I don't use Lisp and Lisp plugins.
I cannot decide the option value for Lisp...
Pull request is wellcome.

**Comment by SevereOverfl0w** [comment]
I'm not sure on the best values to use for lisp either. I'm currently just using "." as my regex (as lisp can take just about anything, just about)

**Comment by Shougo** [comment]
I have no plan to add it.
Pull request is wellcome.  Closing.
