### ISSUE TITLE
gitgutter signs do not update after enabling deoplete

### ISSUE THREAD

**Issue by mroavi** [Shougo/deoplete.nvim#1112]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

**gitgutter** signs are not being updated after enabling **deoplete** with:
```vim
let g:deoplete#enable_at_startup = 1
```
If, however, I switch focus to another tmux pane and back, then the signs get updated.

This problem does not occur if deoplete is not enabled. I have `updatetime` set to `100`.

Here is a gif demonstrating the above:

![git-gutter-bug](https://user-images.githubusercontent.com/19517248/86239145-0bc6e600-bb9f-11ea-8288-4d29840b0a9e.gif)

## Expected

**gitgutter** signs to be updated within 100 ms.

## Environment Information

 * deoplete version (SHA1): a57980ab9d08b11affddc30439f6975e4eb01b41

 * OS:
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

 * neovim/Vim `:version` output:

```
NVIM v0.5.0-577-g48ac77a14
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/gcc-5 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -
Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fst
ack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE
-DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/travis/build/neovim/bot-ci
/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovi
m/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/bu
ild/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-926e4ea1-1710-4627-a936-0e46d2a8c227

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let mapleader = ' '

call plug#begin(stdpath('data') . '/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'neovim/nvim-lsp'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/deoplete-lsp'
Plug 'wincent/pinnacle'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

" vim-gitgutter
let g:gitgutter_map_keys = 0
nmap <Leader>hs <Plug>(GitGutterStageHunk)
nmap <Leader>hu <Plug>(GitGutterUndoHunk)
nmap <Leader>hp <Plug>(GitGutterPreviewHunk)
nmap <Leader>j <Plug>(GitGutterNextHunk)
nmap <Leader>k <Plug>(GitGutterPrevHunk)

" nvim-lsp
" https://github.com/wincent/wincent/blob/master/aspects/vim/files/.vim/after/plugin/nvim-lsp.vim
lua << EOF
  require'nvim_lsp'.clangd.setup{
    cmd = { "clangd", "--background-index", "--fallback-style=Google" };
    filetypes = { "c", "cpp", "objc", "objcpp" };
  }
EOF

nnoremap <buffer> <Leader>gd  <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap <buffer> <Leader>gt  <cmd>lua vim.lsp.buf.declaration()<CR>
nnoremap <buffer> <F2>        <cmd>lua vim.lsp.buf.rename()<CR>
nnoremap <silent> <Leader>gr  <cmd>lua vim.lsp.buf.references()<CR>
nnoremap <silent> <Leader>fo  <cmd>lua vim.lsp.buf.formatting()<CR>
nnoremap <buffer> K           <cmd>lua vim.lsp.buf.hover()<CR>
nnoremap <buffer> <Leader>di  <cmd>lua vim.lsp.util.show_line_diagnostics()<CR>
autocmd BufWritePre *.cpp lua vim.lsp.buf.formatting_sync(nil, 1000)

" deoplete.nvim
let g:deoplete#enable_at_startup = 1

" Tab completion (https://github.com/Shougo/deoplete.nvim/issues/989)
inoremap <silent><expr> <TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

" ultisnips
let g:UltiSnipsExpandTrigger="<C-Space>"
let g:UltiSnipsListSnippets="<C-Tab>"
let g:UltiSnipsJumpForwardTrigger="<C-j>"
let g:UltiSnipsJumpBackwardTrigger="<C-k>"


```

**Comment by Shougo** [comment]
It is not real minimal vimrc.
`nvim-lsp` and `UltiSnips` is really needed??

**Comment by Shougo** [comment]
It works for me.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/src/vim-gitgutter

let g:deoplete#enable_at_startup = 1

" vim-gitgutter
let g:gitgutter_map_keys = 0
nmap <Leader>hs <Plug>(GitGutterStageHunk)
nmap <Leader>hu <Plug>(GitGutterUndoHunk)
nmap <Leader>hp <Plug>(GitGutterPreviewHunk)
nmap <Leader>j <Plug>(GitGutterNextHunk)
nmap <Leader>k <Plug>(GitGutterPrevHunk)
```

Please upload the real minimal vimrc.

```
gitgutter signs are not being updated after enabling deoplete with:

let g:deoplete#enable_at_startup = 1
```

Have you read my minimal vimrc??
I think you should check what change `updatetime` option by `verbose set updatetime?`

**Comment by Shougo** [comment]
> Here is a gif demonstrating the above:

The demonstration should be with minimal vimrc.
Note: your minimal vimrc has not include powerline, so it is not with minimal vimrc.

**Comment by Shougo** [comment]
Please read this.

> Warning: I will close the issue without the minimal init.vim and the reproduction instructions.

And please other issues like this.
https://github.com/Shougo/deoplete.nvim/issues/1102
Note: please compare it with yours.

You think your issue can be reproduce-able everyone by your description?
I don't think so.

**Comment by mroavi** [comment]
I took your remarks into account.

I noticed that the problem might be in the `deoplete-lsp` plugin and not in `deoplete.nvim`.

#### Minimal `init.vim`:
```vim
let mapleader = ' '
set updatetime=100

call plug#begin(stdpath('data') . '/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"Plug 'Shougo/deoplete-lsp'
call plug#end()

let g:deoplete#enable_at_startup = 1
```

#### Demo with minimal `init.vim`

![demo-with-minimal-config-file](https://user-images.githubusercontent.com/19517248/86754005-d27bf380-c040-11ea-98b5-7f6090c61a6a.gif)

Should I open an issue in the `deoplete-lsp` repo?

**Comment by Shougo** [comment]
Reproduced.  It is bug of neovim.
So it is not deoplete or deoplete-lsp issue.

https://github.com/neovim/neovim/issues/12587

**Comment by Shougo** [comment]
Note: deoplete-lsp uses timer feature.  But it breaks CursorHold autocmd in vim-gitgutter plugin.

**Comment by antoinemadec** [comment]
@mroavi @Shougo , could you please try the following plugin and tell me if it fixed your issue?
https://github.com/antoinemadec/FixCursorHold.nvim

**Comment by mroavi** [comment]
I tried the `FixCursorHold.nvim` plugin. It improved the behavior but did not entirely fix the problem. Specifically, after enabling the `FixCursorHold.nvim` plugin, the `gitgutter` sign updates occur without the need to toggle the focus of the Neovim window. However, these updates occur only after leaving insert mode. With `deoplete.lsp` and `FixCursorHold.nvim` disabled, the updates occur almost instantaneously. The only moment when they do not occur instataneously is when the `deoplete` autocompletion menu pops up before the `gigutter` signs are updated. Here are two gifs demonstrating the above: 

### Test 1: `deoplete-lsp` and `FixCursorHold.nvim` disabled:
```vim
" init.vim
let mapleader = ' '
set updatetime=100

call plug#begin(stdpath('data') . '/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
"Plug 'Shougo/deoplete-lsp'
"Plug 'antoinemadec/FixCursorHold.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1
```
![fixcursorhold-test1](https://user-images.githubusercontent.com/19517248/87286003-8de8d000-c4f8-11ea-90bf-c44f5b2c59b6.gif)


### Test 2: `deoplete-lsp` and `FixCursorHold.nvim` enabled:

```vim
" init.vim
let mapleader = ' '
set updatetime=100

call plug#begin(stdpath('data') . '/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/deoplete-lsp'
Plug 'antoinemadec/FixCursorHold.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1
```
![fixcursorhold-test2 gif](https://user-images.githubusercontent.com/19517248/87286016-92ad8400-c4f8-11ea-92dd-961ea445d577.gif)

**Comment by Shougo** [comment]
Because, it hooks CursorMoved event only.
https://github.com/antoinemadec/FixCursorHold.nvim/blob/master/plugin/fix_cursorhold_nvim.vim#L14

It should also hook CursorMovedI and fire CursorHoldI event.
https://github.com/antoinemadec/FixCursorHold.nvim/blob/master/plugin/fix_cursorhold_nvim.vim#L18

**Comment by antoinemadec** [comment]
@Shougo @mroavi , I did not know ```CursorHoldI``` was broken as well.

I just added the support for that as well.
Please update **FixCursorHold.nvim** and all your problems should be solved :sunglasses:

**Comment by mroavi** [comment]
Thanks @antoinemadec and @Shougo. This last update indeed fixes the problem.
