### ISSUE TITLE
Incosistent number of spaces between source-mark and right border in the pmenu

### ISSUE THREAD

**Issue by astier** [Shougo/deoplete.nvim#1119]
## Problem

The number of spaces between the source-mark and the right border in the pmenu is inconsistent.

**NOTE:** I just noticed that the number of spaces between the completions and the left border can also be 0 or 1 as can be seen in the screenshots.

## Expected

The number of spaces between the source-mark and the right border in the pmenu should stay the same. Preferably zero because the completion-matches have also zero spaces between the left border.

## Environment Information

 * deoplete version (SHA1): 7535773

 * OS: Arch Linux

 * NVIM v0.5.0-622-gf26df8bb6

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - OK: escape-time: 0
  - INFO: Checking stuff
  - OK: focus-events: on
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.8 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.8.5
  - INFO: pynvim version: 0.4.1
  - OK: Latest pynvim is installed.

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v14.7.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Perl provider (optional)
  - WARNING: `perl` and `cpanm` must be in $PATH.
    - ADVICE:
      - Install Perl and cpanminus and verify that `perl` and `cpanm` commands work.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## Reproduction

 1. `nvim path/to/minimal-vimrc.vim`
 2. `o` to create new line and enter insert mode
 3. Type `se` -> Multiple spaces after source-mark `[A]`
 4. Delete `se`. Type `ru` -> One space after source-mark `[A]`
 5. Enter instermode at the end of `set runtimepath+=~/.local/share/nvim/plugins/deoplete.nvim/` -> Two spaces after source-mark `[F]`

## Screenshot

![se](https://user-images.githubusercontent.com/36510152/89534966-068c3500-d7f6-11ea-86c6-713c8380f73f.png)

![ru](https://user-images.githubusercontent.com/36510152/89534978-0c821600-d7f6-11ea-9157-88c6c611d88c.png)

![f](https://user-images.githubusercontent.com/36510152/89534984-10159d00-d7f6-11ea-92f4-43bf79349776.png)

**Comment by Shougo** [comment]
I have checked the implementation.
deoplete does not add the spaces.  It adds Vim/neovim.

`:help pumwidth`

```
						*'pumwidth'* *'pw'*
'pumwidth' 'pw'		number	(default 15)
			global
	Minimum width for the popup menu (|ins-completion-menu|).  If the
	cursor column + 'pumwidth' exceeds screen width, the popup menu is
	nudged to fit on the screen.
```

`set pumwidth=5` fixes your problem.
