### ISSUE TITLE
can't write g when pressing g at insert mode

### ISSUE THREAD

**Issue by a43mrk** [Shougo/deoplete.nvim#1126]
Im at spacevim but using deoplete.
when pressing g something blocks me to write g
with the error:
[coc.nvim]: Some plugin change completeopt on insert mode: Last set from ~/.SpaceVim/bundle/deoplete.nvim/autoload/deoplete/mapping.vim line 84!

**Comment by Shougo** [comment]
coc.nvim conflicts with deoplete.
You need to remove deoplete or coc.nvim.
