### ISSUE TITLE
Prefix selection options with numbers

### ISSUE THREAD

**Issue by Timoses** [Shougo/deoplete.nvim#1127]
# Problems summary
I would like to prefix all options in the popupmenu with an incremental number in order to select an option more easily. The reason is to use voice controlled vim where it would be highly helpful to simply spot an option in the popupmenu and say '3' for the 3rd entry in the menu.

## Expected
Something like the following

```
1. def  keyword [jedi]
2. defc snippet [US] class method with docstrings
3. def  snippet [US] function with docstrings
4. deff snippet [US] function or class method
5. defi snippet [US]
6. defm snippet [US]
7. defs snippet [US] static method with docstrings
```

Numbers `1.` through `7.` are useful to visually and quickly select an option (and let e.g. a voice recognition do the rest of actually selecting that option).

## Environment Information

 * deoplete version (SHA1): latest

 * OS: MacOS

 * neovim/Vim `:version` output: NVIM v0.4.3

 * `:checkhealth` or `:CheckHealth` result(neovim only): / healthy /

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.

But you can nearly add the feature like this.

```vim
call deoplete#custom#option('candidate_marks',
      \ ['A', 'S', 'D', 'F', 'G'])
inoremap <expr>A       pumvisible() ? deoplete#insert_candidate(0) : 'A'
inoremap <expr>S       pumvisible() ? deoplete#insert_candidate(1) : 'S'
inoremap <expr>D       pumvisible() ? deoplete#insert_candidate(2) : 'D'
inoremap <expr>F       pumvisible() ? deoplete#insert_candidate(3) : 'F'
inoremap <expr>G       pumvisible() ? deoplete#insert_candidate(4) : 'G'
```
