### ISSUE TITLE
does refresh_always feature only based on change of col?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#113]
@Shougo 
I hava tested YCM neocomplete and deoplete,and I find neocomplete and deoplete's refresh_always feature only base on the changging of col,I think the change of line should be taken into account；
for example
```java
class Foo{
     void test(){
    Date. _  // cursor here can not complete static method,because we do not import Date;
}
}
```
then i move my cursor on Date and type F4(imap to JCimportAdd),after type F4 ,the java file change 
to 
```java
import java.util.Date;

class Foo{
     void test(){
    Date. _  // cursor here can not complete static method,because we do not import Date;
}
}
```
then after the dot,i still can not complete method,i need to source omni manually;I am using \+tab
```vim
    inoremap <silent> <Leader><Tab> <C-r>=MyLeaderTabfunc()<CR>
function! MyLeaderTabfunc() abort
    let g:javacomplete_neosnippet_Toggler = 1
    let g:neosnippet#enable_complete_done = 0
    return "\<c-x>\<c-o>\<c-p>"
endfunction

```

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
Hi @Shougo still same as before,

**Comment by wsdjeg** [comment]
@Shougo  my fault ,it works well ,after using NeobundleUpdate deoplete.nvim, still same as before,but after using Unite neobundle/update ,everything works well, I think maybe `NeobundleUpdate deoplete.nvim` do not registered rplugin,
