### ISSUE TITLE
Flickering with each letter typed (Neovim 0.5)

### ISSUE THREAD

**Issue by tami5** [Shougo/deoplete.nvim#1134]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Completion popup flicker on every additional letter and on backspace.

## Expected

Completion window doesn't flicker when a letter get typed or get deleted.

## Environment Information

 * deoplete version (SHA1): `db9ed8bd9299ede8444f01f9aae0a76dea9231af`
 * OS: `Arch`
 * neovim/Vim `:version` output: 
  - `NVIM v0.5.0-705-g9f704c88a`
   - `LuaJIT 2.0.5`
   - `Features: +acl +iconv +tui`

 * `:checkhealth` or `:CheckHealth` result(neovim only): all OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!) 
```vim
set runtimepath+=~/.local/share/nvim/site/pack/packer/start/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```
## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Install
 2. Open a file 
 3. Type a keyword then as you type it flickers/flashes

## Upload the log file
No log was generated

**Comment by Shougo** [comment]
> Completion popup flicker on every additional letter and on backspace.

It is the feature.  Because, Vim cannot update the popup without close the popup.
I think your machine's spec  is low.

And you can disable auto refresh feature.

```vim
    call deoplete#custom#option({
    \ 'refresh_always': v:false,
    \ })
```

**Comment by Shougo** [comment]
My configuration is:

```vim
call deoplete#custom#option({
      \ 'auto_refresh_delay': 10,
      \ 'camel_case': v:true,
      \ 'skip_multibyte': v:true,
      \ 'auto_preview': v:true,
      \ })
call deoplete#custom#option('num_processes', 1)
```

**Comment by Shougo** [comment]
And you have ignored the issue template.

```
    Install
    Open a file
    Type a keyword then as you type it flickers/flashes
```

Your instruction is very fuzzy and no one cannot reproduce it.

**Comment by Shougo** [comment]
>NVIM v0.5.0-705-g9f704c88a

This version is very old.  My version is `NVIM v0.5.0-3600`.
Why don't you upgrade neovim to the latest version??

**Comment by tami5** [comment]
Hey @Shougo thanks so much for taking a look into my issue 

>  Because, Vim cannot update the popup without close the popup.
I think your machine's spec is low.

Oh so my thats why am experiencing the same issue with both nvim-completion and deoplete. I'm used to coc and perhaps as someone else pointed out coc might be using floating windows.

> Your instruction is very fuzzy and no one cannot reproduce it.

Sorry about that, it is simply installing the plugin and then trying to complete

I just tested and seem

> My configuration is:

Copied it over it seem to improve the experience a bit.


> Why don't you upgrade neovim to the latest version??

I just upgrade now I'm on `v0.5.0-751-gd198aa511`, and I don;t see any big difference

**Comment by tami5** [comment]
@Shougo is it possible to add or consider something like support for floating window completion in upcoming releases. Thanks

**Comment by Shougo** [comment]
>@Shougo is it possible to add or consider something like support for floating window completion in upcoming releases. Thanks

No means.  coc does not use floating window for it.  I have read the code.
coc use `equal` for popup.  deoplete already use it.

**Comment by Shougo** [comment]
> Sorry about that, it is simply installing the plugin and then trying to complete

Please read other issues.

**Comment by Shougo** [comment]
Please update deoplete to the latest.

**Comment by tami5** [comment]
> Please update deoplete to the latest

On it

**Comment by tami5** [comment]
Wow db9ed8b defintaly got rid of the flicker issue I had, along with the following configuration 
```
    call deoplete#custom#option({ 'auto_refresh_delay': 10, 'smart_case': v:true, 'skip_multibyte': v:true, 'auto_preview': v:true, })
    call deoplete#custom#option('num_processes', 1)
```

Thanks @Shougo , I think that fixed my issue, but I should tested it more, I wonder what does the line you've add does.

```viml

  let auto_popup = deoplete#custom#_get_option(
        \ 'auto_complete_popup') !=# 'manual'
  if auto_popup || deoplete#util#check_popup()
    " For popup flicker
    call feedkeys("\<Plug>_", 'i')
  endif
```

Also, if I may add, I think a set height and width might improve my experience further. I look into the docs to achieve this

**Comment by tami5** [comment]
After playing around with the option "num_processes" seem to be a factor to the flickering, and setting it to 1/disable fix the flickering issue. 

I'd like to know what num_processes do and what benefit it does offer, and would disable it effect (ps. you don't have to answer that)

**Comment by Shougo** [comment]
> Thanks @Shougo , I think that fixed my issue, but I should tested it more, I wonder what does the line you've add does.

It remains popup window.

> Also, if I may add, I think a set height and width might improve my experience further. I look into the docs to achieve this

`:help pumwidth`, `:help pumheight`

> After playing around with the option "num_processes" seem to be a factor to the flickering, and setting it to 1/disable fix the flickering issue.

It improves completion performance, but it adds flicker issue.

**Comment by tami5** [comment]
@Shougo I got to configuring and setting up nvim_lsp and it seems that my options is causing completion to be delayed significantly from the lsp. For example when I type vim. <nothing
then if I do vim.fn<backspace it shows completion. I had to enable back completion-nvim to make sure that it isn't a nvim_lap problem.

**Comment by Shougo** [comment]
Unfortunately, my fix has the problem.
https://github.com/Shougo/deoplete.nvim/issues/1135

I have disabled the feature...
