### ISSUE TITLE
 deoplete-vim-lsp not working in a single process

### ISSUE THREAD

**Issue by lighttiger2505** [Shougo/deoplete.nvim#1140]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Upgrading to the latest version of deoplete.nvim caused deoplete-vim-lsp completion to not working.
This problem occurs if you are later than the following version.
https://github.com/Shougo/deoplete.nvim/commit/f439759515703b608d16f55b5f6f19fc9cdb52ba

## Expected

After debugging deoplete-vim-lsp, I found that the [deoplete.nvim callback function](https://github.com/lighttiger2505/deoplete-vim-lsp/blob/2ea06074/autoload/deoplete_vim_lsp.vim#L41) is not working properly.
deoplete-vim-lsp gets the completion candidates successfully, but deoplete.nvim doesn't call for getting the completion candidates via callback, so you won't see them as a result.

I'm working on an interim solution to this problem by reverting deoplete-vim-lsp back to using the context is_async method. However, this method is deprecated.
https://github.com/Shougo/deoplete.nvim/blob/80152d09/doc/deoplete.txt#L1268-L1270

Isn't a similar plugin [deoplete-lsp](https://github.com/Shougo/deoplete-lsp) having the same problem?

## Environment Information

 * deoplete version (SHA1): 80152d0940b0d572711b0c89c6c2f1af7a0faaa9
 * OS: Arch Linux x86_64
 * neovim/Vim `:version` output: NVIM v0.4.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/deopleteissue')

Plug 'Shougo/deoplete.nvim'
Plug 'prabirshrestha/vim-lsp'
" This branch was made specifically for this issue, and master doesn't have this problem
Plug 'lighttiger2505/deoplete-vim-lsp', { 'branch': 'deoplete-issue' }

call plug#end()

let g:deoplete#enable_at_startup = 1
if executable('gopls')
    augroup LspGo
        autocmd!
        autocmd User lsp_setup call lsp#register_server({
           \ 'name': 'gopls',
           \ 'cmd': {server_info->['gopls', '-mode', 'stdio']},
           \ 'allowlist': ['go'],
           \ })
    augroup END
endif
```

Adding this setting will cause deoplete to behave as expected.

```vim
call deoplete#custom#option({
\ 'num_processes': 4,
\ })
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Launch Vim.
    ```sh
    vim main.go
    ```
 1. Write simple code to perform the completion. For example, here's the code.
    ```go
    package main

    func main() {
        fmt.
    }
    ```
 1. Move the cursor behind `fmt.` to switch to inserts mode

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Thanks.  Fixed.

**Comment by lighttiger2505** [comment]
@Shougo I have updated deoplete.nvim to the most recent version. The problem was not resolved.

**Comment by Shougo** [comment]
It works for me...
Can you debug it?

**Comment by lighttiger2505** [comment]
It seems I was wrong. The problem was fixed. Thanks!!!

**Comment by Shougo** [comment]
Oh, OK.
