### ISSUE TITLE
Autocomplete popup only active when I hit CNTRL+n during insert mode

### ISSUE THREAD

**Issue by tommyc38** [Shougo/deoplete.nvim#1145]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Autocomplete popup only active when I hit CNTRL+n during insert mode.

## Expected

I would expect the default settings to work which per the documentation say is set to 'auto'

## Environment Information

 * deoplete version (SHA1):

 * OS:

    OSX 10.13.6

 * neovim/Vim `:version` output:

   NVIM v0.4.4

 * `:checkhealth` or `:CheckHealth` result(neovim only):

  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

" For Vim only
"set runtimepath+=~/path/to/nvim-yarp/
"set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
I don't understand your issue.
Closing.

Please don't ignore issue template.

**Comment by Shougo** [comment]
You need to upload the minimal vimrc.
