### ISSUE TITLE
popup menu location -- question

### ISSUE THREAD

**Issue by tklebanoff** [Shougo/deoplete.nvim#1147]
Hello there,
First, I love deoplete.  It is great.  I use it every day.  Thank you!
Second, I have two questions/feature requests -- maybe there is a simple way I can configure this on my own.  What do you think?  I am not deeply familiar with the codebase.  Perhaps you may be able to provide an answer or point me in the right direction.

1a) is there any standard way to configure the popup menu to show up to the top-left of the cursor instead of the bottom-right?
1b) is there any standard way to configure the popup menu to show up on a part of the screen far away from the code being edited?  

I dont mind moving my eyes away from the edit cursor to scan through the list of potential auto completions.  Unfortunately, the popup often appears right over the text I am focused on while typing.  This can be distracting!

In the meantime, I will do some more investigation into the codebase to see if I can fix it for my purposes myself in my own fork.  If I can figure out a solution, I will let you know!

Thanks for any help in advance!

**Comment by Shougo** [comment]
Unfortunately, it cannot be supported.
It is same behavior with other auto completion plugins and other editors.
