### ISSUE TITLE
Disable auto-completion on backspace character

### ISSUE THREAD

**Issue by renkenn** [Shougo/deoplete.nvim#1149]
Assume the presence of the instruction `pthread_mutex_lock`, current behaviour is that if you delete `kcol` (lock in reverse) you still get suggestions for every character deletion which can be distracting. Preferably I'd want to disable auto-completion on backspace character input and have it so that user will have to remove then write one character to reactivate auto-completion.

Example:

* `pthread_mutex_lock`
* `<BKSPC>` x5, suggestions **should not** show up
* `pthread_mutex`
* insert `_`
* `pthread_mutex_` suggestions show up

I called `:call deoplete#custom#option('skip_chars',['\b'])` in NVIM v0.4.4 and I still don't get the expected behavior.  I also tried `call deoplete#custom#option('skip_chars', ['\b'])`.

Could it be that `skip_chars` does not work with special characters? Or only checks the character at the cursor position and not the actual key pressed. For example, if you have `func(` and then press `BACKSPACE` the character at cursor is `c`. 

I think the related function is `deoplete#util#get_input()` defined in `autoload/deoplete/util.vim`. Judging by the call of `getline()`, I think it's impossible to skip on **input** chars with the current implementation?

Your thoughts on this? Can this be implemented assuming the current one can't handle it?

 * deoplete version (SHA1): Last commit `e7f4c206287e867fe4991f6de76a12107fa14593`

**Comment by Shougo** [comment]
I think other auto completion frameworks has same behavior...

**Comment by Shougo** [comment]
`skip_chars` does not work for special characters.  It is Vim/neovm's limitation.

**Comment by renkenn** [comment]
This works very nicely @Shougo. Thank you very much!
