### ISSUE TITLE
Close preview window after completion?

### ISSUE THREAD

**Issue by Torwori** [Shougo/deoplete.nvim#115]
Is there a way to automatically close the preview window after a completion is made?

**Comment by beezz** [comment]
Hi Torworl,

e.g. from my .vimrc

```
" close preview window on leaving the insert mode
autocmd InsertLeave * if pumvisible() == 0 | pclose | endif
```

Deoplete does not have an option for this.

**Comment by Shougo** [comment]
I think you should use echodoc....

@beezz 

```vim
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
```

is better.

**Comment by Torwori** [comment]
Thanks guys.

**Comment by jamesblau** [comment]
Does this autocommand:

`autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif`

Not give you the error:

```
Error detected while processing InsertLeave Auto commands for "*":                                                                                                                    
E11: Invalid in command-line window; <CR> executes, CTRL-C quits:  pclose | endif
```

When you exit insert mode from the command-line window, because of the pclose?

To reproduce:

`:<C-G>i<Esc>`

**Comment by Shougo** [comment]
> When you exit insert mode from the command-line window, because of the pclose?

Yes.

**Comment by Shougo** [comment]
Please read the documentation.

```
Q: I want to close the preview window after completion is done.

A: >
        autocmd CompleteDone * silent! pclose!
<
Or
>
	autocmd InsertLeave * silent! pclose!
<

```

You must use `silent! pclose` instead of `pclose`.

```vim
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | silent! pclose | endif
```
