### ISSUE TITLE
Doesn't work with vim package manager.

### ISSUE THREAD

**Issue by smekkley** [Shougo/deoplete.nvim#1152]
How to reproduce:
1. cd ~/.vim/pack/git-plugins/start
2. git clone https://github.com/Shougo/deoplete.nvim.git
3. Start vim and you get exceptions and no completion works.

**Comment by Shougo** [comment]
Please don't ignore the issue template.
Please read other issues and compare with yours.

**Comment by Shougo** [comment]
> Start vim and you get exceptions and no completion works.

What is the exceptions?
And why don't you upload the minimal vimrc?

**Comment by smekkley** [comment]
vimrc is empty. I might paste the exception if I install it again. It's not functional for built-in vim package manager users in any case.

**Comment by Shougo** [comment]
deoplete doesn't work if vimrc is empty.
Why don't you read the documentation?

**Comment by smekkley** [comment]
Oh, it's supposed to crash just by git checkout? I might do that when I try this plugin next time.

**Comment by Shougo** [comment]
I don't know.
I don't work for it without minimal vimrc.
