### ISSUE TITLE
Could not load source ghc.py correctly

### ISSUE THREAD

**Issue by ggerico** [Shougo/deoplete.nvim#1153]
# Problems summary
this message appears when starting nvim:

```
[deoplete] Traceback (most recent call last):
  File "/Users/germain/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/child.py", line 112, in _add_source
    source = Source(self._vim)
  File "/Users/germain/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/ghc.py", line 29, in __init__
    self.__executable_ghc = self.vim.funcs.executable('')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvim/api/nvim.py", line 299, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Vim:E928: String required
Could not load source: /Users/germain/.config/nvim/bundle/.cache/init.vim/.dein/rplugin/python3/deoplete/sources/ghc.py.
```

## Expected
Things going smoothly at startup. However the neovim LSP completion (deoplete.nvim and deoplete-lsp plugins) works perfectly well.

## Environment Information

```bash
$ pip3 install --user --upgrade pynvim
Requirement already satisfied: pynvim in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (0.4.2)
Requirement already satisfied: msgpack>=0.5.0 in ./Library/Python/3.9/lib/python/site-packages (from pynvim) (1.0.2)
Requirement already satisfied: greenlet in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from pynvim) (0.4.17)
```

 * deoplete version (SHA1): 2849fa544b9a3a07ec1ddafb2bb6f72945b24c62

 * OS: Macos 11.1

 * neovim/Vim `:version` output:
NVIM v0.5.0-dev+5ce328df4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/tmp/neovim-20201218-70330-utz9oc/build/config -I/tmp/neovim-20201218-70330-utz9oc/src -I/usr/local/include -I/tmp/neovim-20201218-70330-utz9oc/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk/usr/include -I/usr/local/opt/gettext/include -I/tmp/neovim-20201218-70330-utz9oc/build/src/nvim/auto -I/tmp/neovim-20201218-70330-utz9oc/build/include
Compiled by germain@MacBookPro-2.local

Features: +acl +iconv +tui

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
  | - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
  | - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
  | - $ nvim
  | - $ cat /tmp/log_{PID}
  | - and then create an issue on github

```vim
" Your minimal init.vim/vimrc
set completeopt=longest,menuone,preview
autocmd FileType erlang :let g:deoplete#disable_auto_complete = 1
let g:deoplete#enable_at_startup = 1 
let g:deoplete#enable_ignore_case = 1 
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif 
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. open nvim

**Comment by Shougo** [comment]
You need to install `ghc-mod` or `hhpc`.
Have you read the documentation??

**Comment by Shougo** [comment]
And you use `neco-ghc`.  But it is not included in your information.
Have you read the issue template correctly?

**Comment by ggerico** [comment]
Sorry about that, thanks a lot!

**Comment by Shougo** [comment]
OK
