### ISSUE TITLE
[NOT AN ISSUE] How to disable the message underneth the line?

### ISSUE THREAD

**Issue by Godnyx** [Shougo/deoplete.nvim#1155]
I use Neovim and I have set "noshowmode" and now deoplete shows a massage for the matches when I'm on insert mode. Something like "match 1 of 6", "The only match" etc. This is shown underneath the line. I tried to look on documentation but haven't find anything.

**Comment by Shougo** [comment]
It is already documented.

```
Q: I want to silence the |ins-completion-menu| messages in the command line
   such as "-- XXX completion (YYY)", "match 1 of 2", "The only match",
   "Pattern not found", "Back at original", etc.

A: You can disable the messages through the 'shortmess' option. >

	set shortmess+=c
```

> I tried to look on documentation but haven't find anything.

Really?  I can find it easily.
