### ISSUE TITLE
Duplicated source/filter errors when use deoplete with fzf.vim and vim-polyglot

### ISSUE THREAD

**Issue by iven** [Shougo/deoplete.nvim#1156]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

When I use fzf.vim to open a file, a lot of error messages appears in the status line, here is some of them when I run `:messages`:

```
[deoplete] Duplicated source: buffer.  Use :messages / see above for error details.
[deoplete] path: "/Users/iven/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py" "/Users/iven/Workspace/MyHomeSettings/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/buffer.py".  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_word_abbr.  Use :messages / see above for error details.
[deoplete] path: "/Users/iven/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_word_abbr.py" "/Users/iven/Workspace/MyHomeSettings/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_word_abbr.py".  Use :messages / see above for error details.
[deoplete] Duplicated filter: converter_case.  Use :messages / see above for error details.
[deoplete] path: "/Users/iven/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_case.py" "/Users/iven/Workspace/MyHomeSettings/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/filter/converter_case.py".  Use :messages / see above for error details.
```

**BTW, I soft linked my `/Users/iven/Workspace/MyHomeSettings/.config/nvim` to `/Users/iven/.config/nvim`, maybe this caused the error.**

If I remove either fzf.vim or vim-polyglot, there's no error messages.

## Expected

No error messages.

## Environment Information

 * deoplete version (SHA1): b098a5286e95c456d91eed3589a2850aae421219

 * OS: macOS 11.1

 * neovim/Vim `:version` output:
 
```
NVIM v0.4.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough
-Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/config -I/tm
p/neovim-20200808-89283-1us0ytm/neovim-0.4.4/src -I/usr/local/include -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/deps-build/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include -I/usr/local/opt/gettext/i
nclude -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/src/nvim/auto -I/tmp/neovim-20200808-89283-1us0ytm/neovim-0.4.4/build/include

Features: +acl +iconv +tui
See ":help feature-compile"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 
```
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin()
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim', { 'on': ['Files', 'GitFiles', 'Colors', 'Rg'] }
Plug 'sheerun/vim-polyglot'
call plug#end()

let g:deoplete#enable_at_startup = 1

nnoremap <C-P> :GitFiles<CR>
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Open neovim
 2. Use `Ctrl-P` to open a file
 3. The error messages appears.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

![image](https://user-images.githubusercontent.com/56165/103864827-3bcae500-50fe-11eb-9000-f478e3984cba.png)

**Comment by iven** [comment]
I'm afraid after update to 028ebd60d5ad963bf8f77e13c2a85e9edb190f48 the error still exists.

**Comment by Shougo** [comment]
Really?
Please create the reproduce-able instruction.
If not, I will ignore your report.

**Comment by Shougo** [comment]
Your instruction is not reproduce-able.
Because it depends on symbolic link.

**Comment by Shougo** [comment]
I think you have mistaked the instruction.
Because Vim doesn't load add runtimepath automatically after loaded fzf or Vim-polygot.
It is from your configuration.

**Comment by iven** [comment]
I found that the duplicated source errors disappeared, and the duplicated filter errors still exists. Maybe you forgot to resolve symbolic links in `_add_filter` like you did in `_add_source`?

**Comment by Shougo** [comment]
OK.  I will check.

**Comment by Shougo** [comment]
Fixed.
