### ISSUE TITLE
[Workaround] List submodules

### ISSUE THREAD

**Issue by nikisix** [Shougo/deoplete.nvim#1159]
# Problem summary
Take python's `math` module for instance. Assume it has `exp` and `log` sub-modules.
In a blank file we:
```
import math

math.
```
Nothing happens.

## Expected
```
import math

math.
(autocomplete dropdown)
{
    exp()
    log()
}
```

## Workaround
```
import math

math.(<tab>
```
That is, type: math-dot-openparen-tab
One more time, that is:
```
math
.
(
<Tab>
```
Would be great if "math." triggered listing sub-modules.
Is there a simple way to get there I'm missing?
Hope this helps other folks, for me it was a game-changer.

Thanks Shougo for Deoplete :pray: 

## Environment Information

 * deoplete version (SHA1): `Version: 6.1`

 * OS: `Debian 10`

 * neovim/Vim `:version` output: `NVIM v0.3.4`

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

"manual autocomplete (from the deoplete docs)
inoremap <silent><expr> <TAB>
		\ pumvisible() ? "\<C-n>" :
		\ <SID>check_back_space() ? "\<TAB>" :
		\ deoplete#manual_complete()
		function! s:check_back_space() abort "{{{
		let col = col('.') - 1
		return !col || getline('.')[col - 1]  =~ '\s'
		endfunction"}}}


" For Vim only
"set runtimepath+=~/path/to/nvim-yarp/
"set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

## How to reproduce the problem from neovim/Vim startup (Required!)
1. open a python file
2. import math
3. math"."

**Comment by Shougo** [comment]
Please use `deoplete-jedi` for it.

https://github.com/deoplete-plugins/deoplete-jedi
