### ISSUE TITLE
Ignores sources not working

### ISSUE THREAD

**Issue by tony** [Shougo/deoplete.nvim#116]
I would think that ``g:deoplete#ignore_sources`` would follow the same signature as ``g:deoplete#sources``.  See my documentation here: https://github.com/Shougo/deoplete.nvim/compare/master...tony:ignore-sources-doc?expand=1

When I use ``b:deoplete#ignore_sources = ['buffer']`` I get an error:

![2016-01-09-095756_1278x708_scrot](https://cloud.githubusercontent.com/assets/26336/12216937/7928230e-b6b7-11e5-9295-b9270ca01eb6.png)

When I use ``b:deoplete#ignore_sources`` as perscribed in the documentation of my [pull request](https://github.com/Shougo/deoplete.nvim/compare/master...tony:ignore-sources-doc?expand=1), I still get buffers showing up:

![2016-01-09-094718_1278x708_scrot](https://cloud.githubusercontent.com/assets/26336/12216926/d7e80f7c-b6b6-11e5-821f-3516e1391ff1.png)

![2016-01-09-094736_1278x708_scrot](https://cloud.githubusercontent.com/assets/26336/12216922/b9e0a444-b6b6-11e5-902b-a4922e67edb9.png) 

I'm using deoplete at 1a9617948ee3a7dd4dcef302b32cc2d4e3e1b14c. Here's the rest of my deoplete config: https://github.com/tony/vim-config/blob/master/settings/deoplete.vim

nvim version v0.1.2-189-gc154462

**Comment by wsdjeg** [comment]
do you try with `b:deoplete_ignore_sources`

**Comment by tony** [comment]
The behavior is inconsistent both ways.

With autocmd CmdwinEnter * let b:deoplete_ignore_sources = ['buffer’]

I get no errors, but still see [b] suggestions. For a time, I mistakenly did let b:deoplete_sources = [‘buffer’] and saw the C file showed no [b] suggestions.

When I go into .vimrc, I see [b] again. When I open the same C file outside of tmux, I see [b] again.


On January 9, 2016 at 11:06:10 AM, Wang Shidong (notifications@github.com) wrote:

do you try with b:deoplete_ignore_sources

**Comment by tony** [comment]
Is the logic to ignore sources implemented yet? Or part of another repository?

I did grep and ag for ``ignore`` but don't see anything for ignoring sources outside of loading the configs and docs.

**Comment by wsdjeg** [comment]
I just tested with `let b:deoplete_ignore_sources = ['buffer']` also get the same result,maybe we needs help from Shougo

**Comment by wsdjeg** [comment]
@tony
https://github.com/Shougo/deoplete.nvim/issues/120
here is what you want

**Comment by wsdjeg** [comment]
this value is dict ,we should not use list

**Comment by Shougo** [comment]
Fixed.
