### ISSUE TITLE
If you do not set'g:deoplete#lsp#use_icons_for_candidates', you will get an error.

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1161]
# Problems summary
If you do not set'g:deoplete#lsp#use_icons_for_candidates', you will get an error.

## Expected
The default value for "g:deoplete#lsp#use_icons_for_candidates" is set to "False", so no error will occur even if it is not set.

## Environment Information

 * deoplete-lsp version (SHA1): 0b75ca15d94d3fdbbaab321a70182d8f67c55823

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-dev+nightly-569-gb894fbcbe

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

call dein#begin(s:dein_dir, expand('<sfile>'))
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/deoplete.nvim')
call dein#add('deoplete-plugins/deoplete-lsp')
call dein#add('neovim/nvim-lspconfig')
call dein#end()
call dein#save_state()

if has('vim_starting') && dein#check_install()
    call dein#install()
endif

lua require'lspconfig'.tsserver.setup {capabilities = capabilities}
call deoplete#custom#option('sources', {'typescript': ['buffer', 'lsp']})
call deoplete#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `$ npm install -g typescript typescript-language-server`
 2. `$ touch index.ts`
 3. `$ nvim index.ts`
 4. Type `console`.

**Comment by Shougo** [comment]
This is not the issue of deoplete!
It is the issue of deoplete-lsp.

**Comment by Shougo** [comment]
Please use the latest version of deoplete-lsp.
I have fixed it.

**Comment by nabezokodaikon** [comment]
I'm sorry I made a mistake in Issue.
However, `deoplete-lsp` is described as `call dein#add('deoplete-plugins/deoplete-lsp')`.

I confirmed that it was fixed.
Thank you very much.

**Comment by Shougo** [comment]
Oh.  I have not found.
