### ISSUE TITLE
[Question] How can I prevent the completion from appearing after the semicolon?

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1166]
# Problems summary
After typing a semicolon at the end, a completion popup appears.

## Expected
I don't want the completion popup to appear after I type a semicolon at the end.

## Environment Information

 * deoplete version (SHA1): fc928a62d513ba2e27f83a63600747dde7aa5d65

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-dev+nightly-605-g6b7cc45c4

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if &compatible
    set nocompatible
endif

filetype off
filetype plugin indent off

let $CACHE = expand('~/.cache')
if !isdirectory(expand($CACHE))
    call mkdir(expand($CACHE), 'p')
endif

let s:dein_dir = expand('$CACHE/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    execute 'set runtimepath^=' . s:dein_repo_dir
endif

if !dein#load_state(s:dein_dir)
    finish
endif

call dein#begin(s:dein_dir, expand('<sfile>'))

call dein#add('neovim/nvim-lspconfig')
call dein#add('Shougo/deoplete.nvim')
call dein#add('Shougo/deoplete-lsp')

call dein#end()
call dein#save_state()

if has('vim_starting') && dein#check_install()
    call dein#install()
endif

lua require'lspconfig'.tsserver.setup{}

call deoplete#custom#option('sources', {'typescript': ['lsp']})
call deoplete#enable()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. `$ mkdir -p issue/src`
 2. `$ cd issue`
 3. `$ yarn init -y`
 4. `$ yarn add --dev typescript`
 5. `$ yarn add --dev @types/node`
 6. `$ ./node_modules/.bin/tsc --init --rootDir src --outDir dist --esModuleInterop --resolveJsonModule --lib es6,dom --module commonjs`
 7. `$ touch src/index.ts`
 8. `$ nvim src/index.ts`

## Screenshot (if possible)

<img width="719" alt="スクリーンショット 2021-02-25 1 03 49" src="https://user-images.githubusercontent.com/3197942/109030164-edea5a80-7706-11eb-8a27-7cee340b0919.png">

**Comment by Shougo** [comment]
Note: This is not deoplete problem.  It is just deoplete-lsp problem.

**Comment by Shougo** [comment]
You can configure `input_pattern`.

```vim
call deoplete#custom#source('lsp', 'input_pattern', '[a-zA-Z_]\w*$')
```

**Comment by nabezokodaikon** [comment]
> Note: This is not deoplete problem. It is just deoplete-lsp problem.

I made a mistake again. sorry.

**Comment by nabezokodaikon** [comment]
> You can configure `input_pattern`.
> 
> ```viml
> call deoplete#custom#source('lsp', 'input_pattern', '[a-zA-Z_]\w*$')
> ```

it is complete. Thank you for teaching me.

**Comment by Shougo** [comment]
lsp source checks all inputs unfortunately.

**Comment by nabezokodaikon** [comment]
I see.
