### ISSUE TITLE
Setting sources for multiple filetype buffers

### ISSUE THREAD

**Issue by roylez** [Shougo/deoplete.nvim#1167]
# Problems summary

I use multiple filetype `markdown.vim-edit` for some ad-hot editing, I can set deoplete sources for `markdown`, or for `vim-edit`, but sources for `markdown.vim-edit` defaults to what is set for `_`.

## Expected

muti filetype buffers should have sources inherited from every types

## Environment Information

 * deoplete version (SHA1): aa32bd

 * OS: macOS Big Sur

 * neovim/Vim `:version` output:

     VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Dec 19 2020 21:23:05)

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call deoplete#custom#option({
            \'sources': {
            \'_': ['buffer'],
            \'markdown': ['buffer', 'dictionary'],
            \'vim-edit': ['buffer', 'dictionary']})
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Start with the above configuration. Open a markdown file, buffer and dictionary completion should be both there. `set ft=markdown.vim-edit`, and dictionary completion will be gone.

 2. add `'markdown.vim-edit': ['buffer', 'dictionary']` to configuration, and reopen the file, dictionary completion will be available.

**Comment by Shougo** [comment]
Fixed.

**Comment by roylez** [comment]
Thanks a lot. It works great.
