### ISSUE TITLE
Deoplete shows results when inserting a semicolon

### ISSUE THREAD

**Issue by daniel-bencic** [Shougo/deoplete.nvim#1168]
# Problems summary
Deoplete completion triggers when entering a semicolon and shows standard results.

## Expected
Deoplete doesn't show any results.

## Environment Information

 * deoplete version (SHA1): b05a60c81572994eb9b4e1aa5c1c5dba98e10349

 * OS: Gentoo

 * neovim/Vim `:version` output:
NVIM v0.4.4
Build type: Gentoo
Lua 5.1

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
"" language servers
if executable('pyls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'pyls',
        \ 'cmd': {server_info->['pyls']},
        \ 'whitelist': ['python'],
        \ })
endif

if executable('rls')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'rls',
        \ 'cmd': {server_info->['rustup', 'run', 'stable', 'rls']},
        \ 'workspace_config': {'rust': {'clippy_preference': 'on'}},
        \ 'whitelist': ['rust'],
        \ })
endif

""" deoplete completion
let g:deoplete#enable_at_startup = 1

call deoplete#custom#option({
\ 'max_list': 10,
\ })

## How to reproduce the problem from neovim/Vim startup (Required!)
1. Insert semicolon

## Screenshot (if possible)
![Screenshot from 2021-03-30 00-46-42](https://user-images.githubusercontent.com/24390851/112910603-fcf06e00-90f3-11eb-9f20-2b1819b92927.png)
![Screenshot from 2021-03-30 00-47-12](https://user-images.githubusercontent.com/24390851/112910610-ff52c800-90f3-11eb-80ba-828bd80b6edd.png)

**Comment by Shougo** [comment]
Note:  Please read the statement.
>Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

Your vimrc is not minimal!
We need to use ESP skills to investigate your problem.

It is deoplete-vim-lsp issue instead.
deoplete-vim-lsp calls when every non space character input by the line.

https://github.com/lighttiger2505/deoplete-vim-lsp/blob/af5432f1e063fd4c3a5879aa8c2afe82c17dc1c9/rplugin/python3/deoplete/sources/vim_lsp.py#L15
