### ISSUE TITLE
Question: How to make deoplete use all sources for PHP including Omni ?

### ISSUE THREAD

**Issue by khalidchawtany** [Shougo/deoplete.nvim#117]
I have *phpcd.vim* installed and I can confirm it's working using ```ctrl-x xtrl-o```. 
However, I cannot make deoplete show the Omni-completion results including other sources (like: buffer, file, UltiSnips,  etc.).

If I put the following in my *init.vim*, I get **ONLY Omni-completion**.
```vim
   let g:deoplete#omni_patterns = {}
   let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
```
If I remove the above lines I get **all other sources except Omni-completion**.

I have also tried the following in my *init.vim*. However, I get an [error](http://pastebin.com/KCpvR4dF) from *deoplete*
```vim
   Plug 'Shougo/deoplete.nvim'

   let g:deoplete#enable_at_startup = 1
   let g:deoplete#auto_completion_start_length = 1

  "Note that -> added
   let g:deoplete#delimiters = ['/', '.', '::', ':', '#', '->']

   let g:deoplete#sources = {}
   let g:deoplete#sources._=['omni', 'buffer', 'member', 'tag', 'ultisnips', 'file']

   let g:deoplete#omni#input_patterns = {}
   let g:deoplete#omni#input_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
```
I know that the last line causes the error. However, I don't know *python* nor I know *python regex* to fix it.
Could you please elaborate on what I am doing wrong and tell me how to fix it?

**Comment by wsdjeg** [comment]
@khalidchawtany 
here is my confic ,I can get all source for java,I think you can change to what you want.

https://github.com/wsdjeg/DotFiles/blob/master/vimrc#L655-L672

**Comment by khalidchawtany** [comment]
@wsdjeg Thanks your config works for PHP too.

**Comment by wsdjeg** [comment]
welcome

**Comment by herrbischoff** [comment]
The working configuration disappeared. Could you please post the relevant parts in this issue?

**Comment by wsdjeg** [comment]
https://github.com/wsdjeg/DotFiles/blob/master/vim/config/plugins/deoplete.vim

**Comment by herrbischoff** [comment]
@wsdjeg Thanks!

**Comment by cprn** [comment]
Reupload or paste here?

**Comment by herrbischoff** [comment]
@cprn: I just hate it when linked information disappears. My dotfiles are not going to go anywhere. I have disabled all the settings just keeping `let g:deoplete#enable_at_startup = 1` while having `m2mdas/phpcomplete-extended` installed and it just works now: https://github.com/herrbischoff/dotfiles/blob/master/home/.config/nvim/plugins.vim#L134-L164

**Comment by cprn** [comment]
`phpcomplete-extended` has its own issues but this config seems to work. Thanks!

**Comment by cprn** [comment]
@herrbischoff Yeah... your config ghosted and I can't seem to get omni completion to work again.

**Comment by herrbischoff** [comment]
@cprn: Damn. That really should not have happened. I'm going to update it during the next couple of hours.

**Comment by herrbischoff** [comment]
@cprn: I updated the link to a proper one, referencing the repo at the time in history I wrote the comment. This way, it should not disappear again, no matter what happens.
