### ISSUE TITLE
The directory of the current file is recognized as its base directory in a particular case.

### ISSUE THREAD

**Issue by koharus0309** [Shougo/deoplete.nvim#1170]
# Problems summary

When I use neovim with deoplete.nvim, the file path completion of deoplete.nvim does not work as expected. According to the suggestions by deoplete.nvim, it seems that deoplete.nvim recognizes the current directory as its base directory by mistake. 
This phenomenon happens only when I opened existed files, and doesn't happen when I created a new file by command ``` $ nvim "new file name" ```
I firstly recognized this phenomenon in March, 2021. I have used deoplete.nvim for 1 and half of years, and this is the first time I met the phenomenon. This phenomenon is very similar to one reported in #109.

## Expected

Deoplete.nvim is expected to recognize that the current file exists in the current directory.

## Environment Information

 * deoplete version (SHA1):

b05a60c81572994eb9b4e1aa5c1c5dba98e10349

 * OS:

Ubuntu 20.04.2 LTS (Focal Fossa)

I use this OS since April, 2020.

 * neovim/Vim `:version` output:
 
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-
strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-time -D_FORT
IFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-protot
ypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector
-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOA
T32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/build/config -I/build/neovim-gOb7vg/neo
vim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/aut
o -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

My minimal `~/.config/nvim/init.vim` is as below.

```vim
if &compatible
    set nocompatible   "Be iMproved
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')

    call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')    
       
    let g:rc_dir      = expand("~/.config/nvim")    
    let s:toml        = g:rc_dir . '/dein.toml'    
    let s:lazy_toml   = g:rc_dir . '/dein_lazy.toml'    
      
    call dein#load_toml(s:toml,     {'lazy':0})    
    call dein#load_toml(s:lazy_toml,{'lazy':1})

    call dein#end()
    call dein#save_state()
endif
```

The section of my minimal `~/.config/nvim/dein_lazy.toml` to call deoplete.nvim is as below. In addition, this includes scripts to call neosnippet-snippets and neosnippet.vim.

```
[[plugins]]    
repo = 'Shougo/deoplete.nvim'    
on_i = 1    
hook_add = '''    
let g:deoplete#enable_at_startup = 1    
call deoplete#custom#source(    
  \ 'file', 'enable_buffer_path', v:true)    
call deoplete#custom#option({                     
    \ 'auto_complete_delay':0,    
    \ })    
inoremap <expr><TAB> pumvisible() ? "\<C-n>" :    
    \ neosnippet#expandable_or_jumpable() ?       
    \ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"    
''' 
```

In addition, my minimal `~/.config/nvim/dein.toml` is nearly empty. This includes scripts to call `dein.nvim` and `context_filetype.nvim`.

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. open a existed file with the command `nvim -u minimal.init.vim "file name"`
 2. move to insert mode
 3. type `../`, then the objects in the current directory will appear on the suggestions by deoplete.nvim.
 4. type `../../`, then the objects in the base directory will appear on the suggestions by deoplete.nvim.

## Screenshot

![Screenshot from 2021-04-05 13-23-27](https://user-images.githubusercontent.com/73347751/113536886-2177a900-9612-11eb-82ed-9518990f8c14.png "Files exist in the current directory.")
The picture above shows what file exist in the current directory.

![Screenshot from 2021-04-05 13-25-47](https://user-images.githubusercontent.com/73347751/113537014-73203380-9612-11eb-86c6-208715ce4907.png "The suggestions by deoplete.nvim when I open a existed file with neovim.")
The picture above shows the suggestion by deoplete.nvim when I open a existed file.

![Screenshot from 2021-04-05 13-27-30](https://user-images.githubusercontent.com/73347751/113537132-c09ca080-9612-11eb-889a-d43a4137bb73.png "The suggestions by deoplete.nvim when I create a new file by neovim.")
The picture above shows the suggestion by deoplete.nvim when I create a new file.

## Log file
I upload the log file which is generated when I opened a existed file and typed `../`, and `./`.
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/6256306/log_py3_rplugin.txt)

## In the end
This is the first time I submit a issue on github, and I'm not good at English(I'm Japanese). I'm sorry if this sentence is hard to understand, or it doesn't make sense.

I would appreciate if you respond me. 

Thank you.

**Comment by Shougo** [comment]
Reproduced. Fixed.

**Comment by koharus0309** [comment]
I read the discussion in #109 again. I'm sorry that I overlooked the latter part of the discussion.
Thank you for reply, and thank you for dark powered plugins.
