### ISSUE TITLE
macOS Big Surで"("をdeleteしようとすると"<Plug>_"が挿入され続ける

### ISSUE THREAD

**Issue by moonrabit** [Shougo/deoplete.nvim#1171]
OS: macOS Big Sur ver11.2.3
deoplete.nvimは最新のものです。(2021 4/7現在)

インサートモード時に、"("をdeleteキーで消そうとすると”\<Plug>_”という文字列が挿入され、以後deleteキーを押しっぱなしにするとdeleteキーのカーソルが"("のあった場所に到達するたびに、その文字列が挿入され続けると言う現象が発生しました。

deoplete.nvim/autoload/deoplete/handler.vimの217行目をコメントアウトするとこの現象が起こらなくなりました。これ以上詳しいことはわかりません。Ubuntu20.04だとこの現象は起こらなかったのでmacOS固有の問題だろうと考えていますが、Big Sur固有の問題かどうかは確かめていません。

再現gif
![deoplete_issue](https://user-images.githubusercontent.com/65657071/113848448-71519e00-97d3-11eb-839f-c93a8c3a8427.gif)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/1169#issuecomment-812825931

**Comment by Shougo** [comment]
mac でだけ起こるのは気になるんですが、手元に mac がないので
