### ISSUE TITLE
[Question] Is it possible to set 'input_pattern' by language type instead of candidate type?

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#1178]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
'input_pattern' cannot be set for each language.

## Expected
'input_pattern' can be set for each language.

## Environment Information

 * deoplete version (SHA1): 55e81a95a65ed896670abdb3340888db9a57e300

 * OS: Mac

 * neovim/Vim `:version` output: NVIM v0.5.0-dev+nightly-824-gc40de6e5f

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call deoplete#custom#option({'min_pattern_length': 2})
call deoplete#custom#source('rust', 'input_pattern', '[a-zA-Z_]\w*\.$|[a-zA-Z_]\w*::$')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

OK
```vim
call deoplete#custom#source('lsp', 'input_pattern', '[a-zA-Z_]\w*\.$|[a-zA-Z_]\w*::$')
```

Does not work
```vim
call deoplete#custom#source('rust', 'input_pattern', '[a-zA-Z_]\w*\.$|[a-zA-Z_]\w*::$')
```

**Comment by nabezokodaikon** [comment]
It was achieved by the following method.
```vim
call deoplete#custom#source('lsp', 'input_patterns', {
    \ '_': '[a-zA-Z_]\w*$',
    \ 'rust': '[a-zA-Z_]\w*\.$|[a-zA-Z_]\w*::$',
    \ })
```

**Comment by Shougo** [comment]
Yes.
