### ISSUE TITLE
Deoplete hangs on .ipynb files

### ISSUE THREAD

**Issue by jonathf** [Shougo/deoplete.nvim#1179]
# Problems summary

Deoplete slows down when inserting text in raw jupyter notebooks, (which is esentially JSON). We are talking about multiple seconds freeze. Lag also tends to linger after `<c-c>` into normal mode.
Documents are small (<1000 lines).

## Expected

neovim should not hang

## Environment Information

 * deoplete version (SHA1):
 I'm assuming git version. It is current master: 55e81a95a65ed896670abdb3340888db9a57e300

 * OS:
 Arch

 * neovim/Vim `:version` output:
```
NVIM v0.5.0-dev+1291-gb227cedf8
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion
-Wmissing-prototypes -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIB
I_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/runner/work/neovim/neovim/build/config -I/home/runner/work/neovim/neovim/src -I/home/runner/work/neovim/neovim/.deps/usr/include -I/usr
/include -I/home/runner/work/neovim/neovim/build/src/nvim/auto -I/home/runner/work/neovim/neovim/build/include
Compiled by runner@fv-az207-747
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
 ```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

[clip]

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/jonathf/.pyenv/libexec/pyenv
  - INFO: pyenv: Root: /home/jonathf/.pyenv
  - INFO: Using: g:python3_host_prog = "~/.config/nvim/venv/bin/python"
  - INFO: Executable: /home/jonathf/.config/nvim/venv/bin/python
  - INFO: Python version: 3.9.5
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
 ```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:python3_host_prog = '~/.config/nvim/venv/bin/python'

call plug#begin()
Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}
let g:deoplete#enable_at_startup = 1
call plug#end()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

* open `nvim some_file.ipynb -u customrc`
* start insert mode `i`
* write a few letters to trigger completion: `asdf`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file

[log_py3_rplugin.log](https://github.com/Shougo/deoplete.nvim/files/6503861/log_py3_rplugin.log)

**Comment by jonathf** [comment]
I am realizing the document isn't as small as I thought. It has images embedded into it. Here is the file I was editing while generating the log:
[quadrature_integration.txt](https://github.com/Shougo/deoplete.nvim/files/6504048/quadrature_integration.txt)
Rename to .ipynb.

**Comment by Shougo** [comment]
It seems very very long line is included in L90 and deoplete analysis it so it hangs.

**Comment by Shougo** [comment]
> Documents are small (<1000 lines).

It does not mean real small.  Very long lines are included.

**Comment by jonathf** [comment]
Yes, I realized the mistake after I posted. Thank you for looking into the issue, and the swift fix.
