### ISSUE TITLE
Array with four numbers at the bottom in insert mode

### ISSUE THREAD

**Issue by yevhen-m** [Shougo/deoplete.nvim#118]
Hey, I have a 'set noshowmode' setting in my init.vim.
When I enter insert mode, deoplete outputs an array with four numbers (I suppose, two of them are for the current cursor position). When I type, column number changes.
![image](https://cloud.githubusercontent.com/assets/10185058/12222860/5f39d392-b7d0-11e5-8f02-b1f90ff71324.png)

How do I hide these numbers?

**Comment by Shougo** [comment]
Fixed.
