### ISSUE TITLE
deoplete#complete_common_string doesn't work with fuzzy matcher

### ISSUE THREAD

**Issue by bew** [Shougo/deoplete.nvim#1181]
# Problems summary

Trying to use `deoplete#complete_common_string()` only works when the input text is not using the fuzzy matcher.

With input: `gigu#huk#` and completions like:
- `gitgutter#hunk#undo`
- `gitgutter#hunk#stage`

Calling the function `deoplete#complete_common_string()` doesn't work.
It only works if the input is `githutter#h` (to get `githutter#hunk#` in this example).

## Expected

Calling this function should replace the input and enter `gitgutter#hunk#` automatically.

## Environment Information

* deoplete version (SHA1): 187b2bd2beb7802e66c93900430c29b4ab9c20c8

* OS: Linux

<details>
<summary>neovim/Vim `:version` output:</summary>

```
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation:
Compiled by nixbld

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/nix/store/qrz30rk009irha1lzwgcbagd6hjfjr46-neovim-unwrapped-0.4.3/share/nvim
"

Run :checkhealth for more info
```
</details>

<details>
<summary>`checkhealth` or `:CheckHealth` result(neovim only)</summary>

```
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
```
</details>

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=.
let g:deoplete#enable_at_startup = 1

inoremap <silent><expr> <C-b> deoplete#complete_common_string()
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Enter these lines in a files:
```
loreminator
loremonatir
```
Then on a new line, start typing `lom` completion should show the 2 choices, try pressing `<C-b>`.
:point_right: nothing happens (I should get `lorem`.

The mapping is good though because when typing `lor` then pressing `<C-b>` I get `lorem`

## Screenshot (if possible)

Real-like example:
![deoplete_common_substring_fuzzy](https://user-images.githubusercontent.com/9730330/119339026-fc59fb00-bc90-11eb-92ca-faad23c8397c.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by bew** [comment]
Thanks, works perfectly :+1:
