### ISSUE TITLE
Setting options per source

### ISSUE THREAD

**Issue by fenuks** [Shougo/deoplete.nvim#1182]
# Problems summary
I use various programming autocomplete sources, and deoplete-dictionary. For all programming sources I want to *not* ingore case, i.e.
```viml
call deoplete#custom#option({
    \ 'ignore_case': v:false
\ })
```
, but for dictionary autocomplete I would like to ignore case, because starting new sentence with capital letter breaks autocompletion. 

## Expected
Possibility to set options per source, e.g.
```viml
call deoplete#custom#source_option('dictionary', {
    \ 'ignore_case': v:true
\ })
```

**Comment by Shougo** [comment]
OK.  I have changed the feature.

Note: The old options are does not work.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('dictionary', {
    \ 'ignore_case': v:true
\ })
```

is correct.

**Comment by fenuks** [comment]
Thank you so much!
