### ISSUE TITLE
Deoplete Is working but not all completes

### ISSUE THREAD

**Issue by gario300** [Shougo/deoplete.nvim#1184]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Hi everybody, recently im reinstall my SO, im using ubuntu 21.04 but now i can not I can't make it work deoplete as espected.
Deoplete is works but is show a minimal options

Expected : 

it is difficult to explain for me;

for example : 

In this case im espected another options for import from react native, in this case "StyleSheet"

![image](https://user-images.githubusercontent.com/41522264/121509543-5f939f00-c9ac-11eb-9b39-d4219c247132.png)

or in this case im expected deoplete showme Jsx Atributes but deoplete is not complete all options

![image](https://user-images.githubusercontent.com/41522264/121509895-b600dd80-c9ac-11eb-93fd-86ea10f1ca26.png)

im reinstall my SO, peviously this works but now is not working, deoplete only is showing options of current file and some snippeds.

## Environment Information

 deoplete version (SHA1): lastedt

 OS: ubuntu 20.04

 neovim/Vim `:version` output: 0.4.4

 `:checkhealth` result(neovim only):
![image](https://user-images.githubusercontent.com/41522264/121511043-de3d0c00-c9ad-11eb-9e51-a2f7c2a430bd.png)
![image](https://user-images.githubusercontent.com/41522264/121511127-f14fdc00-c9ad-11eb-9845-744f986a0524.png)

 Provide a minimal init.vim/vimrc with less than 50 lines :
```
call plug#begin(expand('~/.config/nvim/plugged'))
Plug 'Shougo/vimproc.vim', {'do': g:make}
"" Vim-Session
Plug 'xolox/vim-misc'
Plug 'xolox/vim-session'
"" Snippets
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
" javascript
"" Javascript Bundle
Plug 'jelera/vim-javascript-syntax'
" typescript
Plug 'leafgarland/typescript-vim'
Plug 'HerringtonDarkholme/yats.vim'

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'ternjs/tern_for_vim', {'do': 'npm install && npm install -g tern'} 
"react
Plug 'peitalin/vim-jsx-typescript'
Plug 'styled-components/vim-styled-components', { 'branch': 'main' } 
Plug 'maxmellon/vim-jsx-pretty'
Plug 'mlaursen/vim-react-snippets'
if filereadable(expand("~/.config/nvim/local_bundles.vim"))
  source ~/.config/nvim/local_bundles.vim
endif
call plug#end()
let g:deoplete#enable_at_startup = 1
```

How to reproduce the problem from neovim/Vim startup 
 Really im not have idea of how to reproduce the problem this only works  before and now does not work.. But im download a template from vim boostrap and after install deoplete

**Comment by Shougo** [comment]
> im reinstall my SO, peviously this works but now is not working, deoplete only is showing options of current file and some snippeds.

So this is not deoplete's issue.
It is deoplete source issue.

**Comment by Shougo** [comment]
I think you need to enable omnifunc auto completion.

```
Q: I want to use JavaScript omnifunc.

A: Please set "input_patterns" manually. >

	call deoplete#custom#var('omni', 'input_patterns', {
	\ 'javascript': '[^. *\t]\.\w*',
	\ })
```

Please read the documentation.

**Comment by gario300** [comment]
Sorry, my english is not so good. In this case my problem not is in autocompletition, my problem is in to see all options what i can to use, for example, before if im import a function or object from another file and im call the function deoplete show me all options what im can to use in to object or function and the properties if is string, function, jsx atributes, etc... Im try your solve but does not working for me

**Comment by Shougo** [comment]
I have read the minimal vimrc and it does not include deoplete source for Typescript.
No magic.

You should use nvim-typescript or LSP completion source.

https://github.com/mhartington/nvim-typescript

https://github.com/deoplete-plugins/deoplete-lsp

Note:  To use deoplete-lsp, you need to configure LSP

**Comment by Shougo** [comment]
> im reinstall my SO, peviously this works but now is not working, deoplete only is showing options of current file and some snippeds.

Really works??  Because your configuration does not include any Javascript completion source.  I think you have changed the configuration.  No magic.

**Comment by gario300** [comment]
> I have read the minimal vimrc and it does not include deoplete source for Typescript.
> No magic.
> 
> You should use nvim-typescript or LSP completion source.
> 
> https://github.com/mhartington/nvim-typescript
> 
> https://github.com/deoplete-plugins/deoplete-lsp
> 
> Note: To use deoplete-lsp, you need to configure LSP

Thank you very much!!!! Really thanks previously im no needs follow this step (I think something must have changed in vim-boostrap, im not install the plugins manually) but now is working, really thank you

**Comment by Shougo** [comment]
Oh, OK.
