### ISSUE TITLE
Unknown function: deoplete#custom#option

### ISSUE THREAD

**Issue by pplmx** [Shougo/deoplete.nvim#1188]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Running `vim` will throw an error. 
From the other issues, it seems that the deoplete `didn't be loaded`. But, I don't know where it should be loaded. Could you give me some help? Thanks a lot. :)
```bash
[root@cf8e34ccda9c src]# vim
Error detected while processing /root/.vimrc:
line  879:
E117: Unknown function: deoplete#custom#option
Press ENTER or type command to continue
```

## Expected
Without Error.

## Environment Information

 * deoplete version (SHA1):

 * OS:
```bash
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
```

 * neovim/Vim `:version` output: 8.2.3281

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
This is my .vimrc, the error occurs in `Line 879`
https://github.com/pplmx/vimConfig/blob/dev/.vimrc

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/26994103/128154011-879514f2-a976-4ee2-8de3-2270cda8cf2a.png)

**Comment by pplmx** [comment]
Hi, Shougo

I also forked spf13-vim and refactor it to use vim-plug to manage the plugins. :)

**Comment by Shougo** [comment]
I don't know your forked spf13-vim code.
I have not ESP skills unfortunately.

**Comment by Shougo** [comment]
If you use vim-plug, `deoplete#custom#option()` must be called after `call plug#end()`.

**Comment by uolot** [comment]
For the record, because I had the same issue, the following also needs to be called after `call plug#end()`:

```
let g:deoplete#enable_at_startup = 1
```
