### ISSUE TITLE
fuzzy filter from current candidates provided LSP without refreshing

### ISSUE THREAD

**Issue by ccshao** [Shougo/deoplete.nvim#1189]
# Problems summary
LSP is quite very helpful but provides too many candidates. If an autocompletion triggered, could it be possible to filter from current popup without renew candidates when I continue to type.

I have tried several options, but when I type, the already listed candidates always get updated.

See below screenshot, when I typed `s`, there is lots of candidates. I am interested to select the function `scale_alpha_binned` provide by lsp. However, when I continued to type `bin`, it is not filtered from current popup but try to redo the completion.

<img width="338" alt="Screenshot 2021-08-05 at 19 02 36" src="https://user-images.githubusercontent.com/4980631/128392870-e3765e75-5cc7-47a6-a0e0-945d09793f51.png">

## Expected
Keeping the current candidates and no refreshing to let me fuzzy filter among them.
This is **TRUE** if the candidates are in the buffer, but not if they are provided by lsp. 

## Environment Information

 * deoplete version (SHA1): latest

 * OS: macos

 * neovim/Vim `:version` output:
NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: clang -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS
_SET_MATCH_LIMIT -O2 -DNDEBUG -Wall -Wextra -pedantic -Wno-unused-para
meter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-p
rototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-c
ommon -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU
_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG
_LEVEL=3 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/build/config
 -I/tmp/neovim-20210702-14987-rep9di/neovim-0.5.0/src -I/usr/local/inc
lude -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include
 -I/usr/local/opt/gettext/include -I/tmp/neovim-20210702-14987-rep9di/
neovim-0.5.0/build/src/nvim/auto -I/tmp/neovim-20210702-14987-rep9di/n
eovim-0.5.0/build/include
Compiled by brew@BigSur

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.5.0/share/nvim"
 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call deoplete#custom#source('_', 'smart_case', v:true)
call deoplete#custom#source('_', 'mark', '')
call deoplete#custom#option({
  \ 'min_pattern_length': 1,
  \ 'camel_case': v:true,
  \ 'on_text_changed_i': v:false,
  \ 'on_insert_enter': v:false,
  \ 'refresh_always': v:false,
\ })

call deoplete#custom#option('num_processes', 2)

set completeopt+=noinsert
set shortmess+=c
let g:deoplete#enable_at_startup = 1
let g:deoplete#lsp#handler_enabled = v:false
let g:deoplete#lsp#use_icons_for_candidates = v:true
inoremap <expr> <CR> (pumvisible() ? "\<c-y>" : "\<CR>")
inoremap <silent> <expr> <TAB> deoplete#manual_complete()
```

## How to reproduce the problem from neovim/Vim startup (Required!)
I am using the R lsp, here is the setup. 
```
require'lspconfig'.r_language_server.setup{}
```
create a .R file from termial, 
neovim 1.R
then type `s` to trigger the completion.

**Comment by Shougo** [comment]
```vim
call deoplete#custom#source('lsp', 'is_volatile', v:false)
```

**Comment by ccshao** [comment]
Thanks for the quick tips! A really versatile plugin.

A further question, with `is_volatile` as `false`, if I am not satisfied with the candidates provided by lsp, how could force it to refresh lsp candiates?

**Comment by Shougo** [comment]
You can use `deoplete#manual_complete()` for it.

**Comment by ccshao** [comment]
Here are my current settings. When enabling `call deoplete#custom#source('lsp', 'is_volatile', v:false)`, very often the lsp candidates are **not** shown in the popup , even when I trigger the manual complete using `<C-space>`.  

LSP condidates are always shown in popup nearly instantly without `is_volatile` setting.  Any issues with my configs? Thanks!

```vim
let g:deoplete#enable_at_startup = 1
let g:deoplete#lsp#handler_enabled = v:false
let g:deoplete#lsp#use_icons_for_candidates = v:true

set completeopt+=noinsert
set shortmess+=c

call deoplete#custom#option('num_processes', 1)
call deoplete#custom#source('_', 'smart_case', v:true)
call deoplete#custom#source('_', 'mark', '')
" call deoplete#custom#source('lsp', 'is_volatile', v:false)
call deoplete#custom#option({
  \ 'min_pattern_length': 1,
  \ 'camel_case': v:true,
  \ 'refresh_backspace': v:false,
  \ 'auto_refresh_delay' : 10,
  \ 'auto_complete_delay' : 10,
\ })

inoremap <expr> <CR> (pumvisible() ? "\<c-y>" : "\<CR>")
inoremap <silent> <C-Space> <C-r>=deoplete#manual_complete()<cr>
```

**Comment by Shougo** [comment]
Unfortunately, lsp source behavior depends on `is_volatile`.
You need to enable `is_volatile` instead.
No magic for it.

I develop new auto completion plugin currently.
https://github.com/Shougo/ddc.vim

deoplete is deprecated plugin and I don't plan to fix the problem.

**Comment by ccshao** [comment]
Thanks for update, deoplete is very smart and this small issue is bearable.

**Comment by Shougo** [comment]
I have added the feature in ddc.vim.  Cheers.

**Comment by ccshao** [comment]
Thanks for the update, will try it later!
