### ISSUE TITLE
Is there a way to tell if my deoplete is configured correctly?

### ISSUE THREAD

**Issue by hahuang65** [Shougo/deoplete.nvim#119]
I'm asking because a plugin I am using for Elixir code completion will block as soon as I type in `:` (start of an atom so lots of possible completions).

I cannot type anything for probably 1 minute until it loads all the completions. Is this supposed to happen? Is there some configuration I'm maybe missing?

`:echo has("python3")` returns `1` for me.

**Comment by wsdjeg** [comment]
where is your min vimrc?how could other people test it for you

**Comment by hahuang65** [comment]
These are all my settings related to Deoplete:

```
" Use Deoplete.
let g:deoplete#enable_at_startup = 1

" Let <Tab> also do completion
inoremap <silent><expr> <Tab>
\ pumvisible() ? "\<C-n>" :
\ deoplete#mappings#manual_complete()

" Close the documentation window when completion is done
autocmd InsertLeave,CompleteDone * if pumvisible() == 0 | pclose | endif
```

The rest are too big to paste, but can be see at http://github.com/hahuang65/vimrc

**Comment by pjrt** [comment]
I'm seeing something similar. Not a minute, but about 5s or so.

**Comment by Shougo** [comment]
@hahuang65 It seems elixir-lang/vim-elixir's block.
Unfortunately, deoplete cannot prevent omnifunc block.
Because, omnifunc is not asynchronous.

You should use it.
https://github.com/awetzel/elixir.nvim
It includes deoplete source for elixir.

**Comment by wsdjeg** [comment]
awesome

**Comment by pjrt** [comment]
Oh, so my issue was related! The neco-ghc lock up I was seeing happened after I set the omnifunc.

**Comment by hahuang65** [comment]
In the readme of https://github.com/archSeer/elixir.nvim it instructs to use both
```
Plug 'elixir-lang/vim-elixir'
Plug 'archSeer/elixir.nvim'
```

Is this incorrect? archSeer's plugin also claims to have deoplete support. What happens if both are installed?

**Comment by hahuang65** [comment]
In fact, I do need to keep `elixir-lang/vim-elixir`. Otherwise I lose syntax highlighting.

**Comment by hahuang65** [comment]
This is not a resolved issue. I tried both https://github.com/awetzel/elixir.nvim and https://github.com/archSeer/elixir.nvim and they both block.

'elixir-lang/vim-elixir' is NOT the issue. They block even without 'elixir-lang/vim-elixir'.

**Comment by Shougo** [comment]
https://github.com/awetzel/elixir.nvim is better.
But it blocks your neovim, Yes.
It is elixir.nvim's source problem.
You should report it.

https://github.com/awetzel/elixir.nvim/blob/master/rplugin/python3/deoplete/sources/elixir.py#L20
It calls Vim's function.  It blocks your neovim.
It is not deoplete problem.

**Comment by hahuang65** [comment]
@Shougo Thank you for your help! I will report it.

**Comment by awetzel** [comment]
I have just improved the response time of the autocomplete function in many cases : https://github.com/awetzel/elixir.nvim/issues/4 

Still if it is not sufficient for fluent Deoplete completion, I do not use Deoplete and so I do not know how to make https://github.com/awetzel/elixir.nvim/blob/master/rplugin/python3/deoplete/sources/elixir.py async.

Have you any hint @Shougo  ? thanks

**Comment by Shougo** [comment]
@awetzel Please use Python functions for async.
You should not call `ElixirComplete` function.
Please see the other sources in deoplete.
