### ISSUE TITLE
Deloplete interfering with Coc ?

### ISSUE THREAD

**Issue by vaibhav135** [Shougo/deoplete.nvim#1192]
OS => Ubuntu 20.04 lts

editor => NeoVim

I am currently using Coc and recently started using ALE with deoplete (for python). So what  end up happening is whenever I am using a .txt file it is giving me an error/warning in insert mode
 
Here's the image of warning/errors:
![image](https://user-images.githubusercontent.com/39329182/131708818-e59f8438-dc41-44f2-ac1b-8827f7f1c761.png)

I tried to disable Coc for certain file types but seems like not working or something..
` autocmd FileType python,venv,ASCII text,vim let b:coc_suggest_disable = 1 `

Also I've seen the similar issues regarding these but they actually never provide a solution.
[](https://github.com/Shougo/deoplete.nvim/issues/1092) 

The thing is I understand the problem but don't know the solution. 
Your help will be highly appreciated

**Comment by vaibhav135** [comment]
@Shougo tell me If you need my init.vim or .vimrc. I will provide them.

**Comment by Shougo** [comment]
Unfortunately, both deoplete and coc.nvim provide auto completion feature.
So deoplete conflicts with coc.nvim.
You cannot use both.  You need to choose coc.nvim or deoplete.

**Comment by Shougo** [comment]
But to change |deoplete-options-overwrite_completeopt| may work for you.

```vim
call deoplete#custom#option('overwrite_completeopt', v:false)
```

**Comment by vaibhav135** [comment]
@Shougo can I overwrite for some certain files like python or .txt files?

**Comment by Shougo** [comment]
You cannot.  Because coc.nvim overwrites 'completeopt' option and is global option unfortunately.  No magic.

**Comment by Shougo** [comment]
The check is implemented in coc.nvim side and you should request it in coc.nvim issues instead.
