### ISSUE TITLE
deoplete autocompletion not working

### ISSUE THREAD

**Issue by uziahmed** [Shougo/deoplete.nvim#1193]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
deoplete autocompletion is not working

## Environment Information

 * deoplete version (SHA1):
sha1
 * OS:
linux: zorin os

 * neovim/Vim `:version` output:
:version
NVIM v0.4.3
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-gOb7vg/neovim-0.4.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=1 -DDISABLE_LOG -Wdate-
time -D_FORTIFY_SOURCE=1 -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough
 -Wvla -fstack-protector-strong -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim-gOb7vg/neovim-0.4.3/bui
ld/config -I/build/neovim-gOb7vg/neovim-0.4.3/src -I/usr/include -I/usr/include/lua5.1 -I/build/neovim-gOb7vg/neovim-0.4.3/build/src/nvim/auto -I/build/neovim-gOb7vg/neovim-0.4.3/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

 * `:checkhealth` or `:CheckHealth` result(neovim only):

![Screenshot from 2021-10-17 16-09-02](https://user-images.githubusercontent.com/69237379/137624730-49eae9a1-a9aa-4347-a9f0-e9ea6d9d2e81.png)

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

`syntax on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent	
set nu
set nowrap
set smartcase
set noswapfile
set incsearch
set mouse=a

call plug#begin()
Plug 'https://github.com/joshdick/onedark.vim.git'
Plug 'vim-airline/vim-airline'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1
call plug#end()

colorscheme onedark
let g:airline_theme='onedark'
let g:airline_powerline_fonts = 1`

## How to reproduce the problem from neovim/Vim startup (Required!)
i literally just did whats in the documentation i have read all of the documentation but still couldn't figure out what is wrong

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)
![Screenshot from 2021-10-16 13-21-11](https://user-images.githubusercontent.com/69237379/137624839-c22c1930-d8e4-44bc-bf53-9b2846d9de33.png)

**Comment by Shougo** [comment]
I think it works.

```vim
def main():
    print();
    pri|
```

Because, the default deoplete does not equals omni completion.
It does not complete Python syntax words.
It completes already input words.

If you need syntax completion, you need to install `deplete-lsp` and configure `nvim-lspconfig` instead.

https://github.com/deoplete-plugins/deoplete-lsp
https://github.com/neovim/nvim-lspconfig
