### ISSUE TITLE
completion doesn't work

### ISSUE THREAD

**Issue by Nymphium** [Shougo/deoplete.nvim#12]
deoplete.vimを最新にしたところ､補完が動かなくなりました｡
https://github.com/Nymphium/vimconfig/tree/neovim に全ての設定が書いてありますが､deoplete.vimに関しては
```
let g:deoplete#enable_at_startup = 1
```
のみです｡`:message`にエラーメッセージは出ていません｡
NeovimのバージョンはCommit: 0685489ee5b958b9cae6b2a36ab3f508559f550a(AURからインストール)､OSはArch Linuxです｡

**Comment by HerringtonDarkholme** [comment]
` :UpdateRemotePlugins`、またはdeoplete再インストール。これで多分済むと思います

**Comment by Nymphium** [comment]
`:UpdateRemotePlugins`はすでにやりましたが補完は動きませんでした｡

**Comment by Nymphium** [comment]
補完が動くようになりました｡というのも､私はvimrcをVimとNeovimで共有しており､neocompleteの設定がdeopleteに影響を及ぼしていたようです｡お騒がせしました｡
