### ISSUE TITLE
[Suggestion] Disable deoplete on the fly

### ISSUE THREAD

**Issue by WhiteBlackGoose** [Shougo/deoplete.nvim#1202]
Hello, thanks for this great plugin!

One suggestion: disabling deoplete on the fly. I currently have a problem that deoplete's autocompletion is *very* slow. I cannot reproduce it minimally, so not filing a bug report. However, to avoid it I'd just disable it.

Related: #77. I tried
```
let g:deoplete#disable_auto_complete = true
```

But it didn't change anything for me, it keeps trying to auto-complete and hangs

**Comment by Shougo** [comment]
the information is too old.

If you want to disable auto completion, please disable `auto_complete`  flag.

```vim
call deoplete#custom#option('auto_complete', v:false)
```

```
					*deoplete-options-auto_complete*
auto_complete
		If it is False, automatic completion becomes invalid, but can
		use the manual completion by |deoplete#manual_complete()|.

		Default value: v:true
```

**Comment by WhiteBlackGoose** [comment]
Thanks!
