### ISSUE TITLE
E605: Exception not caught

### ISSUE THREAD

**Issue by kenkenspin** [Shougo/deoplete.nvim#1207]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I try install deoplete with dein plugin manager, but start vim with error "E605: 例外が捕捉されませんでした: [vim-hug-neovim-rpc] requires one of `:pythonx
 import [pynvim|neovim]` command to work"

I have installed as bellow.

```
pip3 install pynvim
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pynvim in ./.local/lib/python3.12/site-packages (0.4.3)
Requirement already satisfied: msgpack>=0.5.0 in ./.local/lib/python3.12/site-packages (from pynvim) (1.0.7)
Requirement already satisfied: greenlet in ./.local/lib/python3.12/site-packages (from pynvim) (3.0.0)
```

## Expected

Enable deoplete and neosnippet.

## Environment Information

 * deoplete version (SHA1): Latest

 * OS:Fedora 39 Beta updated(Python 3.12)
 * OS:Fedora 38 (Python 3.11) work fine with same /home.

 * neovim/Vim `:version` output: 

~~~
IM - Vi IMproved 9.0 (2022 Jun 28, compiled Oct 05 2023 00:00:00)
適用済パッチ: 1-1984
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge 版 with GTK3 GUI.  機能の一覧 有効(+)/無効(-)
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       -tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl/dyn          +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3/dyn       +virtualedit
~~~

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
" Ward off unexpected things that your distro might have made, as
" well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Set Dein base path (required)
let s:dein_base = '/home/kenken/.vim/bundle'

" Set Dein source path (required)
let s:dein_src = '/home/kenken/.vim/bundle/repos/github.com/Shougo/dein.vim'

" Set Dein runtime path (required)
execute 'set runtimepath+=' . s:dein_src

" Call Dein initialization (required)
call dein#begin(s:dein_base)

call dein#add(s:dein_src)

" Your plugins go here:

call dein#add('Shougo/deoplete.nvim')
if !has('nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')
endif
let g:deoplete#enable_at_startup = 1
call dein#add('Shougo/neosnippet.vim')
call dein#add('Shougo/neosnippet-snippets')
" Finish Dein initialization (required)
call dein#end()

" Attempt to determine the type of a file based on its name and possibly its
" contents. Use this to allow intelligent auto-indenting for each filetype,
" and for plugins that are filetype specific.
if has('filetype')
  filetype indent plugin on
endif

" Enable syntax highlighting
if has('syntax')
  syntax on
endif

" Uncomment if you want to install not-installed plugins on startup.
"if dein#check_install()
" call dein#install()
"endif

" Plugin key-mappings.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
imap <C-k>     <Plug>(neosnippet_expand_or_jump)
smap <C-k>     <Plug>(neosnippet_expand_or_jump)
xmap <C-k>     <Plug>(neosnippet_expand_target)

" SuperTab like snippets behavior.
" Note: It must be "imap" and "smap".  It uses <Plug> mappings.
"imap <expr><TAB>
" \ pumvisible() ? "\<C-n>" :
" \ neosnippet#expandable_or_jumpable() ?
" \    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
\ "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"

" For conceal markers.
if has('conceal')
  set conceallevel=2 concealcursor=niv
endif
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. vi start anyfile. 
 

## Generate a logfile if appropriate

attache logfile.

## Screenshot (if possible)

![Screenshot from 2023-10-15 15-59-07](https://github.com/Shougo/deoplete.nvim/assets/25343413/ea3d6777-3ef4-4d45-b79e-bcb0fe992eed)

## Upload the log file

[deoplete] VimEnter Autocommands for "...bles[11]..neovim_rpc#serveraddr, 行 18
VimEnter Autocommands for "*"..function deoplete#enable[9]..deoplete#initialize[
1]..deoplete#init#_initialize[10]..<SNR>73_init_internal_variables[35]..VimEnter
 Autocommands for "*"..function deoplete#enable[9]..deoplete#initialize[1]..deop
lete#init#_initialize[10]..<SNR>73_init_internal_variables[29]..neovim_rpc#serve
raddr の処理中にエラーが検出されました:
行   18:
E605: 例外が捕捉されませんでした: [vim-hug-neovim-rpc] requires one of `:pythonx
 import [pynvim|neovim]` command to work

[vim.log](https://github.com/Shougo/deoplete.nvim/files/12908883/vim.log)

**Comment by Shougo** [comment]
It is not deoplete problem.

I think your pip command is not same with Vim environment.

**Comment by Shougo** [comment]
```


OS:Fedora 39 Beta updated(Python 3.12)

OS:Fedora 38 (Python 3.11) work fine with same /home.
```

It seems your python is python 3.12.  But your Vim is build with python 3.12.

**Comment by kenkenspin** [comment]
> It is not deoplete problem.
> 
> I think your pip command is not same with Vim environment.

I don’t write it,
pip command run on each environment.

~~~
ls ~/.local/lib/python3.12/site-packages/
greenlet
greenlet-3.0.0.dist-info
msgpack
msgpack-1.0.7.dist-info
neovim
pynvim
pynvim-0.4.3.dist-info
~~~

**Comment by kenkenspin** [comment]
> ```
> 
> 
> OS:Fedora 39 Beta updated(Python 3.12)
> 
> OS:Fedora 38 (Python 3.11) work fine with same /home.
> ```
> 
> 
>     
>   
> 
> It seems your python is python 3.12.  But your Vim is build with python 3.11.

I build vim git source on Fedora 39, but the same error.

**Comment by Shougo** [comment]
You need to find `what Python is build for Vim`.

> pip command run on each environment.

It is Python 3.12.
You need to install pynvim in Python 3.11.

In my environment, pip3.11 exists.

Note: My python environment is Python 3.11 only.

> I build vim git source on Fedora 39, but the same error.

What Python is used?   You need to find the log.  It is no magic.

**Comment by kenkenspin** [comment]
tis post closed.I found that resolve it.

```
pip3 install zombie-imp
```

https://pypi.org/project/zombie-imp/

**Comment by Shougo** [comment]
For python 3.12, please see this.

https://github.com/neovim/pynvim/issues/538

**Comment by kenkenspin** [comment]
fix it via the following command as the link.

https://github.com/neovim/pynvim/issues/538#issuecomment-1760735880

`pip install 'pynvim @ git+https://github.com/neovim/pynvim'`

Thanks!
