### ISSUE TITLE
deoplete requires vim 8.2.1978+ in the error message when it is already installed

### ISSUE THREAD

**Issue by cumt559** [Shougo/deoplete.nvim#1209]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I am using deoplete with vim 8.2

vim --version
VIM - Vi IMproved 8.2 (2019 Dec 12 kompiliert am Oct 16 2023 18:15:38)
Inklusive der Patches: 1-579, 1969, 580-1854, 1857, 1855-1857, 1331, 1858, 1858-1859, 1873, 1860-1969, 1992, 1970-1992, 2010, 1993-3995, 4563, 4646, 4774, 4895, 4899, 4901, 4919, 213, 1840, 1846-1847

When I start my vim, there is always an error message saying: deoplete requires vim 8.2.1978+ and autocompletion does not work. But I had that patch already. Is there any way to solve this issue?

## Environment Information

 * deoplete version (SHA1): newest, Just updated

 * OS: Ubuntu

 * neovim/Vim `:version` output:

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

" For Vim only
"set runtimepath+=~/path/to/nvim-yarp/
"set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

if isdirectory(expand(EverVimBundleDir("deoplete.nvim")))
    let g:deoplete#enable_at_startup = 1
    call deoplete#custom#option({
    \ 'auto_complete_delay': 100,
    \ 'smart_case': v:true,
    \ })
    call deoplete#custom#option('min_pattern_length', 2)
    call deoplete#custom#var('omni', 'input_patterns', {
      \ 'tex': g:vimtex#re#deoplete
      \})
    inoremap <silent><expr> <S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"
    inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
endif

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Please check `:echo has('patch-8.2.1978')`.

I think it is false.

**Comment by Shougo** [comment]
Unfortunately, Vim 8.2.1978 is required.  Because of `<Cmd>` mappings.

```
> Patch 8.2.1978
> Problem:    Making a mapping work in all modes is complicated.
> Solution:   Add the <Cmd> special key. (Yegappan Lakshmanan, closes #7282,
>             closes 4784, based on patch by Bjorn Linse)
> Files:      runtime/doc/autocmd.txt, runtime/doc/eval.txt,
>             runtime/doc/map.txt, src/edit.c, src/errors.h, src/ex_docmd.c,
>             src/ex_getln.c, src/getchar.c, src/insexpand.c, src/keymap.h,
>             src/map.c, src/misc2.c, src/normal.c, src/ops.c,
>             src/proto/[getchar.pro](http://getchar.pro/), src/screen.c, src/terminal.c,
>             src/testdir/test_mapping.vim
```

> Is there any way to solve this issue?

You should build it from Vim's source code.

**Comment by Shougo** [comment]
@cumt559 Please see this.

https://phoenixnap.com/kb/how-to-install-vim-ubuntu

**Comment by cumt559** [comment]
Worked like a charm! Many thanks!


Am Fr., 15. Dez. 2023 um 08:34 Uhr schrieb Shougo ***@***.***
