### ISSUE TITLE
Is this clang_complete with deoplete.nvim?

### ISSUE THREAD

**Issue by tony** [Shougo/deoplete.nvim#121]
Hi, I'm not getting completion information from third-party header libraries. I've had it working a few days ago.

I'm trying to determine if I'm experiencing my own configuration problem, a deoplete issue or a clang_complete issue.

![2016-01-12-115445_640x360_scrot](https://cloud.githubusercontent.com/assets/26336/12271938/4962b7a6-b923-11e5-8f12-99b7234579f3.png)

How do I tell what kind of completion it is?  Is it omni completion? What is ``m``, is that from deoplete?  Are there any ways internally to debug what completion is popping up in neovim?

bundle: https://github.com/tony/vim-config/blob/master/bundles.d/lang.c-cxx.vim
deoplete settings: https://github.com/tony/vim-config/blob/master/settings/deoplete.vim

I've also tried with this snippet from doc and nothing changed:

```viml
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_default_keymappings = 0
```
clang_complete settings: https://github.com/tony/vim-config/blob/master/settings/clang_complete.vim

**Comment by Shougo** [comment]
You should ask it in clang_complete repository.
clang_complete has deoplete source.
But it has [clang] mark.
Your screenshot has not the mark.  So I think it is just omnifunc call.

Advice:  You should create minimal init.vim.
You should check "." mapping.

**Comment by tony** [comment]
> You should check "." mapping.
What do you mean by that?

**Comment by Shougo** [comment]
You should execute `:verbose imap .`

**Comment by tony** [comment]
```
i  .           *@<SNR>199_CompleteDot()                                                                                                                        
        Last set from ~/.dot-config/.vim/bundle/clang_complete/plugin/clang_complete.vim 
```
also:

```
i  <C-X><C-U>  *@<SNR>199_LaunchCompletion()                                                                                                                   
        Last set from ~/.dot-config/.vim/bundle/clang_complete/plugin/clang_complete.vim   
```

Done.

> clang_complete has deoplete source.

Outside of what's mentioned in deoplete docs.txt:

```
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_default_keymappings = 0
```

Do I need to specify anything special for deoplete.nvim to detect the source? Notably, there's no example on deoplete.nvim for how I would set the source ``let g:deoplete#sources#c``. Do I need to?

I have been left with the impression that the integration for clang_complete is done automatically on deoplete.nvim because the deoplete docs already give instructions on how to integrate.

**Comment by Shougo** [comment]
https://github.com/Rip-Rip/clang_complete/blob/master/plugin/clang_complete.vim#L181

Too bad.
The options names  are changed.
I will fix the doc.

**Comment by Shougo** [comment]
Correct options:

```vim
	let g:clang_complete_auto = 0
	let g:clang_auto_select = 0
	let g:clang_omnicppcomplete_compliance = 0
	let g:clang_make_default_keymappings = 0
```

**Comment by tony** [comment]
What's the correct way to do patterns in deoplete?

``g:deoplete#omni_patterns``:
```viml
    let g:deoplete#omni_patterns = {}
    let g:deoplete#omni_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
```
source: https://github.com/tony/vim-config/blob/7607825e9463197c5253a7ce36890211a4174935/settings/deoplete.vim

or ``g:deoplete#omni#input_pattern``:

```viml
let g:deoplete#omni#input_patterns.cpp = ['[^. *\t]\.\w*', '[^. *\t]\::\w*', '[^. *\t]\->\w*', '[<"].*/']
``` 

source: https://github.com/Rip-Rip/clang_complete/issues/466#issuecomment-167975065

**Comment by Shougo** [comment]
You should not set the variable.
Because, clang_complete already has deoplete source.

**Comment by tony** [comment]
> You should not set the variable.
> Because, clang_complete already has deoplete source.

So input_patterns/omni_patterns are unnecessary?

And does there need to be a: 

``let g:deoplete#sources#c = 'clang_complete'``

or anything else for either c/cpp?  Does clang_complete make that unnecessary as well?

**Comment by tony** [comment]
![2016-01-13-183046_822x538_scrot](https://cloud.githubusercontent.com/assets/26336/12312280/ca579ac4-ba23-11e5-982a-9d5f73bddf0a.png)

YES.

I removed all the ``input_patterns``/``omni_patterns``. No need to add a ``g:deoplete#sources#c``.

**Comment by Shougo** [comment]
It seems working.

**Comment by wsdjeg** [comment]
https://github.com/Shougo/deoplete.nvim/issues/117

**Comment by lynndylanhurley** [comment]
Hi @Shougo - thanks for your incredible work. What is the correct `omni_pattern` for objective c?

**Comment by Shougo** [comment]
@lynndylanhurley I think clang_complete already supports objective C.

https://github.com/Rip-Rip/clang_complete/issues/473

**Comment by lynndylanhurley** [comment]
@Shougo - Sorry, I think I meant `input_pattern` instead of `omni_pattern`. This is what I have currently:

~~~viml
if !exists("g:deoplete#omni#input_patterns")
  let g:deoplete#omni#input_patterns = {}
endif

" clang family omnicomplete
let g:deoplete#omni#input_patterns.c = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:deoplete#omni#input_patterns.cpp = '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
let g:deoplete#omni#input_patterns.objc = '[^.[:digit:] *\t]\%(\.\|->\)\w*'
let g:deoplete#omni#input_patterns.objcpp = '[^.[:digit:] *\t]\%(\.\|->\)\w*\|\h\w*::\w*'
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_omnicppcomplete_compliance = 0
let g:clang_make_default_keymappings = 0
~~~

This gives me the following error:
https://gist.github.com/4589bbe85b3048158078

I've also tried omitting the `input_pattern` settings. In that case the error goes away, but I still don't get omni completions.

Thanks for your help.

**Comment by Shougo** [comment]
Your input_pattern regex is wrong.
Please see the documentation.

```
				*g:deoplete#omni#input_patterns*
g:deoplete#omni#input_patterns
		This dictionary records keyword patterns to Omni completion.
		This is appointed in regular expression string or list every
		file type.
		If this pattern is not defined or empty pattern, deoplete
		does not call 'omnifunc'.
		Note: Some omnifuncs which moves the cursor is not worked.
		For example, htmlcomplete, vim-go, etc...
		Note: It is Python3 regexp.
```
It must be Python3 regexp.

**Comment by lynndylanhurley** [comment]
Thanks, I thought that might be the case. Do you know what the correct `input_pattern` regexp is for objective c?

**Comment by Shougo** [comment]
@lynndylanhurley clang_complete already implements the feature.
You don't have to set `input_pattern` manually.

**Comment by lynndylanhurley** [comment]
I commented all of the `input_patterns` and only left this for clang_complete:

~~~viml
let g:clang_complete_auto = 0
let g:clang_auto_select = 0
let g:clang_omnicppcomplete_compliance = 0
let g:clang_make_default_keymappings = 0
~~~

And now I don't have clang_complete completion.

I've tried setting this:

~~~viml
au FileType c,cpp,objc,objcpp setl omnifunc=clang_complete#ClangComplete
~~~

But it doesn't have any effect either.

Do you have a link to a working clang_complete configuration for objective c?

**Comment by Shougo** [comment]
@lynndylanhurley I don't touch the clang_complete implementation.  You should ask it in clang_complete issue.

But, few advice:

* You should create minimal init.vim and upload it.

* You should upload the reproduce ways from neovim starting.

Just your provided information, other people cannot test it.

> And now I don't have clang_complete completion.

The people have not ESP skill.

**Comment by lynndylanhurley** [comment]
@Shougo - here is a minimal init.vim that shows my problem:
https://gist.github.com/lynndylanhurley/5f94c57952362ffc1144

@tony - can you please post the code that you used to get this working?

**Comment by Shougo** [comment]
@lynndylanhurley MInimal init.vim is good.  But You should upload the reproduce ways in the issue.
If you want to create it, you should read other issues in deoplete.

**Comment by lynndylanhurley** [comment]
I created a minimal Objective-C project and everything works as it should. It must be an issue with the project that I was working on.

Thanks for your time :)

**Comment by Shougo** [comment]
If so, you should close it.

https://github.com/Rip-Rip/clang_complete/issues/474

**Comment by lynndylanhurley** [comment]
Done. Thanks @Shougo.
