### ISSUE TITLE
deoplete fails to load

### ISSUE THREAD

**Issue by bon-ami** [Shougo/deoplete.nvim#1213]
# Problems summary
I reinstalled neovim and get plugins with Plug. deoplete did not pop auto completion and I had to ^X^O. If I use some GUI for neovim, such as neoray or neovide, a line of _deoplete_init failure flashed in status line.
Then I use a minimal init.vim with Plug and deoplete only. Now neovim shows the failure.

It worked before I deleted some data and reinstalled everything. I removed python 3.9 and installed 3.8.5. Thanks in advance.

## Environment Information

 * deoplete version (SHA1): e5a47d4a2f0b2b6f568e708163e2354097e611c6 (June 6)

 * OS: Windows 10

 * neovim/Vim `:version` output: 0.10.1

 * `:checkhealth` result(neovim only):
```
deoplete: health#deoplete#check

deoplete.nvim ~
- OK exists("v:t_list") was successful
- OK has("timers") was successful
- OK has("python3") was successful
- OK Require Python 3.6.1+ was successful
- OK Require msgpack 1.0.0+ was successful
- If you're still having problems, try the following commands:
          - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
          - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
          - $ nvim
          - $ cat /tmp/log_{PID}
          - and then create an issue on github

==============================================================================
nvim: require("nvim.health").check()

Configuration ~
- OK no issues found

Runtime ~
- OK $VIMRUNTIME: D:\nvim-win64\share/nvim/runtime

Performance ~
- OK Build type: Release

Remote Plugins ~
- OK Up to date

External Tools ~
- WARNING ripgrep not available
==============================================================================
provider.python: require("provider.python.health").check()

Python 3 provider (optional) ~
- Using: g:python3_host_prog = "D:\\apps\\Python3\\python.exe"
- Executable: D:\\apps\\Python3\\python.exe
- Python version: 3.8.5
- pynvim version: 0.5.0
- OK Latest pynvim is installed.

Python virtualenv ~
- OK no $VIRTUAL_ENV
==============================================================================
vim.lsp: require("vim.lsp.health").check()

- LSP log level : WARN
- Log path: C:\Users\myusername\AppData\Local\nvim-data/lsp.log
- Log size: 0 KB

vim.lsp: Active Clients ~
- No active clients

vim.lsp: File Watcher ~
- file watching "(workspace/didChangeWatchedFiles)" disabled on all clients

vim.lsp: Position Encodings ~
- No active clients
```

python
```
Requirement already satisfied: pynvim in d:\apps\python3\lib\site-packages (0.5.0)
Requirement already satisfied: msgpack>=0.5.0 in d:\apps\python3\lib\site-packages (from pynvim) (1.0.8)
Requirement already satisfied: greenlet>=3.0 in d:\apps\python3\lib\site-packages (from pynvim) (3.0.3)
Requirement already satisfied: neovim in d:\apps\python3\lib\site-packages (0.3.1)
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Use Vim settings, rather than Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

packadd! matchit

let g:python3_host_prog = 'D:\\apps\\Python3\\python.exe'  " Python 3

call plug#begin()

if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif

call plug#end()

let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('sources', { '_': ['file'] })

" Load all plugins now.
" Plugins need to be added to runtimepath before helptags can be generated.
packloadall
" Load all of the helptags now, after plugins have been loaded.
" All messages and errors will be ignored.
silent! helptags ALL
```
removing source option does not help

`:UpdateRemotePlugins` shows
```
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: C:\Users\myusername\AppData\Local\nvim-data/rplugin.vim
```
my C:\Users\myusername\AppData\Local\nvim-data\rplugin.vim
```
" perl plugins


" node plugins


" python3 plugins


" ruby plugins


```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. run nvim with minimal init.vim
 2. in status line: "deoplete failed to load. Try the :UpdateR..."
 3. "call deoplete#enable()" shows "Unknown function: _deoplete_init" and lines below
 ```
[deoplete] function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[15]..deoplete#init#_channel, line 31
[deoplete] deoplete failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth and :messages output.
```
 4. I commented out `call _deoplete_init()` in deoplete.nvim\autoload\deoplete\init.vim, then no error is shown - of course it is not loaded. Then I found this function is defined in rplugin/python3/deoplete/__init__.py. So I doubt the issue is I cannot install the remote plugin.

## Generate a logfile if appropriate

 1. set NVIM_PYTHON_LOG_FILE=/tmp/log
 2. set NVIM_PYTHON_LOG_LEVEL=DEBUG
 6. nvim
 7. auto completion not working
 8. no log files with minimal init.vim and log files are empty with full init.vim

**Comment by Shougo** [comment]
Sorry.  I don't know why it does not work.
Because it is neovim remote plugin issue.

You should use `ddc.vim` instead.
Deoplete and remote plugin are deprecated architecture.

**Comment by Shougo** [comment]
But `g:python3_host_prog` is really executable?
You should check it.

`:echo g:python3_host_prog->executable()`

**Comment by Shougo** [comment]
> Requirement already satisfied: neovim in d:\apps\python3\lib\site-packages (0.3.1)

This package is conflicted with `pynvim`.  Please remove it.

**Comment by bon-ami** [comment]
@Shougo , thanks for your quick reply. `pip uninstall neovim` while keeping pynvim, etc. does not help.
Anyway, I'm switching to ddc.vim.

**Comment by Shougo** [comment]
OK.
