### ISSUE TITLE
elixir.nvim completion not working as expected with deoplete

### ISSUE THREAD

**Issue by jinyeow** [Shougo/deoplete.nvim#122]
Hi, I'm getting some odd behaviour with autocompletion with deoplete.nvim and elixir.nvim's completion.
Inside elixir files the completion popup menu doesn't appear. Ever. If I hit `<C-X><C-O>`, omnicompletion works as expected though.
The other weird behaviour is when I open an elixir file (e.g. test.ex) and then open any other file of any other filetype (e.g. test.py) THEN I get elixir completion in the other file BUT NOT in the elixir file.

I'm using Arch Linux. NVIM v0.1.0-45-gbb43d9b (compiled Nov 12 2015)
Below is a minimal init.vim. Do `:UpdateRemotePlugins` after plugins are installed.
```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'Shougo/deoplete.nvim'
Plug 'elixir-lang/vim-elixir' " this is requried to set the elixir filetype
Plug 'awetzel/elixir.nvim', { 'do': './install.sh' }

call plug#end()

let g:deoplete#enable_at_startup            = 1
```

For reference this is the deoplete source file given with elixir.nvim.
```vim
#=============================================================================
# FILE: elixir.py
# AUTHOR: Blaž Hrastnik 
# based on https://github.com/Rip-Rip/clang_complete/blob/master/rplugin/python3/deoplete/sources/clang_complete.py
#=============================================================================

from .base import Base

class Source(Base):
    def __init__(self, vim):
        Base.__init__(self, vim)

        self.name = 'elixir'
        self.mark = '[elixir]'
        self.filetypes = ['elixir']
        self.is_bytepos = False
        self.min_pattern_length = 1

    def get_complete_position(self, context):
        return self.vim.call('ElixirComplete', "1", "")

    def gather_candidates(self, context):
        return self.vim.call('ElixirComplete', 0, context['complete_str'])

```
I'm not 100% sure if it's deoplete or elixir.nvim that's the issue but since the omnifunc works fine I'm guessing it could be an issue with the provided deoplete source file or deoplete itself. The source file SEEMS to be fine, but I'm not really 100% what to look for so I'm asking for help here. I'm pretty sure this was all working before today's update of deoplete.nvim but I can't figure out what's causing these problems. Any help is greatly appreciated!

**Comment by wsdjeg** [comment]
hi How do you set omnifun for elixir

**Comment by jinyeow** [comment]
I don't set it manually. It used to Just Work after installing the plugins.

**Comment by wsdjeg** [comment]
there is no `set omnifun` in all this three plugin for elixir,how do you complete omni?

**Comment by jinyeow** [comment]
From memory the elixir.nvim source files have a line `setlocal omnifunc=ElixirComplete` I believe.

**Comment by jinyeow** [comment]
Just checked. It's under ftplugin/elixir.vim

**Comment by wsdjeg** [comment]
I can not find it 
https://github.com/elixir-lang/vim-elixir/blob/master/ftplugin/elixir.vim

**Comment by wsdjeg** [comment]
ok git it,thanks

**Comment by Shougo** [comment]
You should use elixir.nvim.

It includes elixir deoplete source.
https://github.com/archSeer/elixir.nvim

**Comment by jinyeow** [comment]
I am using elixir.nvim and the last commit fixed it. thanks!
