### ISSUE TITLE
Can't find Ultisnips snippets

### ISSUE THREAD

**Issue by alexlafroscia** [Shougo/deoplete.nvim#123]
I can't seem to be able to get Ultisnips snippets to show up in the completion options.  Ultisnips will expand them just fine, they just aren't listed in the Deoplete options, even after running `:UpdateRemotePlugins`.  Any advice, or do you think it's more likely an issue on Ultisnip's side?

**Comment by tony** [comment]
I also couldn't get ultisnips working. https://github.com/Shougo/neosnippet.vim works

**Comment by Shougo** [comment]
You should ask it in UltiSnips.
UltiSnips deoplete source author is in it.

**Comment by alexlafroscia** [comment]
@Shougo thanks!

**Comment by alexlafroscia** [comment]
@tony @Shougo thank you both!
