### ISSUE TITLE
Feature - disable completion for specified highlight styles

### ISSUE THREAD

**Issue by brendanjerwin** [Shougo/deoplete.nvim#126]
I'd like to disable completion (or perhaps just change sources to just buffer or something) when the cursor is within certain kinds of text.

I often get unusable completions while working in strings or comments.

**Comment by Shougo** [comment]
I don't think it is useful.
Because, highlight may be wrong and you can use `eval()` like functions.

**Comment by brendanjerwin** [comment]
OK. I clearly have much more to learn. :)
