### ISSUE TITLE
Know the type of source selected (UltiSnips)

### ISSUE THREAD

**Issue by paupalou** [Shougo/deoplete.nvim#129]
I want to make when you have the completion "popup" showing options, if you have selected an US (UltiSnips) source and press Enter <CR> then Expand Trigger.

So.. i need a mapping like that : 
inoremap <silent><expr><CR> pumvisible() ? "is_US_source_type ? \<mybindForExpandTrigger> else \<CR>" : "\<CR>"

How i can do it ?

Thanks

**Comment by Shougo** [comment]
It is not deoplete issue.
You should ask it in UltiSnips issue.

neosnippet can do it though...

```vim
	imap <expr><TAB>	 pumvisible() ? "\<C-n>" :
	\ neosnippet#expandable_or_jumpable() ?
	\    "\<Plug>(neosnippet_expand_or_jump)" : "\<TAB>"
```
