### ISSUE TITLE
Weired error message

### ISSUE THREAD

**Issue by Tranquility** [Shougo/deoplete.nvim#13]
Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line    9:                                                                                                                                                      E684: list index out of range: 0                                                                                                                                Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line    9:                                                                                                                                                      E15: Invalid expression: (has_key(item, 'abbr') && item.word !=# item.abbr) ? item.abbr : split(item.info, '\n')[0]                                             Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   11:                                                                                                                                                      E121: Undefined variable: abbr                                                                                                                                  Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   11:                                                                                                                                                      E15: Invalid expression: has_key(item, 'abbr') && abbr ==# item.abbr && len(get(item, 'menu', '')) > 5                                                          Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   18:                                                                                                                                                      E121: Undefined variable: abbr                                                                                                                                  Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   18:                                                                                                                                                      E116: Invalid arguments for function len(abbr) < len(item.word) + 2                                                                                             Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   18:                                                                                                                                                      E15: Invalid expression: len(abbr) < len(item.word) + 2                                                                                                         Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   22:                                                                                                                                                      E121: Undefined variable: abbr                                                                                                                                  Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   22:                                                                                                                                                      E116: Invalid arguments for function stridx(abbr, item.word)                                                                                                    Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   22:                                                                                                                                                      E15: Invalid expression: stridx(abbr, item.word)                                                                                                                Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   23:                                                                                                                                                      E121: Undefined variable: match                                                                                                                                 Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   23:                                                                                                                                                      E15: Invalid expression: match >= 0                                                                                                                             Error detected while processing function <SNR>168_on_cursor_moved..32:                                                                                          line   28:                                                                                                                                                      E121: Undefined variable: abbr                                                                                                                                  -- More --

**Comment by HerringtonDarkholme** [comment]
I think you should provide a minimum .vimrc and a sample text.  Otherwise we cannot reproduce this problem.

**Comment by Shougo** [comment]
OK.  I get the problem.
I will fix it later.

**Comment by Shougo** [comment]
Fixed.
