### ISSUE TITLE
Very weird problem with autocompletion with start_length at 0

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#130]
Here is a video describing the problem.

https://youtu.be/um1CzfNW-rM

also I opened an issue on zchee/deoplete-go#4 to add the solution for now to the example config.

**Comment by Shougo** [comment]
What is the problem?
Unfortunately, I cannot understand it.

**Comment by Shougo** [comment]
I get it.
It is feature and you can change the behavior.

**Comment by nhooyr** [comment]
@Shougo watch it in slow motion at exactly 50 seconds. You'll see Errorf pop up and then disappear.
