### ISSUE TITLE
backspace to show all completions?

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#131]
https://www.youtube.com/watch?v=2f_lpskwVgQ&feature=youtu.be

In this video I have the omni source min_pattern_length set to 1 (this same problem happens with deoplete-go if the min_pattern_length is set to be greater than 0)

If I change the min_pattern_length of the member source to a value greater than 0 it begins to work perfectly. Shouldn't member's min_pattern_length not be specifically assigned so it takes the user defined value?

**Comment by Shougo** [comment]
You should explain the detailed information.
I have not ESP skills.

I think you should map `<BS>` key.

```vim
	" <C-h>, <BS>: close popup and delete backword char.
	inoremap <expr><C-h> deoplete#mappings#smart_close_popup()."\<C-h>"
	inoremap <expr><BS>  deoplete#mappings#smart_close_popup()."\<C-h>"
```

**Comment by nhooyr** [comment]
@Shougo i added a edit. Has to do with the min_pattern_length's for some reason.

**Comment by Shougo** [comment]
No.  member source and omni sources are should be 0 by default.
And the sources can ignore `g:deoplete#auto_completion_lengh` value.  It is just default.
You can change it though.

You should change the issue title.
I cannot understand `backspace to show all completions?`.
So I explained the `<BS>` mapping.

**Comment by nhooyr** [comment]
@Shougo watch the video. I type some code and get some completions but I don't get all of the completions. I only get a few. But when I press backspace for whatever reason it decides to show me all of the completions now.

**Comment by Shougo** [comment]
@nhooyr It is neovim's feature.
Because, neovim narrows them instead of deoplete.
You can regenerate the candidates by `deoplete#complete_common_string()`.

**Comment by Shougo** [comment]
If you use `deoplete#mappings#smart_close_popup()`, it will close and regenerate the popup yes.

**Comment by nhooyr** [comment]
But if I change the min_pattern_length of the member source to 1 everything begins to work perfectly. When I press backspace it already regenerates the popup. It has to do with the min_pattern_length. I really don't think its neovim.
