### ISSUE TITLE
weird problem with min_length_pattern

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#132]
Ok so I am writing in go. I am using the omni source. I have set its min_pattern_length to 1. This causes weird problems with other sources whose min_pattern_length is 0 such as the member source. In this short video I show the problem.

First I will describe it. I have a very simple hello world file in go with the same setup described above.  Now I already have one line called 

```go
fmt.Print("hello")
```

Now If I try to add another line to print something. I type in "fmt.pri". It only shows me fmt.Print but in reality there is more than one function that fmt.pri matches. The omni source doesn't show at all, only the member source. Now if I type backspace it all of a sudden shows the other two.

However now if I change the min_length_pattern of the member source to 1 it starts working perfectly.

Lastly I also show the problem with flickering but you already said you're working on it.

https://asciinema.org/a/en7mon68ckde1sj4qikp1j1m6

Only thing I hate about asciinema is how ugly my terminal looks in it. God dammit.

**Comment by Shougo** [comment]
@nhooyr I have added `g:deoplete#enable_refresh_always` feature.
Please enable it.

**Comment by nhooyr** [comment]
@Shougo thank you so much.

**Comment by Shougo** [comment]
> Only thing I hate about asciinema is how ugly my terminal looks in it. God dammit.

This is better video than Youtube.
OK.  I get the problem.

**Comment by nhooyr** [comment]
@Shougo also what are the plans to fix the flicker? Is there any way I can help with that?

**Comment by Shougo** [comment]
> @Shougo also what are the plans to fix the flicker? Is there any way I can help with that?

I will improve the flicker.  But I must modify Vim/neovim source.
Please wait.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/4036

**Comment by nhooyr** [comment]
sweet!
