### ISSUE TITLE
Complete from other files in buffer with a different filetype

### ISSUE THREAD

**Issue by JelteF** [Shougo/deoplete.nvim#133]
Is it possible to complete from other files that are loaded in a buffer even when its filetype is different from the current file? In web development this happens quite often when editing css, javascript and html that uses the same classes or ids for elements.

I wouldn't mind adding this functionality myself, just don't know where to start exactly.

**Comment by Shougo** [comment]
You must install context_filetype plugin.
https://github.com/Shougo/context_filetype.vim
And you must set `g:context_filetype#same_filetypes` variable.
