### ISSUE TITLE
Expand snippets

### ISSUE THREAD

**Issue by astromac** [Shougo/deoplete.nvim#135]
## Expected
Is there a way to expand neosnippets/tern_for_vim using deoplete and neovim? It will paste the snippet to the document but won't expand it.

## Screen Shots
[Image of tern_for_vim dropdown]
https://www.dropbox.com/s/sxmp3egry14uovu/Screenshot%202016-01-18%2019.58.26.png?dl=0
[image of tern_for_vim completion]
https://www.dropbox.com/s/dhx89qm6kngwf6r/Screenshot%202016-01-18%2019.59.18.png?dl=0
[image of neosnippet dropdown]
https://www.dropbox.com/s/6m1rl1odz85t2u1/Screenshot%202016-01-18%2019.53.07.png?dl=0
[image of neosnippet completion]
https://www.dropbox.com/s/k5ofqnoe2kr7x39/Screenshot%202016-01-18%2019.54.00.png?dl=0

## Init.vim
The relevant portions of my init.vim file are as such:
```
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

let g:neosnippet#enable_snipmate_compatibility = 1

imap <C-@>     <Plug>(neosnippet_expand_or_jump) " works like <C-SPACE>
smap <C-@>     <Plug>(neosnippet_expand_or_jump) " works like <C-SPACE>
xmap <C-@>     <Plug>(neosnippet_expand_target)  " works like <C-SPACE>
inoremap <silent> <CR>   <C-r>=<SID>my_cr_function()<CR>

imap <expr><TAB>
 \ pumvisible() ? "\<C-n>" :
 \ neosnippet#expandable_or_jumpable() ?
 \    neosnippet#mappings#expand_or_jump_impl() : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
 \    neosnippet#mappings#expand_or_jump_impl() : "\<TAB>"V

function! s:my_cr_function()
  return pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
endfunction

if has('conceal')
  set conceallevel=2 concealcursor=i
endif
```
## Environment Information
OS: OS X 10.11.3
NVIM v0.1.2-253-g964e52e
Build type: Debug
Compilation: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/Users/chris/neovim/build/config -I/Users/chris/neovim/src -I/Users/chris/neovim/.deps/usr/include -I/Users/chris/neovim/.deps/usr/include -I/Users/chris/neovim/.deps/usr/include/luajit-2.0 -I/Users/chris/neovim/.deps/usr/include -I/Users/chris/neovim/.deps/usr/include -I/Users/chris/neovim/.deps/usr/include -I/Users/chris/neovim/.deps/usr/include -I/opt/local/include -I/opt/local/include -I/Users/chris/neovim/build/src/nvim/auto -I/Users/chris/neovim/build/include
Compiled by chris@CWB-MacBook.local

Optional features included (+) or not (-): +acl   +iconv    +jemalloc 
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

I'll generate logs if you think it's necessary.

**Comment by Shougo** [comment]
> Is there a way to expand neosnippets/tern_for_vim using deoplete and neovim? It will paste the snippet to the document but won't expand it.

I have not ESP skils....
You should explain it more clearly.
Your desired behavior is `g:neosnippet#enable_completed_snippet`?

And you must press `<C-@>` to expand the neosnippet snippet.

**Comment by astromac** [comment]
I don't know what you mean by "Your desired behavior is g:neosnippet#enable_completed_snippet?"

What I would like to happen is that the snippet is automatically expand after selecting it from the deoplete dropdown thus avoiding having to hit <C-@>.

**Comment by Shougo** [comment]
@astromac 

For tern_for_vim, neosnippet can expand the candidate by `g:neosnippet#enable_completed_snippet`.

For neosnippet candidates, it cannot.  It is Vim/neovim feature.  Closing.
