### ISSUE TITLE
[Discussion]how to deal with external source.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#137]
@Shougo @artur-shaik  @zchee @Rip-Rip

as the doc says https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L731-L748

The omni source works well for such completion plugin,supports fuzzy match,input_pattern setting.

If the external source set the `self.min_pattern_length = 0` ,it will auto source everywhere even someone do not need it.That will slowdown the input .I think the external source should be ignored by default.

By the way,is it possiable split the match function out of source,I think there is no need to implement the fuzzy match in every external souce

with default omni source I can use input_pattern setting like this.
```vim
            let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
            let g:deoplete#omni#input_patterns.java = [
                        \'[^. \t0-9]\.\w*',
                        \'[^. \t0-9]\->\w*',
                        \'[^. \t0-9]\::\w*',
                        \]
            let g:deoplete#omni#input_patterns.jsp = ['[^. \t0-9]\.\w*']
```

**Comment by Shougo** [comment]
@wsdjeg You should use `input_pattern` attribute instead of min_pattern_length.

```
				*deoplete-source-attribute-input_pattern*
input_pattern
		String				(Optional)
		If it is matched, deoplete ignores
		|deoplete-source-attribute-min_pattern_length|.
		It is useful for omni function sources.
		Note: It is Python3 regexp.

		If you omit it, this feature is ignored.
```

https://github.com/zchee/deoplete-go/issues/7

**Comment by Shougo** [comment]
For the fuzzy match, the omni source must not filter the candidates.
It is the deoplete filters work.

**Comment by wsdjeg** [comment]
I will try to improve https://github.com/artur-shaik/vim-javacomplete2/blob/master/rplugin/python3/deoplete/sources/javacomplete2.py
By the way,does the deoplete-go source support fuzzy match now?

**Comment by Shougo** [comment]
> By the way,does the deoplete-go source support fuzzy match now?

I think deoplete-go does not support fuzzy match.
Deoplete-go uses gocode's filter.

> By the way,does the deoplete-go source support fuzzy match now?

You must remove the completion prefix.
If you add the prefix, javacomplete2 uses it.

**Comment by wsdjeg** [comment]
> You must remove the completion prefix.
> If you add the prefix, javacomplete2 uses it.

what is completion prefix?

**Comment by zchee** [comment]
@wsdjeg 
`deoplete-go` does not use `self.min_pattern_length = 0` now.
I was improved.
https://github.com/zchee/deoplete-go/commit/b7318746d6c4913cb915910b6314b656baefedcd

and,
> I think deoplete-go does not support fuzzy match. deoplete-go uses gocode's filter.

Yes, `deoplete-go` does not support fuzzy match.
The specification of `gocode`.
`gocode` returns only word that depending on the situation.
but, Golang is a very small design, So Golang users are satisfied with it for now.

> If the external source set the self.min_pattern_length = 0 ,it will auto source everywhere even someone do not need it.That will slowdown the input .I think the external source should be ignored by default.

It is your thought.
If dissatisfied, it is better to set yourself. such as
https://github.com/wsdjeg/vim-javacomplete2/commit/f7293b3719e3f36cfeb7728073c43b5fdc72e18c
or 
```vim
call deoplete#custom#set('java', 'min_pattern_length', 1000)
```

===

FYI, `javacomplete2.py` is not necessary `get_complete_api`.
`deoplete-go` use `get_complete_api` for support both `gocode` and `vim-go` completion api.

**Comment by wsdjeg** [comment]
Thanks,I am using deoplete's omni source for javacomplete2 omnifunc now,I have tried to improve javacomplete2.py with fuzzy much ,but it does not work now.

**Comment by zchee** [comment]
@wsdjeg I wrote the modified version.
https://github.com/zchee/vim-javacomplete2/blob/cc24c1a05650af889ffa0072947a0e923c4cafe8/rplugin/python3/deoplete/sources/javacomplete2.py
Passing an empty string to `javacomplete#complete#complete#Complete`, Maybe support the fuzzy match.
I do not write java, so can not be more modified.

**Comment by wsdjeg** [comment]
the fuzzy match still can not work with your code

**Comment by wsdjeg** [comment]
@artur-shaik I think maybe there is no need to create javacomplete2.py,and just make omni.py works better.

**Comment by zchee** [comment]
@wsdjeg Hmm...
OK, I will remove the `support fuzzy match` from the commit message.
but, I anymore can not support.

I think support fuzzy-match need fix `javacomplete2` core code.
(Maybe `javacomplete2` will be ignored `a:base`.)

If you want to correspond to the fuzzy-match, You need to rewrite your own.

**Comment by wsdjeg** [comment]
thanks ,I got it,change to https://github.com/artur-shaik/vim-javacomplete2/pull/188

**Comment by zchee** [comment]
@wsdjeg :)
