### ISSUE TITLE
Buffer snippets clobber other sources

### ISSUE THREAD

**Issue by alexlafroscia** [Shougo/deoplete.nvim#138]
As a followup to #123 I was digging around with the code for the Ultisnips integration, when I realized what seems to be going on.  Originally, I thought that the Ultisnips source wasn't being shown at all.  However, what I realized was that, since the trigger that I was trying to use was called `test` and there were many instances of the word `test` in the current buffer, it was simply showing the Buffer source instead of the Ultisnips once.

To verify this, I opened a fresh JS file and typed `te<TAB>` and sure enough, the snippet appeared!

![screen shot 2016-01-22 at 2 40 30 pm](https://cloud.githubusercontent.com/assets/1645881/12521063/3f3906ea-c116-11e5-92cb-1b140f7d5d74.png)

However, if I inserted the snippet and then tried it a second time, instead of seeing the Ultisnips source in the dropdown list, only the instance of `test` that was in the current buffer appeared.

![screen shot 2016-01-22 at 2 40 40 pm](https://cloud.githubusercontent.com/assets/1645881/12521040/2737f7f4-c116-11e5-94cf-39b3dd552c31.png)

So clearly, it's not really a bug, so much as the match in the buffer overwriting the match from an external source.  However, I think that it would be better to show both, or show the Snippet instead of the match in the buffer since the additional context given there (what the snippet does) can be really useful.

**Comment by Shougo** [comment]
OK.  I get the problem.
UltiSnips source should set `dup` attribute like neosnippet source.

https://github.com/Shougo/neosnippet.vim/blob/master/rplugin/python3/deoplete/sources/neosnippet.py

**Comment by alexlafroscia** [comment]
I see!  Thanks for checking that out.  I'll send a PR to Ultisnips to try to get this fixed then!

**Comment by Shougo** [comment]
:-)
