### ISSUE TITLE
文字入力時にCPU使用率が異常に上昇する

### ISSUE THREAD

**Issue by Nymphium** [Shougo/deoplete.nvim#14]
*既存のファイル*を編集するとき､入力中に適当なタイミングでCPU使用率が異常に上昇します｡新規にファイルを作成して編集するときには起きません｡
プロセスを見てみると､`python3 -c import neovim; neovim.start_host() $HOME.nvim/deoplete.nvim/rplugin/python3/deoplete.py`のCPU使用率がほぼ100%になります｡

例えば､以下の内容のファイル`test.lua`があります｡
```lua
print "hello"
```

ここで､`nvim -u nvimrc-test test.lua`で編集し､

```lua
print "hello"

p -- insert mode中で､ここにカーソルがある
```

まで入力すると､CPU使用率が一気に上昇します｡

OSはArch Linux､NeovimはAURからインストールしたもので､バージョンは*0.0.0-alpha+201506121250*です｡

nvimrc-testとログは https://gist.github.com/Nymphium/97aafd14098a032a6245 に貼りました｡

**Comment by Shougo** [comment]
ログを確認しました。確かに無限ループに陥っているようです。
その nvimrc でよく似た現象を確認したいのでこちらでもチェックします。

**Comment by Shougo** [comment]
原因が分かりました。

`set completeopt+=menuone` を .nvimrc に記述してください。
deoplete 本体でも何か対策を考えます。
