### ISSUE TITLE
omni fuzzy match broken at the next line of @Override

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#140]
@Shougo I think the omni fuzzy match now is matching the `inputchar` with `complete_item.words`,I think the Item.abbr also should be take care of.
for example
```java
public class Foo{
    @Override
    _   // cursor is here
}
```
if I source omni mannully there will get all the method that can be overrided.
just give an example;
Item.words:  `protected Object clone() throws CloneNotSupportedException {`
Item.abbr  :  `clone()`
Item.menu:  `protected Object clone() throws CloneNotSupportedException`
Item.kind:    m
then if I type pr or pt or protected or any char in the first word of `Item.words`,this Item will not miss,as you know the `Item.words` contains space.I think the abbr `clone()` should also be matched,if so I can use `clone` to get this Item.
what do you think of this, @Shougo?

**Comment by Shougo** [comment]
It is Vim/neovim's feature.
I don't think abbr should be matched.
Closing.

**Comment by wsdjeg** [comment]
@artur-shaik what do you think about this,if the class has more than 50 methods ,how could we select the one we need?

**Comment by wsdjeg** [comment]
maybe we can start omni here
@Override
clone_

or provide a command use input() let us type into the name of method?

**Comment by Shougo** [comment]
I think "abbr" filter is not useful.  It is useful only for javacomplete2.
But I can add "matcher_full_fuzzy" feature.

**Comment by wsdjeg** [comment]
thanks,really love this plugin:smail:

**Comment by wsdjeg** [comment]
@artur-shaik If the feature implemented,I think you should know,<*_*>

**Comment by Shougo** [comment]
Implemented.

**Comment by wsdjeg** [comment]
Thank you very much indeed

**Comment by wsdjeg** [comment]
it works gread !!
hi @artur-shaik Thank for you JC2 ,also thank for @Shougo 
now let me show you how deoplete powerful！
![2016-01-26 20 55 32](https://cloud.githubusercontent.com/assets/13142418/12581054/305913a2-c46f-11e5-9987-ae17ba55290c.png)
![2016-01-26 20 55 37](https://cloud.githubusercontent.com/assets/13142418/12581057/34cc4d28-c46f-11e5-89f4-54679bc517fa.png)
