### ISSUE TITLE
Too much autocompletion with clang_complete

### ISSUE THREAD

**Issue by geratheon** [Shougo/deoplete.nvim#141]
Not really sure if this is an issue with deoplete or clang_complete, but I think it's deoplete ..

Whenever I go in insert mode, I get autocompletions. That's far too much and I don't think it's its desired behaviour. Here is a screen of what it looks like now:

![deoplete](https://cloud.githubusercontent.com/assets/5645703/12563329/16325c7e-c3aa-11e5-9cff-d10eb558829b.png)

Thats a bit distracting. I'd love to only get autocompletions, when I begin to type.

After researching I found out, that I can get it to work if I'll change `self.min_pattern_length` to 1, but regarding [you said it should be 0](https://github.com/Rip-Rip/clang_complete/issues/463#issuecomment-172415443) I thought, maybe it's a thing of configuring both of your plugins?

(Also, is it possible to map `c-n` to `tab`, but just when there are completions available? (Just like ycm) But that's a completely different story ..)

**Comment by Shougo** [comment]
https://github.com/zchee/deoplete-go/issues/7

Same problem.

**Comment by Shougo** [comment]
This is fixed in clang_complete.
