### ISSUE TITLE
Omnicompletions not popping up

### ISSUE THREAD

**Issue by pdoak** [Shougo/deoplete.nvim#142]
I have just installed Deoplete and omnicompletions in css files are not showing up.

Environment: Nvim 0.1.2-dev, OS X 10.11.3

I have tested with the following minimal vimrc:
```
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#deoplete_onmni_patterns = get(g:, 'deoplete#force_omni_input_patterns', {})
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
let g:deoplete#sources = {}
let g:deoplete#sources._=['omni', 'buffer', 'member', 'tag', 'ultisnips', 'file']
filetype plugin on
set omnifunc=syntaxcomplete#Complete
echom "minimal vimrc loaded"

```
I know that Omnicompletion is working because `<c-x><c-o>` shows the list of css completions. I am probably missing something simple to get it working.

**Comment by Shougo** [comment]
OK.  I will test it.
But please upload test example file to complete.

**Comment by pdoak** [comment]
Thanks for looking into this for me. 

What exactly are you looking for in a test example file. If I type any css in a *.css file, for example `margin`, the omnicomplete for the word margin does not appear. If I invoke `<c-x><c-o>` the options then appear i.e. margin:, margin-top:, margin-bottom:, margin-left:, margin-right:.

Please let me know if I can provide any further information.

**Comment by Shougo** [comment]
@pdoak I think it is not valid CSS file.

```css
margin-bottom:
```

I think the candidates should not be shown.

**Comment by pdoak** [comment]
@Shougo `margin-bottom` is valid css - please see [here](http://www.w3schools.com/css/css_margin.asp). Invoking `<c-x><c-o>` on `margin` shows the available css functions as one would expect. 
Unless I am misunderstanding how deplete should work, I would expect it to show the same available functions as `<c-x><c-o>`.

**Comment by Shougo** [comment]
OK.

**Comment by pdoak** [comment]
That worked. Thank you
