### ISSUE TITLE
Prevent deoplete from showing the `match x of x` message

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/deoplete.nvim#144]
![image](https://cloud.githubusercontent.com/assets/4171547/12675877/c61923bc-c68d-11e5-97be-aa7499dbcd6b.png)

And/or:

![image](https://cloud.githubusercontent.com/assets/4171547/12676039/3cdfdefe-c68f-11e5-9385-dfbec9c5810a.png)

I use `vim-go` with this recent PR https://github.com/fatih/vim-go/pull/685 This works very nice, but now as soon as I start typing in my function parameters, it starts to autocomplete (using the `buffer` source) which then shows the `match x of x` or `The only match` message.

Is there any way to prevent that message from displaying?

**Comment by Shougo** [comment]
Please read the deoplete documentation.

```
Q: I want to get quiet messages in auto completion.

A: You can disable the messages through the 'shortmess' option.
>
	if has("patch-7.4.314")
	  set shortmess+=c
	endif
<
```

**Comment by svanharmelen** [comment]
Thanks for your reaction! I did try that, but didn't work. So thought this was about something else...

I'm using neovim, should this setting still work in that case?

**Comment by Shougo** [comment]
I cannot reproduce your problem.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/deoplete-jedi/

let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.python = ''

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
inoremap <expr> <Tab>  deoplete#mappings#manual_complete()

syntax enable
filetype plugin indent on

set shortmess+=c
set cmdheight=2
set showmode
```

It works.
You should create minimal init.vim.

**Comment by svanharmelen** [comment]
Ok... Will double check with a minimal `init.nvim` and report back.

Thanks!

**Comment by svanharmelen** [comment]
Tested it again, and indeed it works. No clue why it didn't seem to work the first time I tested this.

Sorry for the noise!

**Comment by Shougo** [comment]
OK.
