### ISSUE TITLE
crashing when preview window will cover cursor with autocomplete while restoring

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#146]
I'm not sure if this is a neovim bug or a deoplete bug.

First make sure that `g:deoplete#disable_auto_complete = 0`. Next open a file that will open the preview window for autocomplete. Next add these two autocmds (essentially they make sure the preview window doesn't cause the main window to move when it opens or closes).

autocmd InsertEnter * let g:view=winsaveview()
autocmd WinEnter * call winrestview(g:view)

Enter insert mode, go to the very bottom of the file. Then type something that will trigger autocomplete and bam it crashes.

This doesn't happen with manual autocomplete.

**Comment by Shougo** [comment]
It seems neovim problem.
You should report it.

**Comment by zchee** [comment]
Sorry for I do not know the lapse of this matter.
If have been fixed or report for neovim core, I will close this issue.

ping @nhooyr

**Comment by nhooyr** [comment]
@zchee its open at neovim/neovim#4132

**Comment by zchee** [comment]
@nhooyr Thanks :)
