### ISSUE TITLE
error when leaving completion without completing

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#147]
https://github.com/neovim/neovim/issues/4132#issuecomment-177353013

Follow those exact same steps but instead of completing with tab, only let deoplete list the options and then press space. It gives this error because `word` is empty so it cannot be used as a key.

```
Error detected while processing function <SNR>36_complete_done:
line    4:
E713: Cannot use empty key for Dictionary
Press ENTER or type command to continue
```

**Comment by Shougo** [comment]
Fixed.
