### ISSUE TITLE
deoplete do not clean up popupmenu when it is empty line.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#148]
```java
public class Foo{
 @Override
  _  //cursor
}
```
1. source omni mannuly, type Ctrl + y close popupmenu without select anyitem.
2. them move cursor end of above line (end of `Override`) 
3. type Enter,the cursor then is on the position just like where I source omni
4. the popupmenu will be auto open ,I think it is due to the plugin do not clean up the Items when I type ctrl+y or Enter

**Comment by Shougo** [comment]
Please upload your deoplete configuration.
I think your omni pattern matches the empty line.

**Comment by wsdjeg** [comment]
ok,but it will not autoopen popupmenu before i manuly source omni

**Comment by Shougo** [comment]
And I don't want to test it by javacomplete2.
It cannot be reproduced in other omni functions?

**Comment by wsdjeg** [comment]
really sorry,I have test html xml js even if viml or py,no one show me like this.
I can show you my mini vimrc for this test;

**Comment by wsdjeg** [comment]
```vim
if has('vim_starting')
    if &compatible
        set nocompatible
    endif
    set runtimepath+=~/.vim/bundle/neobundle.vim/
endif
call neobundle#begin(expand('~/.vim/bundle/'))
scriptencoding utf-8
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Shougo/deoplete.nvim'
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni#input_patterns = get(g:,'deoplete#omni#input_patterns',{})
let g:deoplete#omni#input_patterns.java = [
            \'[^. \t0-9]\.\w*',
            \'[^. \t0-9]\->\w*',
            \'[^. \t0-9]\::\w*',
            \]
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['javacomplete2']
imap <expr> <leader><tab> deoplete#mappings#manual_complete(['omni'])
NeoBundle 'artur-shaik/vim-javacomplete2'
let g:JavaComplete_UseFQN = 1
let g:JavaComplete_ServerAutoShutdownTime = 300
let g:JavaComplete_MavenRepositoryDisable = 0
let g:JavaComplete_ClosingBrace = 0
call neobundle#end()
filetype plugin indent on
syntax on
NeoBundleCheck
set autoindent
" 自动智能对齐
set smartindent
autocmd FileType java set omnifunc=javacomplete#Complete
```

**Comment by wsdjeg** [comment]
Hi @Shougo I wilk write a new omnifunc for test,no need to test JC2

**Comment by wsdjeg** [comment]
@Shougo I have finish testomnifunc
reproduce step
1. open vim 
2. source testomnifun.vim
```vim
	fun! CompleteMonths(findstart, base)
	  if a:findstart
	    " locate the start of the word
	    let line = getline(line('.')-1)
        if matchend(line, '.*@Override$') >= 0
            return col('.')
        endif
	  else
	    " find months matching with "a:base"
	    let res = []
	    for m in split("Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec")
	      if m =~ '^' . a:base
		call add(res, m)
	      endif
	    endfor
	    return res
	  endif
	endfun
	set omnifunc=CompleteMonths

```
3. type into 
```java
    @Override
    _   //source omni here
```
then you will get
![2016-02-01 23 19 01](https://cloud.githubusercontent.com/assets/13142418/12721322/34ee2e6e-c93a-11e5-9ff0-97c5272614a6.png)
4. them just type ctrl+y or Enter to close the popupmenu
5. them move cursor end of above line (end of Override) 
6. type Enter,the cursor then is on the position just like where I source omni
7. the popupmenu will be auto open ,I think it is due to the plugin do not clean up the Items when I type ctrl+y or Enter

**Comment by wsdjeg** [comment]
here is the video
http://pan.baidu.com/s/1i4rU0eh

**Comment by Shougo** [comment]
OK.  I will test it.

**Comment by wsdjeg** [comment]
if  you can not open  the video,please tell me ,I will mail it to you,the size is about 1.4M

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
yes it has been fixed .thanks a lot,
but this issue #140  need to  reopened now,I can not complete like 
![2016-01-26 20 55 32](https://cloud.githubusercontent.com/assets/13142418/12581054/305913a2-c46f-11e5-9987-ae17ba55290c.png)

**Comment by Shougo** [comment]
@wsdjeg It is feature.  In manual complete, fuzzy match does not work.

**Comment by wsdjeg** [comment]
but befroe this commit,manual complete has fuzzy feature ignore case feature and so on just like autocomplet ,so I change ctrl x ctrl o to manual complete

**Comment by Shougo** [comment]
@wsdjeg If I enable the feature, this bug will happen.

**Comment by wsdjeg** [comment]
this issue is just a small bug,I think all of us need the fuzzy featury of manual complete,not only me.
I think only a few people will start complete from a empty line

**Comment by Shougo** [comment]
@wsdjeg The previous omni fuzzy behavior in manual is just bug.
Because, it makes previous cache.

**Comment by wsdjeg** [comment]
how about provide a func clean up previous cache mannully?

**Comment by Shougo** [comment]
No.

Use previous cache is too complex feature like neocomplete.
And it occurs unexpected behavior like this.

**Comment by wsdjeg** [comment]
but manual complete fuzzy feature is really useful 
you see we need this feature,complete afte `Sys`, the just type tr to match `SystemTray`

![2016-02-02 22-11-05](https://cloud.githubusercontent.com/assets/13142418/12751859/751d030a-c9fa-11e5-81d9-1e2d02a02911.png)

also I find a issue,when the popupmenu is exist, we can not start manual source omni

**Comment by Shougo** [comment]
Fixed it again.

**Comment by wsdjeg** [comment]
thans a lot,I will try it later

**Comment by wsdjeg** [comment]
nice,all the issue has been fixed,but the cache of empty line has not been clean up,just hidden ,if I type any char, the omni source still appears.but it is not a issue,so no need deal with it
