### ISSUE TITLE
How do we prevent auto bracket completion?

### ISSUE THREAD

**Issue by trusktr-goin** [Shougo/deoplete.nvim#150]
I'd like to turn that off, For example, I'd like to complete `functionName` but never `functionName(`.

**Comment by Shougo** [comment]
Why this feature is needed?
I think you want to insert parentheses automatically.
But you should use neopairs.vim.

https://github.com/Shougo/neopairs.vim

**Comment by nhooyr** [comment]
@Shougo sometimes in go for example you want to complete just the function name, not the parenthesis after.

**Comment by wsdjeg** [comment]
@trusktr-goin It is not deoplete's work,
for example the popupmenu item
item.word    :  functionName(   ===>  this will be compete into text
item,abbr     : functionName()
item.menu   :  functionName(args a,args b)
item.kind      :    f

all of this comes from the omni completion plugin or other plugin,

what deoplete has done is how to deal with this info.

**Comment by cj** [comment]
I tried adding `let g:deoplete#filters#converter_remove_paren = 1` but I'm still getting things like `post(`

**Comment by Shougo** [comment]
@cj You should read the documentation...

```vim
call deoplete#custom#set('_', 'converters', ['converter_remove_paren'])
```

**Comment by cj** [comment]
@Shougo I did, it was a bit confusing.  the docs for this are here https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L492 but how to set it are here https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L327.  But now I know.  Thank you :smile:

**Comment by Shougo** [comment]
I added FAQ section.
