### ISSUE TITLE
vim-go autocomplete not working with neovim

### ISSUE THREAD

**Issue by pratz** [Shougo/deoplete.nvim#152]
Neovim:
- deoplete/vim-go golang auto complete is not working for me.
- though python auto complete works.
- I am guessing this has to do something with gocode lib.
- my nvimrc https://github.com/pratz/dotfiles/blob/master/neovim/init.vim

Vim:
- necomplete/vim-go golang auto complete works fine using the same gocode lib.
- my vimrc https://github.com/pratz/dotfiles/blob/master/vim.complete/.vimrc

If you guys can figure this out please let me know, thanks.

**Comment by nhooyr** [comment]
read the manual next time. You need deoplete-go https://github.com/zchee/deoplete-go

**Comment by Shougo** [comment]
Yes.  Closing.

**Comment by j0hnr3d** [comment]
golang autocomplete is not working for me.
@pr4th4m is right.
i am using neovim too and deoplete/go is not working!
can anyone help me?

**Comment by Shougo** [comment]
@j0hnr3d Please read this.
https://github.com/Shougo/deoplete.nvim/issues/1138
