### ISSUE TITLE
Very slow completion behavior, how do I begin to debug?

### ISSUE THREAD

**Issue by sethwoodworth** [Shougo/deoplete.nvim#154]
Often, when deoplete triggers, my UI freezes and I have to wait for upto a minute before I can continue.  My keyboard input still works (although nothing new is displayed)  and I can finish typing.

I realize this is an extremely vague  issue.  Can you help me introspect the deoplete process?

The relevant section of my `nvim/init.vim`

```vimscript
" Completion: Using deoplete.     
let g:deoplete#enable_at_startup = 1 
let g:deoplete#sources = {}
let g:deoplete#sources.python = ['buffer', 'tag', 'member', 'omni']
let g:deoplete#sources.ruby = ['buffer', 'tag', 'member', 'omni']
let g:deoplete#auto_completion_start_length = 5
let g:deoplete#max_list = 50  
```

**Comment by Shougo** [comment]
I think this is omnifunc freeze.
Omnifunc is not asynchronous.
Please upload the reproduce ways from Vim starting like other issues.

**Comment by romgrk** [comment]
I confirm having the same problem. Disabling omnifunc doesn't seem to help. 
On the same subject, is there a way to `DeopleteDisable`, for when it gets to slow?

**Comment by Shougo** [comment]
> I confirm having the same problem. Disabling omnifunc doesn't seem to help. 

Hm.  Please upload the reproduce ways.

> On the same subject, is there a way to DeopleteDisable, for when it gets to slow?

Please read the documentation.
You can disable the auto completion by `g:deoplete#disable_auto_completion`.

**Comment by romgrk** [comment]
Ok, thanks, yes I was aware of `g:deoplete#disable_auto_completion`, but it didn't seemed very standard (because `let`ing a var is rarely used as disable mechanism).
Doesn't seem to happen now, but if it does i'll update with steps and configuration.

**Comment by GregorySchwartz** [comment]
I also have this issue. The entire interface hangs after a few characters and it is auto complete related. I did notice, however, that it always happens when I first open the file and type the first characters, after that initial freeze everything is fast and snappy.

**Comment by Shougo** [comment]
@GregorySchwartz Please read CONTRIBUTING.md.
I have not ESP skills.

**Comment by cazador481** [comment]
I am also seeing this issue, alas I can get it to reproduce.  As soon as I get a reproducible slow down I will post it.  Is there a posibilty to add a profiling option to see how long we spend in each source for completion?

**Comment by mattsawyer77** [comment]
I'm seeing this too, though I don't have a good repro yet. I took a guess and rolled back to 65cfbcc0a63d669ccc770716f2e207e61f962466 and I don't see the problem anymore. I'll try to gather more info and report back.

**Comment by Shougo** [comment]
@mattsawyer77 Hm. Please use `git bisect`.

@cazador481 OK.  I will add the feature.

**Comment by cazador481** [comment]
Looks like I have been able to finally reproduce the issue.
Gist of the debug log: https://gist.github.com/cazador481/eb086a308bc50414c1e8

Completing file https://gist.github.com/cazador481/8e8361e44d93a1490b4a
create a new line at 112.  Add self.BufferFooBar.  Issues start hapenning as you get past self.

My init: https://github.com/cazador481/neovim_dot_files/blob/master/.config/nvim/init.vim

deoplete version https://github.com/cazador481/neovim_dot_files/blob/master/.config/nvim/init.vim

I ran out time to get a small version of my init.vim   I will try that tomorrow.
Additional note:  If I disable neco-syntax it speeds up a bit but not fully.  
If I look at the log I can see a ton potential completions going to the filter.  As I try the completion

**Comment by Shougo** [comment]
I get the reason.  I will fix it later.  Please wait.
And I will add the profile feature.

**Comment by Shougo** [comment]
Fixed.

**Comment by cazador481** [comment]
Thanks for the fix.
