### ISSUE TITLE
buffer source is giving odd completes

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#155]
Pretty simple to reproduce.

Open nvim, edit a empty buffer, set the filetype to vim and type the following.

```vim
let g:lmao = 1
let g:lmao = g:lma
```

At the very ending you should see the buffer source giving you a really weird completion that makes it look like this

```vim
let g:lmao = 1
let g:lmao = t g:lmao = g:lmalmao
```

**Comment by Shougo** [comment]
@nhooyr Please create minimal init.vim.  I will try it.

**Comment by nhooyr** [comment]
```vim
call plug#begin('/usr/local/etc/dotfiles/nvim/plugged')
Plug 'Shougo/deoplete.nvim'
Plug 'Shougo/neco-vim'
call plug#end()
let g:deoplete#enable_at_startup = 1
```

Turns out you need neco-vim to reproduce.

**Comment by Shougo** [comment]
Can you upload the gif file?
I want to look the behavior.

**Comment by nhooyr** [comment]
https://asciinema.org/a/6xx7jhi17e9f3i957qgngzvbk

**Comment by Shougo** [comment]
I get it.  It is bug.  Thanks.

**Comment by Shougo** [comment]
Fixed.
