### ISSUE TITLE
deoplete#max_list not working

### ISSUE THREAD

**Issue by aakashsigdel** [Shougo/deoplete.nvim#156]
I made a minimum vimrc and set the max_list to 10, but still the completion popup shows up too many entries in the list.
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/4772643/12864085/7a90d710-cca9-11e5-9739-022e41aa8867.gif)

**Comment by Shougo** [comment]
I cannot reproduce your problem.
Your `vi` command is really `nvim`?

And your vimrc seems not minimal.  Because, it does not change the runtimepath.
And please tell me the your deoplete version.

My minimal init.vim

```vim
set rtp+=~/work/deoplete.nvim/

let g:deoplete#enable_at_startup = 1
let g:deoplete#max_list = 10
```

**Comment by aakashsigdel** [comment]
- even after setting the runtime path i get more than 10 items. 
- yes vi is nvim alias; I even tried it with nvim -u init.vim foo, still not working
- as for deoplete version, I just cloned your master branch

**Comment by Shougo** [comment]
@aakashsigdel Please check `g:deoplete#max_list` value after completion.

**Comment by aakashsigdel** [comment]
it is set to 10

**Comment by Shougo** [comment]
> as for deoplete version, I just cloned your master branch

Please upload your deoplete version by `git log`.
And please upload your `:scriptname` result.

**Comment by zchee** [comment]
@aakashsigdel I have tested this issue been asked to @Shougo.
but did not reproduce :(
See https://asciinema.org/a/35671

**Comment by aakashsigdel** [comment]
[gitlog.txt](https://github.com/Shougo/deoplete.nvim/files/120136/gitlog.txt)
[scriptname.txt](https://github.com/Shougo/deoplete.nvim/files/120135/scriptname.txt)

Here are the script name and git log

**Comment by zchee** [comment]
@aakashsigdel FYI, If launch `nvim` with this flag, default of `shada`(`~/.local/share/nvim/shada/main.shada`) will be loaded.
```bash
nvim -u foo.vim aakash.js
```
Relationship is unlikely, but please try `nvim -i NONE -u vimrc aakash.js`

**Comment by aakashsigdel** [comment]
@zchee I am still getting the same long list of completion even after trying 
`nvim -i NONE -u vimrc aakash.js`

**Comment by Shougo** [comment]
@aakashsigdel 

```
~/temp/init.vim
  2: ~/.config/nvim/plugin/deoplete.vim
  3: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/gzip.vim
  4: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/man.vim
  5: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchit.vim
  6: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/matchparen.vim
  7: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/netrwPlugin.vim
  8: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rplugin.vim
  9: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/remote/host.vim
 10: ~/temp/.-rplugin~
 11: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/autoload/remote/define.vim
 12: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/rrhelper.vim
 13: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/shada.vim
 14: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/spellfile.vim
 15: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tarPlugin.vim
 16: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tohtml.vim
 17: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/tutor.vim
 18: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/vimballPlugin.vim
 19: /usr/local/Cellar/neovim/HEAD/share/nvim/runtime/plugin/zipPlugin.vim
 20: ~/Practice/deoplete.nvim/plugin/deoplete.vim
```

Two different `plugin/deoplete.vim` is loaded.
Please check it.
I think you have installed older one.

**Comment by Shougo** [comment]
And please upload `.-rplugin~` file.

**Comment by aakashsigdel** [comment]
It was due to the conflicting deoplete version I installed little while ago. Sorry for the trouble. Thank you

**Comment by balta2ar** [comment]
@Shougo is there an option to set `max_list` limit per Source? I'd like to limit one Source more than another. Is that possible?

**Comment by Shougo** [comment]
Nothing.   But it is possible to add.

**Comment by balta2ar** [comment]
Created an issue: https://github.com/Shougo/deoplete.nvim/issues/731

**Comment by Shougo** [comment]
OK
