### ISSUE TITLE
Deoplete.nvim is not registered as Neovim remote plugins

### ISSUE THREAD

**Issue by theamazingfedex** [Shougo/deoplete.nvim#160]
### Problem Summary
Alright, so I'm on a Mac, and I have installed Deoplete.nvim using NeoBundle, with Python3 in my $PATH after upgrading my Neovim to support Python3 by calling `sudo pip3 install neovim`, `:echo has("python3")` returns `1`, and `g:deoplete#enable_at_startup = 1`. The problem is that every time I start up Neovim, I get the deoplete warning: `Please execute :UpdateRemotePlugins command and restart Neovim`. Even if I run that command, or **`:NeoBundleRemotePlugins`**, then restart Neovim, I again get that same message asking me to run `:UpdateRemotePlugins and restart`.

If I try to just run `:DeopleteEnable`, I get an error saying:
`deoplete.nvim is not registered as neovim remote plugins`
`Please execute :UpdateRemotePlugins command and restart Neovim`

#### Operating System:  
`OSX Yosemite`
#### Neovim Version: 
`v0.1.1-8-gf40c8c4`
#### Minimal init.vim:
`g:deoplete#enable_at_startup = 1`
#### Generated Logfile:
[Gist of Neovim Log](https://gist.github.com/theamazingfedex/270f875bd2ab52a6076e)

**Comment by Shougo** [comment]
If you use `NeoBundle`, please use `NeoBundleRemotePlugins` command instead of `UpdateRemotePlugins`.
`UpdateRemotePlugins` cannot register lazy loaded plugins.

**Comment by Shougo** [comment]
And it may be neovim's error.
Please read it.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by theamazingfedex** [comment]
Sorry, I was in fact using that function to try to update the remote plugins. Also, I updated my original issue to better reflect the contribution guidelines.

**Comment by Shougo** [comment]
@theamazingfedex Please generate the log file.

```
    export NVIM_PYTHON_LOG_FILE=/tmp/log
    export NVIM_PYTHON_LOG_LEVEL=DEBUG
    nvim -u minimal.vimrc
    some works
    cat /tmp/log_{PID}
`

**Comment by Shougo** [comment]
> Minimal init.vim:

You must set runtimepath.

```
" Your minimal.vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

**Comment by theamazingfedex** [comment]
I tried adding the set runtimepath, without success. I went ahead and gathered the logfile, and put it in a Gist in the base issue.

**Comment by Shougo** [comment]
Please upload your nvimrc-rcplugin file.
It is located in `/Users/daniwood/.nvim`.

My rcplugin file.

```vim
" python3 plugins
call remote#host#RegisterPlugin('python3', '/home/shougo/.nvim/rplugin/python3/snake.py', [
      \ {'sync': 1, 'name': 'SnakeStart', 'type': 'command', 'opts': {}},
     \ ])
call remote#host#RegisterPlugin('python3', '/home/shougo/work/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])


" python plugins
```

The file must be loaded on neovim startup.
But if your runtimepath is broken, it is not loaded.

Please upload your runtimepath.

**Comment by theamazingfedex** [comment]
Adding this to my init file and updating it for my machine fixed my problems. Thanks!
```vim
call remote#host#RegisterPlugin('python3', '/home/shougo/work/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])
```

**Comment by Shougo** [comment]
Hm... It is the strange.

**Comment by Shougo** [comment]
@theamazingfedex Can you test it in #167?
I want to fix the problem.

**Comment by theamazingfedex** [comment]
At one point in the past, I was getting errors about multiple init files from the init.vim-rplugin~ file, so I put a line in at the bottom of my vimrc to delete the file, which stopped me getting that error.
Since that file seems to be needed for some plugins, I just removed that line to delete the file, and since I updated Neovim recently I don't get the multiple init file error, AND I don't need to add in the manual remote plugin registration anymore, it just works.

My suggestion for others having the same issue, would be to try updating your neovim to the head revision, make sure there's nothing too hacky and archaic in your vimrc/init.vim, and if it's still not working, try manually registering the plugin in your vimrc/init.vim, like so:
````vim
call remote#host#RegisterPlugin('python3', '/Users/shougo/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])
````

**Comment by kreedz** [comment]
If you're using vim-plug, try update vim-plug iteself `PlugUpgrade`.
It helped to me to get rid of this message `is not registered as neovim remote plugin`.
Before `PlugUpgrade` I've removed all installed plugins. And installed them again when vim-pug was upgraded.

**Comment by voodoomsr** [comment]
> 
> 
> If you're using vim-plug, try update vim-plug iteself `PlugUpgrade`.
> It helped to me to get rid of this message `is not registered as neovim remote plugin`.
> Before `PlugUpgrade` I've removed all installed plugins. And installed them again when vim-pug was upgraded.

PlugUpgrade was enough for me, I was having the problem with neovim on windows. Thanks for the suggestion.
