### ISSUE TITLE
Deoplete fails after using multiple-cursors

### ISSUE THREAD

**Issue by firedev** [Shougo/deoplete.nvim#162]
After inserting text in a few lines `multiple-cursors`, pressing `i` fails with the following:

```
Error detected while processing function <SNR>160_completion_begin:             
line   27:                                                                      
E475: Invalid argument: Channel doesn't exist                                   
```

Anything I can do to debug this?

Thanks.

**Comment by Shougo** [comment]
Hm.  I don't know the problem.
But multiple-cursors conflicts the auto completion plugin easily.
You should disable auto completion like this.

https://github.com/Shougo/neocomplete.vim/issues/394

```vim
function! Multiple_cursors_before()
    let b:deoplete_disable_auto_complete = 1
endfunction

function! Multiple_cursors_after()
    let b:deoplete_disable_auto_complete = 0
endfunction
``

**Comment by firedev** [comment]
Thanks! That seemed to work.

**Comment by wavded** [comment]
I have the same error.  I do not use multiple cursors.  A file will work for a bit and then every character stroke inside insert mode will cause this error.  Any idea on how to narrow down the problem?

**Comment by Shougo** [comment]
@wavded Please create minimal init.vim less than 50 lines and upload the reproduce ways from neovim starting.
You should create another issue.
