### ISSUE TITLE
UltiSnips + Deoplete Tab Mapping - Works properly only after loading .vimrc again

### ISSUE THREAD

**Issue by AklemTech** [Shougo/deoplete.nvim#164]
## Environment Information
OS: Arch
Neovim Version: 0.1.2

## Minimal Vimrc
```
set rtp+=~/.config/nvim/plugged/ultisnips/
set rtp+=~/.config/nvim/plugged/deoplete.nvim/

let g:deoplete#enable_at_startup = 1

let g:UltiSnipsExpandTrigger="<tab>"
let g:UltiSnipsJumpForwardTrigger="<tab>"
let g:UltiSnipsJumpBackwardTrigger="<s-tab>"

inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><s-tab> pumvisible() ? "\<C-p>" : "\<TAB>"
```

When I load up nvim for the first time with this configuration, tab does not press C-N as mapped (with a completion available). However, with UltiSnips removed, or strangely, when I load the vimrc again with the source command, it starts working.

I am not sure which plugin is creating the incompatibility.

**Comment by sir-minty** [comment]
Did you resolve this problem?  I'm experiencing the same behavior.  Would like to know if you have a solution for this.

**Comment by Shougo** [comment]
@sir-wiggles This is UltiSnips problem.
