### ISSUE TITLE
Deoplete prints to the command line on 'insert enter'

### ISSUE THREAD

**Issue by yevhen-m** [Shougo/deoplete.nvim#165]
![image](https://cloud.githubusercontent.com/assets/10185058/12989732/47f40844-d10f-11e5-99a2-afba3d2f6761.png)

Hey, deoplete started to print these quotes on insert-enter, how can I stop it?

**Comment by nhooyr** [comment]
I opened #166 to correct this. Just wait for Shougo to merge or comment out those lines in your deoplete.

**Comment by Shougo** [comment]
Already fixed.
