### ISSUE TITLE
Errors with Python 3 when changing the installation directory

### ISSUE THREAD

**Issue by RenatoUtsch** [Shougo/deoplete.nvim#168]
I'm having the same error as #59 if I change the vim-plug installation directory from `~/.vim/plugged` to `~/.config/nvim/plugged` when using vim-plug to install deoplete.

**Comment by Shougo** [comment]
OK.  I get it.
You must re-execute `UpdateRemotePlugins` command to update the path.
Because, previous invalid path is already cached.

**Comment by RenatoUtsch** [comment]
Where is this invalid path cached? Because I deleted the entire plugged directory and this still happened.

**Comment by Shougo** [comment]
@RenatoUtsch Please see #160

**Comment by nightire** [comment]
I'm sorry but #160 doesn't answer where is the invalid cached path? I've already try all the solution I've found but none of it works right now.

So how should we clear all the useless stuff and reinstall deoplete to make it works again?

**Comment by Shougo** [comment]
@nightire You should check your rcplugin file.
I think your cached file is broken.

**Comment by nightire** [comment]
@Shougo OK, thank you.

I've just update deoplete, seems it works again magically ;)
