### ISSUE TITLE
how to install deoplete?

### ISSUE THREAD

**Issue by nedab** [Shougo/deoplete.nvim#169]
my system is arch
and I am using neovim with python3 support (tested it, 'echo' gives me 1)

Why is installing so hard? I am trying for a long time now, and nothing works;
all the time I get "not an editor command: deoplete".

I have no idea in what folder which files should go, tried several options but neobundle is not setting it up.

Can anybody help me?

PS: after several managers I have tried vim-plug and it finally worked.
Still, this nice piece of software is too difficult to install.

**Comment by zchee** [comment]
@nedab Hi,
> Why is installing so hard? I am trying for a long time now, and nothing works;

It was difficult?
FYI, Here is tiny init.vim for `deoplete.nvim`
https://gist.github.com/zchee/a081e58555bdf4b7335b

```bash
$ nvim -u ./deoplete.init.vim
```
In nvim,

```vim
:UpdateRemotePlugins
:quit
```
again,
```bash
$ nvim -u ./deoplete.init.vim
```

`deoplete.nvim` is worked.
I think that it is easy.

> PS: after several managers I have tried vim-plug and it finally worked.

I was relieved to hear that.
but I do not know what has been difficult.

**Comment by okket** [comment]
Here is a more elaborate guide for vim-plug, ternjs and deoplete:

https://gregjs.com/vim/2016/configuring-the-deoplete-asynchronous-keyword-completion-plugin-with-tern-for-vim/

If you know vim it is pretty straight forward, but I wouldn't call it easy. But then, so is vim?

**Comment by zchee** [comment]
@okket Oh, Thanks for great how to :)
That seems perfect!

**Comment by nedab** [comment]
Thanks.

@zchee:
you assume that I found the right files from git, I dont know.
Why no git clone or a simple curl command? This "unpack the files" confused me.


The thing is that $XDG_CONFIG_HOME is empty and not set;
and nowhere I could find any init.vim for example though installing neovim from AUR.

@okket:
That howto I already found and followed it.

But now I always have to PlugInstall to be able to use DeopleteEnable
though my vimrc is sourcing fine and the files are where they belong.

**Comment by wsdjeg** [comment]
@okket 
> You should use one of the many plugin managers to install the plugins. Shougo made one (of course he did) called neocomplete, but personally I use vim-plug, so I’ll be using that syntax.

just a type, I think it is neobundle not neocomplete

**Comment by Shougo** [comment]
@nedab Your init.vim seems be broken.
You should upload the init.vim.  Other users can check it.

**Comment by nedab** [comment]
My Scripts were loaded correctly, I always checked with `:scriptnames`

Tried the init.vim above, neovim is loading it, installs it, but the issue still persists and apperently I am not alone, neovim seems to be the problem.

**Comment by Shougo** [comment]
@nedab Why don't you set `g:deoplete#enable_at_startup` to 1?
