### ISSUE TITLE
Kind of janky completion

### ISSUE THREAD

**Issue by landaire** [Shougo/deoplete.nvim#170]
I started using deoplete recently and I've been getting kind of janky autocomplete for some reason. I really only get autocomplete in Go projects so this may be an issue with deoplete-go, but I'm not certain.

My vimrc:

```
call plug#begin('~/.vim/plugged')

Plug 'zchee/deoplete-go'           " Go autocomplete hook for deoplete
Plug 'Shougo/deoplete.nvim'        " Async autocomplete for neovim

call plug#end()

" Deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
```

Video: https://www.youtube.com/watch?v=H0yS6X-BXPY&feature=youtu.be

And here's a bonus clip of something that happens when my cursor isn't even moving: https://gfycat.com/FantasticImmaculateAlaskankleekai

**Comment by zchee** [comment]
@landaire Hi,
This problem is not related deoplete/deoplete-go.
It is Vim/neovim feature.

See also https://github.com/zchee/deoplete-go/issues/40

**Comment by landaire** [comment]
Thanks for the feedback @zchee. I'll close this issue and carry on discussion there.

**Comment by zchee** [comment]
@landaire :)
Also, If you want `preview` like behavior,
```vim
set completeopt-=preview
```
and install
https://github.com/Shougo/echodoc.vim

![](https://cloud.githubusercontent.com/assets/6366270/13019427/bacdee76-d212-11e5-873c-6e1975163d0a.png)
