### ISSUE TITLE
PHP completion only works on empty buffer

### ISSUE THREAD

**Issue by vitaminless** [Shougo/deoplete.nvim#173]
When I have an empty buffer, which is not associated to a file yet everything works fine so far, but when I open a file completion does not work at all.

Even with &lt;C-x&gt;&lt;C-o&gt; I have nothing.
I noticed that a process is started which takes immediately 100% of one core and it seems to me that deoplete/omnicomplete tries to gather candidates again and again and I get a popup which closes just after it is visible, almost unrecognisable when my computer has nothing to do.

I attached the logs I receive for the problem.

[log_30707.txt](https://github.com/Shougo/deoplete.nvim/files/129708/log_30707.txt)
[log_30714.txt](https://github.com/Shougo/deoplete.nvim/files/129709/log_30714.txt)
[log_32143.txt](https://github.com/Shougo/deoplete.nvim/files/129710/log_32143.txt)

My configuration:

```VimL
" Got this from neocomplete, it seems this doesn't affect deoplete
"let g:acp_enableAtStartup = 0
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
"let g:deoplete#enable_refresh_always = 0

let g:deoplete#omni_patterns = {
  \ 'php': '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
\ }

" Define keyword
if !exists('g:deoplete#keyword_patterns')
    let g:deoplete#keyword_patterns = {}
endif

let g:deoplete#keyword_patterns.default = '[a-zA-Z_]\w{2,}?'
" vim: set tw=80 sw=2 sts=2 et foldmethod=marker :
```

**Comment by Shougo** [comment]
It is the omnifunc infinite loop.
I cannot fix.  Closing.

**Comment by Shougo** [comment]
I think it is better PHP auto completion.

https://github.com/m2mdas/phpcomplete-extended

**Comment by vitaminless** [comment]
Thank you, I will give a try.

Anyway, great plugin!

**Comment by roxma** [comment]
looks like [m2mdas/phpcomplete-extended](https://github.com/m2mdas/phpcomplete-extended) is unmaintained now? The last commit is 2 years ago.

**Comment by roxma** [comment]
Is ther any alternatives to phpcomplete-extended ?

**Comment by Shougo** [comment]
You can create it!

**Comment by roxma** [comment]
Yeah, I'm planning on that. Don't know how completions works internally right now. Long way to go.

**Comment by Shougo** [comment]
@roxma 

phpcomplete.vim worked.  You don't have to use this.
https://github.com/roxma/SimpleAutoComplPop

```vim
		let g:deoplete#omni#input_patterns.php =
		\ '\w+|[^. \t]->\w*\|\w+::\w*'
```

**Comment by roxma** [comment]
@Shougo 

Thanks, I still can't get it work for me, Here's my configurations:

```
" Got this from neocomplete, it seems this doesn't affect deoplete
"let g:acp_enableAtStartup = 0
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
"let g:deoplete#enable_refresh_always = 0

"let g:deoplete#omni_patterns = {
"  \ 'php': '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
"\ }
let deoplete#omni#input_patterns = {
  \ 'php': '\w+|[^. \t]->\w*\|\w+::\w*'
\ }

" Define keyword
if !exists('g:deoplete#keyword_patterns')
    let g:deoplete#keyword_patterns = {}
endif

let g:deoplete#keyword_patterns.default = '[a-zA-Z_]\w{2,}?'
" vim: set tw=80 sw=2 sts=2 et foldmethod=marker :
```

Also I notice that deoplete needs neovim-python ver.0.1.8+, I've upgrade the pip, do I need to recomplie neovim after that?

**Comment by Shougo** [comment]
Sorry.

```vim
        let g:deoplete#omni#input_patterns.php =
        \ '\w+|[^. \t]->\w*|\w+::\w*'
```

Is correct.
