### ISSUE TITLE
Completion matches breaks "virtualedit=all"

### ISSUE THREAD

**Issue by DarkDefender** [Shougo/deoplete.nvim#174]
Deoplete seems to move the cursor back if you try to go past a newline and the word before the newline can trigger completion results.

For example in init.vim if you have the following line:
"cal\n"

If you go past the newline in normal mode with "virtualedit=all" set, and then enter insert mode, the cursor will be moved back to the end of "cal" and results will be shown (trying to match the vim "call" command).

This also happens in insert mode if you just type "cal" and then try to move right with the right arrow key.

**Comment by Shougo** [comment]
Fixed.  Thanks.

**Comment by DarkDefender** [comment]
Awesome! Thanks for the quick fix! :)

**Comment by DarkDefender** [comment]
Just a quick note. The fix to #177 breaks moving right when completion results are displayed. It now moves the cursor back to the end of the line and displays the completion results once more.

**Comment by Shougo** [comment]
Fixed again.

**Comment by DarkDefender** [comment]
Thanks! :)

**Comment by washtubs** [comment]
Any chance you can fix this again? Looks like it got dropped between 1.1 and 1.2. It's not a huge deal though. I just started using virtualedit=all and noticed it.

**Comment by washtubs** [comment]
I'm not based off the latest master but I had success just applying your [fix](3bd22ca37599454e6e282c8cb423c9e5548ff18e) by hand.

**Comment by Shougo** [comment]
I don't know why it is removed.
But I think it has some problem...

**Comment by Shougo** [comment]
I have added `virtcol()` check again.

**Comment by washtubs** [comment]
Rad! Thank you
