### ISSUE TITLE
Documentation for patterns not clear

### ISSUE THREAD

**Issue by alerque** [Shougo/deoplete.nvim#175]
I've been sorting through the help file trying to figure out how to match various patterns. I've been unable to figure out what the correct combination of `g:deoplete#omni#input_patterns` and `g:deoplete#omni_patterns` is for some scenarios. I understand that English is not your first language, but the help blobs for these don't make sense to me. I'd like to help you word them better, but first I need to understand when to use which one.

For example I would like to use a specific matching function for `mail` file types. I [have the function](https://github.com/alerque/que-mutt/blob/master/.config/nvim/autoload/mailcomplete.vim) set in `set omnifunc=mailcomplete#Complete` such that it can complete names and addresses from my contacts. I would like it to activate this function on the `To: `, `Cc:`, `Bcc:` lines while I'm editing mails in Neo**vim**.

So far I have:

    let g:deoplete#omni_patterns.mail = ['^\u\l\+: \w\w\w\+']

This works to only complete on the first word of header fields. For example this will complete:

    To: cal‸

But this won't:

    To: Sample Name <name@example.com>,  cal‸

How can I setup a pattern that will only match on email header lines but will work either after `: ` or after `, `?

**Comment by zchee** [comment]
@alerque Thanks issue.

I will debug with install your `mailcomplete.vim` script.
and I'll explain the details of `input_patterns` and `omni_patterns` variables.

BTW, do you have experience in writing a python or Golang?
As an interim answer,
`input_patterns` in Python,


Please wait a moment now.

**Comment by Shougo** [comment]
@alerque For the documentation, please create the Pull Request.

Fox the regex, it is not Q/A site.  You should ask the regex for other place.
`g:deoplete#omni_patterns` is Vim script regex.
You can test the pattern by Vim script.
It is hard to write the complex regex.  I have not much time to debug your regex.

**Comment by alerque** [comment]
Dude I wasn't asking you de debug my regex, I can do that just fine. What I can't do is decipher your documentation. And I can't send a PR that fixes the English until I understand roughly what it's trying to communicate. Hence why I opened this as an issue report. This is not a support question.

Look, these make no sense:

[Line 197](https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L197)

```
g:deoplete#omni_patterns
		This dictionary records keyword patterns to Omni completion.
```

[Line 262](https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L262)

```
g:deoplete#omni#input_patterns
		This dictionary records keyword patterns to Omni completion.
```

These documentation strings don't give any indication of what the difference between them is, when you should use one over the other, or how they interact with each other. Frankly they just don't communicate anything useful.

I'm willing to help write better English descriptions but I need some pointers on what these are to work with. I gave you my specific example as a scenario where it's impossible to figure out from the manual what setup to use.

**Comment by Shougo** [comment]
OK.  I get it.  But please read the documentation and implementation more.

Why don't you read the full section?

These are not same.

```
				*g:deoplete#omni_patterns*
g:deoplete#omni_patterns
		This dictionary records keyword patterns to Omni completion.
		This is appointed in regular expression string or list every
		file type.
		If this pattern is not defined or empty pattern, deoplete
		does not call 'omnifunc'.
		Note: If it is a set, deoplete will call 'omnifunc'
		directly.  So almost deoplete features are disabled.
		Note: It is Vim regexp.
>
		let g:deoplete#omni_patterns = {}
		let g:deoplete#omni_patterns.java = '[^. *\t]\.\w*'
		let g:deoplete#omni_patterns.php =
		\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
<
		Default value: in g:deoplete#_omni_patterns
```

```
				*g:deoplete#omni#input_patterns*
g:deoplete#omni#input_patterns
		This dictionary records keyword patterns to Omni completion.
		This is appointed in regular expression string or list every
		file type.
		If this pattern is not defined or empty pattern, deoplete
		does not call 'omnifunc'.
		Note: Some omnifuncs which moves the cursor is not worked.
		For example, htmlcomplete, vim-go, etc...
		Note: It is Python3 regexp.
>
		let g:deoplete#omni#input_patterns = {}
		let g:deoplete#omni#input_patterns.ruby =
		\ ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::']
		let g:deoplete#omni#input_patterns.java = '[^. *\t]\.\w*'
<
		Default value: in g:deoplete#omni#_input_patterns
```

I have not much time to explain them to you.
