### ISSUE TITLE
Deoplete not working with tab indention after update

### ISSUE THREAD

**Issue by ranranking** [Shougo/deoplete.nvim#177]
My vimrc is:

      if has('vim_starting')
        set runtimepath+=~/.vim/bundle/neobundle.vim/
      endif

      call neobundle#begin(expand('~/.vim/bundle/'))
      NeoBundleFetch 'Shougo/neobundle.vim'
      NeoBundle 'Shougo/deoplete.nvim'

      call neobundle#end()

	
      filetype plugin indent on
      let pluginsExist=1
      NeoBundleCheck

      if pluginsExist

	    let g:deoplete#enable_at_startup=1
	    let g:deoplete#max_list=6
	    inoremap <expr><tab>
		  \ pumvisible() ?
		  \ deoplete#mappings#close_popup() : "\<tab>"
            let g:deoplete#enable_smart_case=1

      endif

If there are 8 or more blank spaces before one line, or just a "tab" , when I hit "O" or "o" on the line, deoplete would not be called no matter what I type in those new lines with 8 spaces indention. When the indention is less than 8 blank spaces, everything works fine. But if I hit a tab, not matter how large the tab is, usually it is 2 spaces, the problem still exists.

**Comment by Shougo** [comment]
> If there are 8 or more blank spaces before one line, or just a "tab" , when I hit "O" or "o" on the line, deoplete would not be called no matter what I type in those new lines with 8 spaces indention. >When the indention is less than 8 blank spaces, everything works fine. But if I hit a tab, not matter how large the tab is, usually it is 2 spaces, the problem still exists.

Please upload the sample file.
I don't want to analyze your long descriptions to reproduce the problem.

> Deoplete not working with tab indention after update

OK.  Please use `git bisect` to detect the bad commit.

**Comment by ranranking** [comment]
[vimrc.txt](https://github.com/Shougo/deoplete.nvim/files/133225/vimrc.txt)

Just use this file, you will see the deoplete setting up section has deep level indention. try make new lines from this section and see whether you can call the plugin.

 Type "neo" would be the easiest way. Normally, there should be deoplete showing NeoBundle. But if you are in the deep indention section, you would not see it.

**Comment by ranranking** [comment]
Thank you!
