### ISSUE TITLE
Provide a DeopleteDisable command

### ISSUE THREAD

**Issue by pwntester** [Shougo/deoplete.nvim#178]
Hi, 

I would like to disable Deoplete for very large buffers, and I thought doing something like:

autocmd BufEnter *.* if getfsize(@%) < 1000000 | :DeopleteEnable | else :DeopleteDisable | endif

Can you please provide a DeopleteDisable command?

Thanks!
A

**Comment by Shougo** [comment]
No.
`:help g:deoplete#disable_auto_complete`
