### ISSUE TITLE
How can I enable filename completion?

### ISSUE THREAD

**Issue by xHN35RQ** [Shougo/deoplete.nvim#18]
Can deoplete pull in file-name completions yet?

Good work on this plugin!! It's already much faster than neocomplete. :+1:

**Comment by xHN35RQ** [comment]
never mind, i'm a silly. I see you're working on it. Thanks!

**Comment by Shougo** [comment]
The pull request is available.

https://github.com/Shougo/deoplete.nvim/pull/11

But it is not merge time.

**Comment by xHN35RQ** [comment]
Awesome. I'm happy to wait for it. Thanks!
