### ISSUE TITLE
99.5% CPU usage and flicker popup

### ISSUE THREAD

**Issue by carlitux** [Shougo/deoplete.nvim#180]
# Problems summary
When starts collecting data for autocomplete starts one or more forks, and autocomplete pop up start to flicker. This is happening when many files are used.

When CPU is high the pop up flicker, but when fork uses less CPU or stops flicker disappear...

## Expected
Popup should not flicker, stop using a lot of CPU.

## Environment Information

 * OS: OSx Captain
 * Neovim version: NVIM v0.1.3-138-g00347ec  Build type: Dev
 * Project type: Javascript/node/ternjs

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
au FileType javascript,jsx,javascript.jsx setl omnifunc=tern#Complete
```

## The reproduce ways from neovim starting (Required!)

 1. Start on directory where javascript, ternjs is used
 2. start editing
 3. wait for some seconds.

**Comment by Shougo** [comment]
It is ternjs omnifunc problem.   I cannot fix it.
Closing.

I think to create the source for tern is better.
Omni source is not asynchronous.
