### ISSUE TITLE
enable_refresh_always is incompatiple with hard wrapping

### ISSUE THREAD

**Issue by ssiegel** [Shougo/deoplete.nvim#182]
# Problems summary

As soon as the current word with active completion auto-wraps, the word is duplicated.

## Expected

The expected behavior is to just wrap without duplication.

## Environment Information
 * OS: openSUSE 13.2 (x86_64)
 * Neovim version: NVIM 0.1.2

## Provide a minimal init.vim with less than 50 lines (Required!)

    " Your minimal.vimrc
    set runtimepath+=~/path/to/deoplete.nvim/
    let g:deoplete#enable_at_startup = 1

    let g:deoplete#enable_refresh_always = 1
    set textwidth=80
    execute "normal 11iabcdef "

## The reproduce ways from neovim starting (Required!)

1. launch neovim
2. type: Aabcdef<Esc>

## Screen shot (if possible)

Expected result:

    abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef
    abcdef

Actual result:

    abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef abcdef
    abcdabcdef

(Sorry, not a screenshot, but the problem should be clear)

## Upload the log file

[log.txt](https://github.com/Shougo/deoplete.nvim/files/139006/log.txt)

**Comment by Shougo** [comment]
Fixed.

**Comment by kwinczek** [comment]
I am experiencing that issue with current HEAD (aad88d60310a5f47115063a993b6d317385b2aba).

**Comment by zchee** [comment]
@kwinczek Really?
We want more information. Could you new issue thread for this problem?
