### ISSUE TITLE
Python omnicomplete doesn't work

### ISSUE THREAD

**Issue by vshl** [Shougo/deoplete.nvim#183]
# Problems summary
I'm unable to get omnicomplete to work with deoplete for python files. I even reset my entire neovim config to see if I had messed up my init.vim. I have attached my minimal init.vim config.

## Expected
Omnicomplete suggestions should work with deoplete.

## Environment Information

 * OS: OS X 10.11.3
 * Neovim version: 0.1.2

## Provide a minimal init.vim with less than 50 lines (Required!)

[init.vim.txt](https://github.com/Shougo/deoplete.nvim/files/139314/init.vim.txt)

## The reproduce ways from neovim starting (Required!)

 1. Open python file
 2. Import a module
 3. Implement module's method

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
[log_85896.txt](https://github.com/Shougo/deoplete.nvim/files/139319/log_85896.txt)

**Comment by zchee** [comment]
@vshl Hi,

Currently, deoplete.nvim does not support Python `omnifunc`.
Try use https://github.com/zchee/deoplete-jedi instead of.

If you have another problem caused by deoplete-jedi, Please post https://github.com/zchee/deoplete-jedi/issues

Close :)
