### ISSUE TITLE
UltiSnips suggestions do not appear on empty lines

### ISSUE THREAD

**Issue by pwntester** [Shougo/deoplete.nvim#184]
# Problems summary
When using ultisnips source, suggestions are only shown when there is no text in the current line or it is just whitespaces. If there is text before the word that should trigger the snippet, the suggestion is not shown. For example, if a snippet is triggered by the word "desc"

foo bar   desc<CURSOR HERE>    ===> desc snippet suggestion is NOT shown

## Expected
if a snippet is triggered by the word "desc"

<WHITE SPACES> desc<CURSOR HERE>            ===> desc snippet suggestion is shown

## Environment Information

 * OS: OSX
 * Neovim version: Latest

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. enter some whitespaces
 2. start writing a word that should trigger a snippet competion

Thanks

**Comment by Shougo** [comment]
This is UltiSnips feature.
Please ask it in the UltiSnips issues.
