### ISSUE TITLE
Completion is giving the wrong results based on context

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#185]
# Problems summary
Using the built in typescript completion trigger, and [tsuquyomi](https://github.com/Quramy/tsuquyomi) as the omnifuc provider, 

## Environment Information

 * OS: OSX
 * Neovim version: NVIM v0.1.1-165-g074d3dc (compiled Jan  4 2016 11:59:01)

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
 set runtimepath+=~/.config/nvim/bundle/neobundle.vim/
call neobundle#begin(expand('~/.config/nvim/bundle/'))
NeoBundleFetch 'Shougo/neobundle.vim'
NeoBundle 'Quramy/tsuquyomi'
NeoBundle 'Shougo/vimproc.vim', {
      \ 'build' : {
      \     'windows' : 'tools\\update-dll-mingw',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'linux' : 'make',
      \     'unix' : 'gmake',
      \    },
      \ }
NeoBundle 'Shougo/deoplete.nvim'
call neobundle#end()
let g:deoplete#enable_at_startup = 1
set completeopt+=noselect,menu,preview
```

## The reproduce ways from neovim starting (Required!)

 1. setup a typescript project (git clone https://github.com/mhartington/deoplete-typescript-errors.git)
 2. open index.ts
 3. start to type `lodash.sum` and see the complete menu choose a wrong method.

## Screen shot (if possible)
![deoplete-typescript](https://cloud.githubusercontent.com/assets/2835826/13208486/8664a572-d8e7-11e5-8716-cbfd6c473cb4.gif)

**Comment by Shougo** [comment]
This omnifunc is not supported.

You should use typescript source.

https://github.com/mhartington/deoplete-typescript

**Comment by mhartington** [comment]
Thanks. Will work on the source more then. Though the built in input patterns would be enough. Cheers!
