### ISSUE TITLE
Problem with using plugin terryma/vim-multiple-cursors

### ISSUE THREAD

**Issue by stevelorenz** [Shougo/deoplete.nvim#186]
# Problems summary

Hallo, i have used your cool plugin some time and find it very good. But i also use the plugin vim-multiple-cursors, and when i use multiple-cursors to edit something , there are some problems because of the autocompletaiton, like time lags and if i tap dot, it will complete something wrong. so i want to turn off deocomplete when i use vim-multiple-cursors. Thank you very much for your help.

## Expected

If there is a command to toggle deoplete just like neocomplete.

## Environment Information

 * OS: Manjaro Linux x64
 * Neovim version: 0.1.2

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/162

**Comment by stevelorenz** [comment]
Thanks very much
