### ISSUE TITLE
Question: about variables in documentation

### ISSUE THREAD

**Issue by rgrinberg** [Shougo/deoplete.nvim#190]
What is the difference between

```
g:deoplete#omni#input_patterns
		This dictionary records keyword patterns to Omni completion.
		This is appointed in regular expression string or list every
		file type.
		If this pattern is not defined or empty pattern, deoplete
		does not call 'omnifunc'.
		Note: Some omnifuncs which moves the cursor is not worked.
		For example, htmlcomplete, vim-go, etc...
		Note: It is Python3 regexp.
>
		let g:deoplete#omni#input_patterns = {}
		let g:deoplete#omni#input_patterns.ruby =
		\ ['[^. *\t]\.\w*', '[a-zA-Z_]\w*::']
		let g:deoplete#omni#input_patterns.java = '[^. *\t]\.\w*'
<
		Default value: in g:deoplete#omni#_input_patterns
```

and

```
g:deoplete#omni_patterns
		This dictionary records keyword patterns to Omni completion.
		This is appointed in regular expression string or list every
		file type.
		If this pattern is not defined or empty pattern, deoplete
		does not call 'omnifunc'.
		Note: If it is a set, deoplete will call 'omnifunc'
		directly.  So almost deoplete features are disabled.
		Note: It is Vim regexp.
>
		let g:deoplete#omni_patterns = {}
		let g:deoplete#omni_patterns.java = '[^. *\t]\.\w*'
		let g:deoplete#omni_patterns.php =
		\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
<
		Default value: in g:deoplete#_omni_patterns

				*b:deoplete_omni_patterns*
```

The doc seems to be the same.

**Comment by zchee** [comment]
@rgrinberg Hi,

### `g:deoplete#omni#input_patterns`
`g:deoplete#omni#input_patterns`, The condition of the **input text** that will display popupmenu.

e.g., (This is not for `omni`, but it is the same kind of meaning)
- In Go
  - https://github.com/zchee/deoplete-go/blob/master/rplugin/python3/deoplete/sources/go.py#L28
- In Python
  - https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi.py#L22-L26
- In C and C++
  - https://github.com/zchee/deoplete-clang/blob/master/rplugin/python3/deoplete/sources/deoplete_clang.py#L26-L28

and, more realistic example in Python.

Python `input_pattern` is
```python
self.input_pattern = (r'[^. \t0-9]\.\w*$|'
                      r'^\s*@\w*$|'
                      r'^\s*from\s.+import \w*|'
                      r'^\s*from \w*|'
                      r'^\s*import \w*')
```

If you typed (` | ` is current cursor.)
```python
import |
```
, will displayed python modules.
also,
```python
from |
from *** import |
```

### `g:deoplete#omni_patterns`
`g:deoplete#omni_patterns`, The pattern of **`omnifunc`** of each language.
e.g.,
- In Ruby
  - https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/init.vim#L169
- In lua
  - https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/init.vim#L172

You seem to have written a `ocaml`, but I did not find sample of `ocaml` omni pattern...
Sorry.

===

BTW, I not good at English :(
If you do not yet understand, please feel free to new comment.

**Comment by Shougo** [comment]
`g:deoplete#omni#input_patterns`

It is called by omni source.
It is faster and integrated to deoplete.
But it does not support some of omnifunc.
It is Python3 regex.

`g:deoplete#omni_patterns`
It called by Vim.
Full compatibility.  But you cannot deoplete features.
It is provided for old omnifunc compatibility.
You should not use this feature if you can avoid.

**Comment by rgrinberg** [comment]
thanks @Shougo and @zchee, the combination of your answers helps me understand
