### ISSUE TITLE
max_list seems to cause matches to be discarded

### ISSUE THREAD

**Issue by DarkDefender** [Shougo/deoplete.nvim#191]
# Problems summary
I noticed a problem when a deopletes gets a lot of matches. It seems like it keeps a cache of the previous matches but discards all the matches that doesn't fit with max_list.

This leads to some problems when there is a lot of matches. And it gives the illusion that deoplete (or the source) didn't generate or miss some matches

## Expected

Limit the completion window to the max_list number of entries but keep all the results that were discared and fill up the completion list with those when there is room.

## Environment Information

 * OS: Gentoo Linux 
 * Neovim version: NVIM v0.1.3-239-gbb56564

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#max_list = 10
```

## The reproduce ways from neovim starting (Required!)

 1. Create an empty directory:
`cd /tmp/ && mkdir test && cd test`
 2. Create a bunch of similar named files:
`touch aa  ab  ac  ad  ae  af  ag  ah  ai  aj  aja  ak  al  am  an  ao  ap  aq  ar`
 3. Start vim, go to insert mode and type `./` and wait for results to show up.
 4. Now continue and type `aj`. Notice that `aja` is missing for the result window.

In this example I would expect deoplete to show the `aja` file but it doesn't. This might not be a problem in this case. But when working with some larger code bases I've been fooled into thinking that some functions doesn't exist because deoplete discarded those when they did not fit with max_list.

I know that I could always set max_list to 0 but I think that it would be better to properly solve this problem. I thought that my sources were bugged before because I ran into this problem with the default 100 max_list value in larger python/c++ projects.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
But your behavior seems fix the config.

`let g:deoplete#enable_auto_refresh = 1`

**Comment by DarkDefender** [comment]
Yupp, that solved it!
