### ISSUE TITLE
File path autocomplete seems broken in some situation

### ISSUE THREAD

**Issue by iamcco** [Shougo/deoplete.nvim#192]
# Problems summary

File path autocomplete seems broken in some situation

## Expected

when i type `~/` it should have the file path autocomplete menu

## Environment Information

 * OS: Ubuntu15.10
 * Neovim version: NVIM 0.1.3-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

minimal init.vim
```vim
" vim-plug {
    call plug#begin('~/dotfiles/nvim/plugged')

    " deoplete and sources about {
        Plug 'Shougo/deoplete.nvim'
    " }
    call plug#end()

" }


" deoplete.nvim {
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#max_list = 15
    inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
    function! s:my_cr_function()
        return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
    endfunction
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
" }

```

## The reproduce ways from neovim starting (Required!)

test.vim file
```
let obj = [{'w': '~/workspaces/common/'}, {'b': '~/workspaces/common'}, {'n': '~/$1'}]
```
my home directory has the `~/workspaces/common/....` directories

when edit the test.vim file cursor at the $1 position doesn't have the autocomplete menu for the file path. And the `<c-x><c-f>` works fine.

## Generate a logfile if appropriate

None

## Screen shot (if possible)

None

## Upload the log file

None

**Comment by Shougo** [comment]
Reproduced.

**Comment by Shougo** [comment]
Fixed.
