### ISSUE TITLE
It is thread safe? It is cached?

### ISSUE THREAD

**Issue by carlitux** [Shougo/deoplete.nvim#193]
# Problems summary
https://github.com/carlitux/deoplete-ternjs/issues/2
When ternjs tries to autocomplete some times it is slow and timeout is reached (I am assuming this) or server still bootstraping plugins like (browser, chai, es6, es7) returns empty then when user still editing returns the data but autocomplete is not showing the results.

## Expected
Autocomplete on editions if first attempt wasn't.

## Environment Information

 * OS: OSX
 * Neovim version: 
NVIM v0.1.3-269-g9c4b34b
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-pr
otector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160228-3796-1bwxdi5/build/config -I/tmp/neovim20160228-3796-1bwxdi5/src -I/tmp/neovim20160228
-3796-1bwxdi5/deps-build/usr/include -I/tmp/neovim20160228-3796-1bwxdi5/deps-build/usr/include -I/tmp/neovim20160228-3796-1bwxdi5/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160228-3796-1bwxdi
5/deps-build/usr/include -I/tmp/neovim20160228-3796-1bwxdi5/deps-build/usr/include -I/tmp/neovim20160228-3796-1bwxdi5/deps-build/usr/include -I/tmp/neovim20160228-3796-1bwxdi5/deps-build/usr/includ
e -I/usr/local/opt/gettext/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160228-3796-1bwxdi
5/build/src/nvim/auto -I/tmp/neovim20160228-3796-1bwxdi5/build/include
Compiled by carlitux@lcruzc

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

## Provide a minimal init.vim with less than 50 lines (Required!)
https://github.com/carlitux/deoplete-ternjs/tree/master/tests

## The reproduce ways from neovim starting (Required!)
https://github.com/carlitux/deoplete-ternjs/issues/2

* You can edit the file as quick as you want.
* You can wait for some seconds
* see :messages to see the data that is returned by source.

**Comment by Shougo** [comment]
Fixed the deoplete problem.
