### ISSUE TITLE
How to move and select suggested autocompletion?

### ISSUE THREAD

**Issue by malteneuss** [Shougo/deoplete.nvim#194]
I cannot walk up or down the list of autocompletions
and  i cannot select any specific autocompletion to be inserted.
I believe that some key mappings are missing.
Could you maybe add an example to this project's front page on how to map deoplete actions to its default insert mode keys.

Btw, i have the initialization setting in my init.vim
`let g:deoplete#enable_at_startup = 1`
and i get a list of suggested autocompletions.

**Comment by iamcco** [comment]
take this

```
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
    return (pumvisible() ? "\<C-y>" : "" ) . "\<CR>"
endfunction
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

```
