### ISSUE TITLE
Working PHP setup?

### ISSUE THREAD

**Issue by herrbischoff** [Shougo/deoplete.nvim#199]
As the documentation is not very clear on this: how would I achieve this? Ideally I'm looking for a step-by-step explanation of what's going on and why. I can't seem to figure this out which I find baffling.

Setting `let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'`, as shown in the documentation, leads to an endless cycle of opening and closing the completion overlay. Setting just `  autocmd FileType php setlocal ts=4 sts=4 sw=4 expandtab omnifunc=phpcomplete#CompletePHP` does absolutely nothing and completes local buffer occurrences only.

How do I get this working? JavaScript completion also does not seem to work, although I set `autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS`.

Thanks for any insight into this.

Mac OS X 10.11.3
NeoVim 0.1.3

**Comment by Shougo** [comment]
#173 

You should use phpcompleted-extended plugin.
