### ISSUE TITLE
Does not work when setting start_length = 1

### ISSUE THREAD

**Issue by HerringtonDarkholme** [Shougo/deoplete.nvim#20]
OS: both linux ubuntu and mac osx
NVIM version: both 201506160136 and latest

Minimal vimrc

```
set rtp+=~/.vim/bundle/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 1
filetype plugin indent on
```

nvim python log: https://gist.github.com/HerringtonDarkholme/4bbdc9e163a5b75d7e77

When I set start length to 2, it works.

**Comment by HerringtonDarkholme** [comment]
https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/deoplete.py#L115

oh... because Python will give a string of length 1 in `cont['input'][-1:]`, complete position of -1 will leak into results when one source does not have candidate.

**Comment by Shougo** [comment]
Fixed.
