### ISSUE TITLE
list of deoplete source provides

### ISSUE THREAD

**Issue by tex** [Shougo/deoplete.nvim#200]
It would be nice to have a list of deoplete source provider in this project's wiki...

**Comment by Shougo** [comment]
I don't want to do it.
But you can create it.

https://github.com/Shougo/deoplete.nvim/wiki

**Comment by tweekmonster** [comment]
I went ahead and created a wiki page for souces: https://github.com/Shougo/deoplete.nvim/wiki/Completion-Sources

**Comment by Shougo** [comment]
Thanks
