### ISSUE TITLE
Callback with manual completion / invoke sendkeys

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#201]
I would like to have a mapping for `<Tab>` that would invoke deoplete, and then
send `<C-n>` / `<C-p>` after the completion popup menu shows up to select an entry.

I could imagine having some optional argument for `deoplete#mappings#manual_complete()`, which would be a dict with options to be added to the context.

This could be a Funcref or arguments that should be passed to `sendkeys()` after the popup menu is displayed.

But I am not sure if the context is the right thing for this after all?!

    function! _My_deoplete_Tab()
      if pumvisible()
        return "\<C-n>"
      endif
      call deoplete#mappings#manual_complete([], "\<C-n>")
      return ''
    endfun
    inoremap <silent><expr> <Tab> _My_deoplete_Tab()

This can be achieved (partly) by using `noinsert` in `'completeopt'` in this context, but it also needs https://github.com/Shougo/deoplete.nvim/pull/202 to handle this better.

**Comment by blueyed** [comment]
Maybe there could just be a "use this &completeopt" during completion argument `deoplete#mappings#manual_complete`?! (or another wrapper/helper)

**Comment by blueyed** [comment]
..of course the main issue would still be to allow for both "noinsert" and "noselect" to be not set.

**Comment by blueyed** [comment]
fun! _My_deoplete_tab()
      if pumvisible()
        return "\<C-n>"
      endif
      let pos = getcurpos()
      let c = getline(pos[1])[pos[2]-2]
      if c =~ '\k'
        augroup my_deoplete_tab_restore
          au!
          au InsertLeave <buffer> let &completeopt = b:my_orig_completeopt
        augroup END
        let b:my_orig_completeopt = &completeopt
        set completeopt+=noinsert
  
        return deoplete#mappings#manual_complete()
      endif
      return "\<Tab>"
    endfun
    inoremap <silent><expr> <Tab> _My_deoplete_tab()

**Comment by Shougo** [comment]
#202 is merged.

It is too complex and useless.
I have rejected the feature.

**Comment by blueyed** [comment]
I agree, thanks!
