### ISSUE TITLE
Add option for delayed auto-completion

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#204]
Firing events on every keypress via `TextChangedI` is very performance intense, and I would rather like to have automatic completion with a small delay (e.g. 500ms).

In jedi-vim I've added the following, which uses a hack through CursorHoldI.
(There might be a better mechanism for Neovim (?), but the idea stays the same.)

    if g:jedi#show_call_signatures_delay > 0
        autocmd InsertEnter <buffer> let b:_jedi_orig_updatetime = &updatetime
                    \ | let &updatetime = g:jedi#show_call_signatures_delay
        autocmd InsertLeave <buffer> if exists('b:_jedi_orig_updatetime')
                    \ |   let &updatetime = b:_jedi_orig_updatetime
                    \ |   unlet b:_jedi_orig_updatetime
                    \ | endif
        autocmd CursorHoldI <buffer> call jedi#show_call_signatures()
    else
        autocmd CursorMovedI <buffer> call jedi#show_call_signatures()
    endif

What do you think about it?

**Comment by MichaelMackus** [comment]
:+1: anything to improve the autocompletion performance. I notice when typing text in neovim with deoplete autocomplete enabled, long text strings take very long to appear into the buffer.

**Comment by blueyed** [comment]
@Shougo 
It would be great to have your input before I start hacking on it.

**Comment by blueyed** [comment]
@MichaelMackus 
You could give #210 a try.

**Comment by MichaelMackus** [comment]
Seems to work nicely for me, thanks @blueyed ! One thing that would make the PR perfect for me is for the "deoplete_omni_patterns" to automatically popup the omnifunc automatically (instead of waiting for the delay) when the pattern is matched, but not a big deal at all.

Hopefully we can get this merged into master because it at least makes deoplete's performance bearable.

**Comment by blueyed** [comment]
> "deoplete_omni_patterns" to automatically popup the omnifunc automatically

Good point!

**Comment by blueyed** [comment]
@MichaelMackus 
Another attempt: #212.

**Comment by Shougo** [comment]
I have implemented the feature.
