### ISSUE TITLE
Deoplete not using omnifunc properly (with tern for vim)

### ISSUE THREAD

**Issue by rivertam** [Shougo/deoplete.nvim#205]
# Problems summary
When I use `<C-x><C-o>`, I get tern-powered output.
When I get the deoplete popup, I get very generic output

## Expected
I'm expecting to get the same popup with `<C-x><C-o>` as with deoplete.

## Environment Information

 * OS: OS X El Capitan
 * Neovim version: 0.1.1

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
filetype plugin on
syntax on
call plug#begin('~/.config/nvim/plugged')
Plug 'ternjs/tern_for_vim', { 'do': 'npm install' }
Plug 'Shougo/deoplete.nvim'
call plug#end()

inoremap <silent><expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 1
let g:deoplete#omni#input_patterns = {}

let g:tern_show_argument_hints = 'on_hold'
let g:tern_show_signature_in_pum = 1

autocmd FileType javascript setlocal omnifunc=tern#Complete
```

There's a lot of other stuff in my config file, but I believe this is all there is that's relevant to tern, omnifunc, and deoplete.

## The reproduce ways from neovim starting (Required!)

 1. Open a javascript file (`something.js`)
 2. Use `<C-x><C-o>` to get auto-completion; be happy
 3. Use deoplete to automatically show auto-completion; be sad :cry: 

## Screen shot (if possible)
Screen gif instead

![happyjs](https://cloud.githubusercontent.com/assets/4165105/13616386/c4c5921a-e547-11e5-9049-ef640cfccea5.gif)

(the second part, where it gives me good autocompletion, is where I used `<C-x><C-o>`)

I recognize that I'm probably doing something wrong, but I'm not sure what. Can anyone help me out? Thanks!

**Comment by rivertam** [comment]
Apparently my issue was that I was using `g:tern_show_argument_hints = 'on_hold'`. When I took this away, it started working. (Tern supposedly shows results after holding for a little while, but I haven't been able to get that to work properly, but that's a Tern issue obviously)

**Comment by simonsmith** [comment]
I'm having this exact issue but I haven't got `g:tern_show_argument_hints = 'on_hold'` set anywhere

**Comment by rivertam** [comment]
Is there anything else in the config that I posted that you don't have?

**Comment by simonsmith** [comment]
Tried using your exact minimal config and I still have the issue. Using latest neovim too.

**Comment by Shougo** [comment]
You should use deoplete-tern instead of tern_for_vim.

https://github.com/carlitux/deoplete-ternjs

**Comment by rivertam** [comment]
@Shougo Thanks! Wouldn't have known. Googling "tern with deoplete" gives a tutorial on how to do what I've basically done.

**Comment by simonsmith** [comment]
@rivertam If it helps, I found that deoplete-ternjs depended on a `tern-project` in the home directory, as opposed to `tern-config` in the Tern documentation. I like to keep a global config for all files and this tripped me up as `tern-project` is supposed to be project level.

**Comment by rivertam** [comment]
Good to note. I have yet to set up a config for tern, as I'm a pretty novice user, but thanks for letting me know. Probably would have gotten confused ;)
