### ISSUE TITLE
autocompletion automatically inserts (wrong) text

### ISSUE THREAD

**Issue by lewicki-pk** [Shougo/deoplete.nvim#206]
# Problems summary
When I'm writing my C++ code autocompletion automatically inserts first value from the list.

## Expected
I would like to just see the autocompletion list and disable option responsible for inserting actual characters from autocompletion menu.

## Environment Information

 * OS: Ubuntu 15.10
 * Neovim version: NVIM 0.1.3-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.nvim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'Shougo/deoplete.nvim'
Plug 'zchee/deoplete-clang'
Plug 'Shougo/neoinclude.vim'
Plug 'benekastah/neomake'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'majutsushi/tagbar'
Plug 'dantler/vim-alternate'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'szw/vim-tags'

call plug#end()

let g:deoplete#enable_at_startup = 1

set completeopt-=preview

let g:deoplete#sources#clang#libclang_path = '/usr/lib/llvm-3.6/lib/libclang.so.1'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
let g:deoplete#sources#clang#std#c = 'c11'
let g:deoplete#sources#clang#std#cpp = 'c++1z'
let g:deoplete#sources#clang#sort_algo = 'priority'

```

## The reproduce ways from neovim starting (Required!)

Currently I cannot think of a simple way to reproduce this. I came across this during following tutorial for cppCMS library (but I hope it's some minor issue or option that I simply don't know).

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
https://www.youtube.com/watch?v=AaHg1IZ4890&feature=youtu.be

## Upload the log file
[log.zip](https://github.com/Shougo/deoplete.nvim/files/165173/log.zip)

**Comment by zchee** [comment]
@lewicki-pk Hi :)
This problem seem to deoplete-clang isuue.
Could you re-post https://github.com/zchee/deoplete-clang/issues?

**Comment by lewicki-pk** [comment]
Hi,
Thanks for quick response.
I have reposted it. It's now in your repo @zchee :-)
https://github.com/zchee/deoplete-clang/issues/12

I'm closing it then..

**Comment by Shougo** [comment]
Reopened.

1. Please update your deoplete to the latest version.
Please upload your deoplete revision number.

2. Please use the init.vim without vim-plug.

```vim
set rtp+=~/.nvim/plugged/deoplete.nvim
set completeopt=menuone,longest

let g:deoplete#enable_at_startup = 1
```

3. Please upload the reproduce ways from neovim starting.

If you use the latest deoplete, it seems conflicts with your config or your installed plugins.
So, your information is important.

**Comment by lewicki-pk** [comment]
I have retried once more with just:
```vim
call plug#begin('~/.nvim/plugged')
Plug 'Shougo/deoplete.nvim'
call plug#end():

" set rtp+=~/.nvim/plugged/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```
I cannot reproduce the issue with `set rtp+=~/.nvim/plugged/deoplete.nvim` instead of vim-plug.

I was able to reproduce it with such a code:
```
#include "SomePage.h"

#include <cgicc/HTTPHTMLHeader.h>
#include <cgicc/Cgicc.h>
#include <iostream>

#include <fstream>
#include <string>
#include <memory>

SomePage::SomePage()
{
}

void SomePage::run()
{
}

void SomePage::appendWithTimestamp(std::string& appendString)
{
    std::string timestampPath = "/some/file";
    std::ifstream inputStream(timestampPath.c_str(), std::ios::in | std::ios::binary);
    if (inputStream) {
        std::string fileContent;
        inputStream.seekg(0, std::ios::end);
        fileContent.resize(inputStream.tellg());
        inputStream.seekg(0, std::ios::beg);
        inputStream.read(&fileContent[0], fileContent.size());
        inputStream.close();

        appendString.append(fileContent);
    } else {
        appendString.append("Unable to read file content");
    }
}
```

and then by moving to line 34 and pressing:
`ostd::fi` which is automatically completed to std::file and then if I want to remove it (with backspace) it automatically and immediately inserts what I'm removing.

Any comment on closing the issue?

Do you suggest it's vim-plug issue now?

**Comment by Shougo** [comment]
Please test it.

```vim
set rtp+=~/.nvim/plugged/deoplete.nvim
set completeopt=menuone,longest
filetype plugin indent on

let g:deoplete#enable_at_startup = 1
```

And please check your 'omnifunc' value in the buffer.

**Comment by Shougo** [comment]
It seems omnifunc conflicts.
Please update deoplete to latest version.

**Comment by lewicki-pk** [comment]
Thank you @Shougo for this hint with omnifunc.
You were right and this was not fault of neither deoplete, nor deoplete-clang.
I had forgot to remove file "clang.vim" from my plugins directory.
I found it just now by examining `:verbose set omnifunc?`

Now - once I have removed this file- everything works perfectly.
