### ISSUE TITLE
Provide API to access current keyword patterns

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#207]
It would be nice if the code from https://github.com/Shougo/deoplete.nvim/blob/e5313e5e4ab26ee66447abfbe798c8b8c407d72c/autoload/deoplete/init.vim#L214-L224 would be available through a separate function in Vim:

    let keyword_patterns = join(deoplete#util#convert2list(
          \   deoplete#util#get_buffer_config(
          \   filetype, 'b:deoplete_keyword_patterns',
          \   'g:deoplete#keyword_patterns',
          \   'g:deoplete#_keyword_patterns')), '|')
  
    " Convert keyword pattern.
    let pattern = deoplete#util#vimoption2python(
          \ &l:iskeyword . (&l:lisp ? ',-' : ''))
    let keyword_patterns = substitute(keyword_patterns,
          \ '\\k', '\=pattern', 'g')

This would be useful to have in a custom Tab mapping.

**Comment by Shougo** [comment]
> This would be useful to have in a custom Tab mapping.

I don't think so.  Please describe it more clearly.

**Comment by Shougo** [comment]
No response.
