### ISSUE TITLE
What is eskk (used for)?

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#209]
Probably https://github.com/tyru/eskk.vim?!

it was added in 0f005f999cd7d536dbad6e146d1098f67d7947b4, and seems to be the reason for a loop that mostly does nothing?! (when eskk is not installed)

Code: https://github.com/Shougo/deoplete.nvim/blob/e5313e5e4ab26ee66447abfbe798c8b8c407d72c/autoload/deoplete/handlers.vim#L54-L60

Could it be moved into a separate source instead, or removed altogether?

After all there should be documentation about it (at least in the code)

**Comment by Shougo** [comment]
> Probably https://github.com/tyru/eskk.vim?!

Yes.

> Could it be moved into a separate source instead, or removed altogether?

OK.  It should be separated.  I will do it.  Please wait.

**Comment by Shougo** [comment]
Removed the code.
