### ISSUE TITLE
File path completion and auto-suggest not working with Dein.vim

### ISSUE THREAD

**Issue by theamazingfedex** [Shougo/deoplete.nvim#214]
# Problems summary
After typing at least two characters, the deoplete suggestion box does not show up.
Also, if I type `../`, nothing is suggested, and if I `<C-x><C-o>` it doesn't even show files as a possible completion.

## Expected
The suggestion box should pop up automatically as I am typing, and should also include file path completions.

## Environment Information

 * OS:  *OSX 10.11.3*
 * Neovim version: *0.1.2*

## Provide a minimal init.vim with less than 50 lines (Required!)
```vim
" My deoplete_minimal.vimrc
set runtimepath^=~/.cache/dein/repos/github.com/Shougo/dein.vim " path to dein.vim

call dein#begin(expand('~/.cache/dein')) " plugins root path
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/vimproc.vim', {
      \ 'build': {
      \     'windows': 'tools\\update-dll-mingw',
      \     'cygwin': 'make -f make_cygwin.mak',
      \     'mac': 'make -f make_mac.mak',
      \     'linux': 'make',
      \     'unix': 'gmake',
      \    },
      \ })

call dein#add( 'SirVer/ultisnips' )
call dein#add( 'ervandew/supertab' )
call dein#add( 'Shougo/deoplete.nvim' )
call dein#add( 'ternjs/tern_for_vim', { 'build': 'npm install' })
call dein#add( 'carlitux/deoplete-ternjs', { 'depends': ['deoplete.nvim', 'tern_for_vim'] } )

call dein#end()

if dein#check_install()
  call dein#install()
endif

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim

let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_at_startup = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#data_directory = '~/.cache/deoplete'

echom "Loaded deoplete_minimal.vimrc"
```

## The reproduce ways from neovim starting (Required!)

1. `nvim -u deoplete_minimal.vimrc`
2. Change to `Insert` mode
3. Start typing
4. Notice deoplete does not open
5. Try to use deoplete file path completion
 1. Type `../` as if to try file completion from the parent directory 
 2. Notice deoplete does not open
 3. Press `<C-x><C-o>`
 4. Notice omnicomplete does not have any file references

**Comment by Shougo** [comment]
It seems not deoplete problem.
Please create minimal init.vim without dein.vim like this.

```vim
set rtp+=~/work/deoplete.nvim/

let g:deoplete#enable_at_startup = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#enable_smart_case = 1
```

This is minimal init.vim.  I cannot reproduce your problem.

**Comment by theamazingfedex** [comment]
I will try that when I am on. Y computer, but if it's not deoplete problem, would it possibly be dein.vim problem?

**Comment by Shougo** [comment]
I have not ESP skills.  Please provide more detailed information.
I cannot decide it.

**Comment by Shougo** [comment]
No repsonse.

**Comment by theamazingfedex** [comment]
I decided to go back to NeoBundle until Dein is more stable.

**Comment by Shougo** [comment]
Hm.  Dein.vim is not stable.
It is active development now.  You can see the commit activity.

**Comment by wsdjeg** [comment]
@theamazingfedex what are you talk about?deoplete's filepath source or dein?I am using this two plugins,and I cannot reproduce you issue.everything works well for me.

**Comment by wsdjeg** [comment]
@Shougo 
deoplete can  not complete after `=~/` or `=./` or `=../` or `=/`.but can complete afte `= ~/` or etc.we need add a space between `=` and `path`
for example when I type `set rtp=~/` no completion
but neocomplete works well

**Comment by Shougo** [comment]
@wsdjeg It is feature.  It seems `isfname` contains `=`.
You should remove it.

```vim
set isfname-==
```

**Comment by wsdjeg** [comment]
I have check neocomplete in vim and deoplete in neovim ,`set isfname?` has same output
`isfname=@,48-57,/,.,-,_,+,,,#,$,%,~,=`

**Comment by wsdjeg** [comment]
OK,THANSK,I know what is going on,I will add this to my vimrc,`neocomplete do not use this feature`

**Comment by Shougo** [comment]
Yes, exactly.
