### ISSUE TITLE
Manual completion pop-up menu disappears in big vimrc

### ISSUE THREAD

**Issue by sunaku** [Shougo/deoplete.nvim#215]
# Problems summary

Completion pop-up menu disappears when invoked manually by:
* `deoplete#mappings#manual_complete()` 
* NeoVim's built-in `<C-n>` feature

Workaround: stop typing :scream: for 2+ seconds (during that time, the cursor blinks in-place) to give Deoplete enough time to think and display the completion menu.

## Expected

Completion pop-up menu should not disappear when it is invoked manually.

## Environment Information

 * OS: x86_64 GNU/Linux 4.4.5
 * Neovim version: NVIM 0.1.2

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" :
      \ deoplete#mappings#manual_complete()
```

## The reproduce ways from neovim starting (Required!)

 1. `nvim -u minimal.vimrc`
 2. `:UpdateRemotePlugins`
 3. `:q`
 4. `nvim -u minimal.vimrc`
 5. `:e README.md` # edit the deoplete readme
 6. `O` # open a new line
 7. `plu<Tab>` # type "plu" followed _quickly_ :dash: by Tab or C-n
 8.  Argh! :tired_face: I'm not able to reproduce it with _only_ 1 bundle (Deoplete) loaded... :sob: but it happens every time under [my normal vimrc](https://github.com/sunaku/.vim/tree/spacey) which uses 190 different bundles! :scream: 

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by zchee** [comment]
@sunaku Hi! Thank you for your kind assistance in tmux :)

I'm investigating this issue, please wait a little bit.

**Comment by zchee** [comment]
@sunaku This problem was deoplete.nvim bug.
But, @Shougo Has quickly solved this problem!
https://github.com/Shougo/deoplete.nvim/commit/1660138ab5c830f9bed20e7991481d0a8c28f54e

If you still does not works for manual_complete, Please post comment on this issue.

**Comment by Shougo** [comment]
@zchee This is the different issue.

**Comment by zchee** [comment]
@Shougo @sunaku
Oh, sorry :(

**Comment by Shougo** [comment]
Fixed

**Comment by sunaku** [comment]
@Shougo and @zchee thank you! :bow: It's much better now. :+1:
