### ISSUE TITLE
No sources/integration with OmniSharp

### ISSUE THREAD

**Issue by mixedCase** [Shougo/deoplete.nvim#217]
I cannot get OmniSharp to work with deoplete, and if I understand deoplete correctly, a middleware "source" plugin has to be written.

If I use <C-x><C-o> OmniSharp works just fine so I don't think much has to be done...

**Comment by Shougo** [comment]
You can create the source if you needed.
Because, the source is written by Python language.

**Comment by mixedCase** [comment]
Guess it's back to YouCompleteMe then :disappointed:

**Comment by Shougo** [comment]
It is not so difficult.

https://github.com/OmniSharp/omnisharp-vim

Omnisharp is written by Python language.

Or you can call omnifunc by `g:deoplete#omni#input_patterns`.

Note: I don't know why the users does not write the source...  It is Python language instead of Vim script.

**Comment by mixedCase** [comment]
I don't have the time to scour source code and documentation, and in fact I can't get anything useful out of the included documentation about input_patterns.

I guess I'm lazy, but if YCM offers me everything I need out of the box and deoplete doesn't and I can't easily configure it to work, I guess it's just that one plugin is for me and the other isn't. Sorry, no disrepect intended.

**Comment by Shougo** [comment]
If you really need this feature, you must work to implement it.
This is the open source theory.
I don't have the time and interest for OmniSharp and C# language.

**Comment by mixedCase** [comment]
I understand and that's okay. That's why I'm just switching to something else.

**Comment by Shougo** [comment]
I have worked for neovim to implement deoplete.
I also have worked for Vim to implement the other plugins.

**Comment by Shougo** [comment]
> I don't have the time to scour source code and documentation, and in fact I can't get anything useful out of the included documentation about input_patterns.

You can update it!

**Comment by Shougo** [comment]
I think YCM is not easy to configure :-)

**Comment by mixedCase** [comment]
Well, I did end up giving deoplete another chance and tried to write a source to use OmniSharp, which ended up with this: https://gist.github.com/mixedCase/1a0cf8490d66725724d2

Doesn't work. Any ideas?

**Comment by Shougo** [comment]
```vim
return self.vim.call('OmniSharp#Complete', 0, 0)
```

should be

```vim
return self.vim.call('OmniSharp#Complete', 0, context['complete_str'])
```

**Comment by mixedCase** [comment]
Well, that worked. Guess I am giving deoplete another go after all! Thanks.

**Comment by Shougo** [comment]
:+1:

**Comment by Swoorup** [comment]
@mixedCase can you share what you've done?

**Comment by mixedCase** [comment]
@Swoorup https://gitlab.com/mixedCase/deoplete-omnisharp

I'm no longer using deoplete so it is completely unsupported.

**Comment by Swoorup** [comment]
@mixedCase What are you using?

**Comment by mixedCase** [comment]
YouCompleteMe. It's the only async solution that isn't laggy.

**Comment by Swoorup** [comment]
@mixedCase I am trying to use Neocomplete instead

**Comment by mixedCase** [comment]
@Swoorup Neovim doesn't support Lua plugins.

**Comment by Shougo** [comment]
> YouCompleteMe. It's the only async solution that isn't laggy.

deoplete is not laggy.
`deoplete-omnisharp` is laggy.
Because it calls Vim script function.
It blocks your neovim.
YouCompleteMe is not laggy.
Because, it calls omnisharp server directly.

**Comment by autozimu** [comment]
For anyone directed by search engine, this one seems working perfectly https://github.com/Robzz/deoplete-omnisharp/

**Comment by Shougo** [comment]
OK.  It seems better.
