### ISSUE TITLE
`:UpdateRemotePlugins` message keeps on poping up.

### ISSUE THREAD

**Issue by define-private-public** [Shougo/deoplete.nvim#220]
# Problems summary
When I start neovim, I get the message `[deoplete] Please execute :UpdateRemotePlugins command and restart Neovim`.  I've done this about three or four times already.  I've made sure to close all instances of neovim running before I try to do the update.

## Expected
I don't see this message after I run the update command.

## Environment Information

 * OS:
Linux laptop 4.2.0-30-generic #36-Ubuntu SMP Fri Feb 26 00:58:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 * Neovim version:
```
NVIM 0.1.3-dev
Build type: RelWithDebInfo
Compilation: /usr/bin/x86_64-linux-gnu-gcc -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/build/config -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/src -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/usr/include/luajit-2.0 -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/.deps/usr/include -I/usr/include -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/build/src/nvim/auto -I/build/neovim-ubL2KQ/neovim-0.1.2ubuntu1+git201603101534+2362+17~ubuntu15.10.1/build/include
Compiled by buildd@lgw01-22
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```
set ruler
set number
let g:deoplete#enable_at_startup = 1
syntax on
set sw=4
set expandtab
set autoindent
set tabstop=4
```

## The reproduce ways from neovim starting (Required!)

 1. I see the message within 5 seconds of startup
 2. I try running the update command
 3. It doesn't show any errors
 4. I close neovim
 5. I start back at `1.` and repeat

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/160
https://github.com/Shougo/deoplete.nvim/issues/167

Please check your  init.vim-rplugin~ file.
I think it is broken or not loaded.

**Comment by Shougo** [comment]
And deoplete is in your runtimepath?
Please upload the `:UpdateRemotePlugins` messages.

**Comment by zchee** [comment]
@define-private-public Or, If you have been set to `NVIM_PYTHON_LOG_FILE`, but does not exist root directory of this environment variable file, will occur same error.

**Comment by define-private-public** [comment]
I'll do that soon (bit busy right now).  Also after running the update command, deoplete stopped working.

**Comment by define-private-public** [comment]
I had deoplete in my runtime path.  I eventually just copied over the files directly from a .zip download of the repo and it started working again.

**Comment by Shougo** [comment]
OK.
