### ISSUE TITLE
Use Python's logging module for debugging

### ISSUE THREAD

**Issue by tweekmonster** [Shougo/deoplete.nvim#224]
I think it would be worthwhile to use Python's logging module to log to a file instead of printing logs to Vim's message history.  This would make source development much easier since the output can be monitored in a separate terminal.  It would make it unnecessary to cross the Vim boundary which seems to be a performance hit for each log message.  It would also mean that `debug()` lines don't need to be commented out.

This is what I propose:

- If debug is enabled, the output should be logged to a file called `/tmp/deoplete.log`.  The file location can be configured with a variable.
- It is the responsibility of the source module to enable or disable logging for itself using it's own Vim variables.  `Base.debug()` would check `self.logging_enabled` before emitting a message through `deoplete.util.debug()`.
- `Base.debug()` will prefix `Base.name` to each log message.
- `Base.debug()` will accept any number of arguments and keyword arguments and pass them directly to `Logger.debug()`.

Suggestions:

- The `Base` superclass should have `.debug()`, `.info()`, etc. for more granular logging.
- If `Base.error()` or `Base.exception()` is emitted, deoplete.nvim should log the message in Vim even if debug is disabled and stop using the source until Vim is restarted to keep the message log relatively clean in Vim.  This could be accomplished in the `Base` class with `self.gather_candidates = lambda x: []` so that the core doesn't need to change.

I don't mind working on a PR to change how debugging works, but I would like to get your thoughts before I got started.

**Comment by blueyed** [comment]
Sounds good to me.
