### ISSUE TITLE
Deoplete stop working after update

### ISSUE THREAD

**Issue by carlitux** [Shougo/deoplete.nvim#226]
# Problems summary
Deoplete stops working and nvim now is slow and some times freezes

## Expected
Working as before

## Environment Information

 * OS: OSX
 * Neovim version:
NVIM v0.1.3-350-gc94575f
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protecto
r-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim20160316-20548-ql3yu8/build/config -I/tmp/neovim20160316-20548-ql3yu8/src -I/tmp/neovim20160316-20548-ql3yu
8/deps-build/usr/include -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/include -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/i
nclude -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/include -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/include -I/tmp/neovim20160316-20548-ql3yu8/deps-build/usr/include -I/usr/local/opt/gette
xt/include -I/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include -I/tmp/neovim20160316-20548-ql3yu8/build/src/nvim/auto -I/tmp/n
eovim20160316-20548-ql3yu8/build/include
Compiled by carlitux@lcruzc

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim

set runtimepath+=$XDG_CONFIG_HOME/nvim/bundle/deoplete.nvim
set runtimepath+=$XDG_CONFIG_HOME/nvim/bundle/deoplete-ternjs
set runtimepath+=$XDG_CONFIG_HOME/nvim/bundle/deoplete-jedi

set completeopt-=preview

hi Pmenu    gui=NONE    guifg=#c5c8c6 guibg=#373b41
hi PmenuSel gui=reverse guifg=#c5c8c6 guibg=#373b41

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_completion_start_length = 1
let g:deoplete#enable_debug=1

filetype plugin indent on
```

## The reproduce ways from neovim starting (Required!)

 1. nvim -u init.vim test.py
 2. start an import: 'import sys'
 3. try to get it working: 'sys.'

## Upload the log file

[log_simple.txt](https://github.com/Shougo/deoplete.nvim/files/176821/log_simple.txt)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/223

Please update neovim-python, neovim-python3, neovim to the latest version.

**Comment by Shougo** [comment]
And it seems deoplete-jedi problem.
@zchee Ping.

**Comment by nhooyr** [comment]
@Shougo I disabled deoplete-jedi and still have the same problem.

**Comment by nhooyr** [comment]
Its a `carlitux/deoplete-ternjs` issue.

**Comment by carlitux** [comment]
@Shougo @nhooyr fixed... closing this
