### ISSUE TITLE
Provide functions to disable/toggle deoplete

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#227]
I would like to control the state of Deoplete, and not only the automatic
completion.  Having functions for this would make it easy to map.

It might be as simple as the following for disabling:

    function! deoplete#init#disable() abort "{{{
      augroup deoplete
        autocmd!
      augroup END
      let s:is_enabled = 0
    endfunction"}}}

**Comment by Shougo** [comment]
No.  I don't want to add the feature.
Why this is needed?  Please provide more information.

**Comment by blueyed** [comment]
> Why this is needed?

It's useful when you want to switch off deoplete completely (temporarily), which I've done often given the recent problem with Neovim closing the popup menu, which annoyed me.  Just toggling `g:deoplete#disable_auto_complete` seemed to not help completely.

I agree that it's a bug elsewhere that needs to be fixed, of course.
But it would provide a supported API for the more advanced user, instead for you to do so manually (e.g. by switching the global and/or removing the autocommands).

Feel free to close / reject it, I just wanted to bring this up at least.

**Comment by Shougo** [comment]
It is just neovim's bug. It is annoying, yes.
If you have not the other advantages, I will close it.

**Comment by smondet** [comment]
I have another use case:

- I (try to) make a function that "edits" code (modifies the text)
- sometimes, in the middle of a function execution, the cursor ends-up in a place where doeplete wants to do show me something
- doeplete fails (I don't know why, don't really care)
- my function exits before finishing its work

Disabling temporarily deoplete at the beginning of the function would solve that I think.
