### ISSUE TITLE
Feature request: Racer support

### ISSUE THREAD

**Issue by leonardinius** [Shougo/deoplete.nvim#23]
I've found out (accidentally) you are wiling to give it a try.

E.g. 
https://gitter.im/neovim/neovim?at=5592a140666fd9af6736be6d
https://gitter.im/neovim/neovim?at=5593011f98f9c0bc3da0b346

I'm highly interested in deoplete.nvim racer support. If you are still considering to try it out - I will gladly help you out with racer compilation steps et cetera... 

Feel free to close the ticket as you find it fit. Just wanted to make sure it doesn't slip your eyes. Kudos!

**Comment by Shougo** [comment]
I gave up the installation.
But, I get racer binary from SolidOak.
So, you don't have to help me.

I tested racer in neocomplete.
It works for me.

**Comment by leonardinius** [comment]
@Shougo Ok, great to hear. 

What about deoplete.nvim? Meaning - If I understand that correctly - neocomplete would not work in Neovim, vanilla vim only, right?

**Comment by Shougo** [comment]
Yes.  I will create deoplete source for racer.

**Comment by Shougo** [comment]
https://github.com/phildawes/racer/pull/298

**Comment by leonardinius** [comment]
@Shougo awesome, will give it a try. 

Great thanks and kudos!
