### ISSUE TITLE
Extremely slow input with vim-javacomplete2

### ISSUE THREAD

**Issue by motdef** [Shougo/deoplete.nvim#231]
# Problems summary
vim-javacomplete2 doesn't seem to be behaving asynchronously with deoplete. For example, after typing ```System.``` there is a ~2 second delay before additional characters are registered.

## Expected
Key presses don't have to wait for deoplete to execute before appearing on screen

## Environment Information

 * OS: OS X 10.11.3
 * Neovim version: NVIM v0.1.3-240-gb16b27a

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim' | Plug 'artur-shaik/vim-javacomplete2'
call plug#end()
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

Edit any .java file and type anything.

**Comment by tweekmonster** [comment]
You can try setting `g:deoplete#auto_complete_delay` to 100.  Deoplete's asynchronicity only refers to it's ability to not block Vim while it gathers completions.  What's most likely happening is that each key press is triggering a completion before results are returned, so there's a backlog of completions for your previous key presses that need to finish before you see the popup menu.

**Comment by zchee** [comment]
@motdef It seems this problem not related `deoplete.nvim`.

`deoplete.nvim` call `vim-javacomplete2` asynchronous. but `vim-javacomplete2` was blocked your neovim.
As a result, ~2 delays will occur.

@tweekmonster Thanks help advice.
It may improve somewhat in this setting.

This problem does not solve unless improving `vim-javacomplete2`.
Sorry, I'll close.
