### ISSUE TITLE
completion sets modified

### ISSUE THREAD

**Issue by nhooyr** [Shougo/deoplete.nvim#232]
# Problems summary
Completing in a buffer results in it becoming modified even if no completion was selected.

## Expected
It should not become modified because of completion. `<c-x><c-o>` does not set modified unless you select a completion.

## Environment Information

 * OS: OSX 10.11.3
 * Neovim version:
```
NVIM v0.1.3-355-g6b22a74
Build type: Dev
Compilation: /usr/local/Library/ENV/4.3/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2
-g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protect
or-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim2016
0317-11722-xxockh/build/config -I/tmp/neovim20160317-11722-xxockh/src -I/tmp/neovim20160317-11722-xxo
ckh/deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/tmp/neovim201
60317-11722-xxockh/deps-build/usr/include/luajit-2.0 -I/tmp/neovim20160317-11722-xxockh/deps-build/us
r/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/tmp/neovim20160317-11722-xxock
h/deps-build/usr/include -I/tmp/neovim20160317-11722-xxockh/deps-build/usr/include -I/usr/local/opt/g
ettext/include -I/usr/include -I/usr/include -I/tmp/neovim20160317-11722-xxockh/build/src/nvim/auto -
I/tmp/neovim20160317-11722-xxockh/build/include
Compiled by nhooyr@aubble

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/HEAD/share/nvim"
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
inoremap <silent><expr><Tab> pumvisible() ? "\<c-n>"
      \ : (<SID>is_whitespace() ? "\<Tab>" : deoplete#mappings#manual_complete())
inoremap <expr><S-Tab>  pumvisible() ? "\<c-p>" : "\<c-h>"
function! s:is_whitespace()
  let l:col = col('.') - 1
  return !l:col || getline('.')[l:col - 1]  =~? '\s'
endfunction
```

## The reproduce ways from neovim starting (Required!)

 1. Enter a file
 2. Press tab to begin completion
 3. Modified is set on the buffer

**Comment by zchee** [comment]
@nhooyr I will check later!

**Comment by zchee** [comment]
@nhooyr I was reproduced.
but, type <C-p> also occur this problem.

I think not related `deoplete.nvim`. Caused by the specification of Vim and Neovim instead of.

WDYT?

**Comment by zchee** [comment]
@nhooyr and,
In `completeopt+=noinsert` case, not reproduced.
In `completeopt+=noselect` case, reproduced.

I can not understand what it the result is changed :(

**Comment by nhooyr** [comment]
@zchee really weird. 

For me, the moment I invoke deoplete, the file gets modified. However for `<c-p>` and the like, if I press `<c-e>` without selecting anything, the file does not get modified.

**Comment by nhooyr** [comment]
Video: https://asciinema.org/a/blmqdbv8qjdr6z3divugbsrjk

First I use `<c-n>` and then deoplete.

**Comment by Shougo** [comment]
This is not deoplete problem.
It is weird behavior though.

I have not much time to create the patch for Vim/neovim.
