### ISSUE TITLE
[Feature request] Get word suggestions when using "set spell"

### ISSUE THREAD

**Issue by DarkDefender** [Shougo/deoplete.nvim#235]
I'm writing my emails and latex documents with neovim and I thought that if would be really nice if there were a source or something for deoplete so I don't have to do "z=" to get the spelling suggestions.

It seems like you can already kinda do this with ":set complete+=k", but I really miss the automatic popup feature from deoplete.

I thought that perhaps the 'dictionary' source already did this, but I have not been able to get it to work if that is the case.

**Comment by kwinczek** [comment]
Have a look at https://github.com/ujihisa/neco-look.

**Comment by DarkDefender** [comment]
@kwinczek I don't think that will work for me. While I do have "look" installed it seems like there isn't any dictionary installed by default for it. So I can't use it for word suggestions.

**Comment by Shougo** [comment]
@DarkDefender Vim's built in spellsuggestion is really slow and blocks neovim.
So deoplete cannot use it as source.  You should use neco-look.

**Comment by Shougo** [comment]
@DarkDefender If look does not work, it is your setup problem.  It is not deoplete issue.

**Comment by balta2ar** [comment]
@Shougo Could you please add https://github.com/ujihisa/neco-look to the list of recommended sources in the deoplete docs? It's very useful, I wish I could find it earlier.

**Comment by Shougo** [comment]
OK.

**Comment by codeinabox** [comment]
I stumbled upon this Deoplete source for spelling if anyone is interested https://github.com/deathlyfrantic/deoplete-spell
