### ISSUE TITLE
Limit the completion text / always show the source name

### ISSUE THREAD

**Issue by SageEx** [Shougo/deoplete.nvim#238]
# Problem summary
When the completion text is too long, the source of the completion is out of the window. The source is visible again when we increase the width of the window.

## Expected
Is there an option to truncate the long completions so that the source is visible always (maybe depending upon the current window width) ? Or a custom fixed value ?

## Environment Information

 * OS: ArchLinux
 * Neovim version:NVIM v0.1.3-363-g2e2b575

**Comment by zchee** [comment]
@SageEx Hi :)
Maybe, do you pointing to the clang? lol

Now, `deoplete.nvim` does not implements max `abbr` or `info` value settings.
but, I heard at @Shougo,  He said planned implementation for the deoplete core.
Let us wait for it.

===

I also planned max `abbr` additional implements for deoplete-clang : P
Just moment.

**Comment by SageEx** [comment]
@zchee Helllo, yes, indeed I was referring to ``deoplete-clang``. 
Shouldn't this feature be part of ``deoplete`` instead of the sources ?

**Comment by zchee** [comment]
@SageEx 
> Shouldn't this feature be part of deoplete instead of the sources ?

Yes! I said,

> He said planned implementation for the **deoplete core**.

Let us wait for it. :)

**Comment by Shougo** [comment]
Implemented.

**Comment by SageEx** [comment]
Thanks.
Is there any chance it can be set to the current window width such that it is resized on buffer width changed ?

**Comment by Shougo** [comment]
OK.  Fixed.

**Comment by SageEx** [comment]
@Shougo thanks for the commit, but it doesn't seem to work.
It is still going out of the window.

**Comment by zchee** [comment]
@SageEx Maybe, do you want this?

![screenshot 2016-03-27 13 39 02](https://cloud.githubusercontent.com/assets/6366270/14063881/1851946c-f423-11e5-8062-ebb04ee5515b.png)

**Comment by SageEx** [comment]
@zchee @Shougo  Here is what I see,
See, how the completion text does not fit into the window and as a result, the sources origin in ``[clang]`` or ``[US]`` is not shown.
![2016-03-27-10 24 01](https://cloud.githubusercontent.com/assets/7141867/14063889/1efe1c6c-f406-11e5-9eb8-4cc3ce230cb4.png)

And yes, the behaviour mentioned by @zchee  does exist.
![2016-03-27-10 27 22](https://cloud.githubusercontent.com/assets/7141867/14063898/9239b326-f406-11e5-9ddf-0e2241bc134b.png)

What I had in mind was that the source of the completion is always visible and the completion string itself is truncated (or ellipsised). Maybe when the next split is still in vim/nvim the behaviour in second screenshot is acceptable. But the behaviour in the first screenshot is still a problem.

**Comment by Shougo** [comment]
I have implemented better one.

**Comment by SageEx** [comment]
@Shougo Perfect, Thanks a lot !!!
