### ISSUE TITLE
Dependency on setuptools

### ISSUE THREAD

**Issue by arkrost** [Shougo/deoplete.nvim#239]
Hi!

Commit 7ce47a109c802ebd0030540e5ef4cc0e1fa7b1df added logger.py file. It relies on setuptools package facilities
```
import pkg_resources
```
So either installation requirements should be updated, or code should be refactored to get rid of this dependency.

**Comment by zchee** [comment]
@arkrost Thanks report :)
We will consider it dependency problem. Update requirements or refactoring.

/cc @tweekmonster

**Comment by tweekmonster** [comment]
A Python installation without setuptools?!  😱

I can submit a PR that fixes this.

**Comment by tweekmonster** [comment]
@arkrost on second thought, how did you install the neovim python package without setuptools?

**Comment by arkrost** [comment]
@tweekmonster python-neovim is distributed as a package in some linux distro. For example, in [arch](https://www.archlinux.org/packages/community/any/python-neovim). There is only make dependency on setuptools as expected.

**Comment by Shougo** [comment]
@tweekmonster Can you remove the dependency?

**Comment by tweekmonster** [comment]
@arkrost Oh okay.  Didn't know that :sweat_smile: 

@Shougo Yeah, I can make it a soft dependency.  One moment.
