### ISSUE TITLE
deoplete creates ..nvimrc-rplugin~ file in home folder

### ISSUE THREAD

**Issue by xHN35RQ** [Shougo/deoplete.nvim#24]
I guess deoplete uses Neovim's remote plugin functionality, and doing so places a `..nvimrc-rplugin~` file in my home folder. I already have a folder structure for nvim in `~/.nvim` with `~/.nvim/tmp` for temp files. How can I tell deoplete to place the `..nvimrc-rplugin~` in my Neovim working folder? Thanks.

**Comment by bfredl** [comment]
I think it is placed in the same directory as your `nvimrc`. At least, if it is `.nvim/nvimrc`, it will be placed in `.nvim/.nvimrc-rplugin~` instead.

**Comment by Shougo** [comment]
It is not deoplete problem.
It is neovim problem.
