### ISSUE TITLE
neovim host hangs on long strings with a repeating character

### ISSUE THREAD

**Issue by tweekmonster** [Shougo/deoplete.nvim#240]
# Problems summary

In a python file, going into insert mode in a long string that repeats a character will cause the neovim python host to hang at 100% CPU usage.  Deoplete will stop working after this.

## Expected

Deoplete to continue working.

## Environment Information

 * OS: Ubuntu 14.04.4 LTS
 * Neovim version: NVIM 0.1.3-dev, Python 3.4.3, neovim client 0.1.5

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
let g:python_host_prog = '/home/tallen/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/home/tallen/.pyenv/versions/neovim3/bin/python'

call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#file#enable_buffer_path = 1
let g:deoplete#auto_complete_start_length = 1

augroup vimrc_deoplete
    autocmd!
    autocmd VimEnter * call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
    autocmd VimEnter * call deoplete#custom#set('_', 'converters',
                \ ['converter_auto_paren', 'converter_remove_overlap'])
augroup END
```

## The reproduce ways from neovim starting (Required!)

I was only able to produce this issue in python, but it may happen in other filetypes.

Minimum Python file that will create the issue:
```python
"thisisalongstringthisisalongstringthisisalongstringthisisalongstringthis"
"tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt"
```

1.  Go into insert mode within the string on the second line
2.  You might need to go into insert mode closer to the right side of the string.  It sometimes doesn't happen right away.

The second line can be replaced with any repetitive character and get the same results.  The first line will not cause any issues.

## Upload the log file

[log.txt](https://github.com/Shougo/deoplete.nvim/files/190360/log.txt)

**Comment by Shougo** [comment]
Fixed.
