### ISSUE TITLE
External sources don't work

### ISSUE THREAD

**Issue by yevhen-m** [Shougo/deoplete.nvim#243]
# Problems summary
I registered deoplete-jedi and UltiSnips as external sources for deoplete.
And they do not work. I don't get any completion suggestions from them.
All dependencies are installed, vim deoplete#sources variable is set properly too.

## Environment Information

 * OS: Ubuntu 14.04
 * Neovim version:
0.1.3-dev

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_refresh_always = 1

let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer', 'UltiSnips']
let g:deoplete#sources.py = ['buffer', 'deoplete-jedi']

```

## The reproduce ways from neovim starting (Required!)
I did everything according to docs.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
The source names are wrong.

```vim
let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer', 'ultisnips']
let g:deoplete#sources.py = ['buffer', 'jedi']
```

**Comment by yevhen-m** [comment]
Thanks.
But deoplete-jedi still does not work.

**Comment by Shougo** [comment]
I get it.  `py` is the invalid filetype.

```vim
let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer', 'ultisnips']
let g:deoplete#sources.python = ['buffer', 'jedi']
```

**Comment by yevhen-m** [comment]
Doesn't work this way too.

**Comment by Shougo** [comment]
Fixed the bug.
Please update deoplete.

**Comment by yevhen-m** [comment]
Thanks a lot!
