### ISSUE TITLE
Deoplete doesn't use tern omnifunc automatically

### ISSUE THREAD

**Issue by eloytoro** [Shougo/deoplete.nvim#244]
# Problems summary
Have to use `<C-o><C-x>` to get tern completion everytime

## Expected
Tern autocompletion should be automatically on (like it used to be)

## Environment Information

 * OS: Ubuntu 15.4
 * Neovim version: 0.1

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin('~/.config/nvim/plug')
Plug 'Shougo/deoplete.nvim'
Plug 'ternjs/tern_for_vim'
call plug#end()

let g:deoplete#enable_at_startup = 1
set completeopt=menuone,noinsert,noselect

imap <silent><expr> <TAB>
            \ pumvisible() ? "\<C-n>" :
            \ "\<TAB>" :
            \ deoplete#mappings#manual_complete()

inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<C-h>"

let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_camel_case = 1
```

## The reproduce ways from neovim starting (Required!)
Open up a javascript file and try to use tern completion, hit `<C-o><C-x>` and completion will enable until finds a match

**Comment by zchee** [comment]
@eloytoro Hi,

deoplete.nvim does not support `javascript` omnifunc.
If you want it, [carlitux/deoplete-ternjs](https://github.com/carlitux/deoplete-ternjs) instead of.
