### ISSUE TITLE
omnicompletion does not use the delay variable

### ISSUE THREAD

**Issue by Jacoby6000** [Shougo/deoplete.nvim#245]
# Problems summary
When using omnifunc completion, omnifunc is called immediately, even when delay is set

## Expected
omnifunc should not be called until after the input delay

## Environment Information

 * OS: Mac OS X 10.11.4
 * Neovim version: 0.1.2

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
if &compatible
  set nocompatible
endif

call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim'
Plug 'ensime/ensime-vim'
Plug 'derekwyatt/vim-scala'
call plug#end()

autocmd BufNewFile,BufRead *.scala   set ft=scala " Set syntax highlighting for .scala files
autocmd BufNewFile,BufRead *.sc      set ft=scala " Set syntax highlighting for scala worksheet files
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.scala = '[^. *\t]\.\w*\|: [A-Z]\w*'
let g:deoplete#auto_complete_delay = 700
```

## The reproduce ways from neovim starting (Required!)

 1. open a scala file (or any other file that you have omnifunc set up for
 2. trigger omnifunc completion
 3. observe that it does not wait 700ms to run omnifunc

**Comment by zchee** [comment]
@Jacoby6000 Hi :)

It's behavior is specific of deoplete.nvim. Not a bug :(
Sorry.

**Comment by Jacoby6000** [comment]
Is there any way we can get support for an omnifunc delay? Maybe as a seperate parameter? (because omnifunc may be slow, but other completion isn't)

**Comment by zchee** [comment]
@Jacoby6000 Okay, I will ask to @Shougo, but In Japan now AM1:35.
Maybe reply comment is tomorrow.
Thanks.

**Comment by Shougo** [comment]
@Jacoby6000 Please read the deoplete documentation.
You can use `g:deoplete#omni#input_patterns` instead of `g:deoplete#omni_patterns`.
But ensime-vim may be not supported.  I don't test it.

**Comment by Jacoby6000** [comment]
`omni#input_patterns` doesn't seem to work either.  omnifunc for ensime does not move the cursor, so I can't think of why it would fail

**Comment by Shougo** [comment]
https://github.com/ensime/ensime-vim

ensime is written by Python.
ensime should create deoplete source.

**Comment by Jacoby6000** [comment]
Ensime provides hooks for omni func, and calling omnifunc directly works as expected.  So should this config work as expected?

```vimrc
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources.scala = ['buffer', 'tags', 'omni']
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.scala = ['[^. *\t0-9]\.\w*',': [A-Z]\w', '[\[\t\( ][A-Za-z]\w*']
```

**Comment by Shougo** [comment]
I will check the problem.

**Comment by Jacoby6000** [comment]
@Shougo Sorry about the false alarm. I was using an old version of ensime.

**Comment by Shougo** [comment]
OK
