### ISSUE TITLE
Navigate through suggestions is not adding them

### ISSUE THREAD

**Issue by eduardoHoefel** [Shougo/deoplete.nvim#246]
# Problems summary
Watching your gif in the README page I can see that when you navigate through complete suggestions, the code is updated with the suggestion. To me, it does not work that way. It just appears in code when I press Enter.

## Environment Information

 * OS: Arch Linux
 * Neovim version: v0.1.3-364-gae68609

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
call plug#begin('~/.vim/plugged')
	Plug 'Shougo/deoplete.nvim'
call plug#end()

filetype plugin indent on
color matrix

```

## The reproduce ways from neovim starting (Required!)

 1. start neovim
 2. write "aaaaaaaaaaaaaa"
 3. in next line, write "aaa"
 4. a window appears suggesting "aaaaaaaaaaaaaaaaaaa"
 5. press down_arrow key to select "aaaaaaaaaaaaaaaaaaa"
 6. it should update my text accordingly, but it doesn't
 7. pressing enter, the text is updated.

**Comment by zchee** [comment]
@eduardoHoefel Hi,
It problem is known. Caused by Neovim core behavior.
Not related deoplete.nvim.

I and Shougo do not know solved way. Sorry.

**Comment by Shougo** [comment]
@eduardoHoefel Please read `:help popupmenu-keys`.  It is feature.

**Comment by emilsoman** [comment]
YouCompleteMe in neovim still supports selecting and inserting text using arrow keys alone. Is there any workaround to achieve this in deoplete ? Thanks

**Comment by Shougo** [comment]
@emilsoman 

Hm....
Why don't you create mappings like this?
It is not hard.    So, I have answered to read `:help popupmenu-keys`.

```vim
inoremap <expr><Down>    pumvisible() ?   "\<C-n>"  : "\<Down>"
inoremap <expr><Up>    pumvisible() ?   "\<C-p>"  : "\<Up>"
```

**Comment by emilsoman** [comment]
@Shougo this works as expected. Thanks for the snippet!

**Comment by randre03** [comment]
Hello, I would like to be able to do the following, 
`inoremap <expr><Down>    pumvisible() ?   "\<C-j>"  : "\<Down>"`
`inoremap <expr><Up>    pumvisible() ?   "\<C-k>"  : "\<Up>"`
but when I press `<C-j>` it just inserts whatever is highlighted and jumps to the next line.

I'd also like to be able to select an entry with `<C-l>` (that's an 'L'). Any way to do this? Thanks

**Comment by Shougo** [comment]
@randre03 I don't understand.
What is the desired behavior?  We have not ESP skills.

**Comment by randre03** [comment]
When the autocomplete options show up, I would like to use `<C-j>` to move down the list of options (as opposed to `<C-n>`). I would like to use `<C-k>` to move back up the list of options (as opposed to ` <C-p>)` . To insert the selected option I would like to be able to use `<C-l>` (that is still an “L”).

Your lack of ESP is *concerning* . Perhaps you should consult a Health Care professional.

**Comment by Shougo** [comment]
> Perhaps you should consult a Health Care professional.

Hahaha, really?

> When the autocomplete options show up, I would like to use `<C-j>` to move down the list of options (as opposed to `<C-n>`). I would like to use `<C-k>` to move back up the list of options (as opposed to `<C-p>`) . To insert the selected option I would like to be able to use `<C-l>` (that is still an “L”).

It is very clealy answer. I understand.
I have known your configuration seems wrong.
But I cannot understand your desired behavior from your previous comment.
https://github.com/Shougo/deoplete.nvim/issues/246#issuecomment-343627162

The solution is here.

```vim
inoremap <expr><C-j> pumvisible() ? "\<C-n>" : "\<Down>"
inoremap <expr><C-k> pumvisible() ? "\<C-p>" : "\<Up>"
inoremap <expr><C-l> pumvisible() ? "\<C-y>" : "\<C-l>"
```

**Comment by randre03** [comment]
This is what I needed. Thanks!
