### ISSUE TITLE
Wrong default value of abbr and menu

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#248]
# Problems summary
wrong default value of abbr and menu

## Expected
for most omni plugin,such as javacomplete2,abbr means abbreviation and  is just a short word about the method name,and menu contains all the info,such as return type and args.
for examplete after `this.`
omni info is : 
word : `toString(`
abbr : `toString()`
kind : `m`
menu : `java.lang.String java.lang.Object.toString()`

so I think the default value should be : 
g:deoplete#max_abbr_width  : 20
g:deoplete#max_menu_width : 80  (and if set to 0, the whole menu info should be display)

## Environment Information

 * OS:arch
 * Neovim version:master

https://github.com/wsdjeg/DotFiles/blob/master/pic/gradle_project.png

**Comment by Shougo** [comment]
This is not "wrong default value problem".
But it should be improved the behavior.

**Comment by wsdjeg** [comment]
Oh ,sorry for the title

**Comment by Shougo** [comment]
Implemented.

**Comment by wsdjeg** [comment]
@Shougo It still not work well for omni source,for javacomplete2,I do not use javacomplete2 source,I just use omni source,
but if I use `call deoplete#custom#set('omni','max_abbr_width', 200)` and `call deoplete#custom#set('omni','max_menu_width', 200)`,the info still not display completely.
here is the pic
![2016-04-24-00 51 40](https://cloud.githubusercontent.com/assets/13142418/14762798/ce639af4-09b6-11e6-912e-ae5e0104762b.png)

**Comment by wsdjeg** [comment]
I need it works same as
https://github.com/wsdjeg/DotFiles/blob/master/pic/gradle_project.png

**Comment by Shougo** [comment]
Fixed.

**Comment by wsdjeg** [comment]
nice, thanks
