### ISSUE TITLE
Feature request: provide completion from :term 

### ISSUE THREAD

**Issue by stobenski** [Shougo/deoplete.nvim#250]
# Problems summary

deoplete does not provide completion from :term buffer/window.  

## Expected

That's would be great if deoplete can provide completion from nvim :term like [tmux-complete](https://github.com/wellle/tmux-complete.vim) provides completion from tmux panes/windows. This is very useful when you work with shells, interpreters and other stuff.

## Environment Information

 * OS: Linux
 * Neovim version: v0.1.4-17-g91c5005

**Comment by Shougo** [comment]
You should create  the new source like tmux-complete.
It is not  deoplete work.
