### ISSUE TITLE
self.debug() does not work in the sources

### ISSUE THREAD

**Issue by Shougo** [Shougo/deoplete.nvim#251]
# Problems summary

`self.debug()` does not work in the sources(no output in the log file).
But it works in the deoplete core.

## Expected

`self.debug()` works in the sources.

@tweekmonster I don't know why it does not work.  Please check it.

**Comment by tweekmonster** [comment]
@Shougo The source needs to set `self.debug_enabled` to True.  This was intentional so that sources can be debugged individually.  Here is how it's enabled in deoplete-jedi: https://github.com/zchee/deoplete-jedi/blob/master/rplugin/python3/deoplete/sources/deoplete_jedi.py#L29

**Comment by tweekmonster** [comment]
I want to also point out that the logger can work outside of the `LoggingMixin` superclass by using the following:

```python
import logging

log = logging.getLogger('deoplete.xxxx')
log.debug('hello')
```

The only requirement is that the logger name is prefixed with `deoplete.`.  It's useful for debugging utility scripts.  Without the prefix, the messages will be sent to neovim's log.  `LoggingMixin` is mainly for convenience and backward compatibility with existing sources.

**Comment by Shougo** [comment]
OK.  But `debug_enabled` is not documented.  I have added it.
