### ISSUE TITLE
Change filename by NERDTree will cause deoplete throw errors

### ISSUE THREAD

**Issue by nightire** [Shougo/deoplete.nvim#253]
# Problems summary

If you change filename in neovim by using plugin like NERDTree, deoplete will throw errors once you enter INSERT mode.

If you cange filename by execute shell command `:!mv ...`, errors will not happen. It may because NERDTree will automatically update the current buffer but shell command not, this will confuse deoplete to maintain the buffer context I guess.

Sometimes switch git branch may also cause this problem but not always.

## Environment Information

 * OS: OS X 10.11.4
 * Neovim version: v0.1.3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. open a file in Neovim
 2. use NERDTree to change the filename
 3. enter Insert Mode
 4. error happens

## Generate a logfile if appropriate

Below is the `:messages` after error happens:

```
[deoplete] Traceback (most recent call last):
[deoplete]   File "/Users/nightire/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 47, in completion_begin
[deoplete]     complete_position, candidates = self.gather_candidates(context)
[deoplete]   File "/Users/nightire/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 85, in gather_candidates
[deoplete]     results = self.gather_results(context)
[deoplete]   File "/Users/nightire/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 158, in gather_results
[deoplete]     context['candidates'] = source.gather_candidates(context)
[deoplete]   File "/Users/nightire/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 24, in gather_candidates
[deoplete]     self.__make_cache(context, self.vim.current.buffer.number)
[deoplete]   File "/Users/nightire/.config/nvim/plugins/deoplete.nvim/rplugin/python3/deoplete/sources/buffer.py", line 59, in __make_cache
[deoplete]     p.findall(x) for x in self.vim.buffers[bufnr]
[deoplete]   File "/Users/nightire/Library/Python/3.5/lib/python/site-packages/neovim/api/common.py", line 138, in __getitem__
[deoplete]     return self._fetch()[idx]
[deoplete] IndexError: list index out of range
[deoplete] An error has occurred. Please execute :messages command.
```

**Comment by wsdjeg** [comment]
have you try with vimfiler, it is also a file manager plugin for vim ,wrote by Shougo,you can have a look at my [Dotfiles](https://github.com/wsdjeg/DotFiles)

**Comment by nightire** [comment]
@wsdjeg Thanks. But the problem is not what tools should user to choose for files management, NERDTree has lots of users, this error will drives them crazy. Besides I am not a new user to deoplete, this error is a new thing, I've never encounter this before 1-2 days ago, I think this exists within recently updates.

**Comment by wsdjeg** [comment]
@nightire I have try in vimfiler,`r` map to rename file bydefault,and I can not reproduce this issue.same as nerdtree.

**Comment by nightire** [comment]
@wsdjeg yep, as mature vim users, we always have many different ways to do one thing well. For me, NERDTree not the only choice to manage files, but still the problem exists, I just point it out to see if it's resolvable. I'm glad vimfiler behaves very well 😸 ~

**Comment by wsdjeg** [comment]
@nightire sorry I can not find out wether it is an issue with nerdtree,but it works well for me.

**Comment by tweekmonster** [comment]
The issue was because a recent change used Vim's buffer number as a list index.  FWIW, I use vimfiler and this error occurred because I was using a session that restored buffers that used non-contiguous buffer numbers.

**Comment by Shougo** [comment]
Fixed.
