### ISSUE TITLE
Duplicated completion while wrapping over textwidth.

### ISSUE THREAD

**Issue by kwinczek** [Shougo/deoplete.nvim#263]
# Problems summary
 As in https://github.com/Shougo/deoplete.nvim/issues/182, wrapping over `textwidth` causes duplication.

## Expected

Simply wrap without duplication.

## Environment Information

 * OS: Mac OS X
 * Neovim version: 0.1.3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/minimal-plugged')

Plug 'Shougo/deoplete.nvim'

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#enable_camel_case = 1
let g:deoplete#file#enable_buffer_path = 1
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
autocmd CompleteDone * pclose!
inoremap <expr> <CR>
    \ pumvisible() ? deoplete#mappings#close_popup() :
    \ "\<CR>"
inoremap <silent><expr> <Tab>
    \ pumvisible() ? "\<C-n>" :
    \ deoplete#mappings#manual_complete()
inoremap <silent><expr> <S-Tab>
    \ pumvisible() ? "\<C-p>" :
    \ deoplete#mappings#manual_complete()
set omnifunc=syntaxcomplete#Complete
set completeopt=longest,menuone,preview,noinsert
```

## The reproduce ways from neovim starting (Required!)

 1. Start neovim with above configuration (provided vim-plug is installed, execute :PlugInstall).
 2. Type in text which will eventually wrap.

## Screen shot (if possible)

![expand](https://cloud.githubusercontent.com/assets/796021/14678480/7c756410-071e-11e6-8a72-b2d05e7c0953.gif)

**Comment by Shougo** [comment]
Fixed.

**Comment by kwinczek** [comment]
Works perfectly, thanks!
