### ISSUE TITLE
Completion suggestion showing even when equal to typed text

### ISSUE THREAD

**Issue by jeromedalbert** [Shougo/deoplete.nvim#267]
# Problems summary

On the screenshot below I start typing "append" and everything is fine:

<img width="538" alt="screen shot 2016-04-26 at 11 13 36 am" src="https://cloud.githubusercontent.com/assets/236461/14843340/3d2f224c-0c04-11e6-87ed-1a1397aa405e.png">

But if I finish manually typing the word "append", the completion suggestion is still displayed:

<img width="555" alt="screen shot 2016-04-26 at 11 14 17 am" src="https://cloud.githubusercontent.com/assets/236461/14843361/613e2e8a-0c04-11e6-8507-0414f76496d2.png">

## Expected

A completion suggestion that is equal to manually typed text should not display.

I do not know if this is a Deoplete or a (neo)Vim problem.

## Environment Information

 * OS: Mac OS X

 * nvim-python-doctor result:
https://github.com/tweekmonster/nvim-python-doctor

```
## Neovim Python Diagnostic

\e[1;37m## Neovim Python Diagnostic\e[m

- Neovim Version: \e[36mNVIM 0.1.3\e[m

\e[1;37m## Remote plugins\e[m

**Manifest File**: `/Users/jerome/.dotfiles/.vim/.init.vim-rplugin~`
**Plugin**: /Users/jerome/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete
  - Registered: \e[31mNo\e[m
\e[31m**Manifest is not up to date**\e[m

\e[1;37m### 'python' info from /usr/local/bin/nvim\e[m

\e[33mWARN: 'g:python_host_prog' is not set.\e[m
\e[33mWARN: Fallback to '/usr/local/bin/python'\e[m
**Python Version**: `2.7.10`
**Neovim Package Version**: `neovim (0.1.5)`\e[33m (latest: `0.1.7`)\e[m

\e[1;37m### 'python3' info from /usr/local/bin/nvim\e[m

\e[33mWARN: 'g:python3_host_prog' is not set.\e[m
\e[33mWARN: Fallback to '/usr/local/bin/python3'\e[m
**Python Version**: `3.5.1`
**Neovim Package Version**: `neovim (0.1.5)`\e[33m (latest: `0.1.7`)\e[m

\e[1;37m## Python versions visible in the current shell\e[m

- **python** version: `Python 2.7.10`
  - **path**: `/usr/local/bin/python`
  - **neovim** version: `neovim (0.1.5)`
- **python3** version: `Python 3.5.1`
  - **path**: `/usr/local/bin/python3`
  - **neovim** version: `neovim (0.1.5)`

\e[1;37m## Messages or Suggestions\e[m

- ERR: You need to run `:UpdateRemotePlugins` in Neovim to enable plugins.
- FIX: Upgrade the neovim package with: `pip2 install -U --user neovim`.
- FIX: Upgrade the neovim package with: `pip3 install -U --user neovim`.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin()
Plug 'Shougo/deoplete.nvim'
Plug 'mattn/emmet-vim'
Plug 'Shougo/neosnippet.vim'
call plug#end()

set completeopt=menu,preview,noinsert
set complete=.,w
let g:deoplete#enable_at_startup = 1
let g:neosnippet#disable_runtime_snippets = { '_' : 1 }
let g:neosnippet#snippets_directory='~/.vim/my-snippets'

imap <expr> <tab> TabComplete()
smap <expr> <tab> TabComplete()
xmap <expr> <tab> TabComplete()
function! TabComplete()
  if neosnippet#expandable_or_jumpable()
    return "\<Plug>(neosnippet_expand_or_jump)"
  elseif &filetype =~ 'html\|css' && emmet#isExpandable()
    return "\<plug>(emmet-expand-abbr)"
  elseif pumvisible()
    return "\<c-y>\<esc>a"
  else
    return "\<tab>"
  endif
endfunction
```

## The reproduce ways from neovim starting (Required!)

 1. type `i`, type `coconut`, press `enter`.
 2. type `coconut`
 3. see the completion still being displayed

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)

<img width="177" alt="screen shot 2016-04-26 at 11 35 08 pm" src="https://cloud.githubusercontent.com/assets/236461/14843744/8c86f1e6-0c07-11e6-82cf-bef9b6ef9df9.png">

## Upload the log file

[log_72457.zip](https://github.com/Shougo/deoplete.nvim/files/238046/log_72457.zip)

**Comment by wsdjeg** [comment]
Why it should not be desplay?

**Comment by wsdjeg** [comment]
and in vim，by default you can type C -p complete key word，and if there is only one result，it will be completed，and popupmenu will not be opened.

**Comment by jeromedalbert** [comment]
> Why it should not be desplay?
Because it is redundant with what I just typed manually.

I have been using Vim for only a month and a half though, so I don't know if this is "expected" traditional Vim behavior. I have been using other text editors in the past who would hide completion if the manually entered text is the same

> and in vim，by default you can type C -p complete key word，and if there is only one result，it will be completed，and popupmenu will not be opened.

I use `completeopt+=noinsert`. In any case, I don't want to complete a key word here, I just type it manually. Consider the case when I type "peach" really fast. I didn't need to use completion for that, because it is a short 5-letter word. But, if "peach" was present before, my screen will be polluted with an unwanted menu completion that would unnecessarily hide the possible line below, forcing me to type another keystroke to hide the completion.

**Comment by wsdjeg** [comment]
how about typr`Ctrl + e`in insert mode?it whould be able to close popupmenu

**Comment by tweekmonster** [comment]
@jeromedalbert I'm pretty sure this is something that Vim does.  Typically, you have to manually trigger completions with `^X^O` and Vim keeps the menu up for as long as you're within the completion word boundary.  deoplete and other completion plugins change the behavior to show completions as you type, but all they can do is set the list of candidates that can be shown in the menu.  From there, the plugins have no control over the display of the menu besides repopulating the list.

I have some unrelated questions about `nvim-python-doctor` if you don't mind:

- In your setup, `~/.dotfiles/.vim` is symlinked to `~/.vim` right?
- How did you copy the output to the clipboard and what terminal were you using?  The color sequences shouldn't have been copied if you piped to `pbcopy`

**Comment by jeromedalbert** [comment]
> how about typrCtrl + ein insert mode?it whould be able to close popupmenu

Indeed it would, but that is an extra keystroke for something I would want to do systematically 😭 

> deoplete and other completion plugins change the behavior to show completions as you type, but all they can do is set the list of candidates that can be shown in the menu. From there, the plugins have no control over the display of the menu besides repopulating the list.

That makes me a sad panda! Ok, I'll have to get used to this behavior then. Although, would there be a way in vimscript to check the current typed word after each inserted character (`InsertCharPre` or equivalent), then check if this word is the same as the one in the completion list (no idea how to do this), and if so, hide the completion list (`c-e` or equivalent)?

> some unrelated questions about nvim-python-doctor if you don't mind:

- my `~/.vim` is symlinked to `~/.dotfiles/.vim`
- Yeah it works fine with `pbcopy`. What I did was selecting the output with my mouse and copy it. In my shell (zsh), the output showed without colors.

**Comment by Shougo** [comment]
`let g:deoplete#enable_refresh_always = 1`

**Comment by jeromedalbert** [comment]
Works with the fix!

Now I need to decide whether I want to keep using this option, since it makes the completion menu flicker a lot. I guess it's as far as we can get with Vim's constraints! Thanks

**Comment by vbauerster** [comment]
@jeromedalbert 
> A completion suggestion that is equal to manually typed text should not display.

I completely agree with that, but I can't live with flickering menu at all.
So it is much more simpler, at least for me, just to close the popup manually, and stay in insert mode. But pressing \<C-e> for closing popup is too overweighting. Pressing \<Esc> would be more natural, so following snippet is just for that:

```
imap <expr><Esc> pumvisible() ? deoplete#mappings#close_popup() : "\<Esc>"
```

**Comment by wsdjeg** [comment]
I use Enter, and here is my func for enter tab and leader+tab
```vim
function! MyEnterfunc() abort
    if pumvisible()
        if getline('.')[col('.') - 2]=="{"
            return "\<Enter>"
        elseif g:settings.autocomplete_method == 'neocomplete'||g:settings.autocomplete_method == 'deoplete'
            return "\<C-y>"
        else
            return "\<esc>a"
        endif
    elseif getline('.')[col('.') - 2]=="{"&&getline('.')[col('.')-1]=="}"
        return "\<Enter>\<esc>ko"
    else
        return "\<Enter>"
    endif
endf

function! MyLeaderTabfunc() abort
    if g:settings.autocomplete_method == 'deoplete'
        return deoplete#mappings#manual_complete(['omni'])
    elseif g:settings.autocomplete_method == 'neocomplete'
        return neocomplete#start_manual_complete(['omni'])
    endif
endfunction

function! MyTabfunc() abort
    if getline('.')[col('.')-2] =='{'&& pumvisible()
        return "\<C-n>"
    endif
    if neosnippet#expandable() && getline('.')[col('.')-2] =='(' && !pumvisible()
        return "\<Plug>(neosnippet_expand)"
    elseif neosnippet#jumpable() && getline('.')[col('.')-2] =='(' && !pumvisible() && !neosnippet#expandable()
        return "\<plug>(neosnippet_jump)"
    elseif neosnippet#expandable_or_jumpable() && getline('.')[col('.')-2] !='('
        return "\<plug>(neosnippet_expand_or_jump)"
    elseif pumvisible()
        return "\<C-n>"
    else
        return "\<tab>"
    endif
endfunction
```

**Comment by vbauerster** [comment]
@wsdjeg very interesting!
As I understood, in the `MyTabfunc`, you avoid expanding snippet, if there is `(` character before cursor. Why? Can you please supply little use case for this behaviour and for `{` character as well?

**Comment by wsdjeg** [comment]
it is due to my useage with neosnippet.sometime I need expand `(`,but some times I do not need.I have snip file like this, it will help me auto close pairs.
```
snippet     (
options     word
    (${1:#:output})${2}

snippet     [
options     word
    [${1:#:output}]${2}

snippet     {
options     word
    {
        ${1}
    }
```

**Comment by Xandaros** [comment]
I'd like to mention that with some completion engines, leaving the menu open might be desirable.
I personally quite like to see the type of a function in the completion menu, even if I typed it completely. In fact, I often type out the whole function (most have short names) and then use the completion menu to look at the type, so I know which way around the arguments go.
