### ISSUE TITLE
Disable deoplete for markdown and text files for buffer but keep suggestions from UltiSnip

### ISSUE THREAD

**Issue by pdoak** [Shougo/deoplete.nvim#269]
# Problems summary

When writing markdown or text documents is it possible to disable deoplete for buffers and windows but still allow deoplete to show snippets from UltiSnips. Current I have the following in my vimrc:
`    let g:deoplete#sources._=['omni', 'buffer', 'member', 'tag', 'ultisnips', 'file']
`
I also have a function in my vimrc which is called by an autocmd:
`autocmd bufread,bufnewfile *.md call MyMarkdownSettings() 
`
Should I add something like:
`    let g:deoplete#sources._=[ 'ultisnips']`
to that function?

## Environment Information

 * OS:10.11.4

```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.4-180-g2ba30a7

## Python versions visible to Neovim

### 'python' info from /usr/local/bin/nvim

WARN: 'g:python_host_prog' is not set
WARN: Fallback to '/usr/bin/python'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

### 'python3' info from /usr/local/bin/nvim

WARN: 'g:python3_host_prog' is not set
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

## Python versions visible in the current shell

- **python** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
- **python3** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
```

**Comment by Shougo** [comment]
`let b:deoplete_ignore_sources = ['buffer']`

**Comment by pdoak** [comment]
Thank you
