### ISSUE TITLE
Custom mark appears twice for the ultisnips source

### ISSUE THREAD

**Issue by gbcreation** [Shougo/deoplete.nvim#270]
# Problems summary

When setting a custom mark for the ultisnips source with  `call deoplete#custom#set('ultisnips', 'mark', '*')`, the `*` mark appears twice in the popup menu. For example:

```
const    * *
contains * *
```

## Expected

The custom mark appears only once:
```
const    *
contains *
```

## Environment Information

 * OS: ArchLinux
 * Neovim Version: NVIM v0.1.4

**Comment by Shougo** [comment]
Fixed.

**Comment by gbcreation** [comment]
Thanks.
