### ISSUE TITLE
How can I config to let deoplete do not change the weigth of popupmenu.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#271]
# Problems summary
I want to see all the info in the popupmenu,but the deoplete only show me part of it when I use `vsplit`.even if I have this in my vimrc.
```vim
let g:deoplete#max_abbr_width = 2000
let g:deoplete#max_menu_width = 2000
```

![2016-05-01-13 18 50](https://cloud.githubusercontent.com/assets/13142418/14940230/9574526c-0f9f-11e6-817d-952d4266aa4a.png)
![2016-05-01-13 18 55](https://cloud.githubusercontent.com/assets/13142418/14940231/9577e7ba-0f9f-11e6-92dd-7c2aee85ac37.png)

## Expected

I have test it in neocomplete,it works as expected
![2016-05-01-13 21 44](https://cloud.githubusercontent.com/assets/13142418/14940236/d1b7bf3e-0f9f-11e6-9357-aab4c9672904.png)

## Environment Information

 * OS:

 * nvim-python-doctor result:
https://github.com/tweekmonster/nvim-python-doctor

```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.4-180-g2ba30a7

## Python versions visible to Neovim

### 'python' info from /usr/local/bin/nvim

WARN: 'g:python_host_prog' is not set
WARN: Fallback to '/usr/bin/python'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

### 'python3' info from /usr/local/bin/nvim

WARN: 'g:python3_host_prog' is not set
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

## Python versions visible in the current shell

- **python** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
- **python3** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Note: Why do you ignore the issue template?

https://github.com/Shougo/deoplete.nvim/issues/238

```vim
		call deoplete#custom#set('javacomplete2', 'max_abbr_width', 0)
		call deoplete#custom#set('javacomplete2', 'max_menu_width', 0)
```

**Comment by wsdjeg** [comment]
oh sorry.i know

**Comment by wsdjeg** [comment]
Hi @Shougo I use 
```vim
let g:deoplete#max_abbr_width = 0
let g:deoplete#max_menu_width = 0
```
after this setting,I see two dots befor abbr.
here is the pic

![2016-05-02-19 41 14](https://cloud.githubusercontent.com/assets/13142418/14953634/f235e098-109d-11e6-9d1c-9e3aed1e68ee.png)

**Comment by Shougo** [comment]
Fixed.
