### ISSUE TITLE
[question] Substitute completion after selection

### ISSUE THREAD

**Issue by balta2ar** [Shougo/deoplete.nvim#272]
Hello. Say, I have a file with completion candidates located at `/tmp/rt.candidates.txt` as follows:
```
338175 apple | Please update apple config https://www.google.com/config
364299 google | C++ coding style https://www.google.com/coding-style
337871 google | Implement simulation https://www.google.com/simulation
```

Whenever I type `RT:<some words>` (any filetype) I want completion to filter candidates by <some words> pattern. **However, when best candidate is expanded (selected) using `Enter` or `C-n`, I want to get `RT:123456`.**

Here is the source for deoplete that I have managed to produce so far: http://ix.io/B2G/python
Could you please give me hints on how to do that? Thank you.

**Comment by balta2ar** [comment]
I've just found out that if I return an item like this:
``` python
            item = {
                    'word': short + '<word',
                    'abbr': long + '<abbr',
                    }
```
leaving only word and abbr, it displays long option, inserts short option, but it looks as if it filters over short version. How do I filter over long version in this case?

**Comment by balta2ar** [comment]
As far as I understand what I want can be achieved if I filter out candidates on my own, in the source plugin. But you clearly stated in the documentation that it's not recommended approach.

**Comment by balta2ar** [comment]
Even though it may look ugly, I still think I have to filter candidates from the source plugin. Is there any way to call deoplete's fuzzy matchers from `gather_candidates`?

**Comment by Shougo** [comment]
Hints: `:help CompleteDone` and `:help v:completed_item`

**Comment by balta2ar** [comment]
Thanks! And what about calling deoplete's fuzzy matchers from `gather_candidates`? Is it possible?

**Comment by Shougo** [comment]
It cannot be possible.
Users can custom the matcher.

**Comment by balta2ar** [comment]
Well, I ended up filtering results by my own using this library: https://pypi.python.org/pypi/regex
