### ISSUE TITLE
snippet don't show in the list

### ISSUE THREAD

**Issue by marcelino671** [Shougo/deoplete.nvim#273]
# Problems summary
Deoplete with omni completion works fine, but when using with snippet this don't show in php files but work when pressing the triger key, neosnippes or ultisnips, both don't work exclusive in php files, tested in python and javascript and show all sources.

If I delete the omni patterns comand above the snippet back to work, but deoplete only show snippet completion:
`let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'`

I have tryed [phpcomplete_extended](https://github.com/m2mdas/phpcomplete-extended) like the recomendation and [phpcomplete.vim](https://github.com/shawncplus/phpcomplete.vim), but have the same behavior, the problem is in the omni_patterns command.

## Expected
Expected to show all sources in the list without errors.

## Environment Information

 * OS: Arch Linux x64

 * nvim-python-doctor result:
[nvim-python-doctor.txt](https://github.com/Shougo/deoplete.nvim/files/256373/nvim-python-doctor.txt)

```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.4-180-g2ba30a7

## Python versions visible to Neovim
3.5.1 and 2.7.11
### 'python' info from /usr/local/bin/nvim

WARN: 'g:python_host_prog' is not set
WARN: Fallback to '/usr/bin/python'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

### 'python3' info from /usr/local/bin/nvim

WARN: 'g:python3_host_prog' is not set
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

## Python versions visible in the current shell

- **python** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
- **python3** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
set runtimepath+=~/.config/nvim/plugged/phpcomplete-extended
set runtimepath+=~/.config/nvim/plugged/vimproc.vim
set runtimepath+=~/.config/nvim/plugged/unite.vim
set runtimepath+=~/.config/nvim/plugged/ultisnips
set runtimepath+=~/.config/nvim/plugged/vim-snippets
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.php = '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
```

## The reproduce ways from neovim starting (Required!)

 1. nvim - /usr/bin/nvim

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID} 
[log_21094.txt](https://github.com/Shougo/deoplete.nvim/files/256372/log_21094.txt)

## Screen shot (if possible)

deoplete without omni patterns
![deoplete without omni patterns](https://cloud.githubusercontent.com/assets/7757352/15135652/4bd39490-1668-11e6-8e88-edf50e1235ca.png)

deoplete with omni patterns
![deoplete with omni patterns](https://cloud.githubusercontent.com/assets/7757352/15135653/4f963f74-1668-11e6-8fd8-3ac0028951eb.jpg)

**Comment by Shougo** [comment]
It is due to `g:deoplete#omni_patterns`.  Please read the documentation.
You should use `g:deoplete#omni#input_patterns`.
