### ISSUE TITLE
ES6 Modules support

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#28]
I know this is still WIP, but curious on your thoughts for adding support for ES6 Modules. A lot of new JS libs are shipping as ES6 and require using modules now. Seems like it would be a great feature to add. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

**Comment by HerringtonDarkholme** [comment]
I think this should probably goes to [neoinclude](https://github.com/Shougo/neoinclude.vim) where you can set up `includeexpr` for ES2015

**Comment by mhartington** [comment]
Will this be something I have to add myself? I thought that deoplete included this? I could be wrong though

**Comment by Shougo** [comment]
deoplete does not support it.
But you can create original source for it.

**Comment by schickling** [comment]
So whats the best way to enable ES6 modules by now?

**Comment by Shougo** [comment]
You can use the omnifunc supports ES6 module or create the original source for ES6 module.

**Comment by schickling** [comment]
Could you please elaborate a bit more on that? Thanks for your help @Shougo!

**Comment by HerringtonDarkholme** [comment]
@schickling Deoplete is just a completion engine. A completion engine is agnostic about language feature. If user wants to add language support, he/she must implement a custom completion candidates for engine. In deoplete, users can provide completion candidates by creating source. Source is an interface written in python. You can look at deoplete's code for example sources.

**Comment by mhartington** [comment]
An example would be this I have for typescript.

https://github.com/mhartington/deoplete-typescript

Or https://github.com/zchee/deoplete-go/ for Go.

They provide deoplete with the completion candidates through their own process.

**Comment by schickling** [comment]
Thank you a lot @HerringtonDarkholme @mhartington

**Comment by mhartington** [comment]
shameless plug, would love some help on the typescript plugin if you're up for it :+1:

**Comment by schickling** [comment]
@mhartington I'm currently riding the flow-type boat but will get back to that if I switch over to Typescript!
