### ISSUE TITLE
neoinclude only completes include filenames

### ISSUE THREAD

**Issue by indiofish** [Shougo/deoplete.nvim#286]
# Problems summary
When using neocomplete + neoinclude, ```#include <string.h>``` and typing str would show completion candidates like strcmp, strlen.
When using deoplete + neoinclude, completion of ```#include <filename.h>``` is supported, but keywords from the included file is not.

## Expected
Work like neocomplete

## Environment Information

 * OS: Ubuntu 14.04

## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.5

## Python versions visible to Neovim
3.4, 2.7

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/neoinclude.vim
set completeopt=.,b,i
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)
#include <string.h>
str...

Not sure if this is a bug, or intended. Should I be using deoplete-clang for completion from included files?
Thanks in advance.

**Comment by Shougo** [comment]
Fixed.
