### ISSUE TITLE
deoplete is not working, in mac, already show please execute :UpdateRemotePlugins command and restart neovim

### ISSUE THREAD

**Issue by aslijiasheng** [Shougo/deoplete.nvim#287]
# Problems summary
My system is MAC, 
 I use neobundle it, but run neovim show please execute :UpdateRemotePlugins command and restart neovim
I look Shougo/deoplete.nvim#160, run neovim execute NeoBundleRemotePlugins and restart nevoid, but already show it

## Environment Information

 * OS:

 * nvim-python-doctor result:
https://github.com/tweekmonster/nvim-python-doctor
Include the output below this line in your Github issues.

\e[1;37m## Neovim Python Diagnostic\e[m

- Neovim Version: \e[36mNVIM v0.1.2-324-gbcbcf23\e[m

\e[1;37m## Remote plugins\e[m

**Manifest File**: `/Users/sky/.config/nvim/.init.vim-rplugin~`
**Plugin**: /Users/sky/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete
  - Registered: \e[31mNo\e[m
\e[31m**Manifest is not up to date**\e[m

\e[1;37m### 'python' info from /usr/local/bin/nvim\e[m

**Config**: `let g:python_host_prog = '/usr/bin/python'`
**Python Version**: `2.7.10`
**Neovim Package Version**: `neovim (0.1.8)`\e[33m (latest: ``)\e[m

\e[1;37m### 'python3' info from /usr/local/bin/nvim\e[m

**Config**: `let g:python3_host_prog = '/usr/local/bin/python3'`
**Python Version**: `3.5.1`
**Neovim Package Version**: `neovim (0.1.8)`\e[33m (latest: ``)\e[m

\e[1;37m## Python versions visible in the current shell\e[m

- **python** version: `Python 2.7.10`
  - **path**: `/usr/bin/python`
  - **neovim** version: `neovim (0.1.8)`
- **python3** version: `Python 3.5.1`
  - **path**: `/usr/local/bin/python3`
  - **neovim** version: `neovim (0.1.8)`

\e[1;37m## Messages or Suggestions\e[m

- ERR: You need to run `:UpdateRemotePlugins` in Neovim to enable plugins.
- FIX: Upgrade the neovim package with: `pip2 install -U --user neovim`.
- FIX: Upgrade the neovim package with: `pip3 install -U --user neovim`.
```
## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.4-180-g2ba30a7

## Python versions visible to Neovim

### 'python' info from /usr/local/bin/nvim

WARN: 'g:python_host_prog' is not set
WARN: Fallback to '/usr/bin/python'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

### 'python3' info from /usr/local/bin/nvim

WARN: 'g:python3_host_prog' is not set
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `Python 3.5.1`
**Neovim Package Version**: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`

## Python versions visible in the current shell

- **python** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
- **python3** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file

[log.txt](https://github.com/Shougo/deoplete.nvim/files/309156/log.txt)

**Comment by Shougo** [comment]
This is not deoplete issue.
