### ISSUE TITLE
Candidates filtered by first character

### ISSUE THREAD

**Issue by alexozer** [Shougo/deoplete.nvim#288]
# Problems summary
Deoplete filters candidates by their first character matching the first character typed, after which full fuzzy matching begins. Thus, it seems like it is impossible to match substrings within candidates that do not contain the first character.

## Expected
Given this Python setup, for instance:

```python
class Something:
    def optionone(self):
        pass

    def optiontwo(self):
        pass

    def thing(self):
        pass

a = Something()
```

Typing `a.one` gives no results, which it should match `optionone`.
Typing `a.t` should match `thing` and `optiontwo`, but only matches `thing`.

## Environment Information

 * OS: Arch Linux

 * nvim-python-doctor result:

```markdown
## Neovim Python Diagnostic

- Neovim Version: NVIM 0.1.4

## Remote plugins

**Manifest File**: `/home/alex/.dotfiles/vim/.config/nvim/.init.vim-rplugin~`
**Plugin**: /home/alex/.dotfiles/vim/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete
  - Registered: No
**Manifest is not up to date**

### 'python' info from /usr/bin/nvim

WARN: 'g:python_host_prog' is not set.
WARN: Fallback to '/usr/bin/python'
**Python Version**: `3.5.1`
**Neovim Package Version**: `0.1.8` (latest: `0.1.9`)

### 'python3' info from /usr/bin/nvim

WARN: 'g:python3_host_prog' is not set.
WARN: Fallback to '/usr/bin/python3'
**Python Version**: `3.5.1`
**Neovim Package Version**: `0.1.8` (latest: `0.1.9`)

## Python versions visible in the current shell

- **python** version: `Python 3.5.1`
  - **path**: `/usr/bin/python`
  - **neovim** version: `neovim (0.1.8)`
- **python3** version: `Python 3.5.1`
  - **path**: `/usr/bin/python3`
  - **neovim** version: `neovim (0.1.8)`

## Messages or Suggestions

- ERR: You need to run `:UpdateRemotePlugins` in Neovim to enable plugins.
- WARN: `python` version should be Python 2.x, but is version `3.5.1`.
- FIX: Upgrade the neovim package with: `pip3 install -U --user neovim`.
- FIX: Upgrade the neovim package with: `pip3 install -U --user neovim`.
- WARN: `python` and `python3` are using the same version: `3.5.1`.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Alex Ozer

if !has('nvim')
	set nocompatible
endif

nnoremap ; :
nnoremap : ;

call plug#begin('~/.vim/plugged')

"Plug 'klen/python-mode'

Plug 'junegunn/vim-plug'

if has('nvim')
   function! DoRemote(arg)
     UpdateRemotePlugins
   endfunction
   Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }
endif
Plug 'zchee/deoplete-jedi'
Plug 'zchee/deoplete-clang'

call plug#end()

let g:deoplete#enable_at_startup = 1

" vim:foldenable:foldlevelstart=0:foldmethod=marker:foldlevel=0
```

## The reproduce ways from neovim starting (Required!)

 1. Open neovim
 2. Add Python code in Expected section
 3. Try the examples given in the Expected section

**Comment by zchee** [comment]
@alexozer Hi, I'm deoplete's collaborator.
Just in case(although not written in your init.vim), Are you use [deoplete-jedi](https://github.com/zchee/deoplete-jedi) ?
If so, I have tested.

- `a.one`
 - match `a.optionone`
- `a.t`
 - match `a.thing`
 - not match `a.optiontwo`
- `a.tw`
 - match `a.optiontwo`

Screen Shot (image was large, link only)
[screenshot 2016-06-13 16 51 54](https://cloud.githubusercontent.com/assets/6366270/16000447/7488e766-3187-11e6-9402-6f3569c5e3a0.png)
[screenshot 2016-06-13 16 53 43](https://cloud.githubusercontent.com/assets/6366270/16000451/7ad70256-3187-11e6-904f-d41240ace7b8.png)
[screenshot 2016-06-13 16 53 29](https://cloud.githubusercontent.com/assets/6366270/16000453/7cb594ac-3187-11e6-907b-c0931b43eb15.png)

and,
```
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
call deoplete#custom#set('go', 'matchers', ['matcher_full_fuzzy'])
```

**Comment by zchee** [comment]
@alexozer and, If you do not use deoplete-jedi, my comment is irrelevant.
Sorry.

**Comment by alexozer** [comment]
@zchee I do use deoplete-jedi, that's strange we get different results! I'll do some more testing in a little while.

Also as a side note, which colorscheme are you using and how are you getting that Python icon in the top bar?

**Comment by zchee** [comment]
@alexozer 
> I do use deoplete-jedi, that's strange we get different results! I'll do some more testing in a little while.

Oh, sorry. I'm mistaken.
deoplete-jedi parses the buffer(and current cursor) context using the jedi, so maybe the result will differ.

> Also as a side note, which colorscheme are you using and how are you getting that Python icon in the top bar?

LOL.
It's [vim-airline/vim-airline](https://github.com/vim-airline/vim-airline) and [ryanoasis/vim-devicons](https://github.com/ryanoasis/vim-devicons)

**Comment by alexozer** [comment]
@zchee I've managed to reproduce in an isolated Linux user account with this updated minimal init.vim (uses [vim-plug](https://github.com/junegunn/vim-plug)):

```vim
" Alex Ozer

if !has('nvim')
	set nocompatible
endif

nnoremap ; :
nnoremap : ;

call plug#begin('~/.vim/plugged')

"Plug 'klen/python-mode'

Plug 'junegunn/vim-plug'

if has('nvim')
   function! DoRemote(arg)
     UpdateRemotePlugins
   endfunction
   Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }
endif
Plug 'zchee/deoplete-jedi'
Plug 'zchee/deoplete-clang'

call plug#end()

let g:deoplete#enable_at_startup = 1

" vim:foldenable:foldlevelstart=0:foldmethod=marker:foldlevel=0
```

And thanks for your vim config info haha, also just wondering what is your overall vim colorscheme?

**Comment by alexozer** [comment]
Aha! It seems like full fuzzy mode is what I wanted:

```vim
call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
```

**Comment by zchee** [comment]
@alexozer Yeah, it's needed.

also, my colorscheme? lol
https://github.com/zchee/.nvim/blob/master/colors/hybrid_reverse.vim
that's [hybrid_reverse.vim](https://github.com/kristijanhusak/vim-hybrid-material/blob/master/colors/hybrid_reverse.vim) with small customize.

**Comment by balta2ar** [comment]
@zchee @Shougo Guys, I'm sorry to chime in as my question is completely irrelevant, but are there any plans to support GoToDefinition in deoplete and its plugins? I know it's not exactly about "completion" but these features always go hand-to-hand in other plugins. Both YouCompleteMe and vim's python-mode plugins support that. I moved from YouCompleteMe to deoplete and I'm happy. Now I want to get rid of python-mode because it's not maintained. But I can't unless there is GoToDefinition.

**Comment by Shougo** [comment]
@balta2ar https://github.com/zchee/deoplete-jedi/issues/35
