### ISSUE TITLE
Order of sources

### ISSUE THREAD

**Issue by kiryph** [Shougo/deoplete.nvim#294]
Is it possible to adjust the order of the entries shown in the popup menu:

Consider for example a menu in a python file using ultisnips ([US]) and deoplete-jedi ([jedi]).

![deoplete-menu-order](https://cloud.githubusercontent.com/assets/371756/16176663/5611156a-3614-11e6-995b-14b6afdfa807.png)

In this case I would like to have the menu alphabetically sorted and snippets should be ranked higher than suggestions from jedi.
The order should look like this

```
1. for                                      [US] for loop
2. for                             keyword  [jedi]
3. format(value, format_spec=None) function [jedi]
4. formatting                               [T]
5. formfeed                                 [T]
```

**Comment by Shougo** [comment]
`:help deoplete-source-attribute-rank`

**Comment by kiryph** [comment]
thanks for your quick response.
I have checked the value
```
~/.config/nvim/plugged
❯ ag self.rank
deoplete-jedi/rplugin/python3/deoplete/sources/deoplete_jedi.py
25:        self.rank = 500

deoplete.nvim/rplugin/python3/deoplete/sources/base.py
30:        self.rank = 100

deoplete.nvim/rplugin/python3/deoplete/sources/file.py
24:        self.rank = 150

deoplete.nvim/rplugin/python3/deoplete/sources/omni.py
20:        self.rank = 500

neco-vim/rplugin/python3/deoplete/sources/vim.py
38:        self.rank = 500

ultisnips/rplugin/python3/deoplete/sources/ultisnips.py
9:        self.rank = 8
```

So I could change the value of ultisnips to a higher value than 500. Could I do this from within my vimrc?

And what about the alphabetical sorting of all entries? It looks like this is not possible right now. Am I right?

**Comment by Shougo** [comment]
```vim
		" Change the source rank
		call deoplete#custom#set('buffer', 'rank', 9999)
```

> And what about the alphabetical sorting of all entries? It looks like this is not possible right now. Am I right?

Please read the documentation before the question.

`:help deoplete-filter-sorter_word`

**Comment by kiryph** [comment]
Apparently, all my questions are contained in the documentation. My fault. Sorry for this issue and clutter. Also thanks for adding my sorting question to the faq.

After adding following two lines to init.vim I get the desired result:

```
call deoplete#custom#set('_', 'sorters', ['sorter_word'])
call deoplete#custom#set('ultisnips', 'rank', 9999)
```
![deoplete-menu-order-sorted](https://cloud.githubusercontent.com/assets/371756/16176815/c3cc7770-3619-11e6-8b40-862ae933af97.png)

What do you think about adding a help tag `|deoplete-change-source-rank|` to the example?

        " Change the source rank                                 |deoplete-change-source-rank|
        call deoplete#custom#set('buffer', 'rank', 9999)

and adding to the help section `|deoplete-source-attribute-rank|` a link to it?

```
                                        deoplete-source-attribute-rank
rank            (Number)                        (Optional)
                Source priority.  Higher values imply higher priority.
                If you omit it, it is set 100.
                Note: It is high priority than match position.
                This value can be changed by the user as shown here
                |deoplete-change-source-rank|.
```

A second low priority suggestion of me would be:
Add an index for all questions of the faq `|deoplete-faq-index|`. Sometimes you do not know what you are looking for. So skimming through all available questions could also be helpful to avoid questions from lazy people like me.

```
~/.config/nvim/plugged/deoplete.nvim/doc master
❯ ag Q:
deoplete.txt
929:Q: deoplete does not work.
954:Q: I want to get quiet messages in auto completion.
962:Q: I want to look selected function's arguments in deoplete. But I don't
968:Q: I want to use auto select feature like |neocomplete|.
974:Q: I want to lock auto completion.
978:Q: Ruby omni completion does not work in neovim.
985:Q: I want to use C/C++ omni completion with deoplete.
1003:Q: I want to use head matcher instead of fuzzy matcher.
1009:Q: Is deoplete faster than neocomplete?
1016:Q: I want to complete AAA using deoplete.
1020:Q: I want to use jedi-vim omni completion with deoplete.
1025:Q: When I press enter, neovim close the popup instead of inserting new line.
1035:Q: I want to use "vim-lua-ftplugin".
1048:Q: I want to disable buffer source.
1055:Q: I want to complete go candidates.
1060:Q: I want to complete the candidates from other files.
1067:Q: I want to close the preview window after completion is done.
1075:Q: I want to see the typed word in the completion menu.
1081:Q: How to prevent auto bracket completion?
1088:Q: Why deoplete checks the foldmethod?
1098:Q: What is the difference of |g:deoplete#omni_patterns| and
1123:Q: deoplete cannot complete filename after "=".
1128:Q: Deoplete does not work with vim-multiple-cursors.
1139:Q: The candidates are filtered by first character.
1145:Q: Are there any plans to support GotoDefinition feature like YouCompleteMe?
1150:Q: What about the alphabetical sorting of all entries?
```

**Comment by Shougo** [comment]
> A second low priority suggestion of me would be:
Add an index for all questions of the faq |deoplete-faq-index|. Sometimes you do not know what you are looking for. So skimming through all available questions could also be helpful to avoid questions from lazy people like me.

Rejected.
You should use unite-line or similar plugins.

**Comment by kiryph** [comment]
I can understand your objection.
In particular avoiding to blow up the documentation file size seems very reasonable. Right now the documentation has 1160 lines with 3727 words (`wc -w deoplete.nvim/doc/deoplete.txt 3727`) which will eventually increase in time.

I am not a fan of using too many plugins, but built-in `grep` can already give the user an overview of all faq. So I can agree that there is no need for adding a faq-table-of-contents.

I feel like I''ve messed this issue up 😞 . Keep up the good work 👍  despite issues such as this which do not improve the plugin in any way.
