### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by indiesquidge** [Shougo/deoplete.nvim#297]
# Problems summary
I just updated this plugin with `PlugUpdate` (using `vim-plug`). When I go into insert mode, this plugin basically explodes with errors.

I've narrowed this down to this commit: https://github.com/Shougo/deoplete.nvim/commit/0b84100ae775a6a1d1436c81a71bbeaeba241ab6

If I use this plugin with the commit before the one mentioned above, it works fine.

## Expected

Not have it blow up in my face when I go into insert mode, haha.

## Environment Information

 * OS: Mac OS X El Capitan v10.11.5

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin()

Plug 'Shougo/deoplete.nvim'

call plug#end()
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. open neovim buffer
 2. go into insert mode

## Screen shot (if possible)

<img width="1440" alt="screen shot 2016-06-21 at 4 02 41 pm" src="https://cloud.githubusercontent.com/assets/3409645/16249992/b62bd794-37ce-11e6-882e-96ed2b3a58db.png">

**Comment by rakr** [comment]
Same issue here, since the last upgrade

**Comment by HerringtonDarkholme** [comment]
I don't think this is the problem of deoplete. Can you show your neovim version?

**Comment by indiesquidge** [comment]
`NVIM 0.1.4`

**Comment by HerringtonDarkholme** [comment]
Also, can you give a `pip3 install -U neovim`? I also encounter this by updating. A reinstall of python3's neovim module might help.

**Comment by rakr** [comment]
Thanks @herringtonDarkholme `pip3 install -U nevoid' seems to work.

**Comment by Unode** [comment]
https://github.com/Shougo/deoplete.nvim/issues/292

**Comment by indiesquidge** [comment]
Seems that updating python's neovim module solves this issue. Thanks for everyone's help.

**Comment by Shougo** [comment]
deoplete requires neovim-python ver.0.18+.

**Comment by Shougo** [comment]
I have added FAQ.
