### ISSUE TITLE
Leave the preview window always closed

### ISSUE THREAD

**Issue by caneta** [Shougo/deoplete.nvim#298]
Hi @Shougo and thank you for your great work.
I'm reading the deoplete docs, but I cannot find a way to disable the automatic opening of the preview window when deoplete matches something.

I set up the automatic close with `autocmd CompleteDone * pclose!` when I choose a match, but I would like to keep it always closed and open it when I need it.

How can I reach these goals?

Thank you.

**Comment by Shougo** [comment]
`set completeopt-=preview`

**Comment by caneta** [comment]
Ok, so this is not deoplete related, but a general Vim/Neovim general settings.
But this is only half of the answer: if I have a match that I'curious to learn more about, how to open that window?
Sorry for my newbe questions, but things like that maybe deserve to be inserted in the docs...

**Comment by Shougo** [comment]
> But this is only half of the answer: if I have a match that I'curious to learn more about, how to open that window?

It cannot.  This feature is not implemented in Vim/NeoVim.

**Comment by caneta** [comment]
Ah ok, this is s a pity.
Thank you anyway!

**Comment by stsewd** [comment]
Probably this will be very useful on the faq section, can we put it?

**Comment by Shougo** [comment]
Added

**Comment by zachliu** [comment]
Instead of `set completeopt-=preview`, is it possible to toggle it dynamically?

**Comment by Shougo** [comment]
It is possible.
You should study Vim script.

**Comment by nomasprime** [comment]
Thanks @Shougo this was driving me crazy.
