### ISSUE TITLE
Reference to recently removed 'sources' folder causes exceptions loading source files 

### ISSUE THREAD

**Issue by twidxuga** [Shougo/deoplete.nvim#299]
# Problems summary

On a **new** clone of deoplete (using neovim) the following exception is constantly triggered while editing:

```
Traceback (most recent call last):
  File "/home/twidxuga/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 57, in on_event
    self.__deoplete.on_event(context)
  File "/home/twidxuga/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 375, in on_event
    self.check_recache(context)
  File "/home/twidxuga/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 363, in check_recache
    self.load_sources(context)
  File "/home/twidxuga/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 255, in load_sources
    'deoplete.source.' + filename, path).load_module()
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrapper
```

Looking at the code in `deoplete.nvim/rplugin/python3/deoplete/deoplete.py`, lines 244 to 256 I see the following:

```python
       def load_sources(self, context):
        # Load sources from runtimepath
        for path in globruntime(context['runtimepath'],
                                'rplugin/python3/deoplete/source/base.py'
                                ) + globruntime(
                                    context['runtimepath'],
                                    'rplugin/python3/deoplete/source/*.py'
                                ) + globruntime(
                                    context['runtimepath'],
                                    'rplugin/python3/deoplete/sources/*.py'
                                ):
            filename = os.path.basename(path)[: -3]
            module = importlib.machinery.SourceFileLoader(
                'deoplete.source.' + filename, path).load_module()
            self.debug(path)
```

Looks like the plugin is still trying to load modules from the `rplugin/python3/deoplete/sources` folder but the folder is no longer there.

In fact a workaround is to just comment the lines below:

```python
        for path in globruntime(context['runtimepath'],
                                'rplugin/python3/deoplete/source/base.py'
                                ) + globruntime(
                                    context['runtimepath'],
                                    'rplugin/python3/deoplete/source/*.py'
                                ):
                                # + globruntime(
                                    # context['runtimepath'],
                                    # 'rplugin/python3/deoplete/sources/*.py'
                                # ):
            filename = os.path.basename(path)[: -3]
            module = importlib.machinery.SourceFileLoader(
                'deoplete.source.' + filename, path).load_module()
            self.debug(path)
```

## Expected

No exceptions.

## Environment Information

 * OS: Linux (Ubuntu 16.04)

 * `:CheckHealth` result:

```
Checking: Python 2
  Executable: /usr/bin/python2
  Python Version: 2.7.11
  python2-neovim Version: 0.1.7 (latest: 0.1.9)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2 in the
      environment.

Checking: Python 3
  Executable: /usr/bin/python3
  Python Version: 3.5.1
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.

Checking: Remote Plugins
  Status: Up to date

```

## Neovim Python Diagnostic

- Neovim Version: NVIM v0.1.5-527-g57b56e3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Open  a file with neovim
 2. Write some text to the file to make it trigger an even handled by deoplete
 3. Save the file 

The exception may be triggered either on step 2 or 3.

**Comment by Shougo** [comment]
It is intended change.

> Looks like the plugin is still trying to load modules from the rplugin/python3/deoplete/sources folder but the folder is no longer there.

It is for compatibility.

**Comment by Shougo** [comment]
I cannot reproduce the exception with minimal init.vim.

**Comment by Shougo** [comment]
The old deoplete sources may import `deoplete.sources` directory.
It makes the error.

**Comment by bruschill** [comment]
@twidxuga I was getting the same error this morning, and I fixed it by doing the following:

- commented out `Plug 'Shougo/deoplete.nvim'` in `init.vim`
- reloaded `init.vim`
- ran `:PlugClean`, hitting `y` when it asks me if I wanted to delete the plugin
- uncommented `Plug 'Shougo/deoplete.nvim'` in `init.vim`
- reloaded `init.vim`
- ran `:PlugInstall`
- ran `:UpdateRemotePlugins`
- restarted `nvim`

Hopefully this fixes it for you too.

**Comment by Shougo** [comment]
Old deoplete-ternjs has the problem.  You should update it.
https://github.com/carlitux/deoplete-ternjs/pull/23
