### ISSUE TITLE
File path completion conflicts with js completion

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#30]
Not sure if this would be an issue with deoplete or my omnifun, but when using 

```
<script src=""></script>
```
and trying to autocomplete the path, I end up getting completion for js code, not the path.

I can temporarily override this by using `c-x c-f`, but if you delete a character, code completion kicks back in.

I have the latest release of deoplete and neoinclude. 
This is my omnifunc for javascript

```
  autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
```

**Comment by Shougo** [comment]
Unfortunatelly, it is feature.
omnifunc(`g:deoplete#omni_patterns`) is higher priority than deoplete normal completion(for example, file path completion).

**Comment by Shougo** [comment]
@mhartington You can use file path completion in the script.
You must input "/".

<script src="./example_path"></script>
