### ISSUE TITLE
Ignore file extension

### ISSUE THREAD

**Issue by billyvg** [Shougo/deoplete.nvim#300]
Is there a way to ignore file extensions when auto completing a file?

**Comment by Shougo** [comment]
Why do you need this feature?
You should install neoinclude.
https://github.com/Shougo/neoinclude.vim

**Comment by billyvg** [comment]
@Shougo Sorry this notification got lost on me.

Example, I have a file `foo.js`, I would like autocomplete to leave out file extension when I select the file.

Currently it becomes
`require('./foo.js');`

I would like
`require('./foo');`

**Comment by Shougo** [comment]
neoinclude supports the feature.
Please use neoinclude.
`:help includeexpr`

**Comment by kristijanhusak** [comment]
@Shougo , i know neoinclude supports this feature, but it's really a hassle to set up (at least it was to me).
Can't we just use a converter that will do that for us, and optionally use it ?
`call deoplete#custom#source('file', 'converters', ['converter_strip_file_ext'])`

I would contribute to add this converter.

**Comment by Shougo** [comment]
Sorry, I don't want to include it in deoplete.
Because it is not so useful.

Of course, you can create the converter and use it.

**Comment by kristijanhusak** [comment]
@Shougo ok, thanks.

@billyvg if you are interested, i added the converter as part of my vim plugin https://github.com/kristijanhusak/vim-js-file-import
