### ISSUE TITLE
deoplete getting triggered after equals sign(=)

### ISSUE THREAD

**Issue by eternalfool** [Shougo/deoplete.nvim#301]
# Problems summary
I use deoplete/jedi for python autocompletion. It gets triggered after the equals sign.
Screenshot of the problem http://imgur.com/UMp21ko
This obscures the screen unnecessarily.

## Expected
There should be no popup on '='.
This is the same as in the deoplete demo gifs.

## Environment Information
I have the following added to be vimrc
`inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"`

My entire vimconfig is https://github.com/eternalfool/dotfiles/blob/master/my_configs.vim although I don't think it's necessary.

 * OS:
Ubuntu

**Comment by Shougo** [comment]
This is deoplete-jedi problem by https://github.com/zchee/deoplete-jedi/commit/0ee56be2a18c46429b04598fda64215802778099
@tweekmonster Ping.

**Comment by tweekmonster** [comment]
@eternalfool Sorry, I ignored this issue and didn't know it had to do with `deoplete-jedi`!  It'll be fixed soon.
