### ISSUE TITLE
How do you actually choose from the autocomplete options effectively?

### ISSUE THREAD

**Issue by nikitavoloboev** [Shougo/deoplete.nvim#302]
# Problems summary
I understand that you can use arrows to go through the options provided but that doesn't seem to be a very effective solution. Also is it possible to extend the suggest autocomplete option with tab?

## Expected
Being able to expand the suggested autocomplete options with tab or perhaps some other key. Being able to scroll through the options in an efficient manner.

## Environment Information
OS: macOS ver. 10.11.5

Thank you for any help.

**Comment by Shougo** [comment]
```vim
	" <TAB>: completion.
	inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```

**Comment by haasn** [comment]
There's also supertab

**Comment by uri** [comment]
You can also use C-n and C-p

**Comment by creamov** [comment]
In addition to comment from @Shougo...

Remap `Tab` to next and `Shift`+`Tab` to previous:

```vim
" <Tab>: completion
inoremap <expr><Tab>  pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr><S-Tab>  pumvisible() ? "\<C-p>" : "\<S-Tab>"
```
