### ISSUE TITLE
Golang: autocompletion is not triggered upon typing variable/function

### ISSUE THREAD

**Issue by dobegor** [Shougo/deoplete.nvim#305]
I am using `neovim` 0.1.5-dev, latest `deoplete.nvim` and `deoplete.go`.
Autocompletion works except when I type variable/function - I have to trigger it manually via `<C-x><C-o>`.

Here is my `init.vim`:[pastebin](http://pastebin.com/2m9asPm3).
Don't know if it's an issue with `deoplete-go` or `deoplete.nvim`.

**Comment by zchee** [comment]
@dobegor Hi, I'm deoplete-go author.

**Maybe** caused by your environment because will work my settings.
but I will help it responsibly.

> Autocompletion works except when I type variable/function - I have to trigger it manually via <C-x><C-o>.

It seems your call omnifunc set by vim-go internal. Displays completion list are not provided by deoplete.nvim.

Just in case, deoplete's other source such as `buffer` is works fine?

**Comment by dobegor** [comment]
@zchee 
It's ignored usually, but yes buffer source works fine for me if I comment the ignore_sources line.

**Comment by zchee** [comment]
@dobegor OK.
Maybe this problem not related deoplete.nvim.

but vim-go's omnifunc also use the gocode. Hmm...
I will see your init.vim, and look for the cause.
Please moments

**Comment by Shougo** [comment]
@dobegor Your init.vim seems long.  Can you upload the init.vim less than 50 lines?

**Comment by zchee** [comment]
@dobegor and, Please test use https://github.com/zchee/deoplete-go/blob/master/tests/deoplete-go.vim and https://github.com/zchee/deoplete-go/blob/master/tests/fmt.go if you have time.

```bash
nvim -u /path/to/deoplete-go.vim tests/fmt.go
```
and type any word such as `fmt.`.

**Note** that would needs fix that path.

```vim
  " vim-plug
  set runtimepath+=$XDG_CONFIG_HOME/nvim/plugged/deoplete.nvim
  set runtimepath+=$XDG_CONFIG_HOME/nvim/plugged/deoplete-go
```

**Comment by dobegor** [comment]
@zchee using the provided .nvim file I have no autocompletion nor omnifunc set at all (i.e. C-x C-o doesn't work too).

@Shougo sorry, please look lines 27-38, 181-182 as those are only lines related to deoplete/deoplete.go.

**Comment by dobegor** [comment]
I don't think it's ignoring the source.
Autocompletion after inserting . works just fine. 
@zchee setting runtimepath didn't help too.

**Comment by zchee** [comment]
@dobegor 
> using the provided .nvim file I have no autocompletion nor omnifunc set at all (i.e. C-x C-o doesn't work too).

No, no. `omnifunc` is provided(automatically set) vim-go. There no vim-go on your runtimepath when to use `deoplete-go.vim`, So `<C-x><C-o>` does not work is normal.

deoplete.nvim and deoplete-go do not use `omnifunc`.

Also, that tiny init.vim must work correctly in any environment. Hmm..

**Comment by Shougo** [comment]
I have tested it.
Hm it seems reproduced.

**Comment by dobegor** [comment]
@Shougo What should I do next? Any additional info required?

**Comment by Shougo** [comment]
I get it.  It is not deoplete problem.

Works:
```
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/deoplete-go/

let g:deoplete#enable_at_startup = 1
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'member', 'file', 'neosnippet']
" let g:deoplete#sources#go#sort_class = ['func', 'type', 'var', 'const']
```

Does not work:
```
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/deoplete-go/

let g:deoplete#enable_at_startup = 1
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'member', 'file', 'neosnippet']
let g:deoplete#sources#go#sort_class = ['func', 'type', 'var', 'const']
```

It is `g:deoplete#sources#go#sort_class` problem.
Please create new issue in deoplete-go repository.

**Comment by dobegor** [comment]
@Shougo 
Thanks, works for me now.
@zchee 
I've created [this](https://github.com/zchee/deoplete-go/issues/65) issue.
