### ISSUE TITLE
.-rplugin~ File

### ISSUE THREAD

**Issue by Jumblemuddle** [Shougo/deoplete.nvim#306]
# Problems summary

Upon :UpdateRemotePlugins, a `.-rplugin~` file is created in the current working directory.

## Expected

This file should be somewhere in my home directory, not in each individual directory

## Environment Information

 * OS: NixOs

**Comment by tweekmonster** [comment]
This was brought up on Reddit: https://www.reddit.com/r/neovim/comments/4s0uhj/how_to_updateremoteplugins_just_once_globally/d56e3me

It's a defect in Neovim.  There's a fix being worked on, but you'll have to go with how he's solving the issue in the mean time.

Link to PR: https://github.com/neovim/neovim/pull/5050

**Comment by Shougo** [comment]
This is not deoplete problem.
