### ISSUE TITLE
Suggestions from ctags don't appear

### ISSUE THREAD

**Issue by lowski** [Shougo/deoplete.nvim#309]
# Problems summary

Hi,
I have a problem with `tag` source for my `Ruby` files - `deoplete` only display suggestions from buffers.

Here are my `deoplete` settings. I generated `ctags` using [universal-ctags](https://github.com/universal-ctags/ctags). I know they are working because when I type `g <c-[>` vim correctly opens the file.

```
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources._ = ['buffer', 'tag']
```

## Expected

I would expect to see suggestions based on the `ctags` file as well.

## Environment Information

 * OS: OS X
 * Neoivm: 0.1.4

**Comment by tweekmonster** [comment]
You probably need to increase the size limit on `deoplete#tag#cache_limit_size`.  The default is `500000` which is ~500KiB.  Add another zero to it to make it ~5MiB:

```vim
let deoplete#tag#cache_limit_size = 5000000
```

**Comment by lowski** [comment]
Thanks @tweekmonster - that was it.

Problem solved, can be closed.

**Comment by lowski** [comment]
I've created PR to include that in the README #311
