### ISSUE TITLE
error caught in async handler 'deoplete_on_event...

### ISSUE THREAD

**Issue by pysnow530** [Shougo/deoplete.nvim#312]
# Problems summary

Hello, when I update from my july 7 to just now version, this error occured when I enter insert mode:

> error caught in async handler 'deoplete_on_event [{'dict__dictionary': '', 'complete_str': '', 'max_menu_width': 118, 'delay': 50, 'event': '', 'cwd': '/Users/jianming.wu/projs/d
> otfiles', 'ignorecase': 0, 'encoding': 'utf-8', 'bufvars': {}, 'sources': [], 'start_complete': '\udc80\udcfdR(deoplete_start_complete)', 'position': [0, 1, 1, 0], 'input': '', '
> custom': {'_': {}}, 'rpc': 'deoplete_on_event', 'omni__omnifunc': '', 'bufname': '', 'changedtick': 2, 'filetype': 'nothing', 'camelcase': 0, 'runtimepath': '/Users/jianming.wu/.
> config/nvim,/Users/jianming.wu/.vim/bundle/Vundle.vim,/Users/jianming.wu/.vim/bundle/snipmate.vim,/Users/jianming.wu/.vim/bundle/vim-python-pep8-indent,/Users/jianming.wu/.vim/bu
> ndle/emmet-vim,/Users/jianming.wu/.vim/bundle/ctrlp.vim,/Users/jianming.wu/.vim/bundle/vim-gitgutter,/Users/jianming.wu/.vim/bundle/vim-fugitive,/Users/jianming.wu/.vim/bundle/le
> xima.vim,/Users/jianming.wu/.vim/bundle/nerdtree,/Users/jianming.wu/.vim/bundle/tagbar,/Users/jianming.wu/.vim/bundle/vim-github-colorscheme,/Users/jianming.wu/.vim/bundle/nerdco
> mmenter,/Users/jianming.wu/.vim/bundle/deoplete.nvim,/Users/jianming.wu/.vim/bundle/neosnippet.vim,/Users/jianming.wu/.vim/bundle/neosnippet-snippets,/Users/jianming.wu/.vim/bund
> le/neo-django,/etc/xdg/nvim,/Users/jianming.wu/.local/share/nvim/site,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/0.1.4/share/nvim/runtime,/usr/share
> /nvim/site/after,/usr/local/share/nvim/site/after,/Users/jianming.wu/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/jianming.wu/.config/nvim/after,/Users/jianming.wu/.vi
> m/bundle/Vundle.vim,/Users/jianming.wu/.vim/bundle/Vundle.vim/after,/Users/jianming.wu/.vim/bundle/snipmate.vim/after,/Users/jianming.wu/.vim/bundle/vim-python-pep8-indent/after,
> /Users/jianming.wu/.vim/bundle/emmet-vim/after,/Users/jianming.wu/.vim/bundle/ctrlp.vim/after,/Users/jianming.wu/.vim/bundle/vim-gitgutter/after,/Users/jianming.wu/.vim/bundle/vi
> m-fugitive/after,/Users/jianming.wu/.vim/bundle/lexima.vim/after,/Users/jianming.wu/.vim/bundle/nerdtree/after,/Users/jianming.wu/.vim/bundle/tagbar/after,/Users/jianming.wu/.vim
> /bundle/vim-github-colorscheme/after,/Users/jianming.wu/.vim/bundle/nerdcommenter/after,/Users/jianming.wu/.vim/bundle/deoplete.nvim/after,/Users/jianming.wu/.vim/bundle/neosnipp
> et.vim/after,/Users/jianming.wu/.vim/bundle/neosnippet-snippets/after,/Users/jianming.wu/.vim/bundle/neo-django/after', 'bufnr': 1, 'filetypes': ['nothing'], 'vars': {'deoplete#s
> ources': {}, 'deoplete#enable_ignore_case': 0, 'deoplete#delimiters': ['/', '.', '::', ':', '#'], 'deoplete#enable_at_startup': 1, 'deoplete#omni#input_patterns': {}, 'deoplete#_
> rank': {}, 'deoplete#auto_complete_delay': 50, 'deoplete#member#prefix_patterns': {}, 'deoplete#enable_refresh_always': 0, 'deoplete#ignore_sources': {}, 'deoplete#auto_complete_
> start_length': 2, 'deoplete#max_menu_width': 40, 'deoplete#omni#functions': {}, 'deoplete#enable_smart_case': 0, 'deoplete#keyword_patterns': {}, 'deoplete#max_list': 100, 'deopl
> ete#_context': {}, 'deoplete#enable_camel_case': 0, 'deoplete#enable_profile': 0, 'deoplete#disable_auto_complete': 0, 'deoplete#omni_patterns': {}, 'deoplete#_omni_patterns': {'
> xml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'html': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'markdown': ['<'
> , '<[^>]*\\s[[:alnum:]-]*']}, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'deoplete#_channel_id': 1, 'deoplete#_neovim_python_version': '0.1.9', 'deoplete#max_abbr_widt
> h': 80}, 'max_abbr_width': 118, 'next_input': '', 'smartcase': 0, 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_À-ÿ]*'}]'
> Traceback (most recent call last):
>   File "/Users/jianming.wu/.config/nvim/.dein/rplugin/python3/deoplete/__init__.py", line 57, in on_event
>     self.__deoplete.on_event(context)
>   File "/Users/jianming.wu/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 375, in on_event
>     self.check_recache(context)
>   File "/Users/jianming.wu/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 363, in check_recache
>     self.load_sources(context)
>   File "/Users/jianming.wu/.config/nvim/.dein/rplugin/python3/deoplete/deoplete.py", line 260, in load_sources
>     source = module.Source(self.__vim)
>   File "/Users/jianming.wu/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/source/member.py", line 28, in __init__
>     '_', '\.')
> TypeError: set_pattern() missing 1 required positional argument: 'pattern'
> 请按 ENTER 或其它命令继续

**Comment by Shougo** [comment]
Your deoplete seems broken.
Please reinstall deoplete.

**Comment by Shougo** [comment]
And you need execute `call dein#recache_runtime_path()`.

**Comment by pysnow530** [comment]
This occured under Vundle.

When I checkout 0a6d152895c36906a13409f53d20621541f2901a, all is ok.

When I checkout the next commit cc2c51821e1dfaa633ca5549633ca6496fa718c9, it happens.

**Comment by zchee** [comment]
@pysnow530 Hi,

First of all, Why do you use together of dein and Vundle? (Sorry if there are any reasons)

If you have two deoplete.nvim in your `runtimepath`(dein and Vundle), Please try to delete one of deoplete.
Or, if
`/Users/jianming.wu/.vim/bundle/deoplete.nvim/rplugin/python3/deoplete/source/member.py`
was carried(copy&paste) from deoplete.nvim, it seems old.
Please update to latest.

**Comment by pysnow530** [comment]
> Why do you use together of dein and Vundle

No, I just use Vundle, no dein.

> If you have two deoplete.nvim in your runtimepath

Just one, It's /Users/jianming.wu/.vim/bundle/deoplete.nvim and /Users/jianming.wu/.vim/bundle/deoplete.nvim/after.

> if member.py was carried(copy&paste) from deoplete.nvim

No, I just cloned and use master branch. I use the newest version and it still crash.

**Comment by zchee** [comment]
@pysnow530 
> No, I just use Vundle, no dein.

Oh, but your post error has that line.
> File "/Users/jianming.wu/.config/nvim/.dein/rplugin/python3/deoplete/init.py", line 57, in on_event

it seems to `dein.vim` cache directory.
WDYT?

**Comment by pysnow530** [comment]
I delete the .dein directory, the problem fixed. Thank you, zchee, thank you very much.

Now my problem is: _I used dein before, but dein is not in my runtimepath already, why .dein/...init.py was used?_

**Comment by zchee** [comment]
@pysnow530 
> I delete the .dein directory, the problem fixed. Thank you, zchee, thank you very much.
🎉 

> Now my problem is: I used dein before, but dein is not in my runtimepath already, why .dein/...init.py was used?

Maybe, you're `.init.vim-rplugin~` is broken. It does not correspond latest your `init.vim`.
It needs to self-reload(`:UpdateRemotePlugins`).
`Vundle` does not automatically reload, but `dein.vim` has auto reloading feature :)

Close.

**Comment by arkadyt** [comment]
Confirming the solution, had to delete `~/.cache/vimfiles/` containing `.dein` folder and everything worked like a charm.
Thanks, @pysnow530!
