### ISSUE TITLE
Question about cross-filetype completion

### ISSUE THREAD

**Issue by noraesae** [Shougo/deoplete.nvim#313]
Hi,

First of all, thank you very much for this wonderful plugin. I'm really happy to use deoplete.nvim everyday.

I'm not familiar with vim internals and this may be a stupid question, but is there anyway to enable autocompletion for tabs with different file types? For example, I'd like to use autocomplete from `.js` to `.html` with `<script>` tags, or vice versa. Is there any setting for this case?

Thanks in advance.

Cheers,

**Comment by Shougo** [comment]
Please install https://github.com/Shougo/context_filetype.vim for it.

**Comment by noraesae** [comment]
It works! Thanks.
