### ISSUE TITLE
What's the correct way to autocomplete?

### ISSUE THREAD

**Issue by Davidslv** [Shougo/deoplete.nvim#314]
# Problems summary

When I type something like `html` there's an option that appears.
I then press down and enter but I was expecting somehow to start an html5 template.
This is just one example, I've been wondering if I have been using your plugin correctly?

## Screenshot

![screen shot 2016-07-20 at 22 11 18](https://cloud.githubusercontent.com/assets/136777/17037742/428db266-4f8a-11e6-8f49-072981d142f1.png)

Thank you

**Comment by Shougo** [comment]
```vim
	imap <expr><CR> pumvisible() && neosnippet#expandable() ?
	\ "\<Plug>(neosnippet_expand)" : "\<CR>"
```
