### ISSUE TITLE
deoplete.nvim is not registered as Neovim remote plugins

### ISSUE THREAD

**Issue by Alok** [Shougo/deoplete.nvim#315]
# Problems summary

I get this error in `:messages`:
```
[deoplete] deoplete.nvim is not registered as Neovim remote plugins.
[deoplete] Please execute :UpdateRemotePlugins command and restart Neovim.
```

Deoplete then fails to work.

## Expected
It shouldn't give any error, as I did run that command.

## Environment Information

 * OS: OSX 10.11.4

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

https://gist.github.com/4850988094b578755c271dbd6def0461

## Neovim Python Diagnostic

- Neovim Version: latest build from git

## Python versions visible to Neovim
2, 3
### 'python' info from /usr/local/bin/nvim

```
Checking: Python 2
  Executable: /usr/bin/python
  Python Version: 2.7.10
  python-neovim Version: 0.1.9 (up to date)
  Messages:
    * Using: g:python_host_prog = "/usr/bin/python"
```
### 'python3' info from /usr/local/bin/nvim
```
Checking: Python 3
  Executable: /usr/local/bin/python3
  Python Version: 3.5.2
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Using: g:python3_host_prog = "/usr/local/bin/python3"
```

## Python versions visible in the current shell
```
- **python** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
- **python3** version: `Python 3.5.1`
  - **neovim** version: `neovim (0.1.7)
neovim-gui (0.1.2)
neovim-remote (1.1.3)`
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

nvim -u minimal.vim

**Comment by Shougo** [comment]
Please upload the minimal init.vim and the reproduce ways.

Note:  I will close the issue without the minimal init.vim and the reproduce ways

**Comment by Shougo** [comment]
And please upload the log file.
It is important for the problem.

**Comment by Alok** [comment]
I ended up running `git bisect` and found that reinstalling `iron.nvim` fixed the issue, somehow.

**Comment by Shougo** [comment]
OK
