### ISSUE TITLE
Sources for Ruby language

### ISSUE THREAD

**Issue by fishbullet** [Shougo/deoplete.nvim#318]
Hello there, I create a source for the ruby lang. 

Also I want to create the PR for add source to the documentation. 
 
Do you accept PR to improve the documentation with links? 

Source
https://github.com/fishbullet/deoplete-ruby 

:walking:

**Comment by Shougo** [comment]
Nice.  I will try it later.

**Comment by Shougo** [comment]
Thank you.  I have added it.

**Comment by Shougo** [comment]
It should be good if it completes the omni candidates like vim-monster.

**Comment by fishbullet** [comment]
Cheers! 
:+1: 
I will improve that plugin, add a normal caching, also create a Rails version.
