### ISSUE TITLE
`UpdateRemotePlugins` always showing up

### ISSUE THREAD

**Issue by jseaidou** [Shougo/deoplete.nvim#319]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Whenever starting neovim, I get the following message: 
```
[deoplete] Please execute :UpdateRemotePlugins command and restart neovim
```
I am aware of #160 and #167 but the resolutions for those hasn't been any help. 

## Environment Information

 * OS: OSX 10.11.4

## Neovim Python Diagnostic

- Neovim Version: NVIM 0.1.5-dev

## Python versions visible to Neovim
python2 and python3

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
" Deoplete
call plug#begin('~/.config/nvim/bundle')

function! DoRemote(arg)
    UpdateRemotePlugins
endfunction
Plug 'Shougo/deoplete.nvim', {'do': function('DoRemote')}
call plug#end()


call remote#host#RegisterPlugin('python3', '~/.config/nvim/bundle/deoplete.nvim/rplugin/python3/deoplete.py', [
      \ {'sync': 1, 'name': 'DeopleteInitializePython', 'type': 'command', 'opts': {}},
     \ ])
set runtimepath+=~/.config/nvim/bundle/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

```

## The reproduce ways from neovim starting (Required!)

 1. Start neovim
 2. Wait up to 5 seconds
 3. Message shows up

**Comment by Shougo** [comment]
Real minimal init.vim.

```vim
set runtimepath+=~/.config/nvim/bundle/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

Please don't call `remote#host#RegisterPlugin()` manually.

I have tested your minmal init.vim, but I cannot reproduce it.

Please upload the log file.  It is needed.

Please upload `:CheckHealth` result.

**Comment by Shougo** [comment]
And please upload  `~/.nvim/.init.vim-rplugin~`  file.

I think your rplugin file is invalid.

**Comment by jseaidou** [comment]
Testing with the minimal init.vim you posted, here are my results. 

```
:CheckHealth

Checking: Python 2
  Executable: /usr/bin/python2.7
  Python Version: 2.7.10
  python2.7-neovim Version: 0.1.7 (latest: 0.1.9)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2.7 in
      the environment.

Checking: Python 3
  Executable: /usr/local/bin/python3
  Python Version: 3.5.2
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.

Checking: Ruby
  Ruby Version: ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin12.0]
  Host Executable: not found
  Host Version: not found
  Messages:
    * Suggestion: Install the neovim RubyGem using `gem install neovim`.

Checking: Remote Plugins
  Status: Out of date
  Messages:
    * "deoplete.nvim" is not registered.
    * "deoplete.nvim" is not registered.
    * Run :UpdateRemotePlugins
```
`~/.nvim/.init.vim-rplugin~`
```
" ruby plugins

" python plugins
```

gist for log file can be found here: https://gist.github.com/jseaidou/f0cd800cc0de87d3125b48f57b5503e8

Thanks for the help in advance!

**Comment by Shougo** [comment]
OK.  It seems not deoplete problem.
Please report it in neovim issues.
