### ISSUE TITLE
Very strange behavior with periods _not at beginning of line_ in python files.

### ISSUE THREAD

**Issue by genkimarshall** [Shougo/deoplete.nvim#32]
Environment: Arch Linux x64
Neovim version: 0.r3836.90ef218-1

Minimal `nvimrc` testing with:
```vim
" -- https://github.com/junegunn/vim-plug -- "
call plug#begin()
Plug 'Shougo/deoplete.nvim'
call plug#end()

" Use deoplete.
let g:deoplete#enable_at_startup = 1
```

[If you believe the plugin system is the problem, let me know, and I'll try without. However, I wouldn't think it would be.]

Example steps to reproduce:
1. `$ nvim test.py`
2. Go to insert mode and insert a period. Notice that nothing changes.
3. Go to the next line, and type any character (e.g. `a`), then type a period `.`.

Error appearing at bottom:
```
Error: Required vim compiled with +python
E117: Unknown function: pythoncomplete#Complete
```

Log file: https://gist.github.com/genkimarshall/307ee21ddbd5c38ac7fd

After ignoring and continuing, I notice it only ever reappears if in normal mode, you press `a` while your cursor is on a period _not at the beginning of the line_, or you press `A` while your cursor is on a line in which a period is _not at the beginning of the line_.

EDIT: I notice it also happens if you press `i` in normal mode when your character is on the same line as, but to the right of, a period that is not at the beginning of the line.

I don't find this error appearing in any other situation. Even in non-python files this error does not happen. I know this is very strange, I almost feel embarassed to post it because it is so weird that I feel I must be doing something wrong. Please let me know if you cannot reproduce and I will keep trying or ignore it.

Thanks for your time.

**Comment by Shougo** [comment]
You must install neovim python module.

It is not deoplete problem.

```
$ sudo pip install neovim
```

**Comment by genkimarshall** [comment]
I originally had:
`:echo has("python3")` return `0` on initial configuration, and so I did
`$ sudo pip install neovim`, at which point `:echo has("python3")` ended
up returning `1` from then on, so I don't believe that is the issue.

However, it sounds like it's not being reproducible, so I will just see
if I can solve it on my own time.

Thanks for taking a look.

**Comment by Shougo** [comment]
I think you must enable *Python2* interface.
`$ sudo pip2 install neovim`
To use python completion, Python2 interface is needed.
You can check it by `echo has('python')`.

**Comment by genkimarshall** [comment]
Ah, I see. After doing so, all seems to be working now.
I was under the impression before that all that was needed was a Python3 interface.
Thank you so much for your help and the great plugin.
