### ISSUE TITLE
deoplete#undo_completion() does not work

### ISSUE THREAD

**Issue by vbauerster** [Shougo/deoplete.nvim#320]
# Problems summary
Invoking deoplete#undo_completion() produces some errors.

## Expected
Invoking deoplete#undo_completion(), should work.

## Environment Information

 * OS: Mac OS X El Capitan

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```
Checking: Python 2
  Executable: /usr/bin/python2.7
  Python Version: 2.7.10
  python2.7-neovim Version: 0.1.8 (latest: 0.1.9)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2.7 in
      the environment.

Checking: Python 3
  Executable: /usr/local/bin/python3
  Python Version: 3.5.2
  python3-neovim Version: 0.1.8 (latest: 0.1.9)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.

Checking: Ruby
  Ruby Version: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
  Host Executable: not found
  Host Version: not found
  Messages:
    * Suggestion: Install the neovim RubyGem using `gem install neovim`.

Checking: Remote Plugins
  Status: Up to date

```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
inoremap <expr><C-z> deoplete#undo_completion()
```

## The reproduce ways from neovim starting (Required!)

Enter insert mode, have deoplete to complete something, then press CTRL-Z while still in insert mode.

## Screen shot (if possible)
![error](https://s25.postimg.org/7n3pvk0y7/Screen_Shot_2016_07_29_at_19_10_23.png)

**Comment by Shougo** [comment]
Fixed.

**Comment by vbauerster** [comment]
Thank you!
