### ISSUE TITLE
Detect UltiSnips snippets in completion menu after delimiters

### ISSUE THREAD

**Issue by rusty1s** [Shougo/deoplete.nvim#321]
# Problems summary

It seems that for me, snippets from UltiSnips don't show up in the completion menu after a delimiter like `.` or `(` although the snippet has the `i` option for in-word expansion. Is there a way to configure deoplete to do so?

I tried `call deoplete#custom#set('ultisnips', 'input_pattern', '[^. \t]\w*')` but it didn't have any effect.

## minimal init.vim

```vim
call plug#begin('~/.config/nvim/cache')
Plug 'Shougo/deoplete.nvim'
Plug 'SirVer/ultisnips'
call plug#end()

set runtimepath+=~/.config/nvim/cache/deoplete.nvim/
call deoplete#enable()

let g:deoplete#sources={}
let g:deoplete#sources._=['buffer', 'file', 'ultisnips']
```

**Comment by Shougo** [comment]
Please create the issue in UltiSnips repository.
