### ISSUE TITLE
common language server protocol

### ISSUE THREAD

**Issue by prabirshrestha** [Shougo/deoplete.nvim#324]
VsCode uses a common protocol for language servers which can be found at https://github.com/Microsoft/language-server-protocol. The announcement at 
https://code.visualstudio.com/blogs/2016/06/27/common-language-protocol

It is currently used by TypeScript and OmniSharp. I wonder if you have thought of implementing the protocol in deoplete.vim.

**Comment by Shougo** [comment]
No plan.
You can implement it!
