### ISSUE TITLE
Refactor question

### ISSUE THREAD

**Issue by tweekmonster** [Shougo/deoplete.nvim#325]
Hello @Shougo!  I want to work on refactoring a little bit.  I wanted to know if it's okay to refactor the imports so they match the PEP8 spec: https://github.com/mumumu/pep8-ja/blob/master/index.rst#import

**Comment by Shougo** [comment]
Please upload the fix example.

**Comment by tweekmonster** [comment]
Here is an example: https://github.com/tweekmonster/deoplete.nvim/commit/0c6cd91b623490fc5d1f5d6362716094809e3b7c

I do this often, so I made a plugin for it: https://github.com/tweekmonster/impsort.vim

I think it looks nicer and it's easier to see what the project vs stdlib vs third party imports are.

**Comment by Shougo** [comment]
It seems nice.
Please create new PR.
