### ISSUE TITLE
`deoplete#enable_logging()` happens too late in the init process.

### ISSUE THREAD

**Issue by tweekmonster** [Shougo/deoplete.nvim#327]
Early log messages are lost.

The flow is:

- `deoplete#enable_logging()`
- `deoplete#initialize()`
- `deoplete#init#_initialize()`
- `deoplete#init#_enable()`
- `deoplete#handler#_init()`
- **Note:** Any logging below this will be lost because `deoplete_enable_logging` hasn't been called yet.
- `s:on_event('')`
- `deoplete_on_event` (RPC)
- `Deoplete.check_recache()`
- `Deoplete.load_sources()`
- `source = Source()`
- `...`
- `source.on_init()`
- `...`

**Comment by Shougo** [comment]
It should be fixed.
