### ISSUE TITLE
[Consult] Odd behaviour

### ISSUE THREAD

**Issue by EPadronU** [Shougo/deoplete.nvim#33]
Hi, everyone,

I just replaced `neocomplcache` with `deoplete`. I know that `deoplete` is still in alfa and is not aimed to production yet but I'm experiencing some odd behavior and I would like to ensure it is not caused by a wrong configuration from my side. The following is my current configuration:

```vim
" Use deoplete.
let g:deoplete#enable_at_startup = 1

" Not ignore the upper- and lower-case
let g:deoplete#enable_ignore_case = 1

" Define keyword
if !exists('g:deoplete#keyword_patterns')
    let g:deoplete#keyword_patterns = {}
endif

let g:deoplete#keyword_patterns.default = '[a-zA-Z_]\w{2,}?'
let g:deoplete#keyword_patterns.groovy = '[a-zA-Z_$]\w{2,}?'

" <CR>: close popup and save indent
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>

function! s:my_cr_function()
  return pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
endfunction

" <TAB>: completion
inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"

" Close popup by <Space>
inoremap <expr><Space> pumvisible() ? deoplete#mappings#close_popup() : "\<Space>"

" Enable omni-completion
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS

autocmd FileType html,html.handlebars,markdown setlocal omnifunc=htmlcomplete#CompleteTags

autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS

autocmd FileType python setlocal omnifunc=pythoncomplete#Complete

autocmd FileType r setlocal omnifunc=CompleteR

" omnifunc-completion patterns
if !exists('g:deoplete#omni_patterns')
  let g:deoplete#omni_patterns = {}
endif

let g:deoplete#omni_patterns.groovy = '[^.\s*\t]\.\w*?'

let g:deoplete#omni_patterns.java = '[^.\s*\t]\.\w*?'

let g:deoplete#omni_patterns.r = '[a-zA-Z_]\w*?'

" Define ctags' arguments
let g:deoplete#ctags_arguments_list = {
\    'python': '--python-kinds=-i -o .vimtags',
\}
```

The mentioned odd behavior is hard to explain, I'll record a video if necessary.

Thanks for your time in advance.

**Comment by HerringtonDarkholme** [comment]
I cannot understand what you say. You could minimize your nvimrc to figure out what causes odd behavior, though. In this case, there are plenty of unnecessary configurations and completion sources. 

You should comment out unrelated configs and keep the minimal config to reproduce bug.

**Comment by EPadronU** [comment]
I'll try to explain the *bug* the best I can: when I type some word, `deoplete` try to put in the buffer the first match and then it go back to the word I just typed, this is more visible when I delete a character (all of this in insert mode). For example: `mo_` ~ it jumps to ~> `Models_` ~ an then go back to the word ~> `mod_` showing the window with all the matches for the word `mo`. To be notice: when I type a third character this doesn't happen but when I use `<BS>` it happens every time until the word is one character long. 

By the way, I followed your advise and it still happens with only this two lines:

```vim
let g:deoplete#enable_at_startup = 1
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
```

**Comment by EPadronU** [comment]
Ah! And when `deoplete` doesn't find a match the cursor start flickering like crazy together with a message in the command-line that says `Pattern not found`.

**Comment by Numkil** [comment]
I'm also getting cursor flickering and hundreds of "Pattern not found" messages. I don't get the other error though. I will investigate with clean vimrc and make a seperate issue if I find something interesting.

**Comment by Shougo** [comment]
@Numkil @EPadronU Please read the documentation.

```
Q: I want to get quiet messages in auto completion.

A: You can disable the messages through the 'shortmess' option.
>
	if has("patch-7.4.314")
	  set shortmess+=c
	endif
<
```

@EPadronU You should map `<C-h>` and `<BS>` keys.

```vim
		inoremap <expr><C-h>
		\ deolete#mappings#smart_close_popup()."\<C-h>"
		inoremap <expr><BS>
		\ deoplete#mappings#smart_close_popup()."\<C-h>"
```

@EPadronU And please read the CONTRIBUTING.md.
I cannot understand/test your problem.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by EPadronU** [comment]
After adding those two maps all my problems has gone. Thanks a lot @Shougo and sorry for not have given the proper details about my problems as described in `CONTRIBUTING.md`. I thought they was caused by me and not by the plugin,  and I was right xD

Btw, now the last match is been inserted. Is this to be expected?

**Comment by EPadronU** [comment]
NVM, the last one was caused by `rope` (`python-mode`) auto-completing without my knowledge.
