### ISSUE TITLE
Errors in recent updates when debugging source

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#333]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

Not sure when this showed up, but it's only visible with debug enabled. 
In working on my source, I get a vim error that makes working impossible (as it gets thrown every time you type)

See the error below
<details>
```vim;
Error detected while processing function deoplete#enable[4]..deoplete#init#_enable[1]..deoplete#handler#_init[17]..<SNR>220_on_event[1]..deoplete#init#_context[13]..deoplete#util#get_buffer_config:
line    7:
E121: Undefined variable: g:deoplete#sources
Error detected while processing function deoplete#enable[4]..deoplete#init#_enable[1]..deoplete#handler#_init[17]..<SNR>220_on_event[1]..deoplete#init#_context[13]..deoplete#util#get_buffer_config:
line    7:
E116: Invalid arguments for function has_key({a:user_var}, a:filetype) && !has_key(eval(a:default_var), a:filetype) ? '_' : a:filetype
Error detected while processing function deoplete#enable[4]..deoplete#init#_enable[1]..deoplete#handler#_init[17]..<SNR>220_on_event[1]..deoplete#init#_context[13]..deoplete#util#get_buffer_config:
line    7:
E15: Invalid expression: !has_key({a:user_var}, a:filetype) && !has_key(eval(a:default_var), a:filetype) ? '_' : a:filetype
Error detected while processing function deoplete#enable[4]..deoplete#init#_enable[1]..deoplete#handler#_init[17]..<SNR>220_on_event[1]..deoplete#init#_context:
line   13:
E706: Variable type mismatch for: sources
```
</details>

## Expected
No error 😁 

## Environment Information

 * OS: osx

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```
Checking: Python 2
  Executable: /usr/local/bin/python2
  Python Version: 2.7.12
  python2-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2 in the
      environment.

Checking: Python 3
  Executable: /usr/local/bin/python3
  Python Version: 3.5.2
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.

Checking: Remote Plugins
  Status: Up to date

Tip: Use :CheckHealth! to open this in a new buffer.
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set nocompatible
set runtimepath+=~/.config-test/nvim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.config-test/nvim'))
 " Required:
call dein#add('Shougo/dein.vim')
call dein#add('Shougo/deoplete.nvim')
if dein#check_install()
  call dein#install()
endif
call dein#end()
filetype plugin indent on
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_debug = 1
call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

## The reproduce ways from neovim starting (Required!)

 1. Start neovim with deoplete and minimal rc file
 2. open any file (filetype does not appear to be an issue here)
 3. enter insert mode and see the error get thrown

## Generate a logfile if appropriate

_Not sure a log file would be of some help here, but feel free to let me know if you still need one_

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
<img width="1680" alt="screen shot 2016-08-21 at 4 46 14 pm" src="https://cloud.githubusercontent.com/assets/2835826/17839716/d30b8786-67be-11e6-8ba2-9f46cd362337.png">

**Comment by Shougo** [comment]
Fixed.

**Comment by mhartington** [comment]
😄  thanks shougo
