### ISSUE TITLE
deoplete doesn't complete include content unless I reopen the file.

### ISSUE THREAD

**Issue by XDXX** [Shougo/deoplete.nvim#334]
## Problems summary
I'm using the deoplete + deoplete-clang + neoinclude. When my file  `#include <limits.h>` and
I typing `INT` it will not show any completion candidates. If I reopen that file and typing `INT`
it will show completion candidates like `INT_MAX` and `INT_MIN`.

## Expected
Completing include content without reopen the code file.

## Environment Information

 - OS: Arch Linux  
 - Neovim version: 0.1.4

## Provide a minimal init.vim with less than 50 lines and not plugin manager (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
set runtimepath+=~/path/to/deoplete-clang/
let g:deoplete#enable_at_startup = 1

" Use smartcase
let g:deoplete#enable_smart_case = 1

" Let <Tab> also do completion
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

"close the preview window after completion is done.
autocmd CompleteDone * pclose!

" completion bracket
call deoplete#custom#set('_', 'converters', ['converter_auto_paren'])

" Deoplete-clang
let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
let g:deoplete#sources#clang#clang_header = '/usr/lib/clang'
```
## The reproduce ways from neovim starting (Required!)

```c
#include <limits.h>
INT   //will not show any completion candidates
```
**save and reopen that file**

```c
#include <limits.h>
INT  //will show completion candidates like INT_MAX and INT_MIN
```
I'm not sure it's deoplete or other plugin's problems.
Thanks for any help.

**Comment by Shougo** [comment]
Dup of https://github.com/zchee/deoplete-clang/issues/52
