### ISSUE TITLE
SIGUSR1 not available on Windows

### ISSUE THREAD

**Issue by Metamist** [Shougo/deoplete.nvim#338]
# Problems summary
UpdateRemotePlugins fails to complete when running on windows, using nvim-qt, because signal.SIGUSR1 is not available.

## Expected
signal.SIGTERM?
Replacing SIGUSR1 to SIGTERM before running UpdateRemotePlugins seem to have worked, however I am not aware of the differences of the two (except that Windows do not support UNIX signals)

## Environment Information

 * OS: Windows

## Python versions visible to Neovim
Python3

## Screen shot (if possible)
https://share.metamist.xyz/Hkp3vjas.jpg

**Comment by Shougo** [comment]
Fixed

**Comment by gitlost-murali** [comment]
May I know how you fixed it?
