### ISSUE TITLE
Any plan to porting Deoplete to Vim 8?

### ISSUE THREAD

**Issue by lifepillar** [Shougo/deoplete.nvim#339]
I have started using Deoplete and so far I love it. If only it worked in Vim… Do you have any plan to port Deoplete (or Neocomplete) to Vim 8, leveraging the new asynchronous features of Vim?

**Comment by rafaelndev** [comment]
Read: @63e7bd9a41f2fe0add43bf8e88d7d1fb6452b334

**Comment by lifepillar** [comment]
I see. Just out of curiosity, do you think that Vim's channels and/or jobs could be used to build a plugin with comparable features and performance to deoplete? Or does the neovim-python API provide some essential functionality?

**Comment by Shougo** [comment]
No plan to support Vim8 API in neocomplete

To support Vim8 API in deoplete, neovim-python compatibility API is needed.  I think it can be implemented.  I don't want to create the API though(I have not much time!).
If it is created, I will support it.

> Just out of curiosity, do you think that Vim's channels and/or jobs could be used to build a plugin with comparable features and performance to deoplete?

I think deoplete in Vim is slower than deoplete in neovim.
It is RPC performance problem(MessagePackRPC vs JSON RPC).

**Comment by lifepillar** [comment]
>I think deoplete in Vim is slower than deoplete in neovim.
>It is RPC performance problem(MessagePackRPC vs JSON RPC).

Crystal clear, thanks!

**Comment by Asheq** [comment]
Hey @Shougo , I saw in the video below that Vim8 support for deoplete is on your roadmap. Is this true as of today? Does this mean that you no longer need the neovim-python compatibility API?

https://www.youtube.com/watch?v=u3ZsAVWCuMM

Thanks!

**Comment by jsfaint** [comment]
@Asheq The link is talking about [Denite.nvim](https://github.com/Shougo/denite.nvim), not deoplete.nvim.
denite.vim is a replacement of unite.vim

**Comment by Asheq** [comment]
@jsfaint Yup, I knew that, but there's a section in the video that he calls "secret topics". One of the things he mentions is:

> My next work is to add Vim8 support in deoplete.nvim

The particular point in the video is the 15 minute mark (http://www.youtube.com/watch?v=u3ZsAVWCuMM&t=15m47s) :)

**Comment by jsfaint** [comment]
@Asheq wow~~ Good news, thank you~

**Comment by Shougo** [comment]
> Hey @Shougo , I saw in the video below that Vim8 support for deoplete is on your roadmap. Is this true as of today?

This is true.  To support Vim 8 is on the current load map.

> Does this mean that you no longer need the neovim-python compatibility API?

I need neovim-python compatibility API!
But anyone does not create it.
So I have decided to create it.  It takes much time.

Note:  This does not mean that I don't want to use neovim.
My main editor is still neovim and it is better.
This is just backup plan.

neocomplete will be deprecated.

**Comment by Asheq** [comment]
Thanks, I would like to use neovim, but I'm on Windows right now and there are currently still some problems with neovim on Windows. When Windows gets first-class support in neovim, I and many others will consider switching over :) ... For right now, I'm using Vim8 + neocomplete, but would like to use Vim8 + deoplete.

**Comment by jwmann** [comment]
Very excited for a Vim 8 port! 👍

**Comment by prabirshrestha** [comment]
If you get the latest neovim from master it now works on windows. I have deoplete with typescript currently working on windows.

**Comment by jwmann** [comment]
I'm not sure what that has to do with Vim 8 😕

**Comment by wsdjeg** [comment]
@jwmann I think you can use neovim. I also use neovim with deoplete in win7, but most of my time is in linux.

**Comment by jwmann** [comment]
@wsdjeg I'm not having any issues using neovim, I would just prefer using Vim 8 as most of my plugins still aren't neovim compatible.

**Comment by Shougo** [comment]
> I'm not sure what that has to do with Vim 8 😕

It needs the implementation of neovim-python.
And Vim8 channel/job interface is very complicated.
I don't have much time now...

**Comment by jwmann** [comment]
> It needs the implementation of neovim-python.
And Vim8 channel/job interface is very complicated.
I don't have much time now...

@Shougo 
I understand, I'm not expecting it to come quickly.
I just want to show my support for it! 👍  😄

**Comment by roxma** [comment]
[roxma/vim-hug-neovim-rpc](https://github.com/roxma/vim-hug-neovim-rpc) might help this vim8 support issue.

For anyone getting interested, please help me improve it  :smile:

**Comment by wsdjeg** [comment]
@roxma nice work!

**Comment by jwmann** [comment]
@roxma Great idea! 😄

**Comment by Shougo** [comment]
> vim-hug-neovim-rpc might help this vim8 support issue.

Yes, it is the needed.
I can add Vim8 support using it.
But... I must understand the implementation and implement the handler.
It takes much time and I am very busy.

The help is wanted.

**Comment by roxma** [comment]
This plugin might also be helpful for vim 8 support:

https://github.com/roxma/nvim-yarp#example-for-existing-neovim-rplugin-porting-to-vim-8

As mentioned in the README, I have write a small example on porting existing neovim rplugin to vim 8.

But it seems deoplete is using the old style rplugin api. I'm not sure how much work needs to be done to conver it to new style api (e.g. `@neovim.function`, `@neovim.command`).

**Comment by Shougo** [comment]
I don't want to depends other plugin.

> But it seems deoplete is using the old style rplugin api. I'm not sure how much work needs to be done to conver it to new style api (e.g. @neovim.function, @neovim.command).

It is not old style.  deoplete uses RPC protocol.

And nvim-yarp seems not support async.

**Comment by Shougo** [comment]
I don't fully understand.

I will test the plugin.

**Comment by Shougo** [comment]
@roxma I have tested it, but it is freezed.  Why?

https://github.com/Shougo/deoplete.nvim/pull/553

**Comment by Shougo** [comment]
The test seems works.

**Comment by Shougo** [comment]
I will merge https://github.com/Shougo/deoplete.nvim/pull/553 on the weekend.
The issue will be closed.
Please wait.

**Comment by wsdjeg** [comment]
nice worK

**Comment by Shougo** [comment]
Done.
