### ISSUE TITLE
Complete position for multibyte lines

### ISSUE THREAD

**Issue by hecal3** [Shougo/deoplete.nvim#34]
Hi,

The vim complete function takes the byte position as input. But in deoplete a:context.complete_position is the actual character position.

So when there are multibyte characters at the same line, there is an offset and the completion pops up at the wrong position:
![deoplete-multibyte](https://cloud.githubusercontent.com/assets/11238697/9332936/769ae128-45c7-11e5-98ff-8b629f71e402.png)

Currently my local workaround is this reassignment to the byte position after everything else is done:
```python
cont['complete_position'] = \
	len(bytes(cont['input'][: cont['complete_position']], 'utf-8'))
```

**Comment by Shougo** [comment]
OH, it is fatal problem.
I will fix it later.

**Comment by Shougo** [comment]
Fixed.
