### ISSUE TITLE
Deoplete complains about neovim python client 0.1.10

### ISSUE THREAD

**Issue by joaoponceleao** [Shougo/deoplete.nvim#342]
# Problems summary
Upon upgrading neovim python client to latest 0.1.10 deoplete issues warning:
`[deoplete] Please update neovim-python by "pip3 install --upgrade neovim"`.

With pip neovim==0.1.10
Deoplete asks to run a `pip3 install --upgrade neovim`.

With pip neovim==0.1.9
Deoplete works as expected.

## Environment Information

 * OS:
- Mac OS 10.11.6
- Homebrew python 2 and python 3.
- PyEnv python 2.

- `CheckHealth`  reports success on latest neovim python client in both python 2 and 3 (for 0.1.9 and 0.1.10).
- `CheckHealth` reports warnings in python 2 provider (no neovim in virtualenv)

**Comment by ahmedelgabri** [comment]
Same problem here after a clean install with Python2 & 3 installed. Also vim confirms that Python is installed `:echo has('python')` & `:echo has('python3')`

**Comment by hayd** [comment]
This again seems to be a problem on neovim 0.1.13.

Though the version query seem to have been changed since @tweekmonster's PR: https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/init.vim#L60

**Comment by Shougo** [comment]
@hayd Please read #415
