### ISSUE TITLE
Directory list dropdown relative to filename

### ISSUE THREAD

**Issue by shri3k** [Shougo/deoplete.nvim#355]
This is more of question and I think I know why this happens but just wanted to confirm this and possibly improve on it.

# Problems summary
I've been using `YouCompleteMe` for sometime and just switched to deoplete couple of weeks ago and I noticed that when I try typing the `path`(../) deoplete displays the path that's relative to `pwd` when I expected it to display files/dirs from the current file's path.  The `pwd` path might not be the same to file path  if you had opened the file with `fzf` or `nerdtree` plugin. 
`YouCompleteMe` handles this well and uses the filepath rather than `pwd` path. 

## Expected
Is it possible to have it something like `YouCompleteMe` because often times when I'm working on file I sort of expect it to display relative to the file path.

## Environment Information

 * OS: Ubuntu 16.04

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
function! Do(info)
  UpdateRemotePlugins
endfunction
Plug 'Shougo/deoplete.nvim', { 'do': function('Do') }
...
let g:deoplete#enable_at_startup = 1
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"

```

## Screen shot (if possible)
![ycm](https://cloud.githubusercontent.com/assets/682197/19352231/b64c1194-9124-11e6-9da8-02b93e3d63d1.png)
The above screenshot is of `YouCompleteMe` listing files/dirs from current filepath. 

![deoplete](https://cloud.githubusercontent.com/assets/682197/19352259/d1de7f00-9124-11e6-9766-849da6c70d2f.png)
The above screenshot is of `deoplete` listing files/dirs from `pwd` path.

**Comment by tweekmonster** [comment]
`let g:deoplete#file#enable_buffer_path = 1` is what you want.

**Comment by shri3k** [comment]
Did not knew it was that simple. Thank you. 🎉
