### ISSUE TITLE
Numeric hints in the completion popup

### ISSUE THREAD

**Issue by meriops** [Shougo/deoplete.nvim#358]
I have no idea if this is doable or not... it's just an idea... 
Would it be possible to include numeric "hints" in the completion popup? Something similar to the hints to links provided by browser plugins such as pentadactyl or vimfx. It would allow quickly picking a number when offered a long list of completion suggestions to "jump" directly to a particular completion, without having to keep typing...

**Comment by Shougo** [comment]
I don't think it is not so useful.
I have implemented the feature in neocomplcache.vim.
But the implementation is very complex and I don't use the feature.
It is easy to input the text or pressing the key.

It is useful for unite.vim though.

**Comment by meriops** [comment]
Right. Fair enough.
