### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by sbuljac** [Shougo/deoplete.nvim#36]
Inside HTML tags when fails to complete, deoplete goes in a infinite loop keep printing "Pattern not found" and raising CPU high.(only in INSERT MODE)

**Comment by Shougo** [comment]
I don't reproduce the problem.

Please read the CONTIBUTING.md.

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

**Comment by sbuljac** [comment]
OS: Linux  4.1.5-1-ARCH  x86_64 GNU/Linux

Neovim version: NVIM 0.0.0-alpha+201508100001 (compiled Aug 11 2015 23:40:41)
                           Commit: 7d9472ab1b7dc4eb2bb838fb8febcc7a1aab649d
                           Build type: RelWithDebInfo

NVIMRC:
```
set runtimepath+=~/.vim/bundle/deoplete.nvim
set runtimepath+=~/.vim/bundle/vim-sensible
let g:deoplete#enable_at_startup = 1
```

Log_file:
https://drive.google.com/open?id=0B7ue_W6SV61sWWxZZFIzaEQ4NWs

**Comment by Shougo** [comment]
@sbuljac Please don't upload the reproduce ways in Google drive.
I open it.
It should be described by simple text.

Example:

1. Open vim
2. type "..."
3. ...

**Comment by Shougo** [comment]
@sbuljac Please don't use vim-sensible in minimal .vimrc.
It is not needed for deoplete.

**Comment by sbuljac** [comment]
nvimrc (as minimal as I can make it):
```
set runtimepath+=~/.vim/bundle/deoplete.nvim
let g:deoplete#enable_at_startup = 1
set ft=html
setlocal omnifunc=htmlcomplete#CompleteTags
```
How to reproduce:
1.open Neovim
2.open any html file
3.when inside tag, after trying to complete and fails , deoplete goes in a infinite loop keep printing **"Pattern not found"** and raising CPU high.(only in INSERT MODE)
**Example: <div blabla_**   (**_** represent cursor position) 

The problem is only present when omnifunc is set and deoplete fails to find a word, without it the deplete works fine.

**Comment by Shougo** [comment]
Reproduced.  I will fix it later.

**Comment by Shougo** [comment]
Fixed.
