### ISSUE TITLE
Error occurred calling omnifunction: rubycomplete#Complete

### ISSUE THREAD

**Issue by josemarluedke** [Shougo/deoplete.nvim#363]
# Problems summary

I just pulled latest of deoplete and started getting this error when typing any dot (`.`) for example: `foo.bar`. 

```
Error occurred calling omnifunction: rubycomplete#Complete
```

## Expected

No errors

## Environment Information

 * OS: MacOX Sierra

```
health#deoplete#check
================================================================================

## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
================================================================================

## Remote Plugins
  - SUCCESS: Up to date

## Python 2 provider
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    python2 not found in search path or not executable.
    /usr/bin/python2.7 does not have the neovim module installed. See ":help provider-python".
    /usr/bin/python2.6 does not have the neovim module installed. See ":help provider-python".
    /usr/bin/python does not have the neovim module installed. See ":help provider-python".
  - ERROR: Python provider error
      - SUGGESTIONS:
        - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          /usr/bin/python2.7 does not have the neovim module installed. See ":help provider-python".
          /usr/bin/python2.6 does not have the neovim module installed. See ":help provider-python".
          /usr/bin/python does not have the neovim module installed. See ":help provider-python".
  - INFO: Executable: Not found

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: There are multiple python3 executables found.  Set "g:python3_host_prog" to avoid surprises.
  - INFO: Executable: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
  - INFO: Other python executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.5.1
  - INFO: python3-neovim Version: 0.1.9
  - SUCCESS: Latest Neovim Python client is installed: (up to date)

## Ruby provider
  - ERROR: Missing Neovim RubyGem
      - SUGGESTIONS:
        - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

https://github.com/josemarluedke/vimfiles/blob/master/vimrc

## The reproduce ways from neovim starting (Required!)

 1. edit any ruby file

## Screen shot (if possible)
![1__auth_rb____projects_neighborly_demeter_api_app_thrift__-_nvim__nvim_](https://cloud.githubusercontent.com/assets/230476/19704716/99f4451e-9abd-11e6-97a9-863b1420e621.png)

**Comment by Shougo** [comment]
Please upload `:message` result.
I have not ESP skills.

**Comment by Shougo** [comment]
I think rubycomplete does not work. Because, Ruby provider is not installed.

```

## Ruby provider
  - ERROR: Missing Neovim RubyGem
      - SUGGESTIONS:
        - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

**Comment by josemarluedke** [comment]
@Shougo what do you mean by `:message` result?

Also, I did install the gem today after seen the error, but the it did not solve the problem. Note that I was not having this problem even though I did not have the gem install before.

**Comment by Shougo** [comment]
if_ruby is works properly?
Why Ruby provider is not detected in the `:CheckHealth` result?

> @Shougo what do you mean by :message result?

Please execute `:message` and paste the screenshot after the error is occurred.

**Comment by josemarluedke** [comment]
Ahh okay: Here you go: 

![screen shot 2016-10-25 at 2 48 04 pm](https://cloud.githubusercontent.com/assets/230476/19705652/8f777aca-9ac2-11e6-83ca-1aa472ed8b71.png)

**Comment by Shougo** [comment]
OK.  I should improve the error messages.
Please update deoplete and re-upload `:messages` result.

**Comment by josemarluedke** [comment]
Done, but no new information is displayed: 

![screen shot 2016-10-25 at 3 10 49 pm](https://cloud.githubusercontent.com/assets/230476/19706166/476041a6-9ac5-11e6-8b6d-3fb72c4824a7.png)

**Comment by Shougo** [comment]
Hm.  I cannot help you.
But you should check if_ruby works properly.

**Comment by Shougo** [comment]
You should check normal omnifunc works by `<C-x><C-o>`.

**Comment by Shougo** [comment]
I have tested `rubycomplete#Complete` and it works for me.

**Comment by Shougo** [comment]
I have improved the trace.
Please update deoplete and re-upload `:messages` result.

**Comment by josemarluedke** [comment]
Okay, now we got some values:


![screen shot 2016-10-25 at 3 38 25 pm](https://cloud.githubusercontent.com/assets/230476/19706861/19ffc688-9ac9-11e6-8117-ebc5a472e9f2.png)

How can I test `if_ruby` works properly ?

**Comment by Shougo** [comment]
OK.  Your if_ruby does not work.

> How can I test if_ruby works properly ?

You can check it by `:echo has('ruby')`.

> Also, I did install the gem today after seen the error, but the it did not solve the problem. Note that I was not having this problem even though I did not have the gem install before.

Really?  I have executed `sudo gem install neovim` and it works.

**Comment by josemarluedke** [comment]
The result of `:echo has('ruby')` was `1`. 

Interesting, you are doing a `sudo` to get the gem installed. I was just doing `gem install neovim`, without `sudo`. I use rbenv to get different versions of ruby so that probably affected it.

Doing a `sudo gem install neovim` worked for me. My problem was actually invalid. Thanks for sticking with me and adding more message to the error log. 

I hope this can help other users to solve similar problems.

**Comment by Shougo** [comment]
OK

**Comment by exAspArk** [comment]
I guess it's better to mention about `sudo gem install neovim` in readme.

P.S. the error was introduced in this commit https://github.com/Shougo/deoplete.nvim/commit/981aedb97b0bc75331eccddef5794c8e3899b12d

**Comment by Shougo** [comment]
> .S. the error was introduced in this commit 981aedb

This is not deoplete problem.
The commit just prints the error.

**Comment by exAspArk** [comment]
@Shougo I totally agree that it's not deoplete problem.

But the error occurs when I use updated deoplete plugin for ruby files. IMHO at least it is good to inform your users how to prevent their neovim crashing after installing the plugin ✌️

**Comment by cbrwizard** [comment]
Also had the same error, also used rbenv.
Running `sudo gem install neovim` helped.
If I didn't find this issue I probably wouldn't have solved it.
