### ISSUE TITLE
Equivalent of neocomplete_start_unite_complete

### ISSUE THREAD

**Issue by AndreaOrru** [Shougo/deoplete.nvim#366]
The old version of the plugin (neocomplete) used to be compatible with Unite that could be used to filter the completion candidates. Any plan to add this feature in Deoplete with Unite/Denite?

**Comment by Shougo** [comment]
No.  It is complex feature and I don't use it.

**Comment by AndreaOrru** [comment]
Ok. Would you accept pull requests?

**Comment by Shougo** [comment]
No.
You can create the external source and use it.
