### ISSUE TITLE
Auto-trigger and manual trigger have different results?

### ISSUE THREAD

**Issue by dvcrn** [Shougo/deoplete.nvim#372]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
First of all, I love deoplete. Thanks a lot for the effort put into it!

When triggering deoplete through `C-k` (or in my case `C-n` with `inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<C-j>"`), I noticed that I am getting different results than with just waiting for the auto complete to trigger. 

Example:

- Not triggering manually
<img width="752" alt="2016-11-04 4 39 56" src="https://cloud.githubusercontent.com/assets/688326/19997975/5ea0faaa-a2ad-11e6-8f12-5f0cc4f42514.png">

- Triggering with `C-n`
<img width="489" alt="2016-11-04 4 40 38" src="https://cloud.githubusercontent.com/assets/688326/19997993/73a97224-a2ad-11e6-88c2-324763a5c4da.png">

If I understood correctly, not doing anything automatically triggers deoplete (with go), while manually triggering should do the same thing, just not automatically. 

If this issue is not related to deoplete, please just let me know and I'll post it into the appropriate repository. 

(slightly related, but also not really: When hitting `C-n`, the autocomplete opens but does not automatically select the first result. Is this changeable?)

## Environment Information

 * OS: macOS Sierra 10.12

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```
Checking: Python 2
  Executable: /usr/local/bin/python2
  Python Version: 2.7.12
  python2-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python_host_prog" is not set.  Searching for python2 in the
      environment.
    * Warning: pyenv was found, but $PYENV_ROOT is not set.  Did you follow
      the final install instructions?

Checking: Python 3
  Executable: /usr/local/bin/python3
  Python Version: 3.5.2
  python3-neovim Version: 0.1.9 (up to date)
  Messages:
    * Warning: "g:python3_host_prog" is not set.  Searching for python3 in
      the environment.
    * Warning: pyenv was found, but $PYENV_ROOT is not set.  Did you follow
      the final install instructions?

Checking: Ruby
  Ruby Version: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
  Host Executable: not found
  Host Version: not found
  Messages:
    * Suggestion: Install the neovim RubyGem using `gem install neovim`.

Checking: Remote Plugins
  Status: Up to date
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
function! PostInstallVimgo(info)
  GoInstallBinaries
endfunction

Plug 'Shougo/deoplete.nvim', { 'do': function('DoRemote') }
Plug 'fatih/vim-go', { 'for': 'go', 'do': function('PostInstallVimgo') }
Plug 'nsf/gocode', { 'rtp': 'nvim', 'do': '~/.config/nvim/plugged/gocode/nvim/symlink.sh' }
Plug 'zchee/deoplete-go', { 'do': 'make' }

let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "\<C-n>" : "\<C-j>"
inoremap <expr><s-tab> pumvisible() ? "\<C-p>" : "\<C-k>"
```

## The reproduce ways from neovim starting (Required!)

 1. Navigate to source file
 2. Type a few characters and wait for autocomplete to trigger
 3. Type the same characters but hit `C-k` / `C-n` instead

**Comment by Shougo** [comment]
The manual completion is just `i_CTRL-N`.
This is not deoplete result.

**Comment by dvcrn** [comment]
Yep, that was the missing piece of knowledge. I probably should have read the documentation better - my apologies. 

For future googlers, here's the code that made it work the way I wanted:
```
inoremap <expr><C-n> pumvisible() ? "\<C-n>" :
		\ <SID>check_back_space() ? "\<TAB>" :
		\ deoplete#mappings#manual_complete()
		function! s:check_back_space() abort "{{{
      let col = col('.') - 1
      return !col || getline('.')[col - 1]  =~ '\s'
		endfunction"}}}
```

Though still having the problem that I can't auto-insert the first result. I want to get rid of the subsequent `C-n` when using manual insertion

Sadly my vimscript knowledge is not very good. Is it possible to just tell deoplete to execute `C-n` after opening the autocompletion window? 

![deoplete](https://cloud.githubusercontent.com/assets/688326/19998782/1cd24606-a2b2-11e6-803c-ce481e535296.gif)

**Comment by Shougo** [comment]
Sorry, the feature cannot be supported.

**Comment by tartley** [comment]
@dvcrn Thanks for posting the `inoremap <expr><C-n>` snippet. I've been trying to deactivate the auto-dropdown and manually invoke it with a keypress for hours, but it seems to work now. Thank you!
