### ISSUE TITLE
Could not get completions from: omni

### ISSUE THREAD

**Issue by degva** [Shougo/deoplete.nvim#376]
# Problems summary
When I try to open any kind of C file (at least other kind of extensions doesn't show this erro) deoplete shows a secuence of errors (shown below). I first tried to install deoplete-clang - which didn't worked. Then I've removed and the error still was there. I've removed the plugged directory, reinstall everything but still, the same error comes up only with C/C++ files.

[deoplete] Traceback (most recent call last):                                                                                                
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 73, in gather_results          
[deoplete]     charpos = source.get_complete_position(ctx)                                                                                   
[deoplete]   File "/home/user/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 59, in get_complete_position
[deoplete] Too many errors from "omni". This source is disabled until Neovim is restarted.                                                   
[deoplete]     self.__omnifunc)                                                                                                              
[deoplete] AttributeError: 'Source' object has no attribute '_Source__omnifunc'                                                              
[deoplete] Could not get completions from: omni.  Use :messages for error details. 

## Expected
I have another machine, with the same init.vim file and I get no problems

## Environment Information

 * OS: Archlinux

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

```
## Neovim Python Diagnostic                                                        
                                                                                   
- Neovim Version: NVIM 0.1.6                                                       
                                                                                   
## Remote plugins                                                                  
                                                                                   
**Manifest File**: `/home/degva/.config/nvim/.init.vim-rplugin~`                   
**Plugin**: /home/degva/.config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete
  - Registered: No                                                                 
**Manifest is not up to date**                                                     
                                                                                   
### 'python' info from /usr/bin/nvim                                               
                                                                                   
**Config**: `let g:python_host_prog = '/usr/bin/python2'`                          
**Python Version**: `2.7.12`                                                       
**Neovim Package Version**: `0.1.10`                                               
                                                                                   
### 'python3' info from /usr/bin/nvim                                              
                                                                                   
**Config**: `let g:python3_host_prog = '/usr/bin/python3'`                         
**Python Version**: `3.5.2`                                                        
**Neovim Package Version**: `0.1.10`                                               
                                                                                   
## Python versions visible in the current shell                                    
                                                                                   
- **python** version: `Python 3.5.2`                                               
  - **path**: `/usr/bin/python`                                                    
  - **neovim** version: `neovim (0.1.10)`                                          
- **python3** version: `Python 3.5.2`                                              
  - **path**: `/usr/bin/python3`                                                   
  - **neovim** version: `neovim (0.1.10)`                                          
                                                                                   
## Messages or Suggestions                                                         
                                                                                   
- ERR: You need to run `:UpdateRemotePlugins` in Neovim to enable plugins.         
```
NOTE: I've done :UpdateRemotePlugins

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin()
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
let g:python_host_prog = '/usr/bin/python2'
let g:python3_host_prog = '/usr/bin/python3'
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. nvim main.cpp
 2. enter to insert mode

## logfile

[logfile.txt](https://github.com/Shougo/deoplete.nvim/files/578376/logfile.txt)

**Comment by rvolosatovs** [comment]
In my case neovim freezes completely in Go.
Turning `deoplete` off removes the issue.
So far I could not manage to run `:mes`...
Arch Linux also

**Comment by Shougo** [comment]
Fixed.
