### ISSUE TITLE
Warning messages showed recursively during insert mode.

### ISSUE THREAD

**Issue by lambdalisue** [Shougo/deoplete.nvim#378]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

In C without proper configuration, the following warning messages are showed forever and slowdown the Vim in Insert mode.

```
[deoplete] NoneType
[deoplete] omni source does not support omnifunction: ccomplete#Complete.  Use :messages for error details.
[deoplete] NoneType
[deoplete] You must use g:deoplete#omni_patterns instead..  Use :messages for error details.
[deoplete] NoneType
[deoplete] omni source does not support omnifunction: ccomplete#Complete.  Use :messages for error details.
[deoplete] NoneType

[deoplete] You must use g:deoplete#omni_patterns instead..  Use :messages for error details.
[deoplete] NoneType
[deoplete] omni source does not support omnifunction: ccomplete#Complete.  Use :messages for error details.
[deoplete] NoneType
[deoplete] You must use g:deoplete#omni_patterns instead..  Use :messages for error details.
```

I know I need to follow the message but sometime I just need simple modification and would like to ignore the message. So forever warnings are too annoying in that case.

## Expected

The warning message showed only **ONCE**. 

Probably put some flag on https://github.com/Shougo/deoplete.nvim/blob/c832f9d176c78a439617d39a6b0393e476a88868/rplugin/python3/deoplete/source/omni.py#L52-L63 to ignore further warnings?

**Comment by paupalou** [comment]
Hello @lambdalisue , i have same issue with php completion and [padawan](https://github.com/pbogut/deoplete-padawan). I think the problem appeared with [this commit](https://github.com/Shougo/deoplete.nvim/commit/0cb276fe5f5b388b9aecb9913401868446e70526).

Had to force plugin on [previous commit](https://github.com/Shougo/deoplete.nvim/commit/5fc5ed772de138439322d728b103a7cb225cbf82) ( **5fc5ed7** ) to get working again.

**Comment by Shougo** [comment]
It is the bug. I have fixed.
