### ISSUE TITLE
Deoplete add mapping to Esc

### ISSUE THREAD

**Issue by dominikduda** [Shougo/deoplete.nvim#386]
# Problems summary

So it seems like deoplete is adding some mapping to ESC which will close popup window when present. This makes me click ESC twice to exit insert mode (first to close popup, second to exit insert mode). I also can't unmap it.

When I call `:iunmap <Esc>` it says `E31: No such mapping`. **But** when I call `:imap <Esc>` it says:
```vim
i <Esc> *@pumvisible() ? '<C-E>' : '<C-R>=<SNR>110_FlushBuffer()<CR><Esc>'
```

When I uninstall deoplete, problem dissappears.

## Expected

I want to leave insert mode always with single ESC press.

## Environment Information

 * OS: ubuntu 16.04

## Minimal init.vim

```vim
filetype off
call plug#begin('~/.config/nvim/plug')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()
filetype plugin indent on

" DEOPLETE CONFIG ************************************
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
let g:deoplete#auto_refresh_delay = 30
imap <c-j> <Tab>
imap <c-k> <S-Tab>
" <!!!!!!!!**************!!!!!!!!>
```

You can find my full `.vimrc` [here](https://github.com/dominikduda/config_files/blob/master/ubuntu_specific/.vimrc) (I am linking it to init.vim)

## The reproduce ways from neovim starting

 1. Install deoplete
 2. Press esc with popup present (it closes popup instead of leaving insert mode)

**Comment by dominikduda** [comment]
Turned out it was problem with `vim-autoclose` plugin. Exacly same issue was opened on YouCompleteMe [here](https://github.com/Valloric/YouCompleteMe/issues/9).

Adding this to `init.vim` solved the issue:
```vim
let g:AutoClosePumvisible = {"ENTER": "<C-Y>", "ESC": "<ESC>"}
```

**Comment by Shougo** [comment]
It is the plugin problem.
deoplete does not map `<ESC>` key.
