### ISSUE TITLE
ver 0.0.1 works while latest commit doesn't work

### ISSUE THREAD

**Issue by gglanzani** [Shougo/deoplete.nvim#39]
Hi all,

I'm feel terribly stupid right now, but here's the thing: when using the latest release, everything works like a charm. When trying to work from HEAD, the autocomplete doesn't show up. I think I've pinned it down to the completion_begin function in __init__.py: if I'm on the latest release and use the completion_begin from HEAD, then it stops working. 

Please tell me I'm doing something very stupid!

I do follow the update procedure (update files, call :UpdateRemovePlugins and call :DeopleteEnable).

**Comment by Shougo** [comment]
Note:  I don't get your issue title...  It should be improved.

> I do follow the update procedure (update files, call :UpdateRemovePlugins and call :DeopleteEnable).

`:UpdateRemotePlugins` is correct command.

OK, I think your neovim and Python3 neovim module is too old.  Please update them.
Unfortunately, neovim broke backward compatiblity (It is not my fault).

**Comment by gglanzani** [comment]
Ah! That was it. Maybe it should be mentioned in the README.md that `pip install --upgrade neovim` should be performed. Hadn't thought of that.

**Comment by Shougo** [comment]
I will update the documentation.
