### ISSUE TITLE
Deoplete neovim-python version check uses string comparison instead of numerical comparison.

### ISSUE THREAD

**Issue by yzhuang** [Shougo/deoplete.nvim#393]
This results in deoplete thinking that version 0.1.11 is older than 0.1.8.
Currently, I fixed my issue by downgrading to neovim-python 0.1.9.

Error message when I use neovim-python 0.1.11:

[deoplete] Current neovim-python module version: 0.1.11
[deoplete] deoplete.nvim requires neovim-python 0.1.8+.
[deoplete] Please update neovim-python by "pip3 install --upgrade neovim"

**Comment by yzhuang** [comment]
To be more precise, I think the problem is inside:
https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/init.vim
Line 57 - 68:
```
  " neovim module version check.
  if empty(g:deoplete#_neovim_python_version) || deoplete#util#versioncmp(
        \ sort(g:deoplete#_neovim_python_version)[-1], '0.1.8') < 0
    call deoplete#util#print_error(
          \ 'Current neovim-python module version: ' .
          \  string(g:deoplete#_neovim_python_version))
    call deoplete#util#print_error(
          \ 'deoplete.nvim requires neovim-python 0.1.8+.')
    call deoplete#util#print_error(
          \ 'Please update neovim-python by "pip3 install --upgrade neovim"')
    return 1
  endif
```

The sorting used is for sorting strings, and not suitable for version numbers.

**Comment by Shougo** [comment]
Fixed.
