### ISSUE TITLE
popupmenu should be auto closed after `)`.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#396]
I have test in neovim:master + deoplete:master + Shougo/neco-vim:master.
and I use `call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])` as default.
when edit a vim file. the popup memu will not closed after `)`. here is the picture.
I think it is due to the complete item.word has `)` at the end.
![2016-12-05-20 22 25](https://cloud.githubusercontent.com/assets/13142418/20884874/bd1b8fa8-bb28-11e6-959c-ad98223ad653.png)
![2016-12-05-20 22 28](https://cloud.githubusercontent.com/assets/13142418/20884890/d537b40e-bb28-11e6-814c-383e5964dd5d.png)

**Comment by wsdjeg** [comment]
@Shougo thanks for quick fix, but line 158 of handler also should be change.
the func `s:is_skip_textwidth` is not exist.

**Comment by Shougo** [comment]
Fixed.
