### ISSUE TITLE
Unknown function: deoplete#enable on startup

### ISSUE THREAD

**Issue by thomaswerner** [Shougo/deoplete.nvim#397]
As the title says, nvim throws

E117: Unknown function: deoplete#enable

on startup.

# System

Ubuntu 14.04, NVIM 0.2.0-dev.

# :CheckHealth output

health nvim check

Configuration
  - SUCCESS: no issues found

Performance
  - SUCCESS: Build type: RelWithDebInfo

Remote Plugins
  - SUCCESS: Up to date

terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health provider check

Clipboard
  - SUCCESS: Clipboard tool found: xclip

Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.6
  - INFO: python2-neovim version: 0.1.12
  - SUCCESS: Latest python2-neovim is installed: 0.1.12

Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.4.3
  - INFO: python3-neovim version: 0.1.12
  - SUCCESS: Latest python3-neovim is installed: 0.1.12

Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found

# :UpdateRemotePlugins
generates rplugin manifest rplugin.vim which contains:

" python3 plugins
" ruby plugins
" python plugins

# init.vim

set nocompatible
filetype off

set rtp+=~/.config/nvim/bundle/Vundle.vim

call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'Shougo/deoplete.nvim'

call vundle#end()
call deoplete#enable()

filetype plugin indent on

**Comment by Shougo** [comment]
Deoplete.nvim is not installed collectly.

**Comment by trusktr** [comment]
Hmm, I am getting this now, although I didn't change anything in my install script. I wonder what changed.

**Comment by Shougo** [comment]
You need to check your Python by `:checkhealth`.
I think pynvim is not installed in your new Python.
