### ISSUE TITLE
E210: Using <SID> not in a script context: s:completion_delayed

### ISSUE THREAD

**Issue by h-michael** [Shougo/deoplete.nvim#398]
# Problems summary
nvim throws
`E210: Using <SID> not in a script context: s:completion_delayed`

This issue may related [this](https://github.com/neovim/neovim/issues/5763) neovim issue

## :CheckHealth output

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - INFO: Build type: Dev
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - SUGGESTIONS:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - See https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - ERROR: key_backspace (kbs) entry is ^H (ASCII DELETE): key_backspace=^H,

    - SUGGESTIONS:
      - Set key_backspace to \177 (ASCII BACKSPACE). Run these commands:
          infocmp $TERM | sed 's/kbs=^[hH]/kbs=\\177/' > $TERM.ti
          tic $TERM.ti
      - See https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
  - ERROR: Failed to run healthcheck for "provider" plugin. Exception:
    function health#check[20]..health#provider#check[2]..<SNR>155_check_python[156]..<SNR>155_version_info[1]..<SNR>155_latest_pypi_version[2]..<SNR>155_download[2]..<SNR>155_system[21]..<SNR>155_system_handler, line 2
    Vim(let):E121: Undefined variable: self

## Environment Information

 * OS: OSX10.11.6

**Comment by synasius** [comment]
:+1: 

Same error here. I'm on Ubuntu 16.04 using latest NVIM version from official ppa.

**Comment by rafaeln** [comment]
Same here with Ubuntu 14.04 and latest NVIM from official PPA

**Comment by funeralismatic** [comment]
Same error. Gentoo Linux, NVIM v0.2.0-134-g988ab580

But I think it because of neovim/neovim#5763

**Comment by max-devjs** [comment]
Same here, issue started less than a hour ago (probably after the last nvim update).

**Comment by katywings** [comment]
Yepp me too! (Ubuntu latest NVIM)

**Comment by rafaeln** [comment]
https://github.com/Shougo/deoplete.nvim/issues/399 fixed it for me.

**Comment by Shougo** [comment]
Fixed.

**Comment by max-devjs** [comment]
Amazing! Thank you.

**Comment by katywings** [comment]
Thx a lot! That was fast :)
