### ISSUE TITLE
When using deoplete, do we need to have python3 in path?

### ISSUE THREAD

**Issue by lazywei** [Shougo/deoplete.nvim#4]
When using deoplete, will we need to have python3 in our $PATH? I'm asking this because I'm using pyenv, and my global python is still python2.

**Comment by Shougo** [comment]
> When using deoplete, will we need to have python3 in our $PATH?

Yes.  You must install Python3 neovim module.

**Comment by pickfire** [comment]
I had installed python3 neovim module by:
```
sudo pip3 install neovim
```
I had installed neovim through **git**. But I can't use *deoplete*, `echo has("python3")` still output **0**.

**Comment by ZyX-I** [comment]
@pickfire And how did you install it? Specifically does it know where *its* runtime is or it tries to use Vim runtime (if you have it)?

**Comment by pickfire** [comment]
I had installed it using `make -j4 && sudo make install` then `sudo pip install neovim`. What do you mean runtime?
```
runtimepath=~/.nvim,~/.vim/plugged/vim-bracketed-paste/,~/.vim/plugged/deoplete.nvim/,~/.vim/plugged/neco-syntax/,~/.vim/plugged/neoinclude.vim/,~/.vim/plugged/lightline.vim/,~/.vim/plugged/papercolor-theme/,/usr/local/share/ nvim/vimfiles,/usr/local/share/nvim/runtime,/usr/local/share/nvim/vimfiles/after,~/.nvim/after
```

**Comment by Shougo** [comment]
@pickfire 
https://github.com/neovim/neovim/wiki/Troubleshooting#python-support-isnt-working

**Comment by pickfire** [comment]
Thanks, it seems the problem is fixed after `:set shell=/bin/sh`, but there isn't any completion for `vim` syntax.

**Comment by Shougo** [comment]
@pickfire If you want to complete vim syntax, you must install neco-vim plugin.
https://github.com/Shougo/neco-vim

**Comment by pickfire** [comment]
@Shougo, I understand what you mean now. But what is the difference from https://github.com/Shougo/neco-syntax? I think it is better to have a page to show the syntax add-on.

**Comment by Shougo** [comment]
@pickfire neco-syntax does not support Vim syntax completion.  Because, neco-vim completion is better.

**Comment by pickfire** [comment]
I hope that there is a README for the neco-projects and neco-vim suggest that neco-syntax is better.

**Comment by Shougo** [comment]
OK.  Added.
