### ISSUE TITLE
Space Removed Before Word to Complete

### ISSUE THREAD

**Issue by antoyo** [Shougo/deoplete.nvim#40]
Hello.
Sometimes, after I choose a completion, the space before the word to complete is removed.

Here are the steps to reproduce this issue:

* Open a C file with nvim: `nvim test.c`.
* Type the following code:

```c
int main() {
    // TODO: ajouter des spin_lock dans toutes les méthodes publiques du buffer et pour ma
```
* Trigger the completion with `ctrl-n` and accept the choice `main`.

The resulting code is:

```c
int main() {
    // TODO: ajouter des spin_lock dans toutes les méthodes publiques du buffer et pourmain
```

The expected code is:

```c
int main() {
    // TODO: ajouter des spin_lock dans toutes les méthodes publiques du buffer et pour main
```

(notice the space before `main`)

My config is:

```vim
let g:deoplete#enable_at_startup = 1
```

Thanks to fix this issue.

**Comment by Shougo** [comment]
OK,  I will test it.

**Comment by Shougo** [comment]
Reproduced the problem.
But it seems neovim multibyte problem...
I will research it.

**Comment by Shougo** [comment]
It is neovim's bug.
It is not deoplete bug.    You should report the problem in neovim issue.
`getline()` is correct, but the view is broken.

In Vim, this problem is not occurred.

**Comment by antoyo** [comment]
I believe there is already an [issue](https://github.com/neovim/neovim/issues/68) for this bug.
