### ISSUE TITLE
deoplete#manual_complete() does nothing in recent builds

### ISSUE THREAD

**Issue by low-ghost** [Shougo/deoplete.nvim#402]
# Problems summary
calling <C-r>=deoplete#manual_complete() while in insert mode does nothing except print:
=deoplete#mapping#_rpcnotify_wrapper([])
this is also true of passing in ['file'] or similar to manual_complete
## Expected
completion options show in popup menu

## Environment Information

 * OS:
16.04 Ubuntu neovim 0.2-dev
 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.12
  - SUCCESS: Latest python2-neovim is installed: 0.1.12

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.12
  - SUCCESS: Latest python3-neovim is installed: 0.1.12

## Ruby provider
  - SUCCESS: Found up-to-date neovim RubyGem
  - INFO: Ruby Version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
  - INFO: Host Executable: /home/lowghost/.rvm/gems/ruby-2.3.0/bin/neovim-ruby-host
  - INFO: Host Version: 0.3.1
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

1. nvim $MYVIMRC
2. on line 3 start insert, type let g:deo
3. popup shows w/ [B] marks
4. <C-r>=deoplete#manual_complete()

**Comment by low-ghost** [comment]
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/659630/log_py3_rplugin.txt)

**Comment by Frefreak** [comment]
Same here. I think it's because of 325ecc3. Comment out those two lines it works, but I don't know why.
