### ISSUE TITLE
deopleate do not show some UltiSnips snippets in complition list for php files

### ISSUE THREAD

**Issue by app** [Shougo/deoplete.nvim#404]
# Problems summary
Deopleate do not display any snippets in complition list when I typed 'sm', 'gm', 'ec', 'ns'  and many others php snippets names/chars combinations. 
Complition list do not displayed at all if I type any of this two letters.
At the same time Deoplete displays snippets in complition list for other snippets name/chars combinations. For example when I type 'fore', 'inc', 'if'  snippets is displayed in complition list.
And at the same time 'sm', 'gm', 'ec', 'ns' are expandable by pressing UltiSnips trigger despite no complition list displayed for them by Deoplete.

If I replace Deoplete with YCM I will get expected snippets in complition list for 'sm', 'gm', 'ec', 'ns' typing.

## Expected
if I type 'gm' in php file I have to see complition list with UltiSnips snippet "PHP Class Getter Setter" from this file https://github.com/honza/vim-snippets/blob/master/snippets/php.snippets#L66

## Environment Information

 * OS: Ubuntu 16.10
apt show neovim  2>&1 |grep -B1 Ver 
Package: neovim
Version: 0.1.5ubuntu1+git201612110104+2963+22~ubuntu16.10.1

 * :CheckHealth` result:
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.12
  - SUCCESS: Latest python2-neovim is installed: 0.1.12

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.12
  - SUCCESS: Latest python3-neovim is installed: 0.1.12

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
  - INFO: Host Executable: not found
  - INFO: Host Version: not found
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
let mapleader=" "
set clipboard+=unnamedplus
function! InstallRemotePlugin(info)
  UpdateRemotePlugins
endfunction
call plug#begin('$HOME/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', {'do':function('InstallRemotePlugin')}
" Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:UltiSnipsExpandTrigger="<C-j>"
```

## The reproduce ways from neovim starting (Required!)

 1. Open empty php file. For example test.php
 2. Type <?php in first line
 3. Type gm in the second line

## Screen shot (if possible)
No complition list
![fail](https://cloud.githubusercontent.com/assets/9341/21342601/d54d9676-c6a3-11e6-808c-4ee5def08523.png)

Complition is here for other letters combination with the same nvim init file
![ok](https://cloud.githubusercontent.com/assets/9341/21342602/d54da4ea-c6a3-11e6-969d-71949a5ace92.png)

**Comment by app** [comment]
It seems to me Deoplete ignores single-char and double-char snippets names. 
Is there any option to tune this Deoplete behaviour ?

**Comment by Shougo** [comment]
Please read the documentation...

```
					*deoplete-filter-matcher_default*
Default matchers: ['matcher_length', 'matcher_fuzzy']

	You can change it by |deoplete#custom#set()|.
```

```
					*deoplete-filter-matcher_length*
matcher_length
		Length matching matcher.
		It removes shorter candidates than user input.
```

So, please disable `matcher_length` matcher.

```vim
call deoplete#custom#set('ultisnips', 'matchers', ['matcher_fuzzy'])
```

**Comment by app** [comment]
Thank you!
```
call deoplete#custom#set('ultisnips', 'matchers', ['matcher_fuzzy'])
```
helps.

I think I have to contribute to UltiSnips documentation. This solution is not visible from beginners point of view.
