### ISSUE TITLE
How to complete words from other buffers?

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#405]
@Shougo I want deoplete's buffer source support complete words from buffers in current windows. for example, I have some error message in quickfix list windows, I need complete the words in the quicklist windows.

**Comment by Shougo** [comment]
`:help g:deoplete#buffer#require_same_filetype`

**Comment by wsdjeg** [comment]
@Shougo I have this option set to 0, but it does not work, here is picture, and I want to complete `InterruptedException` from local list.

**Comment by tweekmonster** [comment]
Buffer text only comes from buffers that trigger Deoplete's `on_event`.  I think a special case for quickfix is needed since it's readonly.

**Comment by Shougo** [comment]
I have implemented it.
But you must open the quickfix window after deoplete enabled.

**Comment by wsdjeg** [comment]
Nice work. will have a look.
