### ISSUE TITLE
deoplete auto insert probleme

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#41]
here is my probleme deoplete auto insert things for me :  

![gifrecord_2015-09-12_010022](https://cloud.githubusercontent.com/assets/13202562/9828742/df7dc568-58e9-11e5-925d-04cacf4bf82e.gif)

**Comment by Shougo** [comment]
Please read the CONTRIBUTION.md....

https://github.com/Shougo/deoplete.nvim/blob/master/CONTRIBUTING.md

I don't understand your problem.
Please don't require ESP skills for me.
You should map `<C-h>` and `<BS>` keys.

**Comment by 7belrhalmia** [comment]
@shugo the probleme is when we autocomplete deoplete auto insert suggestion without is selected anything

**Comment by Shougo** [comment]
Please read documentation....

```
Q: I want to use auto select feature like |neocomplete|.

A: You can use it by the 'completeopt' option. >

	set completeopt+=noinsert
```

**Comment by 7belrhalmia** [comment]
@shugo i didit  dosen't work look :  

![gifrecord_2015-09-12_142455](https://cloud.githubusercontent.com/assets/13202562/9831736/4c3c2576-595a-11e5-8ac0-33680285fd97.gif)

**Comment by Shougo** [comment]
Please read CONTRIBUTION.md!
If you ignore it, I will ignore your issue.

**Comment by 7belrhalmia** [comment]
@Shougo  

here is log file : 

https://gist.github.com/7belrhalmia/7de26be6279c48a0db60

her is my minimal vimrc  : 
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources = {}
let g:deoplete#sources_ = ['buffer','tag']
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-h>
      \ deolete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS>
      \ deoplete#mappings#smart_close_popup()."\<C-h>"
 set completeopt+=noinsert 
    set completeopt+=noselect 
     inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

**Comment by Shougo** [comment]
```vim
set completeopt+=noselect 
```

Please remove the line.
It disables the select feature.

**Comment by 7belrhalmia** [comment]
@Shougo  i didit but the some problem

**Comment by Shougo** [comment]
@7belrhalmia Did you read the CONTRIBUTION.md?
Your information is too poor.
It is hard to reproduce.

**Comment by Shougo** [comment]
You must provide the ways to reproduce like this.

* Start Vim
* input ...
* input ...

Expected:

Current behavior:

Please check your provided information.
I have not ESP skills.

**Comment by Shougo** [comment]
Your provided information is ...

# Problems summary

missing.  I don't understand it.  It seems selected candidates...

## Expected

missing.

## Environment Information

missing.  It is not important information for it though.

## Minimal nvimrc less than 50 lines

I get it.  OK.

## Reproducable ways from Neovim starting

Missing.  It is most important information!

## Screen shot (if possible)

I get it.

## Upload the log file

I get it.  It is not important information for it though.

**Comment by 7belrhalmia** [comment]
OS: linux maint 17.1
Neovim version:     NVIM 0.0.0-alpha+201509102052 
                              Commit: b762e809e40271ad8cad13995a1f0cbdabc10f33

my nvimrc : https://gist.github.com/7belrhalmia/4d1a871473389e933f3f


for Reproducable ways from Neovim starting  i don't now how i do it  :

i did in terminal :
       nvim -u minimal.vimrc

but it says cannot from file and iget nothing

**Comment by Shougo** [comment]
@7belrhalmia 

Correct minimal vimrc is ...

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/neosnippet.vim/

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 'ignorecase'
let g:deoplete#sources = {}
let g:deoplete#sources_ = ['buffer','tag']

imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-h>
      \ deolete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS>
      \ deoplete#mappings#smart_close_popup()."\<C-h>"
 set completeopt+=noinsert
 inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

You must add deoplete path to rtp.

Question: It works.  What is the problem?

**Comment by 7belrhalmia** [comment]
@shugo 
look in this demo i will just write fm and deoplete will autoinsert fmt
![gifrecord_2015-09-13_022404](https://cloud.githubusercontent.com/assets/13202562/9834691/9e3849d6-59be-11e5-8fb8-0651cc32d4ee.gif)

second probleme : 

when i autocomplete a function like fmt.Print(   and i wont to delete this function by back key look what happen : 

![gifrecord_2015-09-13_022705](https://cloud.githubusercontent.com/assets/13202562/9834700/03e4d664-59bf-11e5-9711-721085d49716.gif)


my .vimrc : 
 set rtp+=~/.nvim/bundle/deoplete.nvim/
 let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 'ignorecase'
let g:deoplete#sources = {}
let g:deoplete#sources_ = ['buffer','tag']

imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-h>
      \ deolete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS>
      \ deoplete#mappings#smart_close_popup()."\<C-h>"
 set completeopt+=noinsert
 inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

**Comment by Shougo** [comment]
@7belrhalmia 

Please upload the test go file.

> when i autocomplete a function like fmt.Print( and i wont to delete this function by back key look what happen : 

Please describe it in detail.   Your information is very poor.

**Comment by Shougo** [comment]
@7belrhalmia 

Your minimal .vimrc is not minimal.  You don't load vim-go plugin.
But you said it is minimal .vimrc...

Correct vimrc is below.

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/neosnippet.vim/
set rtp+=~/.cache/neobundle/vim-go/

filetype plugin indent on
syntax enable
setlocal omnifunc=go#complete#Complete

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 'ignorecase'
let g:deoplete#sources = {}
let g:deoplete#sources_ = ['buffer','tag']

imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
    \ "\<Plug>(neosnippet_expand_or_jump)" : pumvisible() ? "\<C-n>" : "\<TAB>"
inoremap <expr><C-h>
      \ deolete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS>
      \ deoplete#mappings#smart_close_popup()."\<C-h>"
set completeopt+=noinsert
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"
```

And I can remove "fmt.Print" function.

So, I think you don't test it in minimal .vimrc.
OK.  I will ignore your issue.

**Comment by Shougo** [comment]
Please don't waste my time...

You should read other issue reports.
Most of reports are better than your reports.

I will lock the issue if your issue report is not improved.

**Comment by 7belrhalmia** [comment]
@Shougo  please forgive me i will try now : 
here is my minimal .nvimrc : https://gist.github.com/7belrhalmia/411c86093d71c1a43db6

here is the problem : 

imagine you insert a function like that 
fmt.Print(
or
fmt.Error( 

now i try to remove Print( and Error( with backspace key  i can't  look : 

![gifrecord_2015-09-13_025314](https://cloud.githubusercontent.com/assets/13202562/9834841/7b4b0df8-59c5-11e5-9f39-79c0f603999f.gif)

**Comment by Shougo** [comment]
@7belrhalmia Please don't use pathogen in minimal .vimrc.  This is not minimal .vimrc to reproduce.
Please use `set rtp+={path}` like my minimal .vimrc.
Pathogen loads all plugins and I have not your plugins directory.

>now i try to remove Print( and Error( with backspace key i can't look : 

I don't understand your description.
Please describe it more cleaner.
I understand you are not native English speaker like me.
But your description is too bad.

**Comment by Shougo** [comment]
You should test the behavior with vim-go and deoplete plugins only.
But I have tested them and it worked.
So, it is your environment problem(other plugins conflict?).
It is not deoplete problem.

**Comment by Shougo** [comment]
You should check `verbose imap <BS>` and `verbose set completeopt`.

**Comment by Shougo** [comment]
@7belrhalmia Why don't you test it in my minimal .vimrc?  YOIf it works, it is not deoplete problem.

**Comment by 7belrhalmia** [comment]
@Shougo  yeah it work man when i use only your  minimal .nvimrc  . i think that there are another plugin that conflict with deoplete

**Comment by 7belrhalmia** [comment]
@Shougo  that's what caused the problem for me 

    set completeopt=longest,menu,menuone  

when i remove it evrything worked like a charm  thanks for your help

**Comment by 7belrhalmia** [comment]
now when i do :  verbose imap <BS>


    i  <BS>        * deoplete#mappings#smart_close_popup()."\<C-H>"                                                                        
          Last set from ~/.nvimrc 

and when i do :  verbose set completeopt

      completeopt=menu,noinsert,menuone                                                                                                    
        Last set from ~/.nvim/bundle/deoplete.nvim/autoload/deoplete/mappings.vim

**Comment by Shougo** [comment]
OK.  It seems fixed.
