### ISSUE TITLE
Is it possible to enable deoplete in the command line window?

### ISSUE THREAD

**Issue by thalesmello** [Shougo/deoplete.nvim#412]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Deoplete doesn't seem to work when I'm editing a command in the command-line window.

## Expected
Deoplete to offer completions (particularly from Neco-vim and filetype completion)

## Environment Information

 * OS: Mac OS

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

Working correctly for common vim files.

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

Type `q:` to open the command-line window
Type `i` to insert text
Deoplete doesn't complete commands, but vim's builtin ctrl+p completion works.

**Comment by Shougo** [comment]
I will check the behavior.

**Comment by Shougo** [comment]
I cannot reproduce it with the minimal init.vim

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/neco-vim/

let g:deoplete#enable_at_startup = 1
```
