### ISSUE TITLE
not working, and requiring to update an already updated python-plugin

### ISSUE THREAD

**Issue by damienr74** [Shougo/deoplete.nvim#415]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

deoplete refuses to work without a neovim-python-plugin update. I'm already above ver.0.1.8. everytime I start up nvim, it prompts me to update the plugin.

## Expected
no issues, since I have has("python3") returns 1. I've also tried UpdateRemotePlugins, and it does not fix the issue

## Environment Information

 * OS: Gentoo, neovim-python-plugin 0.1.13

 * nvim-python-doctor result or `:CheckHealth` result(neovim ver.0.1.5-452+):
https://github.com/tweekmonster/nvim-python-doctor

SUCCESS
The only warning is about python 2 (not the latest update)
ERROR: Missing Neovim RubyGem

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : "<Tab>"
let g:deoplete#enable_at_startup = 1

set runtimepath+=~/.config/nvim/dein.vim/repos/github.com/Shougo/dein.vim
call dein#begin(expand('~/.config/nvim/dein.vim/repos/github.com/Shougo/dein.vim'))
call dein#add('Shougo/deoplete.nvim')
call dein#end()
```

## The reproduce ways from neovim starting (Required!)

 1. open neovim
 2. wait for announcement that deoplete needs a newer version of python3

## Logfile

[deoplete.zip](https://github.com/Shougo/deoplete.nvim/files/705540/deoplete.zip)

**Comment by Shougo** [comment]
I have not ESP skill.
Please upload the error messages by `:messages` command.

> deoplete refuses to work without a neovim-python-plugin update. I'm already above ver.0.1.8. everytime I start up nvim, it prompts me to update the plugin.

**Comment by Shougo** [comment]
You should check neovim-python version from the command line like this.

```
$ python3
Python 3.6.0 (default, Dec 24 2016, 08:03:08)
[GCC 6.2.1 20160830] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> print(pkg_resources.get_distribution('neovim').version)
0.1.13
>>>
```

**Comment by Shougo** [comment]
> SUCCESS
> The only warning is about python 2 (not the latest update)
> ERROR: Missing Neovim RubyGem

Please upload the all `:CheckHealth` result.

**Comment by damienr74** [comment]
# :messages
```
[deoplete] Current neovim-python module version: ['0.1.13']
[deoplete] deoplete.nvim requires neovim-python 0.1.8+.
[deoplete] please update neovim-python by "pip3 install --upgrade neovim"
```

# neovim-python
[check-health.txt](https://github.com/Shougo/deoplete.nvim/files/706402/check-health.txt)


```
sh-4.4$ python3
Python 3.4.5 (default, Dec 15 2016, 23:46:57)
[GCC 4.9.3] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pkg_resources
>>> print(pkg_resources.get_distribution('neovim').version)
0.1.13
>>>
```

# CheckHealth

**Comment by deiwin** [comment]
I had the same issue with `NVIM v0.1.5-411-g06bbb79`, I updated to `0.1.17`, updated both my local python and python3 versions and did `pip install --upgrade neovim` and `pip3 install --upgrade neovim`. After that and another `:UpdateRemotePlugins` the issue was gone.

**Comment by Shougo** [comment]
Please upload `echo dein#util#versioncmp('0.1.13', '0.1.8')` result.
It must be than 0.

@damienr74 Your deoplete is the latest version?
Please upload the commit hash.

**Comment by damienr74** [comment]
I first found the problem on `5bcc98dafa678da5d357eb9e74ebdc4d0c57e4ce` but if I use the current version, or even a version from 2015 I still get the same issue.

```
E117: Unknown function: dein#util#versioncmp
E15: Invalid expression: dein#util#versioncmp('0.1.13', '0.1.8')
```

**Comment by Shougo** [comment]
Please upload the `echo deoplete#util#versioncmp('0.1.13', '0.1.8')` result.

It is easy to remove the check.
But I must know the reason.

I cannot reproduce the problem and the function is well tested.

> I first found the problem on 5bcc98dafa678da5d357eb9e74ebdc4d0c57e4ce but if I use the current version, or even a version from 2015 I still get the same issue.

5bcc98dafa678da5d357eb9e74ebdc4d0c57e4ce is too old.
Please upload the proof if you can reproduce it in the latest deoplete.

If you can reproduce the problem, please test `deoplete#util#versioncmp()` implementation.

**Comment by Shougo** [comment]
> but if I use the current version, or even a version from 2015 I still get the same issue.

You can reproduce the problem in version from 2015?
Really?  It is impossible.  Because the check is implemented in later 2016.

**Comment by damienr74** [comment]
turns out I had two repositories of deoplete, and I was pulling from the wrong one.. Removed the unused one and updated the active one. Now deoplete works. versioncmp returns 5.0.

Really sorry for the inconvenience!
Thank you

**Comment by Shougo** [comment]
OK
