### ISSUE TITLE
how can i move the preview window to other place?

### ISSUE THREAD

**Issue by tcstory** [Shougo/deoplete.nvim#416]
now it always apear at the top, i want to move it to the bottom

**Comment by Shougo** [comment]
`set splitbelow`

**Comment by thymbahutymba** [comment]
It's possible to move preview window on right/left, so verticalsplit?

**Comment by Shougo** [comment]
`set splitright`

**Comment by thymbahutymba** [comment]
I have already set splitright but preview buffer always open on top.

**Comment by Shougo** [comment]
Hm.  It seems Vim feature.
