### ISSUE TITLE
gather_candidates documentation is wrong

### ISSUE THREAD

**Issue by xentac** [Shougo/deoplete.nvim#419]
# Problems summary
https://github.com/Shougo/deoplete.nvim/blob/master/doc%2Fdeoplete.txt#L793 says that candidate can be a String or a Dictionary.

https://github.com/Shougo/deoplete.nvim/commit/d4e22ed85c1985d2dc3d3f9f806c49e274485043 removed the ability to return Strings in gather_candidates.

## Expected

The documentation and the code match.

## The reproduce ways from neovim starting (Required!)

 1. Return list of strings in gather_candidates
 2. Watch tracebacks when you try to complete anything

**Comment by Shougo** [comment]
I have restored the feature
