### ISSUE TITLE
Should we be optimizing our language specific input_source regex?

### ISSUE THREAD

**Issue by CodeMonkeyMike** [Shougo/deoplete.nvim#422]
First I would like to start out in saying this is not an issue per say more of a question.

Should we be optimizing our language specific input_source regex? Will it give better auto complete results and better performance?

Here is the question I asked on stackexchange|superuser which prompted this question http://superuser.com/questions/1169775/optimize-regex-for-php-method-completion

**Comment by Shougo** [comment]
I don't think the optimization is needed.
You should optimize the completion source than the regex.

**Comment by CodeMonkeyMike** [comment]
Got it, so it doesn't make sense to optimize the intput_source for performance. But can I follow up in asking, would it prevent false positives? Like if it is completing on something which is not an object or class name? Thanks.

**Comment by Shougo** [comment]
> But can I follow up in asking, would it prevent false positives? 

If the regex is wrong, it must be fixed.

**Comment by CodeMonkeyMike** [comment]
Good point, thanks for humoring me.
