### ISSUE TITLE
Deoplete not working as expected

### ISSUE THREAD

**Issue by LEGOlord208** [Shougo/deoplete.nvim#426]
# Problems summary
I recently switched to NeoVim, and it has only been uphill pretty much.
I used to use NeoComplete and vim-go, working perfectly...
Now, only like 1 completion is shown, and even the vim-go creator recommends deoplete-go.

But... why?

## Expected
I expected things to work **exactly** as Ctrl+X Ctrl+O does, no extra custom made plugins needed.

## Environment Information
 * deoplete version(SHA1):
9f62f1af933f5852b8d797dde4f8d36997a66941

 * OS:
Linux Minut 18.1

 * neovim version:
NVIM 0.2.0-dev
 * `:CheckHealth` result(neovim ver.0.1.5-452+):
https://hastebin.com/geqaxecodu.vbs

## Provide a minimal init.vim with less than 50 lines (Required!)
(Full but short: https://hastebin.com/awicorufut.sql)

Stripped:
```vim
call plug#begin()

Plug 'Shougo/deoplete.nvim', {'do': ':UpdateRemotePlugins'}
Plug 'fatih/vim-go'

call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Get vim-go.
 2. Remove or deactivate any other go plugin
 3. Try the completion.

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/12830969/22497096/6295f394-e84f-11e6-8a74-343aad2a82ef.png)
(It should have Print and other options as well. If I import and use the "os" package, nothing shows at all.)

## EDIT:
Yes, I got deplete-go working. It's working fine. But that is not the issue. The issue is that I needed it in the first place. I thought deoplete would be an automatic Ctrl+X Ctrl+?, but Ctrl+X Ctrl+O worked without additional deoplete plugins.

**Comment by kevlar1818** [comment]
I was confused by something like this, also. 

I was under the impression that `:UpdateRemotePlugins` pulled down all the language completers that Deoplete needed. Is this not the case? I've had to install the language completers manually for Deoplete to work.

**Comment by Shougo** [comment]
You must set `g:deoplete#omni#input_patterns`.
Please read the documentation.

I recommend for you to use deoplete-go.

**Comment by LEGOlord208** [comment]
I don't think it's realted... I more or less wondered why you couldn't use the built in menu (Ctrl+X Ctrl+O), like NeoComplete has it (also made by you lol).

**Comment by Shougo** [comment]
This is expected behavior.
Because, deoplete has deoplete-go.
If vim-go and deoplete-go are installed, deoplete must disable vim-go omni completion.
So I have removed `g:deoplete#omni#input_patterns` default for vim-go.

**Comment by LEGOlord208** [comment]
I didn't say you should fix it... I just asked why.
Because if vim-go would work, we wouldn't need deoplete-go anyway. Besides, what if a language doesn't have a deoplete plugin, only a normal plugin to it?

**Comment by Shougo** [comment]
> Besides, what if a language doesn't have a deoplete plugin, only a normal plugin to it?

You can set `g:deoplete#omni#input_patterns`.
Some patterns are set in default though.

**Comment by LEGOlord208** [comment]
Ok ok ok ok ok
