### ISSUE TITLE
How to remove duplicate results?

### ISSUE THREAD

**Issue by ahmedelgabri** [Shougo/deoplete.nvim#427]
# Problems summary
Duplicate results with `deoplete-ternjs` _(not sure if this is deoplete problem or deoplete-ternjs problem)_

## Expected
To not have duplicate results

## Environment Information

 * deoplete version(SHA1): https://github.com/Shougo/deoplete.nvim/commit/e182a11a1367af4a3240d9aed6ccefa241d8000a

 * OS: macOS Sierra

 * neovim version: HEAD `NVIM v0.2.0-527-gbb2f36d0`

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 1ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python"
  - INFO: Executable: /usr/local/bin/python
  - INFO: Python2 version: 2.7.13
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.0
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - INFO: Ruby: ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Gem "neovim" is up-to-date: 0.3.1
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/.vim/plugged/deoplete.nvim/
set runtimepath+=~/.vim/plugged/deoplete-ternjs/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Install [`deoplete-ternjs`](https://github.com/carlitux/deoplete-ternjs)
 2. edit `nvim test.js` & type `[].`
 3. you will get omni & ternjs completions

## Screenshot (if possible)
<img width="1113" alt="screen shot 2017-02-05 at 16 24 10" src="https://cloud.githubusercontent.com/assets/63876/22627257/cd080122-ebbf-11e6-880b-4f22f28fc9ce.png">

**Comment by ahonn** [comment]
![image](https://user-images.githubusercontent.com/9718515/49994371-4b7dab00-ffc4-11e8-9140-2da805c7b79c.png)

I use deoplete-ternjs and LanguageClient, how to remove duplicate results?
I want to remove LanguageClient result If exists same tern result

**Comment by Shougo** [comment]
I have added dup option.  So you can disable it.

```vim
call deoplete#custom#source('LanguageClient', 'rank', 500)
call deoplete#custom#source('LanguageClient', 'dup', v:false)
```

Note: Please install the latest version of deoplete.
