### ISSUE TITLE
Extended info for selected item in the menu

### ISSUE THREAD

**Issue by whitecolor** [Shougo/deoplete.nvim#430]
Is it possible to display extended info for currently selected Item in completion menu?
For example UI of VSCode:
![image](https://cloud.githubusercontent.com/assets/736697/22731912/2c1c1e14-ee0e-11e6-8849-0a0dc287d164.png)

**Comment by Shougo** [comment]
No.  It cannot.  Because, it is Vim/neovim feature.
You should request it in neovim issues.
