### ISSUE TITLE
deoplete + context_filetype.vim な状況下でhtmlを編集するとカーソル位置が意図せず移動する

### ISSUE THREAD

**Issue by naoto-k** [Shougo/deoplete.nvim#431]
# Problems summary
https://twitter.com/Outstrp/status/829696255680851968
についての件です。状況は表題の通り。

## Environment Information

 * deoplete version(SHA1): 2e9fd874b7d974a03df8af10a090e2601b16c7f0

 * OS: macOS Sierra

 * neovim version: NVIM 0.1.7

 * `:CheckHealth` result(neovim ver.0.1.5-452+):vim 
```
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```
## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
filetype plugin indent off

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

let s:dein_dir = expand('~/.cache/dein')
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
    if !isdirectory(s:dein_repo_dir)
        execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
    endif
    set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim
endif
set runtimepath+=~/.config/nvim
if dein#load_state(s:dein_dir)
  call dein#begin(s:dein_dir)

  call dein#add('Shougo/dein.vim')
  call dein#add('Shougo/vimproc')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')
  call dein#add('Shougo/context_filetype.vim')

  call dein#end()
  call dein#save_state()
endif

let g:deoplete#enable_at_startup = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_complete_start_length = 1

""""" END OF LINE """""

filetype plugin indent on
syntax enable

if dein#check_install(['vimproc'])
  call dein#install(['vimproc'])
endif
if dein#check_install()
  call dein#install()
endif
```
## The reproduce ways from neovim starting (Required!)
1. htmlファイルをひらく
```bash
nvim test.html
```

2. htmlファイルを編集する(カーソルが移動していることをわかりやすくするために最初開業しています)
```html
 (改行) 
 (改行)  
<span class="a
```

3.上記入力時にカーソルがファイルの先頭に移動しスニペットの候補が出ている状態になります

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
![2017-02-10 15 58 14](https://cloud.githubusercontent.com/assets/7326977/22817935/a439020e-efad-11e6-97aa-681f37681231.png)

## Upload the log file
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/766015/log_py3_rplugin.txt)

**Comment by tweekmonster** [comment]
@naoto-k 
`omnifunc`の値を表示してください。また、HTMLの `filetype`に使用しているプラ​​グインを教えてください。(Google translate, sorry if it's a bad translation)

@Shougo I encountered this issue with django-plus.vim.  It happens because a source is calling the VimL omnifunc outside of a normal omnifunc situation (`<c-x><c-o>`), so the cursor isn't restored after.

This is the fix: https://github.com/tweekmonster/django-plus.vim/commit/28a22174ae247da089fd0abcb0825f1e5b5d7f64
