### ISSUE TITLE
SQL completion support

### ISSUE THREAD

**Issue by vbauerster** [Shougo/deoplete.nvim#437]
Dear @Shougo 

This is just a question, rather than issue. Is there any deoplete compatible external plugin which supports SQL completion you know about? External plugins section in documentation contains no information about SQL completion plugin, and I couldn't find one.
What I found is [SQLComplete](https://github.com/vim-scripts/SQLComplete.vim), which says it is built-in to vim since version 7.0. It is also included in neovim by default. Unfortunately, when I edit any sql file, there is no SQL completion from deoplete side. I expected some basic SQL keywords completion, but there is nothing, expect buffer completion.

I'm sure it is possible to make [SQLComplete](https://github.com/vim-scripts/SQLComplete.vim) deoplete compatible plugin, but don't know how, because my vimscript skill is very primitive.

Would it be possible for you to make some external plugin for SQL completion?
I think it is very common to edit SQL files, and should be enabled by default.

Thank in advance.

**Comment by vbauerster** [comment]
Looks like sql completion works only when keywords are typed in lower case. In my case I typed sql keywords in capital case so there wasn't any completion.

**Comment by Shougo** [comment]
SQLComplete changes the cursor, so it is not good for deoplete.
I think you should create deoplete source for SQL.

> I'm sure it is possible to make SQLComplete deoplete compatible plugin, but don't know how, because my vimscript skill is very primitive.

You don't have to learn Vim script.
deoplete sources are written by Python3.
