### ISSUE TITLE
Please support 'set cscopetag' and thus also gtags

### ISSUE THREAD

**Issue by dsirov** [Shougo/deoplete.nvim#439]
# Problem summary

Deoplete does not use tags supplied by cscope when `set cscopetag` setting is used.
You can see in the screenshots that the tags are set all right and are available in nvim, but deoplete only recognizes the one in the current buffer.

I believe this is due to the fact that [tag.py](https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/source/tag.py) only caches contents of tag files, but in this case tags are populated by cscope and there is no tag file.

I don't know if this is better to be resolved in a new plugin... As `set cscopetag` is a built-in vim feature, I would think maybe this is better to be addressed in deoplete itself...

## Expected

Deoplete should show 3 options for completion: somefunc1, somefunc2 (both from somecfile.c) and some_my_func (from the same buffer).
Currently it only shows the one from same buffer.

# My motivation
I actually use gtags (gnu GLOBAL) to perform indexing (multi-languages, with its pygments plugin for additional languages). It can index large source trees and create efficient binary DB.
It has cscope-compatible interface (which is used by setting `set cscopeprg=gtags-cscope`) and enables vim to use it pretty much out-of-the box.

**Thank you very much for your work, your plugin is awesome!**

# Info
## Environment Information

 * deoplete version(SHA1):
```
commit 134c763f7a7d2130ebbe8686623a5064b2195dde
Author: Shougo Matsushita <Shougo.Matsu@gmail.com>
Date:   Wed Feb 22 08:22:31 2017 +0900
```
 * OS: Fedora 25 x86-64

 * neovim version:
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/bin/cc -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -Wconversion -Wp,-U_FORTIFY_SOURCE -Wp,-D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -D_GNU_SOURCE -I/builddir/build/BUILD/neovim-0.1.7/obj/config -I/builddir/build/BUILD/neovim-0.1.7/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/builddir/build/BUILD/neovim-0.1.7/obj/src/nvim/auto -I/builddir/build/BUILD/neovim-0.1.7/obj/include
Compiled by mockbuild

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```
 * `:CheckHealth` result:
```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminfo
  - INFO: key_backspace terminfo entry: key_backspace=\177,

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - ERROR: Missing Neovim RubyGem
    - SUGGESTIONS:
      - Install or upgrade the neovim RubyGem using `gem install neovim`.
  - INFO: Ruby Version: not found
  - INFO: Host Executable: not found
  - INFO: Host Version: not found

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Minimal init.vim

```vim
set runtimepath+=~/.config/nvim/deoplete.nvim

set cscopetag	" Use tags provided by cscope

let g:deoplete#enable_at_startup = 1
let g:deoplete#tag#cache_limit_size = 50000000 " 50MB - just to rule out cache size-related problems
```

## How to reproduce

 1. In an empty directory create 2 files:
   a. somecfile.c
    ```c
    void somefunc1() { return 0; }
    void somefunc2() { return 1; }
    ```
     b. test.c
    ```c
    int some_my_func();
    ```
 2. run `cscope -b` in the directory (`cscope.out` should be created)
 3. `nvim test.c`
```vim
:cs add cscope.out
:tag some.*
```
## Screen shots
After performing `:tag some.*`
![image](https://cloud.githubusercontent.com/assets/25965216/23276626/bb8a50be-fa13-11e6-9280-b836c42b091e.png)

With deoplete (partial) completion
![image](https://cloud.githubusercontent.com/assets/25965216/23276677/f109d606-fa13-11e6-9c01-e75e9337ba16.png)

**Comment by Shougo** [comment]
I don't want to add the feature.
You can create cscope source for it.
