### ISSUE TITLE
Problem with fast typing

### ISSUE THREAD

**Issue by VasLem** [Shougo/deoplete.nvim#441]
# Problems summary
Hello and congrats for your awesome script. I am using neovim 0.2.0-dev. The problem has appeared after last update of deoplete (which is commit b9774f4), as I can recall (I cannot understand what you mean with SHA1). 
Ok, the problem appears when I am fast typing, or fast backspacing.  There are moments when autocompletion is activated by its own and text gets autocompleted using the first suggestion appearing, without my confirmation. The normal behavior for me would be to either tab through the suggestions (or use arrow keys) and then press <enter> to autocomplete. This still happens, but I now also have the eronious uncorfirmed autocompletion, which happens randomly (but with high likelihood) and mostly when I am fast typing. It might be worth checking it out. Thanks!

## config.vim
Here is my minimal config.vim

```
set nocompatible              " required
filetype off                  " required
highlight BadWhitespace ctermbg=red guibg=darkred
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
"Autocompleter platform
Plugin 'Shougo/deoplete.nvim'
"Syntax checking platform
Plugin 'neomake/neomake'
"Allow snippet support
Plugin 'Shougo/neosnippet'
Plugin 'Shougo/neosnippet-snippets'
"Allow autocomplete Python support
Plugin 'zchee/deoplete-jedi'
"Enable C products autocomplete support
Plugin 'tweekmonster/deoplete-clang2'
call vundle#end()            " required
filetype plugin indent on    " required
syntax on
set backspace=indent,eol,start
set encoding=utf-8
au BufNewFile,BufRead *.py
            \ set tabstop=4 |
            \ set softtabstop=4 |
            \ set shiftwidth=4 |
            \ set textwidth=79 |
            \ set expandtab |
            \ set autoindent |
            \ set fileformat=unix |
au BufRead,BufNewFile *.py,*.pyw,*.c,*.h match BadWhitespace /\s\+$/
let python_highlight_all=1
set clipboard=unnamed
let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#show_docstring = 1
let g:deoplete#sources#jedi#statement_length = 100
let g:neosnippet#enable_completed_snippet = 1
imap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	\ "\<Plug>(neosnippet_expand_or_jump)"
	\: pumvisible() ? "\<C-n>" : "\<TAB>"
smap <expr><TAB> neosnippet#expandable_or_jumpable() ?
	\ "\<Plug>(neosnippet_expand_or_jump)"
	\: "\<TAB>"
let g:jedi#completions_enabled = 0
let g:neomake_python_enabled_makers = ['pylint']
autocmd! BufWritePost * Neomake
let mapleader = "\<Space>"

```

## Environment Information

 * deoplete version(SHA1):

 * OS: Ubuntu 16.04

 * neovim version:  0.2.0-dev

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: xclip

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.12
  - INFO: python2-neovim version: 0.1.12 (outdated; from /usr/local/lib/python2.7/dist-packages/neovim)
  - WARNING: Latest python2-neovim is NOT installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.1.12 (outdated; from ~/.local/lib/python3.5/site-packages/neovim)
  - WARNING: Latest python3-neovim is NOT installed: 0.1.13

## Ruby provider
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

```

**Comment by shri3k** [comment]
I thought I was the only one who was having this issue but recently after the upgrade I too get autocomplete automatically which is quite annoying. I'm not sure where this got introduced but I can confirm this is happening to me too.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/440

**Comment by kropper** [comment]
I'm having this problem excessively on multiple machines, with the latest versions. Even just moving around a buffer in insert mode with the arrow keys will often change text based on the first completion suggestion. 

Fiddling with `auto_complete_delay` or changing the `complete_method` to _omnifunc_ have no effect. 

Is there any way to configure deoplete to ensure that text is only changed when a certain key (e.g., _Tab_ or _Enter_) is pressed?

**Comment by Shougo** [comment]
@kropper Please create the new issue for it.
I will test it.

> I'm having this problem excessively on multiple machines, with the latest versions. Even just moving around a buffer in insert mode with the arrow keys will often change text based on the first completion suggestion.

If so, I can reproduce it in my machine, can't I?

> Is there any way to configure deoplete to ensure that text is only changed when a certain key (e.g., Tab or Enter) is pressed?

I don't understand.

**Comment by JulianIsrael** [comment]
> I don't understand.

I think I do. I'm wondering the same. is it possible to instead of show the menu as we type in chars, to display only the menu when while on insert mode I hit a special command keys? like <c-n> in ex. this.<HERE I PRESS THE COMMAND KEYS>

**Comment by Shougo** [comment]
```vim
let g:deoplete#disable_auto_complete = 1
```

`:help deoplete#mapping#manual_complete()`

Please read the documentation.
