### ISSUE TITLE
Problem implementing async source

### ISSUE THREAD

**Issue by thalesmello** [Shougo/deoplete.nvim#443]
# Problems summary

I'm trying to implement an async source for `webcomplete.vim`. However, I'm having trouble indicating I have no completions at this moment.

## Expected

Suppose I write the following code (based on the example in the documentation)

```
class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'async'
        self.mark = '[async]'
        self.rank = 1000
        self._count = 0

    def gather_candidates(self, context):
        self._count += 1
        self.print('hi')
        context['is_async'] = self._count < 10
        if self._count == 1:
            return []
        return [context['input'] + str(self._count)]
```

I return an empty list to indicate I have nothing to update at this moment, but I need the function to be called in the future so that I can yield the results when they finish. The problem is that the function is not called again. 

Am I doing something wrong?

## Environment Information

 * deoplete version(SHA1): 189cedb

 * OS: Mac OS

 * neovim version: Nvim 1.7

**Comment by thalesmello** [comment]
@Shougo It's still not working yielding an empty list

**Comment by thalesmello** [comment]
I mean, at least I tested the example that I provided above.

**Comment by Shougo** [comment]
Fixed again.
