### ISSUE TITLE
Sorting proposal

### ISSUE THREAD

**Issue by docwhat** [Shougo/deoplete.nvim#446]
This is a proposal for improving the way sorting works.

## The problem

Current sorting is two part: Intra-source sorting and source sorting.

This means that in a Ruby file if I type `defr` and have ultisnips as a source in a plain setup, it is near the bottom of the candidates list, despite being an exact match for the `defr` snippet because ultisnips have a default source rank of 8.

### Intra-source sorting

Sorting within a single source is controlled by the `sorter_*` filters.  At the moment, there is just two:

* `sorter_rank` which combines recently used completions (stored in `deoplete#_rank`) and how many of the head characters match.
* `sorter_head` which is just a plain alphabetical list.

### Source sorting

The sources themselves are sorted via (in order, with the last taking precedence):

1. The default rank value of 100 (from `Base.py`, 100)
2. In the sorter class itself (via `__init__()` on the class)
3. A call to `deoplete#custom#set`.

## Proposed solution

* Leave the source sorting above in place. and make the final rank available to `gather_candidates`.
* Remove the `filter.sorter_*` classes.
* Create a new optional candidate attribute, `rank`.
    * If the candidate `rank` is unset, it defaults to the source `rank`.
    * The sources could use the source-sorting `rank` to calculate the candidate `rank` (e.g. `calculated_rank + 10`) so that sources can do something smart, if needed.  Example, `around` could alter the candidate rank by distance from the cursor.
* Modify the matchers to alter the ranking based on how close to the candidates they are.  Example, `matcher_head` could use the amount of head match to alter the candidate rank.
* Add a new matcher, `matcher_exact_match` which adds 10000 to exact matches's `rank`.
* Add another new matcher, `matcher_recently_used` which uses `deoplete#_rank` to bump up recently used items.

Just prior to displaying, everything could be sorted by the candidate `rank`, then via alphabetical sort for identical ranks.

What do you think?

**Comment by docwhat** [comment]
PS: I really like your code, it is clean and pretty easy to understand. 😃

**Comment by Shougo** [comment]
> This means that in a Ruby file if I type defr and have ultisnips as a source in a plain setup, it is near the bottom of the candidates list, despite being an exact match for the defr snippet because ultisnips have a default source rank of 8.

This is UltiSnips default rank problem.
You can change it.

> Leave the source sorting above in place. and make the final rank available to gather_candidates.

No.  It should not.
You can disable the sort feature.

> Modify the matchers to alter the ranking based on how close to the candidates they are. Example, matcher_head could use the amount of head match to alter the candidate rank.

It should not.  It is sorter's work.

> Add a new matcher, matcher_exact_match which adds 10000 to exact matches's rank.

It should be `sorter_exact_match` or `sorter_match`.

> Add another new matcher, matcher_recently_used which uses deoplete#_rank to bump up recently used items.

It should be `sorter_recently_used` or `sorter_mru`.
