### ISSUE TITLE
probleme when deleting charactere using backspace

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#45]
![gifrecord_2015-09-18_160840](https://cloud.githubusercontent.com/assets/13202562/9962885/1304a5f6-5e20-11e5-947e-c085752cbee5.gif)

@Shougo  look at the cursor when fast removing the cursor make a step back

**Comment by Shougo** [comment]
@7belrhalmia It seems feature.
deoplete skips the completion when fast removing.
What is the problem?

And please read the CONTRIBUTING.md!
Your issue report is always to hard to understand/reproduce.

**Comment by Shougo** [comment]
You should upload the go file.
Why don't you upload the sample code?

**Comment by 7belrhalmia** [comment]
@Shougo  : here is the go code  :   https://gist.github.com/7belrhalmia/ae04679e6c40c06e9b66 

@Shougo  it can't be  a feature because now when deleting you must do it slowly to not remove the letters that comme forward . here is another screenshot that show the error . 

![gifrecord_2015-09-19_231629](https://cloud.githubusercontent.com/assets/13202562/9978406/9335531a-5f24-11e5-9825-65d5b455e75e.gif)
here is log file : https://gist.github.com/7belrhalmia/c9ae691aa0b6a0f2e3ff

**Comment by Shougo** [comment]
It is fixed in latest deoplete.
