### ISSUE TITLE
Competition is not working in macroses

### ISSUE THREAD

**Issue by BjornMelgaard** [Shougo/deoplete.nvim#450]
# Problems summary

Text, inserted by Tab, is omited in macroses

```
  inoremap <silent><expr> <Tab>
      \ pumvisible() ? "\<C-n>" : deoplete#manual_complete()
```

## The reproduce ways from neovim starting (Required!)

 1. some text
 2. @q
 3. trigger autocompletition
 4. qq
 5. competition was omited

## Neovim version
With my nvim all right, this behavior was since I start using vim, is this right or can be repaired?

**Comment by Shougo** [comment]
This is feature.
The macro feature just saves the keys.
But deoplete is asynchronous.
You cannot reproduce the behavior.

**Comment by roxma** [comment]
The best solution is to simply use the popup menu as a hint, and insert the characters on your own, instead of using `<c-n>` and `<c-p>` to select completion items.
