### ISSUE TITLE
Use syntax files as a completion source

### ISSUE THREAD

**Issue by devth** [Shougo/deoplete.nvim#453]
# Problems summary

How can I configure deoplete to use the relevant syntax files as a completion source?

## Expected

For example, in a Dockerfile, I want it to complete:

```
MAI
```

to:

```
MAINTAINER
```

I'd like to do this for all file types without having to list them all out, if possible.

Happy to provide the other issue requirements like minimal init.nvim but I thought the question was simple enough that it didn't require; let me know if you want it anyway.

**Comment by Shougo** [comment]
Please install neco-syntax plugin.
https://github.com/Shougo/neco-syntax

**Comment by devth** [comment]
@Shougo thank you ⚡️
