### ISSUE TITLE
not bug, just a question

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [Shougo/deoplete.nvim#457]
Hi, thanks for deoplete, now i don't use SuperTab plugin anymore.
I think the differences between deoplete and  SuperTab is the trigger way. deoplete is automatic other than press tab key and works like normal IDE.Now I know deoplete is far more than Supertab.
Recently i use deoplete with java-complete2 and vim-go on MacOS with neovim 0.1.7
java-complete2 works very well with deoplete out of the box but vim-go does not.
both java-complete2 and vim-go use <C-X><C-O> for their complete, it's omniCompletion feature of vim. So did java-complete2 do more work to cooperate with deoplete? If i write a language plugin how can get the benefit of deoplete?
i have tried deoplete-go but it did not work in my computer and i want to use vim-go as my only one go plugin.

**Comment by Shougo** [comment]
> i have tried deoplete-go but it did not work in my computer and i want to use vim-go as my only one go plugin.

deoplete-go does not work?
It is deoplete-go issue.  I think.
You should create new issue in deoplete-go.

deoplete-go is recommended.  But you can specify the omni pattern manually like this.

```vim
		let g:deoplete#omni_patterns = {}
		let g:deoplete#omni_patterns.go = '[^. *\t]\.\w*'
```

**Comment by FinallyFinancialFreedom** [comment]
thank you very much. The two lines you mentioned make vim-go work with deoplete very well.
