### ISSUE TITLE
deoplete show popup when it shouldn't

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#46]
this gif show clearly the problem : 

![gifrecord_2015-09-19_225933](https://cloud.githubusercontent.com/assets/13202562/9978384/7be5bb84-5f22-11e5-8fd9-5c589ae0dbe8.gif)

log file : https://gist.github.com/7belrhalmia/13762d7f03b78c3b0385

minimal .nvimrc :  https://gist.github.com/7belrhalmia/630ac19bf2b56e7754b5

**Comment by 7belrhalmia** [comment]
with this i cannot presse enter to return to a new line

**Comment by Shougo** [comment]
Fixed.
