### ISSUE TITLE
Duplicate NeoSnippet entries

### ISSUE THREAD

**Issue by jabui** [Shougo/deoplete.nvim#461]
# Problems summary

As title. See screenshot.
Something to do with ~/.cache?

## Environment Information

 * deoplete version(SHA1): be8d03e547c5bbc00b93c453b04a64a767baba3f

 * OS: macOS

 * neovim version: 0.1.7

 * `:CheckHealth` result(neovim ver.0.1.5-452+): OK

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'Shougo/neosnippet'
  Plug 'honza/vim-snippets'
call plug#end()

let g:deoplete#enable_at_startup = 1

let g:neosnippet#enable_snipmate_compatibility = 1
let g:neosnippet#snippets_directory='~/.local/share/nvim/plugged/vim-snippets/snippets'
let g:neosnippet#disable_runtime_snippets = {
\   '_' : 1,
\ }
```

## The reproduce ways from neovim starting (Required!)

 1. Type a snippet keyword deoplete shows
 2. Delete a few characters and try the keyword again
 3. Duplicate entries from there onward

## Screen shot (if possible)
![2017-04-08 23 59 10](https://cloud.githubusercontent.com/assets/8256446/24829561/73588182-1cb7-11e7-90a4-60f970ad8f07.gif)

**Comment by Shougo** [comment]
Please use the latest version of deoplete.
I cannot reproduce the problem.
