### ISSUE TITLE
Suggest full-line completions

### ISSUE THREAD

**Issue by graysonwright** [Shougo/deoplete.nvim#463]
Hello! Thank you for all of your work on this project.

In vim, I often use `<c-x><c-l>` to complete an entire line at a time. For instance, if I type in insert mode:

```javascript
import Re<c-x><c-l>
```

then I get:
<img width="275" alt="sh" src="https://cloud.githubusercontent.com/assets/829576/24881152/ba819d60-1df1-11e7-9af7-ff1776fe20fe.png">

The problem with vim's default implementation of full-line completion is that it only sources suggestions from currently open buffers. I would like to see suggestions from all files in my project.

I'm wondering if it's possible to set up deoplete to suggest full lines sourced from the entire project, not just the currently open buffer. It seems like this would be possible by using something like [ack.vim](https://github.com/mileszs/ack.vim) to search through files for the matching line.

To continue the above example, the command `:Ack '^import Re'` returns a list of the results I'm interested in.

What is the best way to approach this?

Thanks for your help!

**Comment by Shougo** [comment]
I think it is possible.
The similar project exists in Vim.

https://github.com/haya14busa/vim-auto-programming

Note: Unfortunately, it does not support neovim.

You can create the source for deoplete.

**Comment by graysonwright** [comment]
@Shougo - is there documentation for creating a new source? I looked, but couldn't find a good place to start.

Thanks, I appreciate your help.

**Comment by Shougo** [comment]
I think you should read the other sources implementation.

After that please read `deoplete-create-source` section.

**Comment by graysonwright** [comment]
Great, thanks! I'll check those out.

**Comment by Shougo** [comment]
It may be implemented as denite source...

**Comment by cyansprite** [comment]
have you tried messing around with the `complete` option?

```vim 
complete+=Uube
``` 
will scan buffers from other windows, loaded, unloaded and buffers not in the buffer list, so any buffer that vim knows about, it scans.

```:h 'complete'```

**Comment by Shougo** [comment]
I don't want to add the source in general.
You can create it though.
Closing.
