### ISSUE TITLE
Deoplete inserts characters and jumps randomly

### ISSUE THREAD

**Issue by khalidchawtany** [Shougo/deoplete.nvim#47]
The cursor jumps randomly on fast input. Sometimes the inserted characters are not deleted when undoing. When I press **:q** to quit, **neovim** does not warn me about unsaved changes (Strange!!). This happens with the keys that start insert mode e.g.: a,i, etc

![](https://cldup.com/7zy1nq53tt.gif)

**Description of the screenshot:**

* Notice that the cursor jumped to the middle of typed *iiiii*'s the first time I began typing. Later, I did an undo and began typing *iii* again.
* This time it jumped to the **head* and doing an undo did not delete the inserted characters. However, the + sign in the status bar disappeared, indicating that there are no changes.
* Executing an **:e!** shows that the file on disk is different from what is shown in the window.

**OS Environment:**
```
OS X 10.10.5
iTerm 2 nightlies
```

**nvim version:**
```
NVIM 0.0.0-alpha+201509190915 (compiled Sep 20 2015 19:25:58)
Commit: 2417aeebbffe58eab6ac39feac0f64a27aafbee2
Build type: RelWithDebInfo
```

**Minimal nvimrc:**
```
call plug#begin('~/.nvim/plugged')
  Plug 'Shougo/deoplete.nvim'
  let g:deoplete#enable_at_startup = 1
call plug#end()
```

**HTML used in the screenshot:**
```html
<!DOCTYPE html>
<html lang="en">
  <head>
 </head>
 <body>
	 <div id="">
 </body>
</html>

```

**Comment by Shougo** [comment]
Fixed.

**Comment by khalidchawtany** [comment]
Thanks :+1:
