### ISSUE TITLE
Add Language Server Protocol support

### ISSUE THREAD

**Issue by artursmirnov** [Shougo/deoplete.nvim#472]
The protocol is used in Visual Studio Code and has a perspective of having very wide language support. So it would be nice to support it in deoplete, thus integrating many languages and frameworks autocompletion.

Here's the protocol description: https://github.com/Microsoft/language-server-protocol
There is also a standalone implementation for vim: https://github.com/prabirshrestha/vim-lsp
Here's the protocol implementation for a particular framework (Ember.js): https://github.com/emberwatch/ember-language-server

**Comment by mhartington** [comment]
Pretty sure this has been brought up before.
Can't speak for Shougo, but I'd think this would be outside the scope of deoplete.
Being that deoplete is only focused on async completion, a LSP plugin would need to be made that integrates with deoplete.

https://github.com/autozimu/LanguageClient-neovim

I've not used this plugin, but it seems to implement LSP, then has built in support for deoplete.

**Comment by Shougo** [comment]
You can use the plugin.
