### ISSUE TITLE
Better Documentation

### ISSUE THREAD

**Issue by rmad17** [Shougo/deoplete.nvim#473]
Hi, 
I really appreciate your plugins and deoplete as well. However some feedback I wanted to give.
1. The documentation could be better. Its difficult to read everything in same style font in one doc.
2. There should be an easy way or a keymapping to open completion manually as well as auto.

**Comment by Shougo** [comment]
You can do better it.

**Comment by Shougo** [comment]
> There should be an easy way or a keymapping to open completion manually as well as auto.

Please read the documentation.

```
		If you want to trigger deoplete manually, see also
		|g:deoplete#disable_auto_complete|, which should be 1 then
		typically.
>
		inoremap <silent><expr> <TAB>
		\ pumvisible() ? "\<C-n>" :
		\ <SID>check_back_space() ? "\<TAB>" :
		\ deoplete#mappings#manual_complete()
		function! s:check_back_space() abort "{{{
		let col = col('.') - 1
		return !col || getline('.')[col - 1]  =~ '\s'
		endfunction"}}}
```
