### ISSUE TITLE
Initialize non-blocking between VimEnter and InsertEnter?

### ISSUE THREAD

**Issue by neilvyas** [Shougo/deoplete.nvim#476]
It would be awesome to do (non-blocking) initialization between VimEnter and InsertEnter because then startup time is still fast, but you use normal mode for however long it takes deoplete to initialize (~500ms for me).

```vim
" Initialize on VimEnter, making nvim slow to load
let g:deoplete#enable_at_startup = 1

augroup initialize_completion
    au!
    au VimEnter * call deplete#initialize()
augroup END
```

```vim
" Initialize on InsertEnter, making nvim load quickly, but entering insert mode slow
let g:deoplete#enable_at_startup = 1
```

```vim
" Initialize non-blocking between VimEnter and InsertEnter
???
```

Apologies if this is in the manual, I read it and couldn't figure it out from there.

**Comment by Shougo** [comment]
This is neovim issue instead of deoplete.

https://github.com/neovim/neovim/pull/5856
