### ISSUE TITLE
problem with semantic completion

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#48]
hello @shugo 

i have a question when edit a css file .deoplete show me just completion from buffer i have to presse `<c-x><c-o>` to get semantic completion . if there is possible how can i get both buffer and semantic completion

**Comment by Shougo** [comment]
Please provide sample css file and the reproduce ways.
I will test it.

**Comment by 7belrhalmia** [comment]
css file : https://gist.github.com/7belrhalmia/877eb26dd93f2329a701

my .nvimrc : 

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 'ignorecase'
let g:deoplete#sources = {}
let g:deoplete#sources_ = ['buffer','tag']

let g:deoplete#auto_completion_start_length = 1
let g:deoplete#enable_smart_case = 1
inoremap <expr><C-h>
         \ deolete#mappings#smart_close_popup()."\<C-h>"
inoremap <expr><BS>
         \ deoplete#mappings#smart_close_popup()."\<C-h>"
set completeopt+=noinsert
inoremap <expr> <CR> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

 let g:deoplete#deoplete_onmni_patterns = get(g:, 'deoplete#force_omni_input_patterns', {})
    let g:deoplete#deoplete_onmni_patterns.go = '[^. \t]\.\w*'
  let g:deoplete#deoplete_onmni_patterns.js = '[^. \t]\.\w*'
  let g:deoplete#deoplete_onmni_patterns.css = '[^.]\:*\w*'
let g:deoplete#deoplete_onmni_patterns.scss = '\h\w*\|[^. \t]\.\w*'
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"


@Shougo  i just wont deoplete to combine buffer and semantic completion

**Comment by Shougo** [comment]
> css file : https://gist.github.com/7belrhalmia/877eb26dd93f2329a701

Please provide the complete position for testing.

**Comment by 7belrhalmia** [comment]
@shugo  just inside 
     body {

     }

write any tag element you will get buffer completionj not semantic completion

**Comment by Shougo** [comment]
OK.  I get it.  It is feature.
Because, it is not matched '[^.]\:*\w*' pattern.
And you must use `g:deoplete#omni#input_patterns` instead of `g:deoplete#omni_patterns`.
`g:deoplete#deoplete_omni_patterns` is wrong variable name.

**Comment by 7belrhalmia** [comment]
so i must do 

     let g:deoplete#omni#input_patterns='[^.]:\w'  it's the solution

**Comment by 7belrhalmia** [comment]
@Shougo   when i used i get erro type mismatch

**Comment by Shougo** [comment]
```vim
 let g:deoplete#omni#input_patterns.css='\w\+'
```

**Comment by 7belrhalmia** [comment]
@Shougo  i did exactly what you told me 

but i got : 

    line  925:
     E121: Undefined variable: g:deoplete#omni#input_patterns
    line  927:
    E121: Undefined variable: g:deoplete#omni#input_patterns

**Comment by Shougo** [comment]
You must initialize `g:deoplete#omni#input_patterns`.

```vim
let g:deoplete#omni#input_patterns = {}
```
