### ISSUE TITLE
Deoplete not working at all

### ISSUE THREAD

**Issue by pdoak** [Shougo/deoplete.nvim#481]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
In a new buffer, when I type some text, I get a screen full of error messages

## Expected

It should show completion options as I type

## Environment Information

 * deoplete version(SHA1): c202045

 * OS: 10.12.4

 * neovim version: v0.2.0-704-gbe65fd88

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 0ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.4.0

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              minimal init.vim                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""



set runtimepath+=~/.config/nvim/plugins/deoplete.nvim
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1
let g:deoplete#deoplete_onmni_patterns = get(g:, 'deoplete#force_omni_input_patterns', {})
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
let g:deoplete#sources = {}
let g:deoplete#sources._=['omni', 'buffer', 'member', 'tag', 'ultisnips', 'file']
filetype plugin on
set omnifunc=syntaxcomplete#Complete
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS


set runtimepath+=~/.config/nvim/plugged/vim-multiple-cursors

echom "minimal vimrc loaded"

```

## The reproduce ways from neovim starting (Required!)

 1. n -u minit.vim 
 2. insert "This is a test"
 3. insert "This is a test"
 4. no completions are suggested

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

Two log files produced: /tmp/log_py3_rplugin /tmp/log_py3_script
Both uploaded
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/1004087/log_py3_rplugin.txt)
[log_py3_script.txt](https://github.com/Shougo/deoplete.nvim/files/1004088/log_py3_script.txt)

## Upload the log file
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/1005010/log_py3_rplugin.txt)

**Comment by Shougo** [comment]
Please update deoplete to the latest version.

> In a new buffer, when I type some text, I get a screen full of error messages

Please upload the error messages.

**Comment by pdoak** [comment]
@

**Comment by Shougo** [comment]
I cannot reproduce the problem.
I don't know why.

**Comment by Shougo** [comment]
`set runtimepath+=~/.config/nvim/plugged/vim-multiple-cursors`

It conflicts with deoplete.
Please remove it from minimal vimrc.

**Comment by Shougo** [comment]
> The error messages that I get are:

It is the full of error messages?
Please upload the screenshot.

**Comment by pdoak** [comment]
I have removed vim-multiple-cursors and still get the same errors.

Attached is a screen shot of the errors

![image](https://cloud.githubusercontent.com/assets/1565586/26202012/b7d515fc-3bcd-11e7-8020-ff55f4f782ac.png)

Also, interestingly, I don't get these error messages when I run nvim with my full vimrc but I don't get any completions either.

**Comment by callmekohei** [comment]
Hello. I tried it.

I guess that you try to ':UpdateRemotePlugins'. (maybe :-))

#### init.vim
```vim
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              minimal init.vim                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set runtimepath+=~/.config/nvim/plugins/deoplete.nvim
let g:deoplete#enable_at_startup = 1

filetype plugin indent on
syntax enable

"----------------------------------------------------------
" Neovim's Python provider
"----------------------------------------------------------
let g:python_host_prog  = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'

" Clipbord
set clipboard+=unnamedplus  " use clipboard ( see : help clipboard )

" Mouse ( see :help mouse-using )
set mouse=nvic
```
#### Result
![screen shot 2017-05-18 at 23 31 39](https://cloud.githubusercontent.com/assets/17691683/26207334/32af6512-3c22-11e7-83fb-4afd7cac4d95.png)

**Comment by callmekohei** [comment]
Or ... python's problem?

Please check it up

```
Documents$ pip3 list
Package        Version
-------------- -------
greenlet       0.4.12 
msgpack-python 0.4.8  
neovim         0.1.13 
pip            9.0.1  
setuptools     32.2.0 
ujson          1.35   
wheel          0.29.0 
```

I hope your help :-)

**Comment by pdoak** [comment]
@callmekohei : Thanks for your help. Using your minimal init.vim, deoplete works. However, when I put the same settings in my init.vim, I get the following error messages:
    
<img width="1672" alt="screen shot 2017-05-18 at 17 36 44" src="https://cloud.githubusercontent.com/assets/1565586/26213368/aa759d46-3bf0-11e7-9812-0b78a3326efc.png">

**Comment by pdoak** [comment]
I think that I have now got it working within my init.vim. Removing

```
"----------------------------------------------------------
" Neovim's Python provider
"----------------------------------------------------------
let g:python_host_prog  = '/usr/local/bin/python'
let g:python3_host_prog = '/usr/local/bin/python3'
```
gets it working.

**Comment by callmekohei** [comment]
👍

**Comment by amerysong** [comment]
when I type include[SPC] 
![error](https://user-images.githubusercontent.com/16118124/35774588-e8755d48-09ae-11e8-8aed-c990b061f740.png)

Error occurs

**Comment by Shougo** [comment]
@amerysong Please create the new issue.
Otherwise, I will ignore your problem.
