### ISSUE TITLE
Delete command stopped to work

### ISSUE THREAD

**Issue by EfforiaKnight** [Shougo/deoplete.nvim#485]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Delete (d command) doesn't work.

## Expected
Delete a line when 'dd'

## Environment Information

 * deoplete version(SHA1): 493a97d151b6b89993194b442ca5f6d5e969e9f8

 * OS:
Arch Linux x86_64

 * neovim version:
NVIM v0.2.1-225-g9cc10c69f

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 0ms
  - INFO: $TERM: xterm-256color-italic
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - SUGGESTIONS:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.14dev
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.1
  - INFO: python3-neovim version: 0.1.14dev
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
  - INFO: Host: /home/efforia/.gem/ruby/2.4.0/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.4.0

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim
let g:deoplete#enable_at_startup = 1

filetype plugin indent on
syntax enable

" Clipbord
set clipboard+=unnamedplus  " use clipboard ( see : help clipboard )
```

## The reproduce ways from neovim starting (Required!)

1. nvim -u mini.vim
2. Insert some text
3. Try to delete a line with 'dd'
4. Line didn't deleted and in the status line you can see 'dd'

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
![image](https://cloud.githubusercontent.com/assets/18498403/26284608/1cd05774-3e48-11e7-8764-3c7b0719643b.png)

## Upload the log file
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/1017052/log_py3_rplugin.txt)

**Comment by Shougo** [comment]
Please see https://github.com/Shougo/deoplete.nvim/issues/477.
