### ISSUE TITLE
big issue with the cursor 

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#49]
i think this gift describe the problem : 

![gifrecord_2015-09-26_030043](https://cloud.githubusercontent.com/assets/13202562/10115318/2bc23b0e-63fb-11e5-91eb-8ab3af74115b.gif)

i use vim-go plugin

**Comment by Shougo** [comment]
Thanks.  Fixed.

**Comment by 7belrhalmia** [comment]
@Shougo  thanks man
