### ISSUE TITLE
Delay / Manually trigger completions

### ISSUE THREAD

**Issue by rosstimson** [Shougo/deoplete.nvim#5]
First of all, many thanks for this awesome project.

I know this project is **very** young but I was wondering if it is possible to delay the popup with completions or make it so you have to manually trigger this.  Having the completions popup instantly for every word you're typing can be annoying/distracting.

This is pretty much the only thing stopping me from using deoplete full-time; I understand if this is not yet implemented though.

**Comment by HerringtonDarkholme** [comment]
I wonder whether you need to use a completion plugin at all. But at least deoplete has not yet implemented a feature that can combining multiple sources. So what you get from deoplete's completion is almost the same as neovim's natvie completion. In future, these two completion source will probably differ. 

For now, if you want to manually trigger completions, just use neovim's native key binding.

**Comment by Shougo** [comment]
> I know this project is very young but I was wondering if it is possible to delay the popup with completions or make it so you have to manually trigger this.

What's the delay feature?  It is same with `g:neocomplete#auto_completion_start_length` feature?
I can implement these features.  But I have many of todo listed features in deoplete.

> This is pretty much the only thing stopping me from using deoplete full-time

You don't have to use deoplete in full-time.  It is still alpha version.

**Comment by rosstimson** [comment]
@Shougo 

> What's the delay feature?

I've used several in the past that allowed you to set a slight delay in milliseconds before the popup.  However, the  `g:neocomplete#auto_completion_start_length` you mentioned is better, it looks like YCM has a similar option `g:ycm_min_num_of_chars_for_completion`.

> You don't have to use deoplete in full-time. It is still alpha version.

I'm aware this is alpha, I figure anyone using Neovim in the first place is fairly comfortable on the bleeding edge.  I'd like to start using deoplete from the offset as I believe it will be the next 'de-facto' completion plugin for Neovim (i.e. __the future__) and that the more people using it the quicker bugs etc will be discovered.

-----------

Thanks @HerringtonDarkholme, I'm aware that the completion offered by deoplete is probably not much different to that of the native completion but I believe/hope that will quickly change and would like to start using deoplete straight away (see above).

----------

Perhaps I need to be more patient.  :smile:

I just wanted to get this on the wishlist and keep track of it.

**Comment by Shougo** [comment]
> However, the g:neocomplete#auto_completion_start_length you mentioned is better, it looks like YCM has a similar option g:ycm_min_num_of_chars_for_completion.

I think it is same feature.

**Comment by Shougo** [comment]
Implemented the feature.
