### ISSUE TITLE
How to accept suggestion?

### ISSUE THREAD

**Issue by sid-kap** [Shougo/deoplete.nvim#50]
When deoplete shows me a suggested word, what should I press to insert the suggested word?

**Comment by Shougo** [comment]
You don't have to press the key.  You can just select.
But you can accept suggestion by `<C-y>` key.

**Comment by sid-kap** [comment]
`<C-y>` seems to accept only one character. I want to accept an entire word. Am I doing something wrong?

**Comment by sid-kap** [comment]
Ah, looks like `<C-n>` is what i needed.
