### ISSUE TITLE
WARNING: "deoplete.nvim" is not registered

### ISSUE THREAD

**Issue by codejam1024** [Shougo/deoplete.nvim#501]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

## Expected
always say "deoplete.nvim" is not registered
try `:UpdateRemotePlugins` still not works!

## Environment Information

 * deoplete version(SHA1): master

 * OS: Windows10

 * neovim version:NVIM v0.2.1-25-g2e3b78d1

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
health#nvim#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "D:/WinSofts/Python27/python.exe"
  - INFO: Executable: D:/WinSofts/Python27/python.exe
  - INFO: Python2 version: 2.7.13
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "D:/WinSofts/Python36/python.exe"
  - INFO: Executable: D:/WinSofts/Python36/python.exe
  - INFO: Python3 version: 3.6.1
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "D:/WinSofts/Python27/python.exe"
  - INFO: Executable: D:/WinSofts/Python27/python.exe
  - INFO: Python2 version: 2.7.13
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "D:/WinSofts/Python36/python.exe"
  - INFO: Executable: D:/WinSofts/Python36/python.exe
  - INFO: Python3 version: 3.6.1
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Provide a minimal init.vim with less than 50 lines (Required!)
if &compatible
    set nocompatible
endif
let g:python_host_prog='D:/WinSofts/Python27/python.exe'
let g:python3_host_prog='D:/WinSofts/Python36/python.exe'
let $NVIM_PYTHON_LOG_FILE='debug.log'
let $NVIM_PYTHON_LOG_LEVEL='DEBUG'

filetype plugin indent on

call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
[debug.txt](https://github.com/Shougo/deoplete.nvim/files/1100190/debug.txt)

## Screen shot (if possible)

![s](https://user-images.githubusercontent.com/5414233/27514663-8cdae0d4-59c3-11e7-8ab1-2fb1954f3736.PNG)

## Upload the log file
[debug.txt](https://github.com/Shougo/deoplete.nvim/files/1100190/debug.txt)

**Comment by Shougo** [comment]
I cannot reproduce the problem.
It seems `:CheckHealth` problem in Windows.
It should be reported in neovim issues.

**Comment by Shougo** [comment]
Note:  deoplete works without problem?

**Comment by codejam1024** [comment]
It seems NVIM-v0.2.1  problem in Windows
