### ISSUE TITLE
Deoplete suppresses ConqueGDB/ConqueTerm output

### ISSUE THREAD

**Issue by thomafred** [Shougo/deoplete.nvim#504]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

When Deoplete is loaded: ConqueGDB/ConqueTerm prompt return is not return user input is provided.

For example: When Deoplete is loaded, ConqueGDB startup message does not appear.

## Expected

ConqueGDB/ConqueTerm should act like a regular prompt inside neovim

## Environment Information

 * deoplete version(SHA1):

 * OS: Ubuntu 16.04 LTS

 * neovim version: v0.2.1-390-g42d8929

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.nvim_runtime/plugged')

function! DoRemote(arg)
  UpdateRemotePlugins
endfunction

Plug 'Shougo/deoplete.nvim'

Plug 'vim-scripts/Conque-GDB'
Plug 'zchee/deoplete-clang'
Plug 'tweekmonster/deoplete-clang2'
Plug 'zchee/deoplete-jedi'
Plug 'JuliaEditorSupport/deoplete-julia'

call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Ensure deoplete and ConqueGdb are installed
 2. Start ```nvim```
 3. Start ConqueGDB using the command ```:ConqueGDB```
 
if ```g:deoplete#enable_at_startup = 1```, no startup message will appear. However, if ```g:deoplete#enable_at_startup = 0```, the GDB startup message _will_ appear

**Comment by Shougo** [comment]
It is not deoplete problem.  It is ConqueGDB problem.
And ConqueGDB is deprecated plugin.  You should use other plugin.

**Comment by thomafred** [comment]
Could you please recommend an alternative that will work with Deoplete?

**Comment by Shougo** [comment]
Hm.  I think `:term` is recommended.
I use deol.nvim.

**Comment by thomafred** [comment]
My apologies, I should have been more specific.

 I need a neovim GDB-integration. Until switching to Deoplete, ConqueGDB has served me well. However, since ConqueGDB does not play well with Deoplete, I need an alternative.

Are you able to suggest an alternative GDB-integration?

I should not I tried the following workaround without any luck:

```vim
au BufEnter ConqueGDB* deoplete#disable()
au BufLeave ConqueGDB* deoplete#enable()
```

**Comment by Shougo** [comment]
https://github.com/huawenyu/neogdb.vim
