### ISSUE TITLE
inserting function prototype on complete

### ISSUE THREAD

**Issue by 7belrhalmia** [Shougo/deoplete.nvim#51]
@Shougo  you made a beautiful work on that by using neosnnipet but i think there is a lot of problem with that due to neosnnipet features . 

i find another way using ultisnips  . take a look at and hope it will hwlp the users of deoplete and neosnnipet

    function! MyOnCompleteDone()
        if !exists('v:completed_item') || empty(v:completed_item)
           return
       endif

    let complete_str = v:completed_item.word
    if complete_str == ''
        return
    endif
    let abbr = v:completed_item.abbr
    let startIdx = match(abbr,"(")
    let endIdx = match(abbr,")")
    if endIdx - startIdx > 1
        let argsStr = strpart(abbr, startIdx+1, endIdx - startIdx -1)
        let argsList = split(argsStr, ",")
        let snippet = "" 
        let c = 1
        for i in argsList
            if c > 1 
                let snippet = snippet. ", "
            endif
            " strip space
            let arg = substitute(i, '^\s*\(.\{-}\)\s*$', '\1', '') 
            let snippet = snippet . '${'.c.":".arg.'}'
            let c += 1
        endfor
        let snippet = snippet . ")$0"
        call UltiSnips#Anon(snippet)
    endif
     endfunction
     autocmd CompleteDone *.go  call MyOnCompleteDone()

**Comment by Shougo** [comment]
> @Shougo you made a beautiful work on that by using neosnnipet but i think there is a lot of problem with that due to neosnnipet features . 

You don't explain the problems.
Please explain it.

**Comment by Shougo** [comment]
Closing.
