### ISSUE TITLE
Suggestion: filter out identical completions

### ISSUE THREAD

**Issue by mqudsi** [Shougo/deoplete.nvim#514]
Sometimes deoplete shows the same suggestion from a particular source more than once. I'm not sure if it is deoplete or the source that is misbehaving, but in general, if a source returns more than one exactly identical results (which would be a bug in the source), can deoplete filter them out?

(If I have a reproducible case of deoplete listing a suggestion more than once when I'm sure the source didn't return a duplicate, I will open a full and complete issue w/ a test case for that.)

**Comment by Shougo** [comment]
omni source and filetypes source set `dup`.
It ignores the duplication.
So it is feature.

**Comment by mqudsi** [comment]
OK, thanks. I'll open this issue with deoplete-rust where I am seeing the behavior.

**Comment by mqudsi** [comment]
@Shougo  I looked at the source for deoplete-rust and I can't find that it sets `dup` anywhere: https://github.com/sebastianmarkow/deoplete-rust/blob/master/plugin/deoplete-rust.vim

Do you have any ideas? The actual `racer` binary used by `deoplete-rust` is returning duplicates.

**Comment by mqudsi** [comment]
@Shougo In the `deoplete-rust` plugin, I changed the `dup` value from `1` to `0` in the add candidate call and saved the changes to the python file, but it is still reporting the duplicates. Do I have to do something in dein to get it to update?

**Comment by Shougo** [comment]
@mqudsi deoplete-rust must filter the dup candidates.
I think the duplication is the function overload.
