### ISSUE TITLE
When I press enter, with pop menu but no candidate select, can I select and insert first candidate and close the popup?

### ISSUE THREAD

**Issue by vincent178** [Shougo/deoplete.nvim#515]
Thanks @Shougo for the great work of this awesome project.

I wonder is there any chance to do the action like below.

When I input something and autocomplete popups, when I click the enter, it auto select the first candidate in the popups, insert it, and close the popups.

I have do lots of searching around this, didn't have any clue.

Could you help on this?

Thanks,
Vincent

**Comment by Shougo** [comment]
This is not deoplete specific issue...
You should configure like this:

```vim
set completeopt+=noinsert
```
