### ISSUE TITLE
Hide duplicate completions

### ISSUE THREAD

**Issue by yotamN** [Shougo/deoplete.nvim#516]
I use JavaScript with ternjs and buffer completions, many times I get duplicated options, one from ternjs and one from the buffer. It would be a nice option to remove duplicated options, maybe keep the one in the first order of the sources variable.

Here is an example I get when I use deoplete with both ternjs and buffer enabled:

![screenshot from 2017-07-16 22-30-43](https://user-images.githubusercontent.com/5249239/28250661-f13de4ae-6a76-11e7-86c8-c9b16f2344ec.png)

I know I can just disable the buffer completion but sometimes it's useful because ternjs doesn't know to complete everything.

**Comment by mqudsi** [comment]
I literally just bugged that yesterday, apparently incorrectly :)
#514

**Comment by Shougo** [comment]
This is *not* duplication.
Because, member source candidates is `set(` and ternjs candidates is `set`.
