### ISSUE TITLE
Omnifunc called differently when using input_patterns than when using omni_patterns

### ISSUE THREAD

**Issue by FrigoEU** [Shougo/deoplete.nvim#519]
# Problems summary

I'm trying to figure out how to get deoplete to work with the omnifunc I wrote in my purescript ide plugin. I get the correct results when I use omni_patterns because both arguments to the omnifunc are what I expect, but when I use input_patterns, the second argument (often called "base" in documentation) is always empty on the second invocation of the omnifunc, so no results ever come back. The first invocation of the omnifunc is as I expect, and I return the correct column number.

Is this how it's supposed to work? Are my expectations of how omnifunc will be called wrong? Should I determine the string to be passed on to the completion engine myself?

I'd like to use input_patterns so I would also get suggestions from snippets among others. Basically I don't want to sidestep everything deoplete does by usign omni_patterns.

## Expected

I expected the second argument to the omnifunc to be the same as when neovim calls it, namely the string from the column returned on the first invocation of omnifunc until the cursor.

## Environment Information

 * deoplete version(SHA1): 5cef0e6b607d3acb742d1de07a4ddd3a5bfa3036

 * OS: OSX 10.11.4

 * neovim version: v0.2.0

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/Library/Frameworks/Python.framework/Versions/2.7/bin/python2"
  - INFO: Executable: /Library/Frameworks/Python.framework/Versions/2.7/bin/python2
  - INFO: Python2 version: 2.7.11
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3"
  - INFO: Executable: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3
  - INFO: Python3 version: 3.5.1
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin15]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
call plug#begin('~/.nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'raichoo/purescript-vim'
Plug 'FrigoEU/psc-ide-vim'
call plug#end()

let g:psc_ide_syntastic_mode = 1

set completeopt=longest,menuone
set pumheight=8
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.purescript =
      \ ['\w*']

" let g:deoplete#omni_patterns = {}
" let g:deoplete#omni_patterns.purescript = 
 "     \ ['\w*']
```

## The reproduce ways from neovim starting (Required!)
1. Get PureScript build tool: npm install -g pulp purescript
2. Start a purescript project: 
```
mkdir deoplete-test
cd deoplete-test
pulp init
pulp build
```
3. Go into src/Main.purs
4. Start typing something like "comp". This should get completions like compose, composeKleisli, etc (defined in the standard lib). When you use omni_patterns, you'll see that you do get those completions.

**Comment by Shougo** [comment]
> I'm trying to figure out how to get deoplete to work with the omnifunc I wrote in my purescript ide plugin. I get the correct results when I use omni_patterns because both arguments to the omnifunc are what I expect, but when I use input_patterns, the second argument (often called "base" in documentation) is always empty on the second invocation of the omnifunc, so no results ever come back. The first invocation of the omnifunc is as I expect, and I return the correct column number.

It is intended behavior.
The results is cached in omni source to support fuzzy matcher.

**Comment by Shougo** [comment]
To support omni source, the omnifunc should return all candidates(should not filter by `a:base`).
