### ISSUE TITLE
How to turn off suggestions in comment?

### ISSUE THREAD

**Issue by sid-kap** [Shougo/deoplete.nvim#52]
Hi,

I'm working on a cpp file, and when I'm typing a comment, I see suggestions. Is there a way to turn off suggestions when I'm typing in a comment block?

**Comment by Shougo** [comment]
Nothing.
I think it is hard to detect comment region and disable auto completion in comment region is useless.

**Comment by sid-kap** [comment]
Can't we find out whether we're in a comment section from the syntax highlighting?

**Comment by Shougo** [comment]
Yes, it can be detected.
I have implemented it in neocomplcache and neocomplete.
But it is slow and I think it is not useful.
