### ISSUE TITLE
Issue with completion after commit 330f356899ff6e0d01c9466dc3558158b3f9b7a2

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/deoplete.nvim#521]
I seems the commit is responsible for this (new) behaviour:

![jul-26-2017 12-35-25](https://user-images.githubusercontent.com/4171547/28617153-8be93898-71ff-11e7-857f-97f39bc8bf80.gif)

I typed `pa` and now `pa` is third in the list of suggestions. But now every time I get to that third entry it seems to autoselect that value and I have to <TAB> through the list again starting from the beginning of the list. So this way I never get passed the `ra` entry...

It must have something to do with the mentioned commit, because if I revert that the problem is gone. But it seems very difficult to create a small and simple example to reproduce this. It seems it depends a lot on the complete code surrounding the location were the completion is done.

If I just create a new empty file with a few lines of code, I'm unable to generate the same issue. Do hope you can find anything or think of anything based on this description.

**Comment by Shougo** [comment]
Have you read the issue template?
The reproduce ways and the minimal init.vim are required.
I will close the issue if they are not uploaded.

**Comment by Shougo** [comment]
330f356899ff6e0d01c9466dc3558158b3f9b7a2

**Comment by Shougo** [comment]
>  It seems it depends a lot on the complete code surrounding the location were the completion is done.

I think it seems the plugin/configuration conflict.
Please create the minimal vimrc.

**Comment by Shougo** [comment]
It is deoplete problem, you can create the minimal init.vim, does not it?

**Comment by svanharmelen** [comment]
I have read it, and I am trying to find a way to reproduce it... But as I explain that is not straight forward. Still trying to, but it seems the problem is dependent on the whole context of the project that is being worked on. And the project I noticed this with is close source 😞  Still trying to provide more info...

For starters I will create a minimal vimrc that still gives the error with my project. After that I will try to create a project that gives the same error (was already trying that, but it seems hard to know what needs to be there for the problem to show itself).

FYI my deoplete config is:

```
" ====================== deoplete ======================
let g:deoplete#enable_at_startup = 1
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['member', 'tag']
let g:deoplete#max_list = 30
let g:deoplete#sources#go#align_class = 1
let g:deoplete#sources#go#sort_class = ['package', 'func', 'var', 'type', 'const']
call deoplete#custom#set('_', 'converters', ['converter_remove_overlap'])
call deoplete#custom#set('go,neosnippet', 'disabled_syntaxes', ['Comment', 'String'])
imap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<S-TAB>"
```

Will send a minimal vimrc in a bit...

**Comment by Shougo** [comment]
@svanharmelen Why it is only your project?

**Comment by Shougo** [comment]
Please test only below config.

```vim
set rtp+=~/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
OK, reproduced for me.

**Comment by svanharmelen** [comment]
Really?! Wauw, how did you manage to reproduce that so quickly? I failed to come up with some code showing the issue for 20 minutes (by just writing some code from scratch)... Very glad you can see the problem yourself as well now 😀

**Comment by Shougo** [comment]
I just created the minimal test file like this.

```
hoge hogera hogerahoge hoge
```

**Comment by svanharmelen** [comment]
Strange... I did the same, but then with something like this:

```go
package main

type bla struct {}

func main() {
  blaad := ""
  Blaad2 :=

  // and then tried to use those types in an if statement here
}
```

But that didn't give me the problem...

Tested the fix, and it works perfectly!! Thanks for your help is solving this one!!

**Comment by svanharmelen** [comment]
FYI... Personally I think it's wrong to show the currently typed text (the `pa` in my example screen capture above) as a completion suggestion, when that is in fact not a value that exists anywhere else, but only were I just typed it to get a completion.

But at least with this fix it now works again without issues, so I'm good... 👍

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/512

Please read it.
And you can change the behavior by the configuration.

This is the bug.  So it must be fixed.

**Comment by svanharmelen** [comment]
Yeah, I did read it... So I understand where it comes from. Just not sure if I would consider it a bug or working as designed/expected. But like I said, I'm good as is 👍 

Will look at the config to see if I can find how to configure that behaviour.

**Comment by Shougo** [comment]
You can use "matcher_length" for it.

**Comment by svanharmelen** [comment]
Yes, works great! Thanks!
