### ISSUE TITLE
WIldmenu and deoplete conflict?

### ISSUE THREAD

**Issue by bearcatsandor** [Shougo/deoplete.nvim#523]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
When wildmenu is on deoplete conflicts with it, requiring extra keypresses and extraneous output in the command buffer

## Expected
*expected* Enter the command mode, start typing a command and deopete starts showing options

Instead, you don't get options til you press `<tab>` and then wildmenu executes. When wildmenu shows the options you can't navigate them.  If you press `<cntrl-n>` or `<right-arrow>` then deoplete activates and you can navigate those options. However, the wildmenu is still displayed leading to screen clutter.

**If you remove wildmenu** it almost works as expected. You get the deoplete menu showing up, but you still don't get a popup in the command buffer. Perhaps, it's not supposed to and that's a future feature request. 

**Solution** So, please recommend in the readme that wildmenu be deactivated.
## Environment Information

 * deoplete version(SHA1): git

 * OS: 4.12.0-gentoo #6 SMP Sat Jul 8 16:14:59 MDT 2017 x86_64 AMD FX(tm)-6300 Six-Core Processor AuthenticAMD GNU/Linux

 * neovim version: 0.2.0

 * `:CheckHealth` result(neovim ver.0.1.5-452+): https://gist.github.com/bearcatsandor/cb850df900c83c953f2868f466a7de6f

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```
  " deoplete completion begins    
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
  Plug 'Shougo/neco-syntax'           " completion based on syntax file
  Plug 'zchee/deoplete-jedi'          " python
  Plug 'zchee/deoplete-clang'         " c languages
  Plug 'zchee/deoplete-go'            " go language
  Plug 'zchee/deoplete-zsh'           " zsh completion at the file system level
  Plug 'Shougo/neco-vim'              " vim-script
  Plug 'wellle/tmux-complete.vim'     " completion based on open tmux panes

"deoplete.nvim settings
"set runtimepath+=~/path/to/deoplete.nvim/
 let g:deoplete#enable_at_startup = 1
 call deoplete#custom#set('_', 'matchers', ['matcher_full_fuzzy'])
 let g:tmuxcomplete#trigger = ''         " no need for deoplete autotrigger

## The reproduce ways from neovim starting (Required!)

1. enter command buffer with : 
2. (with vim-plug installed) type "Plug"
3. Hit `<tab>`
4. Hit `<cntrl-n>` or `<right arrow>`

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screen shot (if possible)
https://goo.gl/photos/iHYm7dDqqcBEz2Jb9

**Comment by Shougo** [comment]
I cannot reproduce it.
Please use below minimal init.vim.

```vim
set rtp+=~/.cache/dein/repos/github.com/Shougo/deoplete.nvim/
set wildmenu
let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
This is not deoplete related problem.
