### ISSUE TITLE
Support multiple completions per-item

### ISSUE THREAD

**Issue by euclio** [Shougo/deoplete.nvim#527]
Some languages (like Java) allow completing items that haven't actually been imported yet. For example, the textDocument/completion method (https://github.com/Microsoft/language-server-protocol/blob/master/protocol.md#textDocument_completion) of the language server protocol defines additional text edits that could be applied on completion. It would be useful to be able to tell deoplete to perform these additional edits if a specific completion is chosen.

cc https://github.com/autozimu/LanguageClient-neovim/issues/85

**Comment by Shougo** [comment]
I get it.
But it is the completion engine work?
I don't want to add the feature.

**Comment by Shougo** [comment]
LanguageClient-neovim can support the feature by `CompleteDone` autocmd.
But it may conflict with other plugins.
