### ISSUE TITLE
[suggestion] CSS ids/classes autocomplete in HTML files

### ISSUE THREAD

**Issue by tarciozemel** [Shougo/deoplete.nvim#528]
It would be nice if we have CSS ids/classes autocomplete when editing HTML files.

If it sounds good for the project, what about also to support css preprocessors like Sass, to autocomplete functions, mixins, placeholders selectors etc.?

Regards!

**Comment by mike3run** [comment]
@tarciozemel i think what youre looking for is vim-emmet

**Comment by tarciozemel** [comment]
@mike3run I'm not talking about shortcuts to write HTML tags.

I'm talk about, in HTML tags, if I have a `.u-default-module-size` class in CSS, when I start to type "u-default" in HTML, the autocomplete pops and I choose what I need. Also, autocomplete for Sass features, like functions, mixin and so on.

**Comment by Shougo** [comment]
Please upload the example.

**Comment by tarciozemel** [comment]
```sass
/* whatever.scss */
$layout-module-size: rem-calc(30);
.u-padding-right-default { padding-right: $layout-module-size; }
```
```html
<!-- whatever.html -->
<article class="u-pad<!-- autocomplete starts -->
```

**Comment by Shougo** [comment]
You should install and configure context_filetype.vim plugin.
https://github.com/Shougo/context_filetype.vim

```vim
		if !exists('g:context_filetype#same_filetypes')
		  let g:context_filetype#same_filetypes = {}
		endif
		let g:context_filetype#same_filetypes.html = 'css'
```

**Comment by tarciozemel** [comment]
Thank you, @Shougo, but doesn't work. Autocomplete only shows classes already in use in file.

**Comment by Shougo** [comment]
> Thank you, @Shougo, but doesn't work. Autocomplete only shows classes already in use in file.

Html can complete CSS candidates from the buffer.
What is the problem?
Please explain it more clearly.

**Comment by tarciozemel** [comment]
There's no real "problem"; I'm just suggesting CSS ids/classes autocomplete in HTML files like [the example above](https://github.com/Shougo/deoplete.nvim/issues/528#issuecomment-323132575).

I'm just discovering Neovim and testing deoplete, as I work with HTML/CSS a lot, I figured maybe this kind of feature would be nice.

Regards.

**Comment by Shougo** [comment]
It may be useful.
But it is htmlcomplete work.
It is not deoplete work.
