### ISSUE TITLE
On SCSS Property rotate triggers many errors

### ISSUE THREAD

**Issue by mike3run** [Shougo/deoplete.nvim#529]
# Problems summary
When using scss I have found 3 times already when writing the rotate property and hitting tab to expand suggestions that I get a bunch of errors, here are 2 screenshots one of what I was doing and the other of the results:

![screen shot 2017-08-15 at 11 04 16 pm](https://user-images.githubusercontent.com/7088511/29346989-ca582764-820e-11e7-824c-54a6c2269f1e.png)

![screen shot 2017-08-15 at 11 04 10 pm](https://user-images.githubusercontent.com/7088511/29346996-d8744f94-820e-11e7-91ac-b850aeafb98a.png)

## Expected
To work normally like every other property in scss/css

## Environment Information

 * deoplete version(SHA1): Most recent one

 * OS: MacOS 10.12.6

 * neovim version: 0.2.0

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 0ms
  - INFO: $TERM: xterm-256color-italic
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - SUGGESTIONS:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.5.1
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neco-syntax'
Plug 'othree/csscomplete.vim'
Plug 'ervandew/supertab'

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS noci
let g:SuperTabDefaultCompletionType = "<c-n>"

set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. nvim error.scss
 2. Write this:

```css
.body {
  transform: rot<TAB>
}
```
<TAB> means to hit the tab key so supertab gets triggered.

**Comment by Shougo** [comment]
I cannot reproduce the problem.
Please test the minimal vimrc.

```vim
set rtp+=~/work/deoplete.nvim/

let g:deoplete#enable_at_startup = 1
autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
```

**Comment by mike3run** [comment]
@Shougo the last line i have it like

`autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS noci`

compared to

`autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS`

is maybe that the culprit?

**Comment by Shougo** [comment]
No.
The issue means omnifunc returns the wrong candidates.
So please create the more minimal vimrc.
Really supertab and neco-syntax are needed?

**Comment by Shougo** [comment]
And `autocmd FileType css` does not work for scss filetype.
So it is not affected.

**Comment by mike3run** [comment]
@Shougo about neco-syntax i think i just installed because it was yours not really sure what it does haha

about supertab i added it because of this article

https://gregjs.com/vim/2016/neovim-deoplete-jspc-ultisnips-and-tern-a-config-for-kickass-autocompletion/

I'll try to create a more minimal vimrc and get back to you soon

**Comment by Shougo** [comment]
@mike3run Ping.

**Comment by Shougo** [comment]
OK.
