### ISSUE TITLE
Will fuzzy matching on omni functions be available

### ISSUE THREAD

**Issue by expipiplus1** [Shougo/deoplete.nvim#53]
I use neco-ghc and it would be nice to get fuzzy completion on the output it provides. I think this is down for NeoComplete as Shougo/NeoComplete#344
Is or will this be possible with deoplete?

**Comment by Shougo** [comment]
> I think this is down for NeoComplete as Shougo/neocomplete.vim#344

No.  Please read the whole issue.
The fix is reverted and marked as "won't fix".

deoplete implements omni source, but it has same problem.
It is not supported.

**Comment by Shougo** [comment]
neco-ghc source is omnifunc based implementation.
So fuzzy matching cannot be supported.

**Comment by Shougo** [comment]
So, this is the reason that you should create new source for deoplete.

**Comment by Shougo** [comment]
I have added fuzzy match support in neco-ghc.
So, you don't need the feature.

**Comment by expipiplus1** [comment]
Thanks!
