### ISSUE TITLE
How to config the selected completion?

### ISSUE THREAD

**Issue by zhaochy1990** [Shougo/deoplete.nvim#530]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
I used to use youcompleteme, and recently I want to try deoplete. Can deoplete support config the key for select_completion? I don't want to use <Up> and <Down>, instead i'm comfortable with C-j and C-k, just like the `g:ycm_key_list_select_completion` and `g:ycm_key_list_previous_completion`, is there any configuration for this?

**Comment by Shougo** [comment]
You don't need set the variables.

```vim
inoremap <expr><C-j>   pumvisible() ?  "\<C-n>" : "\<C-j>"
inoremap <expr><C-k>   pumvisible() ?  "\<C-p>" : "\<C-k>"
```
