### ISSUE TITLE
Completions starting with underscore are not updated correctly

### ISSUE THREAD

**Issue by wilywampa** [Shougo/deoplete.nvim#531]
# Problems summary

Previous candidates used when the results should be refreshed. In most Python completers, only names not starting with `_` are returned unless the completion input explicitly starts with `_`. When completing some attribute then backspacing until the `.` and typing `_`, the results are not refreshed and no candidates are shown.

## Expected

Refresh the candidates when the start of the input is changed.

## Environment Information (Required!)

 * neocomplete version(SHA1): e90a231140426c7fb8720cf2c9c97a8879c08407

 * OS: macOS Sierra

 * Vim/neovim version: NVIM v0.2.1-689-gd258ac8ed

 * `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

## tmux
  - SUCCESS: escape-time: 50ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.13
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.0.7/libexec/pyenv"
  - INFO: Executable: /Users/jniehus/Documents/dev/py3.6.2env/bin/python3
  - INFO: Python3 version: 3.6.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - WARNING: Gem "neovim" is out-of-date. Installed: 0.4.0, latest: 0.5.0
    - SUGGESTIONS:
      - Run in shell: gem update neovim

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github
```

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
scriptencoding utf8
set runtimepath+=/Users/jniehus/Downloads/dev/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

## Minimal deoplete source with the problem

```python
from .base import Base


class Source(Base):

    def __init__(self, vim):
        super().__init__(vim)
        self.name = 'testing'
        self.mark = '[test]'
        self.is_volatile = True

    def get_complete_position(self, context):
        return 0

    def gather_candidates(self, context):
        if context['input'].startswith('x.'):
            if '._' in context['input']:
                return ['x._foo', 'x._bar']
            return ['x.abc', 'x.efg']
        return []
```

## The reproduce ways from neovim starting (Required!)

 1. Make sure the testing deoplete source is in your runtimepath
 2. Type `x.` and observe the candidates `x.abc` and `x.efg`
 3. Type `_` so the whole input is `x._`. There are no candidates. This is because deoplete is using the previous result, but that causes completions starting with `_` not to show up
 4. Open a new line and type some random text
 5. Go back to the `x._` line and go into insert mode at the end of the line. Now the completion candidates `x._foo` and `x._bar` show up as they should, because deoplete is not using the previous result anymore

Video of the issue: https://vid.me/LLX9i

**Comment by Shougo** [comment]
```vim
let g:deoplete#enable_refresh_always = 1
```

**Comment by wilywampa** [comment]
That is not a solution and it doesn't even work. When I enable that flag and type `x._`, the results do not show up. I still have to type another character then delete it for the results to refresh. The `use_previous_result` method in `rplugin/python3/deoplete/deoplete.py` should be corrected.

**Comment by wilywampa** [comment]
Thanks 👍

**Comment by Shougo** [comment]
Reproduced.
