### ISSUE TITLE
Deoplete source around: do not offer just entered string

### ISSUE THREAD

**Issue by kiryph** [Shougo/deoplete.nvim#532]
# Problems summary

Open an empty buffer and enter `he`, exit insert mode with `<Esc>` and enter insert mode again with `a`. The two letters `he` are offered as a completion candidate.This is not helpful because everything is already entered.

## Expected

Do not provide candidates which are identical to the current word under consideration for completion. They are not useful completion candidatats. `he` to `he`. not a single character has changed.

## Environment Information

 * deoplete version(SHA1): d2e3a2f6a21582225d1230b70b8ae7233adae125

 * OS: macOS Sierra

 * neovim version: nvim 0.21-dev of [vimr Version 0.18.0 (217)](https://github.com/qvacua/vimr)

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

<details> 
  <summary><strong>Click here for health report</strong>
</summary>

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#jedi#check
========================================================================
#### Jedi-vim debug information
Using Python version: 2
 - sys.version: `2.7.10 (default, Jun 10 2015, 19:42:47), [GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]`
 - site module: `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.pyc`
Jedi path: `/Users/kiryph/.cache/vim/dein/.cache/init.vim/.dein/pythonx/jedi/jedi/__init__.py`
 - version: 0.10.2
 - sys_path:
    - `/Library/Python/2.7/site-packages/jedi-0.8.1_final0-py2.7.egg`
    - `/Library/Python/2.7/site-packages/pip-8.1.2-py2.7.egg`
    - `/Library/Python/2.7/site-packages/setuptools-23.0.0-py2.7.egg`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python27.zip`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old`
    - `/usr/local/Cellar/python/2.7.10/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload`
    - `/Users/kiryph/Library/Python/2.7/lib/python/site-packages`
    - `/Library/Python/2.7/site-packages`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python`
    - `/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC`
    - `/opt/gtk/lib/python2.7/site-packages`
    - `/opt/gtk/lib/python2.7/site-packages/gtk-2.0`
    - `_vim_path_`
 - jedi-vim git version: fatal: Not a git repository (or any of the parent directories): .git
 - jedi git submodule status: fatal: Not a git repository (or any of the parent directories): .git

##### Settings
```
g:jedi#popup_on_dot = 0 (default: 1)


  omnifunc=htmlcomplete#CompleteTags
	Last set from ~/.vim-configs/mbp13-osx-7.4.769+lua/vimrc
  completeopt=longest,preview
	Last set from ~/.vim-configs/mbp13-osx-7.4.769+lua/after/ftplugin/markdown.vim
```

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.1.3/libexec/pyenv"
  - WARNING: pyenv is not set up optimally.
    - SUGGESTIONS:
      - Create a virtualenv specifically for Neovim using pyenv, and set `g:python_host_prog`.  This will avoid the need to install Neovim's Python module in each version/virtualenv.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.10
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - SUCCESS: pyenv found: "/usr/local/Cellar/pyenv/1.1.3/libexec/pyenv"
  - WARNING: pyenv is not set up optimally.
    - SUGGESTIONS:
      - Create a virtualenv specifically for Neovim using pyenv, and set `g:python3_host_prog`.  This will avoid the need to install Neovim's Python module in each version/virtualenv.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.2
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

</details>

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Open an empty buffer and enter `he` (possibly already sufficient)
 2. exit insert mode with `<Esc>`
 3. enter insert mode again with `a`

## Screen shot (if possible)

![deoplete-around-complete](https://user-images.githubusercontent.com/371756/29496634-de5c4d1e-85d6-11e7-94b8-112c4eb383d1.png)

**Comment by Shougo** [comment]
`:help deoplete-matcher_length`

https://github.com/Shougo/deoplete.nvim/issues/512

**Comment by kiryph** [comment]
Thanks for your response. I didn't see the issues #512, #521, the option `deoplete-matcher_length` and you have even added a faq item for this:

> Q: I don't want to see the typed word in the completion menu.
>
> A: You should add |deoplete-filter-matcher_length| to the matchers.
>
>	`call deoplete#custom#source('_', 'matchers', ['matcher_fuzzy',
>	'matcher_length'])`

Sorry!

### Regarding the motivation raised in issue #512
I can imagine that this is useful in following situations:
- some sources provide more information such as valid arguments to functions
- get feedback that a certain item exists: examples  could be snippets, (class member) functions, `tags`, `files`, `dictionary`, which the OP of #512 had most likely in mind.

However, I am obviously not sure about the source `around` and similar plain text sources. I am adding the filter`matcher_length` to `around` and some other.

`call deoplete#custom#source('around', 'matchers', ['matcher_fuzzy',	'matcher_length'])`

### Regarding my apparent lack of not noting everything mentioned in the docs
No one reads a documentation of 1500 lines at once. Also `:h deoplete-faq` has 43 items with a current length of 298 lines. Two of them are not really insightful and could be removed
> Q: I want to complete go candidates.
>
> A: You should install deoplete-go source.
> https://github.com/zchee/deoplete-go

> Q: I want to complete AAA using deoplete.
> 
> A: You can create the source for it.  Why don't create the source if you need?

I also think it could be helpful if the faq would be structured as following:

1. **Troubleshooting** (deoplete does not work, vim8, deoplete is slow, popup is not displayed immediately, multiple cursor)
2. **Configuration** (sorting, filtering etc.)
3. **Filetype Specific Configuration** (ruby, c/c++, python/jedi, lua, go, javascript)
4. General Questions (e.g. why dark-powered, is deoplete better than completor.vim, is deoplete faster than neocomplete); I think these are not as important as other items and can be skipped when reading the first time.

What do you think about this?

**Comment by Shougo** [comment]
> I also think it could be helpful if the faq would be structured as following:

The pull request is wellcome.

**Comment by kiryph** [comment]
I have created a pull request #533. Please let me know what you think.
