### ISSUE TITLE
Deoplete API should never hang

### ISSUE THREAD

**Issue by mqudsi** [Shougo/deoplete.nvim#534]
I don't have a reproducible .vim, and I'm not having any problems with deoplete.

The problem is that while some deoplete sources are fully async, others cause the editor to hang when working on massive projects.

I have omnifunc support completely disabled (not set) in deoplete, but using either clang-deoplete or clang-deoplete2 on a large C++ codebase causes the editor to hang/lag in insert mode.

Suggestion: The deoplete API should never hang, no matter how bad the code in a deoplete completion source is.

**Comment by prabirshrestha** [comment]
I think in deoplete source itself should be marked explicitly as async. More details at the end of https://github.com/Shougo/deoplete.nvim/issues/407.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/471
