### ISSUE TITLE
Enable deoplete when InsertEnter

### ISSUE THREAD

**Issue by DerWeh** [Shougo/deoplete.nvim#535]
In the documentation you propose to use 
```
" Enable deoplete when InsertEnter.
let g:deoplete#enable_at_startup = 0
autocmd InsertEnter * call deoplete#enable()
```
for speedup. Sorry if I am wrong, but wouldn't this trigger `call deoplete#enable()` every time insert mode is entered?

Sadly I have hardly any understanding of `vimscript` but I thought something like 
```autocmd InsertEnter * call deoplete#enable() | autocmd! InsertEnter *```
or even 
```
augroup insertload
  autocmd!
  autocmd InsertEnter * call deoplete#enable() | autocmd! insertload
augroup END
```
was needed.

**Comment by Shougo** [comment]
> for speedup. Sorry if I am wrong, but wouldn't this trigger call deoplete#enable() every time insert mode is entered?

Yes.  Your version is better.
But my recommendation is using the plugin manager.
dein.vim supports the feature.
So I have added the simple version.
