### ISSUE TITLE
Deoplete cannot get Go completion from omni

### ISSUE THREAD

**Issue by Akin909** [Shougo/deoplete.nvim#537]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Deoplete throws an error on entering insert mode editing go files, `error is cannot get completions from omni`, hangs unless process exited with ctrl-c. The problem only seems to affect `Go` files, I am able to get completion in other files without the same errors. I have tried re-installing go code

## Expected
Normal autocompletion (N.B was previously working perfectly 1-2 days ago)
Have tried removing all plugins and running with a minimal vimrc provides and error still occurs even with only deoplete, deoplete-go and vim-go installed

## Environment Information

 * deoplete version(SHA1): 4.0

 * OS: MacOS

 * neovim version: 0.2.0

 * `:CheckHealth` result(neovim ver.0.1.5-452+):

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim_typescript#check
========================================================================
## Find Node
  - SUCCESS: node is in $PATH

## Find Local Typescript
  - WARNING: No local server found, using global
    - SUGGESTIONS:
      - Install typescript locally for more accurate tooling
          $ npm install typescript --save-dev

## Find Global Typescript
  - SUCCESS: global tsserver is found

## Check for deoplete
  - SUCCESS: Deoplete is found!

## Check for python 3 bindings
  - SUCCESS: has("python3") was successful

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/Users/A_nonymous/.pyenv/versions/neovim2/bin/python"
  - INFO: Executable: /Users/A_nonymous/.pyenv/versions/neovim2/bin/python
  - INFO: Python2 version: 2.7.11
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/Users/A_nonymous/.pyenv/versions/neovim3/bin/python"
  - INFO: Executable: /Users/A_nonymous/.pyenv/versions/neovim3/bin/python
  - INFO: Python3 version: 3.4.4
  - INFO: python-neovim version: 0.1.13
  - SUCCESS: Latest python-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
  - INFO: Host: /Users/A_nonymous/.rbenv/shims/neovim-ruby-host
  - ERROR: Command error (17) /Users/A_nonymous/.rbenv/shims/neovim-ruby-host --version: /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': dlopen(/usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle, 9): Library not loaded: /usr/local/opt/ruby/lib/libruby.2.4.0.dylib (LoadError)  Referenced from: /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle  Reason: image not found - /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack/msgpack.bundle	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:11:in `rescue in <top (required)>'	from /usr/local/lib/ruby/gems/2.4.0/gems/msgpack-1.0.2/lib/msgpack.rb:8:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.3.1/lib/neovim/session/serializer.rb:2:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.3.1/lib/neovim/session.rb:5:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.3.1/lib/neovim.rb:3:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.3.1/lib/neovim/host.rb:1:in `<top (required)>'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/Cellar/ruby/2.4.1_1/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'	from /usr/local/lib/ruby/gems/2.4.0/gems/neovim-0.3.1/bin/neovim-ruby-host:3:in `<top (required)>'	from /usr/local/bin/neovim-ruby-host:22:in `load'	from /usr/local/bin/neovim-ruby-host:22:in `<main>'
  - ERROR: Failed to run: /Users/A_nonymous/.rbenv/shims/neovim-ruby-host --version
    - SUGGESTIONS:
      - Report this issue with the output of: 
      - /Users/A_nonymous/.rbenv/shims/neovim-ruby-host --version

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
call plug#begin()
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-go', { 'do': ':UpdateRemotePlugins' }
Plug 'fatih/vim-go', { 'do': 'InstallRemoteBinaries' }
call plug#end()
let g:python_host_prog = '/Users/A_nonymous/.pyenv/versions/neovim2/bin/python'
let g:python3_host_prog = '/Users/A_nonymous/.pyenv/versions/neovim3/bin/python'
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)

 1. Open a go file.
 2. Enter Insert Mode

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

I have attempted to create a log but deoplete crashes immediately upon entering insert mode

## Screen shot (if possible)
<img width="1172" alt="screen shot 2017-09-03 at 19 11 57" src="https://user-images.githubusercontent.com/22454918/30005512-086160ee-90dc-11e7-8b27-786b2829e8cf.png">

**Comment by Akin909** [comment]
After further debugging it seems my gocode process was hanging  for some reason some reason so deoplete threw an error. Gonna close this since the error doesn't seem to be related to deoplete.

**Comment by Shougo** [comment]
OK.
