### ISSUE TITLE
deoplete#toggle() only works once

### ISSUE THREAD

**Issue by drzel** [Shougo/deoplete.nvim#539]
# Problems summary
`deoplete#toggle()` only works once, keep toggling on and off and it will fail.

## Expected
to be able to toggle on and off more than once.

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
" Your minimal init.vim
let g:deoplete#enable_at_startup = 0
```

## The reproduce ways from neovim starting (Required!)

`:call deoplete#toggle()`
  Now it's enabled
`:call deoplete#toggle()`
  Now it's disabled
`:call deoplete#toggle()`
  Still disabled

The problem is the `deoplete#enable()` function relies on `deoplete#initialize()` but that doesn't get updated when toggling.

**Comment by Shougo** [comment]
I will fix it.
