### ISSUE TITLE
Detecting Backslashes

### ISSUE THREAD

**Issue by gleachkr** [Shougo/deoplete.nvim#54]
I'm noticing some odd behavior in connection with backslashes. The following settings:

`let g:deoplete#keyword_patterns = {}`
`let g:deoplete#keyword_patterns.tex = '[^\w|\s][a-zA-Z_]\w*'`

will gather the keywords `#test` and `@test`, but not `\test`. The keyword pattern in the docs,

`let g:deoplete#keyword_patterns.tex = '\\?[a-zA-Z_]\w*'`

seems to have a similar issue. It gathers `alpha` but not `\alpha`, when I take it that this regex should match both.

**Comment by Shougo** [comment]
Reproduced.  But I don't expert of Python regex expert.
I cannot fix the pattern...
I think Python's regex feature is very bad than Vim though...

**Comment by Shougo** [comment]
Fixed.   Thanks.
