### ISSUE TITLE
AutoComplPop like behavior

### ISSUE THREAD

**Issue by palango** [Shougo/deoplete.nvim#542]
# Problems summary
I'd like the first item of the auto-completion list to be selected by default. This is what the `neocomplete#enable_auto_select` option does in neocomplete. Do you plan to make this availabe in deoplete as well?

**Comment by ef2k** [comment]
` set completeopt+=noinsert`

See: https://github.com/Shougo/deoplete.nvim/blob/821d375307183ac5c0936a8d4e4ae872dba76a8e/doc/deoplete.txt#L1353

**Comment by palango** [comment]
Thanks!
