### ISSUE TITLE
Cannot disable buffer source

### ISSUE THREAD

**Issue by nadya-p** [Shougo/deoplete.nvim#545]
# Problems summary
I don't manage to disable autocomplete based on the text already in buffer. Maybe I don't use the options correctly.

## Expected
```
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer']
```
Should disable the buffer source.

## Environment Information

 * deoplete version(SHA1):
821d375307183ac5c0936a8d4e4ae872dba76a8e

 * OS:
Windows 7 x64

 * neovim version:
v0.2.0-840-g88112b4c

 * `:CheckHealth` result(neovim ver.0.1.5-452+):
I did run :UpdateRemotePlugins, but somehow there are still remote plugin-related warnings. Nevertheless the remote plugins do work, so presumably this shouldn't be an issue.
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - WARNING: "denite.nvim" is not registered.
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard
  - SUCCESS: Clipboard tool found: win32yank

## Python 2 provider
  - INFO: Using: g:python_host_prog = "C:/Anaconda2/python.exe"
  - INFO: Executable: C:/Anaconda2/python.exe
  - INFO: Python2 version: 2.7.13
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Python 3 provider
  - INFO: Using: g:python3_host_prog = "C:/Anaconda3/python.exe"
  - INFO: Executable: C:/Anaconda3/python.exe
  - INFO: Python3 version: 3.6.0
  - INFO: python.exe-neovim version: 0.1.13
  - SUCCESS: Latest python.exe-neovim is installed: 0.1.13

## Ruby provider
  - WARNING: `ruby` and `gem` must be in $PATH.
    - SUGGESTIONS:
      - Install Ruby and verify that `ruby` and `gem` commands work.
```

## Provide a minimal init.vim

```vim
let g:python_host_prog  = 'C:/Anaconda2/python.exe'
let g:python3_host_prog = 'C:/Anaconda3/python.exe'

execute pathogen#infect()

let g:deoplete#enable_at_startup = 1
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer']
```

## The reproduce ways from neovim starting

 1. switch to insert mode
 2. type 'abcd', space
 3. type 'ab'. Auto-complete with 'abcd' will appear.

## Screen shot
![image](https://user-images.githubusercontent.com/15910645/30581184-8b302f74-9d1f-11e7-827c-90e93e33b0d0.png)

Could you please explain the meaning of '~' and 'A' in the autocomplete window of the screen shot above? Is this really coming from buffer source?

Thank you for your answer, and for your excellent plugins!

**Comment by Shougo** [comment]
> Could you please explain the meaning of '~' and 'A' in the autocomplete window of the screen shot above? Is this really coming from buffer source?

This is around source instead of buffer source.

```
let g:deoplete#ignore_sources = {}
let g:deoplete#ignore_sources._ = ['buffer', 'around']
```

Closing.

**Comment by nadya-p** [comment]
Great, now it behaves as I want. Thank you!
