### ISSUE TITLE
Recommendations for dealing with rplugins?

### ISSUE THREAD

**Issue by mqudsi** [Shougo/deoplete.nvim#547]
One of the reasons deoplete is so awesome is the support for lazy loading plugins. However, I've run into a lot of problems with plugins using the rplugin neovim interface; unless all plugins are loaded when `:UpdateRemotePlugins` is run, rplugins that are installed but not loaded due to deoplete lazy loading are removed from the rplugins.vim file.

Is there a recommendation on how to deal with this or would there have to be some sort of solution worked out on neovim's end?

**Comment by Shougo** [comment]
You can use dein.vim.
Dein.vim has `dein#remote_plugins()`.
It loads the plugins automatically and calls `:UpdateRemotePlugins`.
Note: `call dein#recache_runtimepath()` or `call dein#install()/dein#update()` calls it.

**Comment by Shougo** [comment]
You can use dein.vim.
Dein.vim has `dein#remote_plugins()`.
It loads the plugins automatically and calls `:UpdateRemotePlugins`.
Note: `call dein#recache_runtimepath()` or `call dein#install()/de`

**Comment by mqudsi** [comment]
Thank you.
