### ISSUE TITLE
Slow php completition

### ISSUE THREAD

**Issue by brunoti** [Shougo/deoplete.nvim#549]
Here is my config:

https://github.com/brunoti/vim-config

I'm on a macOS Sierra with NVIM 0.2.0 using the last version of deoplete.

Every time I start writing some code in php I get stuck for 10 to 20 seconds in a "Searching..." state.

How do i solve this problem?

**Comment by Shougo** [comment]
Please update deoplete in the latest version.

**Comment by brunoti** [comment]
@Shougo my version is now updated with the latest commit that is 60bed29fb33cf32a3946509c3e983c2f4a239d40

But the problem still occurs. I'm not saying that this is a bug, but i really don't know what I'm doing wrong or if this is the normal behavior that don't understand.

**Comment by Shougo** [comment]
https://github.com/brunoti/vim-config/blob/187a4577d6ed6d6c7ec50efdaed44a0e8ea0c76f/plugin/deoplete.vim#L26

This is slow.
You should not enable PHP completion.

https://github.com/php-vim/phpcd.vim

It is better though.  I don't know the performance.
