### ISSUE TITLE
deoplete failed to load: Vim(call):E117: Unknown function: _deoplete

### ISSUE THREAD

**Issue by natemurthy** [Shougo/deoplete.nvim#550]
# Problems summary

I am using Vundle for my plugin manager. I recently installed deoplete on my MacBook. I've of followed the installation steps in the project README but now I get this error when launching neovim:
```bash
$ nvim
[deoplete] deoplete failed to load: Vim(call):E117: Unknown function: _deoplete. Try the :UpdateRemotePlugins command and restart Neovim. See also :CheckHealth.
```
So I tried these suggestions. When I run `:UpdateRemotePlugins` in the command bar I get:

![image](https://user-images.githubusercontent.com/1788878/31312236-a1b684a8-ab72-11e7-8b60-67e6f4798b7c.png)

I restart Neovim, and again same `Unknown function: _deoplete` error.

## Expected

No errors when starting `nvim`.

## Environment Information

 * deoplete version(SHA1): `45f23f1586e7edc13c1fafca201a33112a4700f7`
 * OS: `Mac OS X El Capitan 10.11.1`
 * neovim version: `v0.2.0`
 * `:CheckHealth` result(neovim ver.0.1.5-452+): ![gist](https://gist.github.com/natemurthy/e270e215c33205666ee97386d80c5017)

## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
set completeopt+=noinsert
set completeopt+=noselect

let g:python3_host_prog  = '/usr/local/Cellar/python3/3.5.1/bin'

set runtimepath+=~/.vim/bundle/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim starting (Required!)
1. Install deoplete.nvim plugin using Vundle
2. Run `nvim` command and observe error described in problem summary above.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

I followed these exact steps and no new log files were generated in my `/tmp` folder.

## Related issues
I also read these similar issues that have already been resolved, but still no success on my end. It could be that this is a neovim issue and not a problem with the deoplete.nvim plugin. I am unsure.
* https://github.com/Shougo/deoplete.nvim/issues/160
* https://github.com/Shougo/deoplete.nvim/issues/348

**Comment by Shougo** [comment]
It is not deoplete problem.
You should check `:CheckHealth` result.

**Comment by Shougo** [comment]
```
let g:python3_host_prog  = '/usr/local/Cellar/python3/3.5.1/bin'
```

It must be

```
let g:python3_host_prog  = '/usr/local/Cellar/python3/3.5.1/bin/python3'
```

**Comment by natemurthy** [comment]
Thanks! Got it working now

**Comment by manuelcloop** [comment]
Using let g:deoplete#enable_at_startup = 1 works for me without having to set the python3_host_prog variable.

**Comment by AbhimanyuAryan** [comment]
how can I solve this error? My output of `:CheckHealth` is this. I fixed node error but still not sure how to fix other errors 
`let g:python3_host_prog  = '/usr/local/Cellar/python3/3.5.1/bin/python3'` 

where do I keep the above line?

<img width="1387" alt="screen shot 2018-08-08 at 1 39 32 am" src="https://user-images.githubusercontent.com/8083613/43799756-051bc070-9aac-11e8-8868-16db6701d4e8.png">

<img width="1417" alt="screen shot 2018-08-08 at 1 38 56 am" src="https://user-images.githubusercontent.com/8083613/43799755-04d7d4fa-9aac-11e8-8aad-949441f7dbd1.png">

**Comment by JunsikChoi** [comment]
I installed neovim in my local python2 and 3 environment using
`
$pip install neovim --user
$pip3 install neovim --user`

after that, you can provide the path to the python to nvim.

`which python` gives you the path to python command.
`which python3` gives the path of python3.

and you can provide the path in the .vimrc

in the .vimrc file, add
`
let g:python3_host_prog  = 'your python3 path'
let g:python_host_prog = 'your python path'
`
and that solved the deoplete problem for me!

**Comment by nstgc** [comment]
I'm having the same problem.

I have `let g:python3_host_prog  = '/usr/bin/python3'` and `which` returns `python3
/usr/bin/python3`.

I've installed the packages `neovim` and `python-pynvim` from the Arch repo. `:checkhealth` returns
```
deoplete: health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Require Python 3.6.1+ was successful
  - OK: Require msgpack 1.0.0+ was successful
  - INFO: If you're still having problems, try the following commands:
    - $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    - $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    - $ nvim
    - $ cat /tmp/log_{PID}
    - and then create an issue on github
```
and
```
## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.10.2
  - INFO: pynvim version: 0.4.3
  - OK: Latest pynvim is installed.
```

**Comment by Shougo** [comment]
Yes.  `:UpdateRemotePlugins` is needed and it is not executed automatically.
