### ISSUE TITLE
Terminal completion

### ISSUE THREAD

**Issue by rainerborene** [Shougo/deoplete.nvim#551]
It's possible to use strings from a `:term` buffer as source completion?

**Comment by Shougo** [comment]
No.  It cannot.  But deol.nvim supports it in deol edit buffer.
https://github.com/Shougo/deol.nvim

**Comment by khughitt** [comment]
Apologies for commenting on a closed issue, but this seemed like the most appropriate place to ask  --

Is there any possibility of this being added in the future?

This could be useful, for example, to allow completing commands entered into an R console opened via the [Nvim-R](https://github.com/jalvesaq/Nvim-R) plugin.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete-terminal
