### ISSUE TITLE
Neco-vim needs dictionary when defined in goyo, but works when using all sources

### ISSUE THREAD

**Issue by ajmwagar** [Shougo/deoplete.nvim#556]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
neco-look sources works in all file types but not when I set 
let g:deoplete#sources = ['neco-look']

## Expected
it should work when I set it in Goyo.vim (goyo#enter).
But it errors out with Dictionary required. do I need another source?

## Environment Information

 * deoplete version(SHA1):

 * OS:
 Ubuntu 16.04.3 LTS
 * neovim version:
   0.2.0
 * `:CheckHealth` result(neovim ver.0.1.5-452+):
   No errors
## Provide a minimal init.vim with less than 50 lines (Required!)

```vim
function! s:goyo_enter()
   set spell

  let g:deoplete#sources = ['neco-look', 's', 'k']

  set scrolloff=999
  :Limelight
  " ...
endfunction

function! s:goyo_leave()
  "silent !tmux set status on
  "silent !tmux list-panes -F '\#F' | grep -q Z && tmux resize-pane -Z
  let g:deoplete#sources = {}
  set nospell ci si ai list 
  set showmode
  set showcmd
  set scrolloff=5
  :Limelight!
  
endfunction

autocmd! User GoyoEnter nested call <SID>goyo_enter()
autocmd! User   nested call <SID>goyo_leave()

noremap <leader>z :Goyo<return>

" Deoplete
"Use deoplete.
let g:deoplete#enable_at_startup = 1


let g:deoplete#complete_method = 'omnifunc'

inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ deoplete#mappings#manual_complete()
function! s:check_back_space() abort "{{{
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}

```

## The reproduce ways from neovim starting (Required!)

1. install deoplete and neco-look and goyo
1. use my vimrc 
1. call goyo#enter

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
N/A

**Comment by Shougo** [comment]
neco-look source name is "look" instead of "neco-look".

It should be:

```vim
let b:deoplete_sources = ['look']
```

Please read deoplete documentation.
