### ISSUE TITLE
Add support for hints?

### ISSUE THREAD

**Issue by oblitum** [Shougo/deoplete.nvim#557]
LSP supports parameter hints through textDocument/signatureHelp. Here's a recent usecase video demonstration on Sublime Text: https://reviews.llvm.org/D38048#889568. Hints just display information when filling/inspecting parameters but don't insert any text. Vim [complete-items](http://vimdoc.sourceforge.net/htmldoc/insert.html#complete-items) has an `empty` item that serves as flag for showing menu completions even when the `word` item for insertion text is empty. This is useful for showing current parameter information or current prototypes but not offering any completion text for what is displayed in the popup, with popup menu then just serving for display. [I had implemented this for YCM a time long ago](http://nosubstance.me/articles/2015-01-29-better-completion-for-cpp/), even supporting triggers agnostic to surrounding whitespace (such hints are only shown right after the trigger — when the user starts typing after the trigger, hints are gone and normal completion is back, on _my implementation_). There's discussion on the rationale for different kinds of completions at https://reviews.llvm.org/D38048#888461. It may contain useful information on what to do when there's multiple overloads, long prototypes, etc.

I was wondering whether deoplete.nvim could support this (If it doesn't already)? I'm planning to give the plugin a try, coupled to [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) (cc @autozimu).

**Comment by autozimu** [comment]
This looks very interesting.

Let me know if you need any help from my side.

**Comment by Shougo** [comment]
New popup hinsts feature is needed in neovim/Vim.
deoplete cannot support the feature now.

**Comment by Shougo** [comment]
gonvim supports the similar feature.
https://github.com/dzhou121/gonvim

**Comment by oblitum** [comment]
I did know about gonvim but I think I had arguably provided the same in my YCM fork using raw vim/neovim completion by taking advantage of `empty` and multiplexing popup usage.

**Comment by Shougo** [comment]
Hm..
It is not deoplete work.
It should be  LanguageClient-neovim source work.
