### ISSUE TITLE
Python error with neco-ghc

### ISSUE THREAD

**Issue by expipiplus1** [Shougo/deoplete.nvim#56]
# Problem summary
With `filetype=haskell` typing a bad module name and then `.` throws an error in Deoplete

## Expected
No completions are offered

## Environment Information
 * OS: Ubuntu 15.04
 * Neovim version: a3f048e compiled with nix

## Minimal nvimrc

```
set rtp+=~/.nvim/plugged/deoplete.nvim/
set rtp+=~/.nvim/plugged/neco-ghc/

let g:deoplete#enable_at_startup = 1
```

## Reproducable ways from Neovim starting

 1. Start neovim with the minimal vimrc
 2. Set `filetype` to `haskell`
 3. Enter insert mode and type `a` `.`
 4. Observe that deoplete has sent an error to messsages

## Screen shot
One better: https://asciinema.org/a/2e5roz7j4yw2gaizaqqccs1yp

## Log file

http://paste.ubuntu.com/12794160/

**Comment by expipiplus1** [comment]
This also exhibits itself when one types `a` `'`

This leads me to think that this isn't related to module names.

**Comment by Shougo** [comment]
Thanks.  Fixed.

**Comment by expipiplus1** [comment]
Just out of interest, what did this change do?

**Comment by expipiplus1** [comment]
hmm, this doesn't seem to have fixed things. I still get exactly the same behaviour as before.

**Comment by Shougo** [comment]
Please upload `:DeopleteMessages` result.
I just fixed `:DeopleteMessages` error.
Your error is from neco-ghc.

**Comment by expipiplus1** [comment]
Ah, updating neco-ghc seems to have fixed things.
Thanks again.

**Comment by Shougo** [comment]
OK.
