### ISSUE TITLE
Occasional Performance Issues

### ISSUE THREAD

**Issue by amadeus** [Shougo/deoplete.nvim#562]
# Problems summary
Occasional performance lock ups when generating autocomplete results.

This doesn't fit the normal profile of an issue, as I mean't it as more of a question. Basically I am finding that when generating the results, occasionally Vim will lock up while waiting for the results. Is there something I can do debug this a bit and get more information?

## Environment Information

 * deoplete version(SHA1): a47496f
 * OS: macOS
 * neovim/Vim version: Vim 8, patches 1-1238

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

These are my current Deoplete settings:

```vim
let g:deoplete#enable_at_startup = 1
let g:neosnippet#enable_completed_snippet = 1
let g:deoplete#auto_complete_start_length = 1
let g:deoplete#enable_yarp = 1
let g:deoplete#auto_refresh_delay = 100
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.javascript = '[^. *\t]\.\w*'
let g:deoplete#file#enable_buffer_path = 1
```

The plugins I am using

```
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'wokalski/autocomplete-flow'
Plug 'Shougo/neosnippet'
Plug 'Shougo/neosnippet-snippets'
```

**Comment by Shougo** [comment]
You should remove the line and disable omni completion in JavaScript.

```vim
let g:deoplete#omni#input_patterns.javascript = '[^. *\t]\.\w*'
```

It is not asynchronous completion.
autocomplete-flow works in JavaScript without omni completion.

> This doesn't fit the normal profile of an issue, as I mean't it as more of a question. Basically I am finding that when generating the results, occasionally Vim will lock up while waiting for the results. Is there something I can do debug this a bit and get more information?

https://github.com/wokalski/autocomplete-flow/blob/master/rplugin/python3/deoplete/sources/flow.py#L77

The completion is asynchronous, but it waits the result.
If flow binary is slow, your Vim will be slow.
No magic in the world.
You should check your processes CPU usage.

**Comment by amadeus** [comment]
Ahh that fixed it. Thanks!

**Comment by Shougo** [comment]
OK.
