### ISSUE TITLE
Deoplete can't be loaded for an unknown reason.

### ISSUE THREAD

**Issue by J-Liu** [Shougo/deoplete.nvim#563]
# Problems summary
Deoplete can't be loaded for an unknown reason.
What should I do to make deoplete work?

## Environment Information

 * deoplete version(SHA1): not sure

 * OS: macOS 10.13

 * neovim/Vim version:
neovim 0.2.0
vimr  0.19.1 (229)
 * `:checkhealth` or `:CheckHealth` result(neovim only):
```

health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - WARNING: ".dein" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.1.13
  - SUCCESS: Latest python2-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.3
  - INFO: python3-neovim version: 0.1.13
  - SUCCESS: Latest python3-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set nocompatible
let s:dein_path = expand('~/.vim/dein')
set runtimepath+=~/.vim/dein/repos/github.com/Shougo/dein.vim

if dein#load_state(s:dein_path)
  call dein#begin(s:dein_path)

  call dein#add('Shougo/dein.vim')
  call dein#add('morhetz/gruvbox')
  call dein#add('Shougo/deoplete.nvim')
  call dein#add('roxma/nvim-yarp')
  call dein#add('roxma/vim-hug-neovim-rpc')

  call dein#end()
  call dein#save_state()
endif

if dein#check_install()
  call dein#install()
endif

filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)
just type `nvim` or `vimr` in terminal

## Generate a logfile if appropriate
log file didn't created.

**Comment by Shougo** [comment]
We have not ESP skills.

Please describe the problem more clearly.
I think the screencast is better like asciinema.

You can enable deoplete by `call deoplete#enable()` manually.

Hm.

```
## Remote Plugins
  - WARNING: ".dein" is not registered.
  - WARNING: Out of date
    - SUGGESTIONS:
      - Run `:UpdateRemotePlugins`
```

Please execute `:UpdateRemotePlugins` manually.

**Comment by J-Liu** [comment]
Sorry, I tried times again, and get a `ERROR` like this
```
## terminal
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
```
And I don't know how to deal with it.

**Comment by Shougo** [comment]
You should set `TERM` variable.

And what is the `:UpdateRemotePlugins` output?

**Comment by Shougo** [comment]
Another solution: `let g:deoplete#enable_yarp = 1` in your init.vim.

**Comment by Shougo** [comment]
Dup of https://github.com/Shougo/deoplete.nvim/issues/565

**Comment by Shougo** [comment]
@J-Liu I think you have called `deoplete#enable()` in your init.vim.

**Comment by J-Liu** [comment]
@Shougo  May you please tell me how to set the `TERM` variable?  I don't know that.
I have written `let g:deoplete#enable_at_startup = 1` in my init.vim, which called `deoplete#enable()` I think.

**Comment by Shougo** [comment]
>  May you please tell me how to set the TERM variable? I don't know that.

It depends on your terminal.
For example, my `$TERM` is st-256color.

**Comment by J-Liu** [comment]
I add a `let g:deoplete#enable_yarp=1` in my init.vim, deoplete init successfully.
And then, deoplete-jedi works fine.

But, vim-javacomplete2 get something wrong like this
<img width="564" alt="screen shot 2017-11-02 at 2 04 07 pm" src="https://user-images.githubusercontent.com/1065112/32312087-c5fa02e0-bfd6-11e7-9bc3-f7de85f483c5.png">

Should I ask for help to you or artur-shaik?

**Comment by Shougo** [comment]
It is vim-javacomplete error.
You should test the omnifunc manually by `<C-x><C-o>`.

**Comment by J-Liu** [comment]
Thanks, `<C-x><C-o>` still get a problem, I'll open a issue on vim-javacomplete.
