### ISSUE TITLE
Deoplete fails to startup

### ISSUE THREAD

**Issue by czaarek99** [Shougo/deoplete.nvim#565]
# Problems summary
When starting nvim + deoplete with vim-plug it gives the error below and doesn't load:

```bash
czarek@swagmaster ~
  % nvim                                                                                                          !2822
[deoplete] Vim(call):E117: Unknown function: _deoplete_init
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[11]..deoplete#init#_channel, line 12
[deoplete] deoplete failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :CheckHealth.
Press ENTER or type command to continue

```

## Expected
Deoplete loading correctly

## Environment Information

 * deoplete version(SHA1): Don't know how to find this one, it's the latest version as of the first of November though.

 * OS: Arch Linux

 * neovim/Vim version:
```
NVIM v0.2.0
Build type: Release
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.0/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui      
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: Release

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/bin/python2.7"
  - INFO: Executable: /usr/bin/python2.7
  - INFO: Python2 version: 2.7.14
  - INFO: python2.7-neovim version: 0.1.13
  - SUCCESS: Latest python2.7-neovim is installed: 0.1.13

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3.6"
  - INFO: Executable: /usr/bin/python3.6
  - INFO: Python3 version: 3.6.2
  - INFO: python3.6-neovim version: 0.1.13
  - SUCCESS: Latest python3.6-neovim is installed: 0.1.13

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-linux]
  - INFO: Host: /usr/bin/neovim-ruby-host
  - SUCCESS: Latest "neovim" gem is installed: 0.5.1

```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:python_host_prog = '/usr/bin/python2.7'
let g:python3_host_prog = '/usr/bin/python3.6'

if empty(glob('~/.local/share/nvim/site/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.local/share/nvim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1

call deoplete#enable()
```

## The reproduce ways from neovim/Vim starting (Required!)

1. Start nvim from commandline
2. Error happens

## Logfile
https://gist.github.com/czaarek99/ccc7bc88f07f46ca7dfe68be66607e36

**Comment by fredlb** [comment]
I had the same issue today.
I can however run `call deoplete#enable()` after I have started neovim without issue (maybe try that?).
Simply removing that from my init.vim and just keeping `let g:deoplete#enable_at_startup = 1
` seems to have resolved my issue.

**Comment by czaarek99** [comment]
@fredlb Strangely enough after reinstall deoplete like three times it works fine. Calling `deoplete#enable()` still throws the error but autocompletion works just fine. Using your suggestion it works fine.

**Comment by dirn** [comment]
I'm currently pinned to 45f23f1586e7edc13c1fafca201a33112a4700f7 because of this (and some problems with yarp), although the exact error wasn't introduced until 0039ab2c41f459fdc1b3ae514b7f2fa6001cb7a7.

**Comment by czaarek99** [comment]
@dirn You have any idea what causes this? I'd gladly fix the issue myself but if you've already done half of the work I'll take the head start.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/563

It seems the same problem.
Please test `let g:deoplete#enable_yarp = 1`.

I think your rplugin file is broken.
Because, I have renamed the function name.

**Comment by Shougo** [comment]
https://gist.github.com/czaarek99/ccc7bc88f07f46ca7dfe68be66607e36

?

Your logfile seems works.
I don't understand it.
"Deoplete fails to startup", didn't it?

**Comment by Shougo** [comment]
> @fredlb Strangely enough after reinstalling deoplete like three times it works fine. Calling deoplete#enable() still throws the error but autocompletion works just fine. Using your quiets the error and everything works as expected.

Hm.

Please check your rplugin file.
`:scriptnames`

**Comment by Shougo** [comment]
```
						*$NVIM_RPLUGIN_MANIFEST*
Unless $NVIM_RPLUGIN_MANIFEST is set the manifest will be written to a file
named `rplugin.vim` at:

	Unix ~
	  $XDG_DATA_HOME/nvim/ or ~/.local/share/nvim/

	Windows ~
	  $LOCALAPPDATA/nvim/ or ~/AppData/Local/nvim/
```

**Comment by Shougo** [comment]
> I had the same issue today.
I can however run call deoplete#enable() after I have started neovim without issue (maybe try that?).
Simply removing that from my init.vim and just keeping let g:deoplete#enable_at_startup = 1 seems to have resolved my issue.

I get the reason.
I will fix the issue.

**Comment by Shougo** [comment]
```vim
call deoplete#enable()
```

Please remove it in your init.vim.
It causes the problem.

**Comment by Shougo** [comment]
I have fixed the problem.
