### ISSUE TITLE
Help with `g:deoplete#omni#input_patterns`

### ISSUE THREAD

**Issue by guiniol** [Shougo/deoplete.nvim#566]
# Problems summary

I use `vim-ledger` which supports omni completion (https://github.com/ledger/vim-ledger) :
> Go ahead and try something like:
> `As:Ban:Che<C-X><C-O>`
> When you have an account like this, `Assets:Bank:Checking` should show up.

When I do `<C-X><C-O>`, it does work. However, deoplete only completes the last word (after the `:`) and the source indicated is `A` (around ?)

As per the documentation, I put:
`let g:deoplete#omni#input_patterns.ledger = '^\s+([a-zA-Z]+:?)+'` in my configuration, but still deoplete only completes the last word.

Is `input_patterns` not the way to go? How can I get deoplete to use the omni completion provided by vim-ledger?

## Expected

Deoplete completes the whole abbrevation `As:Ban:Che` to `Assets:Bank:Checking`, using the omni completion.

## Environment Information

 * deoplete version(SHA1): a47496f3d68f409112d492649a1deed5493b0cc0

 * OS: Linux (archlinux)

 * neovim/Vim version: NVIM v0.2.1-1122-g54b79f19d

 * `:checkhealth` or `:CheckHealth` result(neovim only): Everything OK except ruby (missing neovim gem)

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

init.vim:
```vim
" Your minimal init.vim/vimrc
set runtimepath+=./deoplete.nvim
set runtimepath += ./vim-ledger
let g:deoplete#enable_at_startup = 1
let g:deoplete#omni#input_patterns = {}
let g:deoplete#omni#input_patterns.ledger = '\s+([a-z]+:?)+'
```

ledger file:
```ledger
; vim:filetype=ledger tabstop=4 shiftwidth=4 expandtab

2017/11/01 test
    Assets:Bank:Checking    -10.00
    Expenses:Food            10.00

2017/11/01 test2
    As:Ban:Che
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open the ledger file and go to the last line
 2. Switch to insert mode using `A`.
 3. deoplete proposes: `Che      [~] A` and `Checking [~] A`
 4. Type <C-X><C-O>. The following omni completions appear: `Assets:Bank:Checking`, `Assets:Bank` and `Assets`

deoplete should show the omni completions without having to press <C-X><C-O>.

## Screenshots

deoplete:
![screenshot from 2017-11-01 16-42-20](https://user-images.githubusercontent.com/3483433/32283086-b5f90aa2-bf23-11e7-97d1-e66a4464aa11.png)

Omni completion:
![screenshot from 2017-11-01 16-42-33](https://user-images.githubusercontent.com/3483433/32283098-be194b48-bf23-11e7-9cf9-52ec15d0691a.png)

**Comment by Shougo** [comment]
```vim
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.ledger = '^\s\+\%([A-Za-z]\+:\?\)\+'
```

Above script works.
I don't know why `g:deoplete#omni#input_patterns` though.

**Comment by Shougo** [comment]
I get it.
vim-ledger does not support omni source.

**Comment by guiniol** [comment]
Thank you for your explanation. I didn't realise that using omni and suporting omni source were different things. I'm sorry!
