### ISSUE TITLE
Multiple errors at startup

### ISSUE THREAD

**Issue by MasterTextman** [Shougo/deoplete.nvim#569]
# Problems summary
Whenever I open vim, these errors are detected:
```
[vim-hug-neovim-rpc] failed executing: python3 import neovim
[vim-hug-neovim-rpc] Vim(python3):Traceback (most recent call last):
[deoplete] [vim-hug-neovim-rpc] requires `:python3 import neovim` command to work
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[11]..deoplete#init#_channel[10]..yarp#cor...fy[1]..yarp#core#wait_channel[5]..yarp#core#jobstart[2]..yarp#pyx#init[13]..yarp#core#serveraddr[1]..neovim_rpc#serveraddr, line 15
```
Since I have Vim, instead of Neovim, I'm unsure whether the error is related to that.

## Expected

I expect deoplete to start up the moment I open a file.
Since `:echo has("python3")` returns `1`, I expect it not to have problems in that area.

## Environment Information

 * deoplete version(SHA1): Unsure what to put here - but it's the latest version. Installed today.

 * OS: Ubuntu 17.04 x86_64

 * neovim/Vim version: Vim 8.0

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'mkitt/tabline.vim'
Plug 'vim-syntastic/syntastic'
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
call plug#end()

...

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Add Plug lines to .vimrc
 2. Install using :PlugInstall
 3. Add "enable_at_startup" line to .vimrc
 4. Open any file.

## Upload the log file
Here's the log file, generated by using `vim -Vtestlog.log`
[testlog.log](https://github.com/Shougo/deoplete.nvim/files/1443252/testlog.log)

**Comment by MasterTextman** [comment]
Solved by running `pip3 install neovim`.

**Comment by Shougo** [comment]
OK.
