### ISSUE TITLE
enable_at_startup seems to be ignored

### ISSUE THREAD

**Issue by mikezaby** [Shougo/deoplete.nvim#57]
I have set `let g:deoplete#enable_at_startup = 1` nvim configurations, but for some reason this setting seems to be ignored. I checked also if this setting has loaded and seems ok
```
let g:deoplete#enable_at_startup  => g:deoplete#enable_at_startup #1
```
 If i enabled manualy with `DeopleteEnable`, the plugin is working.

**Comment by Shougo** [comment]
I think your configuration is wrong.
You should create minimal .nvimrc for it.

**Comment by mikezaby** [comment]
Thanks Shougo, my configuration was the problem. Sorry for the noise.

**Comment by Shougo** [comment]
OK.
