### ISSUE TITLE
Questions not found on Q/A section

### ISSUE THREAD

**Issue by Dbz** [Shougo/deoplete.nvim#571]
# Problems summary

I am new to vim and have some questions that are not covered in the Q/A. Would someone be able to answer them here, and I can make a pull request to update the Q/A section?

1. How do I select one of the responses from the pop up? I assume this is really obvious, but I have not figured it out.

2. How do I change the color scheme of the pop up? With my current color scheme, it is almost impossible to view the pop up and text.

3. What does each part of a line on the pop up mean? For example I see:

`Bree` pops up `Breed [~] A`. What do `[~]` and `A` stand for?

**Comment by Shougo** [comment]
> How do I select one of the responses from the pop up? I assume this is really obvious, but I have not figured it out.

Please press `<C-y>` on the candidate.

> How do I change the color scheme of the pop up? With my current color scheme, it is almost impossible to view the pop up and text.

```vim
highlight Pmenu ctermbg=8 guibg=#606060
highlight PmenuSel ctermbg=1 guifg=#dddd00 guibg=#1f82cd
highlight PmenuSbar ctermbg=0 guibg=#d6d6d6
```

> What does each part of a line on the pop up mean? For example I see:

It is the source mark.
A is from `:help deoplete-source-around`.

**Comment by Shougo** [comment]
I have updated FAQ.

**Comment by Dbz** [comment]
Hey Shougo,

I really appreciate your help. This is an **awesome** vim plugin.
