### ISSUE TITLE
deoplete inserts "<Plug>" when using vim-multiple-cursor

### ISSUE THREAD

**Issue by nirajgup** [Shougo/deoplete.nvim#574]
# Problems summary
When trying to edit a bunch of word using vim-multiple-cursor plugin, deoplete adds '\<Plug\>' after every character is inputted.

## Expected
"\<Plug>\" shouldn't be added while editing using vim-multiple-cursor

## Environment Information

 * deoplete version(SHA1):3c38321017ae888f7807ff61ae98e0f21239bbd2

 * OS: macOS Sierra

 * neovim/Vim version:NVIM v0.2.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins'}
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Install "vim-multiple-cursor" by the following in .vimrc
   - ```Plug 'terryma/vim-multiple-cursors'```
 2. Start any file in vim
 3. Go to any word which appears multiple times
 4. Press "\<c-n\>\<c-n\>\<c-n\>Aabc\<esc\>"
 5. Notice how \<Plug\> gets inserted for after every letter

## Screen shot (if possible)
![screen shot 2017-11-09 at 2 45 30 pm](https://user-images.githubusercontent.com/6980668/32634461-a6dd257e-c560-11e7-8c7e-168a795ac290.png)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/265
