### ISSUE TITLE
Selection in popupmenu gets deselected

### ISSUE THREAD

**Issue by jhzab** [Shougo/deoplete.nvim#575]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary

I'm using deoplete with deoplete-jedi, completions are displayed fine in the popup menu. But when deoplete-jedi is still doing it's thing in the background and only the default completion is shown, then selecting an entry will fail, since it'll get deselected nearly right away.

The problem started with a005af8644c9d4b3dd47a3e2209b9b37b9184136

## Expected

Selection should not get deselected.

## Environment Information

 * deoplete version(SHA1):
3c38321017ae888f7807ff61ae98e0f21239bbd2

 * OS:
Fedora 26

 * neovim/Vim version:
NVIM v0.2.2-9-g9baa7ca37

 * `:checkhealth` or `:CheckHealth` result(neovim only):

> health#deoplete#check
> ========================================================================
> ## deoplete.nvim
>   - OK: has("nvim") was successful
>   - OK: has("python3") was successful
>   - INFO: If you're still having problems, try the following commands:
>     $ export NVIM_PYTHON_LOG_FILE=/tmp/log
>     $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
>     $ nvim
>     $ cat /tmp/log_{PID}
>     and then create an issue on github
> 
> health#nvim#check
> ========================================================================
> ## Configuration
>   - OK: no issues found
> 
> ## Performance
>   - INFO: Build type: Debug
>   - WARNING: Non-optimized build-type. Nvim will be slower.
>     - ADVICE:
>       - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
>       - https://github.com/neovim/neovim/wiki/FAQ
> 
> ## Remote Plugins
>   - OK: Up to date
> 
> ## terminal
>   - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
>   - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
>   - INFO: $XTERM_VERSION=''
>   - INFO: $TERM_PROGRAM=''
>   - INFO: $SSH_TTY=''
> 
> health#provider#check
> ========================================================================
> ## Clipboard (optional)
>   - OK: Clipboard tool found: xclip
> 
> ## Python 2 provider (optional)
>   - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
>   - INFO: Executable: /usr/bin/python2
>   - INFO: Python2 version: 2.7.14
>   - INFO: python2-neovim version: 0.2.0
>   - OK: Latest python2-neovim is installed: 0.2.0
> 
> ## Python 3 provider (optional)
>   - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
>   - INFO: Executable: /usr/bin/python3
>   - INFO: Python3 version: 3.6.2
>   - INFO: python3-neovim version: 0.2.0
>   - OK: Latest python3-neovim is installed: 0.2.0
> 
> ## Ruby provider (optional)
>   - WARNING: `ruby` and `gem` must be in $PATH.
>     - ADVICE:
>       - Install Ruby and verify that `ruby` and `gem` commands work.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

With vim-plug in the autoload directory.
```vim
call plug#begin('~/.config/nvim/bundle')
Plug 'zchee/deoplete-jedi'
Plug 'roxma/nvim-yarp'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#jedi#python_path = "/usr/bin/python3"
```

## The reproduce ways from neovim/Vim starting (Required!)

I was using the following for testing:

```python
#!/usr/bin/python3
import tensorflow as tf

estimator = tf.estimator.Estimator(model_fn=model_fn)
estimator
```

Adding a `.` after estimator will give a popup menu where the selections will get deselected automatically.

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Sorry, it is the feature because of #543.

**Comment by Shougo** [comment]
```vim
set completeopt+=noinsert
```

is needed.

**Comment by Shougo** [comment]
I have tested it, but I cannot reproduced.

**Comment by jhzab** [comment]
Setting `set completeopt+=noinsert` only results in the selection jumping to the first entry in the completion list all the time vs. deselecting any entry.

**Comment by Shougo** [comment]
I don't understand....
I cannot reproduce the problem.
I cannot revert the commit.
