### ISSUE TITLE
Q about pattern matching YCM vs deoplete

### ISSUE THREAD

**Issue by yelled1** [Shougo/deoplete.nvim#576]
Closing below, as I realized that this is not likely the place to ask....

in my Scala (not specific to scala & this is really Qs)
**1st**
val rl = Range(1, 7).toList
rl.s
YCM: give all possible completion list w/ character 's' in it (seq, sum, ..., distinct, isEmpty) // _note i's'Empty & di's'tinct_
deoplete: completion list  only gives ones that starts w/ 's' (seq, sum, scan, size, span, slice)
Is there a way to change this?

**2nd**
deoplete shows more (longer than YCM of possible completion) but an unordered list, while YCM gives an order list of possible completions
what's the logic of deoplete's order?
can this be changed?

**3rd**
A longtime user told me that "deoplete omnifunc source is synchronous b/c of vim's completion API so it does not have an easy workaround."
So, is deoplete only asyc on neovim? On neovim already, but just curious.

4th
Is there any way to force jedi to cache big module like pandas or numpy on deoplete? Put the let g:deoplete#sources#jedi#server_timeout = 90

On my 1st day on deoplete. Much more involved than YCM to configure, but so far more satisfying
Thank you much,

**Comment by Shougo** [comment]
> deoplete: completion list only gives ones that starts w/ 's' (seq, sum, scan, size, span, slice)
Is there a way to change this?

`:help deoplete-filter-matcher_full_fuzzy`

> what's the logic of deoplete's order?
can this be changed?

The default sort is `sorter_rank`.
You can change it.  Please read deoplete documentation.

> So, is deoplete only asyc on neovim? On neovim already, but just curious.

deoplete is async.  But calling Vim function is sync.

> Is there any way to force jedi to cache big module like pandas or numpy on deoplete?

It is not about deoplete question.  It is about deoplete-jedi question.
You should ask it in deoplete-jedi issues.

**Comment by Shougo** [comment]
> Much more involved than YCM to configure, but so far more satisfying Thank you much,

The configuration is deoplete advantage.
