### ISSUE TITLE
Deoplete appears to fail to initialize in vim 8.

### ISSUE THREAD

**Issue by letharion** [Shougo/deoplete.nvim#577]
# Problems summary
Deoplete prints "[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[9].....rp#core#jobstart[2]..yarp#pyx#init[13]..yarp#core#serveraddr[1]..neovim_rpc#serveraddr" to the bottom of the screen, doesn't autocomplete.

## Expected
No error message, autocompletion.

## Environment Information

 * deoplete version(SHA1):
3c38321017ae888f7807ff61ae98e0f21239bbd2

 * OS:
Ubuntu Linux

 * neovim/Vim version:
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  6 2017 11:22:14)
Included patches: 1-1272
Modified by pkg-vim-maintainers@lists.alioth.debian.org
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=/home/ubuntu/.vim/plugins/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('/home/ubuntu/.vim/plugins')
  call dein#begin('/home/ubuntu/.vim/plugins')

  " Let dein manage dein
  " Required:
  call dein#add('/home/ubuntu/.vim/plugins/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here:
  call dein#add('Shougo/neosnippet.vim')
  call dein#add('Shougo/neosnippet-snippets')

  " You can specify revision/branch/tag.
  call dein#add('Shougo/vimshell', { 'rev': '3787e5' })

  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
    call dein#add('roxma/nvim-yarp')
    call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)
Starting vim is enough to generate the error message

However, full details of how I tested this is:
mkdir /tmp/deopletetest
cd /tmp/deopletetest
vagrant init ubuntu/xenial64
vagrant up
vagrant ssh
sudo apt-get remove vim vim-tiny vim-common vim-runtime
sudo add-apt-repository ppa:jonathonf/vim
sudo apt-get update
sudo apt-get install vim
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > installer.sh
sh ./installer.sh ~/.vim/plugins
vim

**Comment by roxma** [comment]
It doesn't look like you're providing full error messages. Use `:messages` to print them.

By the way, it seems the requirements of https://github.com/roxma/vim-hug-neovim-rpc are not statisfied. Read the requirement section and test the installation.

**Comment by letharion** [comment]
```
[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last):
[deoplete] [vim-hug-neovim-rpc] requires `:pythonx import neovim` command to work
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[11]..deoplete#init#_channel[10]..yarp#core#notify[1]..yarp#core#wait_channel[5]..yarp#core#jobstart[2]..yarp#pyx#init[13
]..yarp#core#serveraddr[1]..neovim_rpc#serveraddr, line 15
```
Is the full error message. Thanks, I didn't know how to get it. So it appears the problem is unrelated to deoplete, but fundamentally as @roxma suggested that vim-hug-neovim-rpc is missing requirements.
I missed the part of the deoplete requirements that said vim-hug-neovim-rpc was necessary. My bad.

**Comment by oronge** [comment]
hi, how did you solve it, I encounter the same problem, thanks!

**Comment by Shougo** [comment]
Please read the requirements.
https://github.com/roxma/vim-hug-neovim-rpc/blob/master/README.md#requirements
