### ISSUE TITLE
Completion inserted at the wrong column

### ISSUE THREAD

**Issue by antoyo** [Shougo/deoplete.nvim#58]
Hello.

I started to use [`racer`][1] (I use its `omnifunc` with `deoplete`) with `deoplete` a few days ago, so I am not sure if it is a `racer` issue or a `deoplete` issue.

When I type `::` or `.`, the popup is sometimes not at the right column and the completion is not inserted at the right column.

For instance, if I type the following in `neovim`:

```rust
use std::
```

and choose the first completion (`core_collections` in my case), the result is:

```rust
core_collections
```

instead of the expected:

```rust
use std::core_collections
```

Here is my config:

```vim
" Deoplete
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_smart_case = 1

" Racer
let g:racer_cmd = "/usr/bin/racer"
let $RUST_SRC_PATH = "/usr/src/rust/src/"
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.rust = '[(\.)(::)]'
```

Is my config wrong or is it a bug in `deoplete` or `racer`?

Moreover, if I continue to write, I get the normal completions instead of the completions from `omnifunc`. For instance, after writing:

```rust
use std::c
```

no completions is shown.

Is there a way to continue getting the completions from the `omnifunc`?

Thanks.

[1]: https://github.com/phildawes/racer

**Comment by Shougo** [comment]
> I started to use racer (I use its omnifunc with deoplete) with deoplete a few days ago, so I am not sure if it is a racer issue or a deoplete issue.

You don't have to use the omnifunc.
racer has deoplete source(I have created it).

https://github.com/phildawes/racer

```vim
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.rust = '[(\.)(::)]'
```

Not needed config for deoplete.

**Comment by antoyo** [comment]
I have the same issue without these lines (and I need to use `C-x C-O` to trigger the completion without the `omnifunc`).
I am not sure of how to use `deoplete` with `racer`.
Do I need to use the [`vim-racer`][1] plugin?
If not, how `deoplete` detects when to use `racer`?
What do I need to do to have `racer` completion in `nvim` with `deoplete`?
Thanks for your help.

[1]: https://github.com/racer-rust/vim-racer

**Comment by Shougo** [comment]
> I am not sure of how to use deoplete with racer.

Please add racer project directory into the runtimepath like vim-racer.
To use plugin manager is easy.
deoplete detects it automatically.

> Do I need to use the vim-racer plugin?

It is not needed.  But you must set `g:racer_cmd` and `$RUST_SRC_PATH`.

**Comment by antoyo** [comment]
Thanks a lot.

I just needed the line:

```vim
Plug 'phildawes/racer'
```
