### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by cohomology** [Shougo/deoplete.nvim#580]
I use deoplete-rtags and often get errors from deoplete, like

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 2675118: invalid start byte
../.config/nvim/plugged/deoplete.vim/rplugin/python3/deoplete/deoplete.py, line 135 in gather_results

As I remember correctly, python has an option to ignore those. Is it possible to turn this on?

**Comment by Shougo** [comment]
It is deoplete-rtags error.
https://github.com/fxor/deoplete-rtags/blob/master/rplugin/python3/deoplete/sources/deoplete_rtags.py#L43
Please create the issue for deoplete-rtags.
