### ISSUE TITLE
Redundant completion candidates from buffer

### ISSUE THREAD

**Issue by wickedbinary** [Shougo/deoplete.nvim#582]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
Whenever I type the any two letters, the Pmenu will show up.
Like
![capture du 2017-11-17 13-00-58](https://user-images.githubusercontent.com/13941218/32930271-9fc7f38e-cb98-11e7-85cb-5dde08302827.png)
![capture du 2017-11-17 13-02-01](https://user-images.githubusercontent.com/13941218/32930282-b15ce46a-cb98-11e7-93a2-24784bdd9efc.png)
These candidates are distractive.

## Expected
Get rid of theses candidates.

## Environment Information

 * deoplete version(SHA1): 4.0

 * OS:Ubuntu 16.04 LTS

 * neovim/Vim version: Vim 8.0

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/532

**Comment by wickedbinary** [comment]
Thank you! I've tried to search the issue on github, but didn't find it.
