### ISSUE TITLE
how to make deoplete autocomplete when start typing in python 3

### ISSUE THREAD

**Issue by LaBatata101** [Shougo/deoplete.nvim#583]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
how I make deoplete autocomplete when start typing

## Environment Information

 * deoplete version(SHA1): 4.0

 * OS: lubuntu 16.04 32 bit

 * neovim/Vim version: 0.2.0

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#deoplete#check
========================================================================
## deoplete.nvim
  - SUCCESS: has("nvim") was successful
  - SUCCESS: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - SUCCESS: no issues found

## Performance
  - SUCCESS: Build type: RelWithDebInfo

## Remote Plugins
  - SUCCESS: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - SUCCESS: Clipboard tool found: xsel

## Python 2 provider (optional)
  - INFO: Disabled. g:loaded_python_provider=1

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.5.2
  - INFO: python3-neovim version: 0.2.0
  - SUCCESS: Latest python3-neovim is installed: 0.2.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.1p112 (2016-04-26) [i386-linux-gnu]
  - WARNING: Missing "neovim" gem.
    - SUGGESTIONS:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
call plug#begin('~/.config/nvim/plugged') 

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins'}                                                         
Plug 'zchee/deoplete-jedi' 

filetype plugin indent on
call plug#end()

let g:python3_host_prog = '/usr/bin/python3'               
" disable python 2 support                                 
let g:loaded_python_provider = 1                           
 "let g:deoplete#enable_yarp=1                              
 set runtimepath+=~/.config/nvim/plugged/deoplete.nvim/     
 let g:deoplete#enable_at_startup = 1                       
 autocmd FileType python setlocal omnifunc=python3complete#Complete                            
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
I don't understand your problem.

> how I make deoplete autocomplete when start typing

What is the problem?
I have checked your configuration and it seems works.

**Comment by Shougo** [comment]
I will close the issue if you cannot describe the problem more properly.

**Comment by LaBatata101** [comment]
I want to deoplete start completing without have to hit c-x c-o or any other key.
Like in [YouCompleteMe](https://github.com/Valloric/YouCompleteMe):
![YouCompleteMe GIF demo](http://i.imgur.com/0OP4ood.gif)

**Comment by Shougo** [comment]
The feature is already supported.
Please upload the screenshots using deoplete.
I will check it.

**Comment by LaBatata101** [comment]
[![asciicast](https://asciinema.org/a/149389.png)](https://asciinema.org/a/149389)

**Comment by Shougo** [comment]
Hm.  deoplete seems not work in your screenshot.
I think it is your configuration problem.
Please test it in your mininimal init.vim.

The screenshot is not created using minimal init.vim
Note: statusline plugin is installed.

**Comment by LaBatata101** [comment]
Testing with `minimal.vim` it works, but with my normal `init.vim` doesn't.
Should I test with my other plugins one by one?

**Comment by Shougo** [comment]
> Should I test with my other plugins one by one?

Yes.  It seems configuration or plugins conflict.
