### ISSUE TITLE
Entering insert mode with cursor on word always pops up completion box

### ISSUE THREAD

**Issue by maskedbyte** [Shougo/deoplete.nvim#585]
# Problems summary
Entering insert mode with cursor on any word (except at the first character of the word) always makes the completion box pop up, this is usually unwanted and distracting. It should at least be able to be toggled.

## Expected
Entering insert mode should not activate any completion box until you start typing. YouCompleteMe works as expected; it only pops up the completion list once you start typing in insert mode.

## Environment Information

 * deoplete version(SHA1): Couldn't find instructions on how to get this, but it's currently the latest version (I cloned it earlier today).

 * OS: FreeBSD 11.1-RELEASE

 * neovim/Vim version: NVIM v0.2.3-24-gd9b3ebfed

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/local/bin/python2 does not have the "neovim" module. :help provider-python
    /usr/local/bin/python2.7 does not have the "neovim" module. :help provider-python
    python2.6 not found in search path or not executable.
    /usr/local/bin/python does not have the "neovim" module. :help provider-python
  - ERROR: Python provider error
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/local/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/local/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/local/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
" I'm using vim-plug.
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Open neovim in a blank file with the minimal init.vim.
 2. Write "hello" in insert mode, and a newline.
 3. On the newline, switch to normal mode, and move the cursor at any point (except the beginning) in the word "hello"
 4. Enter insert mode. You will see the completion box popped up with 1 completion in it.

## Generate a logfile if appropriate

This shouldn't need a logfile, right?

## Screen shot (if possible)

![scrot](https://i.imgur.com/y9yPu8M.png)

**Comment by Shougo** [comment]
I should add the option to prevent the feature.
