### ISSUE TITLE
Deoplete sometimes selects a suggestion on its own

### ISSUE THREAD

**Issue by gadkadosh** [Shougo/deoplete.nvim#586]
I have had this issue for some time now, but I still have no idea what might be causing it, nor how to reproduce reliably. So for now I'm posting it here, maybe somebody would have some ideas as to how to proceed.
Basically sometimes, while just typing, deoplete suddenly decides to pick one of the suggestions and completely replace what has been typed. The screencast shows this in a HTML file. While trying to type "steps" deoplete replaces it automatically with "aria-activedescendent". It is then impossible to type this particular word unless I disable deoplete or the source. 
I'm currently using deoplete with autozimu/LanguageClient-neovim, so this could be related and maybe should have been posted there.

Vimrc can be viewed here:
https://github.com/gadkadosh/dotfiles/blob/master/vimrc.symlink

![deopleteissue](https://user-images.githubusercontent.com/32033534/33239093-5aa989c0-d29b-11e7-9878-afe44cd9ea62.gif)

**Comment by Shougo** [comment]
Related problem?

https://github.com/Shougo/deoplete.nvim/issues/575

I cannot reproduce the problem.
Please use git bisect.

**Comment by Shougo** [comment]
> I'm currently using deoplete with autozimu/LanguageClient-neovim, so this could be related and maybe should have been posted there.

Hm.  Please disable LanguageClient-neovim temporary.

**Comment by Shougo** [comment]
It may be timers conflict problem.
LanguageClient-neovim and deoplete use timers.

**Comment by Shougo** [comment]
I want to test the problem.

So please create the minimal init.vim to reproduce the problem.
Please upload the reproduce ways from neovim starting.

**Comment by gadkadosh** [comment]
Hi, sorry, I was away.

1. If I disable LanguageClient-neovim there is no problem, of course. LanguageClient-neovim is the only source I an using.
2. Here is a minimal vimrc:
```
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
"                              minimal init.vim                              "
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

set runtimepath+=~/.local/share/nvim/plugged/deoplete.nvim
set runtimepath+=~/.local/share/nvim/plugged/LanguageClient-neovim

let g:LanguageClient_autoStart = 1
let g:LanguageClient_diagnosticsEnable = 0
let g:LanguageClient_serverCommands = {}

if executable('html-languageserver')
    let g:LanguageClient_serverCommands.html = ['html-languageserver', '--stdio']
endif

let g:deoplete#enable_at_startup = 1

inoremap jj <esc>

echom "minimal vimrc loaded"
```
This requires only deoplete and LanguageClient-neovim as well as 'html-languageserver'
```
npm -g install vscode-html-languageserver-bin
```
Steps to reproduce:
1. Open an html file
2. Make sure LanguageClient is running `:LanguageClientStart`
3. Start typing inside an html tag an attribute like 'step' or 'steps'
4. After a few letters, usually 'e', deoplete starts completing seemingly random stuff. 
5. If you keep typing it continues to add random stuff.

That's the simplest way I found so far. I'll keep looking into it. I'm not familiar with either deoplete or LanguageClient-neovim code, but it seems to me even if LanguageClient-neovim does something strange, why would deoplete start outputting random strings. I might be wrong though.

This is by the way on MacOS 10.13.1, neoVim 0.2.2
Let me know if you can reproduce it.

**Comment by gadkadosh** [comment]
I am also getting sometimes the following, maybe related:

> [deoplete] Traceback (most recent call last):
> [deoplete]   File "/Users/me/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
> [deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
> [deoplete]   File "/Users/me/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 98, in gather_candidates
> [deoplete]     for candidate in candidates:
> [deoplete] TypeError: 'int' object is not iterable
> [deoplete] Could not get completions from: omni.  Use :messages for error details.
> [deoplete] Traceback (most recent call last):
> [deoplete]   File "/Users/me/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 136, in gather_results
> [deoplete]     ctx['candidates'] = source.gather_candidates(ctx)
> [deoplete]   File "/Users/me/.local/share/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete/source/omni.py", line 98, in gather_candidates
> [deoplete]     for candidate in candidates:
> [deoplete] TypeError: 'int' object is not iterable
> [deoplete] Could not get completions from: omni.  Use :messages for error details.
> [deoplete] Too many errors from "omni". This source is disabled until Neovim is restarted.
>

**Comment by Shougo** [comment]
> If I disable LanguageClient-neovim there is no problem, of course. LanguageClient-neovim is the only source I an using.

Oh...

Hm.  The omnifunc seems broken.

What is the omnifunc?

**Comment by Shougo** [comment]
It seems omnifunc conflict.
I will fix the issue.

**Comment by gadkadosh** [comment]
Omnifunc is just `LanguageClient#complete`

**Comment by Shougo** [comment]
OK.

**Comment by gadkadosh** [comment]
Thanks for this fix.

I'm still getting the following errors when starting to edit inside a CSS file:

> [deoplete] NoneType: None
> [deoplete] omni source does not support: LanguageClient#complete.  Use :messages for error details.
> [deoplete] NoneType: None
> [deoplete] You must use g:deoplete#omni_patterns instead..  Use :messages for error details.
> [deoplete] NoneType: None
> [deoplete] omni source does not support: LanguageClient#complete.  Use :messages for error details.
> [deoplete] NoneType: None
> [deoplete] You must use g:deoplete#omni_patterns instead..  Use :messages for error details.

**Comment by Shougo** [comment]
Fixed.
