### ISSUE TITLE
Deoplete completion menu causes UltiSnips/XPTemplate (etc) plugins to become unusuable.

### ISSUE THREAD

**Issue by maskedbyte** [Shougo/deoplete.nvim#587]
# Problems summary
When deoplete suggestion menu pops up, it will block the multiple-cursors-like system of multiple different snippet plugins, making them useless as you will have to manually edit the snippet's identifiers afterwards because they were messed up. Not only that, but for some snippets it can "corrupt" some characters of the snippet afterwards.

The ones I tested were UltiSnips and XPTemplate. They both have the same issue with Deoplete active.

## Expected
Deoplete completion menu popping up should not break various snippets plugins.

## Environment Information

 * deoplete version(SHA1): Still could not find how to get this, but it is up-to-date with branch master as of this issue posting.

 * OS: FreeBSD 11.1-RELEASE

 * neovim/Vim version: NVIM v0.2.3-58-gd109f5645

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - INFO: Build type: Debug
  - WARNING: Non-optimized build-type. Nvim will be slower.
    - ADVICE:
      - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
      - https://github.com/neovim/neovim/wiki/FAQ

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - WARNING: No Python interpreter was found with the neovim module.  Using the first available for diagnostics.
  - WARNING: provider/pythonx: Could not load Python 2:
    /usr/local/bin/python2 does not have the "neovim" module. :help provider-python

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
" I'm using vim-plug.
call plug#begin('~/.local/share/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'drmingdrmer/xptemplate'
" you could also try with ultisnips, it is not an xptemplate problem
call plug#end()

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

Note: Ignore the <BS> signs if you get them, it is not configured enough in the init.vim to fix that

 1. Open a new *.c file.
 2. Type these 2 lines at the top, to seed autocompletion:
```
ptr
ptre
```
 3. On a new line, type `once` and press `<C-\>`. An include guard snippet should appear.
 4. Slowly start typing the word "ptr" and once you type the letters "pt" the deoplete menu should pop up. It will block updating of other instances of the word ptr, leaving them to as pt. This will corrupt parts of the snippet once switching to normal mode. 

It seems like a small problem/hard to notice here, but on my custom snippets (which I didn't add here because it would be painful to set up) which make big use of the multiple-cursor-like feature of various snippets plugins, it can become a big problem by corrupting them and making them nearly unusuable.

## Screen shot (if possible)
![scrot](https://i.imgur.com/Q5YZ71Z.png)

**Comment by Shougo** [comment]
> Slowly start typing the word "ptr" and once you type the letters "pt" the deoplete menu should pop up. It will block updating of other instances of the word ptr, leaving them to as pt. This will corrupt parts of the snippet once switching to normal mode.

I don't understand.

**Comment by Shougo** [comment]
> When deoplete suggestion menu pops up, it will block the multiple-cursors-like system of multiple different snippet plugins

I understand it is the feature.
I cannot fix it.  And it is not auto completion plugin problem.

**Comment by maskedbyte** [comment]
Allow me to explain better:

Snippets plugins update the same word in multiple places in a snippet. So if you have in a snippet, the word `void` twice, if you change the first word `void` in a snippet, it changes any other instances of void. Like a search and replace but in the snippet.

When the *deoplete* menu pops up, it blocks the word changing. This is a deoplete problem because

 1. it happens with multiple snippets plugins (XPTemplate and Ultisnips)
 2. it only happens with deoplete, completion with YouCompleteMe does not cause this problem

I can give a better reproduce example if you need it.

**Comment by Shougo** [comment]
> When the deoplete menu pops up, it blocks the word changing.

deoplete does not lock the changes.
But Vim/neovim locks them.
I cannot fix the problem.

I don't know YouCompleteMe behavior though.

**Comment by Shougo** [comment]
You can set `g:deoplete#enable_refresh_always`.
It is like YouCompleteMe behavior.
It may fix them.

**Comment by maskedbyte** [comment]
Try init.vim with XPTemplate again but this time type malloc<C-\> and start typing a word that will trigger autocomplete popup and you will see better what I mean

**Comment by Shougo** [comment]
> Try init.vim with XPTemplate again but this time type malloc<C-> and start typing a word that will trigger autocomplete popup and you will see better what I mean

No need to try the problem.
I know the reason.

**Comment by maskedbyte** [comment]
If you are still not going to fix it, can you tell me the reason so I can change xptemplate or try to fix local version of deoplete for myself

**Comment by Shougo** [comment]
> If you are still not going to fix it, can you tell me the reason so I can change xptemplate or try to fix local version of deoplete for myself (if you are talking about refresh_always that didn't work)

It seems xptemplate/UltiSnips implementation problem.
But it is hard to fix.  I think.

xptemplate/UltiSnips cannot detect the input when popupmenu is visible.
I think it can be reproduced by Vim default popup menu(`<C-x><C-n>`)
