### ISSUE TITLE
Completion stops when a filename contains a hyphen

### ISSUE THREAD

**Issue by Ifnister** [Shougo/deoplete.nvim#588]
When trying to complete a filename, if it has a hyphen the completion stops as soon as you type the hyphen. It is quite annoying to have to type the complete filename or press CTRL+X CTRL+F to use neovim completion. I tried removing the '-' from isfname as one question in the FAQ was a problem of this kind (no completion after a '=') and the answer was to remove it from isfname, but it has not worked so far. Is there an option to have completion even when there is a filename with a hyphen?

Minimal init.vim:
```
call plug#begin('~/.config/nvim')
Plug 'Shougo/deoplete.nvim'
call plug#end()

"""""""""" Deoplete plugin """"""""""  

"Enable at startup
let g:deoplete#enable_at_startup = 1
"Disable autocomplete
let g:deoplete#disable_auto_complete = 0
"Delay of autocomplete
let g:deoplete#auto_complete_delay=0
"Disable preview window with docstring
set completeopt-=preview
```

**Comment by Shougo** [comment]
I get it.
It is the bug.

**Comment by Ifnister** [comment]
I can give it a try during the weekend if you hint me where to install looking

**Comment by Shougo** [comment]
It can be fixed easily.
Please wait.
