### ISSUE TITLE
On Termux, /tmp is unavailable and deoplete crashes.

### ISSUE THREAD

**Issue by kosciak9** [Shougo/deoplete.nvim#589]
**Warning:  I will close the issue without the minimal init.vim and the reproduce ways.**

# Problems summary
On Termux (Android Terminal Emulator + Environment) there is no /tmp directory so it can't find the LanguageClient.log file.

Log file: 
```
[deoplete] FileNotFoundError: [Errno 2] No such file or directory: '/tmp/LanguageClient.log'
[deoplete] Could not load source: LanguageClientSource.  Use :messages for error details.
```
## Expected
Deoplete working, or at least not making Neovim unusable (errors keep on popping). 

## Environment Information
Neovim on Termux. 
 * deoplete version(SHA1):

 * OS:
Android
 * neovim/Vim version:
neovim 0.2.1-dev
 * `:checkhealth` or `:CheckHealth` result(neovim only):
All good on both Python and Ruby. 
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Start it on Termux 

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by kosciak9** [comment]
Sorry for not filling all the fields (great issue template!) but i'm on phone and it's cumbersome. I can fix it when home.

**Comment by Shougo** [comment]
It is LanguageClient-neovim issue.

https://github.com/autozimu/LanguageClient-neovim/blob/3788e56d12c05a0e18c296e9f5fed603c582070b/rplugin/python3/LanguageClient/logger.py

**Comment by kosciak9** [comment]
You're right. My bad!

**Comment by farisachugthai** [comment]
This problem still exists. Has anyone considered pushing it upstream because it took me a full week to find this issue and there's no reason to just let it sit around

**Comment by Shougo** [comment]
You should report the problem in LanguageClient-neovim issues.
