### ISSUE TITLE
default keyword_patterns takes a really long time to run in some cases

### ISSUE THREAD

**Issue by yshui** [Shougo/deoplete.nvim#591]
Not sure if this is python bug. On my setup, the default keyword_patterns is:

`(?:[a-zA-Z_][a-zA-Z@0-9_À-ÿ]*)*$`

In some cases, for example this:

`re.search(r'(?:[a-zA-Z_][a-zA-Z@0-9_À-ÿ]*)*$', '\tret.length = dbus_message_iter_element_count(${1:DBusMessageIter *iter})(')`

This pattern just taks forever to finish.

Not sure what can be done on deoplete.nvim's side. But just a head up, if you see your neovim python process takes 100% CPU, it's probably because of this.

**Comment by Shougo** [comment]
The problem is solved?

**Comment by yshui** [comment]
Sorry, I just found out it's the LanguageClient-neovim source which changed the pattern.

Here:
https://github.com/autozimu/LanguageClient-neovim/blob/master/rplugin/python3/deoplete/sources/LanguageClientSource.py#L58

It adds the `*` at the end, the original pattern is fine.

**Comment by Shougo** [comment]
Oh, OK.
