### ISSUE TITLE
Completion menu blocks neovim until restart

### ISSUE THREAD

**Issue by unclechu** [Shougo/deoplete.nvim#593]
# Problems summary
When opening completion menu is triggered before previous window is closed completion menu never close, I can't do anything to close it and I can't go to *insert* mode, only restart can help. I have this bug happens from time to time for more than a year but only now I realized how to reproduce it by direct actions.

## Environment Information

 * deoplete version(SHA1):
    9d048047807b7bfacd7406ebe85acdb1dc019018

 * OS:
    Fedora Workstation 25

 * neovim/Vim version:
    `redir @+ | :ve | redir END`
    ```
    NVIM v0.2.0
    Build type: Debug
    Compilation: /usr/bin/cc -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/config -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/src -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/.deps/usr/include -I/usr/include -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/src/nvim/auto -I/home/unclechu/.compile_n_build/neovim/neovim-v0.2.0-from-git/build/include
    Compiled by unclechu@fedorafarm25

    Optional features included (+) or not (-): +acl   +iconv    +jemalloc +tui
    For differences from Vim, see :help vim-differences

       system vimrc file: "$VIM/sysinit.vim"
      fall-back for $VIM: "/home/unclechu/neovim-v0.2.0-from-git/share/nvim"
    ```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
    ```
    health#nvim#check
    ========================================================================
    ## Configuration
      - SUCCESS: no issues found

    ## Performance
      - INFO: Build type: Debug
      - WARNING: Non-optimized build-type. Nvim will be slower.
        - SUGGESTIONS:
          - Install a different Nvim package, or rebuild with `CMAKE_BUILD_TYPE=RelWithDebInfo`.
          - https://github.com/neovim/neovim/wiki/FAQ

    ## Remote Plugins
      - SUCCESS: Up to date

    ## terminal
      - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
      - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

    health#provider#check
    ========================================================================
    ## Clipboard (optional)
      - SUCCESS: Clipboard tool found: xsel

    ## Python 2 provider (optional)
      - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
      - INFO: Executable: /usr/bin/python2
      - INFO: Python2 version: 2.7.13
      - INFO: python2-neovim version: 0.1.13 (outdated; from /usr/lib/python2.7/site-packages/neovim)
      - WARNING: Latest python2-neovim is NOT installed: 0.2.0

    ## Python 3 provider (optional)
      - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
      - INFO: Executable: /usr/bin/python3
      - INFO: Python3 version: 3.5.4
      - INFO: python3-neovim version: 0.1.13 (outdated; from /usr/lib/python3.5/site-packages/neovim)
      - WARNING: Latest python3-neovim is NOT installed: 0.2.0

    ## Ruby provider (optional)
      - WARNING: `ruby` and `gem` must be in $PATH.
        - SUGGESTIONS:
          - Install Ruby and verify that `ruby` and `gem` commands work.

    health#deoplete#check
    ========================================================================
    ## deoplete.nvim
      - SUCCESS: has("nvim") was successful
      - SUCCESS: has("python3") was successful
      - INFO: If you're still having problems, try the following commands:
        $ export NVIM_PYTHON_LOG_FILE=/tmp/log
        $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
        $ nvim
        $ cat /tmp/log_{PID}
        and then create an issue on github
    ```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
se rtp+=$HOME/.config/nvim/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#disable_auto_complete = 1
inoremap <expr> <A-n> deoplete#manual_complete()
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Create new buffer with three words: `foo`, `bar` and `baz`
 2. Type `b` and press **^N** to call default completion menu
 3. Then, while completion menu is still opened, - press **Alt-n**
 4. Press **Esc** and see that completion menu isn't closed, now you can't close it anyhow anymore, only full restart of neovim will help, also if you try to enter insert mode you get an error *"not allowed here"*

## Screen ~~shot~~ cast

https://youtu.be/RoTMaJLpnVA

## Upload the log file

[nvim-debug-log_py3_rplugin.gz](https://github.com/Shougo/deoplete.nvim/files/1544551/nvim-debug-log_py3_rplugin.gz)

**Comment by Shougo** [comment]
> https://youtu.be/RoTMaJLpnVA

The video quality 360p is very bad.
I cannot see the problem.

**Comment by Shougo** [comment]
I have tested it.
But I cannot reproduce the problem.

**Comment by Shougo** [comment]
> NVIM v0.2.0

Hm.  It is too old.

>   - INFO: python3-neovim version: 0.1.13 (outdated; from /usr/lib/python3.5/site-packages/neovim)
>  - WARNING: Latest python3-neovim is NOT installed: 0.2.0

outdated.

**Comment by Shougo** [comment]
> Press Esc and see that completion menu isn't closed, now you can't close it anyhow anymore, only full restart of neovim will help, also if you try to enter insert mode you get an error "not allowed here"

It seems freezed.
I cannot reproduce it though.

**Comment by Shougo** [comment]
Hm.  I have looked the screencast.  It seems not deoplete bug.
It is neovim bug.
It should be reported in neovim issues.

**Comment by unclechu** [comment]
@Shougo okay, I'll build nightly Neovim soon, try to reproduce it and report here then.

*P.S. I use this old version because `0.2.1` and `0.2.2` have a rendering bug with `termguicolors`, I'm waiting for `0.2.3` release where it supposed to be fixed.*

**Comment by unclechu** [comment]
And about the screencast, I guess it still was rendering at the time you were watching it, now it's available up to 1080p.

**Comment by unclechu** [comment]
@Shougo I cannot reproduce it with latest nightly [Neovim `v0.2.3-dev`](https://github.com/neovim/neovim/commit/8813b29cec13f7410427fbb8913d3753dd6626a7). So, it is fixed in newest Neovim, also it isn't related to `python2-neovim` nor `python3-neovim`. Thank you for clarifying this!

**Comment by Shougo** [comment]
OK.
