### ISSUE TITLE
"call deoplete#enable()" does not work

### ISSUE THREAD

**Issue by otmichael** [Shougo/deoplete.nvim#594]
In my init.vim I had
`call deoplete#enable()`
per the README's instructions, however deoplete was not working. Immediately after switching to
`let g:deoplete#enable_at_startup = 1`,
deoplete became functional.

If this isn't just an issue with my setup, I suggest updating the readme.

**Comment by Shougo** [comment]
Please upload the minimal init.vim and the reproduce ways.
I will test it.

**Comment by Shougo** [comment]
OK.  Reproduced.
I will fix it.

**Comment by Shougo** [comment]
Hm...
Related issue: https://github.com/Shougo/deoplete.nvim/issues/570
