### ISSUE TITLE
breaks undo with this setting in gvim

### ISSUE THREAD

**Issue by lilydjwg** [Shougo/deoplete.nvim#598]
# Problems summary

With the provided setting and gvim, nearly every typing in inside mode creates an undo point: type some text, then when I undo, I see typed characters are removed one by one (or two).

## Expected
The entire inserted text should be removed. In a terminal it behaves as expected.

## Environment Information

 * deoplete version(SHA1): 9d048047807b7bfacd7406ebe85acdb1dc019018

 * OS: Arch Linux

 * neovim/Vim version: 8.0.1387

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
autocmd CursorHoldI * call feedkeys("\<C-g>u", 'nt')
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. open gvim
 2. `i` to enter insert mode, and type some text quickly (like `lksdjfh auijhfna ;ksjdhfiuo`)
 3. `Esc` to normal, press `u` repeatedly

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
[log.zip](https://github.com/Shougo/deoplete.nvim/files/1562186/log.zip)

**Comment by Shougo** [comment]
breaks undo is not deoplete problem.
It is Vim problem.

So I cannot fix it.

**Comment by lilydjwg** [comment]
OK, do you know a minimal case to reproduce this?

**Comment by Shougo** [comment]
deoplete just calls `complete()` internally, so it can be reproduced by using `complete()`.

**Comment by Shougo** [comment]
And please use the latest version of vim-hug-neovim-rpc.
It is updated today.

**Comment by Shougo** [comment]
Ah, it is reproduced on GVim.
Yes.
It seems GUI related problem.

**Comment by lilydjwg** [comment]
vim-hug-neovim-rpc should be latest, because I cloned today.

**Comment by Shougo** [comment]
I think `call feedkeys()` is broken.

If I removed the line, it is not reproduced.

**Comment by Shougo** [comment]
> deoplete just calls complete() internally, so it can be reproduced by using complete().

It is reproduced using omnifunc.
So it is popupmenu behavior problem.
I think it is reproduced by other completions.

**Comment by lilydjwg** [comment]
No, completion is irrelavant. It's caused by timers and some timing.. I'll open an issue for Vim.

**Comment by Shougo** [comment]
OK.
