### ISSUE TITLE
Error on entering Insert mode

### ISSUE THREAD

**Issue by khalidchawtany** [Shougo/deoplete.nvim#6]
I don't know whether I should report this error here or on **neovim**. However, you are the maintainer of the python3 on **neovim** too :)

I have a heavily configured **nvimrc**. If I start ```nvim``` normally I get the following error every time I get into insert mode. However, if I start with ```nvim -u nvimrc_other``` I don't get any errors, knowing that both of ```nvimrc``` and ```nvimrc_other``` has the same content.

```
Error detected while processing InsertEnter Auto commands for "*":
E121: Undefined variable: g:deoplete#_channel_id
```

**Comment by Shougo** [comment]
Please execute `:UpdateRemotePlugins` command.
I think `DeopleteInitializePython` calls error.

**Comment by HerringtonDarkholme** [comment]
Thank you! I also encounter this problem.

Everything goes well after `UpdateRemotePlugins`.

**Comment by khalidchawtany** [comment]
Yep, @Shougo if I run ``` :UpdateRemotePlugins ``` **, I get the following errors:

Here is the python [error report gist](https://gist.github.com/khalidchawtany/6d219535e8832b776868#file-neovim-python-error):

![screen shot 2015-06-12 at 09 36 05](https://cloud.githubusercontent.com/assets/1681606/8124644/81affbcc-10e6-11e5-8064-483acf867b87.png)

**Comment by khalidchawtany** [comment]
If **nvimrc** contains this minimal config as shown in the screenshot, then no error is shown:

![screen shot 2015-06-12 at 09 48 23](https://cloud.githubusercontent.com/assets/1681606/8124833/5334203c-10e8-11e5-9505-150f05ff822b.png)

**Comment by Shougo** [comment]
The crash seems your Python binary problem.
It is not neovim and deoplete problem.

You should check your Python binary.
