### ISSUE TITLE
Preview on completion do not shows correctly with tern_for_vim

### ISSUE THREAD

**Issue by popkirby** [Shougo/deoplete.nvim#60]
In the preview window, '\n' shows up directory instead of new line.

I don't know how neovim/vim shows up preview, but in `tern#PreviewInfo` tern_for_vim uses `split('\n')` , this may causes the problem.

## Expected
![2015-10-19 14 45 43](https://cloud.githubusercontent.com/assets/433373/10570646/1d1f9794-7671-11e5-9112-dcbafa7996f1.png)
(obtained by `<C-x><C-o>`)

## Observed
![2015-10-19 14 45 15](https://cloud.githubusercontent.com/assets/433373/10570651/2bc68136-7671-11e5-88a5-b4fe0ef19299.png)

## Environment
OS: Mac OS X 10.10.4
Neovim version: 0.0.0-alpha+201510120701

## minimal nvimrc
```
if has('vim_starting')
  set runtimepath-=~/.vim
  set runtimepath^=~/vim-test/vim
  set runtimepath^=~/vim-test/vim/bundle/neobundle.vim
endif

let s:neobundle_dir = expand('~/vim-test/vim/bundle')

let g:neobundle#types#git#default_protocol = 'https'

call neobundle#begin(s:neobundle_dir)

NeoBundleFetch 'Shougo/neobundle.vim'

NeoBundle 'Shougo/deoplete.nvim'

NeoBundle 'marijnh/tern_for_vim', {
      \ 'build' : {
      \   'mac' : 'npm install'
      \ }}

filetype plugin indent on

call neobundle#end()

let g:deoplete#enable_at_startup = 1
```

## Reproduce ways
1. nvim -u minimal.vimrc
2. `setf javascript`
3. input below:
```
var a = 10;
a.
```
4. deoplete.nvim shows preview including '\n'
5. `<C-x><C-o>` shows preview including break line instead of '\n'

**Comment by Shougo** [comment]
Thanks.  I will fix it.

**Comment by Shougo** [comment]
Fixed.  Please test it.

**Comment by popkirby** [comment]
Thanks!

**Comment by alnjxn** [comment]
@popkirby have you found a way to disable the tern preview window entirely? By default it should not appear, but it is for deoplete in neovim. Thanks.

**Comment by Shougo** [comment]
@alnjxn `set completeopt-=preview`

**Comment by alnjxn** [comment]
@Shougo thank you!
