### ISSUE TITLE
Open bracket on autocomplete.

### ISSUE THREAD

**Issue by karambaq** [Shougo/deoplete.nvim#604]
How can I enable autocomplete open bracket after selecting something?

I choose function by arrows:
![image](https://user-images.githubusercontent.com/14233969/34621475-5ab72b50-f25a-11e7-886c-1bfd0f8a62c7.png)

Then press enter:

![image](https://user-images.githubusercontent.com/14233969/34621505-76c6ea6a-f25a-11e7-8598-cbbdaa6bea8a.png)

    if has('nvim')
      Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
    else
      Plug 'Shougo/deoplete.nvim'
      Plug 'roxma/nvim-yarp'
      Plug 'roxma/vim-hug-neovim-rpc'
    endif
    Plug 'zchee/deoplete-jedi'
    Plug 'Shougo/echodoc.vim' 
    Plug 'Shougo/neopairs.vim'

    let g:deoplete#enable_at_startup = 1
    let g:deoplete#sources#jedi#popup_select_first = 1
    let g:deoplete#enable_ignore_case = 1
    let g:deoplete#sources#jedi#show_call_signatures = 0
    let g:echodoc#enable_at_startup = 1
    let g:deoplete#sources#jedi#enable_cache = 1
    set completeopt+=noinsert 
    set completeopt-=preview

**Comment by Shougo** [comment]
deoplete does not support the feature.
But neosnippet plugin supports it.

`:help g:neosnippet#enable_completed_snippet`
I think it is not auto completion plugin work.

**Comment by karambaq** [comment]
@Shougo I use neovim and it doesn't support lua :(

**Comment by Shougo** [comment]
> @Shougo I use neovim and it doesn't support lua :(

Why lua is needed?
I don't understand.

**Comment by karambaq** [comment]
@Shougo When I try :NeoCompleteEnable it says: neocomplete does not work with this version of vim. neocomplete requires 7.3.885 or later with Lua support ("+lua")

**Comment by Shougo** [comment]
Yes, neocomplete needs Lua.
But deoplete does not need Lua.

**Comment by Shougo** [comment]
* Install neosnippet

* Set `g:neosnippet#enable_completed_snippet`

* Select the candidate

* Press the snippet expand key
