### ISSUE TITLE
infinite loop

### ISSUE THREAD

**Issue by itachi-59** [Shougo/deoplete.nvim#605]
# Problems summary

hi i have a problem with deoplete in vim deoplete make a loop infinite when i start vim until i end it, and he planted other plugin ( nerdtree, and vim-airline)

## Expected
i dont understand the error message

 * OS: xubuntu xenial

 * neovim/Vim version: vim 8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
vimrc

call plug#begin('~/.vim/plugged')
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'scrooloose/nerdtree'
call plug#end()


```

## Upload the log file

[deoplete.txt](https://github.com/Shougo/deoplete.nvim/files/1609104/deoplete.txt)

**Comment by Shougo** [comment]
I cannot reproduce the problem.

Why `nerdtree` is needed?
Please test it without nerdtree.

**Comment by Shougo** [comment]
> hi i have a problem with deoplete in vim deoplete make a loop infinite when i start vim until i end it, and he planted other plugin ( nerdtree, and vim-airline)

Why the minimal vimrc does not contain vim-airline?
Have you tried the minimal vimrc?

**Comment by itachi-59** [comment]
it's ok i install vim like that https://gist.github.com/odiumediae/3b22d09b62e9acb7788baf6fdbb77cf8 and fixed my isssue. python3 wasnt activate in vim..

**Comment by Shougo** [comment]
OK.
