### ISSUE TITLE
deoplete vs ycm: comparision

### ISSUE THREAD

**Issue by robgrzel** [Shougo/deoplete.nvim#606]
Hi!

1. What are general pros and cons of deoplete over ycm?
2. Ycm is in c, right? So is it faster?
3. Deoplete is python? 
4. What snippet should I use with deoplete? Neosnippet? How is it compared to utilsnips?
5. Is deoplete more like for windows or ubuntu?
6. What languages is deoplete made for specially? Could It handle c language better that ycm? 
7. What is limit of lines that deoplete works efficiently?

**Comment by Shougo** [comment]
> Ycm is in c, right? So is it faster?

Yes.  It is not always faster though.

> Deoplete is python?

Yes.

> What snippet should I use with deoplete? Neosnippet? How is it compared to utilsnips?

neosnippet is better.
https://github.com/Shougo/neosnippet.vim/issues/365

> Is deoplete more like for windows or ubuntu?

In Ubuntu is tested well.  In Windows is experimental and slower.

> What languages is deoplete made for specially? Could It handle c language better that ycm?

Python and Go support is very well.
C language completion is better in YouCompleteMe.

You can test deoplete-clang or deoplete-clang2 though.
Or you can create it!

> What is limit of lines that deoplete works efficiently?

Below 10000 lines are recommended.

**Comment by Shougo** [comment]
> What are general pros and cons of deoplete over ycm?

Pros:

* More configurable.
* No build is needed.
* Less memory.
* Less disk usage
* You can develop/add deoplete sources easily

Cons.

* C/C++ support is weak
* May be slower
* No jump feature
* neovim/Vim8 needed

**Comment by AdamSLevy** [comment]
Is it possible to use both plugins but use them for different languages?

For example, use deoplete with vim-go and gopls for golang but use YCM for c based languages.

**Comment by Shougo** [comment]
You can disable  deoplete in specific languages like this:

```vim
autocmd FileType c,cpp
\ call deoplete#custom#buffer_option('auto_complete', v:false)
```

**Comment by AdamSLevy** [comment]
Thank you. Between that and simply not building golang support for ycm
achieves what I'm looking for.

**Comment by Shougo** [comment]
I don't know about YCM side's configuration.
