### ISSUE TITLE
Completion does not work using context_filetype.vim + LanguageClient-neovim in Vue.

### ISSUE THREAD

**Issue by yymm** [Shougo/deoplete.nvim#609]
## Expected

I want to show both complement candidates.

## Environment Information

 * deoplete version(SHA1): c4b02eb
 * OS: Ubuntu 16.04
 * neovim/Vim version:  v0.2.3-dev
 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

use vim-plug

```vim
call plug#begin('~/.vim/plugged')

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'Shougo/context_filetype.vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/neosnippet-snippets'
Plug 'Shougo/neosnippet.vim'
Plug 'posva/vim-vue'

call plug#end()

let g:deoplete#enable_at_startup = 1

set hidden

let g:LanguageClient_serverCommands = {
    \ 'vue': ['vls'],
    \ }
```

setup environment (require: [nvm](https://github.com/creationix/nvm))

```
$ nvm install --lts
$ nvm use --lts
$ npm install -g vue-cli vue-language-server
$ vue init webpack-simple <project_name>
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. nvim <project_name>/src/App.vue
 2. edit <template> ~ </template>
 3. input <div and div
 4. try 1~3 loading context_filetype.vim or not

use context_filetype.vim

![ct](https://user-images.githubusercontent.com/1256685/34912844-d21c308e-f92e-11e7-930c-a54358577ed5.gif)

not use context_filetype.vim

![nct](https://user-images.githubusercontent.com/1256685/34912847-da6bf044-f92e-11e7-895d-f6763bc9a119.gif)

**Comment by Shougo** [comment]
Please set `g:LanguageClient_serverCommands` in html filetype.
If you use context_filetype.vim, filetype will be changed to `html`.
But `g:LanguageClient_serverCommands['html']` is not set.
So `LC` candidates are disabled.
