### ISSUE TITLE
Provide a way to reload a plugin/source

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#613]
I would like to have a function that would reload an already loaded source.

My use case is reloading deoplete-jedi, for it to pick up a changed `$VIRTUAL_ENV` setting.
This appears to be used by deoplete-jedi's server, and therefore reloading the deoplete-jedi source should also trigger restarting of this server.

/cc @tweekmonster

**Comment by Shougo** [comment]
I don't think it is needed for deoplete.

deoplete-source can detect the changes and restart the server automatically.
