### ISSUE TITLE
Reconfigure/disable logging

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#615]
While looking at https://github.com/Shougo/deoplete.nvim/pull/614 I've noticed that it is not possible to disable or re-configure logging, although that should be possible.

The only problem I see is that e.g. deoplete-jedi uses deoplete's file handler for its server's logging, which would need to be restarted for logging changes.
This could be achieved either by calling "Init" again (not that nice), or having a new event for when logging config changes.

**Comment by Shougo** [comment]
I don't want to add the feature.
But the PR is wellcome.

It should be implemented after https://github.com/Shougo/deoplete.nvim/pull/602.
