### ISSUE TITLE
Cann't start deoplete.nvim on Vim 8

### ISSUE THREAD

**Issue by o01eg** [Shougo/deoplete.nvim#616]
# Problems summary

Deoplete cann't start and `:call deoplete#enable()` produces error:

```
[deoplete] Vim(let):E716: Key not present in Dictionary: 2
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[19]..deoplete#init#_channel[10]..yarp#core#notify[1]..yarp#core#wait
_channel[21]..neovim_rpc#_on_stderr, line 2
```

## Expected

Successfull launch.

## Environment Information

 * deoplete version(SHA1): a338ca8bbee086cc7b9265ae181f22de86d38491

 * vim-hug-neovim-rpc version(SHA1) : 60093847f0ba0a57ace54df30bd17a8239a99d6f

 * nvim-yarp version(SHA1): b222af8dbbfb35c6d833fd76a940f6ca2fe322fa

 * OS: Gentoo Linux AMD64

 * neovim/Vim version: Vim 8.0.1298

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal .vimrc with less than 50 lines (Required!)

```vim
set rtp+=~/.vim/bundle/deoplete.nvim
set rtp+=~/.vim/bundle/nvim-yarp
set rtp+=~/.vim/bundle/vim-hug-neovim-rpc

" Use deoplete.
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from Vim starting (Required!)

 1. Install `Shougo/deoplete.nvim`, `roxma/nvim-yarp`, `roxma/vim-hug-neovim-rpc`
 2. Run `:call deoplete#enable()`

## Upload the log file

[nvim_log_py3_neovim_rpc_server.log](https://github.com/Shougo/deoplete.nvim/files/1669012/nvim_log_py3_neovim_rpc_server.log)

**Comment by Shougo** [comment]
I don't know the error.

Hm.  The channel process is crashed.

It should be reported in vim-hug-neovim-rpc.
