### ISSUE TITLE
Erratic Cursor Flickering

### ISSUE THREAD

**Issue by amadeus** [Shougo/deoplete.nvim#617]
# Problems summary
It appears that Deoplete, or one of it's Vim compatibility dependencies, causes erratic cursor flickering when idling in normal or insert mode.

Based on the output below, it appears a lambda is being called quite frequently even on idle, when there should be no reason for it to be called. I've included a couple videos of with deoplete enabled and with it disabled. I've also included a basic log output for what vim is doing.

## Expected
Cursor should blink normally. Especially if there is nothing to complete or results to display.

## Environment Information

 * deoplete version(SHA1): 2d7e8e367666aff4ae6bb11864ef7fe142b78ac0 (latest on master)

 * OS: macOS

 * neovim/Vim version: MacVim 8, patches 1-1428

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if has('vim_starting')
  set nocompatible
endif
if empty(glob('~/.vim/autoload/plug.vim'))
  execute '!mkdir -p ~/.vim/bundle ~/.vim/autoload'
  execute '!curl -fLo ~/.vim/autoload/plug.vim https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
endif

call plug#begin('~/.vim/bundle')
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_yarp = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Launch Vim
 2. Watch cursor flicker weirdly

## Generate a logfile if appropriate

A basic vim profile:
```
FUNCTION  <SNR>37_ProfileEnd()
Called 1 time
Total time:   0.000000
 Self time:   0.000000

count  total (s)   self (s)
                              profile pause
                              noautocmd qall!

FUNCTION  <lambda>1()
Called 23 times
Total time:   0.000320
 Self time:   0.000320

count  total (s)   self (s)
   23              0.000250 return 0

FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
   23   0.000320             <lambda>1()
    1   0.000000             <SNR>37_ProfileEnd()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
   23              0.000320  <lambda>1()
    1              0.000000  <SNR>37_ProfileEnd()

```

## Screen shot (if possible)
Here are 2 videos with Deoplete enabled and disabled:
[enabled](http://wtf.amadeus.wtf/monosnap/screencast_2018-01-28_12-35-59.mp4)
[disabled](http://wtf.amadeus.wtf/monosnap/screencast_2018-01-28_12-36-49.mp4)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/597

It is MacVim's bug.
I have tired.

**Comment by Shougo** [comment]
I recommend for you to use neovim or CUI Vim in Mac.
