### ISSUE TITLE
Unexpected behavior: matcher_length

### ISSUE THREAD

**Issue by fastbodin** [Shougo/deoplete.nvim#618]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

The matcher_length filter appears not to be working for all scenarios. It does not always filter out words equal to inputted text. 

For instance, if I type 'apple', then type 'apple' a second time, 'apple' will appear as a candidate but I will be unable to select it. If I then type 'apples', then type 'apple' only 'apples' will appear as a candidate, not 'apple'. The screenshots below will aid in the explanation of this behavior.

Related github issues:
https://github.com/Shougo/deoplete.nvim/issues/582
https://github.com/Shougo/deoplete.nvim/issues/532
https://github.com/Shougo/deoplete.nvim/issues/512

Solution that should have worked from deoplete.txt FAQ

Q: I don't want to see the typed word in the completion menu.

A: You should add |deoplete-filter-matcher_length| to the matchers. >

        call deoplete#custom#source('_', 'matchers', ['matcher_fuzzy',
        \ 'matcher_length'])
<
   Note: Replace `'_'` with a specific source such as `'around'` if
         you want to keep seeing certain sources, e.g. snippets.

## Expected

If I type 'apple' deoplete, with the below minimal init.vim/vimrc, should not provide 'apple' as a dropdown menu candidate.

## Environment Information

 * deoplete version(SHA1): Version: 4.0

 * OS: macOS High Sierra version 10.13.2

 * neovim/Vim version: NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2"
  - INFO: Executable: /usr/local/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.2.0
  - OK: Latest python2-neovim is installed: 0.2.0

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3"
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.0
  - OK: Latest python3-neovim is installed: 0.2.0

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
  - WARNING: Missing "neovim" gem.
    - ADVICE:
      - Run in shell: gem install neovim
      - Is the gem bin directory in $PATH? Check `gem environment`.
      - If you are using rvm/rbenv/chruby, try "rehashing".
## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
let g:python_host_prog = '/path/to/python2'
let g:python3_host_prog = '/path/to/python3'

set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_refresh_always = 1
call deoplete#custom#source('_', 'matchers', ['matcher_fuzzy', 'matcher_length'])
```

## Screen shot (if possible)
![screen shot 2018-01-29 at 12 58 53 pm](https://user-images.githubusercontent.com/35845723/35534510-8dba4e3a-04f5-11e8-8127-101e07b6e472.png)
![screen shot 2018-01-29 at 12 59 10 pm](https://user-images.githubusercontent.com/35845723/35534498-86dfbe24-04f5-11e8-9218-12a8da97abb4.png)
![screen shot 2018-01-29 at 12 59 17 pm](https://user-images.githubusercontent.com/35845723/35534504-8aaf864c-04f5-11e8-8987-7cbfc57ec04b.png)
![screen shot 2018-01-29 at 1 09 25 pm](https://user-images.githubusercontent.com/35845723/35534537-aaae22be-04f5-11e8-8c05-4c1d71752e6d.png)

**Comment by uinput** [comment]
I can reproduce this issue with the provided minimal init file. Is it possible that the list is not updated despite enabling `deoplete#enable_refresh_always`?

**Comment by Shougo** [comment]
To fix the problem completely, TextChangedP autocmd is needed.
I don't want to hack anymore.

Closing.

https://github.com/vim/vim/pull/2372

**Comment by balta2ar** [comment]
What about neovim? Is TextChangedP available there or will it be?

**Comment by uinput** [comment]
Seems like Shougo will work on it as soon as it is merged:
https://github.com/neovim/neovim/issues/7443
Original pull request for vim:
https://github.com/vim/vim/pull/2372

**Comment by Shougo** [comment]
Yes.

**Comment by fastbodin** [comment]
Thanks for the quick response and your work on this project! I look forward to the port to NV!

**Comment by Shougo** [comment]
I am also neovim/Vim contributor not only plugins developer.
My specialty is the automatic completion.
