### ISSUE TITLE
Add on_complete option to sources or source candidates.

### ISSUE THREAD

**Issue by uinput** [Shougo/deoplete.nvim#619]
Hi,

this is rather a feature request, so I'm not providing complete issue information.

What I'd like to have is the option to call a function after a candidate was completed. The function I want to be called is different based on which source it came from.

Consider the following scenario: We have two sources providing a candidate with the same name. For this example, I'm going to use the source `deoplete-jedi`, which provides the candidate `datetime` from the standard Python library. Also, we have `UltiSnips` activated, also providing a candidate named `datetime`, which should expand to the current datetime on completion.

Now to get snippet expansion working, I have the following key binding in my configuration:
`inoremap <expr> <CR> pumvisible() ? "\<C-r>=<SID>ExpandAndGetRes()<C-M>" : "\<CR>"`

The function `ExpandAndGetRes` will expand at the current cursor position in the buffer:
```
function! <SID>ExpandAndGetRes() abort                                            
        let snippet = UltiSnips#ExpandSnippet()                       
        if g:ulti_expand_res > 0                                    
                return snippet                                   
        else                                   
                return deoplete#close_popup()  
        endif                                  
endfunction
```

No matter what candidate was selected, the completed candidate (namely `datetime` for both sources) will get expanded to the current datetime by `UltiSnips`. To put this in other words, I can not complete to the `datetime` suggestion from `deoplete-jedi`, even if it was selected in the popup menu.

Would it be possible to add a property named `on_complete` to the completion candidates or the source itself, which will get called if the specific candidate was completed? Maybe I missed something, but I don't think this is currently possible.

**Comment by Shougo** [comment]
You should use `CompleteDone` autocmd and `v:completed_item` feature.

**Comment by Shougo** [comment]
> Would it be possible to add a property named on_complete to the completion candidates or the source itself, which will get called if the specific candidate was completed? Maybe I missed something, but I don't think this is currently possible.

Unfortunately, it cannot be supported.

Please see below.
https://github.com/neovim/neovim/issues/7179

**Comment by uinput** [comment]
Alright, so @roxma requested a way to add an additional attribute to the candidates. Why would a string attribute not solve the problem? Wouldn't a string satisfy our needs?

**Comment by Shougo** [comment]
> Why would a string attribute not solve the problem? Wouldn't a string satisfy our needs?

We can add it easily.  But the additional information is unreliable.
It should be dictionary.

Note:  It should be requested in vim issues instead.
