### ISSUE TITLE
Disable arrow keys to move up/down popup menu

### ISSUE THREAD

**Issue by Karmak0ma** [Shougo/deoplete.nvim#620]
Hi,

Is it possible to disable the arrow keys to move up and down the autocompletion popup menu?
I am sometimes just moving around a file in insert mode, and it is quite annoying when the menu opens and I start moving through the options instead up and down the file as I want to.

I know I can just disable the menu from opening automatically, but I rather keep it like this.
I have found how to map other keys to move up and down the menu, but I am unable to find anywhere how to **disable** the use of the arrow keys. I'd like that when the popup menu is open and I press up/down, it just goes one line up/down in the file and the menu is closed.

Regards

**Comment by Shougo** [comment]
```vim
   inoremap <expr><Left>  deoplete#close_popup() . "\<Left>"
    inoremap <expr><Right> deoplete#close_popup() . "\<Right>"
    inoremap <expr><Up>    deoplete#close_popup() . "\<Up>"
    inoremap <expr><Down> deoplete#close_popup() . "\<Down>"
```
