### ISSUE TITLE
[feature] option to hide all marks and descriptions

### ISSUE THREAD

**Issue by plexigras** [Shougo/deoplete.nvim#621]

**Comment by Shougo** [comment]
For descriptions, please create the original converter for it.

For marks,

```vim
		" Disable the source mark.
		call deoplete#custom#source('omni', 'mark', '')
```

Please read the documentation.

**Comment by plexigras** [comment]
i thought `call deoplete#custom#source('omni', 'mark', '')` only hides the source mark of the omni provider

**Comment by Shougo** [comment]
> For descriptions, please create the original converter for it.

`:help deoplete-create-filter`
