### ISSUE TITLE
Deoplete with parallel branch can no longer find `python3`

### ISSUE THREAD

**Issue by clason** [Shougo/deoplete.nvim#626]
# Problems summary

Starting `nvim` after the merge results in the error
```
[deoplete] You need to set g:python3_host_prog.
[deoplete] python3 is not executble.
[deoplete] You need to set g:python3_host_prog.
[deoplete] python3 is not executble.
[deoplete] You need to set g:python3_host_prog.
[deoplete] python3 is not executble.
[deoplete] You need to set g:python3_host_prog.
```
(and, naturally, no completion). `let`ting `g:python3_host_prog` to the correct path fixes the issue, but that was not necessary before the merge.

(Also, the spelling of `executable` in the error message is wrong.)

## Expected

deoplete finds the `python3` executable.

## Environment Information

 * deoplete version(SHA1): 0a6debf

 * OS: macOS 10.13.4 (beta); openSUSE Tumbleweed

 * neovim/Vim version: NVIM v0.2.3-564-g6452831cf

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the
  environment.
  - INFO: Executable: /usr/local/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.1
  - OK: Latest python3-neovim is installed: 0.2.1

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

`nvim -u minimal.rc

## Upload the log file

[log.txt](https://github.com/Shougo/deoplete.nvim/files/1692640/log.txt)

**Comment by clason** [comment]
Great, that fixed it, thank you very much!

**Comment by clason** [comment]
Actually, that only fixed it on macOS -- on Linux I now get the following error:

```
error caught in async handler '/home/clason/.vim/plugged/deoplete.nvim/rplugin/p
ython3/deoplete:function:_deoplete_init [[]]'
Traceback (most recent call last):
  File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/__init_
_.py", line 28, in init_channel
    self._deoplete = Deoplete(self._vim)
  File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/deoplet
e.py", line 35, in __init__
    self._parents.append(Parent(vim, context))
  File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.
py", line 23, in __init__
    self._start_process(context, context['serveraddr'])
  File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/parent.
py", line 73, in _start_process
    context, context['cwd'])
  File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deoplete/process
.py", line 31, in __init__
    unicode_errors='surrogateescape')
  File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__init__
TypeError: expected bytes, str found
[deoplete] Traceback (most recent call last):
[deoplete]   File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deopl
ete/dp_main.py", line 36, in main
[deoplete]     child = Child(vim)
[deoplete]   File "/home/clason/.vim/plugged/deoplete.nvim/rplugin/python3/deopl
ete/child.py", line 48, in __init__
[deoplete]     unicode_errors='surrogateescape')
[deoplete]   File "msgpack/_packer.pyx", line 136, in msgpack._packer.Packer.__i
nit__
[deoplete] TypeError: expected bytes, str found
[deoplete] Error in child.  Use :messages for error details.
```

(This is with `msgpack` 0.5.3 and `msgpack-python` 0.5.2 -- the same (mismatched) version as in macOS. The error message is from my full `init.vim` because I thought the additional lines might be informative; the `minimal.rc` only shows the lines beginning with `[deoplete]`.)

[log.txt](https://github.com/Shougo/deoplete.nvim/files/1692707/log.txt)

**Comment by Shougo** [comment]
@clason Please see the below.

https://github.com/neovim/python-client/issues/299

**Comment by clason** [comment]
Yes, pinning `msgpack-python` fixes the problem. (A bit weird that 0.5.2 works on macOS but not on Linux.)

**Comment by Shougo** [comment]
Please use the latest version.

**Comment by clason** [comment]
Indeed, that fixed it on Linux as well. Thank you very much for your quick help!
