### ISSUE TITLE
Docs about new parallel processes 

### ISSUE THREAD

**Issue by mhartington** [Shougo/deoplete.nvim#634]
# Problems summary

Since the new parallel processes  feature was merged, nvim-typescript's [deoplete source](https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/deoplete/sources/typescript.py) no longer works. With nvim-ts's current setup, the deoplete source communicates with another python subprocess, but does not seem to be compatible with the parallel processes. Are there any docs/examples on how to update a source ?

## Environment Information

 * deoplete version(SHA1): c5f8165

 * OS: macOS 10.13

 * neovim/Vim version: NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/.config/nvim/repos/github.com/Shougo/dein.vim/
call dein#begin(expand('~/.config/nvim'))
call dein#add('HerringtonDarkholme/yats.vim')
call dein#add('Shougo/deoplete.nvim')
call dein#add('mhartington/nvim-typescript')
call dein#end()
filetype plugin indent on
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

1) Clone https://github.com/mhartington/deoplete-typescript-errors
2) run `npm install` 
3)  nvim -u minimal.vim index.ts
4) no completion happens

**Comment by Shougo** [comment]
I have tested the code.

```python
            data = self._client.completions(
                file=self.relative_file(),
                line=context["position"][1],
                offset=context["complete_position"] + 1,
                prefix=context["complete_str"]
            )
```

`self._client.completions()` does not return.
I don't know why though.

**Comment by mhartington** [comment]
Looking at it further, it seems like while the source is loaded,  Im unable to write logs out to the deoplete log file,

**Comment by Shougo** [comment]
> Looking at it further, it seems like while the source is loaded, Im unable to write logs out to the deoplete log file,

I cannot reproduce the problem.
logging is works for me.

**Comment by mhartington** [comment]
Logging issue ended up being on my end. I think what I am seeing is similar to https://github.com/mhartington/nvim-typescript/pull/81 as ncm also uses separate processes. 

I will have to rework my source to work with deoplete's new process.

**Comment by Shougo** [comment]
OK.
