### ISSUE TITLE
Deoplete breaks in html files when completeopt is set to "longest"

### ISSUE THREAD

**Issue by dylanaraps** [Shougo/deoplete.nvim#65]
Hello, 

I'm having 2 issues with deoplete and html files. The issues only occur when filtype is set to "html". I've narrowed it down to this line in my init.vim.

````VimL
set completeopt=longest
````

I'm on Arch Linux and my neovim version is:

    NVIM 0.0.0-alpha+201510261840 (compiled Oct 27 2015 10:04:47)
    Commit: 95707bf336794c7ec8991917f184c02ae873dd8c

This is the minimal init.vim I used to reproduce the two issues.

````VimL
call plug#begin('~/.config/nvim/plugged')
	Plug 'Shougo/deoplete.nvim'
		let g:deoplete#enable_at_startup = 1

call plug#end()

set completeopt=longest
````

### Issue 1

Deoplete goes into a long loop of errors that prompt you to click enter. Clicking enter inserts spaces and or newlines into the file and breaks undo.

Log: http://pastebin.com/raw.php?i=Dtma3emR
Webm: http://gfycat.com/FlickeringSphericalGalapagospenguin

Steps to reproduce:
1.    nvim -u minimal.vimrc
2     Open a html file and set ft=html
3.    Enter insert mode
4.    Type <
5.    Immediately click \<Tab\>

### Issue 2

Deoplete hangs trying to complete inside of a html tag. It then completes a random word and prevents you from using backspace to delete it.

Log: http://pastebin.com/raw.php?i=VTnTi6uF
Webm: http://gfycat.com/EvenSizzlingHatchetfish

Steps to reproduce: 
1.    nvim -u minimal.vimrc
2     Open a html file and set ft=html
3.    Enter insert mode
4.    Start typing a html tag, for example: "<h1 "
5.    immediately after start typing "class".

Both of these issues occur because of that single option, if I unset completeopt these issues go away.

Thanks!

**Comment by Shougo** [comment]
Reproduced. It is bug.
But I have noticed another omnifunc call bug in latest neovim.
I must fix it before it.
Please wait....

**Comment by dylanaraps** [comment]
All good, thanks.

**Comment by Shougo** [comment]
Fixed.  Thanks.

**Comment by dylanaraps** [comment]
I've updated the plugin and neovim but the first issue still remains. I can still reproduce it with the minimal init.vim above.

This is the issue I'm still getting.
````md
Issue 1

Deoplete goes into a long loop of errors that prompt you to click enter. Clicking enter inserts spaces and or newlines into the file and breaks undo.

Log: http://pastebin.com/raw.php?i=Dtma3emR
Webm: http://gfycat.com/FlickeringSphericalGalapagospenguin

Steps to reproduce:
1. nvim -u minimal.vimrc
2. Open a html file and set ft=html
3. Enter insert mode
4. Type <
5. Immediately click <Tab>
`````

**Comment by Shougo** [comment]
Reproduced.  But it is htmlcomplete bug.

You can reproduce it without deoplete.
You should report it to the plugin maintainer.

minimal nvimrc
```vim
filetype plugin indent on
syntax enable
setfiletype html
```

*  nvim -u minimal.vimrc
* Enter insert mode and Put `<`
* Type `<C-v><C-i><C-x><C-o>`
* Same error

**Comment by dylanaraps** [comment]
You're right.

How do I go about reporting this to the plugin maintainer? Do I just open up an issue on neovim's github page? Or is there someone specific I need to report this to?

**Comment by Shougo** [comment]
Same error is occurred in Vim and neovim.
So, you should contact with the maintainer.
The address is here.

```
" Vim completion script
" Language:	HTML and XHTML
" Maintainer:	Mikolaj Machowski ( mikmach AT wp DOT pl )
" Last Change:	2014 Jun 20
```

If the response is none, you should create new issue in vim repository.

**Comment by dylanaraps** [comment]
Thanks! I'll contact him.

**Comment by ZyX-I** [comment]
@dylanaraps I in this case usually send report *both* to maintainer and vim-dev mailing list. Thus you will automatically have a proof that you have contacted the maintainer, with the timestamp attached. Also in some cases maintainer may receive a fix from other vim-dev readers which he will only need to officially accept.

**Comment by dylanaraps** [comment]
I'm submitting it to both as we speak. 

Thanks guys

**Comment by rafi** [comment]
@dylanaraps any progress from vim-dev?

**Comment by dylanaraps** [comment]
iirc I made a post on vim-dev and emailed the maintainer. The maintainer didn't respond to my emails for over a month and I gave up.

**Comment by rafi** [comment]
@dylanaraps Are you using [`othree/html5.vim`](https://github.com/othree/html5.vim)? It seems to overload the `htmlcomplete#CompleteTags` omnifunc, and without it, I can see HTML completion with deoplete fine.

**Comment by dylanaraps** [comment]
Yeah I am using it.

**Comment by Shougo** [comment]
> iirc I made a post on vim-dev and emailed the maintainer. The maintainer didn't respond to my emails for over a month and I gave up.

You should report it in vim_dev.
Bram will respond.

**Comment by Vvkmnn** [comment]
[Thanks](https://github.com/Shougo/deoplete.nvim/issues/65#issuecomment-241195579) @rafi; wasn't sure how to override this behaviour in the interim. Installing this package does the trick.
