### ISSUE TITLE
Deoplete makes closing vim slow when using the terminal

### ISSUE THREAD

**Issue by glacambre** [Shougo/deoplete.nvim#656]
# Problems summary
When I close a terminal buffer by hitting `<C-d>` and deoplete is loaded, Neovim takes a few seconds to shut down.

## Expected
Neovim should shut down immediately, as it does when deoplete is not loaded.

## Environment Information

 * deoplete version(SHA1): db94ea05afbb36bf92ca0be268880439cc40b6ed

 * OS: Linux 4.14.0-3-amd64 Debian

 * neovim/Vim version: NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only):
    + python3-neovim version 0.2.0
    + No ruby/node/python2 providers

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:deoplete#enable_at_startup = 1
set rtp+=/tmp/deoplete.nvim/

function! OnTermClose()
    if len(filter(range(1, bufnr('$')), 'buflisted(v:val)')) == 1
        :quit!
    else
        call feedkeys(" ")
    endif
endfunction

au TermClose * call OnTermClose()
```

## The reproduce ways from neovim/Vim starting (Required!)
```sh
nvim -u /tmp/init.vim -c startinsert term://zsh -f
```
Then press `<C-d>` to close the shell and neovim.

## Generate a logfile if appropriate
I generated a log file but there doesn't seem to be anything interesting in it, please let me know if you really want me to upload it.

**Comment by glacambre** [comment]
I tried bisecting the issue, it looks like e320da659ca2901d5702d6cc070ae459a1b09d9e is the first commit that has this problem.

**Comment by Shougo** [comment]
`au TermClose * nested call OnTermClose()`

**Comment by glacambre** [comment]
This does indeed fix the issue, thank you for your help!
