### ISSUE TITLE
Error with vim8

### ISSUE THREAD

**Issue by FR4N7Z** [Shougo/deoplete.nvim#660]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
When I run ":call deoplete#enable()" I got the following error :
Erreur détectée en traitant function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[17]..deoplete#init#_variabl
es[12]..neovim_rpc#serveraddr :
E605: Exception non interceptée : [vim-hug-neovim-rpc] requires `:set encoding=utf-8`
Erreur détectée en traitant function deoplete#enable :

If I set encoding=utf-8, I got the following error :

[vim-hug-neovim-rpc] failed executing: pythonx import neovim
[vim-hug-neovim-rpc] Vim(pythonx):Traceback (most recent call last):
Erreur détectée en traitant function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[17]..deoplete#init#_variabl
es[12]..neovim_rpc#serveraddr :
ligne   15 :
E605: Exception non interceptée : [vim-hug-neovim-rpc] requires `:pythonx import neovim` command to work
Erreur détectée en traitant function deoplete#enable :

## Expected

deoplete to work

## Environment Information

 * deoplete version(SHA1):
I don't know how to get that but it is the last version
 * OS:
Windows 10
 * neovim/Vim version:
Vim 8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
" VIM Configuration - Frantz Baustier

" Annule la compatibilite avec l'ancetre Vi : totalement indispensable
set nocompatible

"exec "set runtimepath+=" . parent_directory . "/vim"
"exec "set runtimepath+=" . parent_directory . "/vim/bundle/Vundle.vim"

" Activation de pathogen
" call pathogen#infect()

let mapleader = ","


"""""""""""
" Plugins "
"""""""""""
filetype off
exec "call vundle#begin('" . parent_directory . "/vim/bundle/')"
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
	" activation de nerdtree au lancement de vim
	"autocmd VimEnter * NERDTree
	autocmd StdinReadPre * let s:std_in=1
	autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
	"let nerdtreeshowhidden=0
Plugin 'vim-scripts/LustyExplorer'
Plugin 'mileszs/ack.vim'
	" Parametres par defaut pour ack
	let g:ackprg="ack -H --nocolor --nogroup --column"
	" Place un marqueur et cherche
	nmap <leader>j mA:Ack<space>
	" Place un marqueur et cherche le mot sous le curseur
	nmap <leader>ja mA:Ack "<C-r>=expand("<cword>")<cr>"
	nmap <leader>jA mA:Ack "<C-r>=expand("<cWORD>")<cr>"
Plugin 'kien/ctrlp.vim'
	"let g:ctrlp_map = "<leader>c"
Plugin 'Shougo/deoplete.nvim'
Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'
let g:deoplete#enable_at_startup = 1
call vundle#end()
" Active les comportements specifiques aux types de fichiers comme
" la syntaxe et lâ€™indentation
filetype plugin indent on

" Active la coloration syntaxique
syntax enable



```

## The reproduce ways from neovim/Vim starting (Required!)

 1. start vim

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file

**Comment by Shougo** [comment]
Have you read the documentation?

neovim-python client is not installed.
https://github.com/neovim/python-client
Please install it.
