### ISSUE TITLE
Add deoplete's root to sys.path?

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#667]
I think it is good for sources to be able to `import deoplete`.

Do you agree?

Something for the source is already done in https://github.com/Shougo/deoplete.nvim/blob/a4d4db92a33a793ce753a55c3eea776d401edbf9/rplugin/python3/deoplete/util.py#L96-L99.

**Comment by Shougo** [comment]
I don't understand.
The sources can `import deoplete`.
What is the problem?

**Comment by blueyed** [comment]
Got confused - it works indeed already.

**Comment by Shougo** [comment]
OK.
