### ISSUE TITLE
Add default source that uses is_async

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#669]
It would be useful to have an example or default source that makes use of `is_async`.

As for the feature itself it seems like deoplete is polling the sources regardless (until `is_async` gets set to `False`), right?
Would it be possible for the source to call deoplete instead?

Related: I've seen deoplete being stuck in the `completion_begin`/`completion_end` loop / polling all the time while in insert mode.  This might be related to deoplete-jedi having crashed while experimenting (and therefore never could set `self.is_async = False`), but am not sure.
This needs investigation.

Ref: https://github.com/wellle/tmux-complete.vim/issues/80

**Comment by Shougo** [comment]
I don't want to add no needed `is_async` source.
The default sources are not sample codes!

I think is_async source is not so needed in current deoplete.

**Comment by Shougo** [comment]
> As for the feature itself it seems like deoplete is polling the sources regardless (until is_async gets set to False), right?

Yes.

> Would it be possible for the source to call deoplete instead?

No.

> Related: I've seen deoplete being stuck in the completion_begin/completion_end loop / polling all the time while in insert mode. This might be related to deoplete-jedi having crashed while experimenting (and therefore never could set self.is_async = False), but am not sure.

https://github.com/Shougo/deoplete.nvim/issues/645

**Comment by blueyed** [comment]
>> Would it be possible for the source to call deoplete instead?

> No.

Are you sure?  Why not?
Shouldn't sending a specific RPC message do it?
It could either be just for notification (i.e. "poll me again"), or contain the results already.

**Comment by Shougo** [comment]
Really?
Why it is needed?
I don't know the feature in the other auto completion plugins.

**Comment by blueyed** [comment]
I think the pattern of notifying instead of being polled is better, since it causes less overhead.
But I do not know the internals good enough yet, and therefore asked for why you think it is not possible.

**Comment by Shougo** [comment]
If deoplete uses neovim event loop, the implementation may be possible.
But current implementation is not.

And it is not compabile with older source implementation.
etc...

I think async source support is not important.

**Comment by Shougo** [comment]
https://github.com/neovim/python-client/pull/294
