### ISSUE TITLE
On Vim8 : E605: Exception not caught: [vim-hug-neovim-rpc] requires `:pythonx import neovim` command to work

### ISSUE THREAD

**Issue by FR4N7Z** [Shougo/deoplete.nvim#674]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

Hello. Thanks for your help.

# Problems summary
E605: Exception not caught: [vim-hug-neovim-rpc] requires `:pythonx import neovim` command to work
When I run pythonx import neovim, I got the following error:
No module named neovim.

## Expected

No eror

## Environment Information

 * deoplete version(SHA1): last version

 * OS:Windows 10

 * neovim/Vim version: Vim 8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
" VIM Configuration - Frantz Baustier

" Annule la compatibilite avec l'ancetre Vi : totalement indispensable
set nocompatible

"exec "set runtimepath+=" . parent_directory . "/vim"
"exec "set runtimepath+=" . parent_directory . "/vim/bundle/Vundle.vim"

" Activation de pathogen
" call pathogen#infect()

let mapleader = ","
set encoding=utf-8
set fileencoding=utf-8

"""""""""""
" Plugins "
"""""""""""
filetype off
exec "call vundle#begin('" . parent_directory . "/vim/bundle/')"
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
	" activation de nerdtree au lancement de vim
	"autocmd VimEnter * NERDTree
	autocmd StdinReadPre * let s:std_in=1
	autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
	"let nerdtreeshowhidden=0
Plugin 'vim-scripts/LustyExplorer'
Plugin 'mileszs/ack.vim'
	" Parametres par defaut pour ack
	let g:ackprg="ack -H --nocolor --nogroup --column"
	" Place un marqueur et cherche
	nmap <leader>j mA:Ack<space>
	" Place un marqueur et cherche le mot sous le curseur
	nmap <leader>ja mA:Ack "<C-r>=expand("<cword>")<cr>"
	nmap <leader>jA mA:Ack "<C-r>=expand("<cWORD>")<cr>"
Plugin 'kien/ctrlp.vim'
	"let g:ctrlp_map = "<leader>c"
Plugin 'Shougo/deoplete.nvim'
	Plugin 'roxma/nvim-yarp'
	Plugin 'roxma/vim-hug-neovim-rpc'
	let g:deoplete#enable_at_startup = 1
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-syntastic/syntastic'
	set statusline+=%#warningmsg#
	set statusline+=%{SyntasticStatuslineFlag()}
	set statusline+=%*
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. start Vim

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/673

**Comment by FR4N7Z** [comment]
Hello. Thank you but I ran 'pythonx import neovim' and it says 'No module named neovim'.
Do you mean I need to install Neovim?
