### ISSUE TITLE
Rust - external crates not autocompleting

### ISSUE THREAD

**Issue by compressed** [Shougo/deoplete.nvim#68]
Hi,
I've setup this plugin using neovim + racer + vim-racer and it's working quite well for all of the standard rust library functions. Thank you!

However, if I use an external crate in a file, it doesn't seem to be providing any autocompletions unless I type `<C-x><C-o>` to call racer directly.

For example, this works fine:

```rust
fn main() {
    let v = Vec::new();
    v. // works fine - shows the completions after typing `.`
    println!("Hello, world!");
}
```

But this one doesn't:
```rust
extern crate uuid;

use uuid::Uuid;

fn main() {
    let u = Uuid::new_v4();
    u. // nothing shown after typing `.` until I press <C-x><C-o>.
    println!("Hello, world!");
}
```

Video:
![nov 05 2015 13 31](https://cloud.githubusercontent.com/assets/28634/10977827/816acbee-83c1-11e5-9ebc-0e0cd20266ab.gif)

Last completion for `u.` is when I did `<C-x><C-o>` which shows the completion menu.

I also noticed if I used the omni function settings, then both scenarios will provide autocompletion after the `.` is typed.

```
    let g:deoplete#omni_patterns = {}
    let g:deoplete#omni_patterns.rust = '[(\.)(::)]'
```

Info:
```
OS: Mac OSX 10.11.1
:version
NVIM 0.1.0-dev (compiled Nov  3 2015 21:11:53)
Commit: 4196d0b983d56ac598a30f955bca6d941b058046
```

init.vim:

```
set nocompatible              " be iMproved, required
set hidden
filetype off                  " required

call plug#begin('~/.vim/plugged')
  Plug 'wting/rust.vim'
  Plug 'Shougo/deoplete.nvim'
    let g:deoplete#enable_at_startup = 1
    let g:deoplete#enable_smart_case = 1
    " let g:deoplete#omni_patterns = {}
    " let g:deoplete#omni_patterns.rust = '[(\.)(::)]'
    set completeopt-=preview
  Plug 'phildawes/racer'
  Plug 'racer-rust/vim-racer'
    let g:racer_insert_paren = 1
    let g:racer_cmd = $HOME . "/.vim/plugged/racer/target/release/racer"
    let $RUST_SRC_PATH= $HOME . "/rust/src"
    let g:racer_experimental_completer = 1
call plug#end()

filetype plugin indent on    " required
```

**Comment by Shougo** [comment]
Unfortunately, I cannot get the completion in both(omnicompletion and deoplete).
So I cannot support it.
