### ISSUE TITLE
Menu does not show up after reducing input pattern

### ISSUE THREAD

**Issue by balta2ar** [Shougo/deoplete.nvim#680]
# Problems summary

deoplete menu does not reappear if input pattern goes large and then shrinks.

## Expected

deoplete menu should reappear again when there are matching results to show.

## Environment Information

 * deoplete version(SHA1): c3c9406 (HEAD -> master, origin/master, origin/HEAD) Add deoplete#send_event() (10 hours ago) <Shougo Matsushita>
 * OS: ArchLinux
 * neovim/Vim version: NVIM v0.2.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set rtp+=~/.fzf

if &compatible
  set nocompatible
endif

call plug#begin('~/.vim/plugged')

Plug 'Shougo/vimproc.vim', {'do': 'make'}

Plug 'Shougo/deoplete.nvim'
"Plug 'wellle/tmux-complete.vim'
"Plug 'thalesmello/webcomplete.vim'
Plug 'balta2ar/webcomplete.vim'
call plug#end()

filetype plugin indent on
syntax enable
set nocompatible
set laststatus=2
set number
set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r,cp866
set showcmd

colorscheme desert
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

$ nvim -u test.vim test
$ nvim
<input PySequenceTTT, delete TTT, nothing shows up>

## Screen shot (if possible)

![deoplete-does-not-restore](https://user-images.githubusercontent.com/340676/37306793-e76bef7c-2649-11e8-904c-4261330c5e31.gif)

**Comment by Shougo** [comment]
Reproduced.
I will check the reason.

**Comment by Shougo** [comment]
```diff
diff --git a/rplugin/python3/deoplete/child.py b/rplugin/python3/deoplete/child.py
index b702a75..72ee1a4 100644
--- a/rplugin/python3/deoplete/child.py
+++ b/rplugin/python3/deoplete/child.py
@@ -397,7 +397,8 @@ class Child(logger.LoggingMixin):
                 name, time.clock() - self._profile_start_time))

     def _use_previous_result(self, context, result, is_volatile):
-        if context['position'][1] != result['prev_linenr']:
+        if (context['position'][1] != result['prev_linenr'] or
+                not result['candidates']):
             return False
         if is_volatile:
             return context['input'] == result['prev_input']
```

**Comment by balta2ar** [comment]
That patch seems to help, thank you!

By the way, it looks like deoplete suggests the word under the cursor as follows:

![](https://i.imgur.com/f8zTWQA.png)

It's not really useful as I've already typed the word. Why suggest it? If this is buffer completion, maybe the word under the cursor could be excluded?

**Comment by Shougo** [comment]
> It's not really useful as I've already typed the word. Why suggest it? If this is buffer completion, maybe the word under the cursor could be excluded?

https://github.com/Shougo/deoplete.nvim/issues/532

**Comment by Shougo** [comment]
OK.  The source must set `self.is_volatile = True`.

Because it checks every input.

**Comment by Shougo** [comment]
I will revert the patch.
