### ISSUE TITLE
Multiple row in complete menu and complete stop before (

### ISSUE THREAD

**Issue by thymbahutymba** [Shougo/deoplete.nvim#681]
Why when i select a entry in completeopt menù and i press enter deoplete complete until `(`?
![screenshot_20180313_002719](https://user-images.githubusercontent.com/23526758/37314598-4b8a8b16-2655-11e8-8930-5fdb729cba16.png)

It's normal that i have, inside completeopt menù, multiple rows with same suggestion?
`Output type [Rust]...`

**Comment by Shougo** [comment]
It is just the source problem(deoplete-rust?).
It is not deoplete problem.
closing.

**Comment by thymbahutymba** [comment]
> Why when i select a entry in completeopt menù and i press enter deoplete complete until `(`?
Maybe the second, but the first problem i have also with python. When i call a method like `self.method(parameter)` deoplete complete until `(` and after i insert paramenter between brackets.

**Comment by Shougo** [comment]
You can use neosnippet for it.

`:help g:neosnippet#enable_completed_snippet`
