### ISSUE TITLE
deoplete.nvim + vim-bundler

### ISSUE THREAD

**Issue by bbtdev** [Shougo/deoplete.nvim#683]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Hello,
So I am working with Ruby/Rails and instead of ctags I use ripper-tags (better for ruby), but there is no issue here.
What I wanted is to have tags from gems as well, so I installed gem-ripper-tnags that generate tags in the gems folder as well and bundler.vim that includes the paths to the gem tags.

When I in the project folder and open it with vim and start typing on the unsaved buffer, everything is okay, but when I open a file deoplete ignores the tags in the main project folder, because if I remove bundler.vim deoplete works.

I know, this is kind of a stretch, but if anyone experienced this and solved it, can help me?

## Expected

deoplete should use all the tags (project and gems).

## Environment Information

 * deoplete version(SHA1): Latest(don't know how to find it)

 * OS:  Ubuntu 16.04.4 LTS

 * neovim/Vim version: Vim 8

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```
" tags
Plugin 'ludovicchabant/vim-gutentags'
Plugin 'majutsushi/tagbar'
" ruby/ruby on rails
Plugin 'tpope/vim-bundler'
" autocomplete
Plugin 'Shougo/deoplete.nvim'
Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'
" autocomplete
let g:python3_host_prog = "/usr/bin/python3"
let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

## The reproduce ways from neovim/Vim starting (Required!)

 1. open vim in project folder
 2. open file
 3. type ApplicationController

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Upload the log file
https://gist.github.com/bbtdev/713fcaf9ff0df722e368571d4b371c7e

**Comment by Shougo** [comment]
I don't understand the problem.
But deoplete just uses tags file from `tags` option.

You can set `tags` option manually.
