### ISSUE TITLE
[deoplete] deoplete failed to load

### ISSUE THREAD

**Issue by badeip** [Shougo/deoplete.nvim#688]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

not loading

## Expected
loading

## Environment Information

 * deoplete version(SHA1): c3c9406bfb4207c057d6a366c88466256a6ea2bd

 * OS: CentOS Linux release 7.4.1708 (Core)

 * neovim/Vim version:NVIM v0.2.3-825-g9154782

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $SSH_TTY='/dev/pts/3'

## tmux
  - OK: escape-time: 20ms
  - INFO: $TERM: screen-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: tmux

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Multiple python2 executables found.  Set `g:python_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python2
  - INFO: Other python executable: /bin/python2
  - INFO: Python2 version: 2.7.5
  - INFO: python2-neovim version: 0.2.4
  - OK: Latest python2-neovim is installed: 0.2.4

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /home/pwahlman/local/bin/python3
  - INFO: Other python executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python3 version: 3.5.4
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

call plug#begin('~/.vim/plugged')
Plug 'https://github.com/Shougo/deoplete.nvim'
call plug#end()
let g:deoplete#enable_at_startup = 1

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/.vim/plugged/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. nvim -u ~/.vimrc_minimal
 2. observe warning

## Upload the log file

[log_py3_rplugin.zip](https://github.com/Shougo/deoplete.nvim/files/1814483/log_py3_rplugin.zip)

**Comment by badeip** [comment]
Error when executing `:UpdateRemotePlugins`
```
Encountered ImportError loading plugin at /home/pwahlman/config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete: N
o module named 'vim'
Traceback (most recent call last):
  File "/home/pwahlman/.local/lib/python3.5/site-packages/neovim/plugin/host.py", line 130, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/home/pwahlman/local/lib/python3.5/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/pwahlman/local/lib/python3.5/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
ImportError: No module named 'vim'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/pwahlman/.local/share/nvim/rplugin.vim
```

**Comment by Shougo** [comment]
I don't know.
It is not deoplete issue.
It should be reported in neovim.

**Comment by Shougo** [comment]
You should know this warning...

```
    INFO: g:python3_host_prog is not set. Searching for python3 in the environment.
    INFO: Multiple python3 executables found. Set g:python3_host_prog to avoid surprises.
    INFO: Executable: /home/pwahlman/local/bin/python3
    INFO: Other python executable: /usr/bin/python3
    INFO: Other python executable: /bin/python3
    INFO: Python3 version: 3.5.4
    INFO: python3-neovim version: 0.2.4
    OK: Latest python3-neovim is installed: 0.2.4
```

**Comment by Shougo** [comment]
> Encountered ImportError loading plugin at /home/pwahlman/config/nvim/plugged/deoplete.nvim/rplugin/python3/deoplete: N
o module named 'vim'

```python
from importlib import find_loader
from deoplete.deoplete import Deoplete


if find_loader('yarp'):
    import vim
else:
    import neovim
    vim = neovim
```

Why vim is loaded?
I think you have installed yarp plugin.

**Comment by badeip** [comment]
@Shougo I also saw the reference to yarp, but I certainly don't have it installed.

**Comment by badeip** [comment]
I made a new minimal vimrc where I explicitly set python paths:
```
set runtimepath+=~/.vim/plugged/deoplete.nvim/
let g:python_host_prog = "/usr/bin/python2"
let g:python3_host_prog = "/usr/bin/python3"
let g:deoplete#enable_at_startup = 1
```

running `nvim -u ~/.vimrc_minimal ~/.vimrc_minimal` produces these `:messages`:

```
[deoplete] Vim(call):E117: Unknown function: _deoplete_init
[deoplete] function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[19]..deoplete#init#_channel, line 19
[deoplete] deoplete failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
no notification handler registered for "/home/pwahlman/config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:BufReadPost:*"
no notification handler registered for "/home/pwahlman/config/nvim/plugged/LanguageClient-neovim/rplugin/python3/LanguageClient:autocmd:CursorMoved:*"
```
So it might be related to a language client, but that should not be relevant when using the minimal vimrc?

**Comment by badeip** [comment]
I just built the latest stable version of `nvim`
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
```
and see the exact same problem.
However, on a different machine I don't seem the problem, so this is rather strange.

**Comment by badeip** [comment]
I solved the problem:
`rm -rf ~/.local/lib/python3.5/site-packages/*`

and executed `:UpdateRemotePlugins` in `nvim

**Comment by Shougo** [comment]
Hm.  Your Python packages seems broken.

**Comment by bacondropped** [comment]
Try `pip3 remove yarp`.

**Comment by hasufell** [comment]
I experience this problem with dein if `let g:dein#lazy_rplugins = v:true`.

**Comment by Shougo** [comment]
You need to know what you have set.

```
g:dein#lazy_rplugins
		If you set it to 1, neovim remote plugins are lazy loaded.
		It is useful to save startup time.
		Note: It disables all remote plugins at startup.  You must
		define all remote plugins as lazy loaded if it is enabled.
```

All remote plugins must be lazy loaded and you need to register remote plugins by `call dein#remote_plugins()`.
