### ISSUE TITLE
"is_async" feature doesn't work reliably

### ISSUE THREAD

**Issue by kodemeister** [Shougo/deoplete.nvim#689]
# Problems summary

Deoplete may not show completion candidates from sources that use context["is_async"] feature.

## Expected

Deoplete always shows completion candidates from such sources.

## Environment Information

 * deoplete version(SHA1): c3c9406bfb4207c057d6a366c88466256a6ea2bd

 * OS: Arch Linux

 * neovim/Vim version: NVIM v0.2.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.vim/plugged')
Plug 'Shougo/deoplete.nvim'
Plug '~/.vim/plugged/deoplete-test'
call plug#end()

let g:deoplete#enable_at_startup = 1
```

deoplete-test is a minimal source that demonstrates the issue. It emulates async sources by returning a "foobar" candidate after deoplete calls gather_candidates() for several times. Here is the source code. Also attached deoplete-test.zip for convenience.

```python
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)

        self.name = "deoplete-test"
        self.mark = "[test]"
        self.rank = 1000

        self._count = 0
        self._max_count = 1

    def gather_candidates(self, context):
        if not context["is_async"]:
            context["is_async"] = True
            self._count = 0
            return []
        else:
            self._count += 1
            if self._count > self._max_count:
                context["is_async"] = False
                return [{"word": "foobar"}]
            else:
                return []
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Start nvim with deoplete and deoplete-test source
 2. Open any text file
 3. Type `fo`
 4. Observe that deoplete shows "foobar" candidate from deoplete-test source
 5. Press Backspace and retype `o` again
 6. Observe that deoplete does not show "foobar" candidate

## Screen shot (if possible)

![deoplete](https://user-images.githubusercontent.com/1043953/37553478-55adbc2a-29f3-11e8-9d49-506abbd31db2.gif)

[deoplete-test.zip](https://github.com/Shougo/deoplete.nvim/files/1821442/deoplete-test.zip)

**Comment by kodemeister** [comment]
This is actually related to https://github.com/autozimu/LanguageClient-neovim/issues/281. I wonder whether it's a deoplete bug or it's a source that incorrectly uses "is_async".

Also, if I change `self._max_count` to 0, the source works correctly. The issue seems to happen only when deoplete starts repeatedly calling `gather_candidates()` after some delay.

**Comment by Shougo** [comment]
Please test the latest version.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/680

**Comment by kodemeister** [comment]
Hi @Shougo, I've updated to the latest version but now deoplete doesn't show candidates from my test source at all. When I type `fo`, it calls `gather_candidates` exactly two times and then starts infinitely spam with the following log messages:

```
2018-03-19 12:01:34,498 DEBUG    [22024] (deoplete.core) completion_begin: fo
2018-03-19 12:01:34,499 DEBUG    [22024] (deoplete.core) completion_end: fo
```

Am I missing something? Here is the log file:
[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/1823880/deoplete.log)

**Comment by Shougo** [comment]
OK.  I get it.  Your source is broken.

```python
from .base import Base


class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)

        self.name = "deoplete-test"
        self.mark = "[test]"
        self.rank = 1000

        self._count = 0
        self._max_count = 1

    def gather_candidates(self, context):
        if not context["is_async"]:
            context["is_async"] = True
            return []
        else:
            self._count += 1
            if self._count > self._max_count:
                context["is_async"] = False
                return [{"word": "foobar"}]
            else:
                return []
```

The source must not reset the counter.
Because, it is infinite loop!

`0` -> `1` -> `0` -> `1` ...

**Comment by Shougo** [comment]
Here is the patch for deoplete.

```python
diff --git a/rplugin/python3/deoplete/child.py b/rplugin/python3/deoplete/child.py
index 3e18d74..53f8d2a 100644
--- a/rplugin/python3/deoplete/child.py
+++ b/rplugin/python3/deoplete/child.py
@@ -171,7 +171,7 @@ class Child(logger.LoggingMixin):
                     'rank': rank,
                 })

-        is_async = len([x for x in results if x['context']['is_async']]) > 0
+        is_async = len([x for x in results if x['is_async']]) > 0

         self.debug('merged_results: end')
         return {
diff --git a/rplugin/python3/deoplete/parent.py b/rplugin/python3/deoplete/parent.py
index 2ba08ae..2c9b56d 100644
--- a/rplugin/python3/deoplete/parent.py
+++ b/rplugin/python3/deoplete/parent.py
@@ -58,8 +58,7 @@ class Parent(logger.LoggingMixin):
         if self._child:
             results = self._put('merge_results', [context])
         else:
-            if context['position'] == self._prev_pos and (
-                    self._queue_id or context['event'] == 'Async'):
+            if context['position'] == self._prev_pos and self._queue_id:
                 # Use previous id
                 queue_id = self._queue_id
             else:
```

**Comment by balta2ar** [comment]
This patch seems to help... However, now completion menu flickers...

@Shougo I remember we briefly discussed testing in one issue and you were
against it, claiming that it would slow down the development pace. But if you
look at the recent issues, you're basically testing on your users, urgently
quenching fire here and there. Besides, there are no stable releases and master
branch often gets broken. I think there is room for improvement in terms of user
experience.

Please don't get me wrong, I'm not accusing you or criticizing your work. I just
would like you to reconsider introducing functional/integrational/behaviour
testing. Unittesting indeed may limit your iteration speed if your refactor
often, but deoplete behaviour from the user perspective rarely changes, right?
There are always Sources (sync and async), and there always should be a
completion menu. That's why I think high-level testing could be really helpful
here: you could both save time for your users (it takes a while to prepare good
problem report) and your own time by detecting problems much earlier.

**Comment by kodemeister** [comment]
Thank you, the patch works with the modified source! But now the item "foobar" appears with delay only for the first time. When I trigger the completion menu for second time, "foobar" appears immediately, i.e. without delay. This is not exactly what I want. I'd like to emulate a slow completion source like LanguageClient-neovim. That is, "foobar" should appear in completion menu with delay every time, not only once. For this reason I reset the counter. This is done intentionally to emulate a slow source each time completion menu is triggered.

Without resetting the counter deoplete enters infinite loop. Here's what happens:

1. Deoplete calls `gather_candidates` with `context['is_async'] == False`.
2. Source sets `context['is_async']` to `True`, resets the counter and returns an empty list of candidates.
3. Deoplete again calls `gather_candidates` with `context['is_async'] == True`.
4. Source increments the counter and again returns an empty list of candidates.
5. Deoplete again calls `gather_candidates` with `context['is_async'] == False`. **Why? Shouldn't it repeatedly call `gather_candidates` with `context['is_async'] == True` until the source sets it to `False` to signal that the gathering is finished?**

**Comment by Shougo** [comment]
> This patch seems to help... However, now completion menu flickers...

Please use the latest patch.
It fixes the flicker problem.

**Comment by Shougo** [comment]
> Please don't get me wrong, I'm not accusing you or criticizing your work. I just
would like you to reconsider introducing functional/integrational/behaviour
testing. Unittesting indeed may limit your iteration speed if your refactor
often, but deoplete behaviour from the user perspective rarely changes, right?
There are always Sources (sync and async), and there always should be a
completion menu. That's why I think high-level testing could be really helpful
here: you could both save time for your users (it takes a while to prepare good
problem report) and your own time by detecting problems much earlier.

OK.   Please add the tests.
Wellcome.

**Comment by Shougo** [comment]
> Why? Shouldn't it repeatedly call gather_candidates with context['is_async'] == True until the source sets it to False to signal that the gathering is finished?

OK.  I will look into the behavior.

**Comment by Shougo** [comment]
I have merged the patch.

**Comment by Shougo** [comment]
I get the error reason.
