### ISSUE TITLE
Anaconda problems

### ISSUE THREAD

**Issue by felipefariax** [Shougo/deoplete.nvim#69]
Hello!

First of all, thanks for your project! It is really helpful!

I'm having some problems to get it working. I suspect that is because I have a anaconda which uses python version 2.7

I have python3 on my system, but outside anaconda environment. When i check: echo has("python3"), it returns 1. What can I do to get deoplete working in my environment? set PYTHON_PATH? LD_LIBRARY_PATH?

Thank you!

**Comment by Shougo** [comment]
I think your problem is resolved in gitter.im.  Closing.
