### ISSUE TITLE
Remove completion suggestion identical to input.

### ISSUE THREAD

**Issue by BonaBeavis** [Shougo/deoplete.nvim#697]
![screenshot_2018-03-22_02-07-04](https://user-images.githubusercontent.com/3330855/37745603-fea11f18-2d75-11e8-8575-bf62449666b3.png)

Is the `call` suggestion really necessary?

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/532

Please read FAQ and other issues.
