### ISSUE TITLE
Improve tag source performance

### ISSUE THREAD

**Issue by Shougo** [Shougo/deoplete.nvim#699]
nvim-completion-manager uses binary search for tag search.
deoplete should use binary search too.

Note: In tag source, fuzzy search does not work.

**Comment by prabirshrestha** [comment]
For asymcomplete I use grep. Was suggested by one of the user who had huge tag file. Conversation can be found at https://github.com/prabirshrestha/asyncomplete-tags.vim/pull/3

**Comment by Shougo** [comment]
OK.  I have read the PR.  But I think binary search is better.

**Comment by SkyLeach** [comment]
Before I make a new issue, my issue may be related.  About 30 minutes ago I wanted to start using deocomplete.nvim/jedi as I've just started wanting to try out nvim for development.

The project I'm working on generates a LOT of data.  My unit tests carry regression test logs for me to do performance evaluation and completeness regression testing between releases.  Thus my project test/test_data folder has some really obscenely large text files (usually named with `.log` or `.txt` or `.profile` extensions.

So for about 20-25 minutes now I've been unable to use nvim as it scanns all kinds of massive files.  I think it's even scanning `~/tmp/full_run_2017-01-30.log` right now.

Why is it doing this?  These aren't something I expect to have tags for.  Shouldn't it only be interested in source files?
