### ISSUE TITLE
Going into insert mode in the middle of a word.

### ISSUE THREAD

**Issue by Numkil** [Shougo/deoplete.nvim#7]
Whenever I go into insert mode in the middle of a word, the part after my cursor gets duplicated several times.
Before:

https://i.imgur.com/kzqi4JD.png

Now when I go into insert mode in the middle of the word document I get this, a short burst duplicating that last past of the word document, then 3 more times duplicated on a slower pace. 

https://i.imgur.com/HkUyVuE.png

I thought it would be a good idea to make you aware of this early on.

**Comment by Numkil** [comment]
Image upload on github currently not working for me..

**Comment by Shougo** [comment]
I don't reproduce the problem.
But I can reproduce wrong selection problem.
https://github.com/neovim/neovim/pull/2792 fix it.

**Comment by Numkil** [comment]
I will debug by picking apart my .vimrc when I get the time, the error is still there with lastest neovim and deoplete

**Comment by Shougo** [comment]
> I will debug by picking apart my .vimrc when I get the time, the error is still there with lastest neovim and deoplete

neovim/neovim#2792 is no meaning currently.
Because, to support neovim/neovim#2792, deoplete must change the plugin's codebase.

**Comment by marlun** [comment]
I'm also getting this from time to time. Not sure why yet.

**Comment by Shougo** [comment]
Fixed it.
Please update neovim and deoplete.
