### ISSUE TITLE
unknown function error

### ISSUE THREAD

**Issue by app** [Shougo/deoplete.nvim#701]
https://github.com/Shougo/deoplete.nvim/blob/d8da6ebf0630639ce1139d7614f6da437aa0a919/autoload/deoplete/init.vim#L24

When I open vim config files and some other file types I getting
...function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize:
E117: Unknown function: deoplete#mapping#_init

I'm not sure this is a bug, but why
error messages gone if I comment out this line?

**Comment by app** [comment]
I have no error if I just start my neovim v0.2.2

**Comment by Shougo** [comment]
I don't reproduce the error.
Have you read the issue template?

The minimal init.vim and reproduce-able instructions are needed.

I will close the issue.
If you don't read the issue template.

**Comment by Shougo** [comment]
No response?

**Comment by app** [comment]
Thank you for quick response!
I'll try to prepare minimal config today.

**Comment by Shougo** [comment]
OK.

**Comment by app** [comment]
Ok. I checked my dotfiles on fresh installed Ubuntu 17.10 with neovim v0.2.0
There are no errors AFAICS. :+1: 
Please close this issue.
