### ISSUE TITLE
Q: Can you change completion contents?

### ISSUE THREAD

**Issue by Skyfold** [Shougo/deoplete.nvim#702]
For example: If I type m some of the options I get are:

    M                  [Module]      [LC]
    Monad              [Class]       [LC] Prelude
    MapRequestEvent    [Constructor] [LC] EventType -> CULong -> Bo.. Event^@XMonad
    MappingNotifyEvent [Constructor] [LC] EventType^@-> CULong^@-> B.. Event^@Xmond
    maximum            [Function]    [LC] forall (t :: * -> *). Fol.. -> a^@Prelude
    ...
    ...
    ...

The problem is there is too much information to fit in the completion window so the middle gets truncated. However, if I could abbreviate `[Constructor]` as `[C]` and remove [LC] then I would have enough space to display the missing content. Is this something I can fix with deoplete's options?

I have extended the completion window, but Haskell type signatures are really long.

**Comment by Shougo** [comment]
For `[LC]`,

```
		" Disable the source mark.
		call deoplete#custom#source('omni', 'mark', '')
```

For `[Constructor]`,

`:help deoplete-create-filter`
