### ISSUE TITLE
Deoplete fails to initialize after restoring session

### ISSUE THREAD

**Issue by mr-sudaca** [Shougo/deoplete.nvim#708]
#### Environment Information

 * deoplete version(SHA1):  a80fd52

 * OS: MacOS 10.13.3

 * neovim/Vim version: Vim 8.0.1650

#### vimrc

```vim
Plugin 'Shougo/deoplete.nvim'
Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'

let g:deoplete#enable_at_startup = 1
```

#### how to reproduce

 1. Create a session `mksession!`
 2. close vim
 3. restore session `vim -S`

#### Error:

```
Error detected while processing function deoplete#enable[1]..deoplete#initialize[1]..deoplete#init#_initialize[17]..deoplete#init#_variables[12]..neovim_rpc#serveraddr
```

**Comment by Shougo** [comment]
It is not deoplete problem.
vim-hug-neovim-rpc does not support session restore.

You should disable global variables restore.

`set sessionoptions-=globals`

**Comment by mr-sudaca** [comment]
@Shougo understood. Thanks for your reply!
