### ISSUE TITLE
TypeError: 'int' object is not iterable (With jedi-vim)

### ISSUE THREAD

**Issue by rafi** [Shougo/deoplete.nvim#71]
Problem: When using deoplete+jedi-vim, error when loading Python file. 

OS: OSX 10.11
Neovim: Latest `master` (`86ce65ebe9946096438879190cce724af7fdba21`)

Minimal nvimrc:
```viml
set runtimepath+=~/.config/nvim/bundle/deoplete.nvim/
set runtimepath+=~/.config/nvim/bundle/jedi-vim/
filetype plugin indent on
let g:deoplete#enable_at_startup = 1
autocmd FileType python setlocal omnifunc=jedi#completions
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0
let g:jedi#smart_auto_mappings = 0
let g:jedi#show_call_signatures = 0
imap <expr> <TAB> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
```

Re-produce:
1. Open `nvim`
2. Edit a python file

Error:
```
Failed to load Python host. You can try to see what happened by starting Neovim with the environment variable $NVIM_PYTHON_LOG_FILE set to a file and opening
the generated log file. Also, the host stderr will be available in Neovim log, so it may contain useful information. See also ~/.nvimlog.
```

Log attached:
[neovim.log_27503.txt](https://github.com/Shougo/deoplete.nvim/files/35778/neovim.log_27503.txt)

**Comment by HerringtonDarkholme** [comment]
You can try jedi vim's python 3.

**Comment by rafi** [comment]
Thanks @HerringtonDarkholme, I've successfully have both `jedi-vim` and `deoplete.nvim` working together by installing nvim-python like this:
```sh
pip-2.7 install --user --upgrade neovim
pip-3.4 install --user --upgrade --force-reinstall neovim
```
And adding this to nvim's config:
```viml
let g:jedi#force_py_version = 3
```

**Comment by Shougo** [comment]
It is not deoplete issue.  It is jedi-vim feature.
jedi-vim skips the Python interpreter check in neovim.
So, you must both Python and Python3 neovim module.
You can see it from the jedi-vim code.
