### ISSUE TITLE
Function snippets with Ultisnippets expand parameters

### ISSUE THREAD

**Issue by pLesur** [Shougo/deoplete.nvim#724]
# Problems summary

So using LanguageClient-neovim, deoplete, and ultisnips, I discovered a(n almost) nice feature, which is completion of function with parameters ie:

```rust
fn fooo(bar: i32) {}

fn main() {
  foo // deoplete kicks in, and offers me to expand fooo(bar: i32)
}
```

but after selecting the entry with C-n, here's the line:

```rust
    fooo(${1:bar})
```

And I cannot use my ultisnips bindings to change the template values as you might have guessed.

When expanding any other template (not a dynamic one, generated by LanguageClient), it works as expected.

## Expected

after expanding, my cursor should be over a selected `bar` so I can fill in the value.

## Environment Information

 * deoplete version(SHA1):
34ca8838dfd9600b0a777ecaafafb1e61c8f385b

 * OS:
Linux foo 4.15.15-1-ARCH #1 SMP PREEMPT Sat Mar 31 23:59:25 UTC 2018 x86_64 GNU/Linux

 * neovim/Vim version:
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#LanguageClient#check
========================================================================
  - OK: binary found: /home/plesur/.config/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.67 

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.14
  - INFO: python2-neovim version: 0.1.13 (outdated; from ~/.local/lib/python2.7/site-packages/neovim)
  - WARNING: Latest python2-neovim is NOT installed: 0.2.4

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python3 version: 3.6.4
  - INFO: python3-neovim version: 0.2.4
  - OK: Latest python3-neovim is installed: 0.2.4

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin()
Plug 'rust-lang/rust.vim'

Plug 'autozimu/LanguageClient-neovim', {
    \ 'branch': 'next',
    \ 'do': 'bash install.sh',
    \ }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'
call plug#end()

let g:deoplete#enable_at_startup = 1
let g:UltiSnipsExpandTrigger="<C-s>"
let g:LanguageClient_serverCommands = {
    \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
    \ }
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. Write this to some rust file:
```rust
fn fooo(bar: i32) {}

fn main() {
  //foo // deoplete kicks in, and offers me to expand fooo(bar: i32)
}
```

 2. try to use `foo` to get the autocomplete
 3. realize that the template was expanded but not usuable :(

I think this might be due to deoplete directly writing the template when selecting the completion entry.
ie with 'regular' completion entry, this will happen:

```cpp
vec // completion kicks in
vector // I move the selection to the snippets, now I press the ultisnips expansion shortcut
vector<char> v; // snippet is expanded, char is selected
```

with this issue (with dynamic snippets), here's what happen:
```rust
foo //deoplete kicks in
fooo(${1:bar}) // selecting the foo completion directly writes the raw snippet!

// instead we ought to have
fooo
// then press the ultisnip shortcut
fooo(bar) // bar is selected
```

It seems to me this is indeed a deoplete issue, but of course I could be wrong. Hope that's enough information (hope having rust code for the example is not a problem?).

**Comment by Shougo** [comment]
It is not deoplete feature.
It is LanguageClient-neovim feature.

**Comment by pLesur** [comment]
Ok so unless I misunderstood something the problem mentioned [here](https://github.com/Shougo/neosnippet.vim/issues/412) is the same as the one I described, but using neosnippet instead of ultisnips. So I suppose I should probably create an issue for ultisnip. You mentioned fixing the problem within deoplete in that issue I linked earlier, did you have time to work on it since then?

**Comment by Shougo** [comment]
> You mentioned fixing the problem within deoplete in that issue I linked earlier, did you have time to work on it since then?

deoppet.nvim instead of deoplete.nvim.

I have not much time now...
But I will develop the plugin in the year.

**Comment by andreyorst** [comment]
> deoppet.nvim instead of deoplete.nvim. But I will develop the plugin in the year.

@Shougo you mean that parameter expansion feature will be able for us with deoplete + deoppet plugin bundle? am I right? You don't plan to add parameter expansion to deoplete in same way how Roxma did in NCM, so it could be used with UltiSnips, and others?

**Comment by Shougo** [comment]
> This is just tab completion, I didn't expanded any UltiSnips snippet. Is it Language Client problem? Or Deoplete? Seems like deoplete does different completion with and without Ultisnips plugin.

deoplete does not do it.  LanguageClient-neovim detects UltiSnips.
Please see here.
https://github.com/autozimu/LanguageClient-neovim/blob/d690d2b62fb161266ccce15c3160760530f3c085/autoload/LanguageClient.vim#L36
