### ISSUE TITLE
Flickering with certain set of plugins (probably async)

### ISSUE THREAD

**Issue by balta2ar** [Shougo/deoplete.nvim#726]
# Problems summary

deoplete is erratically flickering and changing completion menu.

## Expected

deoplete should not flicker.

## Environment Information

 * deoplete version(SHA1): 34ca883 (HEAD -> master, origin/master, origin/HEAD) Improve timer check (3 days ago) <Shougo Matsushita>

 * OS: ArchLinux

 * neovim/Vim version: NVIM v0.2.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim

if &compatible
  set nocompatible
endif

call plug#begin('~/.vim/plugged')

"Plug 'Shougo/vimproc.vim', {'do': 'make'}
Plug 'Shougo/deoplete.nvim'

Plug 'sebastianmarkow/deoplete-rust'
Plug 'zchee/deoplete-jedi'
Plug 'wellle/tmux-complete.vim'
Plug 'balta2ar/webcomplete.vim'

call plug#end()

filetype plugin indent on
syntax enable
set nocompatible
set laststatus=2
set number
set encoding=utf-8
set fileencodings=utf-8,cp1251,koi8-r,cp866
set showcmd

"let g:deoplete#sources#webcomplete#script = '~/.local/bin/bt words'
let g:deoplete#sources#webcomplete#script = 'sleep 5 && ls -1 /bin'
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

```
nvim -u min.vim
```
enter two symbols.

## Screen shot (if possible)

![deoplete-flickering](https://user-images.githubusercontent.com/340676/38575038-0c47cc2e-3d03-11e8-825a-ae6efab44165.gif)

I don't know why, but exactly this combination of plugins causes flickering. If I disable any one of them, it's gone. This is weird because if I simply open a new file, deoplete-rust and deoplete-jedi do not produce any results (empty file is neither rust or python code, right?), however, if I disable any of them, it becomes OK. It looks like some sort of race condition or maybe there is something in deoplete that relies on the order of dictionary key (that may be changing). I'm not sure...

Notice the config:
```
let g:deoplete#sources#webcomplete#script = 'sleep 5 && ls -1 /bin'
```
This is only for demo purpose. In real life, there is a command that executes for about 1-2 seconds. In this example, it continues to flicker just about those 5 seconds.

**Comment by Shougo** [comment]
> however, if I disable any of them, it becomes OK. 

You should increase `g:deoplete#num_processes` value.

**Comment by Shougo** [comment]
And you can disable asynchronous update.
I have added the feature.

**Comment by balta2ar** [comment]
https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L1440
By the way, this example in the docs is syntactically wrong.

I've updated to the  0e6c597 and tried a setting as follows and it didn't fix anything, still flickering:
```
call deoplete#custom#option('auth_refresh_delay', 0)
```

However increasing the number of processes helped:
```
call deoplete#custom#option('num_processes', 5)
```
Is it possible to fix the issue without increasing the number of processes? It worked fine one month ago...

**Comment by Shougo** [comment]
```vim
call deoplete#custom#option('auto_refresh_delay', 0)
```

It is `auto_refresh_delay` option.

**Comment by Shougo** [comment]
> By the way, this example in the docs is syntactically wrong.

Fixed.

**Comment by Shougo** [comment]
> Is it possible to fix the issue without increasing the number of processes? It worked fine one month ago...

The parallel feature is merged one month ago.

**Comment by Shougo** [comment]
I have tested it.  It works.

It disables asynchronous update(you have said it is flickering).

**Comment by Shougo** [comment]
You should enable `deoplete-options-refresh_always`.

**Comment by Shougo** [comment]
The flickering is feature of deoplete.
Because it is asynchronous update feature.

Please see the issue.
https://github.com/Shougo/deoplete.nvim/issues/471
(I think you have seen it.  So why?)

**Comment by Shougo** [comment]
The current implementation has some limitation.
Auto completion plugin must close the popup window when updating.
If the popup menu can be updated without closing, it will be no flicker.
But it is not deoplete problem.

**Comment by balta2ar** [comment]
I'm not sure "flickering" is the best word to describe it though... Did you see the gif? Do you agree that it's looking weird and it shouldn't be shaking like that? (and it wasn't like that before)

deoplete is just reordering items in the menu without a reason. It received the output from sources, say, after the first 100ms, and then during the following 5 seconds the trembling (shaking, shivering) continues. Why? There is no new input that could change the order of the items in the menu. The list of candidates is the same during these whole 5 seconds. It shouldn't be changing like that, in my opinion.

Is there a restriction that if you have async plugins, then `num_processes` should be greater than the number of deoplete plugins so that there's one plugin per process? If there is no such restriction, then I think it's a bug, because deoplete used to handle async and non-async pluings in just one process, and it worked without problems.

> It disables asynchronous update(you have said it is flickering).

I don't quite understand.. does it disable the whole async functionality? So async plugins will not work when this value is 0? Is that correct?

**Comment by balta2ar** [comment]
Here is an idea: what if setting `num_processes` to 0 could mean that deoplete should detect how many deoplete plugins are installed and create as many processes as necessary automatically? If there are 3 plugins, create 3 processes, if there are 7, create 7.

**Comment by Shougo** [comment]
> I don't quite understand.. does it disable the whole async functionality? So async plugins will not work when this value is 0? Is that correct?

Yes.  The candidates will be updated when you change input.

**Comment by Shougo** [comment]
> Also, notice that it's only happening when the menu is displayed for the first time after the start of neovim (this is important). Next time deoplete shows menu, it's working fine. Probably, some caching kicks in.

Because, the first candidates generation is slow.
It is caching feature.

**Comment by Shougo** [comment]
> Here is an idea: what if setting num_processes to 0 could mean that deoplete should detect how many deoplete plugins are installed and create as many processes as necessary automatically? If there are 3 plugins, create 3 processes, if there are 7, create 7.

It can.
