### ISSUE TITLE
Use 'iskeyword' as default for buffer's keyword patterns

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#73]
For `g:deoplete#_keyword_patterns` there should maybe be a buffer-local default based on `'iskeyword'`.

Something in this direction?
```
  augroup deoplete_keywords
    au!
    au InsertEnter * if !exists('b:deoplete_keyword_patterns')
          \ let b:deoplete_keyword_patterns = &isk \| endif
  augroup END
```

**Comment by blueyed** [comment]
`'b:deoplete_keyword_patterns'` should not be considerd to be a dict in this case probably?

Does it make sense to have a dict in this case?

**Comment by blueyed** [comment]
Seems to be difficult to do, because of the necessary conversion from Vim to Python regexp.

I am using this now:

  let g:deoplete#keyword_patterns = {'_': '[a-zA-Z_]\w*'}
  let g:deoplete#keyword_patterns.vim = '[a-zA-Z_][\w#:_-]*'

**Comment by Shougo** [comment]
Yes.

> For g:deoplete#_keyword_patterns there should maybe be a buffer-local default based on 'iskeyword'.

You cannot use 'iskeyword' in deoplete.  It is VimL feature.
It must be Python regexp.
Closing.

**Comment by blueyed** [comment]
Yeah, I've noticed this.

But it would be possible to convert it: I could imagine supporting `\k` in the pattern, which would then be replaced by what `iskeyword` would match, before using it in Python.

**Comment by Shougo** [comment]
OK.  I get it.  I will implement it.

**Comment by Shougo** [comment]
Implemented done.
You can use `\k` as iskeyword pattern.
