### ISSUE TITLE
What happened to `deoplete#util#set_pattern`?

### ISSUE THREAD

**Issue by clawoflight** [Shougo/deoplete.nvim#730]
[deoplete-github](https://github.com/SevereOverfl0w/deoplete-github/) recommends using it as part of it's configuration.
An update seems to have removed it, but I can't find any information about why or what should be used instead.

**Comment by Shougo** [comment]
Please don't use `deoplete#util#set_pattern()`.
It is not documented internal function.
So it is removed.

If you need the function, please define it in your vimrc.

**Comment by Shougo** [comment]
```vim
function! s:set_pattern(variable, keys, pattern) abort
  for key in deoplete#util#split(a:keys)
    if !has_key(a:variable, key)
      let a:variable[key] = a:pattern
    endif
  endfor
endfunction
```
