### ISSUE TITLE
Keyword patterns in buffer and dict sources

### ISSUE THREAD

**Issue by petobens** [Shougo/deoplete.nvim#733]
This is basically a copy of [this comment of mine](https://github.com/lervag/vimtex/issues/1110#issuecomment-382718910).

i) Docs seems to be wrong regarding setting `omni input_patterns`: `var` and not`source` should be used: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L553
ii) Is it possible to specify keyword_patterns for dict and buffer sources? I would like to do something like the following:
```vim
let tex_buffer_patterns = {'tex' : '[a-zA-Z_]\w{2,}:\S+'}
let tex_dict_patterns = {'tex' : '\\?[a-zA-Z_]\w*'}
call deoplete#custom#source('buffer', 'keyword_patterns', tex_buffer_patterns)
call deoplete#custom#source('dictionary', 'keyword_patterns', tex_dict_patterns)
```
Thanks in advance

**Comment by Shougo** [comment]
> i) Docs seems to be wrong regarding setting omni input_patterns: var and notsource should be used: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L553

Fixed.

> ii) Is it possible to specify keyword_patterns for dict and buffer sources? I would like to do something like the following:

Why this feature is needed?
Please describe it more.

**Comment by Shougo** [comment]
> i) Docs seems to be wrong regarding setting omni input_patterns: var and notsource should be used: https://github.com/Shougo/deoplete.nvim/blob/master/doc/deoplete.txt#L553

Fixed.

**Comment by petobens** [comment]
Thank you!
