### ISSUE TITLE
:cnext doesn't go over entire list anymore

### ISSUE THREAD

**Issue by stevenroose** [Shougo/deoplete.nvim#734]
Not sure if this is a deoplete or deoplete-go issue.

I have `map <C-n> :cnext<CR>`.

But since I updated now (last update before was like 3 weeks or so), Ctrl-N shows the entire list of suggestions, but on a second hit, it autocompletes the first option which makes the other options disappear. So it's no longer possible to scroll through the entire list of options.

Ctrl-N used to behave like the down arrow. Not it behaves like Ctrl-N + Enter at once.

**Comment by Shougo** [comment]
I don't understand.
Please create the minimal init.vim and reproduce instructions.
If not, I will close the issue.

**Comment by Shougo** [comment]
No response.

**Comment by stevenroose** [comment]
Yeah it still persists, but I'm not sure how to reproduce it.

This is what happens. I want to type `x.DoSomeOtherThing`, I start typing:

```
x.DoSo
```

The autocomplete looks like this:
```
x.DoSo
 |DoSomething     |
 |DoSomeOtherThing|
 |DoSomeMoreThings|
```

So I want the second option. So I need to press Ctrl-N twice (mapped to `:cnext`). On the first press of Ctrl-N, this happens

```
x.DoSomething
 |DoSomething|
```
It already puts the complete first item after the cursor, which makes the two other options disappear from the autocomplete menu. On a second Ctrl-N press, nothing happens since `x.DoSomething` is the only option available.

**Comment by Shougo** [comment]
@stevenroose You need to create the minimal vimrc.
It must be reproduce-able for me.

And you are confusing.

`map <C-n> :cnext<CR>` is normal mode mapping.
It does not affect any of deoplete features.

**Comment by Shougo** [comment]
Please read other issues.

I have fixed all reproduce-able issues.
But I don't fix not reproduce-able issues.

**Comment by Shougo** [comment]
I think it is same problem.

https://github.com/Shougo/deoplete.nvim/issues/704

It is fixed in the latest version.

So I must say "please don't ignore issue template" and please use the latest version.
