### ISSUE TITLE
please add default mappings option

### ISSUE THREAD

**Issue by ahonn** [Shougo/deoplete.nvim#739]
I use the latest version of deoplete.nvim. I set `imap <C-e> <plug>(emmet-expand-abbr)` in my vimrc to use emmet-vim, but <C-e> still run deoplete#cancel_popup().

I found this was added in this [commit](https://github.com/Shougo/deoplete.nvim/commit/9d6c386a28ee3673ad86d4e61edaf9562cfc08c5).
So, please add default mappings option to close this default mappings(E.g. `g:deoplete_default_mappings = 0`)

Or do you have a better solution? please tell me, thanks!

**Comment by balta2ar** [comment]
Same here, this line (https://github.com/Shougo/deoplete.nvim/commit/9d6c386a28ee3673ad86d4e61edaf9562cfc08c5#diff-65f3e5a7f2ef7e1a93c042ae5f899b2fR10) broke my `C-y` mapping for UltiSnips.

**Comment by Alok** [comment]
@balta2ar Yeah, I ended up deleting the offending `c-y` line from the source until I can figure out a cleaner fix.
