### ISSUE TITLE
Enabling omni completion with "disable_auto_complete"

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#74]
I am using `disable_auto_complete = 1` to trigger/map it manually, but would like for the member/omni completion to be triggered still automatically (e.g. when typing a `.` in Python).

**Comment by Shougo** [comment]
> I am using disable_auto_complete = 1 to trigger/map it manually, but would like for the member/omni completion to be triggered still automatically (e.g. when typing a . in Python).

I think it is vim-jedi completion.
Please disable jedi default auto completion.

Please create minimal init.vim.

**Comment by Shougo** [comment]
Please see https://github.com/Shougo/deoplete.nvim/issues/75#issuecomment-157474545

**Comment by blueyed** [comment]
Isn't it that `g:deoplete#disable_auto_complete = 1` will disable deoplete completely?
I am looking for a way to only disable it for keyword completion while typing, but it should be still triggered for member/omni completion.

**Comment by Shougo** [comment]
OK.  I get it.
It is new feature.
I will add it.

**Comment by blueyed** [comment]
Please make it optionally, i.e. the current behavior is fine by default.

**Comment by Shougo** [comment]
Of course Yes.

**Comment by wavded** [comment]
Great job on this @Shougo!  I agree with @blueyed that it would nice to be able to disable keyword as it can get pretty noisey

**Comment by blueyed** [comment]
@wavded 
This is my current config in this regard:

```
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#disable_auto_complete = 1

  fun! _My_deoplete_tab()
    if pumvisible()
      return "\<C-n>"
    endif
    let pos = getcurpos()
    let c = getline(pos[1])[pos[2]-2]
    echom string(pos) c
    if c =~ '\k'
      return deoplete#mappings#manual_complete()
    endif
    return "\<Tab>"
  endfun
  inoremap <silent><expr> <Tab> _My_deoplete_tab()
  inoremap <expr> <S-Tab>  pumvisible() ? "\<C-p>" : "\<S-Tab>"

  " Toggle deoplete.
  fun! _My_toggle_deoplete()
    let g:deoplete#disable_auto_complete = !g:deoplete#disable_auto_complete
  endfun
  noremap  <f11> :<C-u>call _My_toggle_deoplete()<cr>
  inoremap <f11> <c-o>:call _My_toggle_deoplete()<cr>

  " Via g:deoplete#_keyword_patterns
  let g:deoplete#keyword_patterns = {
        \ '_': '[a-zA-Z_]\w*',
        \ 'vim': '[a-zA-Z_][\w#:_-]*'
        \ }
```

**Comment by wavded** [comment]
Thx @blueyed, I'll check that out.

One thing I noticed that is really annoying is that the suggestion list flickers with every backspace key, is there a way around that, typing stuff seems fine.  Anyone else experiencing that?

**Comment by Shougo** [comment]
> One thing I noticed that is really annoying is that the suggestion list flickers with every backspace key, is there a way around that, typing stuff seems fine. Anyone else experiencing that?

Unfortunately, it is feature.  Deoplete must regenerate the candidates.

**Comment by Shougo** [comment]
Implemented.
