### ISSUE TITLE
Add support for trailing punctuation

### ISSUE THREAD

**Issue by Dbz** [Shougo/deoplete.nvim#743]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

When programming in Ruby, methods that are truthy often end in `?`. For example, if you want to know if an integer is zero, you would do `number.zero?`, same for `#nil?` or any custom method. If you define a method `#animal?`, autocomplete will suggest `animal` instead of `animal?`. The same goes for methods that end in bang (`!`).

## Expected

Methods with trailing punctuation are auto suggested properly.

## Environment Information

 * deoplete version(SHA1)
d8da6eb

 * OS:
osx 10.13.3

 * neovim/Vim `:version` output:
vim 8.0

**Comment by Dbz** [comment]
Please let me know if you would like any other information. I didn't think it was necessary, so I cut a lot of fields from the initial issue

**Comment by Shougo** [comment]
```vim
		call deoplete#custom#option('keyword_patterns', {
		\ '_': '[a-zA-Z_]\k*',
		\ 'ruby': '[a-zA-Z_]\w*[!?]?',
		\})
```

**Comment by Dbz** [comment]
You are the best
