### ISSUE TITLE
Complete cache is used without consider the content have changed

### ISSUE THREAD

**Issue by chemzqm** [Shougo/deoplete.nvim#747]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

https://asciinema.org/a/179174

## Expected

Cache should not be used when there is buffer content change.

## Reproduce way

Change the buffer content by using `setline` function in completeDone autocmd, and revoke completion at same position.

**Comment by Shougo** [comment]
Yes, it is the feature.
The cache is updated only `BufWritePost`.
It is for the performance.

`around` source does not cache the content.
