### ISSUE TITLE
Deoplete with Slimv?

### ISSUE THREAD

**Issue by DaveDay** [Shougo/deoplete.nvim#756]
Shougo, 
Thanks so much for Deoplete, I used to maintain 2 separate configs, one for Deoplete and one for YCM but Deoplete has grown up so much I now use just Deoplete.

I have embarked on learning Mit-Scheme, Common Lisp and Clojure; all using Slimv as my main plugin. Slimv provides Lisp fuzzy <TAB> completions pretty well, using a swank server to provide completions.  But I am spoiled, you see.  Deoplete is still there, supplying buffer, tag, etc completions but competing with the swank <TAB> completions from Slimv.  I would like to have Deoplete gather all completion candidates and present them to me automatically as usual.  

There is 'clojure-vim/async-clj-omni' which has already accomplished this for Clojure with tpope/fireplace but I need something that will work with Slimv.  I think that if Deoplete would work with Slimv/swank then it would work with scheme, common lisp, and Clojure (basically any lisp that can cooperate/work with a swank server to provide completions.

Thanks so much for anything you can do to help.

Dave Day

**Comment by Shougo** [comment]
You should use `deoplete-options-omni_patterns`.
