### ISSUE TITLE
Completions are not shown after deleting characters in insert mode

### ISSUE THREAD

**Issue by copy** [Shougo/deoplete.nvim#763]
# Problems summary

Completions are not shown after typing out a non-completion word and then using backspace or ctrl+w. 

## Expected

Completions should be shown again after backspace or ctrl+w.

## Environment Information

 * deoplete version(SHA1): 26334d38a530754368a8fce91ca8f5ef8d3643a3

 * OS: Arch Linux

 * neovim/Vim `:version` output:

```
% nvim --version
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

All okay (not pasting for brevity)

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/.config/nvim/bundle/deoplete.nvim/
set runtimepath+=~/.config/nvim/bundle/deoplete-jedi/
let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

For demo purposes I'm using deoplete-jedi, but I also have this issue with other completion sources.

 1. Insert "import os" and a new line
 2. Insert "os." — as expected completions are shown
 3. Insert "foo" (after "os.")  — as expected no completions are shown
 4. Insert backspace several times or ctrl+w so that the line starts with "os." — no completions are shown, but it should show the same completions as in 2.  

## Screen shot (if possible)

In chronological order:

![1](https://user-images.githubusercontent.com/1816456/40274181-e4cec330-5b95-11e8-9fd8-23dc114faa93.png)
![2](https://user-images.githubusercontent.com/1816456/40274182-e4ee5614-5b95-11e8-9bd7-16eaf0db1d20.png)
![3](https://user-images.githubusercontent.com/1816456/40274183-e50f842e-5b95-11e8-80ff-12fb310b9647.png)
![4](https://user-images.githubusercontent.com/1816456/40274184-e52bdfa2-5b95-11e8-8032-42d664066395.png)
![5](https://user-images.githubusercontent.com/1816456/40274185-e543a434-5b95-11e8-8f01-9431e9f582f4.png)
![6](https://user-images.githubusercontent.com/1816456/40274186-e5700e02-5b95-11e8-8a48-5935d894e03d.png)

## Upload the log file
[log.txt](https://github.com/Shougo/deoplete.nvim/files/2019897/log.txt)

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/754

Same problem?

**Comment by callmekohei** [comment]
Hello!  It's me too.

# Problems summary

![screen shot 2018-05-20 at 16 41 28](https://user-images.githubusercontent.com/17691683/40276765-7096a902-5c4d-11e8-8bcb-086b8d1c5e77.png)

## Expected

![screen shot 2018-05-20 at 16 45 31](https://user-images.githubusercontent.com/17691683/40276761-6902f808-5c4d-11e8-88ea-3b3a2cb47266.png)

## Environment Information

 * deoplete version(SHA1):
```
1cacfeb Sun May 20 14:36:19 2018 +0900
Fix #759 add matcher_key feature
(HEAD -> master, origin/matcher_key)
```

 * OS:
```shell
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E202
```

 * neovim/Vim `:version` output:
```shell
NVIM v0.3.0-1129-g7e9afca99
Build type: Release
LuaJIT 2.0.5
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):
```vim
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: has("nvim") was successful
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='Apple_Terminal'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "/usr/local/bin/python2.7"
  - INFO: Executable: /usr/local/bin/python2.7
  - INFO: Python2 version: 2.7.15
  - INFO: python2.7-neovim version: 0.2.6
  - OK: Latest python2.7-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/local/bin/python3.6"
  - INFO: Executable: /usr/local/bin/python3.6
  - INFO: Python3 version: 3.6.5
  - INFO: python3.6-neovim version: 0.2.6
  - OK: Latest python3.6-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" set path
set runtimepath+=/Users/callmekohei/.config/nvim/dein/repos/github.com/Shougo/deoplete.nvim/
set runtimepath+=/Users/callmekohei/tmp/test-deoplete/

 " turn on plugins
set nocompatible
filetype plugin indent on
syntax enable

" setting of deoplete
let g:deoplete#enable_at_startup = 1
```

## Sample deoplete source
```python
from deoplete.source.base import Base
import re

class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name      = 'callmekohei'
        self.mark      = '[callmekohei]'
        self.filetypes = ['text']
        self.input_pattern = (r'List\.')

    def get_complete_position(self, context):
        m = re.search( r'\w*$', context['input'] )
        return m.start() if m else -1

    def gather_candidates(self, context):
        return [
            "map"
            ,"map2"
            ,"map3"
            ,"mapFold"
            ,"mapfoldBack"
            ,"mapi"
            ,"mapi2"
            ,"max"
            ,"maxBy"
            ,"min"
            ,"minBy"
        ]
```

## The reproduce ways from neovim/Vim starting (Required!)

launch neovim
```shell
$ nvim -N -u minimal.vim bar.txt
```

input following
![screen shot 2018-05-20 at 16 38 01](https://user-images.githubusercontent.com/17691683/40276775-ac1f0a28-5c4d-11e8-84a1-80978ac5c9dc.png)

**Comment by Shougo** [comment]
@callmekohei It is feature of min_pattern_length.

```python
self.input_pattern = (r'List\.')
```

It means `List\.$`.
It does not match `List.m` pattern.
So it must be:

```python
self.input_pattern = (r'List\.\w*')
```

**Comment by callmekohei** [comment]
@Shougo Thank you for your rapid reply. 😄 

So, I just try it now. ` self.input_pattern = (r'List\.\w*')`

But it does not work well. 

I think that `deoplete` can not deal with `cash list` well. 

I'll check it more.

Thanks.

**Comment by Shougo** [comment]
> But it does not work well.

I don't understand.
Please explain it more clearly.

**Comment by callmekohei** [comment]
@Shougo 

like this
![untitled](https://user-images.githubusercontent.com/17691683/40278558-0957f1a8-5c6e-11e8-8103-ee83d20a06ae.gif)

01. expand trigger with `.`
```
     0123456789
--------------
List.
    map 
    map2 
    map3 
    mapFold 
    mapFoldBack 
    mapi 
    mapi2 
    max 
    maxBy 
    min 
    minBy 
```
02. choice `mapFold`
```
     0123456789
--------------
List.mapFold
```

03. input `del` backfoward
```
     0123456789
--------------
List.mapFold
```
```
     0123456789
--------------
List.mapFol
```
```
     0123456789
--------------
List.mapFo
```
```
     0123456789
--------------
List.mapF
```
```
     0123456789
--------------
List.map
    map           [~] A
    mapFoldBack   [callmekohei]
    map           [callmekohei]
    map2          [callmekohei]
    map3          [callmekohei]
    mapFoldBack   [callmekohei]
    mapi          [callmekohei]
    mapi2         [callmekohei]
```


I realize now ...

## always expand at position 2 when cursor go backward
```
       *
     0123456789
--------------
List.map
    map           [~] A
    mapFoldBack   [callmekohei]
    map           [callmekohei]
    map2          [callmekohei]
    map3          [callmekohei]
    mapFoldBack   [callmekohei]
    mapi          [callmekohei]
    mapi2         [callmekohei]
```

**Comment by callmekohei** [comment]
### additing

deoplete source
```python
from deoplete.source.base import Base
import re

class Source(Base):
    def __init__(self, vim):
        super().__init__(vim)
        self.name      = 'callmekohei'
        self.mark      = '[callmekohei]'
        self.filetypes = ['text']

    def gather_candidates(self, context):
        return [
            "map"
            ,"map2"
            ,"map3"
            ,"mapFold"
            ,"mapfoldBack"
            ,"mapi"
            ,"mapi2"
            ,"max"
            ,"maxBy"
            ,"min"
            ,"minBy"
        ]
```
do following
```
$ nvim -N -u minimal.vimrc bar.txt
```
expand at cursor position 2
```
  *
0123456789
--------------
ma|
  ma            [~] A
  map           [callmekohei]
  map2          [callmekohei]
  map3          [callmekohei]
  mapFold       [callmekohei]
  mapfoldBack   [callmekohei]
  mapi          [callmekohei]
  mapi2         [callmekohei]
  max           [callmekohei]
  maxBy         [callmekohei]
```
chose `mapFold`
```
0123456789
--------------
mapFold
```
del backward
```
0123456789
----------
mapFold|
```
```
0123456789
----------
mapFol|
```
```
0123456789
----------
mapFo|
```
```
0123456789
----------
mapF|
```
```
   *
0123456789
----------
map|
    mapFold       [callmekohei]
    map           [callmekohei]
    map2          [callmekohei]
    map3          [callmekohei]
    mapfoldBack   [callmekohei]
    mapi          [callmekohei]
    mapi2         [callmekohei]
```

**Comment by callmekohei** [comment]
# My understanding at the moment

| direction     | expand at cursor position |
| ------------- | :-------------:           |
| forward       | 2                         |
| backward      | 3                         |

# my expected

| direction     | expand at cursor position |
| ------------- | :-------------:           |
| forward       | 2                         |
| backward      | -                         |

deoplete use cash list at backward

**Comment by copy** [comment]
> #754
>
> Same problem?

Yeah, looks like the same problem. I can still reproduce my problem after 9a72cb89631dafd776fdcb88c65954ccaf0d00a7 (latest master).

**Comment by Shougo** [comment]
Fixed on master.
