### ISSUE TITLE
cpoptions breaks deoplete

### ISSUE THREAD

**Issue by petong** [Shougo/deoplete.nvim#769]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
setting cpoptions in init.vim breaks deoplete. typing two consecutive characters in input mode results in ```<C-r>=deoplete#mapping#_complete()<CR>```

## Expected
deoplete should complete after typing two consecutive characters

## Environment Information

 * deoplete version(SHA1): 165e693cbb1198569954b2a01f7ba56026bf7ddf

 * OS: OSX 10.13.5

 * neovim/Vim `:version` output: 
```
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/config -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/src/nvim/auto -I/tmp/neovim-20180209-92407-udkzoo/neovim-0.2.2/build/include
Compiled by brew@HighSierra.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.2.2_1/share/nvim"```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
call plug#begin('~/.config-test/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
let g:deoplete#enable_at_startup = 1
call plug#end()

set cpoptions=c
```


## The reproduce ways from neovim/Vim starting (Required!)

 1. start nvim
 2. type 'fo'

**Comment by petong** [comment]
@Mephistophiles  that change fixes the problem, thanks!

**Comment by teto** [comment]
Same problem and the patch also works for me.

**Comment by Shougo** [comment]
I have tested it and I have found it is bug of neovim.
Vim8 does not have the problem.

You must include `B` in cpoptions to work.

**Comment by Shougo** [comment]
So it works.

```vim
set cpoptions=Bc
```

**Comment by Shougo** [comment]
It should be reported in neovim issues.

**Comment by blueyed** [comment]
@Shougo 
What is the neovim bug here exactly?
That is does not work without B in cpoptions?

**Comment by Shougo** [comment]
Yes.

**Comment by blueyed** [comment]
Can you please try if https://github.com/Shougo/deoplete.nvim/pull/806 also/still works for you?

Not everybody here was using `cpoptions=c`, right?

**Comment by teto** [comment]
I've recently updated both neovim and deoplete and the bug seems to be back.
When I do `verbose set cpoptions?`
Seems like /nix/store/y8anfk7s7r30d81c6cwr8pr7g9ifzics-neovim/share/nvim/runtime/syntax/help.vim empties cpoptions ?

**Comment by Shougo** [comment]
Fixed.

@teto  Please check your `cpoptions` value.
I think you don't include `B` in `cpoptions`.
