### ISSUE TITLE
Function to disable deoplete

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#77]
I would like deoplete to be enabled or disabled explicitly, and therefore a function like `deoplete#init#disable()` would be useful.

**Comment by blueyed** [comment]
Currently that gets done through `g:deoplete#disable_auto_complete`, which might be enough?!

Feel free to close the issue.

**Comment by blueyed** [comment]
I'm closing this myself, given the last comment / existing functionality.

**Comment by Shougo** [comment]
You can use `b:deoplete_disable_auto_complete` for it.

**Comment by fkotsian** [comment]
Used `let g:deoplete#enable_at_startup = 0` in .vimrc[.local], seemed to work
