### ISSUE TITLE
[Question] How can I remap ctrl-j to ctrl-y to close deoplete popup?

### ISSUE THREAD

**Issue by viniciusarcanjo** [Shougo/deoplete.nvim#771]
Hi @Shougo, 

I'd rather have to type `<C-j>` instead of `<C-y>` to accept the candidate and close the popup, I've tried these two mappings but they didn't work for me, could you shed some light how could I map this:

```
inoremap <silent><expr> <C-j> pumvisible() ? "\<C-Y>" : "\<CR>"
```

```
inoremap <silent><expr> <C-j> pumvisible() ? "\<C-Y>" : deoplete#close_popup()
```

Thanks!

**Comment by Shougo** [comment]
```vim
inoremap <silent><expr> <C-j> pumvisible() ? "\<C-Y>" : "\<CR>"
```

Works for me.

**Comment by Shougo** [comment]
Note:  You have ignored the issue template and it works for me.
So I have closed your issue.

**Comment by viniciusarcanjo** [comment]
Hi, @Shougo. 

It's probably an incompatibility with other plugins then. Thanks! It's good to know that the mapping is right.

**Comment by Shougo** [comment]
OK
