### ISSUE TITLE
Deoplete forces completion list refresh when call complete from viml function

### ISSUE THREAD

**Issue by andreyorst** [Shougo/deoplete.nvim#772]
I'm trying to create function that will enter insert mode and then will call a `complete()` function to show me some list. However while deoplete is active the list is being refreshed. But such situation is not happening if I call complete from a remap.

The code:
```vim
function! Compl(list)
    call complete(col('.'), a:list)
    return ''
endfunction

function! CallCompl()
    call feedkeys("a\<C-R>=Compl(['some', 'list'])\<CR>", "n")
endfunction
```
If I do `:call CallCompl()` I will end up with this:
![image](https://user-images.githubusercontent.com/19470159/40880375-4d77a938-66b8-11e8-87dc-91eee9679724.png)
Instead of:
![image](https://user-images.githubusercontent.com/19470159/40880380-5d2352f6-66b8-11e8-9140-9daedb49a503.png)
The first screenshot shows list with a single item: `some [~] A` which is clearly a deoplete's list. But if I toggle deoplete, by using `deoplete#toggle()` I'll see the list provided by `complete()` function. In fact, when deoplete is active, I can still see the list, but for a split second, before screen is redrawn.

But.

If I do this thing by hand, i mean enter insert mode, press <kbd>Ctrl</kbd>+<kbd>R</kbd>, hit <kbd>=</kbd>, type a command `Compl(['some', 'list'])` and hit <kbd>Enter</kbd>, the list will be shown just like if deoplete wasn't active.

![deoplete](https://user-images.githubusercontent.com/19470159/40880482-792c69e0-66ba-11e8-894e-ee28e2c81063.gif)

Or if I call it from `inoremap` like so: `inoremap <F5> <C-R>=Compl(['some', 'list'])<Cr>` the list will be shown properly. So deoplete refreses list only if I call this with simple `call`.

---
 * deoplete version(SHA1): 26334d38a530754368a8fce91ca8f5ef8d3643a3  
 * OS: Arch Linux  
 * neovim/Vim `:version` output:  
  NVIM v0.3.0-1312-gc7350f542                                                                                                                                         
  Build type: RelWithDebInfo

**Comment by Shougo** [comment]
Yes.  deoplete refreshes the list.
Your functions is autocomplete function.
Note: You have not think it is as auto complete plugin though.
It conflicts with deoplete.

**Comment by Shougo** [comment]
> I'm trying to create function that will enter insert mode and then will call a complete() function to show me some list.

It is auto completion plugin behavior.

**Comment by andreyorst** [comment]
Well ok then. I need to show some list with deoplete. Is this possible? Something like emulating `complete()` with deoplete. Can I achieve this? I mean show specific list, *and specific list only*, automatically on certain event.

**Comment by andreyorst** [comment]
Or is there any way of temporary disabling the refreshing of the deoplete's list. I've tried to use `deoplete#toggle()` but on toggling on it refreshes the list automatically, so I can't do something like this:

```vim
function! Compl(list)
    call complete(col('.'), a:list)
    return ''
endfunction

function! CallCompl()
    call deoplete#toggle()
    call feedkeys("a\<C-R>=Compl(['some', 'list'])\<CR>", "n")
    call deoplete#toggle()
endfunction
```

**Comment by Shougo** [comment]
> I mean show specific list, and specific list only, automatically on certain event.

It seems difficult.

**Comment by Shougo** [comment]
> but on toggling on it refreshes the list automatically, so I can't do something like this:

It is difficult.
Because deoplete completion is asynchronous.

**Comment by andreyorst** [comment]
There is a complete method that uses `complete()` function. Maybe I can use this somehow?

**Comment by Shougo** [comment]
`:help deoplete-options-complete_method`

It may help it.
But I don't test it.

**Comment by andreyorst** [comment]
@Shougo That's what I've tried to achieve:
![choice](https://user-images.githubusercontent.com/19470159/40887033-cd3f265e-674a-11e8-9953-75f23d4397da.gif)
It would be super convenient to use something like `deoplete#complete()` (which has no stupid restrictions like executing only from insert mode, like original `complete()) for this.
