### ISSUE TITLE
Is there a way to start deoplete when the user first press is a key?

### ISSUE THREAD

**Issue by dylan-chong** [Shougo/deoplete.nvim#773]
I have a rather unusual setup: I use `tmux-resurrect` which starts up many vim sessions, many of which I don't use. Given that this plug-in starts up several python processes, I end up with roughly 1.5gb of RAM used up by this plug-in. 

One potential solution to this problem is to start up this plug-in only when the user first press is a key. This way, the unused vim sessions I have running in the background do not start up all these python processes. Is there a possible way to do this?

**Comment by Shougo** [comment]
dein.vim supports the feature.
Or use autocmd.

`autocmd InsertEnter * call dein#enable()`

**Comment by dylan-chong** [comment]
Thanks for your response

> `autocmd InsertEnter * call dein#enable()`

Do you mean this instead:

`autocmd InsertEnter * call deoplete#enable()`

**Comment by Shougo** [comment]
Yes
