### ISSUE TITLE
How to remove/solve an error occur by this line "from deoplete.util import get_simple_buffer_config, error"

### ISSUE THREAD

**Issue by thyeun** [Shougo/deoplete.nvim#774]
I'm running into this error that might be related with deoplete.nvim, and i cant get a support from the original creator of the plugins ``` cyansprite/deoplete-omnisharp ```.

The error show as below picture.

![screenshot_2018-06-05_05-05-57](https://user-images.githubusercontent.com/1939446/40941866-eb63edba-687e-11e8-9e80-c5bd1843ffce.jpg)

[The code](https://paste.ubuntu.com/p/ZvtRj4nxRJ/)

p/s : sorry if it is not related with deoplete.vim

**Comment by Shougo** [comment]
It is the source bug.
You need to remove the line.

```python
from deoplete.util import get_simple_buffer_config, error
```

**Comment by thyeun** [comment]
@Shougo, ok, thanks and sorry for asking question that it is not related.
