### ISSUE TITLE
Deoplete breaks indentation for Ada files

### ISSUE THREAD

**Issue by glacambre** [Shougo/deoplete.nvim#775]
# Problems summary
When editing an Ada file (the extension is ".adb" and `&ft` is set to "ada") with deoplete enabled, pressing "e" in insert mode when the file looks like this:
```ada
if True then
    Put()
    els
```
Results in a file looking like this:
```ada
if True then
    Put()
    else
```

## Expected
The resulting file should look like this:
```ada
if True then
    Put()
else
```
This is what happens when deoplete is not enabled.

## Environment Information

 * deoplete version(SHA1): f8faaf248982817cabee2ac69da7312a758fbef2

 * OS: Linux 4.16.0-1-amd64 Debian 4.16.5-1 (2018-04-29) x86_64 GNU/Linux

 * neovim/Vim `:version` output: I can reproduce on the latest master (`36ac80d5dd58e726a89c7108051e29de500a2f77`) and on NVIM v0.2.2

 * `:checkhealth` or `:CheckHealth` result(neovim only): Everything seems to work

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

I didn't add information for the rest of the sections because it seemed unnecessary. Let me know if this issue is missing information.

**Comment by Shougo** [comment]
https://github.com/neovim/neovim/pull/8349
