### ISSUE TITLE
Menu is not filtered after Backspace

### ISSUE THREAD

**Issue by balta2ar** [Shougo/deoplete.nvim#776]
# Problems summary

Coming from https://github.com/Shougo/deoplete.nvim/issues/759.
Completion menu is not filtered after hitting Backspace and removing spaces.

## Expected

Menu should be filtered and query should be applied.

## Environment Information

 * deoplete version(SHA1): f8faaf2

 * OS: Archlinux

 * neovim/Vim `:version` output: NVIM v0.2.2

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
set rtp+=~/.vim/plugged/deoplete.nvim
set rtp+=./plugins/deoplete-matcherkey

call deoplete#custom#option('num_processes', 0)
call deoplete#custom#option('smart_case', v:false)
call deoplete#custom#option('ignore_case', v:true)

inoremap <expr><C-h> deoplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"

let g:deoplete#enable_at_startup = 1
autocmd InsertEnter * call deoplete#enable()
call deoplete#enable()
call deoplete#initialize()
autocmd VimEnter * call deoplete#initialize()

```
matcherkey is this plugin: https://github.com/balta2ar/deoplete-matcherkey

## Reproduce

1. nvim -u minimal-vimrc.vim
2. type: `HGcreatebot<Space><BS>`

## Screen shot (if possible)

![deoplete-does-not-refilter-after-backspace](https://user-images.githubusercontent.com/340676/40966012-fd7c8280-68b7-11e8-89db-1952dd6bce0a.gif)

**Comment by Shougo** [comment]
Reproduced.
But it is bug of deoplete-matcherkey.

```diff
diff --git a/rplugin/python3/deoplete/sources/matcherkey.py b/rplugin/python3/deoplete/sources/matcherkey.py
index d903675..46ff26f 100644
--- a/rplugin/python3/deoplete/sources/matcherkey.py
+++ b/rplugin/python3/deoplete/sources/matcherkey.py
@@ -33,7 +33,7 @@ def get_jira_candidates(current_prefix):
     ticket_formatter = '%' + str(max_ticket_len) + 's'
     return [{'word': ticket,
              'abbr': ticket_formatter % ticket + ' ' + title,
-             'custom_key': current_prefix + title, }
+             'custom_key': 'HG' + title, }
             for ticket, title in candidates]


```

You should know deoplete source features.

I have not much time to explain for you.
So please don't ask the reason to me.
