### ISSUE TITLE
Menu padding

### ISSUE THREAD

**Issue by zezic** [Shougo/deoplete.nvim#777]
I guess that many users will find this idea useless (because it eats space), but can we have an option to enable 1-char-size padding inside menu zone or it depends on Vim menu implementation?
If you don't plan or don't want to make this feature, can you point me to code where I can experiment with this or give me another hint on how to implement this myself?

![deoplete-menu-padding](https://user-images.githubusercontent.com/1945127/41206576-b7a353be-6d0e-11e8-897d-c5f646772ed9.png)

**Comment by Shougo** [comment]
It is feature of Vim/neovim.
You cannot change the padding behavior.

And to remove the padding is very bad idea.

**Comment by zezic** [comment]
>And to remove the padding is very bad idea.
No, no, I want to **add** extra padding, not to remove it.

**Comment by Shougo** [comment]
OK.  I understand.

You can use filter feature for it.
Please read `deoplete-create-filter`.
