### ISSUE TITLE
different highlights for different sections of completion popup

### ISSUE THREAD

**Issue by BonaBeavis** [Shougo/deoplete.nvim#779]
For java there are five different columns in the completion popup. I think with different highlight for different sections it would be easier to parse with a glance. Is there any way to achieve this?

**Comment by Shougo** [comment]
It is Vim/neovim feature.
It cannot be archived by deoplete.
some neovim GUI supports the feature though.

**Comment by Shougo** [comment]
Example: https://github.com/dzhou121/gonvim/wiki/Features#autocomplete-menu-and-function-signature
