### ISSUE TITLE
deoplete start up with a lot of time

### ISSUE THREAD

**Issue by fcying** [Shougo/deoplete.nvim#780]
# Problems summary
deoplete start up with a lot of time

## Expected
speed startup

## Environment Information

 * deoplete version(SHA1):
62078d04aea43aceb7cbdcfc4b22cf8f7767f614

 * OS:
manjaro

 * neovim/Vim `:version` output:
vim: version 8.1.63

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```
set nocompatible

set runtimepath+=~/.vim/plugged/deoplete.nvim
set runtimepath+=~/.vim/plugged/nvim-yarp
set runtimepath+=~/.vim/plugged/vim-hug-neovim-rpc

filetype plugin indent on
syntax enable

let g:deoplete#enable_at_startup = 1
```

## The reproduce ways from neovim/Vim starting (Required!)

vim -u test_vimrc --startuptime log.txt
if enable deoplete, it spend about 270ms.

## Upload the log file
[log.txt](https://github.com/Shougo/deoplete.nvim/files/2109182/log.txt)
[log_nodeoplete.txt](https://github.com/Shougo/deoplete.nvim/files/2109189/log_nodeoplete.txt)

**Comment by Shougo** [comment]
You should set `g:python3_host_prog` like this.

```vim
let g:python3_host_prog = '/usr/bin/python3'
```

**Comment by fcying** [comment]
I set it,the same result
```
set nocompatible
let g:python3_host_prog = '/home/linuxbrew/.linuxbrew/bin/python3'
set runtimepath+=~/.vim/plugged/deoplete.nvim
set runtimepath+=~/.vim/plugged/nvim-yarp
set runtimepath+=~/.vim/plugged/vim-hug-neovim-rpc

filetype plugin indent on
syntax enable
let g:deoplete#enable_at_startup = 1
```
[s.log](https://github.com/Shougo/deoplete.nvim/files/2109637/s.log)

**Comment by Shougo** [comment]
Please read FAQ.

```
Q: Neovim startup is slow when |g:deoplete#enable_at_startup| is enabled.

A: If it is enabled, Neovim will enable and load deoplete in startup. It
   may be slow. You should use lazy load feature in plugin manager or use
   |:autocmd| to call |deoplete#enable()|. >

       " Enable deoplete when InsertEnter.
       let g:deoplete#enable_at_startup = 0
       autocmd InsertEnter * call deoplete#enable()
<
  And you should set |g:python3_host_prog| variable. It reduces almost 20ms
  startuptime.
```
