### ISSUE TITLE
Fixed width completion

### ISSUE THREAD

**Issue by eyvindbjartiandersen** [Shougo/deoplete.nvim#781]
First of all thank you for all of your plugins. I've been searching the documentation and I haven't found an answer to if it's possible to have a fixed width completion menu. I find the autoresizing too busy visually.

**Comment by Shougo** [comment]
What is the autoresizing?
Please describe it more clearly.

**Comment by Shougo** [comment]
I think it is Vim/neovim feature.

**Comment by eyvindbjartiandersen** [comment]
I'm not clear as to if it's a feature of Neovim or Deoplete. I wish to have a fixed width window of possible completions. As it is now the completion menu resizes when the input is changed to fit the changing of characters. I would probably set it so that approximately 50 and only characters always would be visible in the menu. How would I do that?. In Deoplete or Neovim?.

**Comment by Shougo** [comment]
Hm.  OK.  I know it is feature of neovim/Vim.

If you want to change the candidates width.
You can create the filter for it.

`:help deoplete-create-filter`

Note: I have not much time to teach deoplete features for you.
