### ISSUE TITLE
deoplete job is dead on vim 8

### ISSUE THREAD

**Issue by Projjol** [Shougo/deoplete.nvim#782]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
On opening vim and checking :messages I get the following:

> [deoplete] [yarp] [deoplete] job is dead. failed establishing channel for ['/Users/<user>/Documents/anaconda3/bin/python', '-u', '/Users/<user>/.vim/plugged/nvim-yarp/pythonx/yarp.
py', '127.0.0.1:57295', 2, 'deoplete']

Also, on opening a file deoplete auto-completion is not triggered

## Expected
Job should not fail and autocompletion should be triggered

## Environment Information

 * deoplete version(SHA1): 62078d04aea43aceb7cbdcfc4b22cf8f7767f614

 * OS: macOS 10.12.6

 * neovim/Vim `:version` output: 

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Mar 14 2018 15:43:28)
> macOS version
> Included patches: 1-1600
> Compiled by Homebrew
> Huge version without GUI.  Features included (+) or not (-):
> +acl               +cmdline_hist      +eval              +job               +mouse             +num64             +scrollbind        +termresponse      +windows
> +arabic            +cmdline_info      +ex_extra          +jumplist          -mouseshape        +packages          +signs             +textobjects       +writebackup
> +autocmd           +comments          +extra_search      +keymap            +mouse_dec         +path_extra        +smartindent       +timers            -X11
> -autoservername    +conceal           +farsi             +lambda            -mouse_gpm         +perl              +startuptime       +title             -xfontset
> -balloon_eval      +cryptv            +file_in_path      +langmap           -mouse_jsbterm     +persistent_undo   +statusline        -toolbar           -xim
> +balloon_eval_term +cscope            +find_in_path      +libcall           +mouse_netterm     +postscript        -sun_workshop      +user_commands     -xpm
> -browse            +cursorbind        +float             +linebreak         +mouse_sgr         +printer           +syntax            +vertsplit         -xsmp
> ++builtin_terms    +cursorshape       +folding           +lispindent        -mouse_sysmouse    +profile           +tag_binary        +virtualedit       -xterm_clipboard
> +byte_offset       +dialog_con        -footer            +listcmds          +mouse_urxvt       -python            +tag_old_static    +visual            -xterm_save
> +channel           +diff              +fork()            +localmap          +mouse_xterm       +python3           -tag_any_white     +visualextra
> +cindent           +digraphs          -gettext           -lua               +multi_byte        +quickfix          -tcl               +viminfo
> -clientserver      -dnd               -hangul_input      +menu              +multi_lang        +reltime           +termguicolors     +vreplace
> +clipboard         -ebcdic            +iconv             +mksession         -mzscheme          +rightleft         +terminal          +wildignore
> +cmdline_compl     +emacs_tags        +insert_expand     +modify_fname      +netbeans_intg     +ruby              +terminfo          +wildmenu
>    system vimrc file: "$VIM/vimrc"
>      user vimrc file: "$HOME/.vimrc"
>  2nd user vimrc file: "~/.vim/vimrc"
>       user exrc file: "$HOME/.exrc"
>        defaults file: "$VIMRUNTIME/defaults.vim"
>   fall-back for $VIM: "/usr/local/share/vim"
> Compilation: clang -c -I. -Iproto -DHAVE_CONFIG_H   -DMACOS_X -DMACOS_X_DARWIN  -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
> Linking: clang   -L. -fstack-protector -L/usr/local/lib -L/usr/local/opt/libyaml/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/readline/lib  -L/usr/local/lib -o vim        -l
> ncurses -liconv -framework AppKit   -mmacosx-version-min=10.12 -fstack-protector-strong -L/usr/local/lib  -L/usr/local/Cellar/perl/5.26.1/lib/perl5/5.26.1/darwin-thread-multi-2le
> vel/CORE -lperl -lm -lutil -lc  -L/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -framework CoreFoundation  -lruby.2
> .5.0 -lobjc

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
" ternjs for js completion
Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern' }
let g:python3_host_prog = '/Users/<user>/Documents/anaconda3/bin/python'
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr>
autocmd CompleteDone * pclose 
```

## The reproduce ways from neovim/Vim starting (Required!)

- Install deoplete.nvim via vim-plug
- Open vim 8
- Try `:messages` to see error

### Screenshot 
<img width="1440" alt="screen shot 2018-06-22 at 1 18 53 am" src="https://user-images.githubusercontent.com/3725578/41741999-5437295e-75ba-11e8-9cf7-26144bc5ca26.png">

**Comment by Shougo** [comment]
Please upload the log file.

```
## Debugging

Add logging settigns to your vimrc. Log files will be generated with prefix
`/tmp/nvim_log`. An alternative is to export environment variables before
starting vim/nvim.
```

```vim
let $NVIM_PYTHON_LOG_FILE="/tmp/nvim_log"
let $NVIM_PYTHON_LOG_LEVEL="DEBUG"
```

**Comment by Shougo** [comment]
```
Note: You can disable parallel feature by |deoplete-options-num_processes|.
It is workaround. >

       call deoplete#custom#option('num_processes', 1)
```

**Comment by Shougo** [comment]
In my environment, deoplete works both Vim8/neovim.
But it may not work in your environment.
Vim8 support is tricky.  I cannot grantee to work.

I recommend for you to use neovim instead.

**Comment by Projjol** [comment]
hi @Shougo thanks a lot for looking into this. If you could take a look at the log below it would be great, I was hoping to making it work on vim8 before jumping the gun on neovim 😄 

> 2018-06-22 13:46:37,483 [INFO @ neovim_rpc_server.py:handle:88] 98035 - === socket opened ===
> 2018-06-22 13:46:37,483 [INFO @ neovim_rpc_server.py:handle:107] 98035 - received: b'[1,"neovim_rpc_setup"]\n'
> 2018-06-22 13:46:37,484 [INFO @ neovim_rpc_server.py:handle:123] 98035 - sending ["ex", "call neovim_rpc#_callback()"]
> 2018-06-22 13:46:37,487 [INFO @ neovim_rpc_server.py:process_pending_requests:328] 98035 - process_pending_requests

**Comment by Shougo** [comment]
You should create the issue it in vim-hug-neovim-rpc repository.
I cannot fix the problem.
