### ISSUE TITLE
How to register autozimu/LanguageClient-neovim to deoplete sources and customise  sorter and matcher pleasantly ? 

### ISSUE THREAD

**Issue by hackingcat** [Shougo/deoplete.nvim#785]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
I have resistered LanguageClient as a deoplete source .But the sorter and matcher of completion seems like unpleasant .How to customise  the sorter and matcher just like vscode behavior or another source ?

## Environment Information

 * deoplete version(SHA1):
latest
 * OS:
arch linux 
 * neovim/Vim `:version` output:
v0.2.2
 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1

  call deoplete#custom#var('buffer', 'require_same_filetype', v:false)    " otherbuffer complete
  call deoplete#custom#source('LanguageClient','mark', 'ℰ')
  call deoplete#custom#source('omni',          'mark', '⌾')
  call deoplete#custom#source('flow',          'mark', '⌁')
  call deoplete#custom#source('ternjs',        'mark', '⌁')
  call deoplete#custom#source('go',            'mark', '⌁')
  call deoplete#custom#source('jedi',          'mark', '⌁')
  call deoplete#custom#source('vim',           'mark', '⌁')
  call deoplete#custom#source('ultisnips',     'mark', '⌘')
  call deoplete#custom#source('around',        'mark', '↻')
  call deoplete#custom#source('buffer',        'mark', 'ℬ')
  call deoplete#custom#source('tmux-complete', 'mark', '⊶')
  call deoplete#custom#source('syntax',        'mark', '♯')
  call deoplete#custom#source('member',        'mark', '.')

  call deoplete#custom#source('LanguageClient', 'rank', 500)    " change the languageclient ranking
  call deoplete#custom#source('LanguageClient',
              \ 'min_pattern_length',
              \ 2)
  call deoplete#custom#source('LanguageClient', 'sorters', [])
  call deoplete#custom#source('ultisnips', 'rank', 1000)    " change the snippet ranking
  call deoplete#custom#option('ignore_sources', {'python': ['LanguageClient'],'javascript':['LanguageClient'],'javascript.jsx':['LanguageClient']})    " disable LC


" For Vim only
"set runtimepath+=~/path/to/nvim-yarp/
"set runtimepath+=~/path/to/vim-hug-neovim-rpc/
```

## The reproduce ways from neovim/Vim starting (Required!)

 1. foo
 2. bar
 3. baz

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
> I have resistered LanguageClient as a deoplete source .But the sorter and matcher of completion seems like unpleasant .How to customise the sorter and matcher just like vscode behavior or another source ?

I have read LanguageClient source's code.
It uses default matcher and sorter.
So 

```vim
 call deoplete#custom#source('LanguageClient', 'sorters', [])
```

It disables the default sorter(sorter_rank).

And

> How to customise the sorter and matcher just like vscode behavior or another source ?

I don't know VSCode's sort.
But the default is sorter_rank and same with another source.

You can create the new sorter.  You can choose them.
