### ISSUE TITLE
Can't delete completed text in INSERT mode

### ISSUE THREAD

**Issue by marlun** [Shougo/deoplete.nvim#8]
I've updated to the latest version (9afefb0b3a915286e783d7e3497bc7d1ec3da639) but if I create a function like this:

```php
<?php

$foo = "bar";
$foo|
```
The second $foo is autocompleted and if I try to remove it in INSERT mode with `BACKSPACE` it's not possible.

**Comment by Ninja3047** [comment]
Same issue with latest neovim, python-neovim, and latest deoplete. I also noticed this in previous versions. Also I am using Arch Linux, but I'm not sure if that makes a difference. This makes it pretty much unusable, hopefully a fix will come soon.

**Comment by khalidchawtany** [comment]
I think it is fixed. I had this problem and now it is gone :)

**Comment by Ninja3047** [comment]
Hm, seems to be working for me too now

**Comment by Numkil** [comment]
Might be necessary to do :UpdateRemotePlugins, not sure but this helped me a couply of times already

**Comment by Shougo** [comment]
I cannot reproduce it.

**Comment by marlun** [comment]
Well, It's not working for me. I've tried disabling all other plugins except deoplete.

**Comment by Shougo** [comment]
@marlun You should read CONTRIBUTING.md.  I cannot debug your configuration.

**Comment by Shougo** [comment]
@marlun Please update your neovim and deoplete.
And please execute `:UpdateRemotePlugins` and restart it.

**Comment by marlun** [comment]
It worked after doing all of that. Thought I had already done it but nevermind, thanks!

**Comment by Shougo** [comment]
OK
