### ISSUE TITLE
No completions after change in insert mode

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#800]
Given t.txt:

```
foo
foobar
```

And a minimal vimrc:
```
set runtimepath+=~/.vim/plugged/deoplete.nvim
let g:deoplete#enable_at_startup = 1
call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')

call deoplete#custom#source('buffer', 'is_debug_enabled', 1)
let g:deoplete#num_processes = 1

call deoplete#custom#option('sources', {
\ '_': ['buffer'],
\})
```

Starting neovim with `nvim -u vimrc.minimal t.txt`:

1. press `A` to append to the first line
2. it shows "foo" and "foobar" as completions
(3. You can repeat `<Esc>` and `a` now, it will keep repeating)
4. insert `n`
5. the pum will be closed, and the first line is `foon` now

deoplete is now stuck:

1. backspace will keep "foo", and not offer completions
2. leaving insert mode (`<esc>`) and using `a` again will also show no completions

You have to edit the "foo" itself to make it work again.

It looks like a problem in `Deoplete._merge_results`, but it is not clear to me.

**Comment by blueyed** [comment]
Tried to bisect, but had to skip a lot due to other issues (i.e. completion was not working at all):

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
700b7f81593ba0ea2a30e9874d66dee589b24337
ce51f0ce694fedda53a461a58ae2cb23353beda4
dedcb83719e0663d70e641f70859df8809915a63
389b6253527f31d2c6d680daad4caca778ac36fe
38b9a65253780b832881b8939d946ad76b886fca
ab9d23151bfafe84c5a313bb98b856435ef1f49b
b299e7d1f82ad7bda0c6fa35b6085d1abdc1acfc
4fbe097183f14e57c6e113770a545f5f341ad794
572fa2c4c38d2080258cade296997c3085aec4c6
f3663f112a9c41cce122d1e0146bfbd27a2a2928

**Comment by blueyed** [comment]
The first issue (backspace will keep "foo", and not offer completions) can be fixed in Vim/Neovim itself: https://github.com/vim/vim/pull/3193

**Comment by Shougo** [comment]
Fixed.

**Comment by Shougo** [comment]
> The first issue (backspace will keep "foo", and not offer completions) can be fixed in Vim/Neovim itself: vim/vim#3193

I don't understand the problem...

**Comment by blueyed** [comment]
> Fixed.

Thanks.  ´test_800` confirms this (https://github.com/Shougo/deoplete.nvim/pull/807/files#diff-e054dcb6b027ec2cc2fd7a4c6ecf5f5fR102), but needs a sleep for some reason - see the other test above.

https://github.com/vim/vim/pull/3193 is about handling completions via `complete()` more similar to other completions, i.e. using backspace does not close them.
I am not yet sure if this is good or bad for deoplete though - it might need some form of notification?  I do not remember if there are events then (since CompleteDone is not emitted for the closed pum).

**Comment by Shougo** [comment]
> but needs a sleep for some reason - see the other test above.

I think the completion is async and parallel.

> vim/vim#3193 is about handling completions via complete() more similar to other completions, i.e. using backspace does not close them.

For deoplete, the feature is not useful.
Because deoplete must re-generate candidates when you press `<BS>`.
So you need to remap `<BS>` key like this.

```vim
inoremap <expr><BS> deoplete#smart_close_popup()."\<C-h>"
```
