### ISSUE TITLE
Allow source to indicate that refreshing is needed

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#801]
Currently when changing `g:deoplete#sources#jedi#python_path` deoplete-jedi would use a new environment when `gather_candidates` is called, but this might not happen when previous completions are being used.

Is it feasible to provide some API to make this possible?

It could also be a Vimscript function, that could then be wrapped by a command/function like `DeopleteJediSetEnvironment`.

**Comment by Shougo** [comment]
Why it is needed?
I don't understand.
deoplete-jedi should check the variable.

**Comment by Shougo** [comment]
If it is need, deoplete-jedi should use deoplete#send_event().

**Comment by blueyed** [comment]
deoplete-jedi is not called (its `gather_candidates`).
It is a corner case until completions are refreshed (i.e. deoplete-jedi's `gather_candidates` is called again).

I do not know about the internals (prev completions) that much, it might be mainly due to bugs (e.g. https://github.com/Shougo/deoplete.nvim/issues/800) that it takes longer than expected.

> If it is need, deoplete-jedi should use deoplete#send_event().

Ok, good reference.
