### ISSUE TITLE
Travis: use neovim's integration builds / appimage ?

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#803]
https://github.com/neovim/bot-ci#generated-builds

or

https://github.com/neovim/neovim/wiki/Installing-Neovim#linux

Would be faster/better than the current script.

**Comment by Shougo** [comment]
Please send the PR for it.
I have not much time.

**Comment by blueyed** [comment]
What do you prefer?

**Comment by Shougo** [comment]
I don't know the difference.
