### ISSUE TITLE
Can deoplete control PUM position to prevent cut-off display?

### ISSUE THREAD

**Issue by mqudsi** [Shougo/deoplete.nvim#805]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
They say a picture is worth a thousand words:

![image](https://user-images.githubusercontent.com/606923/42656067-b4201928-85e3-11e8-98bd-727e38d659a3.png)

## Expected
Would it be possible for deoplete to manually position the completions popup menu such that it never starts past `window_width - pmu_width`? If not, I can file a upstream report with (neo)vim requesting that this functionality be added.

## Environment Information

 * deoplete version (SHA1): 751d6b3cb6b1a837ab8641482edc766ef3277027

 * OS: Linux

 * neovim/Vim `:version` output:
```
NVIM v0.3.0-1063-g51af911
Build type: Debug
LuaJIT 2.0.5
Compilation: /usr/local/bin/scc -fdiagnostics-color=always -g -Wconversion -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -I/home/mqudsi/random/neovim/build/config -I/home/mqudsi/random/neovim/src -I/home/mqudsi/random/neovim/.deps/usr/include -I/usr/include -I/home/mqudsi/random/neovim/build/src/nvim/auto -I/home/mqudsi/random/neovim/build/include
Compiled by mqudsi@ZBook

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only): n/a

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
n/a

## How to reproduce the problem from neovim/Vim startup (Required!)
n/a

## Generate a logfile if appropriate
n/a

## Screenshot (if possible)
see above

## Upload the log file
n/a

**Comment by Shougo** [comment]
You should use `pumwidth` option.
It is added in Vim 8.0.1491.

Note:  It is not included in neovim yet.

**Comment by mqudsi** [comment]
Thank you 🙏
