### ISSUE TITLE
Prevents CursorHoldI events from being fired

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#81]
Minimal vimrc:

```vim
set runtimepath+=~/.vim/neobundles/deoplete/

set updatetime=500
set cmdheight=2
let counter = 0
au CursorHoldI * echohl WarningMsg | let counter = counter + 1 | echom "CursorHoldI" counter | echohl None

let g:deoplete#enable_at_startup = 1
```

With this, the CursorHoldI will not appear after entering insert mode and usually is not triggered during typing.  But it can be triggered when moving the cursor in insert mode using the cursor keys (without any completion popup).

I've debugged this before, and IIRC it's triggered through the autocommand for `TextChangedI` which gets added in `deoplete#handlers#_init`: removing it will still not trigger `CursorHoldI` after `InsertEnter`, but when text is changed.

I cannot really believe it, but it looks like a Neovim bug and gets triggered through `pos = self.vim.current.window.cursor` in Python's `completion_begin`.

This would still trigger it, but using `pos = self.vim.current` would not?!

```diff
diff --git i/rplugin/python3/deoplete/__init__.py w/rplugin/python3/deoplete/__init__.py
index 7c7ca9c..256e7f5 100644
--- i/rplugin/python3/deoplete/__init__.py
+++ w/rplugin/python3/deoplete/__init__.py
@@ -43,7 +43,8 @@ def init_python(self):
 
     @neovim.rpc_export('completion_begin')
     def completion_begin(self, context):
-        pos = self.vim.current.window.cursor
+        pos = self.vim.current.window
+        return
         try:
             complete_position, candidates = self.deoplete.gather_candidates(
                 context)
```

NVIM v0.1.0-136-g538a57c (compiled Nov 28 2015 15:37:41)

**Comment by blueyed** [comment]
Seems to be a Neovim bug: https://github.com/neovim/neovim/issues/3757.

**Comment by Shougo** [comment]
OK.
