### ISSUE TITLE
How can I force the deoplete to use ensime first instead of languageClient-neovim.

### ISSUE THREAD

**Issue by steelbluelee** [Shougo/deoplete.nvim#813]
I'm using ensime + neovim + deoplete.
After I installed this LanguageClient-neovim + scala LanguageServer
ensime + deoplete doesn't work. I guess that
vim try to auto-complete using deoplete + LanguageClient-neovim first.
But Scala LanguageServer I'm using doesn't support auto completion.
How can I force the deoplete to use ensime first instead of languageClient-neovim?

**Comment by Shougo** [comment]
> How can I force the deoplete to use ensime first instead of languageClient-neovim?

You should disable LanguageClient-neovim source.

```vim
call deoplete#custom#option('ignore_sources', {'scala': ['LanguageClient']})
```

**Comment by steelbluelee** [comment]
Thank you.
