### ISSUE TITLE
Turkish undotted i (ı) not caught by `\k` pattern

### ISSUE THREAD

**Issue by alerque** [Shougo/deoplete.nvim#814]
# Problems summary

All my files are encoded in UTF-8, and my `keyword_patters` is the plugin default that includes `\k*`. This works as expected for most extended character sets, I am able to use deoplete while writing prose in several languages. However Turkish presents a problem. The undotted i (ı) character does not seem to get matched as a keyword character in spite of Neovim recognizing it as such.

I suspect Python needs to be told something special to behave and match what Neovim is already doing right internally.

## Expected

Words such as `kullanılmak` should be auto-completed based on the contents of the current buffer.

## Environment Information

 * deoplete version (SHA1): 0f19217 (but has existed for years)
 * OS: Gnu/Linux Archlinux
 * neovim/Vim `:version` output: NVIM v0.3.0

## Minimal init.vim

(No special setup required)

```vim
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
```

## Reproduce

1. Open a blank file
2. Type `kullanılmak` on a line
3. Go to the next line and start typing `kulla`

Note the suggested completion ends before the `ı` character.

![image](https://user-images.githubusercontent.com/173595/43034657-396cf84c-8ce9-11e8-8ee3-e8381b1216df.png)

Also note that searching in Neovim for `/ku\k*` highlights the entire word including the offending `ı` character.

**Comment by Shougo** [comment]
Unfortunately, I cannot test Turkish.

Please upload `'iskeyword'` option value.
And `echo deoplete#util#vimoption2python(&l:keyword)`.

**Comment by Shougo** [comment]
If you not upload the information, I will close the issue unfortunately.

**Comment by alerque** [comment]
You can actually test this without being a Turkish speaker, all you have to do is copy and paste the word I provided in the issue report (`kullanılmak`) into a new buffer, then type "kul" on a new line and see what you get for completions.

The offending character is `<ı> 305, U+0131 LATIN SMALL LETTER DOTLESS I`.

I am happy to provide whatever debugging information is useful, test anything, or even help fix it if I can figure out where the problem is. You don't have to be so aggressive.

```vim
:set iskeyword
iskeyword=@,48-57,_,192-255

:echo deoplete#util#vimoption2python(&l:keyword)
E113: Unknown option: keyword                                                                                                                                                                                                      
E116: Invalid arguments for function deoplete#util#vimoption2python                                                                                                                                                                
E15: Invalid expression: deoplete#util#vimoption2python(&l:keyword)
```

**Comment by Shougo** [comment]
`echo deoplete#util#vimoption2python(&l:keyword)`

It must be:

`echo deoplete#util#vimoption2python(&l:iskeyword)`

**Comment by Shougo** [comment]
I have  checked the character point.  It is 305.

> :set iskeyword
> iskeyword=@,48-57,_,192-255

OK.  It is not included in `iskeyword`.

So this is feature.

**Comment by Shougo** [comment]
Fixed.
