### ISSUE TITLE
How to config to use <TAB> key for completion

### ISSUE THREAD

**Issue by yi** [Shougo/deoplete.nvim#816]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Just updated to Vim 8 and switched from neocomplete to deoplete. 
I get used to  <TAB> key for completion, is there anyway we can config in deoplete?

## Expected

config to use <TAB> key for completion

**Comment by yi** [comment]
problem sorted:

```
" <TAB>: completion.
inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```

**Comment by h-michael** [comment]
my setting

```
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ deoplete#manual_complete()
```

**Comment by milipili** [comment]
It should be a simple option...

**Comment by Shougo** [comment]
Some plugin defines the mapping.  But the auto completion plugin should not define it.
Because, the best mapping depends on users configuration.

And deoplete is not plugin for beginners.

**Comment by avonmoll** [comment]
Thanks for the snippets. I have tried both and both work but only after re-`source`ing my .vimrc. I'm not sure why this is necessary. I do not map Tab for insert mode anywhere else in my settings.

**Comment by Shougo** [comment]
You should check the mapping.
```vim
:verbose imap <Tab>
```

I think other plugin overwrites your mapping.
