### ISSUE TITLE
no candidates from external sources when manual-completing after a space or blank lines.

### ISSUE THREAD

**Issue by tommasolaurenzi** [Shougo/deoplete.nvim#820]
# Problems summary

When triggering manual completion after a whitespace or in a blank line the completion menu is shown, but the candidates are only from the built-in lists (i.e. around, buffer, tags, etc) and the filetype-specific external source does not seem to be queried. 

## Expected

It would be expected that the popup menu would show candidates also from the filetype-specific external sources, i.e. neco, deoplete-jedi, LanguageClient, etc.

My configuration is ok, I have not encountered any other problems with external sources except they do not work when manual-completing on blank lines.

## Configuration

automatic completion is enabled but I have a custom mapping to trigger manual completion when needed.

**Comment by Shougo** [comment]
It depends on external sources.
You should report it in external sources issues.
Closing.
