### ISSUE TITLE
Autocompleting parameters

### ISSUE THREAD

**Issue by GoingFast** [Shougo/deoplete.nvim#821]
I searched around google for some time and couldnt find the answer for it. Can you autocomplete the parameters? Example with golang, fmt.Println and it autocompletes to fmt.Println(a ...interface{}), parameter gets selected like in a snippet and you can hop to it with tab. Is it possible?

**Comment by Shougo** [comment]
It is possible.  But  you need to install neosnippet.vim.
And you need to enable `g:neosnippet#enable_completed_snippet`.
