### ISSUE TITLE
Use deoplete.nvim error

### ISSUE THREAD

**Issue by Hello-Linux** [Shougo/deoplete.nvim#822]
# Problems summary
When I finished the installation, the configuration did not take effect

## Environment Information

 * deoplete version (SHA1):master branch

 * OS:centos 7.5

 * neovim/Vim `:version` output: I use vim8.1
VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug  3 2018 14:41:17)
Included patches: 1
Compiled by root@k8s.master.com
Huge version without GUI.  Features included (+) or not (-):
+acl               +farsi             +mouse_sgr         -tag_any_white
+arabic            +file_in_path      -mouse_sysmouse    -tcl
+autocmd           +find_in_path      +mouse_urxvt       +termguicolors
-autoservername    +float             +mouse_xterm       +terminal
-balloon_eval      +folding           +multi_byte        +terminfo
+balloon_eval_term -footer            +multi_lang        +termresponse
-browse            +fork()            -mzscheme          +textobjects
++builtin_terms    +gettext           +netbeans_intg     +timers
+byte_offset       -hangul_input      +num64             +title
+channel           +iconv             +packages          -toolbar
+cindent           +insert_expand     +path_extra        +user_commands
-clientserver      +job               +perl              +vertsplit
-clipboard         +jumplist          +persistent_undo   +virtualedit
+cmdline_compl     +keymap            +postscript        +visual
+cmdline_hist      +lambda            +printer           +visualextra
+cmdline_info      +langmap           +profile           +viminfo
+comments          +libcall           +python/dyn        +vreplace
+conceal           +linebreak         +python3/dyn       +wildignore
+cryptv            +lispindent        +quickfix          +wildmenu
+cscope            +listcmds          +reltime           +windows
+cursorbind        +localmap          +rightleft         +writebackup
+cursorshape       +lua               +ruby/dyn          -X11
+dialog_con        +menu              +scrollbind        -xfontset
+diff              +mksession         +signs             -xim
+digraphs          +modify_fname      +smartindent       -xpm
-dnd               +mouse             +startuptime       -xsmp
-ebcdic            -mouseshape        +statusline        -xterm_clipboard
+emacs_tags        +mouse_dec         -sun_workshop      -xterm_save
+eval              -mouse_gpm         +syntax            
+ex_extra          -mouse_jsbterm     +tag_binary        
+extra_search      +mouse_netterm     +tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
  fall-back for $VIM: "/usr/local/share/vim"
Compilation: gcc -std=gnu99 -c -I. -Iproto -DHAVE_CONFIG_H     -g -O2 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
inking: gcc -std=gnu99   -L. -Wl,-z,relro -fstack-protector -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE   -L/usr/local/lib -Wl,--as-needed -o vim        -lm -ltinfo -lnsl  -lselinux   -ldl  -L/usr/local/lib -llua -Wl,--enable-new-dtags -Wl,-rpath,/usr/lib64/perl5/CORE  -fstack-protector  -L/usr/lib64/perl5/CORE -lperl -lresolv -lnsl -ldl -lm -lcrypt -lutil -lpthread -lc        

" For Vim only
My config is

Plugin 'Shoug︎o/deoplete.nvim'                                                                                                                        
Plugin 'roxma/︎nvim-yarp'                                                                                                                             
Plugin 'rox︎ma/vim-hug-neovim-rpc'
let g:deoplete#en︎able_at_startup = 1

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

![error](https://user-images.githubusercontent.com/17851645/43884945-0dd3507c-9bea-11e8-8d98-9163990035e0.png)

**Comment by su8** [comment]
I get it too:

![](https://user-images.githubusercontent.com/29376083/44350288-3f169500-a49f-11e8-90f6-a778f28b66f2.png)

![](https://user-images.githubusercontent.com/29376083/44350287-3e7dfe80-a49f-11e8-92d2-6dd20f7b7c48.png)

**Comment by su8** [comment]
I'm not using neovim though, but pure vim/gvim, so it's not related to #673

**Comment by Shougo** [comment]
@su8 Have you read vim-hug-neovim-rpc requirements?
I think not.

https://github.com/roxma/vim-hug-neovim-rpc#requirements

**Comment by Shougo** [comment]
You need to install neovim module by pip3.
