### ISSUE TITLE
error on edit zsh file

### ISSUE THREAD

**Issue by sudavid4** [Shougo/deoplete.nvim#824]
First of all thanks for this amazing plugin, great work!!!
I've been working with version under commit db94ea05afbb36bf92ca0be268880439cc40b6ed
tried upgrading to commit dc86f96f4f9ccb4214f419646e42c4fbe3287ba3 and I'm getting this when I start editing a `.zsh` file
for now I just cheked out the commit that I've been using till now, it's been serving me well. 
<img width="1144" alt="screen shot 2018-08-12 at 11 37 48" src="https://user-images.githubusercontent.com/4605383/44000210-b3fb9004-9e24-11e8-8644-ae3d94a4860e.png">

**Comment by Shougo** [comment]
Please update deoplete-zsh to the latest version.
