### ISSUE TITLE
Add toggle function

### ISSUE THREAD

**Issue by midnio** [Shougo/deoplete.nvim#827]
Sometimes I'm using Neovim to edit files, sometimes as IDE. I want to make it always disabled when I want to use as an editor, when I want to use it as IDE I want to press `<leader>d` to enable it. Can you add the toggling function like `:DeopleteToggle`?

**Comment by Shougo** [comment]
Please use `call deoplete#toggle()`.

**Comment by midnio** [comment]
nnoremap <leader>e call deoplete#toggle() ?

**Comment by Shougo** [comment]
No.

`nnoremap <leader>e :call deoplete#toggle()<CR>`
