### ISSUE TITLE
Enabling deoplete later

### ISSUE THREAD

**Issue by midnio** [Shougo/deoplete.nvim#828]
`let g:deoplete#enable_at_startup = 0`
When I type this function and open neovim, it doesn't enable it, but when I want to toggle it later with `call deoplete#toggle()` but it doesn't toggle it.

The latest version of deoplete.

**Comment by Shougo** [comment]
Please don't ignore the issue template.
`deoplete#toggle()` does not work if you don't enable deoplete.

You should configure it.

```vim
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('auto_complete', v:false)
```

You can toggle deoplete by `call deoplete#toggle()`.

**Comment by midnio** [comment]
Any solutions?

**Comment by midnio** [comment]
I'll use YCM until this bug is solved.

**Comment by Shougo** [comment]
Fixed.  Please update deoplete.

**Comment by midnio** [comment]
Thank you so much!
