### ISSUE TITLE
"Enter" on exact(?) match dismisses popup-menu, but does not adds linebreak

### ISSUE THREAD

**Issue by blueyed** [Shougo/deoplete.nvim#83]
TEST CASE:
1. `nvim foo`
2. Insert `foobarbaz`
3. Press Enter
4. Insert `foobarbaz` again, a completion for it will be shown.
5. Press Enter

EXPECTED RESULT:
You are on line 3 now.

ACTUAL RESULT:
The pressing of Enter dismisses the completion menu.

This appears to be related to when there's an exact match.
(When this happened to me before, I've experimented with setting `completeopt+=noselect,noinsert` explicitly, but that does not seem to help now.)

Minimal vimrc:
```
set runtimepath+=~/.vim/neobundles/deoplete/
let g:deoplete#enable_at_startup = 1
```

**Comment by Shougo** [comment]
It is Vim's feature.
Please see `:help popupmenu-keys`

You should remap `<CR>` key.

```vim
" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return deoplete#mappings#smart_close_popup() . "\<CR>"
endfunction
```

**Comment by zchee** [comment]
@Shougo I was also troubled, Thank you for the information :)

**Comment by blueyed** [comment]
It does not seem to work as described though?!

I am not using the cursor keys or some other method to select the entry.

The 2nd state is:

> 2. A cursor key has been used to select another match.  The match was not
>    inserted then, only the entry in the popup menu is highlighted.

> The behavior of the <Enter> key depends on the state you are in:
> first state:	  Use the text as it is and insert a line break.
> second state:	  Insert the currently selected match.
> third state:	  Use the text as it is and insert a line break.
> 
> In other words: If you used the cursor keys to select another entry in the
> list of matches then the <Enter> key inserts that match.  If you typed
> something else then <Enter> inserts a line break.

**Comment by zchee** [comment]
@blueyed FYI, I do not understand completely your ideal behavior, but

```
inoremap <silent><expr><CR> pumvisible() ? deoplete#mappings#close_popup()."\<CR>" : "\<CR>"
```

It will be 
1. Insert first `foobarbaz` - does not use the completion
2. Enter - move next line
3. Insert second `foobarbaz` - but when insert `foob`, open `popupmenu`
4. Select `foobarbaz` in `popupmenu` use `<CR>`, will be inserted `foobarbaz` on buffer, and move next line

If you do not want to move to the next line after the selected word, remove `."\<CR>"`
```
inoremap <silent><expr><CR> pumvisible() ? deoplete#mappings#close_popup() : "\<CR>"
```

Use this setting sample screencast:
https://asciinema.org/a/30892

**Comment by blueyed** [comment]
@zchee 
Thanks. `deoplete#mappings#smart_close_popup()` works for me.

I was referring to @Shougo statement that this is a Vim feature.
It is not working as documented for me.

**Comment by Shougo** [comment]
@blueyed Yes, it is not well documented behavior.
But if you input "fo" (just the popup is generated), you can insert new line by `<CR>`.
But if you input "foobarbaz", it seems narrowing state.
It seems same with 2nd state.

> 2. A cursor key has been used to select another match.  The match was not
>   inserted then, only the entry in the popup menu is highlighted.

So, it is just close popup menu.  It is same behavior with Vim/neovim.  deoplete/neocomplete is just completion plugin.  I cannot fix it.

**Comment by blueyed** [comment]
Thanks for your explanation.

> A cursor key has been used to select another match.

That's not the case though, but it appears to behave like that.

**Comment by antoyo** [comment]
As said by @zchee, we should use `deoplete#mappings#close_popup()` instead of `deoplete#mappings#smart_close_popup()` if we want the completion to occur.

Could the FAQ be updated accordingly, please?

**Comment by Shougo** [comment]
Documentation updated.

**Comment by voyeg3r** [comment]
I have also 
`inoremap <expr> <TAB> pumvisible() ? "\<C-y>\<cr>" : "\<TAB>"`

along with 
`" <CR>: close popup and save indent.
inoremap <silent> <CR> <C-r>=<SID>my_cr_function()<CR>
function! s:my_cr_function()
  return deoplete#mappings#smart_close_popup() . "\<CR>"
endfunction
`
And now my Enter creates a new line
