### ISSUE TITLE
reference packages cannot be completed

### ISSUE THREAD

**Issue by Marlboro-go** [Shougo/deoplete.nvim#841]
The setting was made according to the solution，but my reference packages also cannot be completed,I reinstall my macos and neovim ,but the reference package complete also cannot use, These is Ok when I input fmt . ,the deoplete will prompt lot of method ，It's OK。but when i import package ,the method or variable which in the import package , the deoplete is not ok，It can't prompt these method ,variable and so on. I do not know if I have expressed clearly，you can see the pictures,this is my problem.
![wx20180907-184004](https://user-images.githubusercontent.com/41671631/45214614-783b6b80-b2cd-11e8-8434-234ef6c47622.png)

![qq20180907-175149](https://user-images.githubusercontent.com/41671631/45212583-d6fde680-b2c7-11e8-9494-604b7c6b1a07.png)

**Comment by Marlboro-go** [comment]
this is my log file

[log_py3_rplugin.zip](https://github.com/Shougo/deoplete.nvim/files/2360565/log_py3_rplugin.zip)

**Comment by Marlboro-go** [comment]
I used ycm and deoplete. I think the deoplete is very useful .but this problem ，But this question bothers me

**Comment by Shougo** [comment]
Please see the issue.
https://github.com/zchee/deoplete-go/issues/128

Closing.

```vim
let g:deoplete#sources#go#source_importer = 1
```

**Comment by Marlboro-go** [comment]
@Shougo It’s amazing that the problem has been solved when i  use PlugUpdate and go get -u github.com/mdempsky/gocode,I don’t know where the problem is, but fortunately it actually worked. I have not set that。
let g:deoplete#enable_at_startup = 1  
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
let g:deoplete#sources#go#use_cache = 1
let g:deoplete#sources#go#json_directory = '~/.cache/deoplete/go/'
![22](https://user-images.githubusercontent.com/41671631/45262770-ff185180-b44f-11e8-9db3-780917d3125e.png)

**Comment by Shougo** [comment]
>  It’s amazing that the problem has been solved when i use PlugUpdate and go get -u github.com/mdempsky/gocode,I don’t know where the problem is, but fortunately it actually worked. I have not set that

gocode may support it without the config.

**Comment by Marlboro-go** [comment]
@Shougo  Yes, I really appreciate your constant help. For a newcomer like me, a lot of words are translated through Google. I really like your deoplete.I am very passionate about Japanese anime. My wish is to travel to Japan.

**Comment by Shougo** [comment]
> For a newcomer like me, a lot of words are translated through Google. I really like your deoplete.I am very passionate about Japanese anime. My wish is to travel to Japan.

Oh, Google translate is very useful for me.
I have looked "最強の男"(the strongest man) in your screenshots.

**Comment by Marlboro-go** [comment]
@Shougo  yeah  it's a picture in  a anime which name ワンパンマン，

**Comment by Shougo** [comment]
I see.

**Comment by Marlboro-go** [comment]
@Shougo  I am sorry to bother you again.It doesn't work anymore。I added this setting`let g:deoplete#sources#go#source_importer = 1`， It work，But the deoplete is a lot slower。My colleague and I have the same Neomov configuration, but he can still complete the external package without adding this setting.Is this a problem with gocode or a problem with deoplete?

**Comment by Marlboro-go** [comment]
I see  problem of gocode。I really like vim too much, I don't want to use IDE again. It is similar to goland.

**Comment by Marlboro-go** [comment]
@Shougo  I set  `gocode set autobuild true` ,gocode is work and deoplete  very quickly. Another problem is that when I was using js, I didn't complete it. I need ctrl+x, ctrl+o, here is my minimum configuration
Plug 'ternjs/tern_for_vim'
Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern' }
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

let g:tern#command = ["tern"]
let g:tern#arguments = ["--persistent"]
let g:deoplete#sources#ternjs#tern_bin = '/usr/local/bin/tern'
let g:deoplete#sources#ternjs#timeout = 1
let g:deoplete#sources#ternjs#types = 1
let g:deoplete#sources#ternjs#depths = 1
let g:deoplete#sources#ternjs#docs = 1
let g:deoplete#sources#ternjs#filter = 0
let g:deoplete#sources#ternjs#case_insensitive = 1
let g:deoplete#sources#ternjs#guess = 0
let g:deoplete#sources#ternjs#sort = 0
let g:deoplete#sources#ternjs#expand_word_forward = 0
let g:deoplete#sources#ternjs#omit_object_prototype = 0
let g:deoplete#sources#ternjs#include_keywords = 1
let g:deoplete#sources#ternjs#in_literal = 0
let g:deoplete#sources#ternjs#filetypes = [
                \ 'jsx',
                \ 'javascript.jsx',
                \ 'vue',
                \ '...'
                \ ]

**Comment by Shougo** [comment]
It is not deoplete problem.
I think deoplete-ternjs's feature.
I have read the code.
deoplete-ternjs only complete when `\.|@|require` patterns.

**Comment by Shougo** [comment]
You can change the behavior by `deoplete#custom#source()` though.
