### ISSUE TITLE
Customize completion results?

### ISSUE THREAD

**Issue by gomezhyuuga** [Shougo/deoplete.nvim#842]
![screen shot 2018-09-07 at 6 20 19 pm](https://user-images.githubusercontent.com/1633839/45247158-58a34380-b2cb-11e8-9a8c-f6734991bba1.png)

Is it possible to customize the UI of the completion results? I tried to look at the source code without much luck. Any advice?

Best regards,
Fer

**Comment by Shougo** [comment]
You can use filter feature.
Please read deoplete documentation.
