### ISSUE TITLE
Autocomplete menu goes hover the other buffers

### ISSUE THREAD

**Issue by Mte90** [Shougo/deoplete.nvim#844]
# Problems summary
![screenshot_20180913_152532](https://user-images.githubusercontent.com/403283/45491321-c0450d00-b769-11e8-9373-41e2c13f0435.png)

## Expected
The popup don't cover the other section that show the function name complete.

## Environment Information

 * deoplete version (SHA1): last

 * OS: linux

 * neovim/Vim `:version` output: 0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

https://github.com/Mte90/My-Scripts/blob/master/vim/vimrc

I was thinking to change the size of the popup or move `pumvisible` to the top of the VIM ui to fix the issue.

**Comment by Shougo** [comment]
It is Vim/neovim's feature.
Completion plugin cannot change the behavior.
You can set `pumvisible` value.
