### ISSUE TITLE
Could it be possible to create a source like `ncm2_ultisnips`?

### ISSUE THREAD

**Issue by svanharmelen** [Shougo/deoplete.nvim#845]
# Problems summary

Since `deoplete` doesn't actively support anonymous dynamic snippets (like `neosnippet` does using `enable_completed_snippet`), I wondered if we could create a plugin like `ncm2_ultisnips`?

This plugin seems to glue together the `ncm2` and `UltiSnips` to make this work very nicely. So is there any way to add support for that directly into `deoplete` or by creating a dedicated plugin?

Thanks!

**Comment by Shougo** [comment]
> Since deoplete doesn't actively support anonymous dynamic snippets

Because, deoplete should not implement it.
It is depends on snippet plugin.  It should be implemented in snippet plugin like neosnippet.

**Comment by Shougo** [comment]
If you want to create it, you should use CompleteDone autocmd.
But parse candidate is needed...

**Comment by svanharmelen** [comment]
I know (and maybe even agree) that it should be implemented in the snippet plugin. But since some snippets authors seem to have a different opinion, this leaves us users stuck in between without a solution.

Guess that is why the `mcn2` plugin I referred to was created to solve that for any `ncm2` users. I'll have a look what I can do with the `CompleteDone` autocmd. Thanks for that pointer!

**Comment by Shougo** [comment]
> But since some snippets authors seem to have a different opinion, this leaves us users stuck in between without a solution.

I know.  I think UltiSnips author is busy.
