### ISSUE TITLE
Rust completion not working for user defined functions

### ISSUE THREAD

**Issue by SephVelut** [Shougo/deoplete.nvim#846]
```

health#LanguageClient#check
========================================================================
  - OK: binary found: /myhome/.vim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.120 183fbf5e1904aae92baabd809ec8589f251481f7

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release
    LuaJIT

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $TERM_PROGRAM='iTerm.app'
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: pbcopy

## Python 2 provider (optional)
  - INFO: pyenv was found, but $PYENV_ROOT is not set. `pyenv root` will be used. If you run into problems, try setting $PYENV_ROOT explicitly.
  - INFO: pyenv: /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv
  - INFO: pyenv root: /myhome/.pyenv
  - INFO: Using: g:python_host_prog = "/myhome/.virtualenvs/neovim2/bin/python"
  - INFO: Executable: /myhome/.virtualenvs/neovim2/bin/python
  - INFO: Python2 version: 2.7.15
  - INFO: python-neovim version: 0.2.6
  - OK: Latest python-neovim is installed: 0.2.6

## Python 3 provider (optional)
  - INFO: pyenv was found, but $PYENV_ROOT is not set. `pyenv root` will be used. If you run into problems, try setting $PYENV_ROOT explicitly.
  - INFO: pyenv: /usr/local/Cellar/pyenv/1.2.7/libexec/pyenv
  - INFO: pyenv root: /myhome/.pyenv
  - INFO: Using: g:python3_host_prog = "/myhome/.virtualenvs/neovim/bin/python3"
  - INFO: Executable: /myhome/.virtualenvs/neovim/bin/python3
  - INFO: Python3 version: 3.7.0
  - INFO: python3-neovim version: 0.2.6
  - OK: Latest python3-neovim is installed: 0.2.6

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
  - INFO: Host: /myhome/.rvm/gems/ruby-2.2.2/bin/neovim-ruby-host
  - OK: Latest "neovim" gem is installed: 0.7.1

## Node.js provider (optional)
  - INFO: Node.js: v10.9.0
  - INFO: Neovim node.js host: /usr/local/lib/node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn package is installed: 4.2.1
```
-----------------------------------

```
Plug 'racer-rust/vim-racer', { 'do': 'rustup toolchain add beta && rustup toolchain add stable && rustup component add rust-src && rustup update && cargo install racer', 'for': 'rust' }

Plug 'rust-lang/rust.vim'

Plug 'Shougo/deoplete.nvim', { 'do': ':silent UpdateRemotePlugins', 'branch': 'master' }
    \| Plug 'sebastianmarkow/deoplete-rust'

let g:deoplete#sources#rust#racer_binary='/myhome/.cargo/bin/racer'
let g:deoplete#sources#rust#rust_source_path='/myhome/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src'
let g:deoplete#enable_at_startup=1
let deoplete#tag#cache_limit_size = 5000000
call deoplete#custom#option('sources', {
		\ '_': ['buffer'],
		\ 'rs': ['buffer', 'rusty-tags.vi'],
		\})
```

--------------------------------------------------------------

Completion for the std library for Rust works fine. Problem is, non of my own defined functions show up. I do have universal ctags installed and have generated a project tags file in rusty-tags.vi (~500KB) using rusty-tags.

```
struct A;
impl A { fn foo(){} }

fn main() {
     let a: A = A{};
     a. <---- no completion
     std:: <---------- completion works fine
}
```

Completion for Rust works 100% with Clion's Rust plugin. Not sure if they're using some special language server or some special tag generation, but everything works. Maybe I'm doing something wrong?

**Comment by Shougo** [comment]
It is not deoplete problem.
It seems racer problem.

You should check racer can complete it.

**Comment by SephVelut** [comment]
But shouldn't deoplete read from the generated tags file? Got a DEBUG log file here https://gist.github.com/SephVelut/d2e61cc7459030ef4a77b86dbd04732a

**Comment by SephVelut** [comment]
With `set tags=tags;` or `set tags=rusty-tags.vi;' or `set tags=./tags;,tags;` set its still an issue. When I look in the tags file I see `foo src/main.rs /^    fn foo() {}$/;"   P   implementation:A`. Tried variations of different implementation for `foo()`; `foo(&self)`, `foo(self)`, `foo(&mut self)`.

`:echo taglist("foo")` = `[{'cmd': '/^    fn foo(&self) {}$/', 'static': 0, 'name': 'foo', 'kind': 'P', 'implementation': 'A', 'filename': 'src/main.rs'}]`

`:echo taglist("A")` = `[{'cmd': '/^impl A {$/', 'static': 0, 'name': 'A', 'kind': 'c', 'filename': 'src/main.rs'}, {'cmd': '/^struct A;$/', 'static': 0, 'name': 'A', 'kind': 's', 'filename': 'src/main.rs'}]`

--------------

Using rusty-tags tag file

`:echo taglist("foo")` = `[{'cmd': '/^    fn foo(&self) {}$/', 'static': 0, 'name': 'foo', 'kind': 'P', 'implementation': 'A', 'filename': 'src/main.rs'}, {'cmd': '/^    fn foo(&s
elf) {}$/', 'static': 0, 'name': 'foo', 'kind': 'P', 'implementation': 'A', 'filename': '/Users/seph/projects/concepts/syn-test/src/main.rs'}]`

Deoplete seems to recognize `foo` but the in the completion window its labled `[B]` which I assume is from the buffer.

**Comment by Shougo** [comment]
> Deoplete seems to recognize foo alone, without a.foo (which is what's important). 

Yes.  Because, tags does only record `foo` without `a.`.

> Not only that, but in the completion window its labeled [B] which I assume is from the buffer and not reading from a tag or racer.

`tag` is rank 100.  It is same with buffer rank.
It can be overwritten.  You can change the rank.

**Comment by Shougo** [comment]
```
:echo taglist("foo") = [{'cmd': '/^ fn foo(&self) {}$/', 'static': 0, 'name': 'foo', 'kind': 'P', 'implementation': 'A', 'filename': 'src/main.rs'}]

:echo taglist("A") = [{'cmd': '/^impl A {$/', 'static': 0, 'name': 'A', 'kind': 'c', 'filename': 'src/main.rs'}, {'cmd': '/^struct A;$/', 'static': 0, 'name': 'A', 'kind': 's', 'filename': 'src/main.rs'}]
```

taglist() does not recognize the context.
It is same with tag source.
tag completion is not magic.
So racer is needed.

**Comment by Shougo** [comment]
> Completion for Rust works 100% with Clion's Rust plugin.

Clion is JetBrain's proprietary IDE.  So it is better than racer.

**Comment by SephVelut** [comment]
Well `a.` is just method calls from a variable, but `a` is type annotated as `let a: A`. So now I thought the way deoplete worked is because ctags creates a dictionary of definitions, it can use foo's tag entry of`'implementation': 'A'` to resolve `a` to `A` and then `a.` to `A.foo`.

Tried to reduce/increase rank from 9999 to 1 `call deoplete#custom#source('buffer', 'rank', {rank})`. Either way doesn't look like deoplete uses any tags at all. Still getting `[B]`. Maybe that's where the problem is? Tagbar plugin sees tags with correct definitions

<img width="442" alt="screen shot 2018-09-17 at 4 53 01 am" src="https://user-images.githubusercontent.com/4496783/45613953-e6063680-ba35-11e8-9c9d-ef47867445ba.png">

**Comment by Shougo** [comment]
> Well a. is just method calls from a variable, but a is type annotated as let a: A. So now I thought the way deoplete worked is because ctags creates a dictionary of definitions, it can use foo's tag entry of'implementation': 'A' to resolve a to A and then a. to A.foo. I figures this would work with deoplete-rust, understanding the specifics of call hierarchy. What does deoplete-rust do then?

It is very very difficult.
Because, to implement it deoplete needs to recognize type information!

```rust
struct A;
impl A { fn foo(){} }

fn main() {
     let a: A = A{};
     a. <---- no completion
     std:: <---------- completion works fine
}
```

Please see your code.
Yes, foo is implementation of `A`.  But why deoplete can recognize `a` is `A` type?
It is not tags source work.

**Comment by Shougo** [comment]
> Tried to reduce/increase rank from 9999 to 1 call deoplete#custom#source('buffer', 'rank', {rank}). Either way doesn't look like deoplete uses any tags at all. Still getting [B] for just foo without a.. Maybe that's where the problem is? Tagbar plugin sees tags with correct definitions

Really?  Please upload the tags file.
I will try it later.

**Comment by Shougo** [comment]
I don't want to implement the feature your desired.  I have labeled `won't fix` tag.

**Comment by SephVelut** [comment]
`call deoplete#custom#source('tag', 'rank', 999)`

Got `foo` alone to show up as `[T]` but no bueno on the `a.`. Is it worth me implementing type resolution for deoplete-rust, even if its a shim? Is this feature desired at all?

**Comment by Shougo** [comment]
I think to fix racer is better.
