### ISSUE TITLE
neocompleteのフォルダを削除するとdeopleteが動かなくなる

### ISSUE THREAD

**Issue by yoshinaga-hiroyuki** [Shougo/deoplete.nvim#848]
# お礼
[neosnippet.vim の件](https://github.com/Shougo/neosnippet.vim/issues/442)
[context_filetype.vim の件](https://github.com/Shougo/context_filetype.vim/issues/37)
ではお世話になりました

この度は Twitter のつぶやきにもお返事頂きありがとうございます

最初は neosnippet.vim との組み合わせかと思っていたのですが、deoplete.nvim 単独の問題ととわかったので、こちらに質問を投稿させてもらいます
# 現在の状況
まず現在、後術する環境でパス名の補完など vim 標準の機能について deoplete は問題なく動いています
# 問題点
## 問題の前提
では何が問題なのか? ですが、前提として導入しているプラグインは後術の通りで、dein.toml の neocomplete についての記述はコメントアウトしているものの、ファイルは
$HOME/.vim/bundle/repos/github.com/Shougo/neocomplete
にそのまま残っています
## 実際の問題点というか疑問点

1. この上記 neocomplete のフォルダを削除 (移動) すると、deoplete が全く動かなくなる (他の場所にも同盟のフォるだはあるが、もちろん手を付けない)
2. 次に一旦動かなくなると、neocomplete のフォルダを元の位置に戻しても動かない
3. 動かない状態で dein.toml の
> \# [[plugins]]
> \# repo = 'Shougo/neocomplete'

　をコメントを無くして、vim を起動し直しなおすと deoplete が動くようになる

4. この時 neocomplete の動作に最低限必要な
> \# 	" let g:neocomplete#enable_at_startup = 1

　といった記述もコメントアウトのままでも問題なく動くようになります

5. そして一旦 deoplete が動くように成れば、次のようにコメントアウトし直しても正常に動作するままです
> \# [[plugins]]
> \# repo = 'Shougo/neocomplete'

3\~5に関しては、キャッシュ
$HOME/.vim/bundle/.cache
に残っているせいかも知れませんが、どうやって確認すればよいのか解りません

# 環境
## vimrc
`$ grep -vh "^\s*\"" $HOME/.vim/vimrc`
> if has('vim_starting')
>     if &compatible
> 		set nocompatible                           "viとの互換性をとらない
> 	endif
> 	let s:cache_home = empty($XDG_CACHE_HOME) ? expand('\~/.vim') : $XDG_CACHE_HOME
> 	let s:dein_dir = s:cache_home . '/bundle'
> 	let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'
> 	if !isdirectory(s:dein_repo_dir)
> 		call system('git clone https://github.com/Shougo/dein.vim ' . shellescape(s:dein_repo_dir))
> 	endif
> 	set runtimepath+=\~/.vim/bundle/repos/github.com/Shougo/dein.vim
> 	if dein#load_state(s:dein_dir)
> 		call dein#begin(s:dein_dir)
> 		let g:rc_dir = expand('\~/.vim/rc')
> 		let s:toml = g:rc_dir . '/dein.toml'
> 		let s:lazy_toml = g:rc_dir . '/dein_lazy.toml'
> 		call dein#load_toml(s:toml, {'lazy': 0})
> 		call dein#load_toml(s:lazy_toml, {'lazy': 1})
> 		call dein#end()
> 		call dein#save_state()
> 		if dein#check_install()
> 			call dein#install()
> 		endif
> 	endif
> endif
> filetype plugin indent on

## 導入しているプラグイン
`$ grep -vh "^#" $HOME/.vim/rc/dein*.toml | grep -v "^\s*\""`

> [[plugins]]
> repo = 'Shougo/dein.vim'
> [[plugins]]
> repo = 'Shougo/vimproc.vim'
> build = 'make'
> [[plugins]]
> repo = 'roxma/nvim-yarp'                      # NeoVim でない時に deoplete 必要
> [[plugins]]
> repo = 'roxma/vim-hug-neovim-rpc'             # NeoVim でない時に deoplete 必要
> [[plugins]]
> repo = 'Shougo/deoplete.nvim'                 #補完
> depends = [ 'roxma/nvim-yarp', 'roxma/vim-hug-neovim-rpc' ] # NeoVim でない時に必要
> on_i = 1
> hook_source = '''
> 	let g:deoplete#enable_at_startup = 1
> \'''

## OS や Vim の環境については、
`$ lsb_release -a`
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.1 LTS
> Release:	18.04
> Codename:	bionic

`$ uname -a`
> Linux xxxxx 4.15.0-34-generic #37-Ubuntu SMP Mon Aug 27 15:21:48 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

`$ vim --version`

> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
> 適用済パッチ: 1-1453
> Modified by pkg-vim-maintainers@lists.alioth.debian.org
> Compiled by pkg-vim-maintainers@lists.alioth.debian.org
> Huge 版 with GTK2 GUI.  機能の一覧 有効(+)/無効(-)
> <中略>
> ++builtin_terms    +gettext           +netbeans_intg     +timers
> <中略>
> +conceal           +linebreak         +python3           +wildignore
> <後略>

## Python の neovim
Ubuntu のパッケージは古かったので、pip3 で入れ直して、
`:put=system('pip3 show neovim')`
> Name: neovim
> Version: 0.2.6
> Summary: Python client to neovim
> Home-page: http://github.com/neovim/python-client
> Author: Thiago de Arruda
> Author-email: tpadilha84@gmail.com
> License: Apache
> Location: /usr/local/lib/python3.6/dist-packages
> Requires: greenlet, msgpack

# スクリーンショット
## 上記環境で動いている時
![screenshot from 2018-09-23 23-09-00](https://user-images.githubusercontent.com/24851657/45928993-b059d400-bf86-11e8-9f46-b36a19094b44.png)
動いていない時は、この補完候補が全く現れません
## neocomplete と deoplete のどちらが動いているかの確認方法
他に方法分からないので、次のneosnippetの補完候補の表示方法が違う ([ns]と[nsnip]) のを使って確認
![neocomplete](https://user-images.githubusercontent.com/24851657/45929014-fd3daa80-bf86-11e8-8b97-02d8ada3d320.png)
![deoplete](https://user-images.githubusercontent.com/24851657/45929017-00d13180-bf87-11e8-9c0f-cd68b9a745d2.png)

**Comment by yoshinaga-hiroyuki** [comment]
上の投稿で、現状認識に間違いが有りました
neocompleteフォルダの有無は関係なさそうです
# 発生状態の訂正
上記設定ですと、
$HOME/.vim/bundle/
に

- cache_gvim
- cache_vim
- state_gvim.vim
- state_vim.vim

といったファイルが作られますが、

- vim 用のそれが有ると vim
- Gvim 用のそれがあると Gvim

で deoplete が動作しなくなります

私の環境では dein.vim との組み合わせで発生するようなので、その辺りも含めてもう少しきちんと調べてみます

一度 vim 用のそれを削除して vim を、Gvim 用のそれを削除して Gvim を起動すれば動きますが、再びそれぞれのファイルが作成されるので、次の起動では動かなくなります
# 間違いが生じた理由
すぐに環境を戻せる、アンドゥ可能なように

- 設定ファイルはGvimで複数のタブで開く
- deopleteの動作確認は別プロセスとなるvimで確認

をしていたことで、問題が起きる条件を間違えていたようです

**Comment by Shougo** [comment]
中身見ましたが、多分依存関係の定義がおかしいためだとおもいます。
以下でなければいけません。

```
[[plugins]]
repo = 'Shougo/deoplete.nvim' #補完
depends = [ 'nvim-yarp', 'vim-hug-neovim-rpc' ]
on_i = 1
hook_source = '''
let g:deoplete#enable_at_startup = 1
'''
```

dein.vim は neobundle とは微妙に仕様が異なります。
dein.vim の正しい書き方を調べて記述しましょう。

補完が出なかったのは、おそらく依存プラグインがちゃんとロードできていないのでは
ないでしょうか。

> 導入しているプラグイン

この出力ではどのプラグインが lazy になっているのかさっぱり分かりません。


> vim 用のそれが有ると vim
> Gvim 用のそれがあると Gvim
> で deoplete が動作しなくなります

プラグインのロード設定がおかしい状態でキャッシュを保存したんではないですかね。

動作がおかしい状態で、runtimepath に deoplete はありますか？
`set runtimepath?`
依存プラグインはロードされていますか？
確認してください。

依存プラグインが正しくロードされずにエラーが出ているんではないかと思っています。

> neocomplete と deoplete のどちらが動いているかの確認方法

> 他に方法分からないので、次のneosnippetの補完候補の表示方法が違う ([ns]と[nsnip]) のを使って確認

あと、細かいことですが neosnippet を入れて確認しているはずなのに最小構成に
neosnippet が入っていません。
矛盾があると本当にそれで確認したのか疑わないといけません。

**Comment by yoshinaga-hiroyuki** [comment]
依存関係の書き方が未だよく解りませんが、deopleteの読み込みをdein.tomlからdein_lazy.tomlに移動したら、取り敢えず問題が起きなくなりました
合わせて[ HTMLファイル内のstyle属性でCSSの補完が出来ない](https://github.com/Shougo/context_filetype.vim/issues/37)も解決しました
どちらも依存関係・読み込み順序が問題だったんですね
色々とありがとうございました
