### ISSUE TITLE
Default g:deoplete#enable_smart_case value does not refer to a infercase of user settings

### ISSUE THREAD

**Issue by zchee** [Shougo/deoplete.nvim#85]
In `:help g:deoplete#enable_smart_case` of the doc, The default value is described a `infercase`.
https://github.com/Shougo/deoplete.nvim/blob/061f78bb29ec84eb243ae3e56154cdd729b6edc6/doc/deoplete.txt#L126

but, Actual source file section refers to an `ignorecase` of user setting.
https://github.com/Shougo/deoplete.nvim/blob/061f78bb29ec84eb243ae3e56154cdd729b6edc6/autoload/deoplete/init.vim#L89-L90

I do not know whether that's your recommendation, Which is correct?

**Comment by Shougo** [comment]
Fixed.
