### ISSUE TITLE
Addition of a DeopleteInfo/DeopleteDebug command to help diagnose issues

### ISSUE THREAD

**Issue by teto** [Shougo/deoplete.nvim#851]
# Problems summary
I've been trying to debug an issue with deoplete-notmuch https://github.com/paretje/deoplete-notmuch/issues/1 . 
This is my first time diving into vim/deoplete completion system. It seems that there are many ways to trigger the completion, and that rules are per filetype (which is great). 
In order to debug these scenarios with many variables, Neomake  provides a valuable :NeomakeInfo command that displays the configuration for the current filetype.
I believe a similar :DeopleteInfo could be a nice addition to deoplete and would complete the checkhealth script (that should remain minimal).
It could display the different sources available for the filetype and per-source keyword patterns etc.

**Comment by Shougo** [comment]
I think it should be implemented by debug log.

**Comment by Shougo** [comment]
I have added the debug logs for  it.

**Comment by teto** [comment]
thanks !
