### ISSUE TITLE
TAB can't switch between the items in the list

### ISSUE THREAD

**Issue by cslxiao** [Shougo/deoplete.nvim#853]
After installing the plugin in vim8, I can get the popup list. But I cannot switch between the item with TAB key, only the direction keys works.  Pressing TAB still get 4 blanks. 
Thanks in advance.

**Comment by Shougo** [comment]
```vim
inoremap <silent><expr> <TAB> pumvisible() ? "\<C-n>" :
\ <SID>check_back_space() ? "\<TAB>" :
\ deoplete#mappings#manual_complete()
function! s:check_back_space() abort "{{{
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~ '\s'
endfunction"}}}
```

Please read the documentation.

**Comment by t184256** [comment]
People of the future: it's just `deoplete#manual_complete()` now.
