### ISSUE TITLE
C++ completion

### ISSUE THREAD

**Issue by kariya2** [Shougo/deoplete.nvim#856]
Hey, just had a usage question. Not sure if this is the right place to ask this so please feel free to point me elsewhere or close this issue if this is inappropriate. I'm working on a very massive c++ repository and I'm looking for a powerful automomplete option. YCM really slowed my system down to an unusable level and so I had to remove it. I read the FAQ and it said I should install c++ deoplete plugin for omni completion. I was just wondering how that was different from the inbuilt autocomplete that deoplete offers and what the recommended path is. Again very sorry for the long post but it would really be very helpful for me to have these questions answered :)

**Comment by kariya2** [comment]
As a follow up I was wondering if it was possible for the function header and description to show up in a buffer when it is autocompleted like it does in YCM

**Comment by stsewd** [comment]
I think you need https://github.com/tweekmonster/deoplete-clang2

**Comment by kariya2** [comment]
I installed that, still not able to get good completion on enums or the feature I mentioned above. For some reason whenver I hit tab after a scope resolution operator, it ends up adding the name of the enum at the end of it

**Comment by Shougo** [comment]
I don't recommend for you to use deoplete in huge repository.
You should use IDE instead.
LanguageClient-neovim + cpp language server may work though.
