### ISSUE TITLE
Multiline Completion items from Language Server

### ISSUE THREAD

**Issue by meck** [Shougo/deoplete.nvim#863]
# Problems summary
I run Deoplete with Language Client Neovim and a Haskell language server. The completion items  passed from the server contains multiline items. The completion menu renders these as ```^@```
This is [expected](https://github.com/vim/vim/issues/2505) but doesnt look good:
<img width="1027" alt="skarmavbild 2018-10-24 kl 19 16 03" src="https://user-images.githubusercontent.com/762115/47449156-41101380-d7c2-11e8-8244-b9fa06437687.png">

For my use case it would be good to replace the /n with spaces, but I don't know if that would have adverse effect for other sources?

It could be argued that it should be done in [LanguageClient-neovim](https://github.com/autozimu/LanguageClient-neovim) instead? [Matching issue](https://github.com/autozimu/LanguageClient-neovim/issues/638)

## Environment Information

 * deoplete version (SHA1): HEAD

 * OS: macOS

**Comment by Shougo** [comment]
It should be done on LanguageClient-neovim side.
