### ISSUE TITLE
 How to set Enter does not wrap

### ISSUE THREAD

**Issue by MartiniGo** [Shougo/deoplete.nvim#867]
Hi Shougo，I am sorry to bother you again.I am not fully aware of the use of github and some etiquette. I am sorry.I have always used the `up` and `down` filter to complete the list, and then confirmed by `Enter`, it is normal, but I found that my hand will leave the main keypad, so I used `ctrl n `and `ctrl p` to filter the completion list.When I confirm the selected completion column by pressing Enter, it will wrap, and how to set it will not change the line after the carriage return.  
my min init.vim  
```
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }```  
Plug 'zchee/deoplete-go', { 'do': 'make'}  
Plug 'zchee/deoplete-jedi'
" neocomplete like
set completeopt +=noinsert
" deoplete.nvim recommend
set completeopt +=noselect
set completeopt =menu,preview
let g:deoplete#enable_at_startup = 1
" deoplete-go settings
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
"let g:deoplete#sources#go#source_importer = 1
let g:deoplete#sources#go#use_cache = 1
let g:deoplete#sources#go#json_directory = '~/.cache/deoplete/go/
```
![qq20181030-165611-hd 2018-10-30 16_58_17](https://user-images.githubusercontent.com/41671631/47708580-5628ee80-dc69-11e8-9e68-d0947b9cced4.gif)

**Comment by Shougo** [comment]
You should check your CR mapping. 
The default CR behavior does not wrap line.
I think you have overwritten it.

**Comment by Shougo** [comment]
It is not deoplete issue.  I will close it later.

**Comment by MartiniGo** [comment]
> Hm. It seems default behavior. It is reproduce-able without deoplete.

I am so sorry ! you know  i am a new vimer. emm  terrible sorry, I also did this remapping  
`autocmd VimEnter * inoremap <expr> <cr> ((pumvisible()) ? (deoplete#close_popup()) : ("\<cr>"))`
It's work ok

**Comment by Shougo** [comment]
Yes.  It is right.
