### ISSUE TITLE
Source that refreshes on every keystroke

### ISSUE THREAD

**Issue by tbodt** [Shougo/deoplete.nvim#869]
I'm writing a source that needs to refresh on every keystroke, since it does its own matching and filtering (https://tabnine.com). So what I want is an option on the source that's like refresh_always, but only applies to this source. is_volatile didn't make much of a difference. Is this possible?

**Comment by Shougo** [comment]
It is not possible.

**Comment by Shougo** [comment]
I have tested deoplete-tabnine.  It seems works.
And refresh_always is default.
What is the problem?
Please provide more information.

**Comment by Shougo** [comment]
I will review deoplete-tabnine's implementation later.
Please wait.

**Comment by tbodt** [comment]
It's possible the issue is just that I'm using an old version of deoplete. I'll try updating.

**Comment by Shougo** [comment]
OK.
