### ISSUE TITLE
completion of files ignores current pwd

### ISSUE THREAD

**Issue by PonderingGrower** [Shougo/deoplete.nvim#87]
Hi Shougo!

I'm really liking how your plugin is shaping up. I just found a weird behaviour in it. Deoplete seems to ignore the current `pwd` when giving suggstions for files and directories.

Steps to reproduce:

1. Start `nvim`, for example in `~/`.
2. Change directory, for example: `:cd .config/nvim`
3. Check current directory: `:pwd` - Get `/home/USER/.config/nvim`
4. Start insert mode and begin typing `./` to see the suggestions.
5. See suggestions from `~/` rather than from `~/.config/nvim`.

Same thing happens if you use `set autochdir` and edit a file in a different location.

Neovim version:
```
NVIM v0.1.0-39-g3b61598 (compiled Nov 10 2015 23:19:50)
Commit: 3b615980c814eff3fa284dd07b61fbf50885f4ab
Build type: Debug
Compilation: /usr/bin/cc -Wconversion -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERAT
ED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/build/build/config -I/tmp/build/src -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include/luajit-2.0 -I/tmp/build
/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/tmp/build/.deps/usr/include -I/usr/include -I/tmp/build/build/src/nvim/auto -I/tmp/build/build/include
Compiled by root@be8abe028e13
```

Neovim: `b832f20938071e7aa72a223ceb60804e635475fc`

**Comment by Shougo** [comment]
Reproduced.  I need to refactor the file source.
Please wait.

**Comment by PonderingGrower** [comment]
It's cool bro, no rush. I really appreciate all the effort you put into this.

**Comment by Shougo** [comment]
Implemented.

**Comment by PonderingGrower** [comment]
Thank you Shougo, it works perfectly. If we ever meet I owe you a beverage of your choice.
