### ISSUE TITLE
how to stop deoplete kill all child processes and then restart

### ISSUE THREAD

**Issue by liushapku** [Shougo/deoplete.nvim#871]
I don't know whether this is the correct place to ask the question in the title.

My deoplete seems to have got messed up. After vim (and deoplete) is running for hours, I saw more than 30 deoplete processes launched, although I have set the `num_processes` to be 4.

The number of processes at the time vim started was only 4. I don't know when did it increased yet. Perhaps some source crashed and the deoplete restarted it.

Is there a way to terminate all the deoplete processes and then restart deoplete?

**Comment by Shougo** [comment]
It is not deoplete issue.
Deoplete doesn't increase the processes.
You should use pgrep command to kill processes.

**Comment by Shougo** [comment]
I think you have launched several Vim instances.

**Comment by liushapku** [comment]
I only have one vim instance. I still need some time to figure out what happened. But is there a way to stop deoplete from within vim or to restart it afresh? I only found a `deoplete#disable` and it does not affect the process.

**Comment by Shougo** [comment]
I have checked the code, but it is correct.
I don't work for the problem without reproduce instruction.

**Comment by Shougo** [comment]
deoplete doesn't have restart process feature.
So your assume is incorrect.

**Comment by liushapku** [comment]
got it. Thank you very much. I restarted.
