### ISSUE TITLE
How to get names of sources?

### ISSUE THREAD

**Issue by theFool32** [Shougo/deoplete.nvim#873]
I wonder whether there exists any way to get the names of active and inactive sources.
And any way to toggle specific source quickly for current buffer.
Thanks a lot.

**Comment by Shougo** [comment]
> I wonder whether there exists any way to get the names of active and inactive sources.

Nothing.

> And any way to toggle specific source quickly for current buffer.

You can use `deoplete#custom#buffer_option()`.
