### ISSUE TITLE
About keyword_patterns removal

### ISSUE THREAD

**Issue by petobens** [Shougo/deoplete.nvim#875]
Hi, I noticed that in #858 you remove the `keyword_patterns` source attribute. In my vimrc I have the following config:
```vim
call deoplete#custom#source('dictionary', 'min_pattern_length', 1)
call deoplete#custom#source('dictionary', 'rank', 1000)
call deoplete#custom#source('dictionary', 'keyword_patterns', {
            \ 'tex' : '\\?[a-zA-Z_]\w*',
\})
```
that used to allow me to complete `tex` files from dictionary source whenever I input `\\`. With the recent changes this functionality is lost. Can I somehow recover it? (I thought it was a nice feature to have).
Thanks in advance!

**Comment by Shougo** [comment]
Unfortunately, I don't want to add the feature.  Sorry.

**Comment by Shougo** [comment]
You should use `deoplete-options-keyword_patterns` instead.

**Comment by petobens** [comment]
> You should use deoplete-options-keyword_patterns instead.
But this is for all sources right? I only want the regex to apply to the dictionary source...

**Comment by Shougo** [comment]
Yes.  The feature is removed.
I want to simplify the source implementation.

**Comment by petobens** [comment]
Ok! Thanks
