### ISSUE TITLE
How to limit completion window size?

### ISSUE THREAD

**Issue by latiaoxia** [Shougo/deoplete.nvim#878]
![default](https://user-images.githubusercontent.com/9819120/48877426-15725e80-ee3e-11e8-9595-267712fd8919.JPG)

Sometimes the completion candidates are too much, so how to limit the completion window size?

**Comment by Shougo** [comment]
pumheight option.

**Comment by latiaoxia** [comment]
I have tried `call deoplete#custom#option('pumheight', 5)`, but it don't seem to work.
And I grep the deoplete source code, there is no `pumheight ` option.
