### ISSUE TITLE
keyword_patterns is ignored

### ISSUE THREAD

**Issue by pwntester** [Shougo/deoplete.nvim#881]
Hi @Shougo 

Im moving a custom deoplete source to a language server and then using the neovim-languageClient plugin to pass the completion candidates to deoplete.

This seems to work just fine. The only problem I got is that in my deoplete source I was able to trigger a completion request with the `[` character. I check LanguageClient source and it seems like it is calling a function to get the completion start:

https://github.com/autozimu/LanguageClient-neovim/blob/next/rplugin/python3/deoplete/sources/LanguageClientSource.py#L21

which is implemented here:

https://github.com/autozimu/LanguageClient-neovim/blob/next/autoload/LanguageClient.vim#L918

```
function! LanguageClient#get_complete_start(input) abort
    " echomsg a:input
    return match(a:input, '\k*$')
endfunction
```

If I understood it correctly `\k` is expanded to `isKeyword` and therefore, I should be able to control it using:

```
call deoplete#custom#option('keyword_patterns', {
    \ 'myfiletype': '\S+',
    \})
```

Which should consider a keyword any sequence of non-whitespaces, including `[`.
This is not working though, any idea why?

CC @autozimu
Thanks!

**Comment by Shougo** [comment]
`keyword_patterns` works only if the source does not override `get_complete_pattern()`.
But the source already override it.  So `keyword_patterns` does not work.

**Comment by Shougo** [comment]
You should custom `input_pattern` like this.

```vim
call deoplete#custom#source('LanguageClient', 'input_pattern', '\S+$')
```

**Comment by pwntester** [comment]
Thanks!
