### ISSUE TITLE
Bring back support for nvim 0.2.x?

### ISSUE THREAD

**Issue by ws-ono** [Shougo/deoplete.nvim#882]
# Problems summary

deoplete now only supports nvim above 0.3 but since Ubuntu 18.04 (LTS) only has nvim 0.2.2, deoplete no longer works with versions above somewhere around 3170a3d823510a2f50969912d5711336cf10895e with stock nvim Ubuntu package.

Is it hard to keep compatibility with 0.2.x of nvim?

## Environment Information

 * deoplete version (SHA1): acae3732524443ecb53af2f4c8078af47381a180

 * OS: Ubuntu 18.04

 * neovim/Vim `:version` output:

```
NVIM v0.2.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-_mzR4z/neovim-0.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=2 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -I/build/neovim-_mzR4z/neovim-0.2.2/build/config -I/build/neovim-_mzR4z/neovim-0.2.2/src -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/usr/include -I/build/neovim-_mzR4z/neovim-0.2.2/build/src/nvim/auto -I/build/neovim-_mzR4z/neovim-0.2.2/build/include
Compiled by pkg-vim-maintainers@lists.alioth.debian.org

Features: +acl +iconv +jemalloc +tui
```

**Comment by Shougo** [comment]
Sorry.  I don't want to support the old version of neovim.
You can build the latest neovim manually.

**Comment by roxma** [comment]
Neovim has appimage releases: https://github.com/neovim/neovim/releases

You could try that on ubuntu if you need the latest version. It works just out of box.

**Comment by ws-ono** [comment]
Manual install is not really handy as you have to manually keep track of security updates but thanks for responding anyways.

**Comment by ws-ono** [comment]
Manual install is not really handy as you have to manually keep track of security updates but thanks for responding anyways.
