### ISSUE TITLE
tmux環境下で画面が真っ黒になる

### ISSUE THREAD

**Issue by fr0077** [Shougo/deoplete.nvim#883]
# Problems summary
tmuxを起動し、その中でdeopleteを有効にしたVimを起動すると画面が真っ暗で何も応答しなくなる。
その状態でCtrl+Cを2回押すと普通に使えるようになる。

## Environment Information
OS X付属のTerminal、iTerm2 Build 3.2.6の両方で発生
tmux 2.8

 * deoplete version (SHA1):
commit aa43a5f03b7b995841b416c40e8bbc8bcbf9b1a2 (grafted, HEAD -> master, origin/master, origin/HEAD)

 * OS:
macOS mojave 10.14.1（18B75）

 * neovim/Vim `:version` output:
NVIM v0.3.1
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOUR
CE=1 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplici
t-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -
DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/build/config -I/
tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/src -I/usr/local/include -I/usr/local/opt/gettext/include -I/Applicatio
ns/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include -I/tmp/neovim-201
81019-50893-1j0fv9i/neovim-0.3.1/build/src/nvim/auto -I/tmp/neovim-20181019-50893-1j0fv9i/neovim-0.3.1/build/include
Compiled by brew@Mojave-2.local

Features: +acl +iconv +jemalloc +tui

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
```vim
" Your minimal init.vim/vimrc
call plug#begin()
Plug 'Shougo/deoplete.nvim'
call plug#end()
let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

1. tmuxを起動する
2. nvimを起動する
3.  カーソルも出ず、操作が何もできない。tmuxのステータスバーだけ出ている状態。Ctrl-Cを二度押すとVimが表示され操作ができるようになる。
4. deopleteを読み込まなければなんの問題もなく起動する。
5. let g:deoplete#enable_at_startup = 1を書かないと、問題なく起動するが、:call deoplete#enable()を呼んだ時点で問題が発生する。

**Comment by Shougo** [comment]
I have tested it in Linux, but I don't reproduce the problem.
It is really deoplete problem?

**Comment by Shougo** [comment]
deoplete seems hanged.  You can investigate the problem more.
You should enable debug flag.

```
   8. Please enable debug mode from command line and upload the log file. >

       $ export NVIM_PYTHON_LOG_FILE=/tmp/log
       $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
       $ neovim
       ... Use deoplete
       $ cat /tmp/log_{PID}
```

**Comment by fr0077** [comment]
Testing another plugins and I found that it seems not deoplete problem.
ncm2/ncm2 + roxma/nvim-yarp cause the same issue.
Each plugin itself doesn't cause problem, but when combined, nvim hangs.
However, prabirshrestha/asyncomplete.vim has no problem.

Let me close this issue for this time.

**Comment by Shougo** [comment]
OK.
