### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by jahanbani** [Shougo/deoplete.nvim#885]
Just 1 point on the documentation (you ---and the contributors--- are doing an awesome job)
The comma after 'keyword_patterns' must be a colon since this is a dictionary. 
```
		call deoplete#custom#option('keyword_patterns', {
		\ '_': '[a-zA-Z_]\k*',
		\ 'tex': '\\?[a-zA-Z_]\w*',
		\ 'ruby': '[a-zA-Z_]\w*[!?]?',
		\})
```

**Comment by Shougo** [comment]
No.   Please read `deoplete#custom#option()` documentation.

```
deoplete#custom#option({option-name}, {value})
```
