### ISSUE TITLE
How is deoplete different from similar plugins?

### ISSUE THREAD

**Issue by srounce** [Shougo/deoplete.nvim#886]
# Problems summary
Prospective users aren't immediately informed as to the benefits of deoplete.nvim. 
The only summation is:
> Dark powered asynchronous completion framework for neovim/Vim8

Which is frankly meaningless with regard to helping make an informed decision when looking for a new completion engine.

## Expected
Some of the info from #606, put into a few sentences that get across why one would use this over other similar plugins (YCM, asyncomplete, coc.nvim, etc).

## Environment Information

 * deoplete version (SHA1): None

 * OS: WWW

 * neovim/Vim `:version` output: 

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## How to reproduce the problem

Read the first section of the readme, and remain uninformed.

**Comment by Shougo** [comment]
Why I need to explain it?
The auto completion plugins are made for different aims.
And the features will be changed in the later.

This is not QA site and I have not much time to wasting time.
I am very busy to develop plugins.

**Comment by alichtman** [comment]
Yikes. This is a hilariously bad response.

> Why I need to explain it?

Because as the owner, you know the project better than anyone else. If you don't explain what it does better than the other completion plugins, people aren't going to read the code base and figure it out... they're just going to use a different completion plugin. Which is exactly what I'm doing.

**Comment by Shougo** [comment]
Hm.  OK.  I explain it.

**Comment by Shougo** [comment]
deoplete is:

- Python3 based auto completion plugin
- Supports both neovim and Vim8(but neovim is recommended)
- More configurable than other completion plugins

**Comment by Shougo** [comment]
For example, asyncomplete is Vim script based plugin.
So if you don't like Python based plugin, you should not use Python based auto completion plugin(deoplete, ncm2).

coc.nvim is node.js based huge plugin.
It is not just completion plugin, it is all in one IDE system.
If you don't like node.js based plugin or huge plugin base system, you should not choose coc.nvim.

**Comment by Shougo** [comment]
And the important view is the author.
If you like the author or the author created plugins, you should choose the auto completion plugin.

For example, you use denite.nvim deoplete is better than other plugins.

**Comment by Shougo** [comment]
If you use vim-lsp plugin, you should use asyncomplete.vim instead.
Because asyncomplete is created for vim-lsp and it maintained as well.

**Comment by Shougo** [comment]
deoplete is not easy to use plugin and most configurable.
If you don't like to study plugin's usage and configuration, deoplete is not better choice.

**Comment by alichtman** [comment]
You should add these to the README instead of this issue. When people come to this repo, this is the first bit of information they should see.

**Comment by Shougo** [comment]
I don't want to add it to README.
It seems long.  But I will add it on FAQ section.

**Comment by Shougo** [comment]
I have updated the documentation.

**Comment by srounce** [comment]
> I don't want to add it to README.
> It seems long. But I will add it on FAQ section.

I think you really should add it to the README. If someone wants information on this plugin they will come to the repository to find that, and the README will be the first thing they are presented with, the information should be in there. Hardly anyone is going to install the plugin so they can `:help deoplete-faq`. I didn't mean to sound dismissive or sarcastic in opening this issue as I believe it is a real one. The README currently does not do a very good job of communicating what the plugin even really is past the very high level of 'it does autocompletion'.

**Comment by Shougo** [comment]
Sorry.  I don't want to add it in README.

**Comment by Shougo** [comment]
I have added the note about it.

**Comment by fdelacruz** [comment]
This thread is **epic** for lack of a better word.
