### ISSUE TITLE
File name completion in quotes not working

### ISSUE THREAD

**Issue by SageEx** [Shougo/deoplete.nvim#89]
Hi,
First of all thanks for this plugin.

One thing I noticed is that the file name completion works fine outside quotes, but does not trigger inside quotes.
Say, suppose inside #include "" directives file name completion does not work. Is this a feature ? How do I enable this behaviour ?

Also, manual triggering of file name completion does not work in quotes too, any ideas ?

This is my current deoplete config
```
    Plug 'Shougo/deoplete.nvim'
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    " let g:deoplete#omni#input_patterns = {}
    let g:deoplete#auto_completion_start_length = 1
    let g:deoplete#sources = {}
    let g:deoplete#sources._ = []
```

**Comment by Shougo** [comment]
Fixed.

**Comment by SageEx** [comment]
Thanks
