### ISSUE TITLE
file source: enable buffer path not working

### ISSUE THREAD

**Issue by deltaskelta** [Shougo/deoplete.nvim#893]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

when I set the proper options, the file completion path seems to always be in the directory that vim was opened in and it never changes to the buffer path or even when I `cd` into another dir.

## Expected

I would expect that it would respect the `cwd` and the buffer dir if the `enable_buffer_path` option is set I would expect it to generate filenames from the path of the file in the current buffer

## Environment Information

 * deoplete version (SHA1): 04159b053ae83933d67225c53c36d98e516fa729

 * OS: Mac 10.14.1

 * neovim/Vim `:version` output: NVIM v0.3.1

 * `:checkhealth` or `:CheckHealth` result(neovim only): all green 💯 

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:python_host_prog = '/Users/Jeff/.virtualenvs/neovim2/bin/python2.7'
let g:python3_host_prog = '/Users/Jeff/.virtualenvs/neovim3/bin/python3.7'
let g:node_host_prog = '/usr/local/bin/neovim-node-host'
let g:ruby_host_prog = '/usr/local/bin/neovim-ruby-host'

let g:deoplete#enable_at_startup = 1

call deoplete#custom#option({
  \ 'smart_case': v:true,
  \ 'profile': v:true,
  \ })

call deoplete#custom#source(
  \ 'file', 'enable_buffer_path', v:true)

call deoplete#enable_logging('DEBUG', '/tmp/deoplete.log')
```

## How to reproduce the problem from neovim/Vim startup (Required!)

given this structure

```
.
├── README.md
├── dir
│   └── file2
└── file1
```

 1. `vim` (from the README.md dir
 2. `:edit file1` 
 3. type `./` to see completion from the current dir
4. `:edit dir/file2`
5. type `./` to see that the file completion is still happening from the root dir

similarly... if I flip `enable_buffer_path` to false

1. `vim` (from the README.md dir)
2. `:edit file1`
3. type `./` to see current dir path
4. `cd ../
5. type `./` to still see the path that vim was opened in and not the current dir

## Upload the log file

I tried setting the log level to INFO and there were no messages other than deoplete starting

**Comment by Shougo** [comment]
Fixed.

**Comment by deltaskelta** [comment]
Thanks, seems to be working now
