### ISSUE TITLE
Provide a way to optionally parameterize a source in the initialization phase

### ISSUE THREAD

**Issue by reaysawa** [Shougo/deoplete.nvim#894]
The [around](https://github.com/Shougo/deoplete.nvim/blob/master/rplugin/python3/deoplete/source/around.py) source has a bunch of parameters which I would like to be customizable.

- A fixed range of search which is 20 lines up and down.
- Custom marks for the  candidate word relative to where it was gotten from the current line.

All of them are hardcoded.

- I would like to be able to change the range, perhaps to 15 or 10.
- I would like to show the same mark regardless of where it was gotten (above, below, changes, etc...)

So I went ahead and changed the code of around.py to

     def __init__(self, vim):
         super().__init__(vim)
         self.name = 'around'
         self.events = ['Init']
         self.rank = 300
         self.vars = {
             'mark_above': '[A]',
             'mark_below': '[B]',
             'mark_changes': '[C]',
             'range_above': 20,
             'range_below': 20
         }

      def on_event(self, context):
        _vars = self.get_filetype_var('_', 'parameters')
        if _vars:
            self.vars.update(_vars)

And the source configuration to

    call deoplete#custom#var('around', 'parameters', {
      \ '_': {
      \   'mark_above': '[~]',
      \   'mark_below': '[~]',
      \   'mark_changes': '[~]',
      \   'range_above': 10,
      \   'range_below': 10
      \ }
      \})

It does work this way but **it breaks if the user doesn't provide a default vars** for `get_filetype_var` to fetch.

>   -- File around.py, line 28, in on_event
>     _vars = self.get_filetype_var('_', 'parameters')
>   -- File base.py", line 78, in get_filetype_var
>     ft = filetype if (filetype in var) else '_'
>
>
> -- TypeError: argument of type 'NoneType' is not iterable
> Exception during around.on_event for event 'Init': argument of typ e 'NoneType' is not iterable.  Use :messages / see above for error details.

Perhaps I am doing something wrong but I haven't found anything in the documentation regarding customizing of a source's parameters aside from `custom#var`, which breaks under the condition I have mentioned above. Is there a better way to go about this? Thank you in advance.

**Comment by Shougo** [comment]
`deoplete#custom#var()` does not support dictionary initialization.
I will add it later.

**Comment by Shougo** [comment]
And for around source changes, please create the PR.

**Comment by reaysawa** [comment]
I think merging the changes now would break the source for all future users inadvertently, and also people looking to update the plugin. Can I hold off until initialization is supported?

I'll rename the issue to make it easier to track based on what I understood here. Feel free to also do the same if needed.
