### ISSUE TITLE
Manual tag complete and New buffer keywords autoloading

### ISSUE THREAD

**Issue by martin-svk** [Shougo/deoplete.nvim#90]
Hey, Firstly I would like to say Thanks for this amazing plugin. It already words very well,
but I noticed some rough edges. Specs first:

OS: `3.16.0-55-generic #74~14.04.1-Ubuntu  x86_64 GNU/Linux`
Neovim: `NVIM 0.1.1 (compiled Dec  5 2015 21:22:33)`

- 1. I tried to set up manual completion for `tag` source like this:

`inoremap <silent><expr> <C-]> deoplete#mappings#manual_complete("tag")`

But when I try it, it somehow blinks and the popup menu dissapears very fast. I replaced `tag` with
`buffer` and it worked well. When configured to complete automatically, including the `tag` source, everything works and I see tag entries there.

- 2. Are newly opened files automatically "indexed" for keywords ?

I noticed I have to activate completion in the newly opened file to get the keywords "indexed" and
showed in previously opened file's completion menu. Can I force `deoplete` to index newly opened
files automatically? Vim's builtin `<C-p>` works this way.

Thank's again for Your time.

**Comment by Shougo** [comment]
> 1. I tried to set up manual completion for tag source like this:

It is the bug.  Fixed.

> 2. Are newly opened files automatically "indexed" for keywords ?

You must open and edit it.  It is feature to optimize the performance.
No manual caching command.

**Comment by martin-svk** [comment]
1. I just tried it, and it works now.
2. Ok

Thanks.
