### ISSUE TITLE
Have you thought about doing synchronous filtering while waiting for async results to arrive?

### ISSUE THREAD

**Issue by wincent** [Shougo/deoplete.nvim#900]
Just a question inspired by this feature listed in [the Coc README](https://github.com/neoclide/coc.nvim):

> Filter completion items when possible. When your does fuzzy filter with completion items (which would trigger TextChangedI during completion), some completion engines would trigger new completion, but coc filter the items when possible which makes coc much faster. Filter completion items on backspace is also supported.

I've noticed that if I have a long identifier in a buffer like `AVeryLongIdentifier` and I slowly press "A", then "V", then "L", then "I", then deoplete will hide the "pum" after each keypress, retrieve the async completion results after a delay, then show the "pum" again. If you stole the synchronous filtering idea from Coc, then perhaps you could filter the results immediately and leave the "pum" visible while waiting for the definitive results to arrive, which would reduce some of the flickering symptoms that have caused a few people to file issues in the past.

**Comment by Shougo** [comment]
Hm..

deoplete does not `hide` pum until new candidates are generated.
`complete()` is not called.

**Comment by Shougo** [comment]
Of course, I know the flicker issue.

But it should be resolved by new API like `complete_update()`.

**Comment by wincent** [comment]
Just to be clear, the behavior I am talking about is visible here:

![screenflow](https://user-images.githubusercontent.com/7074/50553546-11412880-0ca9-11e9-81e2-e66b0807e078.gif)

Note how after each key press, the "pum" goes away then comes back after a delay.

**Comment by Shougo** [comment]
> Note how after each key press, the "pum" goes away then comes back after a delay.

Hm.  OK.  The popup is removed by Vim.

I want to reproduce the problem in my environment.
Pleasse upload the reproduce-able init.vim and the reproduce instructions.

**Comment by wincent** [comment]
Thanks @Shougo. I can confirm that the current `HEAD` of `master` gets rid of the long delay.
