### ISSUE TITLE
Deoplete plugin's __del__ method not called.

### ISSUE THREAD

**Issue by daliusd** [Shougo/deoplete.nvim#905]
# Problems summary

carlitux/deoplete-ternjs is standard deoplete plugin and it expects that plugin will be destroyed properly. There is \_\_del\_\_ method in plugin that is responsible for closing tern server properly. However deoplete seems to not destroy plugin objects on exit (at least I have not found that in source code).

## Expected

\_\_del\_\_ method for plugin called.

## Environment Information

 * deoplete version (SHA1): dfe7e189b17f28d9b93bda6cc1a64f61fdf5e206

 * OS: Ubuntu Linux

 * neovim/Vim `:version` output: VIM - Vi IMproved 8.0

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'carlitux/deoplete-ternjs', { 'do': 'npm install -g tern' }

let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Open js file and try to auto-complete something.
 2. Check that .tern-port file is created in project dir.
 3. Exit Vim.
 4. Check that .tern-port still exists.

There is pull request with workaround https://github.com/carlitux/deoplete-ternjs/pull/81 that will make this scenario invalid.

**Comment by Shougo** [comment]
Unfortunately, no grantee that `__del__` is called.

`on_event` is called when `VimLeavePre`.  Please use it instead.

**Comment by Shougo** [comment]
Please test it in neovim.

Vim8 has the problem.
https://github.com/Shougo/deoplete.nvim/blob/master/autoload/deoplete/handler.vim#L45

**Comment by Shougo** [comment]
Unfortunately, the source is separated process.
It takes time to send the message.

Vim may finish before message send.

**Comment by daliusd** [comment]
OK. No problem. I will solve problem in other way. I think it would be good to mention that VimLeavePre is not working in Vim.
