### ISSUE TITLE
Commit 252b2b5eb508ff2ba70e8e3d5b7447e6069c0338 breaks language client completion

### ISSUE THREAD

**Issue by dbarrosop** [Shougo/deoplete.nvim#908]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I use `Shougo/deoplete.nvim` in combination with `autozimu/LanguageClient-neovim` to have autocompletion of code, however, since commit 252b2b5eb508ff2ba70e8e3d5b7447e6069c0338 I can only see the `around` source. If I undo that commit everything works as expected.

## Expected

I want to see omni completion source, not just the fastest one.

## Environment Information

 * deoplete version (SHA1):

Current master (b58e1db850fd479fdaa4bbc7d28ebbaa2b31931b)

 * OS:

Macos

 * neovim/Vim `:version` output:

```
NVIM v0.3.2
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNDEBUG -DMIN
_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-
strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/tm
p/neovim-20181231-68781-192nq64/neovim-0.3.2/build/config -I/tmp/neovim-20181231-68781-192nq64/neovim-0.3.2/src -I/usr/local/include -I/u
sr/local/opt/gettext/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/in
clude -I/tmp/neovim-20181231-68781-192nq64/neovim-0.3.2/build/src/nvim/auto -I/tmp/neovim-20181231-68781-192nq64/neovim-0.3.2/build/inclu
de
Compiled by brew@Mojave.local

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/Cellar/neovim/0.3.2/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
set runtimepath+=~/path/to/deoplete.nvim/
let g:deoplete#enable_at_startup = 1
set completefunc=LanguageClient#complete
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Open a file with code for which you have `LanguageClient` properly configured.
 2. Write enough code so the `around` source has some completion data
3. Now try to use `omni` for that same object that `around` has completion data for.

## Screenshot (if possible)

With commit 252b2b5eb508ff2ba70e8e3d5b7447e6069c0338:

<img width="362" alt="screen shot 2019-01-04 at 20 16 26" src="https://user-images.githubusercontent.com/6246622/50706297-b10e0600-105d-11e9-8891-61b90d7906c7.png">

Without commit 252b2b5eb508ff2ba70e8e3d5b7447e6069c0338:

<img width="824" alt="screen shot 2019-01-04 at 20 16 52" src="https://user-images.githubusercontent.com/6246622/50706314-bcf9c800-105d-11e9-9b44-5d91102f51b2.png">

**Comment by Shougo** [comment]
This is not `around` source.  It is `member` source.

I don't know why the problem is occurred.

**Comment by dbarrosop** [comment]
Thanks for the clarification. Is there anything I can do to help out figuring this out? Something I forgot to mention is that in the second case (reverting that commit), when I press `.`, I see immediately the results from the `member` source only to be replaced by the results of the `omni` source a few miliseconds later.
