### ISSUE TITLE
How can a source update completions?

### ISSUE THREAD

**Issue by deltaskelta** [Shougo/deoplete.nvim#909]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

I am writing a source and working with a language server. The `gater_candidates` method gets a simple quick list of completions (easy calculation) and then the detailed completions are gotten which takes longer. Detailed completions will always be a subset of the basic ones. Deoplete by default will show double entries like this 

![screen shot 2019-01-08 at 2 21 35 am](https://user-images.githubusercontent.com/9424192/50782726-2a228d00-12ec-11e9-80af-112445f67bbf.png)

I tried to set `self.dup = False` but that just rejects the detailed completions which will always be coming after the basic ones.

I also tried writing a swappaer function which swaps the duplicate keys and returns one full set, but that didn't work either.
 
## Expected

I would expect that I would have a way to update completions after they have been returned from the function... This function switches to async and then the `completion_res` part returns always before the `completion_res_detailed` part

```python
    def gather_candidates(self, context):
        try:
            if context["is_async"]:
                # if there is a detailed response, this is the end of the line, set async to 
                # false in order to stop deoplete from refreshing
                res_detailed = self.vim.vars["nvim_typescript#completion_res_detailed"]
                if res_detailed:
                    context["is_async"] = False
                    self.reset_vars()
                    return res_detailed

                # if there is a basic completion response, return it and let deoplete keep
                # checking for a more detailed response
                res = self.vim.vars["nvim_typescript#completion_res"]
                if res:
                    return res
            else:
                context["is_async"] = True
                [offset] = context["complete_position"] + 1,
                self.reset_vars()
                self.vim.funcs.TSDeoplete(context["complete_str"], offset)
            return []
        except:
            return []

```

**Comment by Shougo** [comment]
Unfortunately, the behavior is not supported.
`is_async` appends the current candidates.
It is not `update`.

I can change the behavior, but it is breaks backward compatibility.
And the behavior is different from denite.

**Comment by deltaskelta** [comment]
I see. Having double isn't so bad. Thanks for the response!
