### ISSUE TITLE
NeoComplCache like omni completion for all file types

### ISSUE THREAD

**Issue by SageEx** [Shougo/deoplete.nvim#91]
Is there a way to turn on default omni-completion for all file-types like neocomplcache ? 
Also, in deoplete default C-X C-O for omnicomplete does not work. Any ideas ?

My config for deoplete.nvim
```
    Plug 'Shougo/deoplete.nvim'
    let g:deoplete#enable_at_startup = 1
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
    let g:deoplete#omni#input_patterns = {}
    let g:deoplete#auto_completion_start_length = 1
    let g:deoplete#sources = {}
    let g:deoplete#sources._ = []
```

**Comment by Shougo** [comment]
> Is there a way to turn on default omni-completion for all file-types like neocomplcache ? 

I don't get the behaviour.  Please explain it.

> Also, in deoplete default C-X C-O for omnicomplete does not work. Any ideas ?

Please explain the example.

**Comment by SageEx** [comment]
When opening a php file 
 - with neocomplcache, type "mysql" , we get suggestions for all php default functions.

-  with deoplete, type "mysql" nothing happens. Type C-X-C-O - still nothing.

**Comment by Shougo** [comment]
OK.  You must config deoplete.

```vim
		let g:deoplete#omni_patterns = {}
		let g:deoplete#omni_patterns.php =
		\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
```

**Comment by SageEx** [comment]
So, for each file type we need to set this ?

**Comment by SageEx** [comment]
The above configuration still does nothing , so I made a minimal init.vim - still not working.
```
set runtimepath+="~/.config/nvim/plugged/deoplete.nvim"
let g:deoplete#enable_at_startup = 1

let $NVIM_TUI_ENABLE_TRUE_COLOR=1
let $NVIM_TUI_ENABLE_CURSOR_SHAPE=1
let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.php =
\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'
set omnifunc=syntaxcomplete#Complete

let g:deoplete#auto_completion_start_length = 1
let g:deoplete#sources = {}
let g:deoplete#sources._ = []
```

**Comment by Shougo** [comment]
@SageEx If you want to call it automatically, you must set the variable.

> with deoplete, type "mysql" nothing happens. Type C-X-C-O - still nothing.

It is the omnifunc problem.  I cannot fix it.
Your `<C-x><C-o>` is the default mappings?

> The above configuration still does nothing , so I made a minimal init.vim - still not working.

Please check your `omnifunc` option is set correctly in php filetype.

**Comment by Shougo** [comment]
I think you must set `filetype plugin indent on` in your init.vim.

**Comment by SageEx** [comment]
I added `filetype plugin indent on` and removed the custom omnifunc. Still no completion.
This is the current init.vim
```
filetype plugin indent on
set runtimepath+="~/.config/nvim/plugged/deoplete.nvim"
let g:deoplete#enable_at_startup = 1

let g:deoplete#omni_patterns = {}
let g:deoplete#omni_patterns.php =
\ '\h\w*\|[^. \t]->\%(\h\w*\)\?\|\h\w*::\%(\h\w*\)\?'

let g:deoplete#auto_completion_start_length = 1
let g:deoplete#sources = {}
let g:deoplete#sources._ = []
```
set omnifunc? returns - `omnifunc=phpcomplete#CompletePHP`

> Your C-x C-o is the default mappings?

C-x C-o is the default insert mode omnicomplete feature - I have not modified it.

**Comment by SageEx** [comment]
Ok, this is strange, omnicompletion works perfectly when using an existing php file - just like neocomplcache, but when I open a new php file , there is no omnicompletion - it says no patterns found.

Any ideas ?

BTW, can we have camel case completion from neocomplcache ?

**Comment by Shougo** [comment]
@SageEx 

```vim
set runtimepath+=~/.config/nvim/plugged/deoplete.nvim
```
is correct path.

> Ok, this is strange, omnicompletion works perfectly when using an existing php file - just like neocomplcache, but when I open a new php file , there is no omnicompletion - it says no patterns found. 

Yes, phpcomplete needs `<?php ?>` block to complete the candidates.
It is phpcomplete feature.  Closing.

**Comment by SageEx** [comment]
Thanks.
