### ISSUE TITLE
how to behave like YCM when scroll the popup content

### ISSUE THREAD

**Issue by chenjie199234** [Shougo/deoplete.nvim#912]
The deoplete works fine.
I just want to know how behave like this.
When i scroll the popup menu:
Deoplete:i need to insert Enter Key every time i scroll the popup menu to select the right content.
YCM:i dont need to insert Enter Key,it will write the content under the cursor when i scroll the popun menu

**Comment by roxma** [comment]
Use `<C-N>` and `<C-P>` instead of `<down>` and  `<up>` for scrolling the popup menu?

**Comment by chenjie199234** [comment]
@roxma can we add an option to set the key like YCM.
here are my set.
inoremap <C-j> <Down>
inoremap <C-k><Up>
what i want is that:
if (there is a popup menu)
    <C-j> <C-k> will work like <C-n> <C-p>
else
    <C-j> <C-k> will work like <Down> <Up>
In Ycm,there is an option to set <Down> <Up>to work like <C-n><C-p>.
But in deoplete i can't set that.

**Comment by Shougo** [comment]
```vim
inoremap <expr><C-j> pumvisible()? "\<C-n>" : "\<Down>"
inoremap <expr><C-k> pumvisible()? "\<C-p>" : "\<Up>"
```
