### ISSUE TITLE
how to auto close the function info window when i leave insert mode

### ISSUE THREAD

**Issue by chenjie199234** [Shougo/deoplete.nvim#913]
i'm using deoplete.vim and deoplete-go
when i scroll the popup menu,a new window will be created on the top of the terminal to show the information of the function,like args,arg type etc.
how to close the window automatic when i leave the insert mode!
![2019-01-11-010832_1212x753_scrot](https://user-images.githubusercontent.com/29348971/50984891-e58e3000-153d-11e9-8dc2-5f4f00279f88.png)

**Comment by reaysawa** [comment]
```
:pc[lose][!]	Close any "Preview" window currently open.  When the 'hidden'
		option is set, or when the buffer was changed and the [!] is
		used, the buffer becomes hidden (unless there is another
		window editing it).  The command fails if any "Preview" buffer
		cannot be closed.  See also |:close|.
```

I suggest you bind that command to InsertLeave, CompleteDone, whatever works best for you

**Comment by chenjie199234** [comment]
@reaysawa thx very much.it works fine now!
