### ISSUE TITLE
 Can't get the completion of the completion

### ISSUE THREAD

**Issue by PendragonSaber** [Shougo/deoplete.nvim#916]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
hi  The recent gocode table is really bad. I am going to switch go's lsp. I use languageClien-neovim deoplete go-langserver. When I choose to complete, I get a bunch of things, it should be a code snippet but it fails. How can I fix such a problem?

## Environment Information

 * deoplete version (SHA1):
the lastest
 * OS:
linux manjaro  macos13.6 
 * neovim/Vim `:version` output:
neovim 0.3.3
 * `:checkhealth` or `:CheckHealth` result(neovim only):
![check](https://user-images.githubusercontent.com/41671631/51081374-154d5b80-1729-11e9-84e4-e469a53b1a6a.png)

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
let g:deoplete#enable_at_startup = 1
set hidden
let g:LanguageClient_serverCommands = {
    \ 'go' : ['go-langserver', '-gocodecompletion', '-diagnostics', '-logfile=/tmp/go-langserver.log', "-lint-tool=golint"],
\ }
nnoremap <silent> K :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> gd :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <F2> :call LanguageClient_textDocument_rename()<CR>
  " not stop completion $ & /
setlocal iskeyword+=$
setlocal iskeyword+=- 
```
## Screenshot (if possible)
![untitled](https://user-images.githubusercontent.com/41671631/51081407-c5bb5f80-1729-11e9-83bd-48a4324f3174.gif)

**Comment by PendragonSaber** [comment]
I found the same problem, but I didn't find a way. This is a problem with LanguageClient. [issues](https://github.com/autozimu/LanguageClient-neovim/issues/396)

**Comment by Shougo** [comment]
Yes.  It is not deoplete problem.
LanguageClient neovim should use `user_data`.

**Comment by PendragonSaber** [comment]
> 是。这不是deoplete问题。
> LanguageClient neovim应该使用`user_data`。


@Shougo  Because I am your fan, deoplete I have used it for a long time, but bad experience of gocode, I have to consider switching lsp, LangClient-neovim has problems, so I can't continue to use deoplete, I consider switching coc, hope deoplete -lsp can be used as soon as possible

**Comment by Shougo** [comment]
Hm.  You can use deoplete-tabnine instead.

https://github.com/tbodt/deoplete-tabnine

It also supports LSP completion.

**Comment by PendragonSaber** [comment]
> 嗯。您可以使用deoplete-tabnine代替。
> 
> https://github.com/tbodt/deoplete-tabnine
> 
> 它还支持LSP完成。


Tabnine is charged according to my understanding, deoplete-tabnie has no documentation and does not understand how it works with lsp

**Comment by Shougo** [comment]
You can read tabnine's documentation to understand the usage.

**Comment by PendragonSaber** [comment]
> You can read tabnine's documentation to understand the usage.

Thank you for your help, but I still look forward to using your plugin, because I am your loyal fan, the current situation I can only switch coc for a while until your related lsp plugin can be used

**Comment by Shougo** [comment]
> Thank you for your help, but I still look forward to using your plugin, because I am your loyal fan, the current situation I can only switch coc for a while until your related lsp plugin can be used

I use deoplete-tabnine for LSP completion.
So it works.
