### ISSUE TITLE
Gradually fill the completion list for certain sources

### ISSUE THREAD

**Issue by DarkDefender** [Shougo/deoplete.nvim#92]
I'm sorry if this is not the right place to ask, but is it possible to gradually fill the completion list?

I'm asking because I modified the clang_complete source to call the clang lib directly for completions. And it works well, but the clang complete source is quite slow.

https://github.com/Rip-Rip/clang_complete/pull/464

Because it's slow, the completion candidates from other sources will not show up until the clang complete source is done.

So I'm wondering if I could somehow show the completion candidates from the faster sources first and then add the clang complete candidates when it's done?

If this is something that can be done, then perhaps add a something to the menu that tells the user that not all sources has returned their completion candidates.

**Comment by Shougo** [comment]
Unfortunately, it cannot.  Because, Vim/neovim does not support it.
unite.vim already implemented though....
You can request the feature in neovim issues.

Performance advice:
To call clang_complete is too slow.
I think to call clang_complete if cursor is after `.` or `::` or `->` only is better.
