### ISSUE TITLE
Documentation for deoplete-source-around invalid syntax

### ISSUE THREAD

**Issue by ipwnponies** [Shougo/deoplete.nvim#922]
The documentation for `deoplete- source-around` is invalid syntax, needs a trailing comma on line 568.
https://github.com/Shougo/deoplete.nvim/blob/067ed5acdc77d200fb6c2bb28caee63f5781bba3/doc/deoplete.txt#L566-L570

**Comment by Shougo** [comment]
Thanks.  I will fix it later.
