### ISSUE TITLE
I wanted to ask your opinion on "deoplete-plugins" org

### ISSUE THREAD

**Issue by zchee** [Shougo/deoplete.nvim#928]
This issue is not related deoplete.nvim source. Just I wanted to ask your opinion.

I previously developed some deoplete plugins (sources). But now, I have no time to continue to maintain those project. (Thanks for maintaining 🙇)
So, I created [`deoplete-plugins`](https://github.com/deoplete-plugins) organization for now.

If you agree, I would like to transfer some repositories under the [`zchee`](https://github.com/zchee) to that org. And want to invite you (and their maintainers).
What do you think about it?

**Comment by zchee** [comment]
If you accept the org invitation, please close this issue, thank.

**Comment by zchee** [comment]
and @hori-ryota

**Comment by zchee** [comment]
moved all of repositories.

**Comment by Shougo** [comment]
I have updated the documentation.

**Comment by Shougo** [comment]
I have updated Wiki.
