### ISSUE TITLE
Enabling auto completion after locking does not work

### ISSUE THREAD

**Issue by martin-svk** [Shougo/deoplete.nvim#93]
Hello again,

I am trying to solve [this](https://github.com/SirVer/ultisnips/issues/618) issue by locking and then
enabling `deoplete` autocompletion before and after multiple cursors like this:

```viml
" Called once right before you start selecting multiple cursors
function! Multiple_cursors_before()
  let b:deoplete_disable_auto_complete=1
endfunction

" Called once only when the multiple selection is canceled (default <Esc>)
function! Multiple_cursors_after()
  let b:deoplete_disable_auto_complete=0
endfunction
```

The referenced issue is solved by this because the auto-completion is disabled in `before()` function,
but `let b:deoplete_disable_auto_complete=0` does not enables it again.

**Comment by Shougo** [comment]
Fixed.
