### ISSUE TITLE
Deoplete failed to load

### ISSUE THREAD

**Issue by RevoNova** [Shougo/deoplete.nvim#930]
# Problems summary
`[deoplete] Vim(call):E117: Unknown function: _deoplete_init
[deoplete] function deoplete#enable[9]..deoplete#initialize[1]..deoplete#init#_initialize[12]..deoplete#init#_channel, line 27
[deoplete] deoplete failed to load. Try the :UpdateRemotePlugins command and restart Neovim. See also :checkhealth.
`
:UpdateRemotePlugins does nothing
`
function remote#host#UpdateRemotePlugins[6]..<SNR>138_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5
Plugin "C:/Users/jason/.vim/dein/.cache/init.vim/.dein/rplugin/python3/denite" is already registered
remote/host: generated rplugin manifest: C:\Users\jason\AppData\Local\nvim-data/rplugin.vim
`

## Expected
No errors.

## Environment Information

 * deoplete version (SHA1):
1d577d43feae8eae88176c7909e7891297acc8de
 * OS:
Windows 10 x64
 * neovim/Vim `:version` output:
`

NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe /DWIN32 /D_WINDOWS /W3 /MD /Zi /O2 /Ob1 /DNDEBUG -DMIN_LOG_LEVEL=3 /W3 -D_CRT_SECURE_NO_WARNINGS -D_CRT_NONSTDC_NO_DEPRECATE -DWIN32 -D_WIN32_WINNT=0x0600 -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -IC:/projects/neovim/build/config -IC:/projects/neovim/src -IC:/projects/neovim/.deps/usr/include -IC:/projects/neovim/build/src/nvim/auto -IC:/projects/neovim/build/include
Compiled by appveyor@APPVYR-WIN

Features: -acl +iconv -jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM\sysinit.vim"
  fall-back for $VIM: "C:/Program Files/nvim/share/nvim"

Run :checkhealth for more info
`
 * `:checkhealth` or `:CheckHealth` result(neovim only):
`
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#jedi#check
========================================================================
##### jedi-vim version

 - jedi-vim git version: fatal: not a git repository (or any of the parent directories): .git
 - jedi git submodule status: fatal: not a git repository (or any of the parent directories): .git
 - parso git submodule status: fatal: not a git repository (or any of the parent directories): .git

##### Global Python

Using Python version 3 to access Jedi.
 - global sys.version: `3.7.2 (tags/v3.7.2:9a3ffc0492, Dec 23 2018, 23:09:28) [MSC v.1916 64 bit (AMD64)]`
 - global site module: `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site.py`

##### Jedi

 - path: `C:/Users/jason/.vim/dein/.cache/init.vim/.dein\pythonx\jedi\jedi\__init__.py`
 - version: 0.13.1

##### Jedi environment: <SameEnvironment: 3.7.2 in C:\users\jason\Appdata\local\Programs\Python\Python37>

 - executable: C:\users\jason\Appdata\local\Programs\Python\Python37\python.exe
 - sys_path:
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\python37.zip`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\DLLs`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37`
    - `C:\Users\jason\AppData\Roaming\Python\Python37\site-packages`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\google_cl-0.9.15.1-py3.7.egg`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\oauth2client-4.0.0-py3.7.egg`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\httplib2-0.9.2-py3.7.egg`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\gdata-2.0.18-py3.7.egg`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\rsa-4.0-py3.7.egg`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\win32`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\win32\lib`
    - `C:\users\jason\Appdata\local\Programs\Python\Python37\lib\site-packages\Pythonwin`

##### Known environments

 - <Environment: 3.7.2 in C:\Users\jason\AppData\Local\Programs\Python\Python37> (C:\Users\jason\AppData\Local\Programs\Python\Python37\python.exe)

##### Settings

```
g:jedi#completions_enabled = 0 (default: 1)


  omnifunc=htmlcomplete#CompleteTags
	Last set from C:\tools\neovim\Neovim\share\nvim\runtime\ftplugin\html.vim
  completeopt=menuone,longest,preview
	Last set from ~\.vim\dein\.cache\init.vim\.dein\plugin\jedi.vim
```

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: ".dein" is not registered.
  - WARNING: "deoplete.nvim" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 2 provider (optional)
  - INFO: Disabled (g:loaded_python_provider=1).  This might be due to some previous error.
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          python2 not found in search path or not executable.
          python2.7 not found in search path or not executable.
          python2.6 not found in search path or not executable.
          C:\Users\jason\AppData\Local\Programs\Python\Python37\python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\users\jason\Appdata\local\Programs\Python\Python37\python.exe"
  - INFO: Executable: C:\users\jason\Appdata\local\Programs\Python\Python37\python.exe
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node.js provider (optional)
  - INFO: Node.js: v10.14.2
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

`
## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

`
set rtp+=~/.vim/dein/repos/github.com/Shougo/dein.vim
if dein#load_state('~/.vim/dein')
  call dein#begin('~/.vim/dein')
  call dein#add('~/.vim/dein/repos/github.com/shougo/dein.vim')
  call dein#add('shougo/deoplete.nvim')
  call dein#end()
  call dein#save_state()
endif
call deoplete#custom#source('_', 'matchers', ['matcher_full_fuzzy'])
call deoplete#custom#option({
\ 'auto_complete_delay': 200,
\ 'camel_case': v:true,
\ })
let g:python3_host_prog='C:\users\jason\Appdata\local\Programs\Python\Python37\python.exe'
set rtp+=~/.vim/dein/repos/github.com/Shougo/deoplete.nvim
let g:deoplete#enable_at_startup = 1
`

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Start Neovim
or
 2. call deoplete#enable()

## Screenshot (if possible)

![error](https://user-images.githubusercontent.com/35003073/52273573-d653a400-297c-11e9-8848-3d0780d68ab7.PNG)

**Comment by Shougo** [comment]
> :UpdateRemotePlugins does nothing

```
`function remote#host#UpdateRemotePlugins[6]..<SNR>138_RegistrationCommands[13]..remote#host#RegisterPlugin, line 5 Plugin "C:/Users/jason/.vim/dein/.cache/init.vim/.dein/rplugin/python3/denite" is already registered remote/host: generated rplugin manifest: C:\Users\jason\AppData\Local\nvim-data/rplugin.vim`
```

`:UpdateRemotePlugins` does not work.
You must fix the problem.

```
## Remote Plugins

    * WARNING: ".dein" is not registered.

    * WARNING: "deoplete.nvim" is not registered.

    * WARNING: Out of date
      
      * ADVICE:
        
        * Run `:UpdateRemotePlugins`
```

**Comment by RevoNova** [comment]
How can I fix it?

**Comment by Shougo** [comment]
You should read other issues.

https://github.com/Shougo/deoplete.nvim/issues/688

**Comment by Shougo** [comment]
And your `:UpdateRemotePlugins` output is something wrong.

denite.nvim is not installed, but denite.nvim is registered?
Have you tried `:UpdateRemotePlugins` in the minimal vimrc?

**Comment by Shougo** [comment]
I think you don't try the minimal vimrc.
Your screenshot is not from minimal vimrc.

So I don't support it sorry.

**Comment by Shougo** [comment]
You should test deoplete.nvim without dein.vim.
It is the minimal vimrc.

For example:

```vim
let g:python3_host_prog='C:\users\jason\Appdata\local\Programs\Python\Python37\python.exe'
set rtp+=~/.vim/dein/repos/github.com/Shougo/deoplete.nvim
let g:deoplete#enable_at_startup = 1
```

Note: I don't know `set rtp+=~/.vim/dein/...` is works properly in Windows environment.

**Comment by RevoNova** [comment]
Here is the screenshot of the minimal vimrc you sent.
![minimal](https://user-images.githubusercontent.com/35003073/52313775-6546d780-29e2-11e9-9209-acbed2734bd8.PNG)

**Comment by RevoNova** [comment]
Thanks it worked!
Running :UpdateRemotePlugins in the minimal vimrc successfully updated Deoplete as a remote plugin.

Thanks Shougo!

**Comment by Shougo** [comment]
So I have said...

**Comment by Rentfunk** [comment]
What is minmal vimrc?

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/issues/930#issuecomment-460853757
