### ISSUE TITLE
Wrong autopopup OmniSharp (C#)

### ISSUE THREAD

**Issue by trobjo** [Shougo/deoplete.nvim#931]
# Problems summary
For the most part deoplete works really well, but when I try to do a method call (I think that's the name), deoplete won't give the OmniSharp completion but only: 
![screenshot_2019-02-10-205119](https://user-images.githubusercontent.com/26080212/52538996-a986fe80-2d79-11e9-89d6-f24391a5b38a.png)
You can see that deoplete by default only looks in the current buffer. 

I expected it to give me (and that is default behaviour in YouCompleteMe):
![screenshot_2019-02-10-205134](https://user-images.githubusercontent.com/26080212/52538863-f8cc2f80-2d77-11e9-9d3e-67fa0bd751df.png)

I triggered this by C-x C-o.

How do I make deoplete use OmniSharp completion always?

## Environment Information

 * deoplete version (SHA1):

Latest version (2019-02-10)

 * OS: 
Arch Linux

 * neovim/Vim `:version` output: 

NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

 * `:checkhealth` or `:CheckHealth` result(neovim only):

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#LanguageClient#check
========================================================================
  - OK: binary found: /home/tb/.local/share/nvim/plugged/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.139 

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python version: 2.7.15
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
`call plug#begin('~/.local/share/nvim/plugged')
Plug 'OmniSharp/omnisharp-vim'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
call plug#end()

let g:deoplete#enable_at_startup = 1`

## How to reproduce the problem from neovim/Vim startup (Required!)

1. open .cs file with Vim
2. Try method call from another class.

**Comment by Shougo** [comment]
Please create the issue in `omnisharp-vim`.

I think you need to configure omnisharp.
