### ISSUE TITLE
Bug with Vim-Multip-Cursor auto insert "<Plug>_"

### ISSUE THREAD

**Issue by DemonCloud** [Shougo/deoplete.nvim#933]
Bug with Vim-Multip-Cursor auto insert "<Plug>_"

## Environment Information

 * deoplete version (SHA1):

 * OS: Mac 10.14.2

 * neovim/Vim `:version` output: 0.3.4

## Screenshot (if possible)
![2019-02-13 10 05 09](https://user-images.githubusercontent.com/7436361/52681650-8e81dd80-2f77-11e9-87a5-aa2b308632e1.gif)

**Comment by Shougo** [comment]
Please read the documentation

```
Q: Deoplete does not work with vim-multiple-cursors.

A: You must disable deoplete when using vim-multiple-cursors. >

       function g:Multiple_cursors_before()
         call deoplete#custom#buffer_option('auto_complete', v:false)
       endfunction
       function g:Multiple_cursors_after()
         call deoplete#custom#buffer_option('auto_complete', v:true)
       endfunction

```

**Comment by DemonCloud** [comment]
@Shougo  Thanks for reply
