### ISSUE TITLE
xolox/vim-lua-ftplugin omnifunc works but deoplete does not display it

### ISSUE THREAD

**Issue by antoinemadec** [Shougo/deoplete.nvim#934]
# Problems summary
```<C-x> + <C+u>``` works fine with **'xolox/vim-lua-ftplugin'** but deoplete does not display the omnifunc info.

## Expected
Following the LUA guidelines of ```:help deoplete``` (as well as #840 ) should work.
 
## Environment Information
 * deoplete version (SHA1):  8ed2c9a

 * OS: Debian Testing

 * Vim `:version` output:
VIM - Vi IMproved 8.1 (2018 May 18, compiled Feb  1 2019 12:11:00)
Included patches: 1-866

## Minimal vimrc

```vim
call plug#begin('~/.vim/plugins_by_vimplug')
Plug 'Shougo/deoplete.nvim'
Plug 'roxma/nvim-yarp'
Plug 'roxma/vim-hug-neovim-rpc'
Plug 'xolox/vim-misc', { 'for' : 'lua' }
Plug 'xolox/vim-lua-ftplugin', { 'for' : 'lua' }
call plug#end()

set nocompatible

let g:deoplete#enable_at_startup = 1

let g:lua_check_syntax = 0
let g:lua_complete_omni = 1
let g:lua_complete_dynamic = 0
let g:lua_define_completion_mappings = 0
call deoplete#custom#var('omni', 'functions', {
      \ 'lua': 'xolox#lua#omnifunc',
      \ })
```

## How to reproduce the problem from Vim startup

 1. vim -u <minimal_vimrc> foo.lua
 2. enter insert mode: ```i```
 3. type: ```do```
 4. type ```<C-x><C-u```. omnifunc is working fine, we see ```dofile()```
 5. however, we never see this omnifunc info in deoplete without using ```<C-x><C-u>```

**Comment by Shougo** [comment]
```
       call deoplete#custom#var('omni', 'input_patterns', {
       \ 'lua': '\w+|\w+[.:]\w*',
       \ )
```

is needed.

**Comment by antoinemadec** [comment]
Missing a bracket:
```vim
call deoplete#custom#var('omni', 'input_patterns', {
\ 'lua': '\w+|\w+[.:]\w*',
\ })
```

Thanks a lot!
