### ISSUE TITLE
deoplete + neosnippet = bad completion

### ISSUE THREAD

**Issue by JeanMertz** [Shougo/deoplete.nvim#937]
Using the latest deoplete + neosnippet plugin, I've got this issue where completion works (including changing cursor position) if I only select the first available response.

But as soon as I start to scroll up or down using `<c-n>` and `<c-p>`, you can see the cursor position marker `$0` being added to the result, and when I make a selection (even if I scroll back to the first one), a new line is added at the cursor marker.

![recording2](https://user-images.githubusercontent.com/383250/52822773-fdb01c80-30b2-11e9-9ba6-31f39ed8708b.gif)

**Comment by Shougo** [comment]
> you can see the cursor position marker `$0` being added to the result

It is the feature of neosnippet and LanguageClient-neovim.
It supports snippet expansion in the candidate.

**Comment by Shougo** [comment]
I will test it, but...

Please don't ignore the issue template.
You don't upload the minimal init.vim and reproduce-able instructions.
Please read other issues like this.
https://github.com/Shougo/deoplete.nvim/issues/934

I can close ignored template issues.

**Comment by JeanMertz** [comment]
> Please don't ignore the issue template.

You are absolutely right. It was late, and I had been trying to get this to work, so I figured I'd make a quick issue, in the hopes that it was an easy thing I missed. Still, that's selfish, and I shouldn't have done it.

I'll get a minimal init.vim as soon as possible, and perhaps in the process I can figure out what's going on 👍

**Comment by Shougo** [comment]
I have tested it and it works as expected.
If you want to disable the snippets feature:

```vim
let g:LanguageClient_hasSnippet = 0
```

**Comment by JeanMertz** [comment]
> I have tested it and it works as expected.

So just to make sure I understand correctly:

The behavior you are seeing with the above example is:

* when scrolling through the list of potential completions, you don't see `$0` being added to the completion?
* and, more importantly, when you complete a completion with a snippet (importantly, _after_ scrolling to it, so not selecting the first possible completion), you don't see a newline being added at the point of the snippet?

**Comment by Shougo** [comment]
>     * when scrolling through the list of potential completions, you don't see `$0` being added to the completion?

I have seen `$0`, yes.  But it is not deoplete feature.
It is `LanguageClient-neovim` feature.  If you don't like it, you should request in `LanguageClient-neovim` issues.

>     * and, more importantly, when you complete a completion with a snippet (importantly, _after_ scrolling to it, so not selecting the first possible completion), you don't see a newline being added at the point of the snippet?

I think you have selected the candidate by `<CR>` key `from my ESP skills`.

So you should use the mapping:

```vim
inoremap <expr><CR>   pumvisible()?  "\<C-y>" : "\<CR>"
```

So they are expected behavior and not problem for deoplete.
Closing.

**Comment by JeanMertz** [comment]
> you should use the mapping

Ah of course. This was indeed the issue. Thank you.

> I have seen `$0`, yes. But it is not deoplete feature. It is `LanguageClient-neovim` feature.

I see. That makes sense.
