### ISSUE TITLE
golang complete print error

### ISSUE THREAD

**Issue by itetao** [Shougo/deoplete.nvim#943]
i'am a newer for neovim and program,   i got a problem, can you help me, very thanks
![deoplete1](https://user-images.githubusercontent.com/46645709/53707903-e96a6e80-3e6b-11e9-88ab-63fc9c82e52c.png)
![deoplete2](https://user-images.githubusercontent.com/46645709/53707906-ec655f00-3e6b-11e9-8fd8-79120c75f71c.png)
![deoplete3](https://user-images.githubusercontent.com/46645709/53707911-f0917c80-3e6b-11e9-8384-ddfb88119f94.png)
![deoplete4](https://user-images.githubusercontent.com/46645709/53707916-f38c6d00-3e6b-11e9-9de2-d613c152c182.png)

**Comment by Shougo** [comment]
It is not deoplete issue.
Closing.

**Comment by Shougo** [comment]
The first is vim-go error.
The second is deoplete-go error.

The second error is from your configuration.

**Comment by Shougo** [comment]
You have enabled source option.
It is invalid in your gocode.

**Comment by itetao** [comment]
i got it. Thanks very much
