### ISSUE TITLE
Source Precident

### ISSUE THREAD

**Issue by phatsk** [Shougo/deoplete.nvim#944]
This is not a bug report, but a feature request. Is there a way to prefer a completion source over another?

### My init.vim

```vim
" Deoplete
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option('max_list', 10)
" Disable documentation window
set completeopt-=preview
let g:deoplete#enable_at_startup = 1
call deoplete#custom#option( 'sources', {
\	'php': ['LanguageClient', 'tag', 'buffer']
\})
```

### Behavior
When I start typing a function, say `get_post_meta`, which is used in the current buffer elsewhere, it completes based on what it finds in the buffer. If I open a new PHP file and begin typing `get_post_meta`, I get the full method signature from the `tags` source.

### Expected
It would be useful if the completion list could prefer sources in the order they're defined in the `sources` configuration option, such that if `tags` are defined first, they take precedence over the preceding sources.

Thanks, this plugin is great!

**Comment by Shougo** [comment]
Sorry.  I don't want to add the feature.  But you can change the order by source's rank.

`:help deoplete-source-attribute-rank`

```vim
" Change the source rank
call deoplete#custom#source('tag', 'rank', 200)
```
