### ISSUE TITLE
Symbol used for LSP suggestions

### ISSUE THREAD

**Issue by IamGianluca** [Shougo/deoplete.nvim#945]
First of all, thanks for the amazing plugin!

Just a curiosity, what is the [symbol](https://github.com/Shougo/deoplete.nvim/blob/d71a470d2fa4a1dac53fd9eb5684cc4ab7e59400/doc/deoplete.txt#L1444) used to identify suggestions coming from `languageclient-neovim`? `[A]` is used for around, `[B]` for buffer, etc... is it `[M]`?

**Comment by Shougo** [comment]
`[M]` is used for `member` source.
LanguageClient-neovim uses `[LC]`.

**Comment by IamGianluca** [comment]
Thanks Shougo!
