### ISSUE TITLE
Javascript completion

### ISSUE THREAD

**Issue by kuator** [Shougo/deoplete.nvim#946]
So, it's not a problem, but a question. I wanted to set the omnicompletion, so it works all the time. 
```
call deoplete#custom#option('omni_patterns', {
		\  'javascript': '.*',
		\})

```
But should I do this? Because in Q&A omnicompletin works only when there is a dot. 

```
call deoplete#custom#option('omni_patterns', {
		\  'javascript': '[^. *\t]\.\w*',
		\})

```
Maybe there is a reason I don't know. Like deoplete is eating cpu or something. Thank you in advance

**Comment by Shougo** [comment]
Because, omnifunc is slow than other source and it blocks your Vim.
