### ISSUE TITLE
Deoplete not working properly on WSL bash

### ISSUE THREAD

**Issue by matbc92** [Shougo/deoplete.nvim#948]
# Problems summary
I'm using two systems and I was intending to sync my init.vim for the neovim of both of them, the problema is that on one system I use ubuntu, and on the other I use neovim from the ubuntu shell of the Windows Subsystem Linux, and on that second one, the deoplete does not look to be working very well, as on the pure ubuntu system it works flawlessly, then I would like to know what might be causeL. All help is much appreciated.
## Expected
I expected the deoplete plugin to work pretty much as  it worked on the ubuntu system, with the suggestions appearing in real time and contextually appropriately, but they don't show up at all.

## Environment Information

 * deoplete version (SHA1): I cannot find out how to check my actual version of deoplete, although I tried to update to latest version through the Plug plugin manager

 * OS: Windows 10 , although using it through the ubuntu WSL bash

 * neovim `:version` output:  
```
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/gcc-5 -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/travis/build/neovim/bot-ci/build/neovim/build/config -I/home/travis/build/neovim/bot-ci/build/neovim/src -I/home/travis/build/neovim/bot-ci/build/neovim/.deps/usr/include -I/usr/include -I/home/travis/build/neovim/bot-ci/build/neovim/build/src/nvim/auto -I/home/travis/build/neovim/bot-ci/build/neovim/build/include
Compiled by travis@travis-job-bb83ace7-63ac-4a89-b318-3a124a2bc311

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "
/home/travis/build/neovim/bot-ci/build/neovim/build/nvim.AppDir/usr/share/nvim
"

Run :checkhealth for more info
```

 * `:checkhealth` or `:CheckHealth` result(neovim only): 
```


health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#jedi#check
========================================================================
## jedi
#### Jedi-vim debug information


##### jedi-vim version


 - jedi-vim git version: 1f7e661
 - jedi git submodule status:  0bf8a69024aff8599bd1f323c4feba2703ef3d59 pythonx/jedi (v0.13.3)
 - parso git submodule status:  acccb4f28d6d57f4ad4c882f3408136ee8f50ff5 pythonx/parso (v0.3.4)


##### Global Python


Using Python version 3 to access Jedi.
 - global sys.version: `3.6.7 (default, Oct 22 2018, 11:32:17), [GCC 8.2.0]`
 - global site module: `/usr/lib/python3.6/site.py`

##### Jedi

 - path: `/home/matbc92/.config/nvim/plugged/jedi-vim/pythonx/jedi/jedi/__init__.py`
 - version: 0.13.3

##### Jedi environment: <SameEnvironment: 3.6.7 in /usr>


 - executable: /usr/bin/python3.6
 - sys_path:
    - `/usr/lib/python36.zip`
    - `/usr/lib/python3.6`
    - `/usr/lib/python3.6/lib-dynload`
    - `/home/matbc92/.local/lib/python3.6/site-packages`
    - `/usr/local/lib/python3.6/dist-packages`
    - `/usr/lib/python3/dist-packages`

##### Known environments


 - <Environment: 3.7.2 in /home/linuxbrew/.linuxbrew/bin/../Cellar/python/3.7.2_2> (/home/linuxbrew/.linuxbrew/bin/python3.7)

 - <SameEnvironment: 3.6.7 in /usr> (/usr/bin/python3.6)

 - <Environment: 2.7.15 in /usr> (/usr/bin/python2.7)



##### Settings


```
g:jedi#goto_assignments_command = ',a' (default: '<leader>g')
g:jedi#usages_command = ',o' (default: '<leader>n')
g:jedi#goto_command = ',d' (default: '<leader>d')
g:jedi#completions_enabled = 0 (default: 1)

  omnifunc=htmlcomplete#CompleteTags
	Last set from /usr/share/nvim/runtime/ftplugin/html.vim
  completeopt=menu,preview,noinsert
	Last set from ~/.config/nvim/init.vim
```

health#vimtex#check
========================================================================
## vimtex
  - OK: Vim version should have full support!
  - WARNING: bibtex is not executable, so bibtex completions are disabled.
  - ERROR: Selected viewer is not executable!
    - ADVICE:
      - - Selection: evince
  - ERROR: |g:vimtex_compiler_method| (`latexmk`) is not executable!

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=^H
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $XTERM_VERSION=''
  - INFO: $VTE_VERSION=''
  - INFO: $TERM_PROGRAM=''
  - INFO: $COLORTERM=''
  - INFO: $SSH_TTY=''

health#provider#check
========================================================================
## Clipboard (optional)
  - WARNING: No clipboard tool found. Clipboard registers (`"+` and `"*`) will not work.
    - ADVICE:
      - :help |clipboard|

## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.3.2
  - OK: Latest python2-neovim is installed: 0.3.1

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3.6 in the environment.
  - INFO: Executable: /usr/bin/python3.6
  - INFO: Python3 version: 3.6.7
  - INFO: python3.6-neovim version: 0.3.2
  - OK: Latest python3.6-neovim is installed: 0.3.1

## Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

## Node provider (optional)
  - WARNING: `node` and `npm` must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` commands work.


```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
call plug#begin()
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'Shougo/context_filetype.vim'
Plug 'zchee/deoplete-jedi', { 'do': ':UpdateRemotePlugins' }
Plug 'davidhalter/jedi-vim'
Plug 'sheerun/vim-polyglot'
Plug 'mileszs/ack.vim'
Plug 'fisadev/vim-isort'
Plug 'mhinz/vim-signify'
Plug 'neomake/neomake'
Plug 'vim-airline/vim-airline'
call plug#end()        
set completeopt+=noinsert
set completeopt-=preview
set wildmode=list:longest
autocmd! BufWritePost * Neomake
let g:neomake_python_python_maker = neomake#makers#ft#python#python()
let g:neomake_python_flake8_maker = neomake#makers#ft#python#flake8()
let g:neomake_python_python_maker.exe = 'python3 -m py_compile'
let g:neomake_python_flake8_maker.exe = 'python3 -m flake8'
call neomake#configure#automake('nrw')
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
let g:context_filetype#same_filetypes = {}
let g:context_filetype#same_filetypes._ = '_'
let g:jedi#completions_enabled = 0
let g:signify_vcs_list = [ 'git', 'hg' ]
highlight DiffAdd           cterm=bold ctermbg=none ctermfg=119
highlight DiffDelete        cterm=bold ctermbg=none ctermfg=167
highlight DiffChange        cterm=bold ctermbg=none ctermfg=227
highlight SignifySignAdd    cterm=bold ctermbg=237  ctermfg=119
highlight SignifySignDelete cterm=bold ctermbg=237  ctermfg=167
highlight SignifySignChange cterm=bold ctermbg=237  ctermfg=227
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Install properly all the plugins and their respective dependencies into a WSL bash
 2. Run a file that should trigger said plguins

## Screenshot (if possible)
![image](https://user-images.githubusercontent.com/15231830/54251546-5b0a8280-4526-11e9-8881-e98e7914c62d.png)

sorry for the messy post the first time

**Comment by Shougo** [comment]
Unfortunately I cannot help you.

But other people may help you.

You should provide more minimal init.vim.
And please don't ignore the issue template.

**Comment by Shougo** [comment]
If you ignore the issue tem, I can close your issue.

**Comment by matbc92** [comment]
as requested, this should be the more streamlined init.vim, I think those are the most pertinent plugins and configs, although as I do not know what is causing the issue I was a bit worried of hiding something to find out  that it was the thing causing the problem all along
```set nocompatible
call plug#begin()


" Async autocompletion
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
" Completion from other opened files
Plug 'Shougo/context_filetype.vim'
" Python autocompletion
Plug 'zchee/deoplete-jedi', { 'do': ':UpdateRemotePlugins' }
" Just to add the python go-to-definition and similar features, autocompletion
" from this plugin is disabled
Plug 'davidhalter/jedi-vim'


" Better language packs
Plug 'sheerun/vim-polyglot'


" Linters
Plug 'neomake/neomake'
call plug#end()        
"--------------------------fisa plugins configuration-----------------------
" needed so deoplete can auto select the first suggestion
set completeopt+=noinsert
" comment this line to enable autocompletion preview window
" (displays documentation related to the selected completion option)
set completeopt-=preview
set wildmode=list:longest
" autocompletion of files and commands behaves like shell
" (complete only the common part, list the options that match)
" Run linter on write
autocmd! BufWritePost * Neomake

" Check code as python3 by default
let g:neomake_python_python_maker = neomake#makers#ft#python#python()
let g:neomake_python_flake8_maker = neomake#makers#ft#python#flake8()
let g:neomake_python_python_maker.exe = 'python3 -m py_compile'
let g:neomake_python_flake8_maker.exe = 'python3 -m flake8'
call neomake#configure#automake('nrw')

" Deoplete -----------------------------

" Use deoplete.

let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_ignore_case = 1
let g:deoplete#enable_smart_case = 1
" complete with words from any opened file
let g:context_filetype#same_filetypes = {}
let g:context_filetype#same_filetypes._ = '_'

" Jedi-vim ------------------------------

" Disable autocompletion (using deoplete instead)
let g:jedi#completions_enabled = 0

" All these mappings work only for python code:
" Go to definition
let g:jedi#goto_command = ',d'
" Find ocurrences
let g:jedi#usages_command = ',o'
" Find assignments
let g:jedi#goto_assignments_command = ',a'
" Go to definition in new tab
"nmap ,D :tab split<CR>:call jedi#goto()<CR>

```

**Comment by Shougo** [comment]
Please upload :checkhealth result.
It is required.

**Comment by Shougo** [comment]
Please upload the log file.

```
       $ export NVIM_PYTHON_LOG_FILE=/tmp/log
       $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
       $ neovim
       ... Use deoplete
       $ cat /tmp/log_{PID}
```

```vim
       call deoplete#custom#option('profile', v:true)
       call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

**Comment by matbc92** [comment]
Sorry for the delay, I've been away from this system for a while.
So, I did not understand the instructions correctly, I've tried to do as instructed, when I was to do the last step, the only log files that were on the tmp directory were named log_py2_script, log_py3_script, log_py3_rplugin, and I'm not able to upload them, because their file types are not supported.
And for my misunderstanding of the instructions, I think my biggest problem is at step 3 once neovim is opened, am I suppose to input those commands in vim command mode, or write them in the file and save it somewhere or just quit the buffer when I'm done. I'm really sorry, for the nuisance.

**Comment by Shougo** [comment]
> So, I did not understand the instructions correctly, I've tried to do as instructed, when I was to do the last step, the only log files that were on the tmp directory were named log_py2_script, log_py3_script, log_py3_rplugin, and I'm not able to upload them, because their file types are not supported.

You can upload them in gist.

> if I am to replace PID with something

You need to replace `{PID}` to neovim's PID.

**Comment by Shougo** [comment]
> am I suppose to input those commands in vim command mode, or write them in the file and save it somewhere or just quit the buffer when I'm done

```
       $ export NVIM_PYTHON_LOG_FILE=/tmp/log
       $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
       $ neovim
       ... Use deoplete
       $ cat /tmp/log_{PID}
```

It must be executed from shell.

```
 call deoplete#custom#option('profile', v:true)
 call deoplete#enable_logging('DEBUG', 'deoplete.log')
```

Please write it in your vimrc and upload `deoplete.log`.

**Comment by matbc92** [comment]
Something weird happened when doing step 3 of the instructions 
![image](https://user-images.githubusercontent.com/15231830/55120348-64721e00-50d4-11e9-8ffa-84517b3c2112.png)
and after the last step too
![image](https://user-images.githubusercontent.com/15231830/55120664-a780c100-50d5-11e9-82bc-7f3e750a7718.png)

but here is the deoplete log
[deoplete.log](https://github.com/Shougo/deoplete.nvim/files/3015735/deoplete.log)

**Comment by Shougo** [comment]
Oh.  I think your Python does not support UTF-8.
I don't know why.

You should check your environment is UTF-8.

**Comment by Shougo** [comment]
Your encoding system seems ASCII instead of UTF-8.
It does not work.

**Comment by Shougo** [comment]
I think

```
$ sudo update-locale LANG=en_US.UTF-8
```

is needed.

**Comment by matbc92** [comment]
> I think
> 
> ```
> $ sudo update-locale LANG=en_US.UTF-8
> ```
> is needed.

This seems to have not worked
![image](https://user-images.githubusercontent.com/15231830/55127303-719c0680-50ee-11e9-8dde-96c6302cb67d.png)
and deoplete does not seem to be working properly either

**Comment by Shougo** [comment]
Please restart WSL and check `$LANG` value.

**Comment by matbc92** [comment]
How do i do that, just typing LANG in the terminal didn't work
![image](https://user-images.githubusercontent.com/15231830/55206004-cf465680-51b3-11e9-95e4-b36348af5da2.png)

**Comment by Shougo** [comment]
`echo $LANG`

**Comment by matbc92** [comment]
It sais ```en_US.UTF-8```

**Comment by Shougo** [comment]
OK.  Please test deoplete again.

**Comment by matbc92** [comment]
same as before, the suggestions still do not show

**Comment by Shougo** [comment]
I have tested deoplete in WSL environment.
It works both Vim8 and neovim.

my `$LANG` is `C.UTF-8`.

Closing.

**Comment by Shougo** [comment]
Ah, OK.

I get the reason.

```
## Python 2 provider (optional)
  - INFO: `g:python_host_prog` is not set.  Searching for python2 in the environment.
  - INFO: Executable: /usr/bin/python2
  - INFO: Python2 version: 2.7.15
  - INFO: python2-neovim version: 0.3.2
  - OK: Latest python2-neovim is installed: 0.3.1
```

Please remove `pynvim` package in Python2.

**Comment by matbc92** [comment]
I tried doing that, does not seem to have worked.
I did that with the commands 
```pip2 uninstall pynvim``` and ````pip2 uninstall neovim```
this weird thing is still happening 
![image](https://user-images.githubusercontent.com/15231830/55684716-eeb45080-5924-11e9-897f-e19a45ab67f6.png)

**Comment by Shougo** [comment]
Please read the log.
Python 2.7 environment is loaded.  I don't know why though.
It is not deoplete problem.

It works on my environment.
