### ISSUE TITLE
same issue as neocomplete,but which has been fixed.

### ISSUE THREAD

**Issue by wsdjeg** [Shougo/deoplete.nvim#95]
https://github.com/Shougo/neocomplete.vim/issues/501
will you support fuzzy match after dot?

**Comment by Shougo** [comment]
Already implemented.
https://github.com/Shougo/deoplete.nvim/commit/2f1194a719f623398bc65a2752e47e1b6f5dc4dd

**Comment by wsdjeg** [comment]
something wrong with me 
![2015-12-09 21-47-33](https://cloud.githubusercontent.com/assets/13142418/11686886/8ab1474c-9ebe-11e5-84f5-6acda4ff55c3.png)
![2015-12-09 21-47-38](https://cloud.githubusercontent.com/assets/13142418/11686885/8ab0789e-9ebe-11e5-9536-61ee09abbe37.png)
![2015-12-09 21-47-42](https://cloud.githubusercontent.com/assets/13142418/11686887/8ab40ce8-9ebe-11e5-8f9a-25e13f7a9517.png)

**Comment by wsdjeg** [comment]
sorry fixed ,it is my fault i hava forced omni

**Comment by Shougo** [comment]
@wsdjeg You must use `g:deoplete#omni#input_patterns` instead of `g:deoplete#omni_patterns`.

**Comment by wsdjeg** [comment]
ok let me read doc more times ,i think it is better way to use a plugin ,rather than open a lot of issue
