### ISSUE TITLE
[Request] Support for pum for command line in NeoVim

### ISSUE THREAD

**Issue by ratheesh** [Shougo/deoplete.nvim#951]
patch for `pum` support in `wildoptions` is merged into neovim master branch yesterday by @bfredl.
It will be nice if deoplete support is extended to command mode.

**Comment by Shougo** [comment]
Hm...  It is possible?
I will test it later.

**Comment by Shougo** [comment]
Hm...  I think more options are needed to support.

`completeopt`: `noinsert`, `noselect` feature is needed for command line.

**Comment by Shougo** [comment]
And `get current command line completion mode` API is needed.
Because, if the completion mode is empty, it should be disabled.

**Comment by Shougo** [comment]
https://github.com/Shougo/deoplete.nvim/pull/952

I have created the PR for it.

**Comment by Shougo** [comment]
`feedkeys()` does not call cmdline popup menu.
I don't know why.

**Comment by Shougo** [comment]
Please use wilder instead.
https://github.com/gelguy/wilder.nvim

**Comment by Shougo** [comment]
I will add the feature in ddc.vim.

https://github.com/Shougo/ddc.vim/pull/59#issuecomment-932722841

**Comment by Shougo** [comment]
I have merged it.
