### ISSUE TITLE
Floating Windows Support From Neovim

### ISSUE THREAD

**Issue by ciknight** [Shougo/deoplete.nvim#959]
Neovim has a working version of floating windows implementation now.
Is it possible to add floating window?

**Comment by Shougo** [comment]
Please use float-preview.nvim instead.

https://github.com/ncm2/float-preview.nvim

**Comment by mikekreeki** [comment]
Wouldn't it be cool to use floating window instead of regular pmenu for completion options given its ability to produce much nicer UI as pmenu highlighting options are kinda limited. Or this is a no-go given deoplete aims to support regular vim as well?

**Comment by Shougo** [comment]
If you can implement the feature, please do it
