### ISSUE TITLE
`call deoplete#custom#option('deoplete-options-max_list': 5)` has no effect

### ISSUE THREAD

**Issue by mrbig033** [Shougo/deoplete.nvim#962]
# Problems summary

`call deoplete#custom#option('deoplete-options-max_list': 5)` has no effect, as I keep getting a lot more than this number of candidates.

## Expected

Deoplete should only give up to a maximum of 5 candidates.

#### Environment Information ####

 * deoplete version (SHA1):

 * OS: MX-Linux 18

 * neovim/Vim `:version` output:

```
:version
NVIM v0.4.0-429-gf282324e1
Build type: RelWithDebInfo
LuaJIT 2.0.5
Compilation: /usr/bin/cc -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wvla -fstack-
protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/dave/maps/neovim/build/
config -I/home/dave/maps/neovim/src -I/home/dave/maps/neovim/.deps/usr/include -I/usr/include -I/home/dave/maps/neovim/build/src/nvim/auto -I/home/dave/maps/neovim/build/include
Compiled by dave@perk

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info
Press ENTER or type command to continue
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo
    LuaJIT

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='4601'
  - INFO: $COLORTERM='truecolor'

## tmux
  - OK: escape-time: 0ms
  - INFO: $TERM: tmux-256color

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xclip

## Python 2 provider (optional)
  - INFO: pyenv: Path: /home/dave/.pyenv/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/dave/.pyenv
  - INFO: Using: g:python_host_prog = "/usr/bin/python2.7"
  - INFO: Executable: /usr/bin/python2.7
  - INFO: Python version: 2.7.13
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: pyenv: Path: /home/dave/.pyenv/libexec/pyenv
  - INFO: pyenv: $PYENV_ROOT is not set. Infer from `pyenv root`.
  - INFO: pyenv: Root: /home/dave/.pyenv
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /home/dave/.pyenv/versions/3.7.2/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - WARNING: `node` and `npm` (or `yarn`) must be in $PATH.
    - ADVICE:
      - Install Node.js and verify that `node` and `npm` (or `yarn`) commands work.
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```
call plug#begin('~/.config/nvim/plugins/plugged')
if has('nvim')
  Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
  Plug 'Shougo/deoplete.nvim'
  Plug 'roxma/nvim-yarp'
  Plug 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1
```

- [~/.config/nvim](https://github.com/mrbig033/dotfiles/tree/master/nvim)

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Start neovim
 2. Try a few popular keywords
 3. Check how many candidates you get (tested with [gdscript3](https://github.com/calviken/vim-gdscript3), Vim file and shell filetypes)

## Screenshot (if possible)

This is with the option `call deoplete#custom#option({'deoplete-options-max_list': 5})` in my init:

![deoplete](https://user-images.githubusercontent.com/36245777/55857818-86dc5080-5b44-11e9-81fa-5899dd8361ea.png)

**Comment by Shougo** [comment]
It must be:

```vim
call deoplete#custom#option({'max_list': 5})
```

And you should set `pumheight` option.

**Comment by mrbig033** [comment]
Thanks... but I gotta say, man, this syntax is definitely unclear in the documentation.

And there's also no mention of `pumheight` in it, so I have no idea what you mean by `And you should set pumheight option`.

**Comment by Shougo** [comment]
You should read Vim documentation.
:help pumheight

**Comment by mrbig033** [comment]
Vim documentation is big, it's unreasonable to expect a regular human being to read it in its entirety. There's no way I could guess that `pumheight` is a Vim option and not an undocumented Deoplete feature.

**Comment by roxma** [comment]
> Vim documentation is huge, it's unreasonable to expect a regular human being to read it in its entirety. 

It not that much to read. Just `:help ins-completion` you'll get most of info you need on builtin completion. It is part of vim's reference doc `insert.txt`. It should not be really hard to find.

It's reasonable for plugins to assume that users who need customization are already familiar with vim's builtin feature. Builtin features are mostly useful, even with auto completion plugin I still need bulitin completion from time to time.

**Comment by mrbig033** [comment]
Even if I read 600 pages of manuals, very little will stay in my memory. I've been successfully using Vim for the past two years, I have a long configuration made from scratch and, still, there are huge knowledge gaps in that area. I also have a 4000+ Emacs configuration, also made from scratch... so yeah, I'm used to following instructions. I know this is a voluntary effort, but I'd like to kindly suggest adding all the pointers made in this post to the documentation in a clear manner.

**Comment by Shougo** [comment]
If you can improve the documentation, the PR is wellcome.

**Comment by mrbig033** [comment]
I'll try doing that in the coming days.
