### ISSUE TITLE
[question] how do I make meta+character work when auto-complete popup is open?

### ISSUE THREAD

**Issue by dikeert** [Shougo/deoplete.nvim#963]
# Problems summary
I have the autocomplete popup open. I want to press Alt+j to go to the next line but I can't - instead of movement I get popup closed and "j" symbol inserted.
Alt+: works as expected though.

## Expected
Popup closes, nvim switches to normal mode and cursor moves to the next line

## Environment Information

 * deoplete version (SHA1):

 * OS: linux

 * neovim/Vim `:version` output:

NVIM v0.3.4                                                                                                                                                            
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unu
sed-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS
 -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/b
uild/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

## `:checkhealth` or `:CheckHealth` result(neovim only):

**health#LanguageClient#check**

  - OK: binary found: /home/aner/.cache/dein/repos/github.com/autozimu/LanguageClient-neovim/bin/languageclient
  - OK: languageclient 0.1.141 

**health#denite#check**

**### denite.nvim**
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

**health#deoplete#check**

### deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

**health#nvim#check**

### Configuration
  - OK: no issues found

### Performance
  - OK: Build type: Release

### Remote Plugins
  - OK: Up to date

### terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $VTE_VERSION='5402'
  - INFO: $COLORTERM='truecolor'

**health#provider#check**

### Clipboard (optional)
  - OK: Clipboard tool found: wl-copy

### Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

### Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

### Ruby provider (optional)
  - WARNING: `ruby` and `gem` must be in $PATH.
    - ADVICE:
      - Install Ruby and verify that `ruby` and `gem` commands work.

### Node.js provider (optional)
  - INFO: Node.js: v11.11.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
" Your minimal init.vim/vimrc
" {{{ Deoplete
		let g:deoplete#enable_at_startup = 1
		set completeopt-=preview
		set completeopt+=noinsert

		call deoplete#custom#source('go', 'rank', 1000)
		call deoplete#custom#source('_', 'disabled_syntaxes', ['Comment', 'String'])

		let g:deoplete#ignore_sources = {}
		let g:deoplete#ignore_sources._ = ['buffer']

		let b:deoplete_disable_auto_complete=1
		let g:deoplete_disable_auto_complete=1
		let g:deoplete#sources = {}
	" }}}
```

**Comment by Shougo** [comment]
> Popup closes, nvim switches to normal mode and cursor moves to the next line

Really???

```vim
inoremap <expr><A-j>  pumvisible()? "\<C-y>\<ESC>j" : ""
```

This is not question site.  You should ask it in other places.

**Comment by dikeert** [comment]
@Shougo that doesn't help really. It basically means that I have to re-map the whole keyboard to achieve the standard vim behavior. Doesn't seem right. Why <A-:> works and <A-y>? Is there a more generic approach?

**Comment by Shougo** [comment]
> Why <A-:> works and <A-y> doesn't? Is there a more generic approach?

I don't know.  Because, deoplete does not change any mappings.
You should know `this is deoplete's issues`.
Please ask it in other places.

**Comment by Shougo** [comment]
I think it is Vim/neovim features.

**Comment by dikeert** [comment]
> Because, Vim/neovim has internal popup menu mode.
> It is different from Insert mode.

That one explains it, thank you very much!
