### ISSUE TITLE
And probably yet another one moron who can't figure out what's the reason for not working...

### ISSUE THREAD

**Issue by denisvolin** [Shougo/deoplete.nvim#964]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Well, as the title states that, I'm yet another moron who cannot figure out how to make deoplete.nvim work. It's just that if I'm starting to edit a .go file there's no autocompete in action in real time, yet: Ctrl+x, Ctrl+o, Ctrl+o sequence brings the desirable outcome.

The system installation details are downbelow, the distribution is one of the locally recommended for the country, you may probably never heard of that one (using the Google Translate, since they don't have English version): https://translate.google.com/translate?sl=ru&tl=en&u=https%3A%2F%2Fwww.basealt.ru%2Fproducts%2Falt-workstation%2Fk-82%2F

python version installed 3.5.4
pynvim version installed 0.3.2

nvim --version
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -pipe -frecord-gcc-switches -Wall -g -O2 -Wconversion -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/usr/src/RPM/BUILD/neovim-0.3.4/BUILD/config -I/usr/src/RPM/BUILD/neovim-0.3.4/src -I/usr/include -I/usr/src/RPM/BUILD/neovim-0.3.4/BUILD/src/nvim/auto -I/usr/src/RPM/BUILD/neovim-0.3.4/BUILD/include

init.vim as is, I've got nothing to hide (well, except the email address):
«
```
" NEOVIM (NOT VIM) CONFIGURATION

" sets line numbers on
set number

" sets truecolor mode on
set termguicolors

" sets to use default clipboard
set clipboard+=unnamedplus

" setups the cyrillic keyboard usage, switching the locale with Ctrl+^
" as of: https://m.habr.com/ru/post/98393
set keymap=russian-jcukenwin
set iminsert=0
set imsearch=0
highligh lCursor guifg=NONE guibg=Cyan


" VIM-PLUG PLUGIN SETUP
call plug#begin('~/.local/share/nvim/plugged')
	" vim-go
	Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

	" license-to-vim
	Plug 'ararslan/license-to-vim'

	" gocode: completion
	Plug 'stamblerre/gocode', { 'rtp': 'nvim', 'do': '~/.config/nvim/plugged/gocode/nvim/symlink.sh' }
	Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
	Plug 'deoplete-plugins/deoplete-go', { 'do': 'make'}

	" tagbar: source code navigation
	Plug 'majutsushi/tagbar'
	
	" neosnippet
	Plug 'Shougo/neosnippet.vim'

	" vim-godebug: delve integration
	Plug 'jodosha/vim-godebug'

	" ctrlp.vim interactive :GoDecls and :GoDeclsDir
	Plug 'ctrlpvim/ctrlp.vim'

	" vimagit: git assist and diff visualization
	Plug 'jreybert/vimagit'

	" vim-gitgutter: sidebar diff markers
	Plug 'airblade/vim-gitgutter', {'do': ':GitGutterEnable' }

	" solarized theme
	Plug 'altercation/vim-colors-solarized'

	" papercolor theme
	Plug 'NLKNguyen/papercolor-theme'

	" night-and-day: theme switcher (scheduler)
	Plug 'nightsense/night-and-day'
	
	" vim-airline: git status bar line
	Plug 'vim-airline/vim-airline'

	" vim-airline-themes
	Plug 'vim-airline/vim-airline-themes'
call plug#end()
	
" plugin related settings
"
" license-to-vim:
let g:license_author = 'Denis Volin'
let g:license_email = '<removed to avoid spam>'

" night-and-day sunrise/sunset related switching:
let g:nd_themes = [
 \ ['sunrise+0',   'papercolor', 	'light' ],
 \ ['sunrise+1/2', 'solarized', 	'light' ],
 \ ['sunrise+3/4',    'evening',        'dark'  ],
 \ ['sunset+0',    'default',        'dark'  ],
 \ ]

 let g:nd_latitude = '55'
" usage: :call NdSchedule() and choose the proper time shift in minutes to
" current latitude
" let g:nd_timeshift = '74'

" activate airline theme switching with night-and-day
 let g:nd_airline = 1

" competion related:
set completeopt+=noinsert
set completeopt+=noselect

let g:python3_host_prog  = '/usr/bin/python3'

let g:deoplete#enable_at_startup = 1
let g:deoplete#sources#go#gocode_binary = $GOPATH.'/bin/gocode'
let g:deoplete#sources#go#pointer = 1
let g:deoplete#sources#go#cgo = 1
let g:deoplete#sources#go#cgo#libclang_path = '/usr/lib64/libclang.so'
let g:deoplete#sources#go#builtin_objects = 1
let g:deoplete#sources#go#unimported_packages = 1
```
»

Well, I hope, you can help me figure out this issue =)

With my kindest and sincere regards,
Volin, Denis

**Comment by denisvolin** [comment]
Ehm, yeah, I'm not good with whole this issue submitting things, sorry, if it looks ugly as hell.

**Comment by Shougo** [comment]
> python version installed 3.5.4

It does not work.

Please read deoplete requirements.

```
Note: deoplete requires Neovim (0.3.0+) or Vim8 (latest is recommended) with
Python3.6.1+ and |+timers| enabled.
```
