### ISSUE TITLE
Integration with vim-go and gopls

### ISSUE THREAD

**Issue by velovix** [Shougo/deoplete.nvim#965]
# Problems summary

Historically, in order to get Deoplete support in a vim-go environment, one would install the deoplete-go plugin. This plugin works with gocode to provide completion results. However, recently vim-go has added first-class support for using gopls, a Go language server, to provide completion results directly to Omni. Vim-go sets the `omnifunc` variable to `go#complete#Complete` in order to do this, but these results don't appear automatically alongside the basic word suggestion results. Is a special layer like deoplete-go still necessary to make this work?

## Expected

Considering the following Go program:

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello!")
    fmt.<>
}
```

Where "<>" is the cursor position, I would expect to see smart completion results from gopls but I only see the basic word suggestion results. If I press Ctrl+X then Ctrl+O manually, I see the smart completion results.

## Environment Information

 * deoplete version (SHA1): 0e63fb738acdfa7013bb229c0dbcd576c32e2083

 * OS: Arch Linux

 * neovim/Vim `:version` output:

```
NVIM v0.3.4
Build type: Release
LuaJIT 2.0.5
Compilation: /usr/bin/cc -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong -fno-plt -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/build/neovim/src/build/config -I/build/neovim/src/neovim-0.3.4/src -I/usr/include -I/build/neovim/src/build/src/nvim/auto -I/build/neovim/src/build/include
Compiled by builduser

Features: +acl +iconv +jemalloc +tui 
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"
```

 * `:checkhealth` or `:CheckHealth` result(neovim only):

```

health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.5+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: Release

## Remote Plugins
  - OK: Up to date

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='truecolor'

health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help |provider-python|
          /usr/bin/python2.7 does not have the "neovim" module. :help |provider-python|
          python2.6 not found in search path or not executable.
          /usr/bin/python is Python 3.7 and cannot provide Python 2.
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Multiple python3 executables found.  Set `g:python3_host_prog` to avoid surprises.
  - INFO: Executable: /usr/bin/python3
  - INFO: Other python executable: /bin/python3
  - INFO: Python version: 3.7.3
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v11.13.0
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim
```

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.config/nvim/plugged')

Plug 'fatih/vim-go', { 'branch': 'master' }

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:deoplete#enable_at_startup = 1
let g:deoplete#complete_method = "omnifunc"
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Open a Go file in a project with "fmt" or some other standard library package imported. For example:

```go
package main

import "fmt"

func main() {
    fmt.Println("Hello!")
}
```

 2. In the main function, start typing "fmt.", where you should see no smart completion options
 3. Press Ctrl+X and Ctrl+O to open Omni and see the smart completion options

## Screenshot (if possible)

The completions I see before manually opening Omni:

![2019-4-11_21:14:52](https://user-images.githubusercontent.com/2856634/56011961-0ed66d80-5c9f-11e9-8d52-ad59423db865.png)

The completions I see after opening Omni manually:

![2019-4-11_21:15:25](https://user-images.githubusercontent.com/2856634/56011972-1c8bf300-5c9f-11e9-93ca-acc9121b7a72.png)

## Upload the log file

Unfortunately, my Neovim installation doesn't seem to be generating any log files. Please let me know if logs would be helpful for this question and I'll dig more on this.

**Comment by velovix** [comment]
Just read the health check and figured out what I need to do to get logs, here they are!

[nvim-python.log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/3071534/nvim-python.log_py3_rplugin.txt)

**Comment by taigacute** [comment]
@velovix   look this [issue](https://github.com/fatih/vim-go/issues/2185)

**Comment by Shougo** [comment]
> let g:deoplete#complete_method = "omnifunc"

This option is removed.

**Comment by Shougo** [comment]
You need to set omni_patterns.

```vim
		call deoplete#custom#option('omni_patterns', {
		\ 'go': '[^. *\t]\.\w*',
		\  'html': ['<', '</', '<[^>]*\s[[:alnum:]-]*'],
		\  'xhtml': ['<', '</', '<[^>]*\s[[:alnum:]-]*'],
		\  'xml': ['<', '</', '<[^>]*\s[[:alnum:]-]*'],
		\})
```

**Comment by velovix** [comment]
Works perfectly, thank you very much!
