### ISSUE TITLE
[request] Add register to autocomlete source

### ISSUE THREAD

**Issue by amerov** [Shougo/deoplete.nvim#966]
Example: 
Suggest completion from registers

**Comment by Shougo** [comment]
Why it is useful?
Please describe it.

**Comment by Shougo** [comment]
And I don't want to add default sources anymore.
If it is really useful, it should be separated source.

**Comment by amerov** [comment]
> Why it is useful?
> Please describe it.

yank line 1
yank line n
then I want to paste this lines or text fragments.
I think type :reg then see registers content and remember register's numbers is not very comfortable.

**Comment by amerov** [comment]
Maybe is it can be plugin?

**Comment by Shougo** [comment]
OK.  If so, you should denite.nvim instead.
denite.nvim has register source for it.

Closing.
