### ISSUE TITLE
Deoplete ignores custom `max_info_width`

### ISSUE THREAD

**Issue by sitaktif** [Shougo/deoplete.nvim#968]
# Problems summary

Setting e.g. `deoplete#custom#source('_', 'max_menu_width', 0)` works as expected but setting `deoplete#custom#source('_', 'max_info_width', 0)` is ignored by deoplete.

## Expected

`deoplete#custom#source('_', 'max_info_width', 0)` is taken into account

## Environment Information

 * deoplete version (SHA1): 5c50f254175ee1e815a47761c50abec861afcc61

## Notes

A PR is coming to fix this behaviour.

**Comment by Shougo** [comment]
I have tested the behavior.

Deoplete ignores `max_info_width`, but `max_abbr_width` works perfectly.
So I have changed the title.
