### ISSUE TITLE
Unable to UpdateRemotePlugins

### ISSUE THREAD

**Issue by Redcroft** [Shougo/deoplete.nvim#971]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary
Setup dein and deoplete but unable to run UpdateRemote Plugins due to 
"
Encountered AttributeError loading plugin at /home/redsith/.cache/dein/.cache/init.vim/.dein/rplugin/python3/deoplete: module 'vim' has no attribute 'call'
Traceback (most recent call last):
  File "/home/redsith/.local/lib/python3.7/s
[log_py3_rplugin.txt](https://github.com/Shougo/deoplete.nvim/files/3116571/log_py3_rplugin.txt)

ite-packages/pynvim/plugin/host.py", line 145, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib64/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib64/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
AttributeError: module 'vim' has no attribute 'call'
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/redsith/.local/share/nvim/rplugin.vim
"

## Expected
Deoplete load

## Environment Information

 * deoplete version (SHA1):

 * OS:
OpenSuse Tumbleweed

 * neovim/Vim `:version` output:
NVIM v0.3.4
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -Wconversion -U_FORTIFY_SOUR
CE -D_FORTIFY_SOURCE=1 -O2 -g -DMIN_LOG_LEVEL=3 -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fdi
agnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -I/home/abuild/rpmbuild/BUILD/neovim-0.3.4/build/co
nfig -I/home/abuild/rpmbuild/BUILD/neovim-0.3.4/src -I/usr/include -I/home/abuild/rpmbuild/BUILD/neovim-0.3.4/build/src/nvim/auto -I/home/abuild/rpmbuild/BUILD/neovim-0.3.4/build/include
Compiled by abuild@OBS

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful
  - INFO: If you're still having problems, try the following commands:
    $ export NVIM_PYTHON_LOG_FILE=/tmp/log
    $ export NVIM_PYTHON_LOG_LEVEL=DEBUG
    $ nvim
    $ cat /tmp/log_{PID}
    and then create an issue on github

health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: ".dein" is not registered.
  - WARNING: Out of date
    - ADVICE:
      - Run `:UpdateRemotePlugins`

## terminal
  - INFO: key_backspace (kbs) terminfo entry: key_backspace=\177
  - INFO: key_dc (kdch1) terminfo entry: key_dc=\E[3~
  - INFO: $COLORTERM='1'

## tmux
  - ERROR: escape-time (500) is higher than 300ms
    - ADVICE:
      - Set escape-time in ~/.tmux.conf:
          set-option -sg escape-time 10
      - https://github.com/neovim/neovim/wiki/FAQ
  - INFO: $TERM: screen
  - ERROR: $TERM should be "screen-256color" or "tmux-256color" in tmux. Colors might look wrong.
    - ADVICE:
      - Set default-terminal in ~/.tmux.conf:
          set-option -g default-terminal "screen-256color"
      - https://github.com/neovim/neovim/wiki/FAQ
health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: xsel

## Python 2 provider (optional)
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - ERROR: Python provider error:
    - ADVICE:
      - provider/pythonx: Could not load Python 2:
          /usr/bin/python2 does not have the "neovim" module. :help provider-python
          /usr/bin/python2.7 does not have the "neovim" module. :help provider-python
          python2.6 not found in search path or not executable.
          /usr/bin/python does not have the "neovim" module. :help provider-python
  - INFO: Executable: Not found

## Python 3 provider (optional)
  - INFO: `g:python3_host_prog` is not set.  Searching for python3 in the environment.
  - INFO: Executable: /usr/bin/python3
  - INFO: Python version: 3.7.2
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux-gnu]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help g:ruby_host_prog for non-standard gem installations.

## Node.js provider (optional)
  - INFO: Node.js: v10.15.2
  - WARNING: Missing "neovim" npm (or yarn) package.
    - ADVICE:
      - Run in shell: npm install -g neovim
      - Run in shell (if you use yarn): yarn global add neovim

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)
[init.txt](https://github.com/Shougo/deoplete.nvim/files/3116553/init.txt)

" DEIN:
" curl -s https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh | sh -s ~/.cache/dein

```vim
if &compatible
  set nocompatible               " Be iMproved
endif

" Required:
set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

" Required:
if dein#load_state('~/.cache/dein')
  call dein#begin('~/.cache/dein')

  " Let dein manage dein
  " Required:
  call dein#add('~/.cache/dein/repos/github.com/Shougo/dein.vim')

  " Add or remove your plugins here like this:
  "call dein#add('Shougo/neosnippet.vim')
  "call dein#add('Shougo/neosnippet-snippets')
  call dein#add('Shougo/deoplete.nvim')
  if !has('nvim')
            call dein#add('roxma/nvim-yarp')
              call dein#add('roxma/vim-hug-neovim-rpc')
  endif

  " Required:
  call dein#end()
  call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif


let g:deoplete#enable_at_startup = 1
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Run :UpdateRemotePlugins

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

**Comment by Shougo** [comment]
Unfortunately, I don't reproduce the error.
It should work.

```
Encountered AttributeError loading plugin at /home/redsith/.cache/dein/.cache/init.vim/.dein/rplugin/python3/deoplete: module 'vim' has no attribute 'call'
```

I think your module is broken.
You should remove both `pynvim` and `neovim` modules and reinstall `pynvim`.

You should test it in another machine.

**Comment by Shougo** [comment]
And it is not deoplete's issue.
