### ISSUE TITLE
Random Unintended Completion

### ISSUE THREAD

**Issue by Tacklebox** [Shougo/deoplete.nvim#972]
**Warning:  I will close the issue without the minimal init.vim and the reproduction instructions.**

# Problems summary

Sometimes randomly completion is inserted when I don't want it to be. Only happens sometimes.

## Expected
If I am just typing normally in insert mode, completions should not be inserted.

## Environment Information

 * deoplete version (SHA1): Plug reports ['deoplete.nvim'].commit = '9d4e88f'

 * OS: Ubuntu 18.04

 * neovim/Vim `:version` output:
:version                                                                                                                                                            
NVIM v0.3.4
Build type: Release
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -g -O2 -fdebug-prefix-map=/build/neovim-jXFUbD/neovim-0.3.4=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE
=1 -DDISABLE_LOG -Wdate-time -D_FORTIFY_SOURCE=1 -Wconversion -O2 -DNDEBUG -DMIN_LOG_LEVEL=3 -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wim
plicit-fallthrough -Wvla -fstack-protector-strong -fdiagnostics-color=auto -Wno-array-bounds -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_
UNIBI_HAS_VAR_FROM -I/build/neovim-jXFUbD/neovim-0.3.4/build/config -I/build/neovim-jXFUbD/neovim-0.3.4/src -I/usr/include -I/build/neovim-jXFUbD/neovim-0.3.4/build/src/nvim/
auto -I/build/neovim-jXFUbD/neovim-0.3.4/build/include
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +jemalloc +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

 * `:checkhealth` or `:CheckHealth` result(neovim only):
health#deoplete#check
========================================================================
## deoplete.nvim
  - OK: exists("v:t_list") was successful
  - OK: has("timers") was successful
  - OK: has("python3") was successful
  - OK: Python3.6.1+ was successful

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call plug#begin('~/.local/share/nvim/plugged')
" Complete/Lint/Make
Plug 'w0rp/ale'
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

call plug#end()

let g:ale_completion_enabled = 1

let g:ale_linters = {
\   'rust': ['rls']
\}

let g:ale_rust_rls_toolchain = 'stable'

let g:deoplete#enable_at_startup = 1

syntax on
```

## How to reproduce the problem from neovim/Vim startup (Required!)

Open a file, start typing somewhere and completion will sometimes randomly fill without hitting tab or enter or <C-n>

## Generate a logfile if appropriate

 1. export NVIM_PYTHON_LOG_FILE=/tmp/log
 2. export NVIM_PYTHON_LOG_LEVEL=DEBUG
 3. nvim -u minimal.vimrc
 4. some works
 5. cat /tmp/log_{PID}

## Screenshot (if possible)

This is an example where I type "use" but deoplete added the word "util" as soon as I typed "u" resulting in the word "utilse"

https://asciinema.org/a/M95fg8KL0MIRUckVGz00cUnqH

## Upload the log file
/tmp/log_py3_rplugin
https://pastebin.com/FVUFwjz2

**Comment by Shougo** [comment]
https://github.com/w0rp/ale#2iii-completion

It seems ALE conflicts with deoplete.
I cannot support it.
You should report it in ALE issues.
