### ISSUE TITLE
Fix #973 async updateを適用することで影響を受けます。

### ISSUE THREAD

**Issue by takkii** [Shougo/deoplete.nvim#974]
**警告：最低限のinit.vimと再作成の指示なしで問題を解決します。**

```markdown
問題を要約すると、補完リストが暴走しループに入ります。
できれば修正を元に戻すか、新しい対処を求めます。
```

>再現手順は、Neovim起動→Rubyファイルへ移動→コーディングのためreなどを入力（これで発生）

下記は設定です。

＃問題の要約
https://github.com/takkii/totolot
https://github.com/takkii/totolot/issues/2
https://github.com/takkii/totolot/releases/1.4.0

toml

[[plugins]]
repo = 'takkii/totolot'
rev = 'f1fd021'

#1.4.0も多少は影響を受けるがひどくない。
#1.3.1はHDDが損傷するようなファンの音

[[plugins]]
repo = 'takkii/ruby-dictionary3' 
rev = 'b7db6ee'

##期待される
https://github.com/Shougo/deoplete.nvim/releases
rev = 'd7dcca8'

5.0のときと同じようなHDDが周り続けない動作を求めます。

##環境情報

  * deopleteバージョン：　HEADです。
    Commits on May 13, 2019 
    master branch

  * OS：　LinuxMintで確認しました。Neovim 4.0-devです。

再現性は確保していますので、実際実機で試してみるといいと思います。
危ないときはESCキーで消えるので、発火しないように。

## 50行以下の最小限のinit.vim / vimrcを提供してください（必須！）

```vim
# dein_lazy.toml

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><tab> pumvisible() ? "\<C-n>" :
        \ neosnippet#expandable_or_jumpable() ?
        \    "\<Plug>(neosnippet_expand_or_jump)" : "\<tab>"
'''
on_i = 1

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_i  = 1
on_ft = ['snippet']
depends = ['neosnippet-snippets']
```

https://twitter.com/ShougoMatsu/status/1128240258586275840

Twitterで救いの手を差し伸べてくれました。本来はissuesに上げる予定はなかったのですが、
もし改善されたり、deopleteがよりよい方向へ開発が進んでいくことを私も望んでいます。

**Comment by Shougo** [comment]
Please test the latest version of deoplete.

**Comment by takkii** [comment]
修正ありがとうございます。

```markdown
E15 無効な式です:  s:check_completion_mode()
function deoplete#mapping#_prev_completeの処理中にエラーが検出されました

E117 未知の関数です:  s:check_completion_mode()
function deoplete#mapping#_prev_completeの処理中にエラーが検出されました
```

補完リストは正常になりました。
入力すると、上記エラーが流れてbackspaceできない状態です。

**Comment by Shougo** [comment]
Fixed.
Please use the latest version.

**Comment by takkii** [comment]
Deniteのようなファイルの読み込み時にフリーズはありますが、
Tabで移動できますし、読み込んだ後に補完リストを決定できます。

修正されました。ありがとうございます。
これでクローズします。迅速な対応ありがとうございます。
