### ISSUE TITLE
Multiline omni-pattern

### ISSUE THREAD

**Issue by unclechu** [Shougo/deoplete.nvim#977]
Is there any way to write a regex for multiline omni-pattern?

I have this:
```viml
cal deoplete#custom#option('omni_patterns', {
	\ 'haskell': '\c{-# LANGUAGE [A-Z0-9,\t ]*\([A-Z0-9]*\)',
	\})
```

It works for such scenarios:
```haskell
{-# LANGUAGE DataKinds, TypeFamilies, UndecidableInstances, ScopedTypeVariables #-}
```

But I'm trying different ways to rewrite that regex with no success to cover such case of code style:
```haskell
{-# LANGUAGE DataKinds
           , TypeFamilies
           , UndecidableInstances
           , ScopedTypeVariables
  #-}
```
Or similar, I can't match any line-break.

**Comment by Shougo** [comment]
Sorry.  It is not supported.
