### ISSUE TITLE
I want to determine the candidate for completion by TAB

### ISSUE THREAD

**Issue by nabezokodaikon** [Shougo/deoplete.nvim#989]
# Problems summary
I want to determine the candidate for completion by TAB.

## Expected
A complementary candidate is determined by TAB.

## Environment Information

 * deoplete version (aebaec4adbb65339601063f1ee533eef09220145):

 * OS: Mac

 * neovim: `0.3.7`:

 * `:checkhealth` or `:CheckHealth` result(neovim only): OK

## Provide a minimal init.vim/vimrc with less than 50 lines (Required!)

```vim
call deoplete#custom#option('keyword_patterns', {	
   \ 'denite-filter': '',	
   \})	

call deoplete#custom#source('_',
    \ 'matchers', ['matcher_fuzzy', 'matcher_length'])

call deoplete#custom#option('sources', {
    \ 'scala': ['buffer', 'dictionary', 'LanguageClient'],
    \ 'rust': ['buffer', 'dictionary', 'LanguageClient'],
    \})
   
call deoplete#custom#source('_', 'converters', [
    \ 'converter_remove_paren',
    \ 'converter_remove_overlap',
    \ 'matcher_length',
    \ 'converter_truncate_abbr',
    \ 'converter_truncate_info',
    \ 'converter_truncate_menu',
    \ 'converter_auto_delimiter',
    \])

call deoplete#enable()	

inoremap <expr><CR>  pumvisible() ? deoplete#mappings#close_popup() : "<CR>"
```

## How to reproduce the problem from neovim/Vim startup (Required!)

 1. Make some suggestions and display completions.
 2. Select a completion candidate and type the TAB key
 3. The completion candidate selected with the TAB key is input.

**Comment by Shougo** [comment]
```vim
inoremap <silent><expr> <TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
```
