### ISSUE TITLE
Installing deoplete on Vim

### ISSUE THREAD

**Issue by YuhkiYano** [Shougo/deoplete.nvim#990]
Can we install deoplete on Vim not using package manager plugins such as NeoBundle, Bundle, dein and so on? I would like to install it without the use of package manager as much as possible.

**Comment by Shougo** [comment]
It is possible.

For example:

```vim
set rtp+=~/work/deoplete.nvim/
set rtp+=~/work/nvim-yarp
set rtp+=~/work/vim-hug-neovim-rpc/
let g:deoplete#enable_at_startup = 1
```
