### ISSUE TITLE
Additional Question: Installing deoplete on Native Vim8(#990)

### ISSUE THREAD

**Issue by YuhkiYano** [Shougo/deoplete.nvim#992]
I would like to install deoplete on Vim8. How to write codes in .vimrc?
I don't install neovim. I would like to know how to install it without installing neovim.

**Comment by Shougo** [comment]
It should be asked in other places.
This is not QA site for you.

> I would like to install deoplete on Vim8. How to write codes in .vimrc?
I don't install neovim. I would like to know how to install it without installing neovim.

You don't want to use plugin manager.  OK.
If so, you need to study Vim's `:packadd` behavior.

**Comment by YuhkiYano** [comment]
@Shougo 
Thank you very much for your comment.
OK. I try to study Vim's :packadd.
